ContextLogger2 Logger Daemon Internals: ac_app_context.h File Reference
ac_app_context.h File Reference
Classes
struct ac_Registry
Defines
#define ac_global_Controller ac_Controller(ac_get_global_AppContext())
#define ac_global_LogDb ac_LogDb(ac_get_global_AppContext())
#define ac_global_RcFile ac_RcFile(ac_get_global_AppContext())
#define ac_global_ConfigDb ac_ConfigDb(ac_get_global_AppContext())
#define ac_global_Registry ac_get_Registry(ac_get_global_AppContext())
#define ac_global_Blackboard ac_get_Blackboard(ac_get_global_AppContext())
#define LOGDB_FILE ac_get_logdb_file(ac_get_global_AppContext())
#define LOGDB_DIR ac_get_logdb_dir(ac_get_global_AppContext())
#define LOG_UPLOADS_DIR ac_get_log_uploads_dir(ac_get_global_AppContext())
#define ac_STATIC_GET(key) (cf_RcFile_get_##key(ac_global_RcFile))
#define ac_DYNAMIC_GET(_key) (ConfigDb_get_generic(ac_global_ConfigDb, _key, NULL))
#define ac_DYNAMIC_GET_ERR(_key, _errorpp) (ConfigDb_get_generic(ac_global_ConfigDb, _key, _errorpp))
#define ac_DYNAMIC_SET_ERR(_key, _value, _errorpp) (ConfigDb_set_generic(ac_global_ConfigDb, _key, _value, _errorpp))
Typedefs
typedef struct _ac_AppContext ac_AppContext
Functions
ac_AppContext * ac_get_global_AppContext ()
ac_Registry * ac_get_Registry (ac_AppContext *self)
bb_Blackboard * ac_get_Blackboard (ac_AppContext *self)
const char * ac_get_logdb_file (ac_AppContext *self)
const char * ac_get_logdb_dir (ac_AppContext *self)
const char * ac_get_log_uploads_dir (ac_AppContext *self)
kr_Controller * ac_Controller (ac_AppContext *self)
LogDb * ac_LogDb (ac_AppContext *self)
cf_RcFile * ac_RcFile (ac_AppContext *self)
ConfigDb * ac_ConfigDb (ac_AppContext *self)
Define Documentation
#define ac_DYNAMIC_GET (_key) (ConfigDb_get_generic(ac_global_ConfigDb, _key, NULL))
Definition at line 82 of file ac_app_context.h.
#define ac_DYNAMIC_GET_ERR (_key, _errorpp) (ConfigDb_get_generic(ac_global_ConfigDb, _key, _errorpp))
Definition at line 87 of file ac_app_context.h.
Referenced by f_config_get(), and get_lua_value_wd().
#define ac_DYNAMIC_SET_ERR (_key, _value, _errorpp) (ConfigDb_set_generic(ac_global_ConfigDb, _key, _value, _errorpp))
Definition at line 91 of file ac_app_context.h.
Referenced by f_config_set().
#define ac_global_Blackboard ac_get_Blackboard(ac_get_global_AppContext())
Definition at line 65 of file ac_app_context.h.
Referenced by CUploader::BbRegisterL(), CUploader::BbUnregister(), CObserverAo_NetworkRegistration::GetFlightMode(), CObserverAo_NetworkInfo::GetFlightMode(), CObserverAo_SignalStrength::GetFlightMode(), CFlightModeObserver::HandleFlightMode(), netpos_allowed_update_board(), and uploads_allowed_update_board().
#define ac_global_ConfigDb ac_ConfigDb(ac_get_global_AppContext())
Definition at line 63 of file ac_app_context.h.
#define ac_global_Controller ac_Controller(ac_get_global_AppContext())
Definition at line 60 of file ac_app_context.h.
Referenced by ConfigDb_set_generic(), f_are_uploads_allowed(), f_is_sensor_running(), f_remokon_start(), f_remokon_stop(), f_remokon_timed(), f_sensor_start(), f_sensor_stop(), and f_upload_now().
#define ac_global_LogDb ac_LogDb(ac_get_global_AppContext())
Definition at line 61 of file ac_app_context.h.
Referenced by current_iap_is_cellular(), er_log_base(), er_log_status_string(), f_log_message(), FUNC(), CBatteryObserver::HandleBattery(), CFlightModeObserver::HandleFlightMode(), log_uploads_allowed(), netpos_allowed_update_board(), CActiveLogErrG::RunError(), CActiveLogErr::RunError(), and _rk_Remokon::runTimeout().
#define ac_global_RcFile ac_RcFile(ac_get_global_AppContext())
Definition at line 62 of file ac_app_context.h.
Referenced by f_get_username(), and f_static_get_str().
#define ac_global_Registry ac_get_Registry(ac_get_global_AppContext())
Definition at line 64 of file ac_app_context.h.
Referenced by f_get_upload_time(), CUploader::PosterEvent(), and CUploader::postingFinished().
#define ac_STATIC_GET (key) (cf_RcFile_get_##key(ac_global_RcFile))
Definition at line 78 of file ac_app_context.h.
Referenced by _rk_Remokon::_rk_Remokon(), CUploader::CUploader(), get_config_iap_id(), get_config_username(), log_db_take_snapshot(), and CSensor_smsevent::LogEvent().
#define LOG_UPLOADS_DIR ac_get_log_uploads_dir(ac_get_global_AppContext())
Definition at line 68 of file ac_app_context.h.
Referenced by compress_file(), CUploader::CUploader(), getNextOldLogFile(), and CUploader::TakeSnapshotNowL().
#define LOGDB_DIR ac_get_logdb_dir(ac_get_global_AppContext())
Definition at line 67 of file ac_app_context.h.
Referenced by create_log_db().
#define LOGDB_FILE ac_get_logdb_file(ac_get_global_AppContext())
Definition at line 66 of file ac_app_context.h.
Referenced by create_log_db(), ensure_log_db_created(), log_db_open_session(), log_db_take_snapshot(), and prepare_sql_statements().
Typedef Documentation
typedef struct _ac_AppContext ac_AppContext
Definition at line 32 of file ac_app_context.h.
Function Documentation
ConfigDb* ac_ConfigDb (ac_AppContext * self)
Definition at line 160 of file ac_app_context.cpp.
kr_Controller* ac_Controller (ac_AppContext * self)
Definition at line 142 of file ac_app_context.cpp.
bb_Blackboard* ac_get_Blackboard (ac_AppContext * self)
Definition at line 171 of file ac_app_context.cpp.
Referenced by CObserverAo_NetworkRegistration::BbRegisterL(), CObserverAo_NetworkInfo::BbRegisterL(), CObserverAo_SignalStrength::BbRegisterL(), CObserverAo_NetworkRegistration::BbUnregister(), CObserverAo_NetworkInfo::BbUnregister(), CObserverAo_SignalStrength::BbUnregister(), CSensor_cellpos::ConstructL(), and CSensor_cellid::GetBlackboard().
ac_AppContext* ac_get_global_AppContext ()
Definition at line 137 of file ac_app_context.cpp.
Referenced by cl2GlobalCleanup(), CMainObj::ConstructL(), CCl2appAppUi::ConstructL(), FindContactItemByPhoneNoL(), kr_Controller_new(), and kr_PlatAo_new().
const char* ac_get_log_uploads_dir (ac_AppContext * self)
Definition at line 207 of file ac_app_context.cpp.
const char* ac_get_logdb_dir (ac_AppContext * self)
Definition at line 202 of file ac_app_context.cpp.
const char* ac_get_logdb_file (ac_AppContext * self)
Definition at line 197 of file ac_app_context.cpp.
ac_Registry* ac_get_Registry (ac_AppContext * self)
Definition at line 166 of file ac_app_context.cpp.
LogDb* ac_LogDb (ac_AppContext * self)
Definition at line 148 of file ac_app_context.cpp.
Referenced by CSensor_cellpos::CSensor_cellpos(), CUploader::GetLogDb(), Sensor_tap::GetLogDb(), ClQtEventSensorBase::GetLogDb(), CSensor_smsevent::GetLogDb(), CSensor_music::GetLogDb(), CSensor_httpurl::GetLogDb(), CSensor_cellid::GetLogDb(), CSensor_callstatus::GetLogDb(), CSensor_indicator::HandleRead(), CSensor_inactivity::RunL(), sa_Array_new(), and up_Uploader_new().
cf_RcFile* ac_RcFile (ac_AppContext * self)
Definition at line 154 of file ac_app_context.cpp.
Referenced by get_config_database_dir().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1