ContextLogger2 Logger Daemon Internals: ac_app_context.cpp File Reference
ac_app_context.cpp File Reference
Classes
struct _ac_AppContext
Functions
EXTERN_C ac_AppContext * ac_AppContext_new (GError **error)
static const gchar * get_config_database_dir (ac_AppContext *self)
EXTERN_C void ac_AppContext_set_controller (ac_AppContext *self, kr_Controller *kr)
static void free_config_cache (ac_AppContext *self)
EXTERN_C gboolean ac_AppContext_configure (ac_AppContext *self, GError **error)
EXTERN_C void ac_AppContext_destroy (ac_AppContext *self)
EXTERN_C void ac_set_global_AppContext (ac_AppContext *ac)
EXTERN_C ac_AppContext * ac_get_global_AppContext ()
EXTERN_C kr_Controller * ac_Controller (ac_AppContext *self)
EXTERN_C LogDb * ac_LogDb (ac_AppContext *self)
EXTERN_C cf_RcFile * ac_RcFile (ac_AppContext *self)
EXTERN_C ConfigDb * ac_ConfigDb (ac_AppContext *self)
EXTERN_C ac_Registry * ac_get_Registry (ac_AppContext *self)
EXTERN_C bb_Blackboard * ac_get_Blackboard (ac_AppContext *self)
EXTERN_C up_Uploader * ac_get_Uploader (ac_AppContext *self)
EXTERN_C rk_Remokon * ac_get_Remokon (ac_AppContext *self)
EXTERN_C const char * ac_get_logdb_file (ac_AppContext *self)
EXTERN_C const char * ac_get_logdb_dir (ac_AppContext *self)
EXTERN_C const char * ac_get_log_uploads_dir (ac_AppContext *self)
Variables
static ac_AppContext * iGlobal = NULL
Function Documentation
EXTERN_C gboolean ac_AppContext_configure (ac_AppContext * self, GError ** error)
Definition at line 73 of file ac_app_context.cpp.
References DIR_SEP, free_config_cache(), get_config_database_dir(), gx_error_no_memory, LOGDB_BASENAME, logg, and TRAP_OOM.
Referenced by kr_Controller_new().
EXTERN_C void ac_AppContext_destroy (ac_AppContext * self)
Definition at line 112 of file ac_app_context.cpp.
References bb_Blackboard_destroy(), free_config_cache(), and WHEN_SYMBIAN.
Referenced by ac_AppContext_new(), and cl2GlobalCleanup().
EXTERN_C ac_AppContext* ac_AppContext_new (GError ** error)
Definition at line 35 of file ac_app_context.cpp.
References ac_AppContext_destroy(), bb_Blackboard_new(), and gx_error_no_memory.
Referenced by cl2GlobalInit().
EXTERN_C void ac_AppContext_set_controller (ac_AppContext * self, kr_Controller * kr)
Definition at line 59 of file ac_app_context.cpp.
Referenced by kr_Controller_destroy(), and kr_Controller_new().
EXTERN_C ConfigDb* ac_ConfigDb (ac_AppContext * self)
Definition at line 160 of file ac_app_context.cpp.
EXTERN_C kr_Controller* ac_Controller (ac_AppContext * self)
Definition at line 142 of file ac_app_context.cpp.
EXTERN_C bb_Blackboard* ac_get_Blackboard (ac_AppContext * self)
Definition at line 171 of file ac_app_context.cpp.
Referenced by CObserverAo_NetworkRegistration::BbRegisterL(), CObserverAo_NetworkInfo::BbRegisterL(), CObserverAo_SignalStrength::BbRegisterL(), CObserverAo_NetworkRegistration::BbUnregister(), CObserverAo_NetworkInfo::BbUnregister(), CObserverAo_SignalStrength::BbUnregister(), CSensor_cellpos::ConstructL(), and CSensor_cellid::GetBlackboard().
EXTERN_C ac_AppContext* ac_get_global_AppContext ()
Definition at line 137 of file ac_app_context.cpp.
Referenced by cl2GlobalCleanup(), CMainObj::ConstructL(), CCl2appAppUi::ConstructL(), FindContactItemByPhoneNoL(), kr_Controller_new(), and kr_PlatAo_new().
EXTERN_C const char* ac_get_log_uploads_dir (ac_AppContext * self)
Definition at line 207 of file ac_app_context.cpp.
EXTERN_C const char* ac_get_logdb_dir (ac_AppContext * self)
Definition at line 202 of file ac_app_context.cpp.
EXTERN_C const char* ac_get_logdb_file (ac_AppContext * self)
Definition at line 197 of file ac_app_context.cpp.
EXTERN_C ac_Registry* ac_get_Registry (ac_AppContext * self)
Definition at line 166 of file ac_app_context.cpp.
EXTERN_C rk_Remokon* ac_get_Remokon (ac_AppContext * self)
Definition at line 187 of file ac_app_context.cpp.
Referenced by CSmsTrigger::RunL().
EXTERN_C up_Uploader* ac_get_Uploader (ac_AppContext * self)
Definition at line 177 of file ac_app_context.cpp.
EXTERN_C LogDb* ac_LogDb (ac_AppContext * self)
Definition at line 148 of file ac_app_context.cpp.
Referenced by CSensor_cellpos::CSensor_cellpos(), CUploader::GetLogDb(), Sensor_tap::GetLogDb(), ClQtEventSensorBase::GetLogDb(), CSensor_smsevent::GetLogDb(), CSensor_music::GetLogDb(), CSensor_httpurl::GetLogDb(), CSensor_cellid::GetLogDb(), CSensor_callstatus::GetLogDb(), CSensor_indicator::HandleRead(), CSensor_inactivity::RunL(), sa_Array_new(), and up_Uploader_new().
EXTERN_C cf_RcFile* ac_RcFile (ac_AppContext * self)
Definition at line 154 of file ac_app_context.cpp.
Referenced by get_config_database_dir().
EXTERN_C void ac_set_global_AppContext (ac_AppContext * ac)
Definition at line 128 of file ac_app_context.cpp.
Referenced by cl2GlobalCleanup(), and cl2GlobalInit().
static void free_config_cache (ac_AppContext * self) [static]
Definition at line 66 of file ac_app_context.cpp.
References FREE_Z.
Referenced by ac_AppContext_configure(), and ac_AppContext_destroy().
static const gchar* get_config_database_dir (ac_AppContext * self) [static]
Definition at line 53 of file ac_app_context.cpp.
References ac_RcFile().
Referenced by ac_AppContext_configure().
Variable Documentation
ac_AppContext* iGlobal = NULL [static]
Definition at line 126 of file ac_app_context.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1