ContextLogger2 Logger Daemon Internals: ac_app_context_private.h File Reference
ac_app_context_private.h File Reference
Functions
ac_AppContext * ac_AppContext_new (GError **error)
void ac_AppContext_set_controller (ac_AppContext *self, kr_Controller *kr)
gboolean ac_AppContext_configure (ac_AppContext *self, GError **error)
void ac_AppContext_destroy (ac_AppContext *self)
void ac_set_global_AppContext (ac_AppContext *ac)
Function Documentation
gboolean ac_AppContext_configure (ac_AppContext * self, GError ** error)
Definition at line 73 of file ac_app_context.cpp.
References DIR_SEP, free_config_cache(), get_config_database_dir(), gx_error_no_memory, LOGDB_BASENAME, logg, and TRAP_OOM.
Referenced by kr_Controller_new().
void ac_AppContext_destroy (ac_AppContext * self)
Definition at line 112 of file ac_app_context.cpp.
References bb_Blackboard_destroy(), free_config_cache(), and WHEN_SYMBIAN.
Referenced by ac_AppContext_new(), and cl2GlobalCleanup().
ac_AppContext* ac_AppContext_new (GError ** error)
Definition at line 35 of file ac_app_context.cpp.
References ac_AppContext_destroy(), bb_Blackboard_new(), and gx_error_no_memory.
Referenced by cl2GlobalInit().
void ac_AppContext_set_controller (ac_AppContext * self, kr_Controller * kr)
Definition at line 59 of file ac_app_context.cpp.
Referenced by kr_Controller_destroy(), and kr_Controller_new().
void ac_set_global_AppContext (ac_AppContext * ac)
Definition at line 128 of file ac_app_context.cpp.
Referenced by cl2GlobalCleanup(), and cl2GlobalInit().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1