ContextLogger2 Logger Daemon Internals: alter.c File Reference
alter.c File Reference
Functions
static void renameTableFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void renameTriggerFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
void sqlite3AlterFunctions (sqlite3 *db)
static char * whereTempTriggers (Parse *pParse, Table *pTab)
static void reloadTableSchema (Parse *pParse, Table *pTab, const char *zName)
void sqlite3AlterRenameTable (Parse *pParse, SrcList *pSrc, Token *pName)
void sqlite3AlterFinishAddColumn (Parse *pParse, Token *pColDef)
void sqlite3AlterBeginAddColumn (Parse *pParse, SrcList *pSrc)
Function Documentation
static void reloadTableSchema (Parse * pParse, Table * pTab, const char * zName) [static]
Definition at line 217 of file alter.c.
References Parse::db, Trigger::name, OP_DropTable, OP_DropTrigger, OP_ParseSchema, P4_DYNAMIC, Trigger::pNext, Trigger::pSchema, Table::pSchema, Table::pTrigger, sqlite3GetVdbe(), sqlite3MPrintf(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp4(), whereTempTriggers(), and Table::zName.
Referenced by sqlite3AlterFinishAddColumn(), and sqlite3AlterRenameTable().
static void renameTableFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 40 of file alter.c.
References db, Token::n, sqlite3_context_db_handle(), sqlite3_result_text(), sqlite3_value_text(), sqlite3GetToken(), sqlite3MPrintf(), SQLITE_DYNAMIC, TK_LP, TK_SPACE, TK_USING, and Token::z.
Referenced by sqlite3AlterFunctions().
static void renameTriggerFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 95 of file alter.c.
References db, Token::n, sqlite3_context_db_handle(), sqlite3_result_text(), sqlite3_value_text(), sqlite3GetToken(), sqlite3MPrintf(), SQLITE_DYNAMIC, TK_BEGIN, TK_DOT, TK_FOR, TK_ON, TK_SPACE, TK_WHEN, and Token::z.
Referenced by sqlite3AlterFunctions().
void sqlite3AlterBeginAddColumn (Parse * pParse, SrcList * pSrc)
Definition at line 549 of file alter.c.
References SrcList::a, Table::aCol, sqlite3::aDb, Table::addColOffset, Table::db, Parse::db, db, IsVirtual, sqlite3::mallocFailed, Table::nCol, Table::nRef, Column::pDflt, Parse::pNewTable, Db::pSchema, Table::pSchema, Table::pSelect, sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3DbMallocZero(), sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3GetVdbe(), sqlite3LocateTable(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), Column::zColl, SrcList::SrcList_item::zDatabase, Column::zName, Table::zName, SrcList::SrcList_item::zName, and Column::zType.
Referenced by yy_reduce().
void sqlite3AlterFinishAddColumn (Parse * pParse, Token * pColDef)
Definition at line 433 of file alter.c.
References Table::aCol, sqlite3::aDb, Table::addColOffset, Parse::db, db, Column::isPrimKey, sqlite3::mallocFailed, Token::n, Table::nCol, Parse::nErr, Column::notNull, Expr::op, Column::pDflt, Table::pIndex, Parse::pNewTable, Table::pSchema, reloadTableSchema(), SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3DbFree(), sqlite3DbStrNDup(), sqlite3ErrorMsg(), sqlite3FindTable(), sqlite3MinimumFileFormat(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3ValueFree(), sqlite3ValueFromExpr(), SQLITE_AFF_NONE, SQLITE_ALTER_TABLE, SQLITE_UTF8, TK_NULL, Token::z, Table::zName, and Db::zName.
Referenced by yy_reduce().
void sqlite3AlterFunctions (sqlite3 * db)
Definition at line 166 of file alter.c.
References renameTableFunc(), renameTriggerFunc(), sqlite3CreateFunc(), and SQLITE_UTF8.
Referenced by sqlite3RegisterBuiltinFunctions().
void sqlite3AlterRenameTable (Parse * pParse, SrcList * pSrc, Token * pName)
Definition at line 262 of file alter.c.
References SrcList::a, sqlite3::aDb, Parse::db, db, IsVirtual, sqlite3::mallocFailed, Parse::nMem, SrcList::nSrc, OP_String8, OP_VRename, P4_VTAB, Table::pMod, Module::pModule, Table::pSchema, Table::pSelect, Table::pVtab, reloadTableSchema(), SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3LocateTable(), sqlite3NameFromToken(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3StrNICmp(), sqlite3Utf8CharLen(), sqlite3VdbeAddOp4(), sqlite3ViewGetColumnNames(), SQLITE_ALTER_TABLE, SQLITE_OK, whereTempTriggers(), sqlite3_module::xRename, SrcList::SrcList_item::zDatabase, Table::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
static char* whereTempTriggers (Parse * pParse, Table * pTab) [static]
Definition at line 181 of file alter.c.
References sqlite3::aDb, db, Parse::db, Trigger::name, Trigger::pNext, Trigger::pSchema, Table::pSchema, Db::pSchema, Table::pTrigger, sqlite3DbFree(), and sqlite3MPrintf().
Referenced by reloadTableSchema(), and sqlite3AlterRenameTable().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1