ContextLogger2 Logger Daemon Internals: attach.c File Reference
attach.c File Reference
Functions
static int resolveAttachExpr (NameContext *pName, Expr *pExpr)
static void attachFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void detachFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void codeAttach (Parse *pParse, int type, FuncDef *pFunc, Expr *pAuthArg, Expr *pFilename, Expr *pDbname, Expr *pKey)
void sqlite3Detach (Parse *pParse, Expr *pDbname)
void sqlite3Attach (Parse *pParse, Expr *p, Expr *pDbname, Expr *pKey)
int sqlite3FixInit (DbFixer *pFix, Parse *pParse, int iDb, const char *zType, const Token *pName)
int sqlite3FixSrcList (DbFixer *pFix, SrcList *pList)
int sqlite3FixSelect (DbFixer *pFix, Select *pSelect)
int sqlite3FixExpr (DbFixer *pFix, Expr *pExpr)
int sqlite3FixExprList (DbFixer *pFix, ExprList *pList)
int sqlite3FixTriggerStep (DbFixer *pFix, TriggerStep *pStep)
Function Documentation
static void attachFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 65 of file attach.c.
References sqlite3::aDb, sqlite3::aDbStatic, sqlite3::aLimit, sqlite3::autoCommit, db, sqlite3::dfltJournalMode, sqlite3::dfltLockMode, ENC, Schema::enc, Schema::file_format, sqlite3::mallocFailed, sqlite3::nDb, sqlite3::openFlags, Db::pBt, Db::pSchema, Db::safety_level, sqlite3_context_db_handle(), sqlite3_result_error(), sqlite3_result_error_code(), sqlite3_snprintf(), sqlite3_value_blob(), sqlite3_value_bytes(), sqlite3_value_text(), sqlite3_value_type(), sqlite3BtreeClose(), sqlite3BtreeEnterAll, sqlite3BtreeFactory(), sqlite3BtreeLeaveAll, sqlite3BtreePager(), sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3DbRealloc(), sqlite3DbStrDup(), sqlite3Init(), sqlite3PagerJournalMode(), sqlite3PagerLockingMode(), sqlite3ResetInternalSchema(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3SchemaGet(), sqlite3StrICmp(), SQLITE_BLOB, SQLITE_DEFAULT_CACHE_SIZE, SQLITE_ERROR, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_IOERR_NOMEM, SQLITE_LIMIT_ATTACHED, SQLITE_NOMEM, SQLITE_NULL, SQLITE_OK, SQLITE_OPEN_MAIN_DB, SQLITE_TEXT, and Db::zName.
Referenced by sqlite3Attach().
static void codeAttach (Parse * pParse, int type, FuncDef * pFunc, Expr * pAuthArg, Expr * pFilename, Expr * pDbname, Expr * pKey) [static]
Definition at line 283 of file attach.c.
References Parse::db, db, sqlite3::mallocFailed, FuncDef::nArg, Parse::nErr, OP_Expire, OP_Function, P4_FUNCDEF, NameContext::pParse, resolveAttachExpr(), Expr::span, sqlite3AuthCheck(), sqlite3DbFree(), sqlite3ExprCode(), sqlite3ExprDelete(), sqlite3GetTempRange(), sqlite3GetVdbe(), sqlite3NameFromToken(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp3(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), SQLITE_ATTACH, and SQLITE_OK.
Referenced by sqlite3Attach(), and sqlite3Detach().
static void detachFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 233 of file attach.c.
References sqlite3::aDb, sqlite3::autoCommit, db, sqlite3::nDb, Db::pBt, Db::pSchema, sqlite3_context_db_handle(), sqlite3_result_error(), sqlite3_snprintf(), sqlite3_value_text(), sqlite3BtreeClose(), sqlite3BtreeIsInReadTrans(), sqlite3ResetInternalSchema(), sqlite3StrICmp(), and Db::zName.
Referenced by sqlite3Detach().
static int resolveAttachExpr (NameContext * pName, Expr * pExpr) [static]
Definition at line 37 of file attach.c.
References Expr::op, NameContext::pParse, Expr::span, sqlite3ErrorMsg(), sqlite3ExprIsConstant(), sqlite3ResolveExprNames(), SQLITE_ERROR, SQLITE_OK, TK_ID, and TK_STRING.
Referenced by codeAttach().
void sqlite3Attach (Parse * pParse, Expr * p, Expr * pDbname, Expr * pKey)
Definition at line 376 of file attach.c.
References attachFunc(), codeAttach(), SQLITE_ATTACH, and SQLITE_UTF8.
Referenced by yy_reduce().
void sqlite3Detach (Parse * pParse, Expr * pDbname)
Definition at line 355 of file attach.c.
References codeAttach(), detachFunc(), SQLITE_DETACH, and SQLITE_UTF8.
Referenced by yy_reduce().
int sqlite3FixExpr (DbFixer * pFix, Expr * pExpr)
Definition at line 481 of file attach.c.
References Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, sqlite3FixExpr(), sqlite3FixExprList(), and sqlite3FixSelect().
Referenced by sqlite3FixExpr(), sqlite3FixExprList(), sqlite3FixSelect(), sqlite3FixSrcList(), and sqlite3FixTriggerStep().
int sqlite3FixExprList (DbFixer * pFix, ExprList * pList)
Definition at line 499 of file attach.c.
References ExprList::a, and sqlite3FixExpr().
Referenced by sqlite3FixExpr(), sqlite3FixSelect(), and sqlite3FixTriggerStep().
int sqlite3FixInit (DbFixer * pFix, Parse * pParse, int iDb, const char * zType, const Token * pName)
Definition at line 400 of file attach.c.
References sqlite3::aDb, Parse::db, db, sqlite3::nDb, DbFixer::pName, DbFixer::pParse, DbFixer::zDb, Db::zName, and DbFixer::zType.
Referenced by sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3CreateView(), and sqlite3FinishTrigger().
int sqlite3FixSelect (DbFixer * pFix, Select * pSelect)
Definition at line 460 of file attach.c.
References Select::pEList, Select::pHaving, Select::pPrior, Select::pSrc, Select::pWhere, sqlite3FixExpr(), sqlite3FixExprList(), and sqlite3FixSrcList().
Referenced by sqlite3CreateView(), sqlite3FixExpr(), sqlite3FixSrcList(), and sqlite3FixTriggerStep().
int sqlite3FixSrcList (DbFixer * pFix, SrcList * pList)
Definition at line 433 of file attach.c.
References SrcList::a, Parse::db, DbFixer::pName, DbFixer::pParse, sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3FixExpr(), sqlite3FixSelect(), sqlite3StrICmp(), DbFixer::zDb, and DbFixer::zType.
Referenced by sqlite3BeginTrigger(), sqlite3CreateIndex(), and sqlite3FixSelect().
int sqlite3FixTriggerStep (DbFixer * pFix, TriggerStep * pStep)
Definition at line 516 of file attach.c.
References TriggerStep::pExprList, TriggerStep::pNext, TriggerStep::pSelect, TriggerStep::pWhere, sqlite3FixExpr(), sqlite3FixExprList(), and sqlite3FixSelect().
Referenced by sqlite3FinishTrigger().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1