ContextLogger2 Logger Daemon Internals: auth.c File Reference
auth.c File Reference
Functions
int sqlite3_set_authorizer (sqlite3 *db, int(*xAuth)(void *, int, const char *, const char *, const char *, const char *), void *pArg)
static void sqliteAuthBadReturnCode (Parse *pParse, int rc)
void sqlite3AuthRead (Parse *pParse, Expr *pExpr, Schema *pSchema, SrcList *pTabList)
int sqlite3AuthCheck (Parse *pParse, int code, const char *zArg1, const char *zArg2, const char *zArg3)
void sqlite3AuthContextPush (Parse *pParse, AuthContext *pContext, const char *zContext)
void sqlite3AuthContextPop (AuthContext *pContext)
Function Documentation
int sqlite3_set_authorizer (sqlite3 * db, int(*)(void *, int, const char *, const char *, const char *, const char *) xAuth, void * pArg)
Definition at line 72 of file auth.c.
References sqlite3::mutex, sqlite3::pAuthArg, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ExpirePreparedStatements(), SQLITE_OK, and sqlite3::xAuth.
Referenced by DbObjCmd(), and FUNC().
int sqlite3AuthCheck (Parse * pParse, int code, const char * zArg1, const char * zArg2, const char * zArg3)
Definition at line 175 of file auth.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, IN_DECLARE_VTAB, sqlite3::init, sqlite3::pAuthArg, Parse::rc, sqlite3ErrorMsg(), SQLITE_AUTH, SQLITE_DENY, SQLITE_IGNORE, SQLITE_OK, sqliteAuthBadReturnCode(), sqlite3::xAuth, and Parse::zAuthContext.
Referenced by analyzeOneTable(), codeAttach(), flattenSubquery(), resolveExprStep(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTransaction(), sqlite3BeginTrigger(), sqlite3CommitTransaction(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3Insert(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3RollbackTransaction(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), and sqlite3VtabBeginParse().
void sqlite3AuthContextPop (AuthContext * pContext)
Definition at line 227 of file auth.c.
References AuthContext::pParse, AuthContext::zAuthContext, and Parse::zAuthContext.
Referenced by sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), and sqlite3Update().
void sqlite3AuthContextPush (Parse * pParse, AuthContext * pContext, const char * zContext)
Definition at line 211 of file auth.c.
References AuthContext::pParse, Parse::zAuthContext, and AuthContext::zAuthContext.
Referenced by sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), and sqlite3Update().
void sqlite3AuthRead (Parse * pParse, Expr * pExpr, Schema * pSchema, SrcList * pTabList)
Definition at line 105 of file auth.c.
References SrcList::a, Table::aCol, sqlite3::aDb, Parse::db, Expr::iColumn, SrcList::SrcList_item::iCursor, Table::iPKey, Expr::iTable, Table::nCol, sqlite3::nDb, TriggerStack::newIdx, SrcList::nSrc, TriggerStack::oldIdx, Expr::op, sqlite3::pAuthArg, TriggerStack::pTab, SrcList::SrcList_item::pTab, Parse::rc, sqlite3ErrorMsg(), sqlite3SchemaToIndex(), SQLITE_AUTH, SQLITE_DENY, SQLITE_IGNORE, SQLITE_OK, SQLITE_READ, sqliteAuthBadReturnCode(), TK_COLUMN, TK_NULL, Parse::trigStack, sqlite3::xAuth, Parse::zAuthContext, Table::zName, Db::zName, and Column::zName.
Referenced by lookupName().
static void sqliteAuthBadReturnCode (Parse * pParse, int rc) [static]
Definition at line 89 of file auth.c.
References Parse::rc, sqlite3ErrorMsg(), and SQLITE_ERROR.
Referenced by sqlite3AuthCheck(), and sqlite3AuthRead().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1