ContextLogger2 Logger Daemon Internals: bb_blackboard.h File Reference
bb_blackboard.h File Reference
Classes
struct bb_Board
struct bb_Closure
Typedefs
typedef struct _bb_Blackboard bb_Blackboard
typedef void(* bb_Func)(bb_Blackboard *self, enum bb_DataType dt, gpointer data, int len, gpointer arg)
Enumerations
enum bb_DataType {
bb_dt_flightmode, bb_dt_network_info, bb_dt_cell_id, bb_dt_uploads_allowed,
bb_dt_netpos_allowed
}
Functions
bb_Blackboard * bb_Blackboard_new (GError **error)
void bb_Blackboard_destroy (bb_Blackboard *self)
bb_Board * bb_Blackboard_board (bb_Blackboard *self)
gboolean bb_Blackboard_register (bb_Blackboard *self, enum bb_DataType dt, bb_Closure cb, GError **error)
void bb_Blackboard_unregister (bb_Blackboard *self, bb_Closure cb)
void bb_Blackboard_notify (bb_Blackboard *self, enum bb_DataType dt, gpointer data, int len)
Typedef Documentation
typedef struct _bb_Blackboard bb_Blackboard
Definition at line 18 of file bb_blackboard.h.
typedef void(* bb_Func)(bb_Blackboard *self, enum bb_DataType dt, gpointer data, int len, gpointer arg)
Definition at line 44 of file bb_blackboard.h.
Enumeration Type Documentation
enum bb_DataType
Enumerator:
bb_dt_flightmode
bb_dt_network_info
bb_dt_cell_id
bb_dt_uploads_allowed
bb_dt_netpos_allowed
Definition at line 36 of file bb_blackboard.h.
Function Documentation
bb_Board* bb_Blackboard_board (bb_Blackboard * self)
Definition at line 17 of file bb_blackboard.cpp.
Referenced by CUploader::BbRegisterL(), CSensor_cellpos::ConstructL(), DataChanged(), CObserverAo_NetworkRegistration::GetFlightMode(), CObserverAo_NetworkInfo::GetFlightMode(), CObserverAo_SignalStrength::GetFlightMode(), CFlightModeObserver::HandleFlightMode(), netpos_allowed_update_board(), and uploads_allowed_update_board().
void bb_Blackboard_destroy (bb_Blackboard * self)
Definition at line 41 of file bb_blackboard.cpp.
References Registrant_free().
Referenced by ac_AppContext_destroy().
bb_Blackboard* bb_Blackboard_new (GError ** error)
Definition at line 23 of file bb_blackboard.cpp.
References gx_error_no_memory.
Referenced by ac_AppContext_new().
void bb_Blackboard_notify (bb_Blackboard * self, enum bb_DataType dt, gpointer data, int len)
Definition at line 109 of file bb_blackboard.cpp.
References bb_Closure::arg, Registrant::cb, bb_Closure::changed, and Registrant::dt.
Referenced by CFlightModeObserver::HandleFlightMode(), netpos_allowed_update_board(), and uploads_allowed_update_board().
gboolean bb_Blackboard_register (bb_Blackboard * self, enum bb_DataType dt, bb_Closure cb, GError ** error)
Definition at line 59 of file bb_blackboard.cpp.
References Registrant::cb, Registrant::dt, gx_error_no_memory, Registrant_free(), SET_TRAP_OOM, and UNSET_TRAP_OOM.
Referenced by CObserverAo_NetworkRegistration::BbRegisterL(), CObserverAo_NetworkInfo::BbRegisterL(), CObserverAo_SignalStrength::BbRegisterL(), and CUploader::BbRegisterL().
void bb_Blackboard_unregister (bb_Blackboard * self, bb_Closure cb)
Definition at line 86 of file bb_blackboard.cpp.
References bb_Closure::arg, Registrant::cb, bb_Closure::changed, and Registrant_free().
Referenced by CObserverAo_NetworkRegistration::BbUnregister(), CObserverAo_NetworkInfo::BbUnregister(), CObserverAo_SignalStrength::BbUnregister(), CUploader::BbUnregister(), and CSensor_cellid::Unregister().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1