ContextLogger2 Logger Daemon Internals: bitvec.c File Reference
bitvec.c File Reference
Classes
struct Bitvec
Defines
#define BITVEC_SZ 512
#define BITVEC_USIZE (((BITVEC_SZ-12)/sizeof(Bitvec*))*sizeof(Bitvec*))
#define BITVEC_NCHAR BITVEC_USIZE
#define BITVEC_NBIT (BITVEC_NCHAR*8)
#define BITVEC_NINT (BITVEC_USIZE/4)
#define BITVEC_MXHASH (BITVEC_NINT/2)
#define BITVEC_NPTR (BITVEC_USIZE/sizeof(Bitvec *))
#define BITVEC_HASH(X) (((X)*37)%BITVEC_NINT)
#define SETBIT(V, I) V[I>>3] |= (1<<(I&7))
#define CLEARBIT(V, I) V[I>>3] &= ~(1<<(I&7))
#define TESTBIT(V, I) (V[I>>3]&(1<<(I&7)))!=0
Functions
Bitvec * sqlite3BitvecCreate (u32 iSize)
int sqlite3BitvecTest (Bitvec *p, u32 i)
int sqlite3BitvecSet (Bitvec *p, u32 i)
void sqlite3BitvecClear (Bitvec *p, u32 i)
void sqlite3BitvecDestroy (Bitvec *p)
int sqlite3BitvecBuiltinTest (int sz, int *aOp)
Define Documentation
#define BITVEC_HASH (X) (((X)*37)%BITVEC_NINT)
Definition at line 51 of file bitvec.c.
Referenced by sqlite3BitvecSet(), and sqlite3BitvecTest().
#define BITVEC_MXHASH (BITVEC_NINT/2)
Definition at line 48 of file bitvec.c.
Referenced by sqlite3BitvecSet().
#define BITVEC_NBIT (BITVEC_NCHAR*8)
Definition at line 46 of file bitvec.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTest().
#define BITVEC_NCHAR BITVEC_USIZE
Definition at line 45 of file bitvec.c.
#define BITVEC_NINT (BITVEC_USIZE/4)
Definition at line 47 of file bitvec.c.
Referenced by sqlite3BitvecClear(), sqlite3BitvecSet(), and sqlite3BitvecTest().
#define BITVEC_NPTR (BITVEC_USIZE/sizeof(Bitvec *))
Definition at line 49 of file bitvec.c.
Referenced by sqlite3BitvecDestroy(), and sqlite3BitvecSet().
#define BITVEC_SZ 512
Definition at line 41 of file bitvec.c.
Referenced by sqlite3BitvecCreate().
#define BITVEC_USIZE (((BITVEC_SZ-12)/sizeof(Bitvec*))*sizeof(Bitvec*))
Definition at line 44 of file bitvec.c.
#define CLEARBIT (V, I) V[I>>3] &= ~(1<<(I&7))
Definition at line 236 of file bitvec.c.
Referenced by sqlite3BitvecBuiltinTest().
#define SETBIT (V, I) V[I>>3] |= (1<<(I&7))
Definition at line 235 of file bitvec.c.
Referenced by sqlite3BitvecBuiltinTest().
#define TESTBIT (V, I) (V[I>>3]&(1<<(I&7)))!=0
Definition at line 237 of file bitvec.c.
Referenced by sqlite3BitvecBuiltinTest().
Function Documentation
int sqlite3BitvecBuiltinTest (int sz, int * aOp)
Definition at line 269 of file bitvec.c.
References CLEARBIT, SETBIT, sqlite3_free(), sqlite3_malloc(), sqlite3_randomness(), sqlite3BitvecClear(), sqlite3BitvecCreate(), sqlite3BitvecDestroy(), sqlite3BitvecSet(), sqlite3BitvecTest(), and TESTBIT.
Referenced by sqlite3_test_control().
void sqlite3BitvecClear (Bitvec * p, u32 i)
Definition at line 188 of file bitvec.c.
References Bitvec::aBitmap, Bitvec::aHash, Bitvec::apSub, BITVEC_NBIT, BITVEC_NINT, Bitvec::iDivisor, Bitvec::iSize, Bitvec::nSet, sqlite3BitvecClear(), sqlite3BitvecSet(), and Bitvec::u.
Referenced by sqlite3BitvecBuiltinTest(), sqlite3BitvecClear(), and sqlite3PagerMovepage().
Bitvec* sqlite3BitvecCreate (u32 iSize)
Definition at line 90 of file bitvec.c.
References BITVEC_SZ, Bitvec::iSize, and sqlite3MallocZero().
Referenced by pager_open_journal(), pagerStmtBegin(), sqlite3BitvecBuiltinTest(), sqlite3BitvecSet(), sqlite3PagerBegin(), and sqlite3PagerDontWrite().
void sqlite3BitvecDestroy (Bitvec * p)
Definition at line 217 of file bitvec.c.
References Bitvec::apSub, BITVEC_NPTR, Bitvec::iDivisor, sqlite3_free(), sqlite3BitvecDestroy(), and Bitvec::u.
Referenced by pager_end_transaction(), pager_open_journal(), pager_unlock(), pagerStmtBegin(), sqlite3BitvecBuiltinTest(), sqlite3BitvecDestroy(), sqlite3PagerClose(), and sqlite3PagerStmtCommit().
int sqlite3BitvecSet (Bitvec * p, u32 i)
Definition at line 139 of file bitvec.c.
References Bitvec::aBitmap, Bitvec::aHash, Bitvec::apSub, BITVEC_HASH, BITVEC_MXHASH, BITVEC_NBIT, BITVEC_NINT, BITVEC_NPTR, Bitvec::iDivisor, Bitvec::iSize, Bitvec::nSet, sqlite3BeginBenignMalloc(), sqlite3BitvecCreate(), sqlite3BitvecSet(), sqlite3EndBenignMalloc(), SQLITE_NOMEM, SQLITE_OK, and Bitvec::u.
Referenced by pager_write(), sqlite3BitvecBuiltinTest(), sqlite3BitvecClear(), sqlite3BitvecSet(), sqlite3PagerDontRollback(), and sqlite3PagerDontWrite().
int sqlite3BitvecTest (Bitvec * p, u32 i)
Definition at line 105 of file bitvec.c.
References Bitvec::aBitmap, Bitvec::aHash, Bitvec::apSub, BITVEC_HASH, BITVEC_NBIT, BITVEC_NINT, Bitvec::iDivisor, Bitvec::iSize, sqlite3BitvecTest(), and Bitvec::u.
Referenced by pageInStatement(), sqlite3BitvecBuiltinTest(), sqlite3BitvecTest(), sqlite3PagerAcquire(), sqlite3PagerCommitPhaseOne(), sqlite3PagerDontRollback(), sqlite3PagerMovepage(), and sqlite3PagerWrite().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:57 2011 by Doxygen 1.6.1