ContextLogger2 Logger Daemon Internals: build.c File Reference
build.c File Reference
Classes
struct TableLock
Defines
#define SAVE_SZ (sizeof(Parse) - offsetof(Parse,nVar))
#define STRICMP(x, y)
Functions
void sqlite3BeginParse (Parse *pParse, int explainFlag)
void sqlite3TableLock (Parse *pParse, int iDb, int iTab, u8 isWriteLock, const char *zName)
static void codeTableLocks (Parse *pParse)
void sqlite3FinishCoding (Parse *pParse)
void sqlite3NestedParse (Parse *pParse, const char *zFormat,...)
Table * sqlite3FindTable (sqlite3 *db, const char *zName, const char *zDatabase)
Table * sqlite3LocateTable (Parse *pParse, int isView, const char *zName, const char *zDbase)
Index * sqlite3FindIndex (sqlite3 *db, const char *zName, const char *zDb)
static void freeIndex (Index *p)
static void sqliteDeleteIndex (Index *p)
void sqlite3UnlinkAndDeleteIndex (sqlite3 *db, int iDb, const char *zIdxName)
void sqlite3ResetInternalSchema (sqlite3 *db, int iDb)
void sqlite3CommitInternalChanges (sqlite3 *db)
static void sqliteResetColumnNames (Table *pTable)
void sqlite3DeleteTable (Table *pTable)
void sqlite3UnlinkAndDeleteTable (sqlite3 *db, int iDb, const char *zTabName)
char * sqlite3NameFromToken (sqlite3 *db, Token *pName)
void sqlite3OpenMasterTable (Parse *p, int iDb)
int sqlite3FindDb (sqlite3 *db, Token *pName)
int sqlite3TwoPartName (Parse *pParse, Token *pName1, Token *pName2, Token **pUnqual)
int sqlite3CheckObjectName (Parse *pParse, const char *zName)
void sqlite3StartTable (Parse *pParse, Token *pName1, Token *pName2, int isTemp, int isView, int isVirtual, int noErr)
void sqlite3AddColumn (Parse *pParse, Token *pName)
void sqlite3AddNotNull (Parse *pParse, int onError)
char sqlite3AffinityType (const Token *pType)
void sqlite3AddColumnType (Parse *pParse, Token *pType)
void sqlite3AddDefaultValue (Parse *pParse, Expr *pExpr)
void sqlite3AddPrimaryKey (Parse *pParse, ExprList *pList, int onError, int autoInc, int sortOrder)
void sqlite3AddCheckConstraint (Parse *pParse, Expr *pCheckExpr)
void sqlite3AddCollateType (Parse *pParse, Token *pToken)
CollSeq * sqlite3LocateCollSeq (Parse *pParse, const char *zName, int nName)
void sqlite3ChangeCookie (Parse *pParse, int iDb)
static int identLength (const char *z)
static void identPut (char *z, int *pIdx, char *zSignedIdent)
static char * createTableStmt (sqlite3 *db, Table *p, int isTemp)
void sqlite3EndTable (Parse *pParse, Token *pCons, Token *pEnd, Select *pSelect)
void sqlite3CreateView (Parse *pParse, Token *pBegin, Token *pName1, Token *pName2, Select *pSelect, int isTemp, int noErr)
int sqlite3ViewGetColumnNames (Parse *pParse, Table *pTable)
static void sqliteViewResetAll (sqlite3 *db, int idx)
void sqlite3RootPageMoved (Db *pDb, int iFrom, int iTo)
static void destroyRootPage (Parse *pParse, int iTable, int iDb)
static void destroyTable (Parse *pParse, Table *pTab)
void sqlite3DropTable (Parse *pParse, SrcList *pName, int isView, int noErr)
void sqlite3CreateForeignKey (Parse *pParse, ExprList *pFromCol, Token *pTo, ExprList *pToCol, int flags)
void sqlite3DeferForeignKey (Parse *pParse, int isDeferred)
static void sqlite3RefillIndex (Parse *pParse, Index *pIndex, int memRootPage)
void sqlite3CreateIndex (Parse *pParse, Token *pName1, Token *pName2, SrcList *pTblName, ExprList *pList, int onError, Token *pStart, Token *pEnd, int sortOrder, int ifNotExist)
void sqlite3MinimumFileFormat (Parse *pParse, int iDb, int minFormat)
void sqlite3DefaultRowEst (Index *pIdx)
void sqlite3DropIndex (Parse *pParse, SrcList *pName, int ifExists)
void * sqlite3ArrayAllocate (sqlite3 *db, void *pArray, int szEntry, int initSize, int *pnEntry, int *pnAlloc, int *pIdx)
IdList * sqlite3IdListAppend (sqlite3 *db, IdList *pList, Token *pToken)
void sqlite3IdListDelete (sqlite3 *db, IdList *pList)
int sqlite3IdListIndex (IdList *pList, const char *zName)
SrcList * sqlite3SrcListEnlarge (sqlite3 *db, SrcList *pSrc, int nExtra, int iStart)
SrcList * sqlite3SrcListAppend (sqlite3 *db, SrcList *pList, Token *pTable, Token *pDatabase)
void sqlite3SrcListAssignCursors (Parse *pParse, SrcList *pList)
void sqlite3SrcListDelete (sqlite3 *db, SrcList *pList)
SrcList * sqlite3SrcListAppendFromTerm (Parse *pParse, SrcList *p, Token *pTable, Token *pDatabase, Token *pAlias, Select *pSubquery, Expr *pOn, IdList *pUsing)
void sqlite3SrcListIndexedBy (Parse *pParse, SrcList *p, Token *pIndexedBy)
void sqlite3SrcListShiftJoinType (SrcList *p)
void sqlite3BeginTransaction (Parse *pParse, int type)
void sqlite3CommitTransaction (Parse *pParse)
void sqlite3RollbackTransaction (Parse *pParse)
int sqlite3OpenTempDatabase (Parse *pParse)
void sqlite3CodeVerifySchema (Parse *pParse, int iDb)
void sqlite3BeginWriteOperation (Parse *pParse, int setStatement, int iDb)
static int collationMatch (const char *zColl, Index *pIndex)
static void reindexTable (Parse *pParse, Table *pTab, char const *zColl)
static void reindexDatabases (Parse *pParse, char const *zColl)
void sqlite3Reindex (Parse *pParse, Token *pName1, Token *pName2)
KeyInfo * sqlite3IndexKeyinfo (Parse *pParse, Index *pIdx)
Define Documentation
#define SAVE_SZ (sizeof(Parse) - offsetof(Parse,nVar))
Referenced by sqlite3NestedParse().
#define STRICMP (x, y)
Value:
(\
sqlite3UpperToLower[*(unsigned char *)(x)]==   \
sqlite3UpperToLower[*(unsigned char *)(y)]     \
&& sqlite3StrICmp((x)+1,(y)+1)==0)
Definition at line 925 of file build.c.
Referenced by sqlite3AddColumn().
Function Documentation
static void codeTableLocks (Parse * pParse) [static]
Definition at line 103 of file build.c.
References Parse::aTableLock, TableLock::iDb, TableLock::isWriteLock, TableLock::iTab, Parse::nTableLock, OP_TableLock, P4_STATIC, sqlite3GetVdbe(), sqlite3VdbeAddOp4(), and TableLock::zName.
Referenced by sqlite3FinishCoding().
static int collationMatch (const char * zColl, Index * pIndex) [static]
Definition at line 3418 of file build.c.
References Index::azColl, Index::nColumn, and sqlite3StrICmp().
Referenced by reindexTable().
static char* createTableStmt (sqlite3 * db, Table * p, int isTemp) [static]
Definition at line 1354 of file build.c.
References Table::aCol, identLength(), identPut(), sqlite3::mallocFailed, Table::nCol, OMIT_TEMPDB, sqlite3_snprintf(), sqlite3Malloc(), Table::zName, Column::zName, and Column::zType.
Referenced by sqlite3EndTable().
static void destroyRootPage (Parse * pParse, int iTable, int iDb) [static]
Definition at line 1869 of file build.c.
References sqlite3::aDb, Parse::db, OP_Destroy, SCHEMA_TABLE, sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3NestedParse(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp3(), and Db::zName.
Referenced by destroyTable(), and sqlite3DropIndex().
static void destroyTable (Parse * pParse, Table * pTab) [static]
Definition at line 1895 of file build.c.
References Parse::db, destroyRootPage(), Table::pIndex, Index::pNext, Index::pSchema, Table::pSchema, sqlite3SchemaToIndex(), Index::tnum, and Table::tnum.
Referenced by sqlite3DropTable().
static void freeIndex (Index * p) [static]
Definition at line 354 of file build.c.
References Table::db, db, Index::pTable, sqlite3DbFree(), and Index::zColAff.
Referenced by sqlite3CreateIndex(), sqlite3UnlinkAndDeleteIndex(), and sqliteDeleteIndex().
static int identLength (const char * z) [static]
Definition at line 1318 of file build.c.
Referenced by createTableStmt().
static void identPut (char * z, int * pIdx, char * zSignedIdent) [static]
Definition at line 1330 of file build.c.
References sqlite3KeywordCode(), and TK_ID.
Referenced by createTableStmt().
static void reindexDatabases (Parse * pParse, char const * zColl) [static]
Definition at line 3454 of file build.c.
References sqlite3::aDb, Parse::db, db, Db::pSchema, reindexTable(), sqliteHashData, sqliteHashFirst, sqliteHashNext, and Schema::tblHash.
Referenced by sqlite3Reindex().
static void reindexTable (Parse * pParse, Table * pTab, char const * zColl) [static]
Definition at line 3435 of file build.c.
References collationMatch(), Parse::db, Table::pIndex, Index::pNext, Table::pSchema, sqlite3BeginWriteOperation(), sqlite3RefillIndex(), and sqlite3SchemaToIndex().
Referenced by reindexDatabases(), and sqlite3Reindex().
void sqlite3AddCheckConstraint (Parse * pParse, Expr * pCheckExpr)
Definition at line 1192 of file build.c.
References Parse::db, db, IN_DECLARE_VTAB, Table::pCheck, Parse::pNewTable, sqlite3ExprAnd(), sqlite3ExprDelete(), and sqlite3ExprDup().
Referenced by yy_reduce().
void sqlite3AddCollateType (Parse * pParse, Token * pToken)
Definition at line 1214 of file build.c.
References Table::aCol, Index::aiColumn, Index::azColl, Parse::db, db, Table::nCol, Index::nColumn, Table::pIndex, Parse::pNewTable, Index::pNext, sqlite3DbFree(), sqlite3LocateCollSeq(), sqlite3NameFromToken(), and Column::zColl.
Referenced by yy_reduce().
void sqlite3AddColumn (Parse * pParse, Token * pName)
Definition at line 938 of file build.c.
References Table::aCol, Column::affinity, sqlite3::aLimit, Parse::db, db, Table::nCol, Parse::pNewTable, sqlite3DbFree(), sqlite3DbRealloc(), sqlite3ErrorMsg(), sqlite3NameFromToken(), SQLITE_AFF_NONE, SQLITE_LIMIT_COLUMN, STRICMP, Column::zName, and Table::zName.
Referenced by yy_reduce().
void sqlite3AddColumnType (Parse * pParse, Token * pType)
Definition at line 1067 of file build.c.
References Table::aCol, Column::affinity, Parse::db, db, Table::nCol, Parse::pNewTable, sqlite3AffinityType(), sqlite3DbFree(), sqlite3NameFromToken(), and Column::zType.
Referenced by yy_reduce().
void sqlite3AddDefaultValue (Parse * pParse, Expr * pExpr)
Definition at line 1093 of file build.c.
References Table::aCol, Parse::db, db, Table::nCol, Column::pDflt, Parse::pNewTable, Expr::span, sqlite3ErrorMsg(), sqlite3ExprDelete(), sqlite3ExprDup(), sqlite3ExprIsConstantOrFunction(), sqlite3TokenCopy(), and Column::zName.
Referenced by yy_reduce().
void sqlite3AddNotNull (Parse * pParse, int onError)
Definition at line 987 of file build.c.
References Table::aCol, Table::nCol, Column::notNull, and Parse::pNewTable.
Referenced by yy_reduce().
void sqlite3AddPrimaryKey (Parse * pParse, ExprList * pList, int onError, int autoInc, int sortOrder)
Definition at line 1132 of file build.c.
References ExprList::a, Table::aCol, Parse::db, IN_DECLARE_VTAB, Table::iPKey, Column::isPrimKey, Table::keyConf, Table::nCol, ExprList::nExpr, Parse::pNewTable, sqlite3CreateIndex(), sqlite3ErrorMsg(), sqlite3ExprListDelete(), sqlite3StrICmp(), SQLITE_SO_ASC, Table::tabFlags, TF_Autoincrement, TF_HasPrimaryKey, Column::zName, ExprList::ExprList_item::zName, Table::zName, and Column::zType.
Referenced by yy_reduce().
char sqlite3AffinityType (const Token * pType)
Definition at line 1020 of file build.c.
References Token::n, sqlite3UpperToLower, SQLITE_AFF_INTEGER, SQLITE_AFF_NONE, SQLITE_AFF_NUMERIC, SQLITE_AFF_REAL, SQLITE_AFF_TEXT, and Token::z.
Referenced by sqlite3AddColumnType(), sqlite3ExprAffinity(), and sqlite3ExprCodeTarget().
void* sqlite3ArrayAllocate (sqlite3 * db, void * pArray, int szEntry, int initSize, int * pnEntry, int * pnAlloc, int * pIdx)
Definition at line 2909 of file build.c.
References sqlite3DbRealloc().
Referenced by addAggInfoColumn(), addAggInfoFunc(), and sqlite3IdListAppend().
void sqlite3BeginParse (Parse * pParse, int explainFlag)
Definition at line 34 of file build.c.
References Parse::explain, and Parse::nVar.
Referenced by yy_reduce().
void sqlite3BeginTransaction (Parse * pParse, int type)
Definition at line 3249 of file build.c.
References sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, sqlite3::nDb, Parse::nErr, OP_AutoCommit, OP_Transaction, Db::pBt, sqlite3AuthCheck(), sqlite3GetVdbe(), sqlite3VdbeAddOp2(), sqlite3VdbeUsesBtree(), SQLITE_TRANSACTION, TK_DEFERRED, and TK_EXCLUSIVE.
Referenced by yy_reduce().
void sqlite3BeginWriteOperation (Parse * pParse, int setStatement, int iDb)
Definition at line 3400 of file build.c.
References sqlite3::aDb, Parse::db, Parse::nested, OMIT_TEMPDB, OP_Statement, Db::pBt, sqlite3BeginWriteOperation(), sqlite3CodeVerifySchema(), sqlite3GetVdbe(), sqlite3VdbeAddOp1(), and Parse::writeMask.
Referenced by analyzeDatabase(), analyzeTable(), reindexTable(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginWriteOperation(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3FinishTrigger(), sqlite3Insert(), sqlite3Pragma(), sqlite3Reindex(), sqlite3StartTable(), and sqlite3Update().
void sqlite3ChangeCookie (Parse * pParse, int iDb)
Definition at line 1301 of file build.c.
References sqlite3::aDb, Parse::db, db, OP_Integer, OP_SetCookie, Db::pSchema, Parse::pVdbe, Schema::schema_cookie, sqlite3GetTempReg(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp2(), and sqlite3VdbeAddOp3().
Referenced by sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3FinishTrigger(), and sqlite3VtabFinishParse().
int sqlite3CheckObjectName (Parse * pParse, const char * zName)
Definition at line 696 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, sqlite3::flags, sqlite3::init, Parse::nested, sqlite3ErrorMsg(), sqlite3StrNICmp(), SQLITE_ERROR, SQLITE_OK, and SQLITE_WriteSchema.
Referenced by sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CreateIndex(), and sqlite3StartTable().
void sqlite3CodeVerifySchema (Parse * pParse, int iDb)
Definition at line 3356 of file build.c.
References sqlite3::aDb, Parse::cookieGoto, Parse::cookieMask, Parse::cookieValue, Parse::db, db, OMIT_TEMPDB, OP_Goto, Db::pBt, Db::pSchema, Schema::schema_cookie, sqlite3GetVdbe(), sqlite3OpenTempDatabase(), sqlite3VdbeAddOp2(), and SQLITE_MAX_ATTACHED.
Referenced by sqlite3BeginWriteOperation(), sqlite3Pragma(), sqlite3WhereBegin(), and xferOptimization().
void sqlite3CommitInternalChanges (sqlite3 * db)
Definition at line 472 of file build.c.
References sqlite3::flags, and SQLITE_InternChanges.
Referenced by sqlite3Init(), and sqlite3VdbeHalt().
void sqlite3CommitTransaction (Parse * pParse)
Definition at line 3272 of file build.c.
References sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, Parse::nErr, OP_AutoCommit, Db::pBt, sqlite3AuthCheck(), sqlite3GetVdbe(), sqlite3VdbeAddOp2(), and SQLITE_TRANSACTION.
Referenced by yy_reduce().
void sqlite3CreateForeignKey (Parse * pParse, ExprList * pFromCol, Token * pTo, ExprList * pToCol, int flags)
Definition at line 2133 of file build.c.
References ExprList::a, FKey::aCol, Table::aCol, Parse::db, db, FKey::deleteConf, FKey::sColMap::iFrom, IN_DECLARE_VTAB, FKey::insertConf, FKey::isDeferred, Token::n, FKey::nCol, Table::nCol, Parse::nErr, ExprList::nExpr, Table::pFKey, FKey::pFrom, Parse::pNewTable, FKey::pNextFrom, FKey::pNextTo, sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3ErrorMsg(), sqlite3ExprListDelete(), sqlite3StrICmp(), FKey::updateConf, Token::z, FKey::sColMap::zCol, ExprList::ExprList_item::zName, Column::zName, and FKey::zTo.
Referenced by yy_reduce().
void sqlite3CreateIndex (Parse * pParse, Token * pName1, Token * pName2, SrcList * pTblName, ExprList * pList, int onError, Token * pStart, Token * pEnd, int sortOrder, int ifNotExist)
Definition at line 2336 of file build.c.
References ExprList::a, SrcList::a, Table::aCol, sqlite3::aDb, Index::aiColumn, Index::aiRowEst, Index::aSortOrder, Index::autoIndex, Index::azColl, sqlite3::sqlite3InitInfo::busy, Parse::db, db, Schema::file_format, sqlite3::flags, freeIndex(), Schema::idxHash, IN_DECLARE_VTAB, sqlite3::init, IsVirtual, sqlite3::mallocFailed, Token::n, Table::nCol, Index::nColumn, Parse::nErr, sqlite3::sqlite3InitInfo::newTnum, ExprList::nExpr, Parse::nMem, OE_Default, OE_None, OE_Replace, OMIT_TEMPDB, Index::onError, OP_CreateIndex, OP_Expire, OP_ParseSchema, P4_DYNAMIC, Expr::pColl, sqlite3::pDfltColl, ExprList::ExprList_item::pExpr, Table::pIndex, Parse::pNewTable, Index::pNext, Index::pSchema, Db::pSchema, Table::pSchema, Table::pSelect, Index::pTable, SCHEMA_TABLE, ExprList::ExprList_item::sortOrder, sqlite3_snprintf(), sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DefaultRowEst(), sqlite3ErrorMsg(), sqlite3ExprListAppend(), sqlite3ExprListDelete(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3FixInit(), sqlite3FixSrcList(), sqlite3GetVdbe(), sqlite3HashInsert(), sqlite3LocateCollSeq(), sqlite3LocateTable(), sqlite3MPrintf(), sqlite3NameFromToken(), sqlite3NestedParse(), sqlite3ReadSchema(), sqlite3RefillIndex(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StrICmp(), sqlite3StrNICmp(), sqlite3TwoPartName(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), SQLITE_CREATE_INDEX, SQLITE_CREATE_TEMP_INDEX, SQLITE_INSERT, SQLITE_InternChanges, SQLITE_OK, Index::tnum, Token::z, Column::zColl, SrcList::SrcList_item::zDatabase, Index::zName, CollSeq::zName, Column::zName, Db::zName, Table::zName, and SrcList::SrcList_item::zName.
Referenced by sqlite3AddPrimaryKey(), and yy_reduce().
void sqlite3CreateView (Parse * pParse, Token * pBegin, Token * pName1, Token * pName2, Select * pSelect, int isTemp, int noErr)
Definition at line 1645 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::init, sqlite3::mallocFailed, Token::n, Parse::nErr, Parse::nVar, Parse::pNewTable, Table::pSchema, Table::pSelect, Parse::sLastToken, sqlite3EndTable(), sqlite3ErrorMsg(), sqlite3FixInit(), sqlite3FixSelect(), sqlite3SchemaToIndex(), sqlite3SelectDelete(), sqlite3SelectDup(), sqlite3StartTable(), sqlite3TwoPartName(), sqlite3ViewGetColumnNames(), and Token::z.
Referenced by yy_reduce().
void sqlite3DefaultRowEst (Index * pIdx)
Definition at line 2806 of file build.c.
References Index::aiRowEst, Index::nColumn, OE_None, and Index::onError.
Referenced by sqlite3AnalysisLoad(), and sqlite3CreateIndex().
void sqlite3DeferForeignKey (Parse * pParse, int isDeferred)
Definition at line 2242 of file build.c.
References FKey::isDeferred, Table::pFKey, and Parse::pNewTable.
Referenced by yy_reduce().
void sqlite3DeleteTable (Table * pTable)
Definition at line 507 of file build.c.
References Schema::aFKey, Table::db, db, Table::nRef, Table::pCheck, Table::pFKey, Table::pIndex, Index::pNext, FKey::pNextFrom, Table::pSchema, Index::pSchema, Table::pSelect, sqlite3DbFree(), sqlite3ExprDelete(), sqlite3HashFind(), sqlite3SelectDelete(), sqlite3VtabClear(), sqliteDeleteIndex(), sqliteResetColumnNames(), Table::zColAff, Table::zName, and FKey::zTo.
Referenced by sqlite3_declare_vtab(), sqlite3EndTable(), sqlite3ResultSetOfSelect(), sqlite3RunParser(), sqlite3SchemaFree(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StartTable(), sqlite3UnlinkAndDeleteTable(), and sqlite3ViewGetColumnNames().
void sqlite3DropIndex (Parse * pParse, SrcList * pName, int ifExists)
Definition at line 2827 of file build.c.
References SrcList::a, sqlite3::aDb, Index::autoIndex, Parse::checkSchema, Parse::db, db, destroyRootPage(), sqlite3::mallocFailed, Parse::nErr, SrcList::nSrc, OMIT_TEMPDB, OP_DropIndex, Index::pSchema, Index::pTable, SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3NestedParse(), sqlite3ReadSchema(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3VdbeAddOp4(), SQLITE_DELETE, SQLITE_DROP_INDEX, SQLITE_DROP_TEMP_INDEX, SQLITE_OK, Index::tnum, SrcList::SrcList_item::zDatabase, Table::zName, Index::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
void sqlite3DropTable (Parse * pParse, SrcList * pName, int isView, int noErr)
Definition at line 1952 of file build.c.
References SrcList::a, sqlite3::aDb, Parse::db, db, destroyTable(), IsVirtual, sqlite3::mallocFailed, Parse::nErr, SrcList::nSrc, OMIT_TEMPDB, OP_DropTable, OP_VBegin, OP_VDestroy, Table::pMod, Trigger::pNext, Db::pSchema, Trigger::pSchema, Table::pSchema, Table::pSelect, Table::pTrigger, SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3DropTriggerPtr(), sqlite3ErrorClear(), sqlite3ErrorMsg(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3LocateTable(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3StrNICmp(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp4(), sqlite3ViewGetColumnNames(), SQLITE_DELETE, SQLITE_DROP_TABLE, SQLITE_DROP_TEMP_TABLE, SQLITE_DROP_TEMP_VIEW, SQLITE_DROP_VIEW, SQLITE_DROP_VTABLE, sqliteViewResetAll(), Table::tabFlags, TF_Autoincrement, SrcList::SrcList_item::zDatabase, Table::zName, Module::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
void sqlite3EndTable (Parse * pParse, Token * pCons, Token * pEnd, Select * pSelect)
Definition at line 1424 of file build.c.
References SrcList::a, Table::aCol, sqlite3::aDb, Table::addColOffset, Schema::aFKey, sqlite3::sqlite3InitInfo::busy, createTableStmt(), Parse::db, db, sqlite3::flags, SrcList::SrcList_item::iCursor, sqlite3::init, NameContext::isCheck, sqlite3::mallocFailed, Table::nCol, Parse::nErr, sqlite3::sqlite3InitInfo::newTnum, SrcList::nSrc, Parse::nTab, sqlite3::nTable, OP_Close, OP_OpenWrite, OP_ParseSchema, P4_DYNAMIC, Table::pCheck, Table::pFKey, Parse::pNewTable, FKey::pNextFrom, FKey::pNextTo, NameContext::pParse, Db::pSchema, Table::pSchema, Table::pSelect, Schema::pSeqTab, NameContext::pSrcList, SrcList::SrcList_item::pTab, Parse::regRoot, Parse::regRowid, SCHEMA_TABLE, Parse::sNameToken, sqlite3ChangeCookie(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3GetVdbe(), sqlite3HashFind(), sqlite3HashInsert(), sqlite3MPrintf(), sqlite3NestedParse(), sqlite3ResolveExprNames(), sqlite3ResultSetOfSelect(), sqlite3SchemaToIndex(), sqlite3Select(), sqlite3SelectDestInit(), sqlite3Utf8CharLen(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP5(), SQLITE_InternChanges, SRT_Table, Table::tabFlags, Schema::tblHash, TF_Autoincrement, Table::tnum, Token::z, Db::zName, Table::zName, SrcList::SrcList_item::zName, and FKey::zTo.
Referenced by sqlite3CreateView(), and yy_reduce().
int sqlite3FindDb (sqlite3 * db, Token * pName)
Definition at line 627 of file build.c.
References sqlite3::aDb, sqlite3::nDb, OMIT_TEMPDB, sqlite3DbFree(), sqlite3NameFromToken(), sqlite3StrICmp(), and Db::zName.
Referenced by sqlite3Analyze(), and sqlite3TwoPartName().
Index* sqlite3FindIndex (sqlite3 * db, const char * zName, const char * zDb)
Definition at line 334 of file build.c.
References sqlite3::aDb, Schema::idxHash, sqlite3::nDb, OMIT_TEMPDB, Db::pBt, Db::pSchema, sqlite3HashFind(), sqlite3StrICmp(), sqlite3Strlen(), and Db::zName.
Referenced by analysisLoader(), sqlite3AlterRenameTable(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3InitCallback(), sqlite3Pragma(), sqlite3Reindex(), and sqlite3StartTable().
Table* sqlite3FindTable (sqlite3 * db, const char * zName, const char * zDatabase)
Definition at line 270 of file build.c.
References sqlite3::aDb, sqlite3::nDb, OMIT_TEMPDB, Db::pSchema, sqlite3HashFind(), sqlite3StrICmp(), sqlite3Strlen(), Schema::tblHash, and Db::zName.
Referenced by openStatTable(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AnalysisLoad(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3InitOne(), sqlite3LocateTable(), sqlite3Pragma(), sqlite3Reindex(), sqlite3StartTable(), sqlite3VtabCallCreate(), and sqlite3VtabCallDestroy().
void sqlite3FinishCoding (Parse * pParse)
Definition at line 132 of file build.c.
References Parse::apVtabLock, sqlite3::sqlite3InitInfo::busy, codeTableLocks(), Parse::colNamesSet, Parse::cookieGoto, Parse::cookieMask, Parse::cookieValue, Parse::db, db, Parse::disableColCache, Parse::explain, sqlite3::flags, sqlite3::init, sqlite3::mallocFailed, sqlite3::nDb, Parse::nErr, Parse::nested, Parse::nMem, Parse::nSet, Parse::nTab, Parse::nVar, Parse::nVtabLock, OP_Goto, OP_Halt, OP_Trace, OP_Transaction, OP_VBegin, OP_VerifyCookie, VdbeOp::opcode, P4_VTAB, Table::pVtab, Parse::rc, sqlite3GetVdbe(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeGetOp(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeReady(), sqlite3VdbeUsesBtree(), SQLITE_DONE, SQLITE_ERROR, SQLITE_OK, SQLITE_VdbeTrace, Parse::writeMask, Parse::zSql, and Parse::zTail.
Referenced by yy_reduce().
IdList* sqlite3IdListAppend (sqlite3 * db, IdList * pList, Token * pToken)
Definition at line 2944 of file build.c.
References IdList::a, IdList::nAlloc, IdList::nId, sqlite3ArrayAllocate(), sqlite3DbMallocZero(), sqlite3IdListDelete(), sqlite3NameFromToken(), and IdList::IdList_item::zName.
Referenced by yy_reduce().
void sqlite3IdListDelete (sqlite3 * db, IdList * pList)
Definition at line 2971 of file build.c.
References IdList::a, IdList::nId, sqlite3DbFree(), and IdList::IdList_item::zName.
Referenced by sqlite3BeginTrigger(), sqlite3DeleteTrigger(), sqlite3DeleteTriggerStep(), sqlite3IdListAppend(), sqlite3Insert(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListDelete(), sqlite3TriggerInsertStep(), sqlitePersistTriggerStep(), and yy_destructor().
int sqlite3IdListIndex (IdList * pList, const char * zName)
Definition at line 2985 of file build.c.
References IdList::a, IdList::nId, sqlite3StrICmp(), and IdList::IdList_item::zName.
Referenced by checkColumnOverLap(), and selectExpander().
KeyInfo* sqlite3IndexKeyinfo (Parse * pParse, Index * pIdx)
Definition at line 3551 of file build.c.
References KeyInfo::aColl, Index::aSortOrder, KeyInfo::aSortOrder, Index::azColl, KeyInfo::db, Parse::db, db, Index::nColumn, Parse::nErr, sqlite3DbFree(), sqlite3DbMallocZero(), and sqlite3LocateCollSeq().
Referenced by analyzeOneTable(), sqlite3FindInIndex(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Update(), sqlite3WhereBegin(), and xferOptimization().
CollSeq* sqlite3LocateCollSeq (Parse * pParse, const char * zName, int nName)
Definition at line 1263 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, ENC, sqlite3::init, sqlite3ErrorMsg(), sqlite3FindCollSeq(), sqlite3GetCollSeq(), sqlite3Strlen(), and CollSeq::xCmp.
Referenced by sqlite3AddCollateType(), sqlite3CreateIndex(), sqlite3ExprSetColl(), and sqlite3IndexKeyinfo().
Table* sqlite3LocateTable (Parse * pParse, int isView, const char * zName, const char * zDbase)
Definition at line 295 of file build.c.
References Parse::checkSchema, Parse::db, sqlite3ErrorMsg(), sqlite3FindTable(), sqlite3ReadSchema(), and SQLITE_OK.
Referenced by selectExpander(), sqlite3_blob_open(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3Analyze(), sqlite3CreateIndex(), sqlite3DropTable(), sqlite3SrcListLookup(), and xferOptimization().
void sqlite3MinimumFileFormat (Parse * pParse, int iDb, int minFormat)
Definition at line 2770 of file build.c.
References OP_Ge, OP_Integer, OP_ReadCookie, OP_SetCookie, sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeJumpHere(), and sqlite3VdbeUsesBtree().
Referenced by sqlite3AlterFinishAddColumn().
char* sqlite3NameFromToken (sqlite3 * db, Token * pName)
Definition at line 599 of file build.c.
References Token::n, sqlite3DbStrNDup(), sqlite3Dequote(), Token::z, and Db::zName.
Referenced by codeAttach(), lookupName(), resolveAsName(), selectExpander(), sqlite3AddCollateType(), sqlite3AddColumn(), sqlite3AddColumnType(), sqlite3AlterRenameTable(), sqlite3Analyze(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3ExprListAppend(), sqlite3ExprSetColl(), sqlite3FindDb(), sqlite3IdListAppend(), sqlite3Pragma(), sqlite3Reindex(), sqlite3SrcListAppend(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListIndexedBy(), sqlite3StartTable(), and sqlite3VtabBeginParse().
void sqlite3NestedParse (Parse * pParse, const char * zFormat, ...)
Definition at line 232 of file build.c.
References Parse::db, db, Parse::nErr, Parse::nested, Parse::nVar, SAVE_SZ, sqlite3DbFree(), sqlite3RunParser(), and sqlite3VMPrintf().
Referenced by destroyRootPage(), openStatTable(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3EndTable(), sqlite3FinishTrigger(), and sqlite3VtabFinishParse().
void sqlite3OpenMasterTable (Parse * p, int iDb)
Definition at line 614 of file build.c.
References MASTER_ROOT, OP_OpenWrite, OP_SetNumColumns, SCHEMA_TABLE, sqlite3GetVdbe(), sqlite3TableLock(), sqlite3VdbeAddOp2(), and sqlite3VdbeAddOp3().
Referenced by sqlite3DropTriggerPtr(), and sqlite3StartTable().
int sqlite3OpenTempDatabase (Parse * pParse)
Definition at line 3307 of file build.c.
References sqlite3::aDb, sqlite3::autoCommit, Parse::db, db, sqlite3::dfltJournalMode, Parse::explain, sqlite3::flags, Db::pBt, Db::pSchema, Parse::rc, sqlite3BtreeFactory(), sqlite3BtreePager(), sqlite3ErrorMsg(), sqlite3PagerJournalMode(), SQLITE_DEFAULT_CACHE_SIZE, SQLITE_InTrans, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_DELETEONCLOSE, SQLITE_OPEN_EXCLUSIVE, SQLITE_OPEN_READWRITE, and SQLITE_OPEN_TEMP_DB.
Referenced by sqlite3CodeVerifySchema(), and sqlite3Pragma().
static void sqlite3RefillIndex (Parse * pParse, Index * pIndex, int memRootPage) [static]
Definition at line 2262 of file build.c.
References sqlite3::aDb, Parse::db, db, Index::nColumn, Parse::nTab, OE_Abort, OE_None, Index::onError, OP_Clear, OP_Close, OP_Halt, OP_IdxInsert, OP_IsNull, OP_IsUnique, OP_Next, OP_OpenRead, OP_OpenWrite, OP_Rewind, P4_INT32, P4_KEYINFO_HANDOFF, P4_STATIC, Index::pSchema, Index::pTable, sqlite3AuthCheck(), sqlite3GenerateIndexKey(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3IndexKeyinfo(), sqlite3OpenTable(), sqlite3ReleaseTempReg(), sqlite3SchemaToIndex(), sqlite3TableLock(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP5(), sqlite3VdbeJumpHere(), SQLITE_CONSTRAINT, SQLITE_INT_TO_PTR, SQLITE_REINDEX, Index::tnum, Table::tnum, Table::zName, Db::zName, and Index::zName.
Referenced by reindexTable(), sqlite3CreateIndex(), and sqlite3Reindex().
void sqlite3Reindex (Parse * pParse, Token * pName1, Token * pName2)
Definition at line 3485 of file build.c.
References sqlite3::aDb, Parse::db, db, ENC, reindexDatabases(), reindexTable(), sqlite3BeginWriteOperation(), sqlite3DbFree(), sqlite3ErrorMsg(), sqlite3FindCollSeq(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3NameFromToken(), sqlite3ReadSchema(), sqlite3RefillIndex(), sqlite3TwoPartName(), SQLITE_OK, Token::z, and Db::zName.
Referenced by yy_reduce().
void sqlite3ResetInternalSchema (sqlite3 * db, int iDb)
Definition at line 416 of file build.c.
References sqlite3::aDb, sqlite3::aDbStatic, sqlite3::flags, sqlite3::nDb, Db::pAux, Db::pBt, Db::pSchema, sqlite3BtreeEnterAll, sqlite3BtreeLeaveAll, sqlite3DbFree(), sqlite3SchemaFree(), SQLITE_InternChanges, Db::xFreeAux, and Db::zName.
Referenced by attachFunc(), createModule(), detachFunc(), invalidateTempStorage(), sqlite3_close(), sqlite3Init(), sqlite3InitOne(), sqlite3Prepare(), sqlite3RollbackAll(), sqlite3RunVacuum(), sqlite3VdbeExec(), and sqlite3VdbeHalt().
void sqlite3RollbackTransaction (Parse * pParse)
Definition at line 3289 of file build.c.
References sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, Parse::nErr, OP_AutoCommit, Db::pBt, sqlite3AuthCheck(), sqlite3GetVdbe(), sqlite3VdbeAddOp2(), and SQLITE_TRANSACTION.
Referenced by yy_reduce().
void sqlite3RootPageMoved (Db * pDb, int iFrom, int iTo)
Definition at line 1842 of file build.c.
References Schema::idxHash, Db::pSchema, sqliteHashData, sqliteHashFirst, sqliteHashNext, Schema::tblHash, Index::tnum, and Table::tnum.
Referenced by sqlite3VdbeExec().
SrcList* sqlite3SrcListAppend (sqlite3 * db, SrcList * pList, Token * pTable, Token * pDatabase)
Definition at line 3089 of file build.c.
References SrcList::a, sqlite3::mallocFailed, SrcList::nAlloc, SrcList::nSrc, sqlite3DbMallocZero(), sqlite3NameFromToken(), sqlite3SrcListDelete(), sqlite3SrcListEnlarge(), and Token::z.
Referenced by flattenSubquery(), sqlite3SrcListAppendFromTerm(), targetSrcList(), and yy_reduce().
SrcList* sqlite3SrcListAppendFromTerm (Parse * pParse, SrcList * p, Token * pTable, Token * pDatabase, Token * pAlias, Select * pSubquery, Expr * pOn, IdList * pUsing)
Definition at line 3174 of file build.c.
References SrcList::a, Parse::db, db, Token::n, SrcList::nSrc, sqlite3ExprDelete(), sqlite3IdListDelete(), sqlite3NameFromToken(), sqlite3SelectDelete(), sqlite3SrcListAppend(), and SrcList::SrcList_item::zAlias.
Referenced by sqlite3MaterializeView(), and yy_reduce().
void sqlite3SrcListAssignCursors (Parse * pParse, SrcList * pList)
Definition at line 3123 of file build.c.
References SrcList::a, Parse::db, sqlite3::mallocFailed, Parse::nTab, and sqlite3SrcListAssignCursors().
Referenced by selectExpander(), sqlite3SrcListAssignCursors(), and sqlite3ViewGetColumnNames().
void sqlite3SrcListDelete (sqlite3 * db, SrcList * pList)
Definition at line 3141 of file build.c.
References SrcList::a, sqlite3DbFree(), sqlite3DeleteTable(), sqlite3ExprDelete(), sqlite3IdListDelete(), and sqlite3SelectDelete().
Referenced by clearSelect(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTrigger(), sqlite3Insert(), sqlite3SrcListAppend(), sqlite3Update(), yy_destructor(), and yy_reduce().
SrcList* sqlite3SrcListEnlarge (sqlite3 * db, SrcList * pSrc, int nExtra, int iStart)
Definition at line 3013 of file build.c.
References SrcList::a, SrcList::SrcList_item::iCursor, sqlite3::mallocFailed, SrcList::nAlloc, SrcList::nSrc, and sqlite3DbRealloc().
Referenced by flattenSubquery(), and sqlite3SrcListAppend().
void sqlite3SrcListIndexedBy (Parse * pParse, SrcList * p, Token * pIndexedBy)
Definition at line 3207 of file build.c.
References SrcList::a, Parse::db, Token::n, SrcList::nSrc, sqlite3NameFromToken(), and Token::z.
Referenced by yy_reduce().
void sqlite3SrcListShiftJoinType (SrcList * p)
Definition at line 3236 of file build.c.
References SrcList::a, SrcList::SrcList_item::jointype, and SrcList::nSrc.
Referenced by yy_reduce().
void sqlite3StartTable (Parse * pParse, Token * pName1, Token * pName2, int isTemp, int isView, int isVirtual, int noErr)
Definition at line 722 of file build.c.
References sqlite3::aDb, sqlite3::sqlite3InitInfo::busy, Table::db, Parse::db, db, ENC, sqlite3::flags, sqlite3::sqlite3InitInfo::iDb, IN_DECLARE_VTAB, sqlite3::init, Table::iPKey, sqlite3::mallocFailed, Parse::nErr, Parse::nested, Parse::nMem, Table::nRef, OMIT_TEMPDB, OP_Close, OP_CreateTable, OP_If, OP_Insert, OP_Integer, OP_NewRowid, OP_Null, OP_ReadCookie, OP_SetCookie, OP_VBegin, OPFLAG_APPEND, Parse::pNewTable, Db::pSchema, Table::pSchema, Schema::pSeqTab, Parse::rc, Parse::regRoot, Parse::regRowid, SCHEMA_TABLE, Parse::sNameToken, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DeleteTable(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3NameFromToken(), sqlite3OpenMasterTable(), sqlite3ReadSchema(), sqlite3TwoPartName(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeChangeP5(), sqlite3VdbeJumpHere(), sqlite3VdbeUsesBtree(), SQLITE_CREATE_TABLE, SQLITE_CREATE_TEMP_TABLE, SQLITE_CREATE_TEMP_VIEW, SQLITE_CREATE_VIEW, SQLITE_INSERT, SQLITE_LegacyFileFmt, SQLITE_MAX_FILE_FORMAT, SQLITE_NOMEM, SQLITE_OK, Table::zName, and Db::zName.
Referenced by sqlite3CreateView(), sqlite3VtabBeginParse(), and yy_reduce().
void sqlite3TableLock (Parse * pParse, int iDb, int iTab, u8 isWriteLock, const char * zName)
Definition at line 61 of file build.c.
References Parse::aTableLock, Parse::db, TableLock::iDb, TableLock::isWriteLock, TableLock::iTab, sqlite3::mallocFailed, Parse::nTableLock, sqlite3DbReallocOrFree(), and TableLock::zName.
Referenced by analyzeOneTable(), openStatTable(), sqlite3OpenMasterTable(), sqlite3OpenTable(), sqlite3RefillIndex(), and sqlite3WhereBegin().
int sqlite3TwoPartName (Parse * pParse, Token * pName1, Token * pName2, Token ** pUnqual)
Definition at line 663 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::sqlite3InitInfo::iDb, sqlite3::init, Token::n, Parse::nErr, sqlite3ErrorMsg(), and sqlite3FindDb().
Referenced by sqlite3Analyze(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3Pragma(), sqlite3Reindex(), and sqlite3StartTable().
void sqlite3UnlinkAndDeleteIndex (sqlite3 * db, int iDb, const char * zIdxName)
Definition at line 383 of file build.c.
References sqlite3::aDb, sqlite3::flags, freeIndex(), Schema::idxHash, Table::pIndex, Index::pNext, Db::pSchema, Index::pTable, sqlite3HashInsert(), sqlite3Strlen(), and SQLITE_InternChanges.
Referenced by sqlite3VdbeExec().
void sqlite3UnlinkAndDeleteTable (sqlite3 * db, int iDb, const char * zTabName)
Definition at line 559 of file build.c.
References sqlite3::aDb, Schema::aFKey, sqlite3::flags, Table::pFKey, FKey::pNextFrom, FKey::pNextTo, Db::pSchema, sqlite3DeleteTable(), sqlite3HashFind(), sqlite3HashInsert(), SQLITE_InternChanges, Schema::tblHash, and FKey::zTo.
Referenced by sqlite3VdbeExec().
int sqlite3ViewGetColumnNames (Parse * pParse, Table * pTable)
Definition at line 1723 of file build.c.
References Table::aCol, Parse::db, db, DB_UnresetViews, Schema::flags, IsVirtual, Table::nCol, Parse::nTab, Table::pSchema, Table::pSelect, Select::pSrc, sqlite3DeleteTable(), sqlite3ErrorMsg(), sqlite3ResultSetOfSelect(), sqlite3SelectDelete(), sqlite3SelectDup(), sqlite3SrcListAssignCursors(), sqlite3VtabCallConnect(), SQLITE_ERROR, sqlite3::xAuth, and Table::zName.
Referenced by selectExpander(), sqlite3AlterRenameTable(), sqlite3CreateView(), sqlite3DeleteFrom(), sqlite3DropTable(), sqlite3Insert(), sqlite3Pragma(), and sqlite3Update().
static void sqliteDeleteIndex (Index * p) [static]
Definition at line 368 of file build.c.
References freeIndex(), Schema::idxHash, Index::pSchema, sqlite3HashInsert(), and Index::zName.
Referenced by sqlite3DeleteTable().
static void sqliteResetColumnNames (Table * pTable) [static]
Definition at line 479 of file build.c.
References Table::aCol, Table::db, db, Table::nCol, Column::pDflt, sqlite3DbFree(), sqlite3ExprDelete(), Column::zColl, Column::zName, and Column::zType.
Referenced by sqlite3DeleteTable(), and sqliteViewResetAll().
static void sqliteViewResetAll (sqlite3 * db, int idx) [static]
Definition at line 1809 of file build.c.
References sqlite3::aDb, DB_UnresetViews, DbClearProperty, DbHasProperty, Db::pSchema, Table::pSelect, sqliteHashData, sqliteHashFirst, sqliteHashNext, sqliteResetColumnNames(), and Schema::tblHash.
Referenced by sqlite3DropTable().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1