ContextLogger2 Logger Daemon Internals: callback.c File Reference
callback.c File Reference
Functions
static void callCollNeeded (sqlite3 *db, const char *zName, int nName)
static int synthCollSeq (sqlite3 *db, CollSeq *pColl)
CollSeq * sqlite3GetCollSeq (sqlite3 *db, CollSeq *pColl, const char *zName, int nName)
int sqlite3CheckCollSeq (Parse *pParse, CollSeq *pColl)
static CollSeq * findCollSeqEntry (sqlite3 *db, const char *zName, int nName, int create)
CollSeq * sqlite3FindCollSeq (sqlite3 *db, u8 enc, const char *zName, int nName, int create)
static int matchQuality (FuncDef *p, int nArg, u8 enc)
static FuncDef * functionSearch (FuncDefHash *pHash, int h, const char *zFunc, int nFunc)
void sqlite3FuncDefInsert (FuncDefHash *pHash, FuncDef *pDef)
FuncDef * sqlite3FindFunction (sqlite3 *db, const char *zName, int nName, int nArg, u8 enc, int createFlag)
void sqlite3SchemaFree (void *p)
Schema * sqlite3SchemaGet (sqlite3 *db, Btree *pBt)
Function Documentation
static void callCollNeeded (sqlite3 * db, const char * zName, int nName) [static]
Definition at line 26 of file callback.c.
References ENC, sqlite3::pCollNeededArg, sqlite3DbFree(), sqlite3DbStrNDup(), sqlite3Strlen(), sqlite3ValueFree(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3ValueText(), SQLITE_STATIC, SQLITE_UTF16NATIVE, SQLITE_UTF8, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
Referenced by sqlite3GetCollSeq().
static CollSeq* findCollSeqEntry (sqlite3 * db, const char * zName, int nName, int create) [static]
Definition at line 154 of file callback.c.
References sqlite3::aCollSeq, CollSeq::enc, sqlite3::mallocFailed, sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3HashFind(), sqlite3HashInsert(), sqlite3Strlen(), SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, and CollSeq::zName.
Referenced by sqlite3FindCollSeq().
static FuncDef* functionSearch (FuncDefHash * pHash, int h, const char * zFunc, int nFunc) [static]
Definition at line 267 of file callback.c.
References FuncDefHash::a, FuncDef::pHash, sqlite3StrNICmp(), and FuncDef::zName.
Referenced by sqlite3FindFunction(), and sqlite3FuncDefInsert().
static int matchQuality (FuncDef * p, int nArg, u8 enc) [static]
Definition at line 245 of file callback.c.
References FuncDef::iPrefEnc, match(), FuncDef::nArg, SQLITE_UTF16BE, and SQLITE_UTF16LE.
Referenced by sqlite3FindFunction().
int sqlite3CheckCollSeq (Parse * pParse, CollSeq * pColl)
Definition at line 123 of file callback.c.
References Parse::db, Parse::nErr, sqlite3ErrorMsg(), sqlite3GetCollSeq(), SQLITE_ERROR, SQLITE_OK, and CollSeq::zName.
Referenced by sqlite3ExprCollSeq().
CollSeq* sqlite3FindCollSeq (sqlite3 * db, u8 enc, const char * zName, int nName, int create)
Definition at line 206 of file callback.c.
References findCollSeqEntry(), sqlite3::pDfltColl, SQLITE_UTF16BE, SQLITE_UTF16LE, and SQLITE_UTF8.
Referenced by createCollation(), openDatabase(), sqlite3ExprCollSeq(), sqlite3FindInIndex(), sqlite3GetCollSeq(), sqlite3InitOne(), sqlite3LocateCollSeq(), sqlite3Reindex(), and synthCollSeq().
FuncDef* sqlite3FindFunction (sqlite3 * db, const char * zName, int nName, int nArg, u8 enc, int createFlag)
Definition at line 326 of file callback.c.
References FuncDefHash::a, sqlite3::aFunc, ArraySize, functionSearch(), GLOBAL, FuncDef::iPrefEnc, matchQuality(), FuncDef::nArg, FuncDef::pNext, sqlite3DbMallocZero(), sqlite3FuncDefInsert(), sqlite3GlobalFunctions, sqlite3UpperToLower, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, FuncDef::xFunc, FuncDef::xStep, and FuncDef::zName.
Referenced by analyzeAggregate(), resolveExprStep(), setLikeOptFlag(), sqlite3_overload_function(), sqlite3CreateFunc(), sqlite3ExprCodeTarget(), and sqlite3IsLikeFunction().
void sqlite3FuncDefInsert (FuncDefHash * pHash, FuncDef * pDef)
Definition at line 285 of file callback.c.
References FuncDefHash::a, ArraySize, functionSearch(), FuncDef::pHash, FuncDef::pNext, sqlite3UpperToLower, and FuncDef::zName.
Referenced by sqlite3FindFunction(), sqlite3RegisterDateTimeFunctions(), and sqlite3RegisterGlobalFunctions().
CollSeq* sqlite3GetCollSeq (sqlite3 * db, CollSeq * pColl, const char * zName, int nName)
Definition at line 86 of file callback.c.
References callCollNeeded(), ENC, sqlite3FindCollSeq(), synthCollSeq(), and CollSeq::xCmp.
Referenced by sqlite3CheckCollSeq(), and sqlite3LocateCollSeq().
void sqlite3SchemaFree (void * p)
Definition at line 405 of file callback.c.
References Schema::aFKey, DB_SchemaLoaded, Schema::flags, Schema::idxHash, Schema::pSeqTab, sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3HashClear(), sqlite3HashInit(), sqliteHashData, sqliteHashFirst, sqliteHashNext, Schema::tblHash, and Schema::trigHash.
Referenced by sqlite3ResetInternalSchema(), and sqlite3SchemaGet().
Schema* sqlite3SchemaGet (sqlite3 * db, Btree * pBt)
Definition at line 434 of file callback.c.
References Schema::aFKey, Schema::enc, Schema::file_format, Schema::idxHash, sqlite3::mallocFailed, sqlite3BtreeSchema(), sqlite3HashInit(), sqlite3MallocZero(), sqlite3SchemaFree(), SQLITE_UTF8, Schema::tblHash, and Schema::trigHash.
Referenced by attachFunc(), and openDatabase().
static int synthCollSeq (sqlite3 * db, CollSeq * pColl) [static]
Definition at line 56 of file callback.c.
References sqlite3FindCollSeq(), SQLITE_ERROR, SQLITE_OK, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, CollSeq::xCmp, CollSeq::xDel, and CollSeq::zName.
Referenced by sqlite3GetCollSeq().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1