ContextLogger2 Logger Daemon Internals: cf_query.c File Reference
cf_query.c File Reference
Defines
#define get_lua_value(name, L, err) get_lua_value_wd(name,NULL,L,err)
Functions
static gboolean eval_lua_str (const gchar *luaStr, lua_State **pL, GError **error)
static gboolean get_lua_value_wd (const gchar *name, const gchar *defStr, lua_State **pL, GError **error)
static gboolean get_int_from_lua (lua_State *L, int *value, GError **error)
gboolean try_get_ConfigDb_int (const gchar *name, int *value, gboolean *found, GError **error)
gboolean get_ConfigDb_int (const gchar *name, int *value, int default_value, GError **error)
int force_get_ConfigDb_int (const gchar *name, int default_value)
int force_lua_eval_int (const gchar *luaStr, int default_value)
static gboolean get_bool_from_lua (lua_State *L, gboolean *value, GError **error)
gboolean try_get_ConfigDb_bool (const gchar *name, gboolean *value, gboolean *found, GError **error)
gboolean get_ConfigDb_bool (const gchar *name, gboolean *value, gboolean default_value, GError **error)
gboolean force_get_ConfigDb_bool (const gchar *name, gboolean default_value)
gboolean force_lua_eval_bool (const gchar *luaStr, gboolean default_value)
gboolean try_get_ConfigDb_str (const gchar *name, gchar **s, GError **error)
gboolean get_ConfigDb_str (const gchar *name, gchar **s, const gchar *default_s, GError **error)
int get_config_iap_id ()
const gchar * get_config_username ()
Define Documentation
#define get_lua_value (name, L, err) get_lua_value_wd(name,NULL,L,err)
Definition at line 81 of file cf_query.c.
Referenced by try_get_ConfigDb_bool(), try_get_ConfigDb_int(), and try_get_ConfigDb_str().
Function Documentation
static gboolean eval_lua_str (const gchar * luaStr, lua_State ** pL, GError ** error) [static]
Definition at line 17 of file cf_query.c.
References cl_lua_new_libs(), gx_error_no_memory, lua_close(), lua_isnil, lua_pcall(), lua_set_gerror(), and luaL_loadstring().
Referenced by force_lua_eval_bool(), force_lua_eval_int(), and get_lua_value_wd().
gboolean force_get_ConfigDb_bool (const gchar * name, gboolean default_value)
Definition at line 198 of file cf_query.c.
References try_get_ConfigDb_bool().
Referenced by _rk_Remokon::_rk_Remokon(), and sensor_autostart_is_allowed().
int force_get_ConfigDb_int (const gchar * name, int default_value)
Definition at line 131 of file cf_query.c.
References try_get_ConfigDb_int().
Referenced by CSensor_cellpos::ReadConfig().
gboolean force_lua_eval_bool (const gchar * luaStr, gboolean default_value)
Definition at line 205 of file cf_query.c.
References eval_lua_str(), get_bool_from_lua(), and lua_close().
Referenced by rk_Remokon_reconfigure().
int force_lua_eval_int (const gchar * luaStr, int default_value)
Definition at line 138 of file cf_query.c.
References eval_lua_str(), get_int_from_lua(), and lua_close().
Referenced by rk_Remokon_reconfigure().
static gboolean get_bool_from_lua (lua_State * L, gboolean * value, GError ** error) [static]
Definition at line 154 of file cf_query.c.
References code_type_error, domain_cl2app, gx_error_new(), lua_isboolean, and lua_toboolean().
Referenced by force_lua_eval_bool(), and try_get_ConfigDb_bool().
int get_config_iap_id ()
Definition at line 269 of file cf_query.c.
References ac_STATIC_GET, and try_get_ConfigDb_int().
Referenced by _rk_Remokon::_rk_Remokon(), current_iap_is_cellular(), and CUploader::RefreshIap().
const gchar* get_config_username ()
Definition at line 280 of file cf_query.c.
References ac_STATIC_GET.
Referenced by CUploader::CreatePosterAoL(), and CFileDataSupplier::OpenL().
gboolean get_ConfigDb_bool (const gchar * name, gboolean * value, gboolean default_value, GError ** error)
Definition at line 187 of file cf_query.c.
References try_get_ConfigDb_bool().
gboolean get_ConfigDb_int (const gchar * name, int * value, int default_value, GError ** error)
Definition at line 120 of file cf_query.c.
References try_get_ConfigDb_int().
gboolean get_ConfigDb_str (const gchar * name, gchar ** s, const gchar * default_s, GError ** error)
Definition at line 253 of file cf_query.c.
References gx_error_no_memory, and try_get_ConfigDb_str().
Referenced by CUploader::RefreshSnapshotTimeExpr().
static gboolean get_int_from_lua (lua_State * L, int * value, GError ** error) [static]
Definition at line 87 of file cf_query.c.
References code_type_error, domain_cl2app, gx_error_new(), lua_isnumber(), and lua_tonumber().
Referenced by force_lua_eval_int(), and try_get_ConfigDb_int().
static gboolean get_lua_value_wd (const gchar * name, const gchar * defStr, lua_State ** pL, GError ** error) [static]
Definition at line 49 of file cf_query.c.
References ac_DYNAMIC_GET_ERR, eval_lua_str(), gx_propagate_error(), and is_not_found_error.
gboolean try_get_ConfigDb_bool (const gchar * name, gboolean * value, gboolean * found, GError ** error)
Definition at line 169 of file cf_query.c.
References get_bool_from_lua(), get_lua_value, and lua_close().
Referenced by force_get_ConfigDb_bool(), and get_ConfigDb_bool().
gboolean try_get_ConfigDb_int (const gchar * name, int * value, gboolean * found, GError ** error)
Definition at line 102 of file cf_query.c.
References get_int_from_lua(), get_lua_value, and lua_close().
Referenced by force_get_ConfigDb_int(), get_config_iap_id(), get_ConfigDb_int(), and CSensor_btprox::RefreshBaseScanIntervalSecs().
gboolean try_get_ConfigDb_str (const gchar * name, gchar ** s, GError ** error)
Definition at line 221 of file cf_query.c.
References code_type_error, domain_cl2app, get_lua_value, gx_error_new(), gx_error_no_memory, lua_close(), lua_isstring(), and lua_tostring.
Referenced by get_ConfigDb_str().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1