ContextLogger2 Logger Daemon Internals: cl2appappui.cpp File Reference
cl2appappui.cpp File Reference
Defines
#define KEnableSkinFlag 0x1000
#define KLayoutAwareFlag 0x08
Functions
void ExitApplication ()
void ShutdownApplication ()
void KillLogger ()
static void DisplayText (TDesC const &aText)
Define Documentation
#define KEnableSkinFlag 0x1000
Definition at line 16 of file cl2appappui.cpp.
Referenced by CCl2appAppUi::ConstructL().
#define KLayoutAwareFlag 0x08
Definition at line 17 of file cl2appappui.cpp.
Referenced by CCl2appAppUi::ConstructL().
Function Documentation
static void DisplayText (TDesC const & aText) [static]
Definition at line 64 of file cl2appappui.cpp.
Referenced by CCl2appAppUi::ConstructL(), and CCl2appAppUi::Start().
void ExitApplication ()
Definition at line 20 of file cl2appappui.cpp.
References logt.
Referenced by ShutdownApplication().
void KillLogger ()
Definition at line 48 of file cl2appappui.cpp.
References logt.
void ShutdownApplication ()
Definition at line 28 of file cl2appappui.cpp.
References logg, and logt.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1