ContextLogger2 Logger Daemon Internals: CCl2appDocument Class Reference
CCl2appDocument Class Reference
#include <cl2appdocument.h>
Public Member Functions
virtual ~CCl2appDocument ()
Static Public Member Functions
static CCl2appDocument * NewL (CEikApplication &aApp)
Private Member Functions
CCl2appDocument (CEikApplication &aApp)
void ConstructL ()
CEikAppUi * CreateAppUiL ()
Detailed Description
Definition at line 10 of file cl2appdocument.h.
Constructor & Destructor Documentation
CCl2appDocument::~CCl2appDocument () [virtual]
Definition at line 15 of file cl2appdocument.cpp.
CCl2appDocument::CCl2appDocument (CEikApplication & aApp) [private]
Definition at line 10 of file cl2appdocument.cpp.
Referenced by NewL().
Member Function Documentation
void CCl2appDocument::ConstructL () [private]
Definition at line 19 of file cl2appdocument.cpp.
CEikAppUi * CCl2appDocument::CreateAppUiL () [private]
Definition at line 32 of file cl2appdocument.cpp.
CCl2appDocument * CCl2appDocument::NewL (CEikApplication & aApp) [static]
Definition at line 23 of file cl2appdocument.cpp.
References CCl2appDocument().
Referenced by CCl2appApp::CreateDocumentL().
The documentation for this class was generated from the following files:
cl2appdocument.h
cl2appdocument.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1