ContextLogger2 Logger Daemon Internals: MainWindow Class Reference
MainWindow Class Reference
#include <window_demo_qt.hpp>
Public Member Functions
MainWindow (QWidget *parent=0)
Private Slots
void uploadNow ()
void remokonNow ()
Private Attributes
QListView * listView
QStringList stringList
QsKineticScroller * iScroller
Detailed Description
Definition at line 12 of file window_demo_qt.hpp.
Constructor & Destructor Documentation
MainWindow::MainWindow (QWidget * parent = 0)
Definition at line 61 of file window_demo_qt.cpp.
References QsKineticScroller::enableKineticScrollFor(), gModel, iScroller, listView, remokonNow(), stringList, and uploadNow().
Member Function Documentation
void MainWindow::remokonNow () [private, slot]
Definition at line 126 of file window_demo_qt.cpp.
References ac_global_Remokon, rk_Remokon_start_timed(), and showFreeGerror().
Referenced by MainWindow().
void MainWindow::uploadNow () [private, slot]
Definition at line 115 of file window_demo_qt.cpp.
References ac_global_Uploader, showFreeGerror(), and up_Uploader_upload_now().
Referenced by MainWindow().
Member Data Documentation
QsKineticScroller* MainWindow::iScroller [private]
Definition at line 22 of file window_demo_qt.hpp.
Referenced by MainWindow().
QListView* MainWindow::listView [private]
Definition at line 20 of file window_demo_qt.hpp.
Referenced by MainWindow().
QStringList MainWindow::stringList [private]
Definition at line 21 of file window_demo_qt.hpp.
Referenced by MainWindow().
The documentation for this class was generated from the following files:
window_demo_qt.hpp
window_demo_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1