ContextLogger2 Logger Daemon Internals: CMyWindowGroup Class Reference
CMyWindowGroup Class Reference
Public Member Functions
virtual ~CMyWindowGroup ()
RWindowGroup & Ref ()
Static Public Member Functions
static CMyWindowGroup * NewL (RWsSession &aWsSession)
Private Member Functions
CMyWindowGroup (RWsSession &aWsSession)
void ConstructL ()
DEF_SESSION (RWindowGroup, iWindowGroup)
Private Attributes
RWsSession & iWsSession
Detailed Description
Definition at line 26 of file epoc-appfocus.cpp.
Constructor & Destructor Documentation
CMyWindowGroup::~CMyWindowGroup () [virtual]
Definition at line 78 of file epoc-appfocus.cpp.
References SESSION_CLOSE_IF_OPEN.
CMyWindowGroup::CMyWindowGroup (RWsSession & aWsSession) [inline, private]
Definition at line 39 of file epoc-appfocus.cpp.
Referenced by NewL().
Member Function Documentation
void CMyWindowGroup::ConstructL () [private]
Definition at line 59 of file epoc-appfocus.cpp.
References iWsSession, and LEAVE_IF_ERROR_OR_SET_SESSION_OPEN.
Referenced by NewL().
CMyWindowGroup::DEF_SESSION (RWindowGroup , iWindowGroup) [private]
CMyWindowGroup * CMyWindowGroup::NewL (RWsSession & aWsSession) [static]
Definition at line 50 of file epoc-appfocus.cpp.
References CMyWindowGroup(), and ConstructL().
RWindowGroup& CMyWindowGroup::Ref () [inline]
Definition at line 35 of file epoc-appfocus.cpp.
Referenced by CSensor_appfocus::StartL(), and CSensor_appfocus::Stop().
Member Data Documentation
RWsSession& CMyWindowGroup::iWsSession [private]
Definition at line 45 of file epoc-appfocus.cpp.
Referenced by ConstructL().
The documentation for this class was generated from the following file:
epoc-appfocus.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1