ContextLogger2 Logger Daemon Internals: CAppContextImpl Class Reference
CAppContextImpl Class Reference
Public Member Functions
~CAppContextImpl ()
DEF_SESSION (RFs, iFs)
Public Attributes
ac_AppContext * iCtx
MAppContextInitObserver & iObs
CTelephony * iTelephony
TPlatformVersion iPlatformVersion
Private Member Functions
virtual void GotData_BatteryInfo (TInt aError)
virtual void GotData_FlightMode (TInt aError)
void GotMoreInfo ()
Private Attributes
CTOR_DECL_CAppContextImpl
CBatteryObserver * iBatteryObserver
CFlightModeObserver * iFlightModeObserver
TBool iHaveBattery
TBool iHaveFlightMode
Detailed Description
Definition at line 334 of file ac_app_context_epoc.cpp.
Constructor & Destructor Documentation
CAppContextImpl::~CAppContextImpl ()
Definition at line 419 of file ac_app_context_epoc.cpp.
References iBatteryObserver, iFlightModeObserver, iTelephony, and SESSION_CLOSE_IF_OPEN.
Member Function Documentation
CAppContextImpl::DEF_SESSION (RFs , iFs)
void CAppContextImpl::GotData_BatteryInfo (TInt aError) [private, virtual]
Implements MGetterObs_BatteryInfo.
Definition at line 388 of file ac_app_context_epoc.cpp.
References GotMoreInfo(), and iHaveBattery.
void CAppContextImpl::GotData_FlightMode (TInt aError) [private, virtual]
Implements MGetterObs_FlightMode.
Definition at line 395 of file ac_app_context_epoc.cpp.
References GotMoreInfo(), and iHaveFlightMode.
void CAppContextImpl::GotMoreInfo () [private]
Definition at line 379 of file ac_app_context_epoc.cpp.
References iHaveBattery, iHaveFlightMode, and iObs.
Referenced by GotData_BatteryInfo(), and GotData_FlightMode().
Member Data Documentation
CAppContextImpl::CTOR_DECL_CAppContextImpl [private]
Definition at line 339 of file ac_app_context_epoc.cpp.
CBatteryObserver* CAppContextImpl::iBatteryObserver [private]
Definition at line 363 of file ac_app_context_epoc.cpp.
Referenced by ~CAppContextImpl().
ac_AppContext* CAppContextImpl::iCtx
Definition at line 345 of file ac_app_context_epoc.cpp.
CFlightModeObserver* CAppContextImpl::iFlightModeObserver [private]
Definition at line 364 of file ac_app_context_epoc.cpp.
Referenced by ~CAppContextImpl().
TBool CAppContextImpl::iHaveBattery [private]
Definition at line 372 of file ac_app_context_epoc.cpp.
Referenced by GotData_BatteryInfo(), and GotMoreInfo().
TBool CAppContextImpl::iHaveFlightMode [private]
Definition at line 373 of file ac_app_context_epoc.cpp.
Referenced by GotData_FlightMode(), and GotMoreInfo().
MAppContextInitObserver& CAppContextImpl::iObs
Definition at line 349 of file ac_app_context_epoc.cpp.
Referenced by GotMoreInfo().
TPlatformVersion CAppContextImpl::iPlatformVersion
Definition at line 360 of file ac_app_context_epoc.cpp.
CTelephony* CAppContextImpl::iTelephony
Definition at line 354 of file ac_app_context_epoc.cpp.
Referenced by ~CAppContextImpl().
The documentation for this class was generated from the following file:
ac_app_context_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1