ContextLogger2 Logger Daemon Internals: CSensor_callstatus Class Reference
CSensor_callstatus Class Reference
#include <epoc-callstatus.hpp>
Public Member Functions
virtual ~CSensor_callstatus ()
gboolean StartL (GError **error)
void Stop ()
TBool IsActive () const
Private Types
enum TState {
EInactive = 0, EQueryingFlightMode, EQueryingCallStatus, ERetryWaiting,
EInFlightMode
}
Private Member Functions
virtual void RetryTimerExpired (CRetryAo *src, TInt errCode)
virtual void GotData_FlightMode (TInt aError)
virtual void ChangedData_FlightMode (TInt aError)
virtual void ChangedData_CallStatus (TInt aError)
void Cancel ()
LogDb * GetLogDb () const
Private Attributes
CTOR_DECL_CSensor_callstatus
ac_AppContext * iAppContext
CTelephony * iTelephony
CRetryAo * iRetryAo
CGetterAo_FlightMode * iFlightModeGetter
CNotifyAo_FlightMode * iFlightModeNotifier
CNotifyAo_CallStatus * iCallStatusNotifier
TState iState
Detailed Description
Definition at line 54 of file epoc-callstatus.hpp.
Member Enumeration Documentation
enum CSensor_callstatus::TState [private]
Enumerator:
EInactive
EQueryingFlightMode
EQueryingCallStatus
ERetryWaiting
EInFlightMode
Definition at line 108 of file epoc-callstatus.hpp.
Constructor & Destructor Documentation
CSensor_callstatus::~CSensor_callstatus () [virtual]
Definition at line 88 of file epoc-callstatus.cpp.
References iCallStatusNotifier, iFlightModeGetter, iFlightModeNotifier, iRetryAo, and iTelephony.
Member Function Documentation
void CSensor_callstatus::Cancel () [private]
Definition at line 97 of file epoc-callstatus.cpp.
References EInactive, iCallStatusNotifier, iFlightModeGetter, iFlightModeNotifier, iRetryAo, and iState.
Referenced by ChangedData_CallStatus(), ChangedData_FlightMode(), GotData_FlightMode(), RetryTimerExpired(), and Stop().
void CSensor_callstatus::ChangedData_CallStatus (TInt aError) [private, virtual]
Implements MNotifyObs_CallStatus.
Definition at line 169 of file epoc-callstatus.cpp.
References Cancel(), CNotifyAo_CallStatus::Data(), DoGetCallInfo(), EQueryingCallStatus, ERetryWaiting, GetLogDb(), guilogf(), gx_txtlog_fatal_error_free(), iCallStatusNotifier, iRetryAo, iState, iTelephony, LocalEpocTimeToUnixTime(), log_db_log_callstatus(), log_db_log_status(), logg, logt, CNotifyAo_CallStatus::MakeRequest(), plat_error_strerror, CRetryAo::ResetFailures(), CRetryAo::Retry(), and SET_NUMBER_AND_CONTACT.
void CSensor_callstatus::ChangedData_FlightMode (TInt aError) [private, virtual]
Implements MNotifyObs_FlightMode.
Definition at line 147 of file epoc-callstatus.cpp.
References Cancel(), CNotifyAo_FlightMode::Data(), EInFlightMode, EQueryingCallStatus, GetLogDb(), iCallStatusNotifier, iFlightModeNotifier, iRetryAo, iState, log_db_log_status(), CNotifyAo_FlightMode::MakeRequest(), CNotifyAo_CallStatus::MakeRequest(), plat_error_strerror, and TFlightModeV1ToBoolean().
LogDb* CSensor_callstatus::GetLogDb () const [inline, private]
Definition at line 123 of file epoc-callstatus.hpp.
References ac_LogDb().
Referenced by ChangedData_CallStatus(), ChangedData_FlightMode(), GotData_FlightMode(), and RetryTimerExpired().
void CSensor_callstatus::GotData_FlightMode (TInt aError) [private, virtual]
Implements MGetterObs_FlightMode.
Definition at line 126 of file epoc-callstatus.cpp.
References Cancel(), CGetterAo_FlightMode::Data(), EInFlightMode, EQueryingCallStatus, GetLogDb(), iCallStatusNotifier, iFlightModeGetter, iFlightModeNotifier, iState, log_db_log_status(), logg, CNotifyAo_FlightMode::MakeRequest(), CNotifyAo_CallStatus::MakeRequest(), plat_error_strerror, and TFlightModeV1ToBoolean().
TBool CSensor_callstatus::IsActive () const [inline]
Definition at line 119 of file epoc-callstatus.hpp.
Referenced by StartL(), and Stop().
void CSensor_callstatus::RetryTimerExpired (CRetryAo * src, TInt errCode) [private, virtual]
Implements MRetryAoObserver.
Definition at line 355 of file epoc-callstatus.cpp.
References Cancel(), EQueryingCallStatus, GetLogDb(), iCallStatusNotifier, iState, log_db_log_status(), CNotifyAo_CallStatus::MakeRequest(), and plat_error_strerror.
gboolean CSensor_callstatus::StartL (GError ** error)
Definition at line 106 of file epoc-callstatus.cpp.
References EQueryingFlightMode, iFlightModeGetter, iRetryAo, IsActive(), iState, CGetterAo_FlightMode::MakeRequest(), and CRetryAo::ResetFailures().
void CSensor_callstatus::Stop ()
Definition at line 117 of file epoc-callstatus.cpp.
References Cancel(), and IsActive().
Member Data Documentation
CSensor_callstatus::CTOR_DECL_CSensor_callstatus [private]
Definition at line 61 of file epoc-callstatus.hpp.
ac_AppContext* CSensor_callstatus::iAppContext [private]
Definition at line 96 of file epoc-callstatus.hpp.
CNotifyAo_CallStatus* CSensor_callstatus::iCallStatusNotifier [private]
Definition at line 106 of file epoc-callstatus.hpp.
Referenced by Cancel(), ChangedData_CallStatus(), ChangedData_FlightMode(), GotData_FlightMode(), RetryTimerExpired(), and ~CSensor_callstatus().
CGetterAo_FlightMode* CSensor_callstatus::iFlightModeGetter [private]
Definition at line 102 of file epoc-callstatus.hpp.
Referenced by Cancel(), GotData_FlightMode(), StartL(), and ~CSensor_callstatus().
CNotifyAo_FlightMode* CSensor_callstatus::iFlightModeNotifier [private]
Definition at line 104 of file epoc-callstatus.hpp.
Referenced by Cancel(), ChangedData_FlightMode(), GotData_FlightMode(), and ~CSensor_callstatus().
CRetryAo* CSensor_callstatus::iRetryAo [private]
Definition at line 100 of file epoc-callstatus.hpp.
Referenced by Cancel(), ChangedData_CallStatus(), ChangedData_FlightMode(), StartL(), and ~CSensor_callstatus().
TState CSensor_callstatus::iState [private]
Definition at line 115 of file epoc-callstatus.hpp.
Referenced by Cancel(), ChangedData_CallStatus(), ChangedData_FlightMode(), GotData_FlightMode(), RetryTimerExpired(), and StartL().
CTelephony* CSensor_callstatus::iTelephony [private]
Definition at line 98 of file epoc-callstatus.hpp.
Referenced by ChangedData_CallStatus(), and ~CSensor_callstatus().
The documentation for this class was generated from the following files:
epoc-callstatus.hpp
epoc-callstatus.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1