ContextLogger2 Logger Daemon Internals: CSensor_inactivity Class Reference
CSensor_inactivity Class Reference
#include <epoc-inactivity.hpp>
Public Member Functions
virtual ~CSensor_inactivity ()
gboolean StartL (GError **error)
void Stop ()
Private Types
enum EState { EUnknown, EIdle, EActive }
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
void MakeRequest ()
void GetState ()
DEF_SESSION (RTimer, iTimer)
Private Attributes
CTOR_DECL_CSensor_inactivity
ac_AppContext * iC
EState iCurrentState
Detailed Description
Definition at line 50 of file epoc-inactivity.hpp.
Member Enumeration Documentation
enum CSensor_inactivity::EState [private]
Enumerator:
EUnknown
EIdle
EActive
Definition at line 74 of file epoc-inactivity.hpp.
Constructor & Destructor Documentation
CSensor_inactivity::~CSensor_inactivity () [virtual]
Definition at line 64 of file epoc-inactivity.cpp.
References IS_SESSION_OPEN.
Member Function Documentation
CSensor_inactivity::DEF_SESSION (RTimer , iTimer) [private]
void CSensor_inactivity::DoCancel () [private, virtual]
Definition at line 119 of file epoc-inactivity.cpp.
void CSensor_inactivity::GetState () [private]
Definition at line 141 of file epoc-inactivity.cpp.
References EActive, EIdle, iCurrentState, and TIMEOUT_SECS.
Referenced by StartL().
void CSensor_inactivity::MakeRequest () [private]
Definition at line 124 of file epoc-inactivity.cpp.
References EIdle, iCurrentState, and TIMEOUT_SECS.
Referenced by RunL(), and StartL().
void CSensor_inactivity::RunL () [private, virtual]
Definition at line 92 of file epoc-inactivity.cpp.
References ac_LogDb(), EActive, EIdle, guilogf(), gx_txtlog_fatal_error_free(), iC, iCurrentState, iLogDb, log_db_log_inactivity(), log_db_log_status(), and MakeRequest().
gboolean CSensor_inactivity::StartL (GError ** error)
Definition at line 74 of file epoc-inactivity.cpp.
References GetState(), and MakeRequest().
void CSensor_inactivity::Stop ()
Definition at line 84 of file epoc-inactivity.cpp.
Member Data Documentation
CSensor_inactivity::CTOR_DECL_CSensor_inactivity [private]
Definition at line 52 of file epoc-inactivity.hpp.
ac_AppContext* CSensor_inactivity::iC [private]
Definition at line 71 of file epoc-inactivity.hpp.
Referenced by RunL().
EState CSensor_inactivity::iCurrentState [private]
Definition at line 75 of file epoc-inactivity.hpp.
Referenced by GetState(), MakeRequest(), and RunL().
The documentation for this class was generated from the following files:
epoc-inactivity.hpp
epoc-inactivity.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1