ContextLogger2 Logger Daemon Internals: Sensor_proximity Class Reference
Sensor_proximity Class Reference
#include <sa_sensor_proximity_qt.hpp>
Public Member Functions
Sensor_proximity (ac_AppContext *aAppContext)
Private Member Functions
virtual const char * Name () const
virtual void handleReadingChanged ()
Detailed Description
Definition at line 9 of file sa_sensor_proximity_qt.hpp.
Constructor & Destructor Documentation
Sensor_proximity::Sensor_proximity (ac_AppContext * aAppContext)
Definition at line 12 of file sa_sensor_proximity_qt.cpp.
References ClQtEventSensorBase::run().
Referenced by new_Sensor_proximity().
Member Function Documentation
void Sensor_proximity::handleReadingChanged () [private, virtual]
Implements ClQtEventSensorBase.
Definition at line 23 of file sa_sensor_proximity_qt.cpp.
References ClQtEventSensorBase::GetLogDb(), guilogf(), and log_db_log_proximity().
const char * Sensor_proximity::Name () const [private, virtual]
Implements ClQtEventSensorBase.
Definition at line 18 of file sa_sensor_proximity_qt.cpp.
The documentation for this class was generated from the following files:
sa_sensor_proximity_qt.hpp
sa_sensor_proximity_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1