ContextLogger2 Logger Daemon Internals: i_handle_received_sms Class Reference
i_handle_received_sms Class Reference
#include <ut_sms_epoc.hpp>
Public Member Functions
virtual void handle_reception (const TMsvId &entry_id, const TMsvId &folder_id, const TDesC &sender, CRichText &body)=0
virtual void handle_reception (const TMsvId &entry_id, const TMsvId &folder_id, TUid aMtmUid, CBaseMtm *aMtm)
virtual void handle_error (TInt aError)=0
virtual void handle_close ()=0
virtual void handle_sending (const TMsvId &entry_id, const TDesC &sender, CRichText &body)=0
virtual void handle_sending (const TMsvId &entry_id, TUid aMtmUid, CBaseMtm *aMtm)
Detailed Description
Definition at line 59 of file ut_sms_epoc.hpp.
Member Function Documentation
virtual void i_handle_received_sms::handle_close () [pure virtual]
Implemented in CSensor_smsevent.
Referenced by CSmsEventNotifier::DoHandleSessionEventL().
virtual void i_handle_received_sms::handle_error (TInt aError) [pure virtual]
Implemented in CSensor_smsevent.
Referenced by CSmsEventNotifier::HandleErrorL().
void i_handle_received_sms::handle_reception (const TMsvId & entry_id, const TMsvId & folder_id, TUid aMtmUid, CBaseMtm * aMtm) [virtual]
Definition at line 78 of file ut_sms_epoc.cpp.
References handle_reception().
virtual void i_handle_received_sms::handle_reception (const TMsvId & entry_id, const TMsvId & folder_id, const TDesC & sender, CRichText & body) [pure virtual]
Implemented in CSensor_smsevent.
Referenced by handle_reception(), and CSmsEventNotifier::HandleReceivedL().
void i_handle_received_sms::handle_sending (const TMsvId & entry_id, TUid aMtmUid, CBaseMtm * aMtm) [virtual]
Definition at line 95 of file ut_sms_epoc.cpp.
References handle_sending().
virtual void i_handle_received_sms::handle_sending (const TMsvId & entry_id, const TDesC & sender, CRichText & body) [pure virtual]
Implemented in CSensor_smsevent.
Referenced by handle_sending(), and CSmsEventNotifier::HandleSentL().
The documentation for this class was generated from the following files:
ut_sms_epoc.hpp
ut_sms_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1