ContextLogger2 Logger Daemon Internals: CCliapiSession Class Reference
CCliapiSession Class Reference
Public Member Functions
CCliapiSession ()
void CreateL ()
void Send (const TDesC &aMessage)
Private Member Functions
~CCliapiSession ()
CCliapiServer & Server ()
void ServiceL (const RMessage2 &aMessage)
void ServiceError (const RMessage2 &aMessage, TInt aError)
TBool ReceivePending () const
Private Attributes
RMessagePtr2 iReceiveMsg
TInt iReceiveLen
Detailed Description
Definition at line 50 of file epoc-cliapi-server.cpp.
Constructor & Destructor Documentation
CCliapiSession::CCliapiSession () [inline]
Definition at line 143 of file epoc-cliapi-server.cpp.
CCliapiSession::~CCliapiSession () [private]
Definition at line 164 of file epoc-cliapi-server.cpp.
References CCliapiServer::DropSession(), and Server().
Member Function Documentation
void CCliapiSession::CreateL ()
Definition at line 156 of file epoc-cliapi-server.cpp.
References CCliapiServer::AddSession(), and Server().
TBool CCliapiSession::ReceivePending () const [inline, private]
Definition at line 151 of file epoc-cliapi-server.cpp.
References iReceiveMsg.
Referenced by Send().
void CCliapiSession::Send (const TDesC & aMessage)
Definition at line 169 of file epoc-cliapi-server.cpp.
References EPanicBadDescriptor, iReceiveLen, iReceiveMsg, PanicClient(), and ReceivePending().
CCliapiServer & CCliapiSession::Server () [inline, private]
Definition at line 146 of file epoc-cliapi-server.cpp.
Referenced by CreateL(), and ~CCliapiSession().
void CCliapiSession::ServiceError (const RMessage2 & aMessage, TInt aError) [private]
Definition at line 428 of file epoc-cliapi-server.cpp.
void CCliapiSession::ServiceL (const RMessage2 & aMessage) [private]
Definition at line 198 of file epoc-cliapi-server.cpp.
References cl_lua_new_libs(), EEvalGetResult, EPanicIllegalFunction, ETickCountFresh, ETryEvalScript, logg, logt, LUA_ERRERR, LUA_ERRMEM, LUA_ERRRUN, LUA_ERRSYNTAX, lua_isnone, lua_pcall(), lua_tostring, luaL_loadstring(), luaResultBuf_size, PanicClient(), and TRAP_OOM_FAIL.
Member Data Documentation
TInt CCliapiSession::iReceiveLen [private]
Definition at line 64 of file epoc-cliapi-server.cpp.
Referenced by Send().
RMessagePtr2 CCliapiSession::iReceiveMsg [private]
Definition at line 63 of file epoc-cliapi-server.cpp.
Referenced by ReceivePending(), and Send().
The documentation for this class was generated from the following file:
epoc-cliapi-server.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1