ContextLogger2 Logger Daemon Internals: CUtTimer Class Reference
CUtTimer Class Reference
Static Public Member Functions
static CUtTimer * NewLC (ut_Timer &aInterface, TInt aPriority)
static CUtTimer * NewL (ut_Timer &aInterface, TInt aPriority)
Private Member Functions
CUtTimer (ut_Timer &aInterface, TInt aPriority)
virtual void RunL ()
Private Attributes
ut_Timer & iInterface
Detailed Description
Definition at line 17 of file ut_timer_epoc.cpp.
Constructor & Destructor Documentation
CUtTimer::CUtTimer (ut_Timer & aInterface, TInt aPriority) [private]
Definition at line 50 of file ut_timer_epoc.cpp.
Referenced by NewLC().
Member Function Documentation
CUtTimer * CUtTimer::NewL (ut_Timer & aInterface, TInt aPriority) [static]
Definition at line 43 of file ut_timer_epoc.cpp.
References NewLC().
Referenced by ut_Timer_new().
CUtTimer * CUtTimer::NewLC (ut_Timer & aInterface, TInt aPriority) [static]
Definition at line 35 of file ut_timer_epoc.cpp.
References CUtTimer().
Referenced by NewL().
void CUtTimer::RunL () [private, virtual]
Definition at line 60 of file ut_timer_epoc.cpp.
References _ut_Timer::cb, error(), iInterface, make_error, and _ut_Timer::userdata.
Member Data Documentation
ut_Timer& CUtTimer::iInterface [private]
Definition at line 32 of file ut_timer_epoc.cpp.
Referenced by RunL().
The documentation for this class was generated from the following file:
ut_timer_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1