ContextLogger2 Logger Daemon Internals: CCliapiServer Class Reference
CCliapiServer Class Reference
#include <epoc-cliapi-server.hpp>
Public Member Functions
TInt Start ()
void AddSession ()
void DropSession ()
void Send (const TDesC &aMessage)
Static Public Member Functions
static CCliapiServer * NewLC ()
static CCliapiServer * NewL ()
Private Member Functions
CCliapiServer ()
void ConstructL ()
CSession2 * NewSessionL (const TVersion &aVersion, const RMessage2 &aMessage) const
Private Attributes
TInt iSessionCount
Detailed Description
Definition at line 28 of file epoc-cliapi-server.hpp.
Constructor & Destructor Documentation
CCliapiServer::CCliapiServer () [inline, private]
Definition at line 77 of file epoc-cliapi-server.cpp.
Member Function Documentation
void CCliapiServer::AddSession ()
Definition at line 112 of file epoc-cliapi-server.cpp.
References iSessionCount.
Referenced by CCliapiSession::CreateL().
void CCliapiServer::ConstructL () [private]
Definition at line 96 of file epoc-cliapi-server.cpp.
void CCliapiServer::DropSession ()
Definition at line 120 of file epoc-cliapi-server.cpp.
References iSessionCount.
Referenced by CCliapiSession::~CCliapiSession().
CCliapiServer * CCliapiServer::NewL () [static]
Definition at line 89 of file epoc-cliapi-server.cpp.
References NewLC().
Referenced by LocalServer_start().
CCliapiServer * CCliapiServer::NewLC () [static]
Definition at line 81 of file epoc-cliapi-server.cpp.
Referenced by NewL().
CSession2 * CCliapiServer::NewSessionL (const TVersion & aVersion, const RMessage2 & aMessage) const [private]
Definition at line 104 of file epoc-cliapi-server.cpp.
void CCliapiServer::Send (const TDesC & aMessage)
Definition at line 128 of file epoc-cliapi-server.cpp.
TInt CCliapiServer::Start ()
Definition at line 71 of file epoc-cliapi-server.cpp.
Referenced by LocalServer_start().
Member Data Documentation
TInt CCliapiServer::iSessionCount [private]
Definition at line 53 of file epoc-cliapi-server.hpp.
Referenced by AddSession(), and DropSession().
The documentation for this class was generated from the following files:
epoc-cliapi-server.hpp
epoc-cliapi-server.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1