ContextLogger2 Logger Daemon Internals: CSensor_httpurl Class Reference
CSensor_httpurl Class Reference
#include <epoc-httpurl.hpp>
Public Member Functions
virtual ~CSensor_httpurl ()
Static Public Member Functions
static CSensor_httpurl * NewLC (ac_AppContext *aAppContext)
static CSensor_httpurl * NewL (ac_AppContext *aAppContext)
Private Member Functions
CSensor_httpurl (ac_AppContext *aAppContext)
void ConstructL ()
DEF_SESSION (RProperty, iProperty)
LogDb * GetLogDb () const
void MakeRequest ()
virtual void DoCancel ()
virtual TInt RunError (TInt errCode)
virtual void RunL ()
Private Attributes
ac_AppContext * iAppContext
Detailed Description
Definition at line 17 of file epoc-httpurl.hpp.
Constructor & Destructor Documentation
CSensor_httpurl::~CSensor_httpurl () [virtual]
Definition at line 36 of file epoc-httpurl.cpp.
References SESSION_CLOSE_IF_OPEN.
CSensor_httpurl::CSensor_httpurl (ac_AppContext * aAppContext) [private]
Definition at line 42 of file epoc-httpurl.cpp.
Referenced by NewLC().
Member Function Documentation
void CSensor_httpurl::ConstructL () [private]
Definition at line 49 of file epoc-httpurl.cpp.
References LEAVE_IF_ERROR_OR_SET_SESSION_OPEN, and MakeRequest().
Referenced by NewLC().
CSensor_httpurl::DEF_SESSION (RProperty , iProperty) [private]
void CSensor_httpurl::DoCancel () [private, virtual]
Definition at line 71 of file epoc-httpurl.cpp.
References IS_SESSION_OPEN.
LogDb* CSensor_httpurl::GetLogDb () const [inline, private]
Definition at line 34 of file epoc-httpurl.hpp.
References ac_LogDb().
Referenced by RunL().
void CSensor_httpurl::MakeRequest () [private]
Definition at line 65 of file epoc-httpurl.cpp.
Referenced by ConstructL(), and RunL().
CSensor_httpurl * CSensor_httpurl::NewL (ac_AppContext * aAppContext) [static]
Definition at line 29 of file epoc-httpurl.cpp.
References NewLC().
CSensor_httpurl * CSensor_httpurl::NewLC (ac_AppContext * aAppContext) [static]
Definition at line 21 of file epoc-httpurl.cpp.
References ConstructL(), and CSensor_httpurl().
Referenced by NewL().
TInt CSensor_httpurl::RunError (TInt errCode) [private, virtual]
Definition at line 77 of file epoc-httpurl.cpp.
References er_log_symbian.
void CSensor_httpurl::RunL () [private, virtual]
Definition at line 83 of file epoc-httpurl.cpp.
References er_log_symbian, GetLogDb(), guilogf(), log_db_log_httpurl(), and MakeRequest().
Member Data Documentation
ac_AppContext* CSensor_httpurl::iAppContext [private]
Definition at line 30 of file epoc-httpurl.hpp.
The documentation for this class was generated from the following files:
epoc-httpurl.hpp
epoc-httpurl.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1