ContextLogger2 Logger Daemon Internals: _rk_Remokon Class Reference
_rk_Remokon Class Reference
#include <rk_remokon_qt.hpp>
Public Member Functions
_rk_Remokon ()
~_rk_Remokon ()
void start ()
void stop ()
void startTimed (int secs)
void send (const QString &toJid, const QString &msgText)
Public Attributes
struct {
const char * server
int port
const char * password
const char * jid
int iap_id
} params
QXmppClient iSession
bool iIsActive
bool iHaveConfig
bool iAutostartEnabled
lua_State * L
Private Slots
void gotJabberError (QXmppClient::Error anError)
void gotJabberMessage (const QXmppMessage &aMessage)
void runTimeout ()
Private Member Functions
void resetRunTimer ()
Private Attributes
QXmppPresence iXmppPresence
QXmppConfiguration iXmppConfiguration
int iRunForSecs
QTimer iRunTimer
Detailed Description
Definition at line 20 of file rk_remokon_qt.hpp.
Constructor & Destructor Documentation
_rk_Remokon::_rk_Remokon ()
Definition at line 52 of file rk_remokon_qt.cpp.
References ac_STATIC_GET, error(), force_get_ConfigDb_bool(), get_config_iap_id(), gotJabberError(), gotJabberMessage(), iAutostartEnabled, iHaveConfig, iRunTimer, iSession, iXmppConfiguration, iXmppPresence, jid, logg, params, and runTimeout().
_rk_Remokon::~_rk_Remokon ()
Definition at line 113 of file rk_remokon_qt.cpp.
References L, lua_close(), and stop().
Member Function Documentation
void _rk_Remokon::gotJabberError (QXmppClient::Error anError) [private, slot]
Definition at line 178 of file rk_remokon_qt.cpp.
References er_log_none, error(), and iSession.
Referenced by _rk_Remokon().
void _rk_Remokon::gotJabberMessage (const QXmppMessage & aMessage) [private, slot]
Definition at line 230 of file rk_remokon_qt.cpp.
References L, logg, lua_gettop(), lua_isstring(), LUA_MULTRET, lua_pcall(), lua_tostring, luaL_loadstring(), LuaStack::pop, resetRunTimer(), send(), and TOCSTR.
Referenced by _rk_Remokon().
void _rk_Remokon::resetRunTimer () [private]
Definition at line 144 of file rk_remokon_qt.cpp.
References iRunForSecs, iRunTimer, and SecsToMsecs().
Referenced by gotJabberMessage(), and startTimed().
void _rk_Remokon::runTimeout () [private, slot]
Definition at line 164 of file rk_remokon_qt.cpp.
References ac_global_LogDb, iRunForSecs, log_db_log_status(), stop(), and TRAPFATAL.
Referenced by _rk_Remokon().
void _rk_Remokon::send (const QString & toJid, const QString & msgText)
Definition at line 171 of file rk_remokon_qt.cpp.
References iSession.
Referenced by gotJabberMessage().
void _rk_Remokon::start ()
Definition at line 120 of file rk_remokon_qt.cpp.
References iIsActive, iSession, iXmppConfiguration, iXmppPresence, and logh.
Referenced by startTimed().
void _rk_Remokon::startTimed (int secs)
Definition at line 153 of file rk_remokon_qt.cpp.
References iIsActive, iRunForSecs, logh, resetRunTimer(), and start().
void _rk_Remokon::stop ()
Definition at line 129 of file rk_remokon_qt.cpp.
References iIsActive, and iSession.
Referenced by runTimeout(), and ~_rk_Remokon().
Member Data Documentation
int _rk_Remokon::iap_id
Definition at line 47 of file rk_remokon_qt.hpp.
bool _rk_Remokon::iAutostartEnabled
Definition at line 67 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon().
bool _rk_Remokon::iHaveConfig
Definition at line 63 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon().
bool _rk_Remokon::iIsActive
Definition at line 58 of file rk_remokon_qt.hpp.
Referenced by start(), startTimed(), and stop().
int _rk_Remokon::iRunForSecs [private]
Definition at line 31 of file rk_remokon_qt.hpp.
Referenced by resetRunTimer(), runTimeout(), and startTimed().
QTimer _rk_Remokon::iRunTimer [private]
Definition at line 32 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon(), and resetRunTimer().
QXmppClient _rk_Remokon::iSession
Definition at line 53 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon(), gotJabberError(), send(), start(), and stop().
QXmppConfiguration _rk_Remokon::iXmppConfiguration [private]
Definition at line 29 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon(), and start().
QXmppPresence _rk_Remokon::iXmppPresence [private]
Definition at line 28 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon(), and start().
const char* _rk_Remokon::jid
Definition at line 46 of file rk_remokon_qt.hpp.
Referenced by _rk_Remokon().
lua_State* _rk_Remokon::L
Definition at line 71 of file rk_remokon_qt.hpp.
Referenced by gotJabberMessage(), new_my_lua(), and ~_rk_Remokon().
struct { ... } _rk_Remokon::params
Referenced by _rk_Remokon().
const char* _rk_Remokon::password
Definition at line 45 of file rk_remokon_qt.hpp.
int _rk_Remokon::port
Definition at line 44 of file rk_remokon_qt.hpp.
const char* _rk_Remokon::server
Definition at line 43 of file rk_remokon_qt.hpp.
The documentation for this class was generated from the following files:
rk_remokon_qt.hpp
rk_remokon_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1