ContextLogger2 Logger Daemon Internals: CWatchdog Class Reference
CWatchdog Class Reference
#include <watchdog.h>
Public Member Functions
~CWatchdog ()
void Start ()
Static Public Member Functions
static CWatchdog * NewLC (CActiveSchedulerWait &aLoop)
static CWatchdog * NewL (CActiveSchedulerWait &aLoop)
Private Member Functions
CWatchdog (CActiveSchedulerWait &aLoop)
void ConstructL ()
void UpdateAppStartTime ()
void WaitWhile (TInt aSecs)
void HandleMinorError ()
void ObserveProcess ()
void StartApp ()
void FindApp ()
void FindAppByPattern ()
void CloseProcess ()
void HandleTimerEvent (TInt errCode)
void HandleProcessHandleEvent (TInt errCode)
void ExitWatchdog (TInt errCode, char const *errText)
void Cancel ()
TBool DiedQuickly ()
Private Attributes
CActiveSchedulerWait & iLoop
CTimerAo * iTimerAo
CProcessHandleObserver * iLogonAo
RWsSession iWsSession
TBool iWsSessionOpen
RFs iFs
TBool iFsOpen
RProcess iProcess
TBool iProcessOpen
TTime iAppStartTime
TInt iNumMinorErrors
TInt64 iRandSeed
Detailed Description
Definition at line 19 of file watchdog.h.
Constructor & Destructor Documentation
CWatchdog::CWatchdog (CActiveSchedulerWait & aLoop) [private]
Definition at line 22 of file watchdog.cpp.
References iAppStartTime, iRandSeed, and UpdateAppStartTime().
Referenced by NewLC().
CWatchdog::~CWatchdog ()
Definition at line 36 of file watchdog.cpp.
References CloseProcess(), iFs, iFsOpen, iLogonAo, iTimerAo, iWsSession, and iWsSessionOpen.
Member Function Documentation
void CWatchdog::Cancel () [private]
Definition at line 224 of file watchdog.cpp.
References iLogonAo, and iTimerAo.
Referenced by ExitWatchdog().
void CWatchdog::CloseProcess () [private]
Definition at line 175 of file watchdog.cpp.
References iProcess, and iProcessOpen.
Referenced by HandleProcessHandleEvent(), and ~CWatchdog().
void CWatchdog::ConstructL () [private]
Definition at line 28 of file watchdog.cpp.
References iFs, iFsOpen, iLogonAo, iProcess, iTimerAo, iWsSession, iWsSessionOpen, and NewL().
TBool CWatchdog::DiedQuickly () [private]
Definition at line 232 of file watchdog.cpp.
References iAppStartTime.
Referenced by HandleProcessHandleEvent().
void CWatchdog::ExitWatchdog (TInt errCode, char const * errText) [private]
Definition at line 217 of file watchdog.cpp.
References Cancel(), iLoop, and logg.
Referenced by HandleTimerEvent().
void CWatchdog::FindApp () [private]
Definition at line 100 of file watchdog.cpp.
References _LIT(), FindAppByPattern(), HandleMinorError(), iProcess, iProcessOpen, logg, and ObserveProcess().
Referenced by HandleTimerEvent().
void CWatchdog::FindAppByPattern () [private]
Definition at line 125 of file watchdog.cpp.
References _LIT(), HandleMinorError(), iProcess, iProcessOpen, logg, ObserveProcess(), and StartApp().
Referenced by FindApp().
void CWatchdog::HandleMinorError () [private]
Definition at line 64 of file watchdog.cpp.
References iNumMinorErrors, iRandSeed, KNormalWait, and WaitWhile().
Referenced by FindApp(), FindAppByPattern(), HandleProcessHandleEvent(), and StartApp().
void CWatchdog::HandleProcessHandleEvent (TInt errCode) [private, virtual]
Implements MProcessHandleObserver.
Definition at line 192 of file watchdog.cpp.
References CloseProcess(), DiedQuickly(), HandleMinorError(), KNormalWait, logg, and WaitWhile().
void CWatchdog::HandleTimerEvent (TInt errCode) [private, virtual]
Implements MTimerObserver.
Definition at line 183 of file watchdog.cpp.
References ExitWatchdog(), and FindApp().
CWatchdog * CWatchdog::NewL (CActiveSchedulerWait & aLoop) [static]
Definition at line 15 of file watchdog.cpp.
References NewLC().
Referenced by ConstructL().
CWatchdog * CWatchdog::NewLC (CActiveSchedulerWait & aLoop) [static]
Definition at line 7 of file watchdog.cpp.
References CWatchdog().
Referenced by MainLoopL(), and NewL().
void CWatchdog::ObserveProcess () [private]
Definition at line 72 of file watchdog.cpp.
References iLogonAo, iProcessOpen, and CProcessHandleObserver::MakeRequest().
Referenced by FindApp(), FindAppByPattern(), and StartApp().
void CWatchdog::Start ()
Definition at line 49 of file watchdog.cpp.
References KNormalWait, and WaitWhile().
Referenced by MainLoopL().
void CWatchdog::StartApp () [private]
Definition at line 78 of file watchdog.cpp.
References _LIT(), HandleMinorError(), iProcess, iProcessOpen, logg, ObserveProcess(), and UpdateAppStartTime().
Referenced by FindAppByPattern().
void CWatchdog::UpdateAppStartTime () [private]
Definition at line 54 of file watchdog.cpp.
References iAppStartTime.
Referenced by CWatchdog(), and StartApp().
void CWatchdog::WaitWhile (TInt aSecs) [private]
Definition at line 59 of file watchdog.cpp.
References iTimerAo, and SecsToUsecs().
Referenced by HandleMinorError(), HandleProcessHandleEvent(), and Start().
Member Data Documentation
TTime CWatchdog::iAppStartTime [private]
Definition at line 88 of file watchdog.h.
Referenced by CWatchdog(), DiedQuickly(), and UpdateAppStartTime().
RFs CWatchdog::iFs [private]
Definition at line 80 of file watchdog.h.
Referenced by ConstructL(), and ~CWatchdog().
TBool CWatchdog::iFsOpen [private]
Definition at line 82 of file watchdog.h.
Referenced by ConstructL(), and ~CWatchdog().
CProcessHandleObserver* CWatchdog::iLogonAo [private]
Definition at line 74 of file watchdog.h.
Referenced by Cancel(), ConstructL(), ObserveProcess(), and ~CWatchdog().
CActiveSchedulerWait& CWatchdog::iLoop [private]
Definition at line 36 of file watchdog.h.
Referenced by ExitWatchdog().
TInt CWatchdog::iNumMinorErrors [private]
Definition at line 90 of file watchdog.h.
Referenced by HandleMinorError().
RProcess CWatchdog::iProcess [private]
Definition at line 84 of file watchdog.h.
Referenced by CloseProcess(), ConstructL(), FindApp(), FindAppByPattern(), and StartApp().
TBool CWatchdog::iProcessOpen [private]
Definition at line 86 of file watchdog.h.
Referenced by CloseProcess(), FindApp(), FindAppByPattern(), ObserveProcess(), and StartApp().
TInt64 CWatchdog::iRandSeed [private]
Definition at line 92 of file watchdog.h.
Referenced by CWatchdog(), and HandleMinorError().
CTimerAo* CWatchdog::iTimerAo [private]
Definition at line 72 of file watchdog.h.
Referenced by Cancel(), ConstructL(), WaitWhile(), and ~CWatchdog().
RWsSession CWatchdog::iWsSession [private]
Definition at line 76 of file watchdog.h.
Referenced by ConstructL(), and ~CWatchdog().
TBool CWatchdog::iWsSessionOpen [private]
Definition at line 78 of file watchdog.h.
Referenced by ConstructL(), and ~CWatchdog().
The documentation for this class was generated from the following files:
watchdog.h
watchdog.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1