ContextLogger2 Logger Daemon Internals: CNotifyAo_NetworkRegistration Class Reference
CNotifyAo_NetworkRegistration Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CNotifyAo_NetworkRegistration (CTelephony &aTelephony, MNotifyObs_NetworkRegistration &aInterface)
virtual ~CNotifyAo_NetworkRegistration ()
void MakeRequest ()
CTelephony::TNetworkRegistrationV1
const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TNetworkRegistrationV1 iData
CTelephony::TNetworkRegistrationV1Pckg iDataDes
CTelephony & iTelephony
MNotifyObs_NetworkRegistration & iInterface
Detailed Description
Definition at line 371 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CNotifyAo_NetworkRegistration::CNotifyAo_NetworkRegistration (CTelephony & aTelephony, MNotifyObs_NetworkRegistration & aInterface)
Definition at line 235 of file ut_telephony_epoc.cpp.
CNotifyAo_NetworkRegistration::~CNotifyAo_NetworkRegistration () [virtual]
Definition at line 240 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TNetworkRegistrationV1 const & CNotifyAo_NetworkRegistration::Data () const [inline]
Definition at line 750 of file ut_telephony_epoc.h.
References iData.
Referenced by CObserverAo_NetworkRegistration::ChangedData_NetworkRegistration().
void CNotifyAo_NetworkRegistration::DoCancel () [private, virtual]
Definition at line 258 of file ut_telephony_epoc.cpp.
References iTelephony.
void CNotifyAo_NetworkRegistration::MakeRequest ()
Definition at line 245 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CObserverAo_NetworkRegistration::HandleData(), and CObserverAo_NetworkRegistration::MakeRequest().
void CNotifyAo_NetworkRegistration::RunL () [private, virtual]
Definition at line 253 of file ut_telephony_epoc.cpp.
References MNotifyObs_NetworkRegistration::ChangedData_NetworkRegistration(), and iInterface.
Member Data Documentation
CTelephony::TNetworkRegistrationV1 CNotifyAo_NetworkRegistration::iData [private]
Definition at line 394 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TNetworkRegistrationV1Pckg CNotifyAo_NetworkRegistration::iDataDes [private]
Definition at line 396 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MNotifyObs_NetworkRegistration& CNotifyAo_NetworkRegistration::iInterface [private]
Definition at line 400 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CNotifyAo_NetworkRegistration::iTelephony [private]
Definition at line 398 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1