ContextLogger2 Logger Daemon Internals: CSmsEventNotifier Class Reference
CSmsEventNotifier Class Reference
#include <ut_sms_epoc.hpp>
Public Member Functions
CSmsEventNotifier ()
~CSmsEventNotifier ()
void ConstructL ()
void SetHandler (i_handle_received_sms *handler)
Static Public Member Functions
static CSmsEventNotifier * NewL ()
Protected Member Functions
virtual void HandleSessionEventL (TMsvSessionEvent aEvent, TAny *aArg1, TAny *aArg2, TAny *aArg3)
Private Member Functions
void DoHandleSessionEventL (TMsvSessionEvent aEvent, TAny *aArg1, TAny *aArg2, TAny *aArg3)
void HandleReceivedL (const TMsvId &entry_id, const TMsvId &folder_id)
void HandleErrorL (TInt aError)
void HandleSentL (const TMsvId &entry_id)
TUid loadmessageL (const TMsvId &entry_id, TMsvEntry &entry)
Private Attributes
CMsvSession * iReceiveSession
CClientMtmRegistry * iReceiveMtmReg
CBaseMtm * iReceiveMtm
CBaseMtm * iMMSMtm
TBuf< 50 > state
i_handle_received_sms * iHandler
Detailed Description
Definition at line 75 of file ut_sms_epoc.hpp.
Constructor & Destructor Documentation
CSmsEventNotifier::CSmsEventNotifier ()
Definition at line 121 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N.
Referenced by NewL().
CSmsEventNotifier::~CSmsEventNotifier ()
Definition at line 127 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, iMMSMtm, iReceiveMtm, iReceiveMtmReg, and iReceiveSession.
Member Function Documentation
void CSmsEventNotifier::ConstructL ()
Definition at line 137 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, iReceiveMtmReg, iReceiveSession, and NewL().
Referenced by NewL().
void CSmsEventNotifier::DoHandleSessionEventL (TMsvSessionEvent aEvent, TAny * aArg1, TAny * aArg2, TAny * aArg3) [private]
Definition at line 172 of file ut_sms_epoc.cpp.
References i_handle_received_sms::handle_close(), HandleReceivedL(), HandleSentL(), iHandler, iMMSMtm, and iReceiveMtm.
Referenced by HandleSessionEventL().
void CSmsEventNotifier::HandleErrorL (TInt aError) [private]
Definition at line 231 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, i_handle_received_sms::handle_error(), and iHandler.
Referenced by HandleSessionEventL().
void CSmsEventNotifier::HandleReceivedL (const TMsvId & entry_id, const TMsvId & folder_id) [private]
Definition at line 307 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, i_handle_received_sms::handle_reception(), iHandler, iMMSMtm, iReceiveMtm, iReceiveMtmReg, and loadmessageL().
Referenced by DoHandleSessionEventL().
void CSmsEventNotifier::HandleSentL (const TMsvId & entry_id) [private]
Definition at line 328 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, i_handle_received_sms::handle_sending(), iHandler, iMMSMtm, iReceiveMtm, iReceiveMtmReg, loadmessageL(), and logt.
Referenced by DoHandleSessionEventL().
void CSmsEventNotifier::HandleSessionEventL (TMsvSessionEvent aEvent, TAny * aArg1, TAny * aArg2, TAny * aArg3) [protected, virtual]
Definition at line 162 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, DoHandleSessionEventL(), and HandleErrorL().
TUid CSmsEventNotifier::loadmessageL (const TMsvId & entry_id, TMsvEntry & entry) [private]
Definition at line 239 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, CC_TRAP, e_auto_ptr< X >::get(), iMMSMtm, iReceiveMtm, iReceiveMtmReg, iReceiveSession, e_auto_ptr< X >::release(), and e_auto_ptr< X >::reset().
Referenced by HandleReceivedL(), and HandleSentL().
CSmsEventNotifier * CSmsEventNotifier::NewL () [static]
Definition at line 112 of file ut_sms_epoc.cpp.
References ConstructL(), and CSmsEventNotifier().
Referenced by CSensor_smsevent::ActivateL(), and ConstructL().
void CSmsEventNotifier::SetHandler (i_handle_received_sms * handler)
Definition at line 152 of file ut_sms_epoc.cpp.
References CALLSTACKITEM_N, and iHandler.
Referenced by CSensor_smsevent::ActivateL().
Member Data Documentation
i_handle_received_sms* CSmsEventNotifier::iHandler [private]
Definition at line 105 of file ut_sms_epoc.hpp.
Referenced by DoHandleSessionEventL(), HandleErrorL(), HandleReceivedL(), HandleSentL(), and SetHandler().
CBaseMtm * CSmsEventNotifier::iMMSMtm [private]
Definition at line 102 of file ut_sms_epoc.hpp.
Referenced by DoHandleSessionEventL(), HandleReceivedL(), HandleSentL(), loadmessageL(), and ~CSmsEventNotifier().
CBaseMtm* CSmsEventNotifier::iReceiveMtm [private]
Definition at line 102 of file ut_sms_epoc.hpp.
Referenced by DoHandleSessionEventL(), HandleReceivedL(), HandleSentL(), loadmessageL(), and ~CSmsEventNotifier().
CClientMtmRegistry* CSmsEventNotifier::iReceiveMtmReg [private]
Definition at line 101 of file ut_sms_epoc.hpp.
Referenced by ConstructL(), HandleReceivedL(), HandleSentL(), loadmessageL(), and ~CSmsEventNotifier().
CMsvSession* CSmsEventNotifier::iReceiveSession [private]
Definition at line 100 of file ut_sms_epoc.hpp.
Referenced by ConstructL(), loadmessageL(), and ~CSmsEventNotifier().
TBuf<50> CSmsEventNotifier::state [private]
Definition at line 103 of file ut_sms_epoc.hpp.
The documentation for this class was generated from the following files:
ut_sms_epoc.hpp
ut_sms_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1