ContextLogger2 Logger Daemon Internals: ClQtEventSensorBase Class Reference
ClQtEventSensorBase Class Reference
#include <sa_qt_sensors.hpp>
Public Slots
void handleActiveChanged ()
void handleBusyChanged ()
void handleSensorError (int errCode)
virtual void handleReadingChanged ()=0
Public Member Functions
ClQtEventSensorBase (const QByteArray &type, ac_AppContext *aAppContext)
Protected Member Functions
LogDb * GetLogDb () const
virtual const char * Name () const =0
void run ()
Protected Attributes
ac_AppContext * iAppContext
Detailed Description
QtSensors related utilities.
Definition at line 17 of file sa_qt_sensors.hpp.
Constructor & Destructor Documentation
ClQtEventSensorBase::ClQtEventSensorBase (const QByteArray & type, ac_AppContext * aAppContext)
Definition at line 8 of file sa_qt_sensors.cpp.
Member Function Documentation
LogDb* ClQtEventSensorBase::GetLogDb () const [inline, protected]
Definition at line 30 of file sa_qt_sensors.hpp.
References ac_LogDb(), and iAppContext.
Referenced by handleActiveChanged(), handleBusyChanged(), Sensor_proximity::handleReadingChanged(), Sensor_light::handleReadingChanged(), and handleSensorError().
void ClQtEventSensorBase::handleActiveChanged () [slot]
Definition at line 27 of file sa_qt_sensors.cpp.
References GetLogDb(), log_db_log_status(), and Name().
Referenced by run().
void ClQtEventSensorBase::handleBusyChanged () [slot]
Definition at line 34 of file sa_qt_sensors.cpp.
References GetLogDb(), log_db_log_status(), and Name().
Referenced by run().
virtual void ClQtEventSensorBase::handleReadingChanged () [pure virtual, slot]
Implemented in Sensor_light, and Sensor_proximity.
Referenced by run().
void ClQtEventSensorBase::handleSensorError (int errCode) [slot]
Definition at line 43 of file sa_qt_sensors.cpp.
References GetLogDb(), log_db_log_status(), and Name().
Referenced by run().
virtual const char* ClQtEventSensorBase::Name () const [protected, pure virtual]
Implemented in Sensor_light, and Sensor_proximity.
Referenced by handleActiveChanged(), handleBusyChanged(), and handleSensorError().
void ClQtEventSensorBase::run () [protected]
Definition at line 14 of file sa_qt_sensors.cpp.
References handleActiveChanged(), handleBusyChanged(), handleReadingChanged(), and handleSensorError().
Referenced by Sensor_light::Sensor_light(), and Sensor_proximity::Sensor_proximity().
Member Data Documentation
ac_AppContext* ClQtEventSensorBase::iAppContext [protected]
Definition at line 27 of file sa_qt_sensors.hpp.
Referenced by GetLogDb().
The documentation for this class was generated from the following files:
sa_qt_sensors.hpp
sa_qt_sensors.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1