ContextLogger2 Logger Daemon Internals: Sensor_tap Class Reference
Sensor_tap Class Reference
#include <sa_sensor_tap_qt.hpp>
Public Member Functions
Sensor_tap (ac_AppContext *aAppContext, bool aDouble, const char *aName)
Private Slots
void handleActiveChanged ()
void handleBusyChanged ()
void handleReadingChanged ()
void handleSensorError (int errCode)
Private Member Functions
LogDb * GetLogDb () const
const char * Name () const
Private Attributes
ac_AppContext * iAppContext
bool iDouble
const char * iName
Detailed Description
Definition at line 13 of file sa_sensor_tap_qt.hpp.
Constructor & Destructor Documentation
Sensor_tap::Sensor_tap (ac_AppContext * aAppContext, bool aDouble, const char * aName)
Definition at line 10 of file sa_sensor_tap_qt.cpp.
References handleActiveChanged(), handleBusyChanged(), handleReadingChanged(), and handleSensorError().
Referenced by new_Sensor_tap().
Member Function Documentation
LogDb* Sensor_tap::GetLogDb () const [inline, private]
Definition at line 28 of file sa_sensor_tap_qt.hpp.
References ac_LogDb(), and iAppContext.
Referenced by handleActiveChanged(), handleBusyChanged(), handleReadingChanged(), and handleSensorError().
void Sensor_tap::handleActiveChanged () [private, slot]
Definition at line 34 of file sa_sensor_tap_qt.cpp.
References GetLogDb(), log_db_log_status(), and Name().
Referenced by Sensor_tap().
void Sensor_tap::handleBusyChanged () [private, slot]
Definition at line 41 of file sa_sensor_tap_qt.cpp.
References GetLogDb(), log_db_log_status(), and Name().
Referenced by Sensor_tap().
void Sensor_tap::handleReadingChanged () [private, slot]
Definition at line 50 of file sa_sensor_tap_qt.cpp.
References GetLogDb(), guilogf(), log_db_log_tap(), and Name().
Referenced by Sensor_tap().
void Sensor_tap::handleSensorError (int errCode) [private, slot]
Definition at line 62 of file sa_sensor_tap_qt.cpp.
References GetLogDb(), log_db_log_status(), and Name().
Referenced by Sensor_tap().
const char* Sensor_tap::Name () const [inline, private]
Definition at line 30 of file sa_sensor_tap_qt.hpp.
References iName.
Referenced by handleActiveChanged(), handleBusyChanged(), handleReadingChanged(), and handleSensorError().
Member Data Documentation
ac_AppContext* Sensor_tap::iAppContext [private]
Definition at line 23 of file sa_sensor_tap_qt.hpp.
Referenced by GetLogDb().
bool Sensor_tap::iDouble [private]
Definition at line 24 of file sa_sensor_tap_qt.hpp.
const char* Sensor_tap::iName [private]
Definition at line 25 of file sa_sensor_tap_qt.hpp.
Referenced by Name().
The documentation for this class was generated from the following files:
sa_sensor_tap_qt.hpp
sa_sensor_tap_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1