ContextLogger2 Logger Daemon Internals: CActiveLogErr Class Reference
CActiveLogErr Class Reference
#include <epoc-ao-gerror.hpp>
Protected Member Functions
CActiveLogErr (TInt aPriority)
virtual TInt RunError (TInt aError)
virtual const char * Description ()=0
Detailed Description
Definition at line 20 of file epoc-ao-gerror.hpp.
Constructor & Destructor Documentation
CActiveLogErr::CActiveLogErr (TInt aPriority) [inline, protected]
Definition at line 23 of file epoc-ao-gerror.hpp.
Member Function Documentation
virtual const char* CActiveLogErr::Description () [protected, pure virtual]
Implemented in CSensor_appfocus, CSensor_btprox, and CPositioner_gps.
Referenced by CActiveLogErrG::RunError(), and RunError().
TInt CActiveLogErr::RunError (TInt aError) [protected, virtual]
Reimplemented in CActiveLogErrG.
Definition at line 19 of file epoc-ao-gerror.cpp.
References ac_global_LogDb, Description(), and log_db_log_status().
The documentation for this class was generated from the following files:
epoc-ao-gerror.hpp
epoc-ao-gerror.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1