ContextLogger2 Logger Daemon Internals: CGetterAo_NetworkInfo Class Reference
CGetterAo_NetworkInfo Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CGetterAo_NetworkInfo (CTelephony &aTelephony, MGetterObs_NetworkInfo &aInterface)
virtual ~CGetterAo_NetworkInfo ()
void MakeRequest ()
CTelephony::TNetworkInfoV1 const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TNetworkInfoV1 iData
CTelephony::TNetworkInfoV1Pckg iDataDes
CTelephony & iTelephony
MGetterObs_NetworkInfo & iInterface
Detailed Description
Definition at line 414 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CGetterAo_NetworkInfo::CGetterAo_NetworkInfo (CTelephony & aTelephony, MGetterObs_NetworkInfo & aInterface)
Definition at line 263 of file ut_telephony_epoc.cpp.
CGetterAo_NetworkInfo::~CGetterAo_NetworkInfo () [virtual]
Definition at line 268 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TNetworkInfoV1 const & CGetterAo_NetworkInfo::Data () const [inline]
Definition at line 755 of file ut_telephony_epoc.h.
References iData.
Referenced by CObserverAo_NetworkInfo::GotData_NetworkInfo().
void CGetterAo_NetworkInfo::DoCancel () [private, virtual]
Definition at line 286 of file ut_telephony_epoc.cpp.
References iTelephony.
void CGetterAo_NetworkInfo::MakeRequest ()
Definition at line 273 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CObserverAo_NetworkInfo::ConstructL(), and CObserverAo_NetworkInfo::MakeRequest().
void CGetterAo_NetworkInfo::RunL () [private, virtual]
Definition at line 281 of file ut_telephony_epoc.cpp.
References MGetterObs_NetworkInfo::GotData_NetworkInfo(), and iInterface.
Member Data Documentation
CTelephony::TNetworkInfoV1 CGetterAo_NetworkInfo::iData [private]
Definition at line 437 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TNetworkInfoV1Pckg CGetterAo_NetworkInfo::iDataDes [private]
Definition at line 439 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MGetterObs_NetworkInfo& CGetterAo_NetworkInfo::iInterface [private]
Definition at line 443 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CGetterAo_NetworkInfo::iTelephony [private]
Definition at line 441 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1