ContextLogger2 Logger Daemon Internals: CBatteryObserver Class Reference
CBatteryObserver Class Reference
Public Member Functions
~CBatteryObserver ()
Private Member Functions
virtual void GotData_BatteryInfo (TInt aError)
virtual void ChangedData_BatteryInfo (TInt aError)
void HandleBattery (TInt aError, CTelephony::TBatteryInfoV1 const &aData)
Private Attributes
CTOR_DECL_CBatteryObserver
CGetterAo_BatteryInfo * iBatteryInfoGetter
CNotifyAo_BatteryInfo * iBatteryInfoNotifier
MGetterObs_BatteryInfo & iObserver
Detailed Description
Definition at line 66 of file ac_app_context_epoc.cpp.
Constructor & Destructor Documentation
CBatteryObserver::~CBatteryObserver ()
Definition at line 99 of file ac_app_context_epoc.cpp.
References iBatteryInfoGetter, and iBatteryInfoNotifier.
Member Function Documentation
void CBatteryObserver::ChangedData_BatteryInfo (TInt aError) [private, virtual]
Implements MNotifyObs_BatteryInfo.
Definition at line 111 of file ac_app_context_epoc.cpp.
References CNotifyAo_BatteryInfo::Data(), HandleBattery(), and iBatteryInfoNotifier.
void CBatteryObserver::GotData_BatteryInfo (TInt aError) [private, virtual]
Implements MGetterObs_BatteryInfo.
Definition at line 105 of file ac_app_context_epoc.cpp.
References CGetterAo_BatteryInfo::Data(), MGetterObs_BatteryInfo::GotData_BatteryInfo(), HandleBattery(), iBatteryInfoGetter, and iObserver.
void CBatteryObserver::HandleBattery (TInt aError, CTelephony::TBatteryInfoV1 const & aData) [private]
Definition at line 116 of file ac_app_context_epoc.cpp.
References ac_global_LogDb, er_fatal_battery_low, er_fatal_quiet(), er_log_none, er_log_symbian, iBatteryInfoNotifier, logg, and CNotifyAo_BatteryInfo::MakeRequest().
Referenced by ChangedData_BatteryInfo(), and GotData_BatteryInfo().
Member Data Documentation
CBatteryObserver::CTOR_DECL_CBatteryObserver [private]
Definition at line 71 of file ac_app_context_epoc.cpp.
CGetterAo_BatteryInfo* CBatteryObserver::iBatteryInfoGetter [private]
Definition at line 82 of file ac_app_context_epoc.cpp.
Referenced by GotData_BatteryInfo(), and ~CBatteryObserver().
CNotifyAo_BatteryInfo* CBatteryObserver::iBatteryInfoNotifier [private]
Definition at line 83 of file ac_app_context_epoc.cpp.
Referenced by ChangedData_BatteryInfo(), HandleBattery(), and ~CBatteryObserver().
MGetterObs_BatteryInfo& CBatteryObserver::iObserver [private]
Definition at line 86 of file ac_app_context_epoc.cpp.
Referenced by GotData_BatteryInfo().
The documentation for this class was generated from the following file:
ac_app_context_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1