ContextLogger2 Logger Daemon Internals: MImmediateObserver Class Reference
MImmediateObserver Class Reference
#include <ut_immediate_epoc.hpp>
Public Member Functions
virtual void HandleImmediateEvent ()=0
virtual TInt HandleImmediateError (TInt errCode)
virtual TInt HandleImmediateLeave (TInt errCode)
Detailed Description
Definition at line 11 of file ut_immediate_epoc.hpp.
Member Function Documentation
TInt MImmediateObserver::HandleImmediateError (TInt errCode) [virtual]
Reimplemented in _ut_Immediate.
Definition at line 14 of file ut_immediate_epoc.cpp.
References er_FATAL, and er_log_symbian.
Referenced by CImmediateAo::RunL().
virtual void MImmediateObserver::HandleImmediateEvent () [pure virtual]
Implemented in CUploader, and _ut_Immediate.
Referenced by CImmediateAo::RunL().
TInt MImmediateObserver::HandleImmediateLeave (TInt errCode) [virtual]
Definition at line 20 of file ut_immediate_epoc.cpp.
References er_FATAL, and er_log_symbian.
Referenced by CImmediateAo::RunError().
The documentation for this class was generated from the following files:
ut_immediate_epoc.hpp
ut_immediate_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1