ContextLogger2 Logger Daemon Internals: QAbsTimer Class Reference
QAbsTimer Class Reference
#include <ut_abs_timer_qt_epoc.hpp>
Signals
void timeout ()
void timeout ()
Public Member Functions
QAbsTimer (QObject *parent=0)
~QAbsTimer ()
bool isActive () const
void start (const QDateTime &aExpTime)
void stop ()
QAbsTimer (QObject *parent=0)
~QAbsTimer ()
bool isActive () const
void start (const QDateTime &aExpTime)
void stop ()
Properties
bool active
Private Slots
void handleTimeout ()
Private Member Functions
virtual void HandleTimerEvent (CTimerAo *aOrig, TInt aError)
void startOrSignal ()
Private Attributes
CTimerAo * iTimerAo
TTime iAtTime
QTimer iTimerAo
QDateTime iExpTime
Detailed Description
Definition at line 9 of file ut_abs_timer_qt_epoc.hpp.
Constructor & Destructor Documentation
QAbsTimer::QAbsTimer (QObject * parent = 0)
Definition at line 12 of file ut_abs_timer_qt_epoc.cpp.
References iTimerAo, and CTimerAo::NewL().
QAbsTimer::~QAbsTimer ()
Definition at line 20 of file ut_abs_timer_qt_epoc.cpp.
References iTimerAo.
QAbsTimer::QAbsTimer (QObject * parent = 0)
QAbsTimer::~QAbsTimer ()
Member Function Documentation
void QAbsTimer::handleTimeout () [private, slot]
Definition at line 57 of file ut_abs_timer_qt_pure.cpp.
References startOrSignal().
void QAbsTimer::HandleTimerEvent (CTimerAo * aOrig, TInt aError) [private, virtual]
Implements MTimerObserver.
Definition at line 44 of file ut_abs_timer_qt_epoc.cpp.
References er_FATAL, er_log_symbian, iAtTime, iTimerAo, and timeout().
bool QAbsTimer::isActive () const
bool QAbsTimer::isActive () const
Definition at line 25 of file ut_abs_timer_qt_epoc.cpp.
References iTimerAo.
void QAbsTimer::start (const QDateTime & aExpTime)
void QAbsTimer::start (const QDateTime & aExpTime)
Definition at line 30 of file ut_abs_timer_qt_epoc.cpp.
References iAtTime, iTimerAo, and UnixTimeToUtcEpocTime().
void QAbsTimer::startOrSignal () [private]
Definition at line 32 of file ut_abs_timer_qt_pure.cpp.
References iExpTime, iTimerAo, and timeout().
Referenced by handleTimeout().
void QAbsTimer::stop ()
void QAbsTimer::stop ()
Definition at line 39 of file ut_abs_timer_qt_epoc.cpp.
References iTimerAo.
void QAbsTimer::timeout () [signal]
void QAbsTimer::timeout () [signal]
Definition at line 109 of file moc_ut_abs_timer_qt_epoc.cpp.
Referenced by HandleTimerEvent(), and startOrSignal().
Member Data Documentation
TTime QAbsTimer::iAtTime [private]
Definition at line 17 of file ut_abs_timer_qt_epoc.hpp.
Referenced by HandleTimerEvent(), and start().
QDateTime QAbsTimer::iExpTime [private]
Definition at line 15 of file ut_abs_timer_qt_pure.hpp.
Referenced by startOrSignal().
QTimer QAbsTimer::iTimerAo [private]
Definition at line 14 of file ut_abs_timer_qt_pure.hpp.
CTimerAo* QAbsTimer::iTimerAo [private]
Definition at line 16 of file ut_abs_timer_qt_epoc.hpp.
Referenced by HandleTimerEvent(), isActive(), QAbsTimer(), start(), startOrSignal(), stop(), and ~QAbsTimer().
Property Documentation
bool QAbsTimer::active [read]
Definition at line 13 of file ut_abs_timer_qt_epoc.hpp.
The documentation for this class was generated from the following files:
ut_abs_timer_qt_epoc.hpp
ut_abs_timer_qt_pure.hpp
moc_ut_abs_timer_qt_epoc.cpp
moc_ut_abs_timer_qt_pure.cpp
ut_abs_timer_qt_epoc.cpp
ut_abs_timer_qt_pure.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1