ContextLogger2 Logger Daemon Internals: CSensor_smsevent Class Reference
CSensor_smsevent Class Reference
#include <epoc-smsevent.hpp>
Public Member Functions
virtual ~CSensor_smsevent ()
gboolean StartL (GError **error)
void Stop ()
TBool IsActive () const
Private Member Functions
virtual void handle_reception (const TMsvId &entry_id, const TMsvId &folder_id, const TDesC &sender, CRichText &body)
virtual void handle_sending (const TMsvId &entry_id, const TDesC &sender, CRichText &body)
virtual void handle_error (TInt aError)
virtual void handle_close ()
void ActivateL ()
void Disactivate ()
void LogEvent (const char *evType, const TDesC &aTelNo, CRichText &aBody)
LogDb * GetLogDb () const
Private Attributes
CTOR_DECL_CSensor_smsevent
ac_AppContext * iAppContext
CSmsEventNotifier * iSmsEventNotifier
Detailed Description
Definition at line 52 of file epoc-smsevent.hpp.
Constructor & Destructor Documentation
CSensor_smsevent::~CSensor_smsevent () [virtual]
Definition at line 26 of file epoc-smsevent.cpp.
References iSmsEventNotifier.
Member Function Documentation
void CSensor_smsevent::ActivateL () [private]
Definition at line 50 of file epoc-smsevent.cpp.
References iSmsEventNotifier, CSmsEventNotifier::NewL(), and CSmsEventNotifier::SetHandler().
Referenced by StartL().
void CSensor_smsevent::Disactivate () [private]
Definition at line 56 of file epoc-smsevent.cpp.
References iSmsEventNotifier.
Referenced by Stop().
LogDb* CSensor_smsevent::GetLogDb () const [inline, private]
Definition at line 95 of file epoc-smsevent.hpp.
References ac_LogDb().
Referenced by handle_close(), handle_error(), and LogEvent().
void CSensor_smsevent::handle_close () [private, virtual]
Implements i_handle_received_sms.
Definition at line 177 of file epoc-smsevent.cpp.
References GetLogDb(), gx_txtlog_fatal_error_free(), log_db_log_status(), and Stop().
void CSensor_smsevent::handle_error (TInt aError) [private, virtual]
Implements i_handle_received_sms.
Definition at line 160 of file epoc-smsevent.cpp.
References GetLogDb(), gx_txtlog_fatal_error_free(), log_db_log_status(), plat_error_strerror, and Stop().
void CSensor_smsevent::handle_reception (const TMsvId & entry_id, const TMsvId & folder_id, const TDesC & sender, CRichText & body) [private, virtual]
Implements i_handle_received_sms.
Definition at line 143 of file epoc-smsevent.cpp.
References LogEvent().
void CSensor_smsevent::handle_sending (const TMsvId & entry_id, const TDesC & sender, CRichText & body) [private, virtual]
Implements i_handle_received_sms.
Definition at line 152 of file epoc-smsevent.cpp.
References LogEvent().
TBool CSensor_smsevent::IsActive () const [inline]
Definition at line 69 of file epoc-smsevent.hpp.
Referenced by StartL(), and Stop().
void CSensor_smsevent::LogEvent (const char * evType, const TDesC & aTelNo, CRichText & aBody) [private]
Definition at line 95 of file epoc-smsevent.cpp.
References ac_STATIC_GET, er_fatal_oom, GetBody(), GetContactNameByPhoneNo(), GetLogDb(), guilogf(), gx_txtlog_fatal_error_free(), log_db_log_smsevent(), and logt.
Referenced by handle_reception(), and handle_sending().
gboolean CSensor_smsevent::StartL (GError ** error)
Definition at line 33 of file epoc-smsevent.cpp.
References ActivateL(), and IsActive().
void CSensor_smsevent::Stop ()
Definition at line 42 of file epoc-smsevent.cpp.
References Disactivate(), and IsActive().
Referenced by handle_close(), and handle_error().
Member Data Documentation
CSensor_smsevent::CTOR_DECL_CSensor_smsevent [private]
Definition at line 56 of file epoc-smsevent.hpp.
ac_AppContext* CSensor_smsevent::iAppContext [private]
Definition at line 89 of file epoc-smsevent.hpp.
CSmsEventNotifier* CSensor_smsevent::iSmsEventNotifier [private]
Definition at line 91 of file epoc-smsevent.hpp.
Referenced by ActivateL(), Disactivate(), and ~CSensor_smsevent().
The documentation for this class was generated from the following files:
epoc-smsevent.hpp
epoc-smsevent.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1