ContextLogger2 Logger Daemon Internals: MObserverObs_NetworkInfo Class Reference
MObserverObs_NetworkInfo Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
virtual void ObservedData_NetworkInfo (TData_NetworkInfo const &aData)=0
virtual void ReportTransientError_NetworkInfo (TInt aError)=0
virtual void RetriesExhausted_NetworkInfo ()=0
virtual void InFlightMode_NetworkInfo ()=0
Detailed Description
Definition at line 565 of file ut_telephony_epoc.h.
Member Function Documentation
virtual void MObserverObs_NetworkInfo::InFlightMode_NetworkInfo () [pure virtual]
Implemented in CNetworkObserver.
Referenced by CObserverAo_NetworkInfo::HandleFlightModeChange().
virtual void MObserverObs_NetworkInfo::ObservedData_NetworkInfo (TData_NetworkInfo const & aData) [pure virtual]
Implemented in CNetworkObserver.
Referenced by CObserverAo_NetworkInfo::HandleData().
virtual void MObserverObs_NetworkInfo::ReportTransientError_NetworkInfo (TInt aError) [pure virtual]
Implemented in CNetworkObserver.
Referenced by CObserverAo_NetworkInfo::HandleData().
virtual void MObserverObs_NetworkInfo::RetriesExhausted_NetworkInfo () [pure virtual]
Implemented in CNetworkObserver.
Referenced by CObserverAo_NetworkInfo::HandleData().
The documentation for this class was generated from the following file:
ut_telephony_epoc.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1