ContextLogger2 Logger Daemon Internals: e_auto_ptr< X > Class Template Reference
e_auto_ptr< X > Class Template Reference
#include <symbian_auto_ptr.hpp>
Public Types
typedef X element_type
Public Member Functions
e_auto_ptr (X *aPtr=0)
e_auto_ptr (e_auto_ptr &aPtr)
e_auto_ptr< X > & operator= (e_auto_ptr< X > &aRhs)
~e_auto_ptr ()
X & operator* () const
X * operator-> () const
X * get () const
X * release ()
void reset (X *aPtr=0)
e_auto_ptr (e_auto_ptr_ref< X > aRef)
template<class Y >
operator e_auto_ptr_ref< Y > ()
Private Attributes
CBase * iBasePtr
Detailed Description
template<class X>
class e_auto_ptr< X >
Definition at line 62 of file symbian_auto_ptr.hpp.
Member Typedef Documentation
template<class X> typedef X e_auto_ptr< X >::element_type
Definition at line 65 of file symbian_auto_ptr.hpp.
Constructor & Destructor Documentation
template<class X> e_auto_ptr< X >::e_auto_ptr (X * aPtr = 0) [inline]
Definition at line 67 of file symbian_auto_ptr.hpp.
References CloseCBaseIndirect(), and e_auto_ptr< X >::iBasePtr.
template<class X> e_auto_ptr< X >::e_auto_ptr (e_auto_ptr< X > & aPtr) [inline]
Definition at line 74 of file symbian_auto_ptr.hpp.
References CloseCBaseIndirect(), and e_auto_ptr< X >::iBasePtr.
template<class X> e_auto_ptr< X >::~e_auto_ptr () [inline]
Definition at line 91 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr.
template<class X> e_auto_ptr< X >::e_auto_ptr (e_auto_ptr_ref< X > aRef) [inline]
Definition at line 119 of file symbian_auto_ptr.hpp.
References CloseCBaseIndirect(), and e_auto_ptr< X >::iBasePtr.
Member Function Documentation
template<class X> X* e_auto_ptr< X >::get () const [inline]
Definition at line 102 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr.
Referenced by CSmsEventNotifier::loadmessageL().
template<class X> template<class Y > e_auto_ptr< X >::operator e_auto_ptr_ref< Y > () [inline]
Definition at line 127 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::release().
template<class X> X& e_auto_ptr< X >::operator* () const [inline]
Definition at line 99 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr.
template<class X> X* e_auto_ptr< X >::operator-> () const [inline]
Definition at line 100 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr.
template<class X> e_auto_ptr<X>& e_auto_ptr< X >::operator= (e_auto_ptr< X > & aRhs) [inline]
Definition at line 81 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr, and e_auto_ptr< X >::release().
template<class X> X* e_auto_ptr< X >::release () [inline]
Definition at line 104 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr.
Referenced by CSmsEventNotifier::loadmessageL(), CTimeOut::NewL(), e_auto_ptr< HBufC8 >::operator e_auto_ptr_ref< Y >(), e_auto_ptr< HBufC16 >::operator e_auto_ptr_ref< Y >(), e_auto_ptr< X >::operator e_auto_ptr_ref< Y >(), and e_auto_ptr< X >::operator=().
template<class X> void e_auto_ptr< X >::reset (X * aPtr = 0) [inline]
Definition at line 111 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::iBasePtr.
Referenced by CSmsEventNotifier::loadmessageL().
Member Data Documentation
template<class X> CBase* e_auto_ptr< X >::iBasePtr [private]
Definition at line 131 of file symbian_auto_ptr.hpp.
Referenced by e_auto_ptr< X >::e_auto_ptr(), e_auto_ptr< X >::get(), e_auto_ptr< X >::operator*(), e_auto_ptr< X >::operator->(), e_auto_ptr< X >::operator=(), e_auto_ptr< X >::release(), e_auto_ptr< X >::reset(), and e_auto_ptr< X >::~e_auto_ptr().
The documentation for this class was generated from the following file:
symbian_auto_ptr.hpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1