ContextLogger2 Logger Daemon Internals: CSensor_cellid Class Reference
CSensor_cellid Class Reference
#include <epoc-cellid.hpp>
Public Member Functions
virtual ~CSensor_cellid ()
void PostNewData (const CTelephony::TNetworkInfoV1 &aData)
Private Member Functions
void PostNewDataL (const CTelephony::TNetworkInfoV1 &aData)
void Unregister ()
LogDb * GetLogDb () const
bb_Blackboard * GetBlackboard () const
Private Attributes
CTOR_DECL_CSensor_cellid
ac_AppContext * iAppContext
bb_Closure iClosure
CTelephony::TNetworkInfoV1 iOldData
Detailed Description
Definition at line 53 of file epoc-cellid.hpp.
Constructor & Destructor Documentation
CSensor_cellid::~CSensor_cellid () [virtual]
Definition at line 39 of file epoc-cellid.cpp.
References Unregister().
Member Function Documentation
bb_Blackboard* CSensor_cellid::GetBlackboard () const [inline, private]
Definition at line 82 of file epoc-cellid.hpp.
References ac_get_Blackboard().
Referenced by Unregister().
LogDb* CSensor_cellid::GetLogDb () const [inline, private]
Definition at line 80 of file epoc-cellid.hpp.
References ac_LogDb().
Referenced by PostNewDataL().
void CSensor_cellid::PostNewData (const CTelephony::TNetworkInfoV1 & aData)
Definition at line 49 of file epoc-cellid.cpp.
References er_FATAL, er_log_symbian, and PostNewDataL().
Referenced by DataChanged().
void CSensor_cellid::PostNewDataL (const CTelephony::TNetworkInfoV1 & aData) [private]
Definition at line 58 of file epoc-cellid.cpp.
References GetLogDb(), guilogf(), iOldData, and log_db_log_cellid().
Referenced by PostNewData().
void CSensor_cellid::Unregister () [private]
Definition at line 44 of file epoc-cellid.cpp.
References bb_Blackboard_unregister(), GetBlackboard(), and iClosure.
Referenced by ~CSensor_cellid().
Member Data Documentation
CSensor_cellid::CTOR_DECL_CSensor_cellid [private]
Definition at line 59 of file epoc-cellid.hpp.
ac_AppContext* CSensor_cellid::iAppContext [private]
Definition at line 73 of file epoc-cellid.hpp.
bb_Closure CSensor_cellid::iClosure [private]
Definition at line 75 of file epoc-cellid.hpp.
Referenced by Unregister().
CTelephony::TNetworkInfoV1 CSensor_cellid::iOldData [private]
Definition at line 77 of file epoc-cellid.hpp.
Referenced by PostNewDataL().
The documentation for this class was generated from the following files:
epoc-cellid.hpp
epoc-cellid.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1