ContextLogger2 Logger Daemon Internals: CSensor_music Class Reference
CSensor_music Class Reference
#include <epoc-music.hpp>
Public Member Functions
virtual ~CSensor_music ()
Static Public Member Functions
static CSensor_music * NewLC (ac_AppContext *aAppContext)
static CSensor_music * NewL (ac_AppContext *aAppContext)
Private Member Functions
CSensor_music (ac_AppContext *aAppContext)
void ConstructL ()
LogDb * GetLogDb () const
void CloseSession ()
void RequestMediaL ()
virtual void HandlePlaybackMessage (CMPXMessage *aMsg, TInt errCode)
virtual void HandlePropertyL (TMPXPlaybackProperty aProperty, TInt aValue, TInt aError)
virtual void HandleSubPlayerNamesL (TUid aPlayer, const MDesCArray *aSubPlayers, TBool aComplete, TInt aError)
virtual void HandleMediaL (const CMPXMedia &aProperties, TInt aError)
Private Attributes
ac_AppContext * iAppContext
MMPXPlaybackUtility * iPlaybackUtility
MyTrackInfo * iOldTrackInfo
MyTrackInfo * iTrackInfo
TInt iOldPbState
Detailed Description
Definition at line 33 of file epoc-music.hpp.
Constructor & Destructor Documentation
CSensor_music::~CSensor_music () [virtual]
Definition at line 77 of file epoc-music.cpp.
References CloseSession(), iOldTrackInfo, and iTrackInfo.
CSensor_music::CSensor_music (ac_AppContext * aAppContext) [private]
Definition at line 97 of file epoc-music.cpp.
Referenced by NewLC().
Member Function Documentation
void CSensor_music::CloseSession () [private]
Definition at line 84 of file epoc-music.cpp.
References iPlaybackUtility.
Referenced by HandlePlaybackMessage(), and ~CSensor_music().
void CSensor_music::ConstructL () [private]
Definition at line 102 of file epoc-music.cpp.
References iOldTrackInfo, iPlaybackUtility, iTrackInfo, NewL(), and RequestMediaL().
Referenced by NewLC().
LogDb* CSensor_music::GetLogDb () const [inline, private]
Definition at line 55 of file epoc-music.hpp.
References ac_LogDb().
Referenced by HandleMediaL(), and HandlePlaybackMessage().
void CSensor_music::HandleMediaL (const CMPXMedia & aProperties, TInt aError) [private, virtual]
Definition at line 493 of file epoc-music.cpp.
References MyTrackInfo::Cmp(), GetLogDb(), guilogf(), MyTrackInfo::iAlbum, MyTrackInfo::iArtist, iOldTrackInfo, MyTrackInfo::iTitle, iTrackInfo, MyTrackInfo::iUrl, log_db_log_musictrack(), MyTrackInfo::Reset(), and SWAP.
void CSensor_music::HandlePlaybackMessage (CMPXMessage * aMsg, TInt errCode) [private, virtual]
Definition at line 121 of file epoc-music.cpp.
References CloseSession(), DETAILBUFSIZE, DETAILFMT, er_log_symbian, GetLogDb(), guilogf(), iOldPbState, log_db_log_musicplayer(), and RequestMediaL().
virtual void CSensor_music::HandlePropertyL (TMPXPlaybackProperty aProperty, TInt aValue, TInt aError) [inline, private, virtual]
Definition at line 65 of file epoc-music.hpp.
virtual void CSensor_music::HandleSubPlayerNamesL (TUid aPlayer, const MDesCArray * aSubPlayers, TBool aComplete, TInt aError) [inline, private, virtual]
Definition at line 69 of file epoc-music.hpp.
CSensor_music * CSensor_music::NewL (ac_AppContext * aAppContext) [static]
Definition at line 70 of file epoc-music.cpp.
References NewLC().
Referenced by ConstructL().
CSensor_music * CSensor_music::NewLC (ac_AppContext * aAppContext) [static]
Definition at line 62 of file epoc-music.cpp.
References ConstructL(), and CSensor_music().
Referenced by NewL().
void CSensor_music::RequestMediaL () [private]
Definition at line 468 of file epoc-music.cpp.
References iPlaybackUtility.
Referenced by ConstructL(), and HandlePlaybackMessage().
Member Data Documentation
ac_AppContext* CSensor_music::iAppContext [private]
Definition at line 48 of file epoc-music.hpp.
TInt CSensor_music::iOldPbState [private]
Definition at line 52 of file epoc-music.hpp.
Referenced by HandlePlaybackMessage().
MyTrackInfo* CSensor_music::iOldTrackInfo [private]
Definition at line 50 of file epoc-music.hpp.
Referenced by ConstructL(), HandleMediaL(), and ~CSensor_music().
MMPXPlaybackUtility* CSensor_music::iPlaybackUtility [private]
Definition at line 49 of file epoc-music.hpp.
Referenced by CloseSession(), ConstructL(), and RequestMediaL().
MyTrackInfo* CSensor_music::iTrackInfo [private]
Definition at line 51 of file epoc-music.hpp.
Referenced by ConstructL(), HandleMediaL(), and ~CSensor_music().
The documentation for this class was generated from the following files:
epoc-music.hpp
epoc-music.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1