ContextLogger2 Logger Daemon Internals: CNotifyAo_SignalStrength Class Reference
CNotifyAo_SignalStrength Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CNotifyAo_SignalStrength (CTelephony &aTelephony, MNotifyObs_SignalStrength &aInterface)
virtual ~CNotifyAo_SignalStrength ()
void MakeRequest ()
CTelephony::TSignalStrengthV1
const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TSignalStrengthV1 iData
CTelephony::TSignalStrengthV1Pckg iDataDes
CTelephony & iTelephony
MNotifyObs_SignalStrength & iInterface
Detailed Description
Definition at line 285 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CNotifyAo_SignalStrength::CNotifyAo_SignalStrength (CTelephony & aTelephony, MNotifyObs_SignalStrength & aInterface)
Definition at line 179 of file ut_telephony_epoc.cpp.
CNotifyAo_SignalStrength::~CNotifyAo_SignalStrength () [virtual]
Definition at line 184 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TSignalStrengthV1 const & CNotifyAo_SignalStrength::Data () const [inline]
Definition at line 740 of file ut_telephony_epoc.h.
References iData.
Referenced by CObserverAo_SignalStrength::ChangedData_SignalStrength().
void CNotifyAo_SignalStrength::DoCancel () [private, virtual]
Definition at line 202 of file ut_telephony_epoc.cpp.
References iTelephony.
void CNotifyAo_SignalStrength::MakeRequest ()
Definition at line 189 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CObserverAo_SignalStrength::HandleData(), and CObserverAo_SignalStrength::MakeRequest().
void CNotifyAo_SignalStrength::RunL () [private, virtual]
Definition at line 197 of file ut_telephony_epoc.cpp.
References MNotifyObs_SignalStrength::ChangedData_SignalStrength(), and iInterface.
Member Data Documentation
CTelephony::TSignalStrengthV1 CNotifyAo_SignalStrength::iData [private]
Definition at line 308 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TSignalStrengthV1Pckg CNotifyAo_SignalStrength::iDataDes [private]
Definition at line 310 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MNotifyObs_SignalStrength& CNotifyAo_SignalStrength::iInterface [private]
Definition at line 314 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CNotifyAo_SignalStrength::iTelephony [private]
Definition at line 312 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1