ContextLogger2 Logger Daemon Internals: CActiveRunG Class Reference
CActiveRunG Class Reference
#include <epoc-ao-gerror.hpp>
Protected Member Functions
CActiveRunG (TInt aPriority)
virtual gboolean RunGL (GError **error)=0
Private Member Functions
virtual void RunL ()
Detailed Description
Definition at line 57 of file epoc-ao-gerror.hpp.
Constructor & Destructor Documentation
CActiveRunG::CActiveRunG (TInt aPriority) [inline, protected]
Definition at line 60 of file epoc-ao-gerror.hpp.
Member Function Documentation
virtual gboolean CActiveRunG::RunGL (GError ** error) [protected, pure virtual]
This function may either leave or return a GError.
Implemented in CSensor_appfocus, CSensor_btprox, and CPositioner_gps.
Referenced by RunL().
void CActiveRunG::RunL () [private, virtual]
Implements RunL based on RunGL.
Definition at line 60 of file epoc-ao-gerror.cpp.
References error(), CActiveLogErrG::iError, KGError, CActiveLogErrG::Leave(), and RunGL().
The documentation for this class was generated from the following files:
epoc-ao-gerror.hpp
epoc-ao-gerror.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1