ContextLogger2 Logger Daemon Internals: CSensor_cellpos Class Reference
CSensor_cellpos Class Reference
#include <epoc-cellpos.hpp>
Public Member Functions
virtual ~CSensor_cellpos ()
void StartL ()
void Stop ()
TBool IsActive () const
void Reconfigure (const gchar *name, const gchar *value)
Static Public Member Functions
static CSensor_cellpos * NewL (ac_AppContext *aAppContext)
Private Types
enum TState { EInactive = 0, EActive }
Private Member Functions
CSensor_cellpos (ac_AppContext *aAppContext)
void ConstructL ()
virtual void PosModChangeL ()
virtual void PosModErrorL (TInt errCode)
virtual void PosModLeave (TInt errCode)
virtual TBool PosModIsCurrent (TPositionModuleId id) const
virtual gboolean PositionerEventL (GError **error)
virtual void RetryTimerExpired (CRetryAo *src, TInt errCode)
virtual void BbChangedL (bb::RHandle *self, enum bb_DataType dt, gpointer data, int len)
void ReadConfig ()
void CreateSpecifiedPositionerL (TPositionModuleId bestId)
Private Attributes
ac_AppContext * iAppContext
LogDb * iLogDb
CPosModuleStatAo * iModuleAo
CPositioner_gps * iSatPositioner
CRetryAo * iRetryAo
bb::RHandle iCellChangeHandle
bb::RHandle iNetposChangeHandle
TTime iLastScanTime
TState iState
TPositionModuleId iModuleId
TBool iAllowAssisted
TInt iMinScanRequestIntervalSecs
TInt iSatelliteQueryTimeoutSecs
TInt iDataMaxAgeSecs
Detailed Description
Definition at line 29 of file epoc-cellpos.hpp.
Member Enumeration Documentation
enum CSensor_cellpos::TState [private]
Enumerator:
EInactive
EActive
Definition at line 77 of file epoc-cellpos.hpp.
Constructor & Destructor Documentation
CSensor_cellpos::~CSensor_cellpos () [virtual]
Definition at line 86 of file epoc-cellpos.cpp.
References iModuleAo, iRetryAo, and Stop().
CSensor_cellpos::CSensor_cellpos (ac_AppContext * aAppContext) [private]
Definition at line 65 of file epoc-cellpos.cpp.
References ac_LogDb(), and iLogDb.
Referenced by NewL().
Member Function Documentation
void CSensor_cellpos::BbChangedL (bb::RHandle * self, enum bb_DataType dt, gpointer data, int len) [private, virtual]
Definition at line 177 of file epoc-cellpos.cpp.
References bb_dt_cell_id, bb_dt_netpos_allowed, guilogf(), iAllowAssisted, iLastScanTime, iMinScanRequestIntervalSecs, iRetryAo, IsActive(), iSatPositioner, CPositioner_gps::MakeRequest(), and PosModChangeL().
void CSensor_cellpos::ConstructL () [private]
Definition at line 72 of file epoc-cellpos.cpp.
References ac_get_Blackboard(), bb_Blackboard_board(), bb_dt_cell_id, bb_dt_netpos_allowed, iAllowAssisted, iAppContext, iCellChangeHandle, iModuleAo, iNetposChangeHandle, iRetryAo, bb_Board::netpos_allowed, NewL(), and ReadConfig().
Referenced by NewL().
void CSensor_cellpos::CreateSpecifiedPositionerL (TPositionModuleId bestId) [private]
Definition at line 114 of file epoc-cellpos.cpp.
References iDataMaxAgeSecs, iModuleAo, iModuleId, iSatelliteQueryTimeoutSecs, iSatPositioner, NewL(), POSITIONER_SCAN_INTERVAL_SECS, and CPosModuleStatAo::PositionServer().
Referenced by PosModChangeL().
TBool CSensor_cellpos::IsActive () const [inline]
Definition at line 98 of file epoc-cellpos.hpp.
Referenced by BbChangedL(), and StartL().
CSensor_cellpos * CSensor_cellpos::NewL (ac_AppContext * aAppContext) [static]
Definition at line 56 of file epoc-cellpos.cpp.
References ConstructL(), and CSensor_cellpos().
Referenced by ConstructL(), and CreateSpecifiedPositionerL().
gboolean CSensor_cellpos::PositionerEventL (GError ** error) [private, virtual]
Implements MObserver_gps.
Definition at line 365 of file epoc-cellpos.cpp.
References assert_error_unset, er_FATAL, er_log_symbian, guilogf(), iLastScanTime, iLogDb, iRetryAo, iSatPositioner, log_db_log_status(), logg, LogSatelliteInfoL(), CPositioner_gps::PositionInfo(), CRetryAo::ResetFailures(), CPositioner_gps::StatusCode(), and Stop().
void CSensor_cellpos::PosModChangeL () [private, virtual]
Implements MObserverPosMod.
Definition at line 128 of file epoc-cellpos.cpp.
References CPosModuleStatAo::ChooseBestPositionerL(), CreateSpecifiedPositionerL(), er_log_symbian, iAllowAssisted, iModuleAo, iModuleId, iRetryAo, iSatPositioner, CPosModuleStatAo::KAllowAssisted, CPosModuleStatAo::MakeRequest(), and CRetryAo::ResetFailures().
Referenced by BbChangedL(), and StartL().
void CSensor_cellpos::PosModErrorL (TInt errCode) [private, virtual]
Implements MObserverPosMod.
Definition at line 154 of file epoc-cellpos.cpp.
References er_log_symbian, and Stop().
TBool CSensor_cellpos::PosModIsCurrent (TPositionModuleId id) const [private, virtual]
Implements MObserverPosMod.
Definition at line 149 of file epoc-cellpos.cpp.
References iModuleId.
void CSensor_cellpos::PosModLeave (TInt errCode) [private, virtual]
Implements MObserverPosMod.
Definition at line 162 of file epoc-cellpos.cpp.
References er_FATAL, and er_log_symbian.
void CSensor_cellpos::ReadConfig () [private]
Definition at line 493 of file epoc-cellpos.cpp.
References force_get_ConfigDb_int(), iDataMaxAgeSecs, iMinScanRequestIntervalSecs, iSatelliteQueryTimeoutSecs, MIN_SCAN_REQUEST_INTERVAL_SECS, POSITIONER_MAX_AGE_SECS, and SATELLITE_QUERY_TIMEOUT_SECS.
Referenced by ConstructL(), and Reconfigure().
void CSensor_cellpos::Reconfigure (const gchar * name, const gchar * value)
Definition at line 484 of file epoc-cellpos.cpp.
References ReadConfig().
void CSensor_cellpos::RetryTimerExpired (CRetryAo * src, TInt errCode) [private, virtual]
Implements MRetryAoObserver.
Definition at line 167 of file epoc-cellpos.cpp.
References er_FATAL, er_log_symbian, iSatPositioner, and CPositioner_gps::MakeRequest().
void CSensor_cellpos::StartL ()
Definition at line 101 of file epoc-cellpos.cpp.
References EActive, iModuleId, iRetryAo, IsActive(), iState, PosModChangeL(), and CRetryAo::ResetFailures().
void CSensor_cellpos::Stop ()
Definition at line 93 of file epoc-cellpos.cpp.
References EInactive, iModuleAo, iRetryAo, iSatPositioner, and iState.
Referenced by PositionerEventL(), PosModErrorL(), and ~CSensor_cellpos().
Member Data Documentation
TBool CSensor_cellpos::iAllowAssisted [private]
Definition at line 85 of file epoc-cellpos.hpp.
Referenced by BbChangedL(), ConstructL(), and PosModChangeL().
ac_AppContext* CSensor_cellpos::iAppContext [private]
Definition at line 61 of file epoc-cellpos.hpp.
Referenced by ConstructL().
bb::RHandle CSensor_cellpos::iCellChangeHandle [private]
Definition at line 72 of file epoc-cellpos.hpp.
Referenced by ConstructL().
TInt CSensor_cellpos::iDataMaxAgeSecs [private]
Definition at line 89 of file epoc-cellpos.hpp.
Referenced by CreateSpecifiedPositionerL(), and ReadConfig().
TTime CSensor_cellpos::iLastScanTime [private]
Definition at line 75 of file epoc-cellpos.hpp.
Referenced by BbChangedL(), and PositionerEventL().
LogDb* CSensor_cellpos::iLogDb [private]
Definition at line 62 of file epoc-cellpos.hpp.
Referenced by CSensor_cellpos(), and PositionerEventL().
TInt CSensor_cellpos::iMinScanRequestIntervalSecs [private]
Definition at line 87 of file epoc-cellpos.hpp.
Referenced by BbChangedL(), and ReadConfig().
CPosModuleStatAo* CSensor_cellpos::iModuleAo [private]
Definition at line 64 of file epoc-cellpos.hpp.
Referenced by ConstructL(), CreateSpecifiedPositionerL(), PosModChangeL(), Stop(), and ~CSensor_cellpos().
TPositionModuleId CSensor_cellpos::iModuleId [private]
Definition at line 83 of file epoc-cellpos.hpp.
Referenced by CreateSpecifiedPositionerL(), PosModChangeL(), PosModIsCurrent(), and StartL().
bb::RHandle CSensor_cellpos::iNetposChangeHandle [private]
Definition at line 73 of file epoc-cellpos.hpp.
Referenced by ConstructL().
CRetryAo* CSensor_cellpos::iRetryAo [private]
Definition at line 70 of file epoc-cellpos.hpp.
Referenced by BbChangedL(), ConstructL(), PositionerEventL(), PosModChangeL(), StartL(), Stop(), and ~CSensor_cellpos().
TInt CSensor_cellpos::iSatelliteQueryTimeoutSecs [private]
Definition at line 88 of file epoc-cellpos.hpp.
Referenced by CreateSpecifiedPositionerL(), and ReadConfig().
CPositioner_gps* CSensor_cellpos::iSatPositioner [private]
Definition at line 68 of file epoc-cellpos.hpp.
Referenced by BbChangedL(), CreateSpecifiedPositionerL(), PositionerEventL(), PosModChangeL(), RetryTimerExpired(), and Stop().
TState CSensor_cellpos::iState [private]
Definition at line 81 of file epoc-cellpos.hpp.
Referenced by StartL(), and Stop().
The documentation for this class was generated from the following files:
epoc-cellpos.hpp
epoc-cellpos.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1