ContextLogger2 Logger Daemon Internals: CNotifyAo_BatteryInfo Class Reference
CNotifyAo_BatteryInfo Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CNotifyAo_BatteryInfo (CTelephony &aTelephony, MNotifyObs_BatteryInfo &aInterface)
virtual ~CNotifyAo_BatteryInfo ()
void MakeRequest ()
CTelephony::TBatteryInfoV1 const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TBatteryInfoV1 iData
CTelephony::TBatteryInfoV1Pckg iDataDes
CTelephony & iTelephony
MNotifyObs_BatteryInfo & iInterface
Detailed Description
Definition at line 199 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CNotifyAo_BatteryInfo::CNotifyAo_BatteryInfo (CTelephony & aTelephony, MNotifyObs_BatteryInfo & aInterface)
Definition at line 123 of file ut_telephony_epoc.cpp.
CNotifyAo_BatteryInfo::~CNotifyAo_BatteryInfo () [virtual]
Definition at line 128 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TBatteryInfoV1 const & CNotifyAo_BatteryInfo::Data () const [inline]
Definition at line 730 of file ut_telephony_epoc.h.
References iData.
Referenced by CBatteryObserver::ChangedData_BatteryInfo().
void CNotifyAo_BatteryInfo::DoCancel () [private, virtual]
Definition at line 146 of file ut_telephony_epoc.cpp.
References iTelephony.
void CNotifyAo_BatteryInfo::MakeRequest ()
Definition at line 133 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CBatteryObserver::HandleBattery().
void CNotifyAo_BatteryInfo::RunL () [private, virtual]
Definition at line 141 of file ut_telephony_epoc.cpp.
References MNotifyObs_BatteryInfo::ChangedData_BatteryInfo(), and iInterface.
Member Data Documentation
CTelephony::TBatteryInfoV1 CNotifyAo_BatteryInfo::iData [private]
Definition at line 222 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TBatteryInfoV1Pckg CNotifyAo_BatteryInfo::iDataDes [private]
Definition at line 224 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MNotifyObs_BatteryInfo& CNotifyAo_BatteryInfo::iInterface [private]
Definition at line 228 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CNotifyAo_BatteryInfo::iTelephony [private]
Definition at line 226 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1