ContextLogger2 Logger Daemon Internals: CFileDataSupplier Class Reference
CFileDataSupplier Class Reference
#include <up_poster_epoc.hpp>
Public Member Functions
virtual ~CFileDataSupplier ()
void OpenL (const TDesC &aFileName)
void Close ()
void CloseFile ()
const TDesC8 & Boundary () const
TBool GetNextDataPart (TPtrC8 &aDataPart)
void ReleaseData ()
TInt Reset ()
TInt OverallDataSize ()
void SetHttpTransaction (RHTTPTransaction *aTransaction)
Private Member Functions
DEF_SESSION (RFs, iFs)
DEF_SESSION (RFile, iFile)
Private Attributes
TFileName iFileName
RRsBuf8 iPrelude
RRsBuf8 iEpilogue
TBuf8< 512 > iBuffer
TInt iDataLen
TInt iPhase
RHTTPTransaction * iTransaction
Detailed Description
Definition at line 31 of file up_poster_epoc.hpp.
Constructor & Destructor Documentation
CFileDataSupplier::~CFileDataSupplier () [virtual]
Definition at line 277 of file up_poster_epoc.cpp.
References Close().
Member Function Documentation
const TDesC8 & CFileDataSupplier::Boundary () const
Definition at line 349 of file up_poster_epoc.cpp.
References KBoundary.
Referenced by CPosterAo::PostFileL().
void CFileDataSupplier::Close ()
Definition at line 287 of file up_poster_epoc.cpp.
References CloseFile(), iEpilogue, iPrelude, and SESSION_CLOSE_IF_OPEN.
Referenced by OpenL(), and ~CFileDataSupplier().
void CFileDataSupplier::CloseFile ()
Definition at line 282 of file up_poster_epoc.cpp.
References SESSION_CLOSE_IF_OPEN.
Referenced by Close(), and CPosterAo::PostComplete().
CFileDataSupplier::DEF_SESSION (RFile , iFile) [private]
CFileDataSupplier::DEF_SESSION (RFs , iFs) [private]
TBool CFileDataSupplier::GetNextDataPart (TPtrC8 & aDataPart)
Definition at line 363 of file up_poster_epoc.cpp.
References iBuffer, iEpilogue, iPhase, and iPrelude.
void CFileDataSupplier::OpenL (const TDesC & aFileName)
Definition at line 305 of file up_poster_epoc.cpp.
References _LIT8(), RRsBuf8::AppendL(), Close(), RRsBuf8::CopyL(), get_config_username(), iDataLen, iEpilogue, iFileName, iPhase, iPrelude, KBoundary, LEAVE_IF_ERROR_OR_SET_SESSION_OPEN, and logg.
Referenced by CPosterAo::PostFileL().
TInt CFileDataSupplier::OverallDataSize ()
Definition at line 420 of file up_poster_epoc.cpp.
References iDataLen.
void CFileDataSupplier::ReleaseData ()
Definition at line 404 of file up_poster_epoc.cpp.
References iPhase, and iTransaction.
TInt CFileDataSupplier::Reset ()
Definition at line 412 of file up_poster_epoc.cpp.
References iPhase.
void CFileDataSupplier::SetHttpTransaction (RHTTPTransaction * aTransaction) [inline, virtual]
Implements MDataSupplier.
Definition at line 46 of file up_poster_epoc.hpp.
Member Data Documentation
TBuf8<512> CFileDataSupplier::iBuffer [private]
Definition at line 56 of file up_poster_epoc.hpp.
Referenced by GetNextDataPart().
TInt CFileDataSupplier::iDataLen [private]
Definition at line 57 of file up_poster_epoc.hpp.
Referenced by OpenL(), and OverallDataSize().
RRsBuf8 CFileDataSupplier::iEpilogue [private]
Definition at line 55 of file up_poster_epoc.hpp.
Referenced by Close(), GetNextDataPart(), and OpenL().
TFileName CFileDataSupplier::iFileName [private]
Definition at line 51 of file up_poster_epoc.hpp.
Referenced by OpenL().
TInt CFileDataSupplier::iPhase [private]
Definition at line 58 of file up_poster_epoc.hpp.
Referenced by GetNextDataPart(), OpenL(), ReleaseData(), and Reset().
RRsBuf8 CFileDataSupplier::iPrelude [private]
Definition at line 54 of file up_poster_epoc.hpp.
Referenced by Close(), GetNextDataPart(), and OpenL().
RHTTPTransaction* CFileDataSupplier::iTransaction [private]
Definition at line 59 of file up_poster_epoc.hpp.
Referenced by ReleaseData().
The documentation for this class was generated from the following files:
up_poster_epoc.hpp
up_poster_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1