ContextLogger2 Logger Daemon Internals: e_auto_ptr< HBufC16 > Class Template Reference
e_auto_ptr< HBufC16 > Class Template Reference
#include <symbian_auto_ptr.hpp>
Public Member Functions
e_auto_ptr (HBufC16 *aPtr=0)
e_auto_ptr (e_auto_ptr &aPtr)
e_auto_ptr< HBufC16 > & operator= (e_auto_ptr< HBufC16 > &aRhs)
~e_auto_ptr ()
const TDesC16 & operator* () const
HBufC16 * operator-> () const
HBufC16 * get () const
HBufC16 * release ()
void reset (HBufC16 *aPtr=0)
e_auto_ptr (e_auto_ptr_ref< HBufC16 > aRef)
template<class Y >
operator e_auto_ptr_ref< Y > ()
Private Attributes
HBufC16 * iPtr
Detailed Description
template<>
class e_auto_ptr< HBufC16 >
Definition at line 134 of file symbian_auto_ptr.hpp.
Constructor & Destructor Documentation
e_auto_ptr< HBufC16 >::e_auto_ptr (HBufC16 * aPtr = 0) [inline]
Definition at line 138 of file symbian_auto_ptr.hpp.
References CloseHBufC16Indirect().
e_auto_ptr< HBufC16 >::e_auto_ptr (e_auto_ptr< HBufC16 > & aPtr) [inline]
Definition at line 145 of file symbian_auto_ptr.hpp.
References CloseHBufC16Indirect().
e_auto_ptr< HBufC16 >::~e_auto_ptr () [inline]
Definition at line 162 of file symbian_auto_ptr.hpp.
e_auto_ptr< HBufC16 >::e_auto_ptr (e_auto_ptr_ref< HBufC16 > aRef) [inline]
Definition at line 190 of file symbian_auto_ptr.hpp.
References CloseHBufC16Indirect().
Member Function Documentation
HBufC16* e_auto_ptr< HBufC16 >::get () const [inline]
Definition at line 173 of file symbian_auto_ptr.hpp.
template<class Y > e_auto_ptr< HBufC16 >::operator e_auto_ptr_ref< Y > () [inline]
Definition at line 198 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::release().
const TDesC16& e_auto_ptr< HBufC16 >::operator* () const [inline]
Definition at line 170 of file symbian_auto_ptr.hpp.
HBufC16* e_auto_ptr< HBufC16 >::operator-> () const [inline]
Definition at line 171 of file symbian_auto_ptr.hpp.
e_auto_ptr<HBufC16>& e_auto_ptr< HBufC16 >::operator= (e_auto_ptr< HBufC16 > & aRhs) [inline]
Definition at line 152 of file symbian_auto_ptr.hpp.
References release().
HBufC16* e_auto_ptr< HBufC16 >::release () [inline]
Definition at line 175 of file symbian_auto_ptr.hpp.
Referenced by operator=().
void e_auto_ptr< HBufC16 >::reset (HBufC16 * aPtr = 0) [inline]
Definition at line 182 of file symbian_auto_ptr.hpp.
Member Data Documentation
HBufC16* e_auto_ptr< HBufC16 >::iPtr [private]
Definition at line 202 of file symbian_auto_ptr.hpp.
The documentation for this class was generated from the following file:
symbian_auto_ptr.hpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1