ContextLogger2 Logger Daemon Internals: MObserverObs_NetworkRegistration Class Reference
MObserverObs_NetworkRegistration Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
virtual void ObservedData_NetworkRegistration (TData_NetworkRegistration const &aData)=0
virtual void Failed_NetworkRegistration (TInt aError)=0
virtual void InFlightMode_NetworkRegistration ()=0
Detailed Description
Definition at line 641 of file ut_telephony_epoc.h.
Member Function Documentation
virtual void MObserverObs_NetworkRegistration::Failed_NetworkRegistration (TInt aError) [pure virtual]
Implemented in CRegistrationObserver.
Referenced by CObserverAo_NetworkRegistration::HandleData().
virtual void MObserverObs_NetworkRegistration::InFlightMode_NetworkRegistration () [pure virtual]
Implemented in CRegistrationObserver.
Referenced by CObserverAo_NetworkRegistration::HandleFlightModeChange().
virtual void MObserverObs_NetworkRegistration::ObservedData_NetworkRegistration (TData_NetworkRegistration const & aData) [pure virtual]
Implemented in CRegistrationObserver.
Referenced by CObserverAo_NetworkRegistration::HandleData().
The documentation for this class was generated from the following file:
ut_telephony_epoc.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1