ContextLogger2 Logger Daemon Internals: CObserverAo_NetworkInfo Class Reference
CObserverAo_NetworkInfo Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
virtual ~CObserverAo_NetworkInfo ()
void HandleFlightModeChange ()
Static Public Member Functions
static CObserverAo_NetworkInfo * NewLC (ac_AppContext *aAppContext, MObserverObs_NetworkInfo &aInterface)
static CObserverAo_NetworkInfo * NewL (ac_AppContext *aAppContext, MObserverObs_NetworkInfo &aInterface)
Private Member Functions
CObserverAo_NetworkInfo (ac_AppContext *aAppContext, MObserverObs_NetworkInfo &aInterface)
void ConstructL ()
void BbRegisterL ()
void BbUnregister ()
void MakeRequest ()
void Cancel ()
TBool GetFlightMode () const
virtual void RetryTimerExpired (CRetryAo *, TInt aError)
virtual void GotData_NetworkInfo (TInt aError)
virtual void ChangedData_NetworkInfo (TInt aError)
void HandleData (TInt aError, TData_NetworkInfo const &aData)
Private Attributes
ac_AppContext * iAppContext
MObserverObs_NetworkInfo & iInterface
TBool iGetterDone
CGetterAo_NetworkInfo * iGetter
CNotifyAo_NetworkInfo * iNotifier
CRetryAo * iRetryAo
bb_Closure iClosure
Detailed Description
Definition at line 578 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CObserverAo_NetworkInfo::CObserverAo_NetworkInfo (ac_AppContext * aAppContext, MObserverObs_NetworkInfo & aInterface) [private]
Definition at line 460 of file ut_telephony_epoc.cpp.
Referenced by NewLC().
CObserverAo_NetworkInfo::~CObserverAo_NetworkInfo () [virtual]
Definition at line 464 of file ut_telephony_epoc.cpp.
References BbUnregister(), iGetter, iNotifier, and iRetryAo.
Member Function Documentation
void CObserverAo_NetworkInfo::BbRegisterL () [private]
Definition at line 483 of file ut_telephony_epoc.cpp.
References ac_get_Blackboard(), bb_Closure::arg, bb_Blackboard_register(), bb_dt_flightmode, bb_Closure::changed, ClosureFunc_NetworkInfo(), iAppContext, and iClosure.
Referenced by ConstructL().
void CObserverAo_NetworkInfo::BbUnregister () [private]
Definition at line 492 of file ut_telephony_epoc.cpp.
References ac_get_Blackboard(), bb_Blackboard_unregister(), iAppContext, and iClosure.
Referenced by ~CObserverAo_NetworkInfo().
void CObserverAo_NetworkInfo::Cancel () [private]
Definition at line 506 of file ut_telephony_epoc.cpp.
References iGetter, iGetterDone, iNotifier, iRetryAo, and CRetryAo::ResetFailures().
Referenced by HandleFlightModeChange().
void CObserverAo_NetworkInfo::ChangedData_NetworkInfo (TInt aError) [private, virtual]
Implements MNotifyObs_NetworkInfo.
Definition at line 547 of file ut_telephony_epoc.cpp.
References CNotifyAo_NetworkInfo::Data(), HandleData(), and iNotifier.
void CObserverAo_NetworkInfo::ConstructL () [private]
Definition at line 472 of file ut_telephony_epoc.cpp.
References BbRegisterL(), GetFlightMode(), iAppContext, iGetter, iNotifier, iRetryAo, CGetterAo_NetworkInfo::MakeRequest(), and NewL().
TBool CObserverAo_NetworkInfo::GetFlightMode () const [private]
Definition at line 515 of file ut_telephony_epoc.cpp.
References ac_global_Blackboard, bb_Blackboard_board(), and bb_Board::flightmode.
Referenced by ConstructL(), and HandleFlightModeChange().
void CObserverAo_NetworkInfo::GotData_NetworkInfo (TInt aError) [private, virtual]
Implements MGetterObs_NetworkInfo.
Definition at line 539 of file ut_telephony_epoc.cpp.
References CGetterAo_NetworkInfo::Data(), HandleData(), iGetter, and iGetterDone.
void CObserverAo_NetworkInfo::HandleData (TInt aError, TData_NetworkInfo const & aData) [private]
Definition at line 552 of file ut_telephony_epoc.cpp.
References iInterface, iNotifier, iRetryAo, CNotifyAo_NetworkInfo::MakeRequest(), MObserverObs_NetworkInfo::ObservedData_NetworkInfo(), MObserverObs_NetworkInfo::ReportTransientError_NetworkInfo(), CRetryAo::ResetFailures(), MObserverObs_NetworkInfo::RetriesExhausted_NetworkInfo(), and CRetryAo::Retry().
Referenced by ChangedData_NetworkInfo(), and GotData_NetworkInfo().
void CObserverAo_NetworkInfo::HandleFlightModeChange ()
Definition at line 520 of file ut_telephony_epoc.cpp.
References Cancel(), GetFlightMode(), iInterface, MObserverObs_NetworkInfo::InFlightMode_NetworkInfo(), and MakeRequest().
void CObserverAo_NetworkInfo::MakeRequest () [private]
Definition at line 497 of file ut_telephony_epoc.cpp.
References iGetter, iGetterDone, iNotifier, CGetterAo_NetworkInfo::MakeRequest(), and CNotifyAo_NetworkInfo::MakeRequest().
Referenced by HandleFlightModeChange(), and RetryTimerExpired().
CObserverAo_NetworkInfo * CObserverAo_NetworkInfo::NewL (ac_AppContext * aAppContext, MObserverObs_NetworkInfo & aInterface) [static]
Definition at line 453 of file ut_telephony_epoc.cpp.
References NewLC().
Referenced by ConstructL().
CObserverAo_NetworkInfo * CObserverAo_NetworkInfo::NewLC (ac_AppContext * aAppContext, MObserverObs_NetworkInfo & aInterface) [static]
Definition at line 445 of file ut_telephony_epoc.cpp.
References CObserverAo_NetworkInfo().
Referenced by NewL().
void CObserverAo_NetworkInfo::RetryTimerExpired (CRetryAo * , TInt aError) [private, virtual]
Implements MRetryAoObserver.
Definition at line 530 of file ut_telephony_epoc.cpp.
References er_FATAL, er_log_symbian, and MakeRequest().
Member Data Documentation
ac_AppContext* CObserverAo_NetworkInfo::iAppContext [private]
Definition at line 600 of file ut_telephony_epoc.h.
Referenced by BbRegisterL(), BbUnregister(), and ConstructL().
bb_Closure CObserverAo_NetworkInfo::iClosure [private]
Definition at line 612 of file ut_telephony_epoc.h.
Referenced by BbRegisterL(), and BbUnregister().
CGetterAo_NetworkInfo* CObserverAo_NetworkInfo::iGetter [private]
Definition at line 606 of file ut_telephony_epoc.h.
Referenced by Cancel(), ConstructL(), GotData_NetworkInfo(), MakeRequest(), and ~CObserverAo_NetworkInfo().
TBool CObserverAo_NetworkInfo::iGetterDone [private]
Definition at line 604 of file ut_telephony_epoc.h.
Referenced by Cancel(), GotData_NetworkInfo(), and MakeRequest().
MObserverObs_NetworkInfo& CObserverAo_NetworkInfo::iInterface [private]
Definition at line 602 of file ut_telephony_epoc.h.
Referenced by HandleData(), and HandleFlightModeChange().
CNotifyAo_NetworkInfo* CObserverAo_NetworkInfo::iNotifier [private]
Definition at line 608 of file ut_telephony_epoc.h.
Referenced by Cancel(), ChangedData_NetworkInfo(), ConstructL(), HandleData(), MakeRequest(), and ~CObserverAo_NetworkInfo().
CRetryAo* CObserverAo_NetworkInfo::iRetryAo [private]
Definition at line 610 of file ut_telephony_epoc.h.
Referenced by Cancel(), ConstructL(), HandleData(), and ~CObserverAo_NetworkInfo().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1