ContextLogger2 Logger Daemon Internals: CObserverAo_SignalStrength Class Reference
CObserverAo_SignalStrength Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
virtual ~CObserverAo_SignalStrength ()
void HandleFlightModeChange ()
Static Public Member Functions
static CObserverAo_SignalStrength * NewLC (ac_AppContext *aAppContext, MObserverObs_SignalStrength &aInterface)
static CObserverAo_SignalStrength * NewL (ac_AppContext *aAppContext, MObserverObs_SignalStrength &aInterface)
Private Member Functions
CObserverAo_SignalStrength (ac_AppContext *aAppContext, MObserverObs_SignalStrength &aInterface)
void ConstructL ()
void BbRegisterL ()
void BbUnregister ()
void MakeRequest ()
void Cancel ()
TBool GetFlightMode () const
virtual void RetryTimerExpired (CRetryAo *, TInt aError)
virtual void GotData_SignalStrength (TInt aError)
virtual void ChangedData_SignalStrength (TInt aError)
void HandleData (TInt aError, TData_SignalStrength const &aData)
Private Attributes
ac_AppContext * iAppContext
MObserverObs_SignalStrength & iInterface
TBool iGetterDone
CGetterAo_SignalStrength * iGetter
CNotifyAo_SignalStrength * iNotifier
CRetryAo * iRetryAo
bb_Closure iClosure
Detailed Description
Definition at line 502 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CObserverAo_SignalStrength::CObserverAo_SignalStrength (ac_AppContext * aAppContext, MObserverObs_SignalStrength & aInterface) [private]
Definition at line 334 of file ut_telephony_epoc.cpp.
Referenced by NewLC().
CObserverAo_SignalStrength::~CObserverAo_SignalStrength () [virtual]
Definition at line 338 of file ut_telephony_epoc.cpp.
References BbUnregister(), iGetter, iNotifier, and iRetryAo.
Member Function Documentation
void CObserverAo_SignalStrength::BbRegisterL () [private]
Definition at line 357 of file ut_telephony_epoc.cpp.
References ac_get_Blackboard(), bb_Closure::arg, bb_Blackboard_register(), bb_dt_flightmode, bb_Closure::changed, ClosureFunc_SignalStrength(), iAppContext, and iClosure.
Referenced by ConstructL().
void CObserverAo_SignalStrength::BbUnregister () [private]
Definition at line 366 of file ut_telephony_epoc.cpp.
References ac_get_Blackboard(), bb_Blackboard_unregister(), iAppContext, and iClosure.
Referenced by ~CObserverAo_SignalStrength().
void CObserverAo_SignalStrength::Cancel () [private]
Definition at line 380 of file ut_telephony_epoc.cpp.
References iGetter, iGetterDone, iNotifier, iRetryAo, and CRetryAo::ResetFailures().
Referenced by HandleFlightModeChange().
void CObserverAo_SignalStrength::ChangedData_SignalStrength (TInt aError) [private, virtual]
Implements MNotifyObs_SignalStrength.
Definition at line 421 of file ut_telephony_epoc.cpp.
References CNotifyAo_SignalStrength::Data(), HandleData(), and iNotifier.
void CObserverAo_SignalStrength::ConstructL () [private]
Definition at line 346 of file ut_telephony_epoc.cpp.
References BbRegisterL(), GetFlightMode(), iAppContext, iGetter, iNotifier, iRetryAo, CGetterAo_SignalStrength::MakeRequest(), and NewL().
TBool CObserverAo_SignalStrength::GetFlightMode () const [private]
Definition at line 389 of file ut_telephony_epoc.cpp.
References ac_global_Blackboard, bb_Blackboard_board(), and bb_Board::flightmode.
Referenced by ConstructL(), and HandleFlightModeChange().
void CObserverAo_SignalStrength::GotData_SignalStrength (TInt aError) [private, virtual]
Implements MGetterObs_SignalStrength.
Definition at line 413 of file ut_telephony_epoc.cpp.
References CGetterAo_SignalStrength::Data(), HandleData(), iGetter, and iGetterDone.
void CObserverAo_SignalStrength::HandleData (TInt aError, TData_SignalStrength const & aData) [private]
Definition at line 426 of file ut_telephony_epoc.cpp.
References iInterface, iNotifier, iRetryAo, CNotifyAo_SignalStrength::MakeRequest(), MObserverObs_SignalStrength::ObservedData_SignalStrength(), MObserverObs_SignalStrength::ReportTransientError_SignalStrength(), CRetryAo::ResetFailures(), MObserverObs_SignalStrength::RetriesExhausted_SignalStrength(), and CRetryAo::Retry().
Referenced by ChangedData_SignalStrength(), and GotData_SignalStrength().
void CObserverAo_SignalStrength::HandleFlightModeChange ()
Definition at line 394 of file ut_telephony_epoc.cpp.
References Cancel(), GetFlightMode(), iInterface, MObserverObs_SignalStrength::InFlightMode_SignalStrength(), and MakeRequest().
void CObserverAo_SignalStrength::MakeRequest () [private]
Definition at line 371 of file ut_telephony_epoc.cpp.
References iGetter, iGetterDone, iNotifier, CGetterAo_SignalStrength::MakeRequest(), and CNotifyAo_SignalStrength::MakeRequest().
Referenced by HandleFlightModeChange(), and RetryTimerExpired().
CObserverAo_SignalStrength * CObserverAo_SignalStrength::NewL (ac_AppContext * aAppContext, MObserverObs_SignalStrength & aInterface) [static]
Definition at line 327 of file ut_telephony_epoc.cpp.
References NewLC().
Referenced by ConstructL().
CObserverAo_SignalStrength * CObserverAo_SignalStrength::NewLC (ac_AppContext * aAppContext, MObserverObs_SignalStrength & aInterface) [static]
Definition at line 319 of file ut_telephony_epoc.cpp.
References CObserverAo_SignalStrength().
Referenced by NewL().
void CObserverAo_SignalStrength::RetryTimerExpired (CRetryAo * , TInt aError) [private, virtual]
Implements MRetryAoObserver.
Definition at line 404 of file ut_telephony_epoc.cpp.
References er_FATAL, er_log_symbian, and MakeRequest().
Member Data Documentation
ac_AppContext* CObserverAo_SignalStrength::iAppContext [private]
Definition at line 524 of file ut_telephony_epoc.h.
Referenced by BbRegisterL(), BbUnregister(), and ConstructL().
bb_Closure CObserverAo_SignalStrength::iClosure [private]
Definition at line 536 of file ut_telephony_epoc.h.
Referenced by BbRegisterL(), and BbUnregister().
CGetterAo_SignalStrength* CObserverAo_SignalStrength::iGetter [private]
Definition at line 530 of file ut_telephony_epoc.h.
Referenced by Cancel(), ConstructL(), GotData_SignalStrength(), MakeRequest(), and ~CObserverAo_SignalStrength().
TBool CObserverAo_SignalStrength::iGetterDone [private]
Definition at line 528 of file ut_telephony_epoc.h.
Referenced by Cancel(), GotData_SignalStrength(), and MakeRequest().
MObserverObs_SignalStrength& CObserverAo_SignalStrength::iInterface [private]
Definition at line 526 of file ut_telephony_epoc.h.
Referenced by HandleData(), and HandleFlightModeChange().
CNotifyAo_SignalStrength* CObserverAo_SignalStrength::iNotifier [private]
Definition at line 532 of file ut_telephony_epoc.h.
Referenced by Cancel(), ChangedData_SignalStrength(), ConstructL(), HandleData(), MakeRequest(), and ~CObserverAo_SignalStrength().
CRetryAo* CObserverAo_SignalStrength::iRetryAo [private]
Definition at line 534 of file ut_telephony_epoc.h.
Referenced by Cancel(), ConstructL(), HandleData(), and ~CObserverAo_SignalStrength().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1