ContextLogger2 Logger Daemon Internals: CProcessHandleObserver Class Reference
CProcessHandleObserver Class Reference
#include <process_handle_observer.h>
Public Member Functions
~CProcessHandleObserver ()
void MakeRequest ()
Static Public Member Functions
static CProcessHandleObserver * NewLC (MProcessHandleObserver &aInterface, TInt aPriority, RProcess &aProcess)
static CProcessHandleObserver * NewL (MProcessHandleObserver &aInterface, TInt aPriority, RProcess &aProcess)
Private Member Functions
CProcessHandleObserver (MProcessHandleObserver &aInterface, TInt aPriority, RProcess &aProcess)
void ConstructL ()
void DoCancel ()
virtual void RunL ()
Private Attributes
MProcessHandleObserver & iInterface
RProcess & iProcess
Detailed Description
A fairly generic active object that delivers process handle events via a callback interface.
Definition at line 21 of file process_handle_observer.h.
Constructor & Destructor Documentation
CProcessHandleObserver::CProcessHandleObserver (MProcessHandleObserver & aInterface, TInt aPriority, RProcess & aProcess) [private]
Definition at line 20 of file process_handle_observer.cpp.
Referenced by NewLC().
CProcessHandleObserver::~CProcessHandleObserver ()
Definition at line 29 of file process_handle_observer.cpp.
Member Function Documentation
void CProcessHandleObserver::ConstructL () [private]
Definition at line 25 of file process_handle_observer.cpp.
void CProcessHandleObserver::DoCancel () [private]
Definition at line 40 of file process_handle_observer.cpp.
References iProcess.
void CProcessHandleObserver::MakeRequest ()
Definition at line 34 of file process_handle_observer.cpp.
References iProcess.
Referenced by CWatchdog::ObserveProcess().
CProcessHandleObserver * CProcessHandleObserver::NewL (MProcessHandleObserver & aInterface, TInt aPriority, RProcess & aProcess) [static]
Definition at line 13 of file process_handle_observer.cpp.
References NewLC().
CProcessHandleObserver * CProcessHandleObserver::NewLC (MProcessHandleObserver & aInterface, TInt aPriority, RProcess & aProcess) [static]
Definition at line 5 of file process_handle_observer.cpp.
References CProcessHandleObserver().
Referenced by NewL().
void CProcessHandleObserver::RunL () [private, virtual]
Definition at line 45 of file process_handle_observer.cpp.
References MProcessHandleObserver::HandleProcessHandleEvent(), and iInterface.
Member Data Documentation
MProcessHandleObserver& CProcessHandleObserver::iInterface [private]
Definition at line 48 of file process_handle_observer.h.
Referenced by RunL().
RProcess& CProcessHandleObserver::iProcess [private]
Definition at line 50 of file process_handle_observer.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
process_handle_observer.h
process_handle_observer.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1