ContextLogger2 Logger Daemon Internals: Sensor_light Class Reference
Sensor_light Class Reference
#include <sa_sensor_light_qt.hpp>
Public Member Functions
Sensor_light (ac_AppContext *aAppContext)
Private Member Functions
virtual const char * Name () const
virtual void handleReadingChanged ()
Detailed Description
Definition at line 10 of file sa_sensor_light_qt.hpp.
Constructor & Destructor Documentation
Sensor_light::Sensor_light (ac_AppContext * aAppContext)
Definition at line 10 of file sa_sensor_light_qt.cpp.
References ClQtEventSensorBase::run().
Referenced by new_Sensor_light().
Member Function Documentation
void Sensor_light::handleReadingChanged () [private, virtual]
Implements ClQtEventSensorBase.
Definition at line 21 of file sa_sensor_light_qt.cpp.
References ClQtEventSensorBase::GetLogDb(), guilogf(), and log_db_log_light().
const char * Sensor_light::Name () const [private, virtual]
Implements ClQtEventSensorBase.
Definition at line 16 of file sa_sensor_light_qt.cpp.
The documentation for this class was generated from the following files:
sa_sensor_light_qt.hpp
sa_sensor_light_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1