ContextLogger2 Logger Daemon Internals: CActiveRetry Class Reference
CActiveRetry Class Reference
#include <sa_sensor_util_epoc.hpp>
Protected Types
enum TRetryState { EInactive = 0, EDoingActual, ERetryWaiting }
Protected Member Functions
CActiveRetry (TInt aPriority)
virtual ~CActiveRetry ()
DEF_SESSION (RTimer, iRetryTimer)
void TimerConstructL ()
virtual TInt MaxNumRetries ()
virtual TInt BaseInterval ()
virtual TTimeIntervalMicroSeconds32 WaitInterval ()
virtual void RunActualL ()=0
virtual void MakeRequestActual ()=0
virtual void DoCancelActual ()=0
void MakeRequest ()
void Retry ()
Protected Attributes
TInt iNumScanFailures
TRetryState iRetryState
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Detailed Description
Definition at line 15 of file sa_sensor_util_epoc.hpp.
Member Enumeration Documentation
enum CActiveRetry::TRetryState [protected]
Enumerator:
EInactive
EDoingActual
ERetryWaiting
Definition at line 29 of file sa_sensor_util_epoc.hpp.
Constructor & Destructor Documentation
CActiveRetry::CActiveRetry (TInt aPriority) [inline, protected]
Definition at line 20 of file sa_sensor_util_epoc.hpp.
CActiveRetry::~CActiveRetry () [protected, virtual]
Definition at line 18 of file sa_sensor_util_epoc.cpp.
References SESSION_CLOSE_IF_OPEN.
Member Function Documentation
virtual TInt CActiveRetry::BaseInterval () [inline, protected, virtual]
Definition at line 44 of file sa_sensor_util_epoc.hpp.
Referenced by WaitInterval().
CActiveRetry::DEF_SESSION (RTimer , iRetryTimer) [protected]
void CActiveRetry::DoCancel () [private, virtual]
Definition at line 68 of file sa_sensor_util_epoc.cpp.
References DoCancelActual(), EDoingActual, EInactive, ERetryWaiting, and iRetryState.
virtual void CActiveRetry::DoCancelActual () [protected, pure virtual]
Referenced by DoCancel().
void CActiveRetry::MakeRequest () [inline, protected]
Definition at line 54 of file sa_sensor_util_epoc.hpp.
Referenced by RunL(), and CActiveSensorG::StartL().
virtual void CActiveRetry::MakeRequestActual () [protected, pure virtual]
virtual TInt CActiveRetry::MaxNumRetries () [inline, protected, virtual]
Definition at line 42 of file sa_sensor_util_epoc.hpp.
void CActiveRetry::Retry () [protected]
Definition at line 30 of file sa_sensor_util_epoc.cpp.
References ERetryWaiting, iRetryState, and WaitInterval().
virtual void CActiveRetry::RunActualL () [protected, pure virtual]
Referenced by RunL().
void CActiveRetry::RunL () [private, virtual]
Definition at line 38 of file sa_sensor_util_epoc.cpp.
References EDoingActual, EInactive, ERetryWaiting, iRetryState, MakeRequest(), and RunActualL().
void CActiveRetry::TimerConstructL () [protected]
Definition at line 13 of file sa_sensor_util_epoc.cpp.
References LEAVE_IF_ERROR_OR_SET_SESSION_OPEN.
TTimeIntervalMicroSeconds32 CActiveRetry::WaitInterval () [protected, virtual]
Definition at line 23 of file sa_sensor_util_epoc.cpp.
References BaseInterval(), iNumScanFailures, and SecsToUsecs().
Referenced by Retry().
Member Data Documentation
TInt CActiveRetry::iNumScanFailures [protected]
Definition at line 27 of file sa_sensor_util_epoc.hpp.
Referenced by CActiveSensorG::StartL(), and WaitInterval().
TRetryState CActiveRetry::iRetryState [protected]
Definition at line 35 of file sa_sensor_util_epoc.hpp.
Referenced by DoCancel(), Retry(), and RunL().
The documentation for this class was generated from the following files:
sa_sensor_util_epoc.hpp
sa_sensor_util_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1