ContextLogger2 Logger Daemon Internals: CNotifyAo_FlightMode Class Reference
CNotifyAo_FlightMode Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CNotifyAo_FlightMode (CTelephony &aTelephony, MNotifyObs_FlightMode &aInterface)
virtual ~CNotifyAo_FlightMode ()
void MakeRequest ()
CTelephony::TFlightModeV1 const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TFlightModeV1 iData
CTelephony::TFlightModeV1Pckg iDataDes
CTelephony & iTelephony
MNotifyObs_FlightMode & iInterface
Detailed Description
Definition at line 70 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CNotifyAo_FlightMode::CNotifyAo_FlightMode (CTelephony & aTelephony, MNotifyObs_FlightMode & aInterface)
Definition at line 39 of file ut_telephony_epoc.cpp.
CNotifyAo_FlightMode::~CNotifyAo_FlightMode () [virtual]
Definition at line 44 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TFlightModeV1 const & CNotifyAo_FlightMode::Data () const [inline]
Definition at line 715 of file ut_telephony_epoc.h.
References iData.
Referenced by CSensor_callstatus::ChangedData_FlightMode(), and CFlightModeObserver::ChangedData_FlightMode().
void CNotifyAo_FlightMode::DoCancel () [private, virtual]
Definition at line 62 of file ut_telephony_epoc.cpp.
References iTelephony.
void CNotifyAo_FlightMode::MakeRequest ()
Definition at line 49 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CSensor_callstatus::ChangedData_FlightMode(), CSensor_callstatus::GotData_FlightMode(), and CFlightModeObserver::HandleFlightMode().
void CNotifyAo_FlightMode::RunL () [private, virtual]
Definition at line 57 of file ut_telephony_epoc.cpp.
References MNotifyObs_FlightMode::ChangedData_FlightMode(), and iInterface.
Member Data Documentation
CTelephony::TFlightModeV1 CNotifyAo_FlightMode::iData [private]
Definition at line 93 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TFlightModeV1Pckg CNotifyAo_FlightMode::iDataDes [private]
Definition at line 95 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MNotifyObs_FlightMode& CNotifyAo_FlightMode::iInterface [private]
Definition at line 99 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CNotifyAo_FlightMode::iTelephony [private]
Definition at line 97 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1