ContextLogger2 Logger Daemon Internals: CPositioner_gps Class Reference
CPositioner_gps Class Reference
#include <epoc-gps-positioner.hpp>
Public Member Functions
virtual ~CPositioner_gps ()
void MakeRequest ()
TInt StatusCode () const
const TPositionSatelliteInfo & PositionInfo () const
TPositionModuleId ModuleId () const
Public Attributes
CTOR_DECL_CPositioner_gps
Private Member Functions
virtual gboolean RunGL (GError **error)
virtual const char * Description ()
virtual void DoCancel ()
DEF_SESSION (RPositioner, iPositioner)
Private Attributes
RPositionServer & iPositionServer
MObserver_gps & iObserver
TPositionModuleId iModuleId
TPositionUpdateOptions iUpdateOptions
TPositionSatelliteInfo iPositionInfo
Detailed Description
Definition at line 57 of file epoc-gps-positioner.hpp.
Constructor & Destructor Documentation
CPositioner_gps::~CPositioner_gps () [virtual]
Definition at line 44 of file epoc-gps-positioner.cpp.
References SESSION_CLOSE_IF_OPEN.
Member Function Documentation
CPositioner_gps::DEF_SESSION (RPositioner , iPositioner) [private]
const char * CPositioner_gps::Description () [private, virtual]
Implements CActiveLogErr.
Definition at line 61 of file epoc-gps-positioner.cpp.
void CPositioner_gps::DoCancel () [private, virtual]
Definition at line 66 of file epoc-gps-positioner.cpp.
References IS_SESSION_OPEN.
void CPositioner_gps::MakeRequest ()
Definition at line 50 of file epoc-gps-positioner.cpp.
References iPositionInfo.
Referenced by CSensor_cellpos::BbChangedL(), and CSensor_cellpos::RetryTimerExpired().
TPositionModuleId CPositioner_gps::ModuleId () const [inline]
Definition at line 75 of file epoc-gps-positioner.hpp.
const TPositionSatelliteInfo& CPositioner_gps::PositionInfo () const [inline]
Definition at line 73 of file epoc-gps-positioner.hpp.
Referenced by CSensor_cellpos::PositionerEventL().
gboolean CPositioner_gps::RunGL (GError ** error) [private, virtual]
This function may either leave or return a GError.
Implements CActiveRunG.
Definition at line 56 of file epoc-gps-positioner.cpp.
References iObserver, and MObserver_gps::PositionerEventL().
TInt CPositioner_gps::StatusCode () const [inline]
Definition at line 71 of file epoc-gps-positioner.hpp.
Referenced by CSensor_cellpos::PositionerEventL().
Member Data Documentation
CPositioner_gps::CTOR_DECL_CPositioner_gps
Definition at line 64 of file epoc-gps-positioner.hpp.
TPositionModuleId CPositioner_gps::iModuleId [private]
Definition at line 89 of file epoc-gps-positioner.hpp.
MObserver_gps& CPositioner_gps::iObserver [private]
Definition at line 88 of file epoc-gps-positioner.hpp.
Referenced by RunGL().
TPositionSatelliteInfo CPositioner_gps::iPositionInfo [private]
Definition at line 96 of file epoc-gps-positioner.hpp.
Referenced by MakeRequest().
RPositionServer& CPositioner_gps::iPositionServer [private]
Definition at line 87 of file epoc-gps-positioner.hpp.
TPositionUpdateOptions CPositioner_gps::iUpdateOptions [private]
Definition at line 93 of file epoc-gps-positioner.hpp.
The documentation for this class was generated from the following files:
epoc-gps-positioner.hpp
epoc-gps-positioner.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1