ContextLogger2 Logger Daemon Internals: MObserverObs_SignalStrength Class Reference
MObserverObs_SignalStrength Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
virtual void ObservedData_SignalStrength (TData_SignalStrength const &aData)=0
virtual void ReportTransientError_SignalStrength (TInt aError)=0
virtual void RetriesExhausted_SignalStrength ()=0
virtual void InFlightMode_SignalStrength ()=0
Detailed Description
Definition at line 489 of file ut_telephony_epoc.h.
Member Function Documentation
virtual void MObserverObs_SignalStrength::InFlightMode_SignalStrength () [pure virtual]
Referenced by CObserverAo_SignalStrength::HandleFlightModeChange().
virtual void MObserverObs_SignalStrength::ObservedData_SignalStrength (TData_SignalStrength const & aData) [pure virtual]
Referenced by CObserverAo_SignalStrength::HandleData().
virtual void MObserverObs_SignalStrength::ReportTransientError_SignalStrength (TInt aError) [pure virtual]
Referenced by CObserverAo_SignalStrength::HandleData().
virtual void MObserverObs_SignalStrength::RetriesExhausted_SignalStrength () [pure virtual]
Referenced by CObserverAo_SignalStrength::HandleData().
The documentation for this class was generated from the following file:
ut_telephony_epoc.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1