ContextLogger2 Logger Daemon Internals: CPosterAo Class Reference
CPosterAo Class Reference
#include <up_poster_epoc.hpp>
Public Member Functions
~CPosterAo ()
void PostFileL (const TDesC8 &aUri, const TDesC &aFileName)
TBool IsActive () const
Private Types
enum TState { EReady = 0, EActive, EDone }
Private Member Functions
DEF_SESSION (RSocketServ, iSocketServ)
DEF_SESSION (RConnection, iConnection)
DEF_SESSION (RHTTPSession, iHttpSession)
DEF_SESSION (RHTTPTransaction, iHttpTransaction)
void MHFRunL (RHTTPTransaction aTransaction, const THTTPEvent &aEvent)
TInt MHFRunError (TInt aError, RHTTPTransaction aTransaction, const THTTPEvent &aEvent)
void PostComplete (TInt errCode)
void SetHeaderL (RHTTPHeaders aHeaders, TInt aHdrField, const TDesC8 &aHdrValue)
void SetBoundary (const TDesC8 &aBoundary)
void PostGenericL (const TDesC8 &aUri, MDataSupplier &aDataSupplier)
Private Attributes
CTOR_DECL_CPosterAo
TState iState
MPosterObserver & iObserver
TUint32 iIapId
TInt iHttpStatus
CFileDataSupplier * iFileDataSupplier
TBuf8< KMultiPartBoundaryMaxLen > iBoundary
Detailed Description
Definition at line 111 of file up_poster_epoc.hpp.
Member Enumeration Documentation
enum CPosterAo::TState [private]
Enumerator:
EReady
EActive
EDone
Definition at line 118 of file up_poster_epoc.hpp.
Constructor & Destructor Documentation
CPosterAo::~CPosterAo ()
Definition at line 47 of file up_poster_epoc.cpp.
References iFileDataSupplier, and SESSION_CLOSE_IF_OPEN.
Member Function Documentation
CPosterAo::DEF_SESSION (RHTTPTransaction , iHttpTransaction) [private]
CPosterAo::DEF_SESSION (RHTTPSession , iHttpSession) [private]
CPosterAo::DEF_SESSION (RConnection , iConnection) [private]
CPosterAo::DEF_SESSION (RSocketServ , iSocketServ) [private]
TBool CPosterAo::IsActive () const [inline]
Definition at line 141 of file up_poster_epoc.hpp.
Referenced by CUploader::PosterAoIsActive().
TInt CPosterAo::MHFRunError (TInt aError, RHTTPTransaction aTransaction, const THTTPEvent & aEvent) [private]
Definition at line 260 of file up_poster_epoc.cpp.
References logg, and PostComplete().
void CPosterAo::MHFRunL (RHTTPTransaction aTransaction, const THTTPEvent & aEvent) [private]
Definition at line 148 of file up_poster_epoc.cpp.
References body(), iHttpStatus, logg, logt, PostComplete(), POSTER_SUCCESS, and POSTER_TRANSIENT_FAILURE.
void CPosterAo::PostComplete (TInt errCode) [private]
Definition at line 74 of file up_poster_epoc.cpp.
References CFileDataSupplier::CloseFile(), EActive, EDone, iFileDataSupplier, iObserver, iState, logh, and MPosterObserver::PosterEvent().
Referenced by MHFRunError(), and MHFRunL().
void CPosterAo::PostFileL (const TDesC8 & aUri, const TDesC & aFileName)
Definition at line 84 of file up_poster_epoc.cpp.
References CFileDataSupplier::Boundary(), EReady, iFileDataSupplier, iState, CFileDataSupplier::OpenL(), PostGenericL(), and SetBoundary().
Referenced by CUploader::PostNowL().
void CPosterAo::PostGenericL (const TDesC8 & aUri, MDataSupplier & aDataSupplier) [private]
Definition at line 100 of file up_poster_epoc.cpp.
References _LIT8(), EActive, iBoundary, iState, SESSION_CLOSE_IF_OPEN, SET_SESSION_OPEN, SetHeaderL(), and MDataSupplier::SetHttpTransaction().
Referenced by PostFileL().
void CPosterAo::SetBoundary (const TDesC8 & aBoundary) [inline, private]
Definition at line 156 of file up_poster_epoc.hpp.
Referenced by PostFileL().
void CPosterAo::SetHeaderL (RHTTPHeaders aHeaders, TInt aHdrField, const TDesC8 & aHdrValue) [private]
Definition at line 61 of file up_poster_epoc.cpp.
Referenced by PostGenericL().
Member Data Documentation
CPosterAo::CTOR_DECL_CPosterAo [private]
Definition at line 115 of file up_poster_epoc.hpp.
TBuf8<KMultiPartBoundaryMaxLen> CPosterAo::iBoundary [private]
Definition at line 132 of file up_poster_epoc.hpp.
Referenced by PostGenericL().
CFileDataSupplier* CPosterAo::iFileDataSupplier [private]
Definition at line 130 of file up_poster_epoc.hpp.
Referenced by PostComplete(), PostFileL(), and ~CPosterAo().
TInt CPosterAo::iHttpStatus [private]
Definition at line 128 of file up_poster_epoc.hpp.
Referenced by MHFRunL().
TUint32 CPosterAo::iIapId [private]
Definition at line 122 of file up_poster_epoc.hpp.
MPosterObserver& CPosterAo::iObserver [private]
Definition at line 121 of file up_poster_epoc.hpp.
Referenced by PostComplete().
TState CPosterAo::iState [private]
Definition at line 119 of file up_poster_epoc.hpp.
Referenced by PostComplete(), PostFileL(), and PostGenericL().
The documentation for this class was generated from the following files:
up_poster_epoc.hpp
up_poster_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1