ContextLogger2 Logger Daemon Internals: CTimeOutImpl Class Reference
CTimeOutImpl Class Reference
Public Member Functions
~CTimeOutImpl ()
Private Member Functions
virtual void Wait (int seconds)
virtual void WaitMax (int seconds)
virtual void Reset ()
virtual void WaitShort (int milliseconds)
virtual const TTime & WaitingUntil () const
CTimeOutImpl (MTimeOut &i_cb, CActive::TPriority aPriority)
void ConstructL ()
void RunL ()
Private Attributes
MTimeOut & cb
TTime iWaitUntil
Friends
class CTimeOut
Detailed Description
Definition at line 50 of file ut_timeout_epoc.cpp.
Constructor & Destructor Documentation
CTimeOutImpl::~CTimeOutImpl ()
Definition at line 160 of file ut_timeout_epoc.cpp.
CTimeOutImpl::CTimeOutImpl (MTimeOut & i_cb, CActive::TPriority aPriority) [private]
Definition at line 79 of file ut_timeout_epoc.cpp.
Member Function Documentation
void CTimeOutImpl::ConstructL () [private]
Definition at line 84 of file ut_timeout_epoc.cpp.
void CTimeOutImpl::Reset () [private, virtual]
Implements CTimeOut.
Definition at line 154 of file ut_timeout_epoc.cpp.
References iWaitUntil.
Referenced by Wait(), WaitMax(), and WaitShort().
void CTimeOutImpl::RunL () [private]
Definition at line 97 of file ut_timeout_epoc.cpp.
References cb, MTimeOut::expired(), and iWaitUntil.
void CTimeOutImpl::Wait (int seconds) [private, virtual]
Implements CTimeOut.
Definition at line 131 of file ut_timeout_epoc.cpp.
References iWaitUntil, and Reset().
const TTime & CTimeOutImpl::WaitingUntil () const [private, virtual]
Implements CTimeOut.
Definition at line 114 of file ut_timeout_epoc.cpp.
References iWaitUntil.
void CTimeOutImpl::WaitMax (int seconds) [private, virtual]
Implements CTimeOut.
Definition at line 143 of file ut_timeout_epoc.cpp.
References iWaitUntil, and Reset().
void CTimeOutImpl::WaitShort (int milliseconds) [private, virtual]
Implements CTimeOut.
Definition at line 119 of file ut_timeout_epoc.cpp.
References iWaitUntil, and Reset().
Friends And Related Function Documentation
friend class CTimeOut [friend]
Definition at line 68 of file ut_timeout_epoc.cpp.
Member Data Documentation
MTimeOut& CTimeOutImpl::cb [private]
Definition at line 65 of file ut_timeout_epoc.cpp.
Referenced by RunL().
TTime CTimeOutImpl::iWaitUntil [private]
Definition at line 66 of file ut_timeout_epoc.cpp.
Referenced by Reset(), RunL(), Wait(), WaitingUntil(), WaitMax(), and WaitShort().
The documentation for this class was generated from the following file:
ut_timeout_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1