ContextLogger2 Logger Daemon Internals: CRetryAo Class Reference
CRetryAo Class Reference
#include <ut_retry_epoc.hpp>
Public Member Functions
~CRetryAo ()
TBool Retry () __attribute__((warn_unused_result))
void ResetFailures ()
Static Public Member Functions
static CRetryAo * NewL (MRetryAoObserver &aObserver, TInt aMaxNumRetries, TInt aBaseInterval)
Protected Member Functions
DEF_SESSION (RTimer, iTimer)
virtual TTimeIntervalMicroSeconds32 WaitInterval ()
Protected Attributes
MRetryAoObserver & iObserver
TInt iMaxNumRetries
TInt iBaseInterval
TInt iNumScanFailures
Private Member Functions
CRetryAo (MRetryAoObserver &aObserver, TInt aMaxNumRetries, TInt aBaseInterval)
void ConstructL ()
virtual void RunL ()
virtual void DoCancel ()
Detailed Description
Definition at line 24 of file ut_retry_epoc.hpp.
Constructor & Destructor Documentation
CRetryAo::~CRetryAo ()
Definition at line 46 of file ut_retry_epoc.cpp.
References SESSION_CLOSE_IF_OPEN.
CRetryAo::CRetryAo (MRetryAoObserver & aObserver, TInt aMaxNumRetries, TInt aBaseInterval) [private]
Definition at line 29 of file ut_retry_epoc.cpp.
Referenced by NewL().
Member Function Documentation
void CRetryAo::ConstructL () [private]
Definition at line 41 of file ut_retry_epoc.cpp.
References LEAVE_IF_ERROR_OR_SET_SESSION_OPEN.
Referenced by NewL().
CRetryAo::DEF_SESSION (RTimer , iTimer) [protected]
void CRetryAo::DoCancel () [private, virtual]
Definition at line 71 of file ut_retry_epoc.cpp.
CRetryAo * CRetryAo::NewL (MRetryAoObserver & aObserver, TInt aMaxNumRetries, TInt aBaseInterval) [static]
Definition at line 17 of file ut_retry_epoc.cpp.
References ConstructL(), and CRetryAo().
void CRetryAo::ResetFailures ()
Definition at line 83 of file ut_retry_epoc.cpp.
References iNumScanFailures.
Referenced by CObserverAo_NetworkInfo::Cancel(), CObserverAo_SignalStrength::Cancel(), CSensor_callstatus::ChangedData_CallStatus(), CObserverAo_NetworkInfo::HandleData(), CObserverAo_SignalStrength::HandleData(), CSensor_cellpos::PositionerEventL(), CSensor_cellpos::PosModChangeL(), CSensor_cellpos::StartL(), and CSensor_callstatus::StartL().
TBool CRetryAo::Retry ()
Definition at line 52 of file ut_retry_epoc.cpp.
References iMaxNumRetries, iNumScanFailures, and WaitInterval().
Referenced by CSensor_callstatus::ChangedData_CallStatus(), CObserverAo_NetworkInfo::HandleData(), and CObserverAo_SignalStrength::HandleData().
void CRetryAo::RunL () [private, virtual]
Definition at line 66 of file ut_retry_epoc.cpp.
References iObserver, and MRetryAoObserver::RetryTimerExpired().
TTimeIntervalMicroSeconds32 CRetryAo::WaitInterval () [protected, virtual]
Definition at line 76 of file ut_retry_epoc.cpp.
References iBaseInterval, iNumScanFailures, and SecsToUsecs().
Referenced by Retry().
Member Data Documentation
TInt CRetryAo::iBaseInterval [protected]
Definition at line 58 of file ut_retry_epoc.hpp.
Referenced by WaitInterval().
TInt CRetryAo::iMaxNumRetries [protected]
Definition at line 57 of file ut_retry_epoc.hpp.
Referenced by Retry().
TInt CRetryAo::iNumScanFailures [protected]
Definition at line 62 of file ut_retry_epoc.hpp.
Referenced by ResetFailures(), Retry(), and WaitInterval().
MRetryAoObserver& CRetryAo::iObserver [protected]
Definition at line 56 of file ut_retry_epoc.hpp.
Referenced by RunL().
The documentation for this class was generated from the following files:
ut_retry_epoc.hpp
ut_retry_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1