ContextLogger2 Logger Daemon Internals: e_auto_ptr< HBufC8 > Class Template Reference
e_auto_ptr< HBufC8 > Class Template Reference
#include <symbian_auto_ptr.hpp>
Public Member Functions
e_auto_ptr (HBufC8 *aPtr=0)
e_auto_ptr (e_auto_ptr &aPtr)
e_auto_ptr< HBufC8 > & operator= (e_auto_ptr< HBufC8 > &aRhs)
~e_auto_ptr ()
const TDesC8 & operator* () const
HBufC8 * operator-> () const
HBufC8 * get () const
HBufC8 * release ()
void reset (HBufC8 *aPtr=0)
e_auto_ptr (e_auto_ptr_ref< HBufC8 > aRef)
template<class Y >
operator e_auto_ptr_ref< Y > ()
Private Attributes
HBufC8 * iPtr
Detailed Description
template<>
class e_auto_ptr< HBufC8 >
Definition at line 205 of file symbian_auto_ptr.hpp.
Constructor & Destructor Documentation
e_auto_ptr< HBufC8 >::e_auto_ptr (HBufC8 * aPtr = 0) [inline]
Definition at line 209 of file symbian_auto_ptr.hpp.
References CloseHBufC8Indirect().
e_auto_ptr< HBufC8 >::e_auto_ptr (e_auto_ptr< HBufC8 > & aPtr) [inline]
Definition at line 216 of file symbian_auto_ptr.hpp.
References CloseHBufC8Indirect().
e_auto_ptr< HBufC8 >::~e_auto_ptr () [inline]
Definition at line 233 of file symbian_auto_ptr.hpp.
e_auto_ptr< HBufC8 >::e_auto_ptr (e_auto_ptr_ref< HBufC8 > aRef) [inline]
Definition at line 261 of file symbian_auto_ptr.hpp.
References CloseHBufC8Indirect().
Member Function Documentation
HBufC8* e_auto_ptr< HBufC8 >::get () const [inline]
Definition at line 244 of file symbian_auto_ptr.hpp.
template<class Y > e_auto_ptr< HBufC8 >::operator e_auto_ptr_ref< Y > () [inline]
Definition at line 269 of file symbian_auto_ptr.hpp.
References e_auto_ptr< X >::release().
const TDesC8& e_auto_ptr< HBufC8 >::operator* () const [inline]
Definition at line 241 of file symbian_auto_ptr.hpp.
HBufC8* e_auto_ptr< HBufC8 >::operator-> () const [inline]
Definition at line 242 of file symbian_auto_ptr.hpp.
e_auto_ptr<HBufC8>& e_auto_ptr< HBufC8 >::operator= (e_auto_ptr< HBufC8 > & aRhs) [inline]
Definition at line 223 of file symbian_auto_ptr.hpp.
References release().
HBufC8* e_auto_ptr< HBufC8 >::release () [inline]
Definition at line 246 of file symbian_auto_ptr.hpp.
Referenced by operator=().
void e_auto_ptr< HBufC8 >::reset (HBufC8 * aPtr = 0) [inline]
Definition at line 253 of file symbian_auto_ptr.hpp.
Member Data Documentation
HBufC8* e_auto_ptr< HBufC8 >::iPtr [private]
Definition at line 273 of file symbian_auto_ptr.hpp.
The documentation for this class was generated from the following file:
symbian_auto_ptr.hpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1