ContextLogger2 Logger Daemon Internals: CCl2appAppUi Class Reference
CCl2appAppUi Class Reference
#include <cl2appappui.h>
Public Member Functions
void ConstructL ()
~CCl2appAppUi ()
void DestroyLogger ()
void Exit ()
Private Member Functions
void Start ()
void Stop ()
void DynInitMenuPaneL (TInt aResourceId, CEikMenuPane *aMenuPane)
void HandleCommandL (TInt aCommand)
virtual TKeyResponse HandleKeyEventL (const TKeyEvent &aKeyEvent, TEventCode aType)
void AppContextReady (TInt aError)
Private Attributes
CCl2appContainer * iAppContainer
kr_Controller * iClient
Detailed Description
Definition at line 19 of file cl2appappui.h.
Constructor & Destructor Documentation
CCl2appAppUi::~CCl2appAppUi ()
Definition at line 136 of file cl2appappui.cpp.
References cl2GlobalCleanup(), DestroyLogger(), iAppContainer, and logt.
Member Function Documentation
void CCl2appAppUi::AppContextReady (TInt aError) [private]
Definition at line 110 of file cl2appappui.cpp.
References er_FATAL, er_FREE, er_log_gerror, er_log_symbian, iClient, kr_Controller_new(), logg, logt, and Start().
void CCl2appAppUi::ConstructL ()
Definition at line 71 of file cl2appappui.cpp.
References _LIT(), ac_get_global_AppContext(), cl2GlobalInit(), COMPONENT_NAME_LIT, CCl2appContainer::ConstructL(), DisplayText(), iAppContainer, KEnableSkinFlag, KLayoutAwareFlag, and logt.
void CCl2appAppUi::DestroyLogger ()
Definition at line 54 of file cl2appappui.cpp.
References iClient, kr_Controller_destroy(), and logt.
Referenced by ~CCl2appAppUi().
void CCl2appAppUi::DynInitMenuPaneL (TInt aResourceId, CEikMenuPane * aMenuPane) [private]
Definition at line 151 of file cl2appappui.cpp.
void CCl2appAppUi::Exit () [inline]
Definition at line 30 of file cl2appappui.h.
Referenced by HandleCommandL().
void CCl2appAppUi::HandleCommandL (TInt aCommand) [private]
Definition at line 189 of file cl2appappui.cpp.
References ECl2appCmdAnotherMenuCommand, ECl2appCmdOneMenuCommand, and Exit().
TKeyResponse CCl2appAppUi::HandleKeyEventL (const TKeyEvent & aKeyEvent, TEventCode aType) [private, virtual]
Definition at line 157 of file cl2appappui.cpp.
void CCl2appAppUi::Start () [private]
Definition at line 162 of file cl2appappui.cpp.
References _LIT(), DisplayText(), gx_txtlog_error_free(), iClient, and kr_Controller_start().
Referenced by AppContextReady().
void CCl2appAppUi::Stop () [private]
Definition at line 179 of file cl2appappui.cpp.
References iClient, and kr_Controller_stop().
Member Data Documentation
CCl2appContainer* CCl2appAppUi::iAppContainer [private]
Definition at line 48 of file cl2appappui.h.
Referenced by ConstructL(), and ~CCl2appAppUi().
kr_Controller* CCl2appAppUi::iClient [private]
Definition at line 49 of file cl2appappui.h.
Referenced by AppContextReady(), DestroyLogger(), Start(), and Stop().
The documentation for this class was generated from the following files:
cl2appappui.h
cl2appappui.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1