ContextLogger2 Logger Daemon Internals: QsKineticScroller Class Reference
QsKineticScroller Class Reference
#include <QsKineticScroller.hpp>
Public Member Functions
QsKineticScroller (QObject *parent=0)
~QsKineticScroller ()
void enableKineticScrollFor (QAbstractScrollArea *scrollArea)
enabled for one widget only, new calls remove previous association
Protected Member Functions
bool eventFilter (QObject *object, QEvent *event)
intercepts mouse events to make the scrolling work
Private Slots
void onKineticTimerElapsed ()
Private Attributes
QScopedPointer
< QsKineticScrollerImpl > d
Detailed Description
Vertical kinetic scroller implementation without overshoot and bouncing. A temporary solution to get kinetic-like scrolling on Symbian.
Definition at line 37 of file QsKineticScroller.hpp.
Constructor & Destructor Documentation
QsKineticScroller::QsKineticScroller (QObject * parent = 0)
Definition at line 82 of file QsKineticScroller.cpp.
References d, and onKineticTimerElapsed().
QsKineticScroller::~QsKineticScroller ()
Definition at line 90 of file QsKineticScroller.cpp.
Member Function Documentation
void QsKineticScroller::enableKineticScrollFor (QAbstractScrollArea * scrollArea)
enabled for one widget only, new calls remove previous association
Definition at line 94 of file QsKineticScroller.cpp.
References d.
Referenced by MainWindow::MainWindow().
bool QsKineticScroller::eventFilter (QObject * object, QEvent * event) [protected]
intercepts mouse events to make the scrolling work
Definition at line 117 of file QsKineticScroller.cpp.
References d, gMaxIgnoredMouseMoves, and gTimerInterval.
void QsKineticScroller::onKineticTimerElapsed () [private, slot]
Definition at line 192 of file QsKineticScroller.cpp.
References d, gFriction, and gMaxDecelerationSpeed.
Referenced by QsKineticScroller().
Member Data Documentation
QScopedPointer<QsKineticScrollerImpl> QsKineticScroller::d [private]
Definition at line 53 of file QsKineticScroller.hpp.
Referenced by enableKineticScrollFor(), eventFilter(), onKineticTimerElapsed(), and QsKineticScroller().
The documentation for this class was generated from the following files:
QsKineticScroller.hpp
QsKineticScroller.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1