ContextLogger2 Logger Daemon Internals: CGetterAo_SignalStrength Class Reference
CGetterAo_SignalStrength Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CGetterAo_SignalStrength (CTelephony &aTelephony, MGetterObs_SignalStrength &aInterface)
virtual ~CGetterAo_SignalStrength ()
void MakeRequest ()
CTelephony::TSignalStrengthV1
const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TSignalStrengthV1 iData
CTelephony::TSignalStrengthV1Pckg iDataDes
CTelephony & iTelephony
MGetterObs_SignalStrength & iInterface
Detailed Description
Definition at line 242 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CGetterAo_SignalStrength::CGetterAo_SignalStrength (CTelephony & aTelephony, MGetterObs_SignalStrength & aInterface)
Definition at line 151 of file ut_telephony_epoc.cpp.
CGetterAo_SignalStrength::~CGetterAo_SignalStrength () [virtual]
Definition at line 156 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TSignalStrengthV1 const & CGetterAo_SignalStrength::Data () const [inline]
Definition at line 735 of file ut_telephony_epoc.h.
References iData.
Referenced by CObserverAo_SignalStrength::GotData_SignalStrength().
void CGetterAo_SignalStrength::DoCancel () [private, virtual]
Definition at line 174 of file ut_telephony_epoc.cpp.
References iTelephony.
void CGetterAo_SignalStrength::MakeRequest ()
Definition at line 161 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CObserverAo_SignalStrength::ConstructL(), and CObserverAo_SignalStrength::MakeRequest().
void CGetterAo_SignalStrength::RunL () [private, virtual]
Definition at line 169 of file ut_telephony_epoc.cpp.
References MGetterObs_SignalStrength::GotData_SignalStrength(), and iInterface.
Member Data Documentation
CTelephony::TSignalStrengthV1 CGetterAo_SignalStrength::iData [private]
Definition at line 265 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TSignalStrengthV1Pckg CGetterAo_SignalStrength::iDataDes [private]
Definition at line 267 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MGetterObs_SignalStrength& CGetterAo_SignalStrength::iInterface [private]
Definition at line 271 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CGetterAo_SignalStrength::iTelephony [private]
Definition at line 269 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1