ContextLogger2 Logger Daemon Internals: CSensor_indicator Class Reference
CSensor_indicator Class Reference
#include <epoc-indicator.hpp>
Public Member Functions
virtual ~CSensor_indicator ()
gboolean StartL (GError **error)
void Stop ()
Private Types
enum TState { EInactive = 0, EQuerying, ERetryWaiting }
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
void MakeRequest ()
void SetTimer ()
void HandleTimer ()
void HandleRead ()
DEF_SESSION (RTimer, iTimer)
Private Attributes
CTOR_DECL_CSensor_indicator
ac_AppContext * iAppContext
CTelephony::TIndicatorV1 iOldIndicator
CTelephony::TIndicatorV1 iIndicator
CTelephony::TIndicatorV1Pckg iIndicatorDes
TInt iNumScanFailures
TState iState
Detailed Description
Definition at line 52 of file epoc-indicator.hpp.
Member Enumeration Documentation
enum CSensor_indicator::TState [private]
Enumerator:
EInactive
EQuerying
ERetryWaiting
Definition at line 99 of file epoc-indicator.hpp.
Constructor & Destructor Documentation
CSensor_indicator::~CSensor_indicator () [virtual]
Definition at line 29 of file epoc-indicator.cpp.
References SESSION_CLOSE_IF_OPEN.
Member Function Documentation
CSensor_indicator::DEF_SESSION (RTimer , iTimer) [private]
void CSensor_indicator::DoCancel () [private, virtual]
Definition at line 180 of file epoc-indicator.cpp.
References EInactive, EQuerying, ERetryWaiting, iState, and iTelephony.
void CSensor_indicator::HandleRead () [private]
Definition at line 102 of file epoc-indicator.cpp.
References ac_LogDb(), dblogg, guilogf(), gx_txtlog_fatal_error_free(), iAppContext, iIndicator, IND2CH, INDICATOR_EQ, iNumScanFailures, iOldIndicator, log_db_log_indicator(), log_db_log_status(), logg, MakeRequest(), plat_error_strerror, and SetTimer().
Referenced by RunL().
void CSensor_indicator::HandleTimer () [private]
Definition at line 75 of file epoc-indicator.cpp.
References er_FATAL, er_log_symbian, and MakeRequest().
Referenced by RunL().
void CSensor_indicator::MakeRequest () [private]
Definition at line 56 of file epoc-indicator.cpp.
References EQuerying, iIndicatorDes, iState, and iTelephony.
Referenced by HandleRead(), HandleTimer(), and StartL().
void CSensor_indicator::RunL () [private, virtual]
Definition at line 153 of file epoc-indicator.cpp.
References EInactive, EQuerying, ERetryWaiting, HandleRead(), HandleTimer(), and iState.
void CSensor_indicator::SetTimer () [private]
Definition at line 64 of file epoc-indicator.cpp.
References ERetryWaiting, iNumScanFailures, iState, logg, and SecsToUsecs().
Referenced by HandleRead().
gboolean CSensor_indicator::StartL (GError ** error)
Definition at line 38 of file epoc-indicator.cpp.
References iNumScanFailures, and MakeRequest().
void CSensor_indicator::Stop ()
Definition at line 48 of file epoc-indicator.cpp.
Member Data Documentation
CSensor_indicator::CTOR_DECL_CSensor_indicator [private]
Definition at line 55 of file epoc-indicator.hpp.
ac_AppContext* CSensor_indicator::iAppContext [private]
Definition at line 86 of file epoc-indicator.hpp.
Referenced by HandleRead().
CTelephony::TIndicatorV1 CSensor_indicator::iIndicator [private]
Definition at line 90 of file epoc-indicator.hpp.
Referenced by HandleRead().
CTelephony::TIndicatorV1Pckg CSensor_indicator::iIndicatorDes [private]
Definition at line 92 of file epoc-indicator.hpp.
Referenced by MakeRequest().
TInt CSensor_indicator::iNumScanFailures [private]
Definition at line 97 of file epoc-indicator.hpp.
Referenced by HandleRead(), SetTimer(), and StartL().
CTelephony::TIndicatorV1 CSensor_indicator::iOldIndicator [private]
Definition at line 88 of file epoc-indicator.hpp.
Referenced by HandleRead().
TState CSensor_indicator::iState [private]
Definition at line 104 of file epoc-indicator.hpp.
Referenced by DoCancel(), MakeRequest(), RunL(), and SetTimer().
The documentation for this class was generated from the following files:
epoc-indicator.hpp
epoc-indicator.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1