ContextLogger2 Logger Daemon Internals: CGetterAo_FlightMode Class Reference
CGetterAo_FlightMode Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CGetterAo_FlightMode (CTelephony &aTelephony, MGetterObs_FlightMode &aInterface)
virtual ~CGetterAo_FlightMode ()
void MakeRequest ()
CTelephony::TFlightModeV1 const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TFlightModeV1 iData
CTelephony::TFlightModeV1Pckg iDataDes
CTelephony & iTelephony
MGetterObs_FlightMode & iInterface
Detailed Description
Definition at line 27 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CGetterAo_FlightMode::CGetterAo_FlightMode (CTelephony & aTelephony, MGetterObs_FlightMode & aInterface)
Definition at line 11 of file ut_telephony_epoc.cpp.
CGetterAo_FlightMode::~CGetterAo_FlightMode () [virtual]
Definition at line 16 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TFlightModeV1 const & CGetterAo_FlightMode::Data () const [inline]
Definition at line 710 of file ut_telephony_epoc.h.
References iData.
Referenced by CSensor_callstatus::GotData_FlightMode(), and CFlightModeObserver::GotData_FlightMode().
void CGetterAo_FlightMode::DoCancel () [private, virtual]
Definition at line 34 of file ut_telephony_epoc.cpp.
References iTelephony.
void CGetterAo_FlightMode::MakeRequest ()
Definition at line 21 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CSensor_callstatus::StartL().
void CGetterAo_FlightMode::RunL () [private, virtual]
Definition at line 29 of file ut_telephony_epoc.cpp.
References MGetterObs_FlightMode::GotData_FlightMode(), and iInterface.
Member Data Documentation
CTelephony::TFlightModeV1 CGetterAo_FlightMode::iData [private]
Definition at line 50 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TFlightModeV1Pckg CGetterAo_FlightMode::iDataDes [private]
Definition at line 52 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MGetterObs_FlightMode& CGetterAo_FlightMode::iInterface [private]
Definition at line 56 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CGetterAo_FlightMode::iTelephony [private]
Definition at line 54 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1