ContextLogger2 Logger Daemon Internals: CUploader Class Reference
CUploader Class Reference
#include <up_uploader_qt_private.hpp>
Public Member Functions
~CUploader ()
void RefreshIap (TBool aNotInitial)
void RefreshSnapshotTimeExpr (TBool aNotInitial)
void RequestSnapshot ()
void Set_uploads_allowed (TBool val)
CUploader (ac_AppContext *aAppContext)
~CUploader ()
void RefreshIap (bool aNotInitial)
void RefreshSnapshotTimeExpr (bool aNotInitial)
void RequestSnapshot ()
void Set_uploads_allowed (bool val)
Private Slots
void handlePosterTimerEvent ()
void handleSnapshotTimerEvent ()
void postingSslErrors (const QList< QSslError > &errors)
void postingFinished ()
Private Member Functions
void HandleTimerEvent (CTimerAo *aTimerAo, TInt errCode)
void PosterEvent (TInt anError)
void HandleImmediateEvent ()
void BbRegisterL ()
void BbUnregister ()
void Inactivate ()
void InactivateLater ()
void StateChanged ()
void StateChangedL ()
void StateChangedLater ()
void NextOldFileL ()
TInt CreatePosterAo ()
void DestroyPosterAo ()
TBool PosterAoIsActive ()
void HandleCommsError (TInt errCode)
void PostNowL ()
void SetPostRetryTimer ()
void SetSnapshotTimerL ()
void TakeSnapshotNowL ()
void FatalError (TInt anError)
void PosterEvent (int anError)
void Inactivate ()
void StateChanged ()
void StateChangedL ()
void NextOldFileL ()
void CreatePosterAoL ()
void DestroyPosterAo ()
bool PosterAoIsActive ()
void HandleCommsError (int errCode)
void PostNowL ()
void SetPostTimer ()
void SetSnapshotTimerL ()
void TakeSnapshotNowL ()
void FatalError (const std::exception &ex)
LogDb * GetLogDb () const
QUrl GetUrl () const
void BbRegisterL ()
void BbUnregister ()
Private Attributes
CTOR_DECL_CUploader
LogDb * iLogDb
TBool iNotReady
TPtrC8 iUploadUrl
TUint32 iIapId
CPosterAo * iPosterAo
CTimerAo * iPostTimerAo
gchar * iFileToPost
TBool iNoOldFiles
TInt iNumPostFailures
CImmediateAo * iImmediateAo
CTimerAo * iSnapshotTimerAo
TBool iSnapshotTimePassed
gchar * iSnapshotTimeExpr
time_t iSnapshotTimeCtx
TBool iNoNextSnapshotTime
TBool i_uploads_allowed
bb_Closure iClosure
ac_AppContext * iAppContext
bool iNoConfig
QNetworkAccessManager iNetworkAccessManager
QSslConfiguration iSslConfiguration
QNetworkRequest iNetworkRequest
QTimer iPostTimerAo
bool iNoOldFiles
int iNumPostFailures
PostSession * iPostSession
QFile * iFileToPost
QAbsTimer iSnapshotTimerAo
bool iSnapshotTimePassed
bool iNoNextSnapshotTime
bool i_uploads_allowed
Detailed Description
Definition at line 92 of file up_uploader_epoc.cpp.
Constructor & Destructor Documentation
CUploader::~CUploader ()
Definition at line 293 of file up_uploader_epoc.cpp.
References iFileToPost, iImmediateAo, Inactivate(), iPostTimerAo, iSnapshotTimeExpr, and iSnapshotTimerAo.
CUploader::CUploader (ac_AppContext * aAppContext)
Definition at line 142 of file up_uploader_qt.cpp.
References ac_STATIC_GET, BbRegisterL(), er_FATAL, er_FREE, er_log_gerror, handlePosterTimerEvent(), handleSnapshotTimerEvent(), iIapId, iNetworkRequest, iNoConfig, iPostTimerAo, iSnapshotTimeCtx, iSnapshotTimerAo, iSslConfiguration, LOG_UPLOADS_DIR, logg, logt, mkdir_p(), qxDebug, RefreshIap(), RefreshSnapshotTimeExpr(), StateChangedL(), and TimeNow().
CUploader::~CUploader ()
Member Function Documentation
void CUploader::BbRegisterL () [private]
void CUploader::BbRegisterL () [private]
Definition at line 187 of file up_uploader_epoc.cpp.
References ac_global_Blackboard, bb_Closure::arg, bb_Blackboard_board(), bb_Blackboard_register(), bb_dt_uploads_allowed, bb_Closure::changed, DataChanged(), i_uploads_allowed, iClosure, and bb_Board::uploads_allowed.
Referenced by CUploader().
void CUploader::BbUnregister () [private]
void CUploader::BbUnregister () [private]
Definition at line 205 of file up_uploader_epoc.cpp.
References ac_global_Blackboard, bb_Blackboard_unregister(), and iClosure.
Referenced by Inactivate().
TInt CUploader::CreatePosterAo () [private]
Definition at line 623 of file up_uploader_epoc.cpp.
References iIapId, iPosterAo, and logg.
Referenced by PostNowL().
void CUploader::CreatePosterAoL () [private]
Definition at line 556 of file up_uploader_qt.cpp.
References CHECKBUFOPEN, dblogg, domain_qt, get_config_username(), gx_error_new(), gx_throw, PostSession::iEpilogue, PostSession::iFileToPost, iFileToPost, iNetworkAccessManager, PostSession::iNetworkReply, iNetworkRequest, PostSession::iPostData, PostSession::iPostElems, iPostSession, PostSession::iPrologue, logg, postingFinished(), and postingSslErrors().
void CUploader::DestroyPosterAo () [private]
void CUploader::DestroyPosterAo () [private]
Definition at line 635 of file up_uploader_epoc.cpp.
References iPosterAo, and logt.
Referenced by Inactivate(), and StateChangedL().
void CUploader::FatalError (const std::exception & ex) [private]
Definition at line 256 of file up_uploader_qt.cpp.
References er_FATAL, er_log_none, and Inactivate().
void CUploader::FatalError (TInt anError) [private]
Definition at line 330 of file up_uploader_epoc.cpp.
References er_FATAL, and er_log_symbian.
Referenced by HandleCommsError(), HandleTimerEvent(), PosterEvent(), postingFinished(), and StateChanged().
LogDb* CUploader::GetLogDb () const [inline, private]
Definition at line 113 of file up_uploader_qt_private.hpp.
References ac_LogDb(), and iAppContext.
Referenced by postingFinished(), RefreshIap(), and RefreshSnapshotTimeExpr().
QUrl CUploader::GetUrl () const [inline, private]
Definition at line 114 of file up_uploader_qt_private.hpp.
References iNetworkRequest.
void CUploader::HandleCommsError (int errCode) [private]
void CUploader::HandleCommsError (TInt errCode) [private]
Definition at line 536 of file up_uploader_epoc.cpp.
References dblogg, FatalError(), InactivateLater(), iNumPostFailures, SetPostRetryTimer(), and StateChangedLater().
Referenced by PosterEvent(), and PostNowL().
void CUploader::HandleImmediateEvent () [private, virtual]
Implements MImmediateObserver.
Definition at line 468 of file up_uploader_epoc.cpp.
References logh, and StateChanged().
void CUploader::handlePosterTimerEvent () [private, slot]
Definition at line 377 of file up_uploader_qt.cpp.
References logt, and StateChanged().
Referenced by CUploader().
void CUploader::handleSnapshotTimerEvent () [private, slot]
Definition at line 384 of file up_uploader_qt.cpp.
References iSnapshotTimePassed, logt, and StateChanged().
Referenced by CUploader().
void CUploader::HandleTimerEvent (CTimerAo * aTimerAo, TInt errCode) [private, virtual]
Implements MTimerObserver.
Definition at line 427 of file up_uploader_epoc.cpp.
References FatalError(), iNoNextSnapshotTime, iPostTimerAo, iSnapshotTimePassed, iSnapshotTimerAo, logg, logt, and StateChanged().
void CUploader::Inactivate () [private]
void CUploader::Inactivate () [private]
Definition at line 310 of file up_uploader_epoc.cpp.
References BbUnregister(), DestroyPosterAo(), iImmediateAo, iNotReady, iPostTimerAo, iSnapshotTimerAo, and logh.
Referenced by FatalError(), postingFinished(), StateChangedL(), and ~CUploader().
void CUploader::InactivateLater () [private]
Definition at line 321 of file up_uploader_epoc.cpp.
References iNotReady, iPostTimerAo, iSnapshotTimerAo, logh, and StateChangedLater().
Referenced by HandleCommsError(), and PosterEvent().
void CUploader::NextOldFileL () [private]
void CUploader::NextOldFileL () [private]
Definition at line 342 of file up_uploader_epoc.cpp.
References dblogt, er_FATAL, er_FREE, er_log_gerror, error(), getNextOldLogFile(), iFileToPost, and iNoOldFiles.
Referenced by StateChangedL().
bool CUploader::PosterAoIsActive () [private]
bool CUploader::PosterAoIsActive () [inline, private]
Definition at line 158 of file up_uploader_epoc.cpp.
References CPosterAo::IsActive().
Referenced by StateChangedL().
void CUploader::PosterEvent (int anError) [private]
void CUploader::PosterEvent (TInt anError) [private, virtual]
Implements MPosterObserver.
Definition at line 475 of file up_uploader_epoc.cpp.
References ac_global_Registry, dblogg, er_FATAL, er_log_errno, er_log_none, FatalError(), gx_txtlog_error_free(), HandleCommsError(), iFileToPost, iLogDb, InactivateLater(), iNumPostFailures, log_db_log_status(), POSTER_PERMANENT_FAILURE, POSTER_SUCCESS, POSTER_TRANSIENT_FAILURE, rm_file(), SetPostRetryTimer(), and StateChangedLater().
void CUploader::postingFinished () [private, slot]
Definition at line 437 of file up_uploader_qt.cpp.
References ac_global_Registry, dblogg, er_log_none, FatalError(), GetLogDb(), PostSession::iFileToPost, iFileToPost, Inactivate(), PostSession::iNetworkReply, iNumPostFailures, iPostSession, log_db_log_status(), logg, logt, rm_file(), SetPostTimer(), StateChanged(), and TimeNow().
Referenced by CreatePosterAoL().
void CUploader::postingSslErrors (const QList< QSslError > & errors) [private, slot]
Definition at line 398 of file up_uploader_qt.cpp.
References PostSession::iNetworkReply, iPostSession, iSslConfiguration, logt, and qxDebug.
Referenced by CreatePosterAoL().
void CUploader::PostNowL () [private]
void CUploader::PostNowL () [private]
Definition at line 644 of file up_uploader_epoc.cpp.
References CreatePosterAo(), dblogg, HandleCommsError(), iFileToPost, iPosterAo, iUploadUrl, logg, logt, and CPosterAo::PostFileL().
Referenced by StateChangedL().
void CUploader::RefreshIap (bool aNotInitial)
Definition at line 95 of file up_uploader_qt.cpp.
References get_config_iap_id(), GetLogDb(), iIapId, and log_db_log_status().
void CUploader::RefreshIap (TBool aNotInitial)
Definition at line 215 of file up_uploader_epoc.cpp.
References get_config_iap_id(), iIapId, iLogDb, and log_db_log_status().
Referenced by CUploader().
void CUploader::RefreshSnapshotTimeExpr (bool aNotInitial)
Definition at line 105 of file up_uploader_qt.cpp.
References __UPLOAD_TIME_EXPR__, get_ConfigDb_str(), GetLogDb(), gx_dblog_error_free_check(), gx_error_free(), iNoNextSnapshotTime, iSnapshotTimeExpr, iSnapshotTimerAo, log_db_log_status(), logt, and StateChanged().
void CUploader::RefreshSnapshotTimeExpr (TBool aNotInitial)
Definition at line 223 of file up_uploader_epoc.cpp.
References __UPLOAD_TIME_EXPR__, get_ConfigDb_str(), gx_dblog_error_free_check(), gx_error_free(), iLogDb, iNoNextSnapshotTime, iSnapshotTimeExpr, iSnapshotTimerAo, log_db_log_status(), logt, and StateChanged().
Referenced by CUploader().
void CUploader::RequestSnapshot ()
void CUploader::RequestSnapshot ()
Definition at line 363 of file up_uploader_epoc.cpp.
References iSnapshotTimePassed, iSnapshotTimerAo, and StateChanged().
void CUploader::Set_uploads_allowed (bool val)
Definition at line 61 of file up_uploader_qt.cpp.
References i_uploads_allowed, and StateChanged().
void CUploader::Set_uploads_allowed (TBool val)
Definition at line 181 of file up_uploader_epoc.cpp.
References i_uploads_allowed, and StateChanged().
void CUploader::SetPostRetryTimer () [private]
Definition at line 409 of file up_uploader_epoc.cpp.
References dblogg, iNumPostFailures, iPostTimerAo, and SecsToUsecs().
Referenced by HandleCommsError(), and PosterEvent().
void CUploader::SetPostTimer () [private]
Definition at line 361 of file up_uploader_qt.cpp.
References dblogg, iNumPostFailures, iPostTimerAo, and SecsToMsecs().
Referenced by postingFinished().
void CUploader::SetSnapshotTimerL () [private]
void CUploader::SetSnapshotTimerL () [private]
Definition at line 372 of file up_uploader_epoc.cpp.
References dblogt, gx_txtlog_error_free(), iNoNextSnapshotTime, iSnapshotTimeCtx, iSnapshotTimeExpr, iSnapshotTimePassed, iSnapshotTimerAo, log_time, logt, parse_moment(), UnixTimeToLocalEpocTime(), and UnixTimeToUtcEpocTime().
Referenced by StateChangedL().
void CUploader::StateChanged () [private]
void CUploader::StateChanged () [private]
Definition at line 335 of file up_uploader_epoc.cpp.
References FatalError(), and StateChangedL().
Referenced by HandleImmediateEvent(), handlePosterTimerEvent(), handleSnapshotTimerEvent(), HandleTimerEvent(), postingFinished(), RefreshSnapshotTimeExpr(), RequestSnapshot(), and Set_uploads_allowed().
void CUploader::StateChangedL () [private]
void CUploader::StateChangedL () [private]
Definition at line 589 of file up_uploader_epoc.cpp.
References DestroyPosterAo(), i_uploads_allowed, iFileToPost, Inactivate(), iNoNextSnapshotTime, iNoOldFiles, iNotReady, iPostTimerAo, iSnapshotTimePassed, iSnapshotTimerAo, NextOldFileL(), PosterAoIsActive(), PostNowL(), SetSnapshotTimerL(), and TakeSnapshotNowL().
Referenced by CUploader(), StateChanged(), and TakeSnapshotNowL().
void CUploader::StateChangedLater () [private]
Definition at line 303 of file up_uploader_epoc.cpp.
References CImmediateAo::Complete(), and iImmediateAo.
Referenced by HandleCommsError(), InactivateLater(), and PosterEvent().
void CUploader::TakeSnapshotNowL () [private]
void CUploader::TakeSnapshotNowL () [private]
Definition at line 672 of file up_uploader_epoc.cpp.
References dblogt, er_FATAL, er_FREE, er_log_errno, er_log_gerror, iFileToPost, iLogDb, iSnapshotTimePassed, log_db_log_status(), log_db_take_snapshot(), LOG_UPLOADS_DIR, logg, and StateChangedL().
Referenced by StateChangedL().
Member Data Documentation
CUploader::CTOR_DECL_CUploader [private]
Definition at line 98 of file up_uploader_epoc.cpp.
bool CUploader::i_uploads_allowed [private]
Definition at line 120 of file up_uploader_qt_private.hpp.
TBool CUploader::i_uploads_allowed [private]
Definition at line 144 of file up_uploader_epoc.cpp.
Referenced by BbRegisterL(), Set_uploads_allowed(), and StateChangedL().
ac_AppContext* CUploader::iAppContext [private]
Definition at line 82 of file up_uploader_qt_private.hpp.
Referenced by GetLogDb().
bb_Closure CUploader::iClosure [private]
Definition at line 145 of file up_uploader_epoc.cpp.
Referenced by BbRegisterL(), and BbUnregister().
QFile* CUploader::iFileToPost [private]
Definition at line 98 of file up_uploader_qt_private.hpp.
gchar* CUploader::iFileToPost [private]
Definition at line 128 of file up_uploader_epoc.cpp.
Referenced by CreatePosterAoL(), NextOldFileL(), PosterEvent(), postingFinished(), PostNowL(), StateChangedL(), TakeSnapshotNowL(), and ~CUploader().
TUint32 CUploader::iIapId [private]
Definition at line 123 of file up_uploader_epoc.cpp.
Referenced by CreatePosterAo(), CUploader(), and RefreshIap().
CImmediateAo* CUploader::iImmediateAo [private]
Definition at line 131 of file up_uploader_epoc.cpp.
Referenced by Inactivate(), StateChangedLater(), and ~CUploader().
LogDb* CUploader::iLogDb [private]
Definition at line 119 of file up_uploader_epoc.cpp.
Referenced by PosterEvent(), RefreshIap(), RefreshSnapshotTimeExpr(), and TakeSnapshotNowL().
QNetworkAccessManager CUploader::iNetworkAccessManager [private]
Definition at line 90 of file up_uploader_qt_private.hpp.
Referenced by CreatePosterAoL().
QNetworkRequest CUploader::iNetworkRequest [private]
Definition at line 92 of file up_uploader_qt_private.hpp.
Referenced by CreatePosterAoL(), CUploader(), and GetUrl().
bool CUploader::iNoConfig [private]
Definition at line 84 of file up_uploader_qt_private.hpp.
Referenced by CUploader().
bool CUploader::iNoNextSnapshotTime [private]
Definition at line 105 of file up_uploader_qt_private.hpp.
TBool CUploader::iNoNextSnapshotTime [private]
Definition at line 138 of file up_uploader_epoc.cpp.
Referenced by HandleTimerEvent(), RefreshSnapshotTimeExpr(), SetSnapshotTimerL(), and StateChangedL().
bool CUploader::iNoOldFiles [private]
Definition at line 94 of file up_uploader_qt_private.hpp.
TBool CUploader::iNoOldFiles [private]
Definition at line 129 of file up_uploader_epoc.cpp.
Referenced by NextOldFileL(), and StateChangedL().
TBool CUploader::iNotReady [private]
Definition at line 121 of file up_uploader_epoc.cpp.
Referenced by Inactivate(), InactivateLater(), and StateChangedL().
int CUploader::iNumPostFailures [private]
Definition at line 95 of file up_uploader_qt_private.hpp.
TInt CUploader::iNumPostFailures [private]
Definition at line 130 of file up_uploader_epoc.cpp.
Referenced by HandleCommsError(), PosterEvent(), postingFinished(), SetPostRetryTimer(), and SetPostTimer().
CPosterAo* CUploader::iPosterAo [private]
Definition at line 126 of file up_uploader_epoc.cpp.
Referenced by CreatePosterAo(), DestroyPosterAo(), and PostNowL().
PostSession* CUploader::iPostSession [private]
Definition at line 97 of file up_uploader_qt_private.hpp.
Referenced by CreatePosterAoL(), postingFinished(), and postingSslErrors().
QTimer CUploader::iPostTimerAo [private]
Definition at line 93 of file up_uploader_qt_private.hpp.
CTimerAo* CUploader::iPostTimerAo [private]
Definition at line 127 of file up_uploader_epoc.cpp.
Referenced by CUploader(), HandleTimerEvent(), Inactivate(), InactivateLater(), SetPostRetryTimer(), SetPostTimer(), StateChangedL(), and ~CUploader().
time_t CUploader::iSnapshotTimeCtx [private]
Definition at line 137 of file up_uploader_epoc.cpp.
Referenced by CUploader(), and SetSnapshotTimerL().
gchar * CUploader::iSnapshotTimeExpr [private]
Definition at line 136 of file up_uploader_epoc.cpp.
Referenced by RefreshSnapshotTimeExpr(), SetSnapshotTimerL(), and ~CUploader().
bool CUploader::iSnapshotTimePassed [private]
Definition at line 102 of file up_uploader_qt_private.hpp.
TBool CUploader::iSnapshotTimePassed [private]
Definition at line 135 of file up_uploader_epoc.cpp.
Referenced by handleSnapshotTimerEvent(), HandleTimerEvent(), RequestSnapshot(), SetSnapshotTimerL(), StateChangedL(), and TakeSnapshotNowL().
QAbsTimer CUploader::iSnapshotTimerAo [private]
Definition at line 101 of file up_uploader_qt_private.hpp.
CTimerAo* CUploader::iSnapshotTimerAo [private]
Definition at line 134 of file up_uploader_epoc.cpp.
Referenced by CUploader(), HandleTimerEvent(), Inactivate(), InactivateLater(), RefreshSnapshotTimeExpr(), RequestSnapshot(), SetSnapshotTimerL(), StateChangedL(), and ~CUploader().
QSslConfiguration CUploader::iSslConfiguration [private]
Definition at line 91 of file up_uploader_qt_private.hpp.
Referenced by CUploader(), and postingSslErrors().
TPtrC8 CUploader::iUploadUrl [private]
Definition at line 122 of file up_uploader_epoc.cpp.
Referenced by PostNowL().
The documentation for this class was generated from the following files:
up_uploader_epoc.cpp
up_uploader_qt_private.hpp
up_uploader_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1