ContextLogger2 Logger Daemon Internals: CGetterAo_NetworkRegistration Class Reference
CGetterAo_NetworkRegistration Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CGetterAo_NetworkRegistration (CTelephony &aTelephony, MGetterObs_NetworkRegistration &aInterface)
virtual ~CGetterAo_NetworkRegistration ()
void MakeRequest ()
CTelephony::TNetworkRegistrationV1
const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TNetworkRegistrationV1 iData
CTelephony::TNetworkRegistrationV1Pckg iDataDes
CTelephony & iTelephony
MGetterObs_NetworkRegistration & iInterface
Detailed Description
Definition at line 328 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CGetterAo_NetworkRegistration::CGetterAo_NetworkRegistration (CTelephony & aTelephony, MGetterObs_NetworkRegistration & aInterface)
Definition at line 207 of file ut_telephony_epoc.cpp.
CGetterAo_NetworkRegistration::~CGetterAo_NetworkRegistration () [virtual]
Definition at line 212 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TNetworkRegistrationV1 const & CGetterAo_NetworkRegistration::Data () const [inline]
Definition at line 745 of file ut_telephony_epoc.h.
References iData.
Referenced by CObserverAo_NetworkRegistration::GotData_NetworkRegistration().
void CGetterAo_NetworkRegistration::DoCancel () [private, virtual]
Definition at line 230 of file ut_telephony_epoc.cpp.
References iTelephony.
void CGetterAo_NetworkRegistration::MakeRequest ()
Definition at line 217 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CObserverAo_NetworkRegistration::ConstructL(), and CObserverAo_NetworkRegistration::MakeRequest().
void CGetterAo_NetworkRegistration::RunL () [private, virtual]
Definition at line 225 of file ut_telephony_epoc.cpp.
References MGetterObs_NetworkRegistration::GotData_NetworkRegistration(), and iInterface.
Member Data Documentation
CTelephony::TNetworkRegistrationV1 CGetterAo_NetworkRegistration::iData [private]
Definition at line 351 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TNetworkRegistrationV1Pckg CGetterAo_NetworkRegistration::iDataDes [private]
Definition at line 353 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MGetterObs_NetworkRegistration& CGetterAo_NetworkRegistration::iInterface [private]
Definition at line 357 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CGetterAo_NetworkRegistration::iTelephony [private]
Definition at line 355 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1