ContextLogger2 Logger Daemon Internals: CNotifyAo_NetworkInfo Class Reference
CNotifyAo_NetworkInfo Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CNotifyAo_NetworkInfo (CTelephony &aTelephony, MNotifyObs_NetworkInfo &aInterface)
virtual ~CNotifyAo_NetworkInfo ()
void MakeRequest ()
CTelephony::TNetworkInfoV1 const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TNetworkInfoV1 iData
CTelephony::TNetworkInfoV1Pckg iDataDes
CTelephony & iTelephony
MNotifyObs_NetworkInfo & iInterface
Detailed Description
Definition at line 457 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CNotifyAo_NetworkInfo::CNotifyAo_NetworkInfo (CTelephony & aTelephony, MNotifyObs_NetworkInfo & aInterface)
Definition at line 291 of file ut_telephony_epoc.cpp.
CNotifyAo_NetworkInfo::~CNotifyAo_NetworkInfo () [virtual]
Definition at line 296 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TNetworkInfoV1 const & CNotifyAo_NetworkInfo::Data () const [inline]
Definition at line 760 of file ut_telephony_epoc.h.
References iData.
Referenced by CObserverAo_NetworkInfo::ChangedData_NetworkInfo().
void CNotifyAo_NetworkInfo::DoCancel () [private, virtual]
Definition at line 314 of file ut_telephony_epoc.cpp.
References iTelephony.
void CNotifyAo_NetworkInfo::MakeRequest ()
Definition at line 301 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CObserverAo_NetworkInfo::HandleData(), and CObserverAo_NetworkInfo::MakeRequest().
void CNotifyAo_NetworkInfo::RunL () [private, virtual]
Definition at line 309 of file ut_telephony_epoc.cpp.
References MNotifyObs_NetworkInfo::ChangedData_NetworkInfo(), and iInterface.
Member Data Documentation
CTelephony::TNetworkInfoV1 CNotifyAo_NetworkInfo::iData [private]
Definition at line 480 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TNetworkInfoV1Pckg CNotifyAo_NetworkInfo::iDataDes [private]
Definition at line 482 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MNotifyObs_NetworkInfo& CNotifyAo_NetworkInfo::iInterface [private]
Definition at line 486 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CNotifyAo_NetworkInfo::iTelephony [private]
Definition at line 484 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1