ContextLogger2 Logger Daemon Internals: CSensor_keypress Class Reference
CSensor_keypress Class Reference
#include <epoc-keypress-anim.hpp>
Public Member Functions
virtual ~CSensor_keypress ()
gboolean StartL (GError **error)
void Stop ()
Static Public Member Functions
static CSensor_keypress * NewL (LogDb *aLogDb)
Private Member Functions
CSensor_keypress (LogDb *aLogDb)
void ConstructL ()
void MakeRequest ()
virtual void RunL ()
virtual void DoCancel ()
gboolean LogAndClear (GError **error)
DEF_SESSION (RProperty, iProperty)
Private Attributes
LogDb * iLogDb
RWsSession * iSession
RWindowGroup * iWinGroup
CApaWindowGroupName * iWinGroupName
CKeyEventsClient * iKeyEventsClient
TInt32 iCaptureHandles [350]
int iNumCaptureHandles
time_t iCapturedKeys [MAX_NUM_CAPTURED_KEYS]
int iNumCapturedKeys
GString * iKeysText
Detailed Description
Definition at line 29 of file epoc-keypress-anim.hpp.
Constructor & Destructor Documentation
CSensor_keypress::~CSensor_keypress () [virtual]
Definition at line 69 of file epoc-keypress-anim.cpp.
References iKeyEventsClient, iKeysText, iSession, iWinGroup, iWinGroupName, LogAndClear(), and SESSION_CLOSE_IF_OPEN.
CSensor_keypress::CSensor_keypress (LogDb * aLogDb) [private]
Definition at line 29 of file epoc-keypress-anim.cpp.
References iLogDb.
Referenced by NewL().
Member Function Documentation
void CSensor_keypress::ConstructL () [private]
Definition at line 36 of file epoc-keypress-anim.cpp.
References iKeyEventsClient, iKeysText, iSession, iWinGroup, iWinGroupName, KPropertyCategory, KPropertyKey, MAX_NUM_CAPTURED_KEYS, NewL(), SET_SESSION_OPEN, SET_TRAP_OOM, and UNSET_TRAP_OOM.
CSensor_keypress::DEF_SESSION (RProperty , iProperty) [private]
void CSensor_keypress::DoCancel () [private, virtual]
Definition at line 115 of file epoc-keypress-anim.cpp.
References IS_SESSION_OPEN.
gboolean CSensor_keypress::LogAndClear (GError ** error) [private]
Definition at line 163 of file epoc-keypress-anim.cpp.
References gx_error_no_memory, iCapturedKeys, iKeysText, iLogDb, iNumCapturedKeys, log_db_log_keypress(), SET_TRAP_OOM, and UNSET_TRAP_OOM.
Referenced by RunL(), Stop(), and ~CSensor_keypress().
void CSensor_keypress::MakeRequest () [private]
Definition at line 109 of file epoc-keypress-anim.cpp.
Referenced by RunL(), and StartL().
CSensor_keypress * CSensor_keypress::NewL (LogDb * aLogDb) [static]
==================================================================== capturer.cpp Copyright (c) 2006 Nokia Corporation
Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License. ====================================================================
Definition at line 20 of file epoc-keypress-anim.cpp.
References CSensor_keypress().
Referenced by ConstructL().
void CSensor_keypress::RunL () [private, virtual]
Definition at line 121 of file epoc-keypress-anim.cpp.
References gx_dblog_fatal_error_clear(), iCapturedKeys, iLogDb, iNumCapturedKeys, KPropertyCategory, KPropertyKey, log_db_log_status(), LogAndClear(), MakeRequest(), MAX_NUM_CAPTURED_KEYS, plat_error_strerror, px_dblog_fatal_errno(), and Stop().
gboolean CSensor_keypress::StartL (GError ** error)
Definition at line 89 of file epoc-keypress-anim.cpp.
References MakeRequest().
void CSensor_keypress::Stop ()
Definition at line 100 of file epoc-keypress-anim.cpp.
References LogAndClear().
Referenced by RunL().
Member Data Documentation
time_t CSensor_keypress::iCapturedKeys[MAX_NUM_CAPTURED_KEYS] [private]
Definition at line 74 of file epoc-keypress-anim.hpp.
Referenced by LogAndClear(), and RunL().
TInt32 CSensor_keypress::iCaptureHandles[350] [private]
Definition at line 68 of file epoc-keypress-anim.hpp.
CKeyEventsClient* CSensor_keypress::iKeyEventsClient [private]
Definition at line 66 of file epoc-keypress-anim.hpp.
Referenced by ConstructL(), and ~CSensor_keypress().
GString* CSensor_keypress::iKeysText [private]
Definition at line 76 of file epoc-keypress-anim.hpp.
Referenced by ConstructL(), LogAndClear(), and ~CSensor_keypress().
LogDb* CSensor_keypress::iLogDb [private]
Definition at line 58 of file epoc-keypress-anim.hpp.
Referenced by CSensor_keypress(), LogAndClear(), and RunL().
int CSensor_keypress::iNumCapturedKeys [private]
Definition at line 75 of file epoc-keypress-anim.hpp.
Referenced by LogAndClear(), and RunL().
int CSensor_keypress::iNumCaptureHandles [private]
Definition at line 69 of file epoc-keypress-anim.hpp.
RWsSession* CSensor_keypress::iSession [private]
Definition at line 60 of file epoc-keypress-anim.hpp.
Referenced by ConstructL(), and ~CSensor_keypress().
RWindowGroup* CSensor_keypress::iWinGroup [private]
Definition at line 61 of file epoc-keypress-anim.hpp.
Referenced by ConstructL(), and ~CSensor_keypress().
CApaWindowGroupName* CSensor_keypress::iWinGroupName [private]
Definition at line 62 of file epoc-keypress-anim.hpp.
Referenced by ConstructL(), and ~CSensor_keypress().
The documentation for this class was generated from the following files:
epoc-keypress-anim.hpp
epoc-keypress-anim.cpp
epoc-keypress.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1