ContextLogger2 Logger Daemon Internals: CMainObj Class Reference
CMainObj Class Reference
Public Member Functions
~CMainObj ()
~CMainObj ()
~CMainObj ()
Static Public Member Functions
static CMainObj * NewL ()
static CMainObj * NewL ()
static CMainObj * NewL ()
Private Member Functions
void ConstructL ()
void AppContextReady (TInt aError)
void ConstructL ()
void AppContextReady (TInt aError)
void ConstructL ()
void AppContextReady (TInt aError)
Private Attributes
kr_Controller * controller
kr_Controller * client
Detailed Description
Definition at line 52 of file main_demo_epoc_qt.cpp.
Constructor & Destructor Documentation
CMainObj::~CMainObj ()
Definition at line 76 of file main_demo_epoc_qt.cpp.
References controller, kr_Controller_destroy(), and logt.
CMainObj::~CMainObj ()
CMainObj::~CMainObj ()
Member Function Documentation
void CMainObj::AppContextReady (TInt aError) [private]
void CMainObj::AppContextReady (TInt aError) [private]
void CMainObj::AppContextReady (TInt aError) [private]
Definition at line 91 of file main_demo_epoc_qt.cpp.
References controller, er_FATAL, er_FREE, er_log_gerror, er_log_symbian, kr_Controller_new(), kr_Controller_start(), and logt.
void CMainObj::ConstructL () [private]
void CMainObj::ConstructL () [private]
void CMainObj::ConstructL () [private]
Definition at line 85 of file main_demo_epoc_qt.cpp.
References ac_get_global_AppContext().
Referenced by NewL().
static CMainObj* CMainObj::NewL () [static]
static CMainObj* CMainObj::NewL () [static]
CMainObj * CMainObj::NewL () [static]
Definition at line 67 of file main_demo_epoc_qt.cpp.
References ConstructL().
Referenced by MainLoop(), and QtMainE().
Member Data Documentation
kr_Controller* CMainObj::client [private]
Definition at line 52 of file main_epoc.cpp.
kr_Controller * CMainObj::controller [private]
Definition at line 64 of file main_demo_epoc_qt.cpp.
Referenced by AppContextReady(), and ~CMainObj().
The documentation for this class was generated from the following files:
main_demo_epoc_qt.cpp
main_epoc.cpp
main_epoc_qt.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1