ContextLogger2 Logger Daemon Internals: CSensor_btprox Class Reference
CSensor_btprox Class Reference
#include <epoc-btprox.hpp>
Public Member Functions
virtual ~CSensor_btprox ()
gboolean StartL (GError **error)
void Stop ()
void Reconfigure (const gchar *name, const gchar *value)
Static Public Member Functions
static CSensor_btprox * NewL (LogDb *aLogDb)
Private Types
enum TState { EInactive = 0, EScanWaiting, EDiscovering, ERetryWaiting }
Private Member Functions
CSensor_btprox (LogDb *aLogDb)
void ConstructL ()
TBool EnsureBtInit ()
void TryBtInitL ()
void BtClose ()
void TryStartScanning ()
gboolean HandleScanEventL (TInt errCode, GError **error)
void RefreshBaseScanIntervalSecs ()
void SetTimer ()
void BtDiscover ()
void BtNext ()
virtual gboolean RunGL (GError **error)
virtual void DoCancel ()
virtual const char * Description ()
DEF_SESSION (RSocketServ, iSocketServ)
DEF_SESSION (RHostResolver, iHostResolver)
DEF_SESSION (RTimer, iTimer)
Private Attributes
TState iState
TInquirySockAddr iInquirySockAddr
TNameEntry iNameEntry
TInt iNumScanFailures
TInt iBaseScanIntervalSecs
GPtrArray * iResult
GPtrArray * iOldResult
LogDb * iLogDb
Detailed Description
Definition at line 18 of file epoc-btprox.hpp.
Member Enumeration Documentation
enum CSensor_btprox::TState [private]
Enumerator:
EInactive
EScanWaiting
EDiscovering
ERetryWaiting
Definition at line 59 of file epoc-btprox.hpp.
Constructor & Destructor Documentation
CSensor_btprox::~CSensor_btprox () [virtual]
Definition at line 121 of file epoc-btprox.cpp.
References BtClose(), FreeResult(), iOldResult, iResult, and SESSION_CLOSE_IF_OPEN.
CSensor_btprox::CSensor_btprox (LogDb * aLogDb) [private]
Definition at line 170 of file epoc-btprox.cpp.
References iLogDb.
Referenced by NewL().
Member Function Documentation
void CSensor_btprox::BtClose () [private]
Definition at line 133 of file epoc-btprox.cpp.
References SESSION_CLOSE_IF_OPEN.
Referenced by ~CSensor_btprox().
void CSensor_btprox::BtDiscover () [private]
Definition at line 252 of file epoc-btprox.cpp.
References ClearResult(), EDiscovering, guilogf(), iInquirySockAddr, iNameEntry, iOldResult, iResult, iState, and SWAP.
Referenced by RunGL().
void CSensor_btprox::BtNext () [private]
Definition at line 270 of file epoc-btprox.cpp.
References EDiscovering, iNameEntry, and iState.
Referenced by HandleScanEventL().
void CSensor_btprox::ConstructL () [private]
Definition at line 177 of file epoc-btprox.cpp.
References iOldResult, iResult, LEAVE_IF_ERROR_OR_SET_SESSION_OPEN, RefreshBaseScanIntervalSecs(), SET_TRAP_OOM, and UNSET_TRAP_OOM.
Referenced by NewL().
CSensor_btprox::DEF_SESSION (RTimer , iTimer) [private]
CSensor_btprox::DEF_SESSION (RHostResolver , iHostResolver) [private]
CSensor_btprox::DEF_SESSION (RSocketServ , iSocketServ) [private]
const char * CSensor_btprox::Description () [private, virtual]
Implements CActiveLogErr.
Definition at line 441 of file epoc-btprox.cpp.
void CSensor_btprox::DoCancel () [private, virtual]
Definition at line 415 of file epoc-btprox.cpp.
References EDiscovering, EInactive, ERetryWaiting, EScanWaiting, and iState.
TBool CSensor_btprox::EnsureBtInit () [private]
Definition at line 193 of file epoc-btprox.cpp.
References dblogg, IS_SESSION_OPEN, plat_error_strerror, and TryBtInitL().
Referenced by TryStartScanning().
gboolean CSensor_btprox::HandleScanEventL (TInt errCode, GError ** error) [private]
Definition at line 291 of file epoc-btprox.cpp.
References BtDevAddrToString(), BtNext(), CmpResults(), dblogg, ERetryWaiting, EScanWaiting, free_item_action, guilogf(), iLogDb, iNameEntry, iNumScanFailures, iOldResult, iResult, iState, plat_error_strerror, SET_TRAP_OOM, SetTimer(), SortResult(), and UNSET_TRAP_OOM.
Referenced by RunGL().
CSensor_btprox * CSensor_btprox::NewL (LogDb * aLogDb) [static]
Definition at line 112 of file epoc-btprox.cpp.
References ConstructL(), and CSensor_btprox().
void CSensor_btprox::Reconfigure (const gchar * name, const gchar * value)
Definition at line 222 of file epoc-btprox.cpp.
References RefreshBaseScanIntervalSecs().
void CSensor_btprox::RefreshBaseScanIntervalSecs () [private]
Definition at line 231 of file epoc-btprox.cpp.
References dblogg, iBaseScanIntervalSecs, SCAN_INTERVAL_SECS, and try_get_ConfigDb_int().
Referenced by ConstructL(), and Reconfigure().
gboolean CSensor_btprox::RunGL (GError ** error) [private, virtual]
This function may either leave or return a GError.
Implements CActiveRunG.
Definition at line 363 of file epoc-btprox.cpp.
References assert_error_unset, BtDiscover(), code_timer, domain_cl2app, EDiscovering, EInactive, ERetryWaiting, EScanWaiting, gx_error_new(), HandleScanEventL(), iState, plat_error_strerror, and TryStartScanning().
void CSensor_btprox::SetTimer () [private]
Definition at line 240 of file epoc-btprox.cpp.
References ERetryWaiting, EScanWaiting, iBaseScanIntervalSecs, iNumScanFailures, iState, and SecsToUsecs().
Referenced by HandleScanEventL(), and TryStartScanning().
gboolean CSensor_btprox::StartL (GError ** error)
Definition at line 138 of file epoc-btprox.cpp.
References EInactive, iLogDb, iNumScanFailures, iState, log_db_log_status(), and TryStartScanning().
void CSensor_btprox::Stop ()
Definition at line 162 of file epoc-btprox.cpp.
References EInactive, iLogDb, iState, and log_db_log_status().
void CSensor_btprox::TryBtInitL () [private]
Definition at line 209 of file epoc-btprox.cpp.
References _LIT(), IS_SESSION_OPEN, and LEAVE_IF_ERROR_OR_SET_SESSION_OPEN.
Referenced by EnsureBtInit().
void CSensor_btprox::TryStartScanning () [private]
Definition at line 148 of file epoc-btprox.cpp.
References EnsureBtInit(), ERetryWaiting, EScanWaiting, iNumScanFailures, iState, and SetTimer().
Referenced by RunGL(), and StartL().
Member Data Documentation
TInt CSensor_btprox::iBaseScanIntervalSecs [private]
Definition at line 77 of file epoc-btprox.hpp.
Referenced by RefreshBaseScanIntervalSecs(), and SetTimer().
TInquirySockAddr CSensor_btprox::iInquirySockAddr [private]
Definition at line 72 of file epoc-btprox.hpp.
Referenced by BtDiscover().
LogDb* CSensor_btprox::iLogDb [private]
Definition at line 84 of file epoc-btprox.hpp.
Referenced by CSensor_btprox(), HandleScanEventL(), StartL(), and Stop().
TNameEntry CSensor_btprox::iNameEntry [private]
Definition at line 73 of file epoc-btprox.hpp.
Referenced by BtDiscover(), BtNext(), and HandleScanEventL().
TInt CSensor_btprox::iNumScanFailures [private]
Definition at line 75 of file epoc-btprox.hpp.
Referenced by HandleScanEventL(), SetTimer(), StartL(), and TryStartScanning().
GPtrArray* CSensor_btprox::iOldResult [private]
Definition at line 80 of file epoc-btprox.hpp.
Referenced by BtDiscover(), ConstructL(), HandleScanEventL(), and ~CSensor_btprox().
GPtrArray* CSensor_btprox::iResult [private]
Definition at line 79 of file epoc-btprox.hpp.
Referenced by BtDiscover(), ConstructL(), HandleScanEventL(), and ~CSensor_btprox().
TState CSensor_btprox::iState [private]
Definition at line 65 of file epoc-btprox.hpp.
Referenced by BtDiscover(), BtNext(), DoCancel(), HandleScanEventL(), RunGL(), SetTimer(), StartL(), Stop(), and TryStartScanning().
The documentation for this class was generated from the following files:
epoc-btprox.hpp
epoc-btprox.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1