ContextLogger2 Logger Daemon Internals: MObserverPosMod Class Reference
MObserverPosMod Class Reference
#include <epoc-gps-observer.hpp>
Public Member Functions
virtual void PosModChangeL ()=0
virtual void PosModErrorL (TInt errCode)=0
virtual void PosModLeave (TInt errCode)=0
virtual TBool PosModIsCurrent (TPositionModuleId id) const =0
Detailed Description
Definition at line 23 of file epoc-gps-observer.hpp.
Member Function Documentation
virtual void MObserverPosMod::PosModChangeL () [pure virtual]
Implemented in CSensor_cellpos.
Referenced by CPosModuleStatAo::PosModChange().
virtual void MObserverPosMod::PosModErrorL (TInt errCode) [pure virtual]
Implemented in CSensor_cellpos.
Referenced by CPosModuleStatAo::RunError().
virtual TBool MObserverPosMod::PosModIsCurrent (TPositionModuleId id) const [pure virtual]
Implemented in CSensor_cellpos.
Referenced by CPosModuleStatAo::RunL().
virtual void MObserverPosMod::PosModLeave (TInt errCode) [pure virtual]
Implemented in CSensor_cellpos.
Referenced by CPosModuleStatAo::PosModChange(), and CPosModuleStatAo::RunError().
The documentation for this class was generated from the following file:
epoc-gps-observer.hpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1