ContextLogger2 Logger Daemon Internals: CFlightModeObserver Class Reference
CFlightModeObserver Class Reference
Public Member Functions
~CFlightModeObserver ()
Private Member Functions
virtual void GotData_FlightMode (TInt aError)
virtual void ChangedData_FlightMode (TInt aError)
void HandleFlightMode (TInt aError, CTelephony::TFlightModeV1 const &aData)
Private Attributes
CTOR_DECL_CFlightModeObserver
CGetterAo_FlightMode * iGetter
CNotifyAo_FlightMode * iNotifier
MGetterObs_FlightMode & iObserver
Detailed Description
Definition at line 196 of file ac_app_context_epoc.cpp.
Constructor & Destructor Documentation
CFlightModeObserver::~CFlightModeObserver ()
Definition at line 231 of file ac_app_context_epoc.cpp.
References iGetter, and iNotifier.
Member Function Documentation
void CFlightModeObserver::ChangedData_FlightMode (TInt aError) [private, virtual]
Implements MNotifyObs_FlightMode.
Definition at line 243 of file ac_app_context_epoc.cpp.
References CNotifyAo_FlightMode::Data(), HandleFlightMode(), and iNotifier.
void CFlightModeObserver::GotData_FlightMode (TInt aError) [private, virtual]
Implements MGetterObs_FlightMode.
Definition at line 237 of file ac_app_context_epoc.cpp.
References CGetterAo_FlightMode::Data(), MGetterObs_FlightMode::GotData_FlightMode(), HandleFlightMode(), iGetter, and iObserver.
void CFlightModeObserver::HandleFlightMode (TInt aError, CTelephony::TFlightModeV1 const & aData) [private]
Definition at line 259 of file ac_app_context_epoc.cpp.
References ac_global_Blackboard, ac_global_LogDb, bb_Blackboard_board(), bb_Blackboard_notify(), bb_dt_flightmode, boolstr_on, er_FATAL, er_log_symbian, bb_Board::flightmode, iNotifier, logg, CNotifyAo_FlightMode::MakeRequest(), and TFlightModeV1ToBoolean().
Referenced by ChangedData_FlightMode(), and GotData_FlightMode().
Member Data Documentation
CFlightModeObserver::CTOR_DECL_CFlightModeObserver [private]
Definition at line 201 of file ac_app_context_epoc.cpp.
CGetterAo_FlightMode* CFlightModeObserver::iGetter [private]
Definition at line 214 of file ac_app_context_epoc.cpp.
Referenced by GotData_FlightMode(), and ~CFlightModeObserver().
CNotifyAo_FlightMode* CFlightModeObserver::iNotifier [private]
Definition at line 215 of file ac_app_context_epoc.cpp.
Referenced by ChangedData_FlightMode(), HandleFlightMode(), and ~CFlightModeObserver().
MGetterObs_FlightMode& CFlightModeObserver::iObserver [private]
Definition at line 218 of file ac_app_context_epoc.cpp.
Referenced by GotData_FlightMode().
The documentation for this class was generated from the following file:
ac_app_context_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1