ContextLogger2 Logger Daemon Internals: CActiveLogErrG Class Reference
CActiveLogErrG Class Reference
#include <epoc-ao-gerror.hpp>
Protected Member Functions
CActiveLogErrG (TInt aPriority)
virtual ~CActiveLogErrG ()
virtual TInt RunError (TInt aError)
void Leave (GError *aError)
void LeaveWithError ()
Protected Attributes
GError * iError
Detailed Description
Definition at line 35 of file epoc-ao-gerror.hpp.
Constructor & Destructor Documentation
CActiveLogErrG::CActiveLogErrG (TInt aPriority) [inline, protected]
Definition at line 38 of file epoc-ao-gerror.hpp.
CActiveLogErrG::~CActiveLogErrG () [protected, virtual]
Definition at line 29 of file epoc-ao-gerror.cpp.
References gx_error_free(), and iError.
Member Function Documentation
void CActiveLogErrG::Leave (GError * aError) [protected]
Definition at line 50 of file epoc-ao-gerror.cpp.
References gx_error_free(), iError, and KGError.
Referenced by CActiveRunG::RunL().
void CActiveLogErrG::LeaveWithError () [inline, protected]
Definition at line 49 of file epoc-ao-gerror.hpp.
References KGError.
TInt CActiveLogErrG::RunError (TInt aError) [protected, virtual]
As in CActiveLogErr, but supports the logging of a GError value.
Reimplemented from CActiveLogErr.
Definition at line 37 of file epoc-ao-gerror.cpp.
References ac_global_LogDb, CActiveLogErr::Description(), gx_dblog_fatal_error_clear(), iError, KGError, and log_db_log_status().
Member Data Documentation
GError* CActiveLogErrG::iError [protected]
Definition at line 52 of file epoc-ao-gerror.hpp.
Referenced by Leave(), RunError(), CActiveRunG::RunL(), and ~CActiveLogErrG().
The documentation for this class was generated from the following files:
epoc-ao-gerror.hpp
epoc-ao-gerror.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1