ContextLogger2 Logger Daemon Internals: CNotifyAo_CallStatus Class Reference
CNotifyAo_CallStatus Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
CNotifyAo_CallStatus (CTelephony &aTelephony, MNotifyObs_CallStatus &aInterface)
virtual ~CNotifyAo_CallStatus ()
void MakeRequest ()
CTelephony::TCallStatusV1 const & Data () const
Private Member Functions
virtual void RunL ()
virtual void DoCancel ()
Private Attributes
CTelephony::TCallStatusV1 iData
CTelephony::TCallStatusV1Pckg iDataDes
CTelephony & iTelephony
MNotifyObs_CallStatus & iInterface
Detailed Description
Definition at line 113 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CNotifyAo_CallStatus::CNotifyAo_CallStatus (CTelephony & aTelephony, MNotifyObs_CallStatus & aInterface)
Definition at line 67 of file ut_telephony_epoc.cpp.
CNotifyAo_CallStatus::~CNotifyAo_CallStatus () [virtual]
Definition at line 72 of file ut_telephony_epoc.cpp.
Member Function Documentation
CTelephony::TCallStatusV1 const & CNotifyAo_CallStatus::Data () const [inline]
Definition at line 720 of file ut_telephony_epoc.h.
References iData.
Referenced by CSensor_callstatus::ChangedData_CallStatus().
void CNotifyAo_CallStatus::DoCancel () [private, virtual]
Definition at line 90 of file ut_telephony_epoc.cpp.
References iTelephony.
void CNotifyAo_CallStatus::MakeRequest ()
Definition at line 77 of file ut_telephony_epoc.cpp.
References iDataDes, and iTelephony.
Referenced by CSensor_callstatus::ChangedData_CallStatus(), CSensor_callstatus::ChangedData_FlightMode(), CSensor_callstatus::GotData_FlightMode(), and CSensor_callstatus::RetryTimerExpired().
void CNotifyAo_CallStatus::RunL () [private, virtual]
Definition at line 85 of file ut_telephony_epoc.cpp.
References MNotifyObs_CallStatus::ChangedData_CallStatus(), and iInterface.
Member Data Documentation
CTelephony::TCallStatusV1 CNotifyAo_CallStatus::iData [private]
Definition at line 136 of file ut_telephony_epoc.h.
Referenced by Data().
CTelephony::TCallStatusV1Pckg CNotifyAo_CallStatus::iDataDes [private]
Definition at line 138 of file ut_telephony_epoc.h.
Referenced by MakeRequest().
MNotifyObs_CallStatus& CNotifyAo_CallStatus::iInterface [private]
Definition at line 142 of file ut_telephony_epoc.h.
Referenced by RunL().
CTelephony& CNotifyAo_CallStatus::iTelephony [private]
Definition at line 140 of file ut_telephony_epoc.h.
Referenced by DoCancel(), and MakeRequest().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1