ContextLogger2 Logger Daemon Internals: CImmediateAo Class Reference
CImmediateAo Class Reference
#include <ut_immediate_epoc.hpp>
Public Member Functions
~CImmediateAo ()
void Complete ()
Static Public Member Functions
static CImmediateAo * NewL (MImmediateObserver &aObserver)
Private Member Functions
CImmediateAo (MImmediateObserver &aObserver)
void DoCancel ()
TInt RunError (TInt aError)
void RunL ()
Private Attributes
MImmediateObserver & iObserver
Detailed Description
Definition at line 19 of file ut_immediate_epoc.hpp.
Constructor & Destructor Documentation
CImmediateAo::~CImmediateAo ()
Definition at line 37 of file ut_immediate_epoc.cpp.
CImmediateAo::CImmediateAo (MImmediateObserver & aObserver) [private]
Definition at line 42 of file ut_immediate_epoc.cpp.
Referenced by NewL().
Member Function Documentation
void CImmediateAo::Complete ()
Definition at line 48 of file ut_immediate_epoc.cpp.
Referenced by CUploader::StateChangedLater().
void CImmediateAo::DoCancel () [private]
Definition at line 59 of file ut_immediate_epoc.cpp.
CImmediateAo * CImmediateAo::NewL (MImmediateObserver & aObserver) [static]
Definition at line 26 of file ut_immediate_epoc.cpp.
References CImmediateAo().
Referenced by ut_Immediate_new().
TInt CImmediateAo::RunError (TInt aError) [private]
Definition at line 67 of file ut_immediate_epoc.cpp.
References MImmediateObserver::HandleImmediateLeave(), and iObserver.
void CImmediateAo::RunL () [private]
Definition at line 72 of file ut_immediate_epoc.cpp.
References MImmediateObserver::HandleImmediateError(), MImmediateObserver::HandleImmediateEvent(), and iObserver.
Member Data Documentation
MImmediateObserver& CImmediateAo::iObserver [private]
Definition at line 37 of file ut_immediate_epoc.hpp.
Referenced by RunError(), and RunL().
The documentation for this class was generated from the following files:
ut_immediate_epoc.hpp
ut_immediate_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1