ContextLogger2 Logger Daemon Internals: CTimerAo Class Reference
CTimerAo Class Reference
#include <timer_generic_epoc.h>
Static Public Member Functions
static CTimerAo * NewLC (MTimerObserver &aInterface, TInt aPriority)
static CTimerAo * NewL (MTimerObserver &aInterface, TInt aPriority)
static CTimerAo * NewLC (MTimerObserver &aInterface, TInt aPriority)
static CTimerAo * NewL (MTimerObserver &aInterface, TInt aPriority)
Private Member Functions
CTimerAo (MTimerObserver &aInterface, TInt aPriority)
virtual void RunL ()
CTimerAo (MTimerObserver &aInterface, TInt aPriority)
virtual void RunL ()
Private Attributes
MTimerObserver & iInterface
Detailed Description
A fairly generic, concrete CTimer subclass that delivers timer events via a callback interface.
Definition at line 23 of file timer_generic_epoc.h.
Constructor & Destructor Documentation
CTimerAo::CTimerAo (MTimerObserver & aInterface, TInt aPriority) [private]
Definition at line 22 of file timer_generic_epoc.cpp.
Referenced by NewLC().
CTimerAo::CTimerAo (MTimerObserver & aInterface, TInt aPriority) [private]
Member Function Documentation
static CTimerAo* CTimerAo::NewL (MTimerObserver & aInterface, TInt aPriority) [static]
CTimerAo * CTimerAo::NewL (MTimerObserver & aInterface, TInt aPriority) [static]
Definition at line 15 of file timer_generic_epoc.cpp.
References NewLC().
Referenced by QAbsTimer::QAbsTimer().
static CTimerAo* CTimerAo::NewLC (MTimerObserver & aInterface, TInt aPriority) [static]
CTimerAo * CTimerAo::NewLC (MTimerObserver & aInterface, TInt aPriority) [static]
Definition at line 7 of file timer_generic_epoc.cpp.
References CTimerAo().
Referenced by NewL().
virtual void CTimerAo::RunL () [private, virtual]
void CTimerAo::RunL () [private, virtual]
Definition at line 27 of file timer_generic_epoc.cpp.
References MTimerObserver::HandleTimerEvent(), and iInterface.
Member Data Documentation
MTimerObserver & CTimerAo::iInterface [private]
Definition at line 38 of file timer_generic_epoc.h.
Referenced by RunL().
The documentation for this class was generated from the following files:
timer_generic_epoc.h
timer_observer.h
timer_generic_epoc.cpp
timer_observer.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1