ContextLogger2 Logger Daemon Internals: CSensor_appfocus Class Reference
CSensor_appfocus Class Reference
#include <epoc-appfocus.hpp>
Public Member Functions
virtual ~CSensor_appfocus ()
gboolean StartL (GError **error)
void Stop ()
Static Public Member Functions
static CSensor_appfocus * NewL (LogDb *aLogDb)
Private Member Functions
CSensor_appfocus (LogDb *aLogDb)
void ConstructL ()
void MakeRequest ()
virtual gboolean RunGL (GError **error)
virtual const char * Description ()
virtual void DoCancel ()
DEF_SESSION (RWsSession, iWsSession)
Private Attributes
LogDb * iLogDb
TBool iFocusChangeEventsEnabled
CMyWindowGroup * iMyWindowGroup
Detailed Description
Definition at line 24 of file epoc-appfocus.hpp.
Constructor & Destructor Documentation
CSensor_appfocus::~CSensor_appfocus () [virtual]
Definition at line 110 of file epoc-appfocus.cpp.
References iMyWindowGroup, and SESSION_CLOSE_IF_OPEN.
CSensor_appfocus::CSensor_appfocus (LogDb * aLogDb) [private]
Definition at line 94 of file epoc-appfocus.cpp.
References iLogDb.
Referenced by NewL().
Member Function Documentation
void CSensor_appfocus::ConstructL () [private]
Definition at line 101 of file epoc-appfocus.cpp.
References iMyWindowGroup, LEAVE_IF_ERROR_OR_SET_SESSION_OPEN, and NewL().
Referenced by NewL().
CSensor_appfocus::DEF_SESSION (RWsSession , iWsSession) [private]
const char * CSensor_appfocus::Description () [private, virtual]
Implements CActiveLogErr.
Definition at line 214 of file epoc-appfocus.cpp.
void CSensor_appfocus::DoCancel () [private, virtual]
Definition at line 219 of file epoc-appfocus.cpp.
void CSensor_appfocus::MakeRequest () [private]
Definition at line 148 of file epoc-appfocus.cpp.
Referenced by RunGL(), and StartL().
CSensor_appfocus * CSensor_appfocus::NewL (LogDb * aLogDb) [static]
Definition at line 85 of file epoc-appfocus.cpp.
References ConstructL(), and CSensor_appfocus().
Referenced by ConstructL().
gboolean CSensor_appfocus::RunGL (GError ** error) [private, virtual]
This function may either leave or return a GError.
Implements CActiveRunG.
Definition at line 157 of file epoc-appfocus.cpp.
References assert_error_unset, guilogf(), iLogDb, log_db_log_appfocus(), log_db_log_status(), MakeRequest(), and plat_error_strerror.
gboolean CSensor_appfocus::StartL (GError ** error)
Definition at line 117 of file epoc-appfocus.cpp.
References iFocusChangeEventsEnabled, iMyWindowGroup, MakeRequest(), and CMyWindowGroup::Ref().
void CSensor_appfocus::Stop ()
Definition at line 134 of file epoc-appfocus.cpp.
References iFocusChangeEventsEnabled, iMyWindowGroup, and CMyWindowGroup::Ref().
Member Data Documentation
TBool CSensor_appfocus::iFocusChangeEventsEnabled [private]
Definition at line 58 of file epoc-appfocus.hpp.
Referenced by StartL(), and Stop().
LogDb* CSensor_appfocus::iLogDb [private]
Definition at line 56 of file epoc-appfocus.hpp.
Referenced by CSensor_appfocus(), and RunGL().
CMyWindowGroup* CSensor_appfocus::iMyWindowGroup [private]
Definition at line 60 of file epoc-appfocus.hpp.
Referenced by ConstructL(), StartL(), Stop(), and ~CSensor_appfocus().
The documentation for this class was generated from the following files:
epoc-appfocus.hpp
epoc-appfocus.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1