ContextLogger2 Logger Daemon Internals: CSensor_profile Class Reference
CSensor_profile Class Reference
#include <epoc-profile-31.hpp>
Public Member Functions
virtual ~CSensor_profile ()
gboolean StartL (GError **error)
void Stop ()
gboolean IsActive ()
Static Public Member Functions
static CSensor_profile * NewL (LogDb *aLogDb)
Private Member Functions
CSensor_profile (LogDb *aLogDb)
void ConstructL ()
virtual void HandleProfileActivatedL (TInt aProfileId)
HBufC8 * GetCurrentProfileNameL ()
Private Attributes
LogDb * iLogDb
MProEngEngine * iProfileEngine
MProEngNotifyHandler * iNotifyHandler
TBool iIsActive
Detailed Description
Definition at line 23 of file epoc-profile-31.hpp.
Constructor & Destructor Documentation
CSensor_profile::~CSensor_profile () [virtual]
Definition at line 75 of file epoc-profile-31.cpp.
References iNotifyHandler, and iProfileEngine.
CSensor_profile::CSensor_profile (LogDb * aLogDb) [private]
Definition at line 45 of file epoc-profile-31.cpp.
References iLogDb.
Referenced by NewL().
Member Function Documentation
void CSensor_profile::ConstructL () [private]
Definition at line 50 of file epoc-profile-31.cpp.
References iNotifyHandler, and iProfileEngine.
Referenced by NewL().
HBufC8 * CSensor_profile::GetCurrentProfileNameL () [private]
Definition at line 22 of file epoc-profile-31.cpp.
References iProfileEngine.
Referenced by HandleProfileActivatedL().
void CSensor_profile::HandleProfileActivatedL (TInt aProfileId) [private, virtual]
Definition at line 85 of file epoc-profile-31.cpp.
References dblogg, GetCurrentProfileNameL(), guilogf(), gx_dblog_fatal_error_free(), iLogDb, log_db_log_profile(), and plat_error_strerror.
gboolean CSensor_profile::IsActive () [inline]
Definition at line 40 of file epoc-profile-31.hpp.
CSensor_profile * CSensor_profile::NewL (LogDb * aLogDb) [static]
Definition at line 36 of file epoc-profile-31.cpp.
References ConstructL(), and CSensor_profile().
gboolean CSensor_profile::StartL (GError ** error)
Definition at line 56 of file epoc-profile-31.cpp.
References iIsActive, and iNotifyHandler.
void CSensor_profile::Stop ()
Definition at line 66 of file epoc-profile-31.cpp.
References iIsActive, and iNotifyHandler.
Member Data Documentation
TBool CSensor_profile::iIsActive [private]
Definition at line 67 of file epoc-profile-31.hpp.
Referenced by StartL(), and Stop().
LogDb* CSensor_profile::iLogDb [private]
Definition at line 61 of file epoc-profile-31.hpp.
Referenced by CSensor_profile(), and HandleProfileActivatedL().
MProEngNotifyHandler* CSensor_profile::iNotifyHandler [private]
Definition at line 65 of file epoc-profile-31.hpp.
Referenced by ConstructL(), StartL(), Stop(), and ~CSensor_profile().
MProEngEngine* CSensor_profile::iProfileEngine [private]
Definition at line 63 of file epoc-profile-31.hpp.
Referenced by ConstructL(), GetCurrentProfileNameL(), and ~CSensor_profile().
The documentation for this class was generated from the following files:
epoc-profile-31.hpp
epoc-profile-31.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1