ContextLogger2 Logger Daemon Internals: CObserverAo_NetworkRegistration Class Reference
CObserverAo_NetworkRegistration Class Reference
#include <ut_telephony_epoc.h>
Public Member Functions
virtual ~CObserverAo_NetworkRegistration ()
void HandleFlightModeChange ()
Static Public Member Functions
static
CObserverAo_NetworkRegistration * NewLC (ac_AppContext *aAppContext, MObserverObs_NetworkRegistration &aInterface)
static
CObserverAo_NetworkRegistration * NewL (ac_AppContext *aAppContext, MObserverObs_NetworkRegistration &aInterface)
Private Member Functions
CObserverAo_NetworkRegistration (ac_AppContext *aAppContext, MObserverObs_NetworkRegistration &aInterface)
void ConstructL ()
void BbRegisterL ()
void BbUnregister ()
void MakeRequest ()
void Cancel ()
TBool GetFlightMode () const
virtual void GotData_NetworkRegistration (TInt aError)
virtual void ChangedData_NetworkRegistration (TInt aError)
void HandleData (TInt aError, TData_NetworkRegistration const &aData)
Private Attributes
ac_AppContext * iAppContext
MObserverObs_NetworkRegistration & iInterface
TBool iGetterDone
CGetterAo_NetworkRegistration * iGetter
CNotifyAo_NetworkRegistration * iNotifier
bb_Closure iClosure
Detailed Description
Definition at line 652 of file ut_telephony_epoc.h.
Constructor & Destructor Documentation
CObserverAo_NetworkRegistration::CObserverAo_NetworkRegistration (ac_AppContext * aAppContext, MObserverObs_NetworkRegistration & aInterface) [private]
Definition at line 586 of file ut_telephony_epoc.cpp.
Referenced by NewLC().
CObserverAo_NetworkRegistration::~CObserverAo_NetworkRegistration () [virtual]
Definition at line 590 of file ut_telephony_epoc.cpp.
References BbUnregister(), iGetter, and iNotifier.
Member Function Documentation
void CObserverAo_NetworkRegistration::BbRegisterL () [private]
Definition at line 607 of file ut_telephony_epoc.cpp.
References ac_get_Blackboard(), bb_Closure::arg, bb_Blackboard_register(), bb_dt_flightmode, bb_Closure::changed, ClosureFunc_NetworkRegistration(), iAppContext, and iClosure.
Referenced by ConstructL().
void CObserverAo_NetworkRegistration::BbUnregister () [private]
Definition at line 616 of file ut_telephony_epoc.cpp.
References ac_get_Blackboard(), bb_Blackboard_unregister(), iAppContext, and iClosure.
Referenced by ~CObserverAo_NetworkRegistration().
void CObserverAo_NetworkRegistration::Cancel () [private]
Definition at line 630 of file ut_telephony_epoc.cpp.
References iGetter, iGetterDone, and iNotifier.
Referenced by HandleFlightModeChange().
void CObserverAo_NetworkRegistration::ChangedData_NetworkRegistration (TInt aError) [private, virtual]
Implements MNotifyObs_NetworkRegistration.
Definition at line 660 of file ut_telephony_epoc.cpp.
References CNotifyAo_NetworkRegistration::Data(), HandleData(), and iNotifier.
void CObserverAo_NetworkRegistration::ConstructL () [private]
Definition at line 597 of file ut_telephony_epoc.cpp.
References BbRegisterL(), GetFlightMode(), iAppContext, iGetter, iNotifier, and CGetterAo_NetworkRegistration::MakeRequest().
TBool CObserverAo_NetworkRegistration::GetFlightMode () const [private]
Definition at line 637 of file ut_telephony_epoc.cpp.
References ac_global_Blackboard, bb_Blackboard_board(), and bb_Board::flightmode.
Referenced by ConstructL(), and HandleFlightModeChange().
void CObserverAo_NetworkRegistration::GotData_NetworkRegistration (TInt aError) [private, virtual]
Implements MGetterObs_NetworkRegistration.
Definition at line 652 of file ut_telephony_epoc.cpp.
References CGetterAo_NetworkRegistration::Data(), HandleData(), iGetter, and iGetterDone.
void CObserverAo_NetworkRegistration::HandleData (TInt aError, TData_NetworkRegistration const & aData) [private]
Definition at line 665 of file ut_telephony_epoc.cpp.
References MObserverObs_NetworkRegistration::Failed_NetworkRegistration(), iInterface, iNotifier, CNotifyAo_NetworkRegistration::MakeRequest(), and MObserverObs_NetworkRegistration::ObservedData_NetworkRegistration().
Referenced by ChangedData_NetworkRegistration(), and GotData_NetworkRegistration().
void CObserverAo_NetworkRegistration::HandleFlightModeChange ()
Definition at line 642 of file ut_telephony_epoc.cpp.
References Cancel(), GetFlightMode(), iInterface, MObserverObs_NetworkRegistration::InFlightMode_NetworkRegistration(), and MakeRequest().
void CObserverAo_NetworkRegistration::MakeRequest () [private]
Definition at line 621 of file ut_telephony_epoc.cpp.
References iGetter, iGetterDone, iNotifier, CGetterAo_NetworkRegistration::MakeRequest(), and CNotifyAo_NetworkRegistration::MakeRequest().
Referenced by HandleFlightModeChange().
CObserverAo_NetworkRegistration * CObserverAo_NetworkRegistration::NewL (ac_AppContext * aAppContext, MObserverObs_NetworkRegistration & aInterface) [static]
Definition at line 579 of file ut_telephony_epoc.cpp.
References NewLC().
CObserverAo_NetworkRegistration * CObserverAo_NetworkRegistration::NewLC (ac_AppContext * aAppContext, MObserverObs_NetworkRegistration & aInterface) [static]
Definition at line 571 of file ut_telephony_epoc.cpp.
References CObserverAo_NetworkRegistration().
Referenced by NewL().
Member Data Documentation
ac_AppContext* CObserverAo_NetworkRegistration::iAppContext [private]
Definition at line 673 of file ut_telephony_epoc.h.
Referenced by BbRegisterL(), BbUnregister(), and ConstructL().
bb_Closure CObserverAo_NetworkRegistration::iClosure [private]
Definition at line 683 of file ut_telephony_epoc.h.
Referenced by BbRegisterL(), and BbUnregister().
CGetterAo_NetworkRegistration* CObserverAo_NetworkRegistration::iGetter [private]
Definition at line 679 of file ut_telephony_epoc.h.
Referenced by Cancel(), ConstructL(), GotData_NetworkRegistration(), MakeRequest(), and ~CObserverAo_NetworkRegistration().
TBool CObserverAo_NetworkRegistration::iGetterDone [private]
Definition at line 677 of file ut_telephony_epoc.h.
Referenced by Cancel(), GotData_NetworkRegistration(), and MakeRequest().
MObserverObs_NetworkRegistration& CObserverAo_NetworkRegistration::iInterface [private]
Definition at line 675 of file ut_telephony_epoc.h.
Referenced by HandleData(), and HandleFlightModeChange().
CNotifyAo_NetworkRegistration* CObserverAo_NetworkRegistration::iNotifier [private]
Definition at line 681 of file ut_telephony_epoc.h.
Referenced by Cancel(), ChangedData_NetworkRegistration(), ConstructL(), HandleData(), MakeRequest(), and ~CObserverAo_NetworkRegistration().
The documentation for this class was generated from the following files:
ut_telephony_epoc.h
ut_telephony_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1