ContextLogger2 Logger Daemon Internals: CSmsTrigger Class Reference
CSmsTrigger Class Reference
#include <kr_sms_trigger_epoc.hpp>
Public Member Functions
~CSmsTrigger ()
Private Member Functions
DEF_SESSION (RSocketServ, iSocketServ)
DEF_SESSION (RSocket, iSocket)
virtual void RunL ()
virtual void DoCancel ()
virtual TInt RunError (TInt errCode)
void MakeRequest ()
Private Attributes
CTOR_DECL_CSmsTrigger
ac_AppContext * iAppContext
RFs & iFs
TSmsAddr iSmsAddr
TPckgBuf< TUint > iPckgBuf
TBool iRead
Detailed Description
Definition at line 56 of file kr_sms_trigger_epoc.hpp.
Constructor & Destructor Documentation
CSmsTrigger::~CSmsTrigger ()
Definition at line 36 of file kr_sms_trigger_epoc.cpp.
References SESSION_CLOSE_IF_OPEN.
Member Function Documentation
CSmsTrigger::DEF_SESSION (RSocket , iSocket) [private]
CSmsTrigger::DEF_SESSION (RSocketServ , iSocketServ) [private]
void CSmsTrigger::DoCancel () [private, virtual]
Definition at line 112 of file kr_sms_trigger_epoc.cpp.
void CSmsTrigger::MakeRequest () [private]
Definition at line 125 of file kr_sms_trigger_epoc.cpp.
References iPckgBuf, and iRead.
Referenced by RunL().
TInt CSmsTrigger::RunError (TInt errCode) [private, virtual]
Definition at line 119 of file kr_sms_trigger_epoc.cpp.
References er_log_symbian.
Referenced by RunL().
void CSmsTrigger::RunL () [private, virtual]
Definition at line 43 of file kr_sms_trigger_epoc.cpp.
References ac_get_Remokon(), er_FREE, er_log_gerror, iAppContext, iFs, iPckgBuf, iRead, logg, MakeRequest(), rk_Remokon_start_timed(), and RunError().
Member Data Documentation
CSmsTrigger::CTOR_DECL_CSmsTrigger [private]
Definition at line 59 of file kr_sms_trigger_epoc.hpp.
ac_AppContext* CSmsTrigger::iAppContext [private]
Definition at line 65 of file kr_sms_trigger_epoc.hpp.
Referenced by RunL().
RFs& CSmsTrigger::iFs [private]
Definition at line 66 of file kr_sms_trigger_epoc.hpp.
Referenced by RunL().
TPckgBuf<TUint> CSmsTrigger::iPckgBuf [private]
Definition at line 70 of file kr_sms_trigger_epoc.hpp.
Referenced by MakeRequest(), and RunL().
TBool CSmsTrigger::iRead [private]
Definition at line 71 of file kr_sms_trigger_epoc.hpp.
Referenced by MakeRequest(), and RunL().
TSmsAddr CSmsTrigger::iSmsAddr [private]
Definition at line 69 of file kr_sms_trigger_epoc.hpp.
The documentation for this class was generated from the following files:
kr_sms_trigger_epoc.hpp
kr_sms_trigger_epoc.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1