ContextLogger2 Logger Daemon Internals: CPosModuleStatAo Class Reference
CPosModuleStatAo Class Reference
#include <epoc-gps-module.hpp>
Public Types
enum { KAllowAssisted = 1, KAllowExternal = 2 }
Public Member Functions
virtual ~CPosModuleStatAo ()
void MakeRequest ()
TPositionModuleId ChooseBestPositionerL (TInt aModifiers)
RPositionServer & PositionServer ()
Static Public Member Functions
static CPosModuleStatAo * NewL (MObserverPosMod &aObserver)
Private Member Functions
CPosModuleStatAo (MObserverPosMod &aObserver)
void ConstructL ()
DEF_SESSION (RPositionServer, iPositionServer)
void PosModChange ()
virtual void DoCancel ()
virtual TInt RunError (TInt errCode)
virtual void RunL ()
Private Attributes
MObserverPosMod & iObserver
TPositionModuleStatusEvent iPositionModuleStatusEvent
Detailed Description
Definition at line 12 of file epoc-gps-module.hpp.
Member Enumeration Documentation
anonymous enum
Enumerator:
KAllowAssisted
KAllowExternal
Definition at line 32 of file epoc-gps-module.hpp.
Constructor & Destructor Documentation
CPosModuleStatAo::~CPosModuleStatAo () [virtual]
Definition at line 15 of file epoc-gps-module.cpp.
References SESSION_CLOSE_IF_OPEN.
CPosModuleStatAo::CPosModuleStatAo (MObserverPosMod & aObserver) [private]
Definition at line 21 of file epoc-gps-module.cpp.
Referenced by NewL().
Member Function Documentation
TPositionModuleId CPosModuleStatAo::ChooseBestPositionerL (TInt aModifiers)
Definition at line 67 of file epoc-gps-module.cpp.
References bestIndex(), dblogg, guilogf(), KAllowAssisted, KAllowExternal, and logg.
Referenced by CSensor_cellpos::PosModChangeL().
void CPosModuleStatAo::ConstructL () [private]
Definition at line 28 of file epoc-gps-module.cpp.
References iPositionModuleStatusEvent, and LEAVE_IF_ERROR_OR_SET_SESSION_OPEN.
Referenced by NewL().
CPosModuleStatAo::DEF_SESSION (RPositionServer , iPositionServer) [private]
void CPosModuleStatAo::DoCancel () [private, virtual]
Definition at line 42 of file epoc-gps-module.cpp.
void CPosModuleStatAo::MakeRequest ()
Definition at line 34 of file epoc-gps-module.cpp.
References iPositionModuleStatusEvent.
Referenced by CSensor_cellpos::PosModChangeL().
CPosModuleStatAo * CPosModuleStatAo::NewL (MObserverPosMod & aObserver) [static]
Definition at line 6 of file epoc-gps-module.cpp.
References ConstructL(), and CPosModuleStatAo().
Referenced by FindIapByNameL(), IsModemIapL(), and LogBearerTypesL().
RPositionServer& CPosModuleStatAo::PositionServer () [inline]
Definition at line 38 of file epoc-gps-module.hpp.
Referenced by CSensor_cellpos::CreateSpecifiedPositionerL().
void CPosModuleStatAo::PosModChange () [private]
Definition at line 56 of file epoc-gps-module.cpp.
References iObserver, MObserverPosMod::PosModChangeL(), and MObserverPosMod::PosModLeave().
Referenced by RunL().
TInt CPosModuleStatAo::RunError (TInt errCode) [private, virtual]
Definition at line 48 of file epoc-gps-module.cpp.
References iObserver, MObserverPosMod::PosModErrorL(), and MObserverPosMod::PosModLeave().
Referenced by RunL().
void CPosModuleStatAo::RunL () [private, virtual]
Definition at line 178 of file epoc-gps-module.cpp.
References DeviceNotAvailable(), iObserver, iPositionModuleStatusEvent, logg, PosModChange(), MObserverPosMod::PosModIsCurrent(), and RunError().
Member Data Documentation
MObserverPosMod& CPosModuleStatAo::iObserver [private]
Definition at line 25 of file epoc-gps-module.hpp.
Referenced by PosModChange(), RunError(), and RunL().
TPositionModuleStatusEvent CPosModuleStatAo::iPositionModuleStatusEvent [private]
Definition at line 26 of file epoc-gps-module.hpp.
Referenced by ConstructL(), MakeRequest(), and RunL().
The documentation for this class was generated from the following files:
epoc-gps-module.hpp
epoc-gps-module.cpp
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1