ContextLogger2 Logger Daemon Internals: client-run.c File Reference
client-run.c File Reference
Defines
#define TRAP_OOM_ENOMEM(_x) TRAP_OOM_VALUE(ENOMEM, _x)
Functions
gboolean cl2RunOnce (GError **error)
int cl2RunOnceGetExitCode ()
int cl2GlobalInit ()
void cl2GlobalCleanup ()
Define Documentation
#define TRAP_OOM_ENOMEM (_x) TRAP_OOM_VALUE(ENOMEM, _x)
Definition at line 84 of file client-run.c.
Referenced by cl2GlobalInit().
Function Documentation
void cl2GlobalCleanup ()
Definition at line 203 of file client-run.c.
References ac_AppContext_destroy(), ac_get_global_AppContext(), ac_set_global_AppContext(), logt, and up_global_cleanup().
Referenced by main(), QtMainE(), SubMain(), and CCl2appAppUi::~CCl2appAppUi().
int cl2GlobalInit ()
Definition at line 91 of file client-run.c.
References __ABLD_VARIANT__, __APP_NAME__, __COMPILER_NAME__, __VARIANT_NAME__, __VERSION_STRING__, ac_AppContext_new(), ac_set_global_AppContext(), error(), g_snprintf_fix, gx_txtlog_error_clear(), log_clear, log_ctx, log_text(), logg, logst, logt, preallocate_all_quarks, PRIMARY_LOG_FILENAME, SET_TRAP_OOM_VALUE, TRAP_OOM_ENOMEM, UNSET_TRAP_OOM, and up_global_init().
Referenced by CCl2appAppUi::ConstructL(), main(), QtMainE(), and SubMain().
gboolean cl2RunOnce (GError ** error)
Definition at line 29 of file client-run.c.
References assert_error_unset, kr_Controller_destroy(), kr_Controller_new(), kr_Controller_run(), kr_Controller_start(), kr_Controller_stop(), and logt.
Referenced by cl2RunOnceGetExitCode().
int cl2RunOnceGetExitCode ()
Definition at line 63 of file client-run.c.
References cl2RunOnce(), error(), gx_txtlog_error_clear(), and logt.
Referenced by main().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1