ContextLogger2 Logger Daemon Internals: complete.c File Reference
complete.c File Reference
Defines
#define tkSEMI 0
#define tkWS 1
#define tkOTHER 2
#define tkEXPLAIN 3
#define tkCREATE 4
#define tkTEMP 5
#define tkTRIGGER 6
#define tkEND 7
Functions
int sqlite3_complete (const char *zSql)
int sqlite3_complete16 (const void *zSql)
Define Documentation
#define tkCREATE 4
Definition at line 47 of file complete.c.
Referenced by sqlite3_complete().
#define tkEND 7
Definition at line 50 of file complete.c.
Referenced by sqlite3_complete().
#define tkEXPLAIN 3
Definition at line 46 of file complete.c.
Referenced by sqlite3_complete().
#define tkOTHER 2
Definition at line 45 of file complete.c.
Referenced by sqlite3_complete().
#define tkSEMI 0
Definition at line 43 of file complete.c.
Referenced by sqlite3_complete().
#define tkTEMP 5
Definition at line 48 of file complete.c.
Referenced by sqlite3_complete().
#define tkTRIGGER 6
Definition at line 49 of file complete.c.
Referenced by sqlite3_complete().
#define tkWS 1
Definition at line 44 of file complete.c.
Referenced by sqlite3_complete().
Function Documentation
int sqlite3_complete (const char * zSql)
Definition at line 102 of file complete.c.
References IdChar, sqlite3StrNICmp(), tkCREATE, tkEND, tkEXPLAIN, tkOTHER, tkSEMI, tkTEMP, tkTRIGGER, and tkWS.
Referenced by DbObjCmd(), FUNC(), process_input(), and sqlite3_complete16().
int sqlite3_complete16 (const void * zSql)
Definition at line 256 of file complete.c.
References sqlite3_complete(), sqlite3_initialize(), sqlite3ApiExit(), sqlite3ValueFree(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3ValueText(), SQLITE_NOMEM, SQLITE_STATIC, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1