ContextLogger2 Logger Daemon Internals: config_db.h File Reference
config_db.h File Reference
Typedefs
typedef struct _ConfigDb ConfigDb
Functions
ConfigDb * ConfigDb_new (GError **error)
void ConfigDb_destroy (ConfigDb *self)
gchar * ConfigDb_get_generic (ConfigDb *self, const gchar *name, GError **error)
gboolean ConfigDb_set_generic (ConfigDb *self, const gchar *name, const gchar *value, GError **error)
Typedef Documentation
typedef struct _ConfigDb ConfigDb
Definition at line 17 of file config_db.h.
Function Documentation
void ConfigDb_destroy (ConfigDb * self)
Definition at line 145 of file config_db.c.
References close_config_db_session(), and mutex_destroy.
Referenced by ConfigDb_new(), and kr_Controller_destroy().
gchar* ConfigDb_get_generic (ConfigDb * self, const gchar * name, GError ** error)
Definition at line 230 of file config_db.c.
References db_get(), and mutex_synchronized.
ConfigDb* ConfigDb_new (GError ** error)
Definition at line 119 of file config_db.c.
References ConfigDb_destroy(), ensure_config_db_created(), gx_error_no_memory, mutex_init, and open_config_db_session().
Referenced by kr_Controller_new().
gboolean ConfigDb_set_generic (ConfigDb * self, const gchar * name, const gchar * value, GError ** error)
Definition at line 297 of file config_db.c.
References ac_global_Controller, db_set(), kr_Controller_reconfigure(), and mutex_synchronized.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1