ContextLogger2 Logger Daemon Internals: db_creation.c File Reference
db_creation.c File Reference
Functions
gboolean create_database (const char *db_dir, const char *db_file, const char *sql, GError **error)
gboolean ensure_database_created (const char *db_dir, const char *db_file, const char *sql, GError **error)
Function Documentation
gboolean create_database (const char * db_dir, const char * db_file, const char * sql, GError ** error)
Definition at line 11 of file db_creation.c.
References code_database_close, code_database_command, code_database_open, db, domain_cl2app, gx_error_new(), logt, mkdir_p(), rm_file(), sqlite3_close(), sqlite3_exec(), sqlite3_open(), and sqlite_get_error_string.
Referenced by create_config_db(), create_log_db(), and ensure_database_created().
gboolean ensure_database_created (const char * db_dir, const char * db_file, const char * sql, GError ** error)
Definition at line 66 of file db_creation.c.
References assert_error_unset, and create_database().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1