ContextLogger2 Logger Daemon Internals: delete.c File Reference
delete.c File Reference
Functions
Table * sqlite3SrcListLookup (Parse *pParse, SrcList *pSrc)
int sqlite3IsReadOnly (Parse *pParse, Table *pTab, int viewOk)
void sqlite3OpenTable (Parse *p, int iCur, int iDb, Table *pTab, int opcode)
void sqlite3MaterializeView (Parse *pParse, Table *pView, Expr *pWhere, int iCur)
void sqlite3DeleteFrom (Parse *pParse, SrcList *pTabList, Expr *pWhere)
void sqlite3GenerateRowDelete (Parse *pParse, Table *pTab, int iCur, int iRowid, int count)
void sqlite3GenerateRowIndexDelete (Parse *pParse, Table *pTab, int iCur, int *aRegIdx)
int sqlite3GenerateIndexKey (Parse *pParse, Index *pIdx, int iCur, int regOut, int doMakeRec)
Function Documentation
void sqlite3DeleteFrom (Parse * pParse, SrcList * pTabList, Expr * pWhere)
Definition at line 218 of file delete.c.
References SrcList::a, sqlite3::aDb, COLNAME_NAME, Parse::db, db, sqlite3::flags, SrcList::SrcList_item::iCursor, IsVirtual, sqlite3::mallocFailed, Table::nCol, Parse::nErr, Parse::nested, Parse::nMem, SrcList::nSrc, Parse::nTab, OE_Default, OP_AddImm, OP_Clear, OP_Close, OP_FifoRead, OP_FifoWrite, OP_Goto, OP_Insert, OP_Integer, OP_NotExists, OP_Null, OP_OpenPseudo, OP_OpenWrite, OP_ResultRow, OP_RowData, OP_Rowid, OP_SetNumColumns, OP_VRowid, OP_VUpdate, TriggerStack::orconf, P4_STATIC, P4_VTAB, Table::pIndex, Index::pNext, NameContext::pParse, AuthContext::pParse, Index::pSchema, Table::pSchema, Table::pSelect, NameContext::pSrcList, Table::pVtab, sqlite3AuthCheck(), sqlite3AuthContextPop(), sqlite3AuthContextPush(), sqlite3BeginWriteOperation(), sqlite3CodeRowTrigger(), sqlite3ExprDelete(), sqlite3GenerateRowDelete(), sqlite3GetVdbe(), sqlite3IsReadOnly(), sqlite3MaterializeView(), sqlite3OpenTableAndIndices(), sqlite3ResolveExprNames(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3TriggersExist(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeCountChanges(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3ViewGetColumnNames(), sqlite3VtabMakeWritable(), sqlite3WhereBegin(), sqlite3WhereEnd(), SQLITE_CountRows, SQLITE_DELETE, SQLITE_DENY, SQLITE_IGNORE, SQLITE_OK, SQLITE_STATIC, TK_DELETE, Index::tnum, Table::tnum, TRIGGER_AFTER, TRIGGER_BEFORE, Parse::trigStack, Table::zName, and Db::zName.
Referenced by codeTriggerProgram(), and yy_reduce().
int sqlite3GenerateIndexKey (Parse * pParse, Index * pIdx, int iCur, int regOut, int doMakeRec)
Definition at line 598 of file delete.c.
References Index::aiColumn, Table::iPKey, Index::nColumn, OP_Column, OP_MakeRecord, OP_Rowid, OP_SCopy, Index::pTable, Parse::pVdbe, sqlite3ColumnDefault(), sqlite3ExprCacheAffinityChange(), sqlite3GetTempRange(), sqlite3IndexAffinityStr(), sqlite3ReleaseTempRange(), sqlite3VdbeAddOp2(), and sqlite3VdbeAddOp3().
Referenced by sqlite3GenerateRowIndexDelete(), sqlite3Pragma(), and sqlite3RefillIndex().
void sqlite3GenerateRowDelete (Parse * pParse, Table * pTab, int iCur, int iRowid, int count)
Definition at line 534 of file delete.c.
References OP_Delete, OP_NotExists, OPFLAG_NCHANGE, P4_STATIC, Parse::pVdbe, sqlite3GenerateRowIndexDelete(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeChangeP4(), sqlite3VdbeJumpHere(), and Table::zName.
Referenced by sqlite3DeleteFrom(), and sqlite3GenerateConstraintChecks().
void sqlite3GenerateRowIndexDelete (Parse * pParse, Table * pTab, int iCur, int * aRegIdx)
Definition at line 570 of file delete.c.
References Index::nColumn, OP_IdxDelete, Table::pIndex, Index::pNext, Parse::pVdbe, sqlite3GenerateIndexKey(), and sqlite3VdbeAddOp3().
Referenced by sqlite3GenerateConstraintChecks(), sqlite3GenerateRowDelete(), and sqlite3Update().
int sqlite3IsReadOnly (Parse * pParse, Table * pTab, int viewOk)
Definition at line 45 of file delete.c.
References Parse::db, sqlite3::flags, Parse::nested, Table::pMod, Module::pModule, Table::pSelect, sqlite3ErrorMsg(), SQLITE_WriteSchema, Table::tabFlags, TF_Readonly, sqlite3_module::xUpdate, and Table::zName.
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
void sqlite3MaterializeView (Parse * pParse, Table * pView, Expr * pWhere, int iCur)
Definition at line 92 of file delete.c.
References Parse::db, db, Token::n, Table::pSelect, sqlite3ExprDup(), sqlite3Select(), sqlite3SelectDelete(), sqlite3SelectDestInit(), sqlite3SelectDup(), sqlite3SelectNew(), sqlite3SrcListAppendFromTerm(), SRT_EphemTab, Token::z, and Table::zName.
Referenced by sqlite3DeleteFrom(), and sqlite3Update().
void sqlite3OpenTable (Parse * p, int iCur, int iDb, Table * pTab, int opcode)
Definition at line 68 of file delete.c.
References IsVirtual, Table::nCol, OP_OpenRead, OP_OpenWrite, OP_SetNumColumns, sqlite3GetVdbe(), sqlite3TableLock(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), Table::tnum, VdbeComment, and Table::zName.
Referenced by autoIncBegin(), autoIncEnd(), sqlite3FindInIndex(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Update(), sqlite3WhereBegin(), and xferOptimization().
Table* sqlite3SrcListLookup (Parse * pParse, SrcList * pSrc)
Definition at line 24 of file delete.c.
References SrcList::a, Table::nRef, SrcList::nSrc, sqlite3DeleteTable(), sqlite3IndexedByLookup(), and sqlite3LocateTable().
Referenced by sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1