ContextLogger2 Logger Daemon Internals: epoc-callstatus.cpp File Reference
epoc-callstatus.cpp File Reference
Defines
#define SET_NUMBER_AND_CONTACT
Functions
static gboolean TFlightModeV1ToBoolean (const CTelephony::TFlightModeV1 &data)
static TInt DoGetCallInfo (CTelephony &aTelephony, CTelephony::TCallInfoV1 &callInfo, CTelephony::TRemotePartyInfoV1 &remoteInfo)
Variables
CTOR_IMPL_CSensor_callstatus
Define Documentation
#define SET_NUMBER_AND_CONTACT
Value:
{ \
  if (numberW.Length() > 0) { \
    numberBuf.Copy(numberW); \
    number = (const char*)(numberBuf.PtrZ()); \
    logg("call remote party number is '%s'", number); \
    contactName = GetContactNameByPhoneNo(numberW); \
    if (contactName) { \
      logg("call remote party name is '%s'", contactName); \
    } else { \
      logt("could not get call remote party name"); \
    } \
  } else { \
    logt("could not get call remote party phone number"); \
  } \
      }
Referenced by CSensor_callstatus::ChangedData_CallStatus().
Function Documentation
static TInt DoGetCallInfo (CTelephony & aTelephony, CTelephony::TCallInfoV1 & callInfo, CTelephony::TRemotePartyInfoV1 & remoteInfo) [static]
Definition at line 55 of file epoc-callstatus.cpp.
Referenced by CSensor_callstatus::ChangedData_CallStatus().
static gboolean TFlightModeV1ToBoolean (const CTelephony::TFlightModeV1 & data) [static]
Definition at line 39 of file epoc-callstatus.cpp.
Referenced by CSensor_callstatus::ChangedData_FlightMode(), and CSensor_callstatus::GotData_FlightMode().
Variable Documentation
CTOR_IMPL_CSensor_callstatus
Definition at line 77 of file epoc-callstatus.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1