ContextLogger2 Logger Daemon Internals: epoc-iap.cpp File Reference
epoc-iap.cpp File Reference
Defines
#define MAX_IAP_NAME_LENGTH KCommsDbSvrMaxFieldLength
Functions
static TBool FindIapByNameL (const TDesC &aIapName, TUint32 &aIapId)
gboolean epoc_iap_by_name (const gchar *iapName, guint32 *iapId, gboolean *found, GError **error)
static TBool IsModemIapL (TUint32 aIapId)
gboolean epoc_iap_is_modem (guint32 iapId, gboolean *found, gboolean *yes, GError **error)
static void LogBearerTypesL ()
void epoc_log_bearer_types ()
Define Documentation
#define MAX_IAP_NAME_LENGTH KCommsDbSvrMaxFieldLength
Definition at line 13 of file epoc-iap.cpp.
Function Documentation
gboolean epoc_iap_by_name (const gchar * iapName, guint32 * iapId, gboolean * found, GError ** error)
Definition at line 45 of file epoc-iap.cpp.
References domain_symbian, FindIapByNameL(), gx_error_new(), and plat_error_strerror.
Referenced by f_iap_id_by_name().
gboolean epoc_iap_is_modem (guint32 iapId, gboolean * found, gboolean * yes, GError ** error)
Definition at line 103 of file epoc-iap.cpp.
References domain_symbian, gx_error_new(), IsModemIapL(), and plat_error_strerror.
Referenced by current_iap_is_cellular().
void epoc_log_bearer_types ()
Definition at line 160 of file epoc-iap.cpp.
References LogBearerTypesL(), and logg.
static TBool FindIapByNameL (const TDesC & aIapName, TUint32 & aIapId) [static]
Definition at line 15 of file epoc-iap.cpp.
References CPosModuleStatAo::NewL().
Referenced by epoc_iap_by_name().
static TBool IsModemIapL (TUint32 aIapId) [static]
Definition at line 79 of file epoc-iap.cpp.
References _LIT(), and CPosModuleStatAo::NewL().
Referenced by epoc_iap_is_modem().
static void LogBearerTypesL () [static]
Definition at line 125 of file epoc-iap.cpp.
References logg, and CPosModuleStatAo::NewL().
Referenced by epoc_log_bearer_types().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1