ContextLogger2 Logger Daemon Internals: epoc-iap.h File Reference
epoc-iap.h File Reference
Functions
gboolean epoc_iap_by_name (const gchar *iapName, guint32 *iapId, gboolean *found, GError **error)
gboolean epoc_iap_is_modem (guint32 iapId, gboolean *found, gboolean *yes, GError **error)
void epoc_log_bearer_types ()
Function Documentation
gboolean epoc_iap_by_name (const gchar * iapName, guint32 * iapId, gboolean * found, GError ** error)
Definition at line 45 of file epoc-iap.cpp.
References domain_symbian, FindIapByNameL(), gx_error_new(), and plat_error_strerror.
Referenced by f_iap_id_by_name().
gboolean epoc_iap_is_modem (guint32 iapId, gboolean * found, gboolean * yes, GError ** error)
Definition at line 103 of file epoc-iap.cpp.
References domain_symbian, gx_error_new(), IsModemIapL(), and plat_error_strerror.
Referenced by current_iap_is_cellular().
void epoc_log_bearer_types ()
Definition at line 160 of file epoc-iap.cpp.
References LogBearerTypesL(), and logg.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1