ContextLogger2 Logger Daemon Internals: epoc-cellpos.cpp File Reference
epoc-cellpos.cpp File Reference
Defines
#define MIN_SCAN_REQUEST_INTERVAL_SECS (3 * 60)
#define SATELLITE_QUERY_TIMEOUT_SECS (60)
#define POSITIONER_SCAN_INTERVAL_SECS (0)
#define POSITIONER_MAX_AGE_SECS (60)
#define SAT_STRING_MAX 300
#define COU_STRING_MAX 300
#define TIME_STRING_MAX 50
#define APPEND_STRING(s) { int slen = strlen(s); if (space <= slen) goto fail; space -= slen; strcpy(output, s); output += slen; }
#define APPEND_SEP { if (!first) APPEND_STRING(", "); }
#define COU_UPDATE_STATE(r) { if (r < 0 || r >= space) goto fail; space -= r; output += r; first = EFalse; }
Functions
static void LogSatelliteInfoL (LogDb *aLogDb, const char *aSensorName, const TPositionSatelliteInfo &positionInfo)
Define Documentation
#define APPEND_SEP { if (!first) APPEND_STRING(", "); }
Referenced by LogSatelliteInfoL().
#define APPEND_STRING (s) { int slen = strlen(s); if (space <= slen) goto fail; space -= slen; strcpy(output, s); output += slen; }
Referenced by LogSatelliteInfoL().
#define COU_STRING_MAX 300
Referenced by LogSatelliteInfoL().
#define COU_UPDATE_STATE (r) { if (r < 0 || r >= space) goto fail; space -= r; output += r; first = EFalse; }
Referenced by LogSatelliteInfoL().
#define MIN_SCAN_REQUEST_INTERVAL_SECS (3 * 60)
Definition at line 36 of file epoc-cellpos.cpp.
Referenced by CSensor_cellpos::ReadConfig().
#define POSITIONER_MAX_AGE_SECS (60)
Definition at line 52 of file epoc-cellpos.cpp.
Referenced by CSensor_cellpos::ReadConfig().
#define POSITIONER_SCAN_INTERVAL_SECS (0)
Definition at line 50 of file epoc-cellpos.cpp.
Referenced by CSensor_cellpos::CreateSpecifiedPositionerL().
#define SAT_STRING_MAX 300
Referenced by LogSatelliteInfoL().
#define SATELLITE_QUERY_TIMEOUT_SECS (60)
Definition at line 42 of file epoc-cellpos.cpp.
Referenced by CSensor_cellpos::ReadConfig().
#define TIME_STRING_MAX 50
Referenced by LogSatelliteInfoL().
Function Documentation
static void LogSatelliteInfoL (LogDb * aLogDb, const char * aSensorName, const TPositionSatelliteInfo & positionInfo) [static]
Definition at line 229 of file epoc-cellpos.cpp.
References _LIT(), APPEND_SEP, APPEND_STRING, COU_STRING_MAX, COU_UPDATE_STATE, g_snprintf_fix, g_string_append_printf_fix, guilogf(), LocalEpocTimeToUnixTime(), log_db_log_position(), logg, logt, output, SAT_STRING_MAX, SET_TRAP_OOM, TIME_STRING_MAX, and UNSET_TRAP_OOM.
Referenced by CSensor_cellpos::PositionerEventL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1