ContextLogger2 Logger Daemon Internals: epoc-event-internal.cpp File Reference
epoc-event-internal.cpp File Reference
Defines
#define ACTIVE_SCHEDULER_TYPE CActiveSchedulerG
Functions
EXTERN_C int AoScheduler_install (MAYBE_ERROR_SOLE_PARAM)
EXTERN_C void AoScheduler_uninstall ()
EXTERN_C int AoScheduler_replace (MAYBE_ERROR_SOLE_PARAM)
EXTERN_C AoLoop * AoLoop_new ()
EXTERN_C void AoLoop_delete (AoLoop *asw)
EXTERN_C void AoLoop_start (AoLoop *asw)
EXTERN_C void AoLoop_stop (AoLoop *asw)
Define Documentation
#define ACTIVE_SCHEDULER_TYPE CActiveSchedulerG
Definition at line 11 of file epoc-event-internal.cpp.
Referenced by AoScheduler_install(), and AoScheduler_replace().
Function Documentation
EXTERN_C void AoLoop_delete (AoLoop * asw)
Definition at line 61 of file epoc-event-internal.cpp.
EXTERN_C AoLoop* AoLoop_new ()
Definition at line 56 of file epoc-event-internal.cpp.
EXTERN_C void AoLoop_start (AoLoop * asw)
Definition at line 66 of file epoc-event-internal.cpp.
EXTERN_C void AoLoop_stop (AoLoop * asw)
Definition at line 71 of file epoc-event-internal.cpp.
EXTERN_C int AoScheduler_install (MAYBE_ERROR_SOLE_PARAM)
Definition at line 16 of file epoc-event-internal.cpp.
References ACTIVE_SCHEDULER_TYPE, and MAYBE_ERROR_SOLE_ARG.
Referenced by event_scheduler_install().
EXTERN_C int AoScheduler_replace (MAYBE_ERROR_SOLE_PARAM)
Definition at line 39 of file epoc-event-internal.cpp.
References ACTIVE_SCHEDULER_TYPE, and MAYBE_ERROR_SOLE_ARG.
Referenced by event_scheduler_replace().
EXTERN_C void AoScheduler_uninstall ()
Definition at line 29 of file epoc-event-internal.cpp.
Referenced by event_scheduler_uninstall().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1