ContextLogger2 Logger Daemon Internals: epoc-btprox.cpp File Reference
epoc-btprox.cpp File Reference
Defines
#define PRINT_ELEMENTS (__DO_LOGGING__ && 0)
#define SCAN_INTERVAL_SECS (10 * 60)
#define SWAP(t, x, y) { t _tmp = x; x = y; y = _tmp; }
#define free_item_action FreeElement(item, NULL); User::Leave(KErrNoMemory);
Functions
static void FreeElement (gpointer data, gpointer user_data)
static void FreeElements (GPtrArray *array)
static void FreeResult (GPtrArray *array)
static void ClearResult (GPtrArray *array)
static gint CmpString (const char *a, const char *b)
static gint CmpElement (gconstpointer a, gconstpointer b)
static gint cmpInt (int a, int b)
static gint g_ptr_array_cmp (GPtrArray *array0, GPtrArray *array1, GCompareFunc compareFunc)
static void SortResult (GPtrArray *array)
static gint CmpResults (GPtrArray *array0, GPtrArray *array1)
static void BtDevAddrToString (TDes8 &aString, const TBTDevAddr &addr)
Define Documentation
#define free_item_action FreeElement(item, NULL); User::Leave(KErrNoMemory);
Referenced by CSensor_btprox::HandleScanEventL().
#define PRINT_ELEMENTS (__DO_LOGGING__ && 0)
Definition at line 18 of file epoc-btprox.cpp.
#define SCAN_INTERVAL_SECS (10 * 60)
Definition at line 228 of file epoc-btprox.cpp.
Referenced by CSensor_btprox::RefreshBaseScanIntervalSecs().
#define SWAP (t, x, y) { t _tmp = x; x = y; y = _tmp; }
Definition at line 250 of file epoc-btprox.cpp.
Referenced by CSensor_btprox::BtDiscover(), exprCommute(), CSensor_music::HandleMediaL(), and sqlite3WhereBegin().
Function Documentation
static void BtDevAddrToString (TDes8 & aString, const TBTDevAddr & addr) [static]
Definition at line 277 of file epoc-btprox.cpp.
References _LIT8().
Referenced by CSensor_btprox::HandleScanEventL().
static void ClearResult (GPtrArray * array) [static]
Definition at line 57 of file epoc-btprox.cpp.
References FreeElements().
Referenced by CSensor_btprox::BtDiscover().
static gint CmpElement (gconstpointer a, gconstpointer b) [static]
Definition at line 71 of file epoc-btprox.cpp.
References CmpString().
Referenced by CmpResults(), and SortResult().
static gint cmpInt (int a, int b) [static]
Definition at line 79 of file epoc-btprox.cpp.
Referenced by g_ptr_array_cmp().
static gint CmpResults (GPtrArray * array0, GPtrArray * array1) [static]
Definition at line 105 of file epoc-btprox.cpp.
References CmpElement(), and g_ptr_array_cmp().
Referenced by CSensor_btprox::HandleScanEventL().
static gint CmpString (const char * a, const char * b) [static]
Definition at line 63 of file epoc-btprox.cpp.
Referenced by CmpElement().
static void FreeElement (gpointer data, gpointer user_data) [static]
Definition at line 35 of file epoc-btprox.cpp.
Referenced by FreeElements().
static void FreeElements (GPtrArray * array) [static]
Definition at line 44 of file epoc-btprox.cpp.
References FreeElement().
Referenced by ClearResult(), and FreeResult().
static void FreeResult (GPtrArray * array) [static]
Definition at line 49 of file epoc-btprox.cpp.
References FreeElements().
Referenced by CSensor_btprox::~CSensor_btprox().
static gint g_ptr_array_cmp (GPtrArray * array0, GPtrArray * array1, GCompareFunc compareFunc) [static]
Definition at line 89 of file epoc-btprox.cpp.
References cmpInt(), and MIN.
Referenced by CmpResults().
static void SortResult (GPtrArray * array) [static]
Definition at line 100 of file epoc-btprox.cpp.
References CmpElement().
Referenced by CSensor_btprox::HandleScanEventL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1