ContextLogger2 Logger Daemon Internals: epoc-smsevent.cpp File Reference
epoc-smsevent.cpp File Reference
Defines
#define iLogDb ac_LogDb(iAppContext)
Functions
static gchar * GetBodyL (CRichText &richText)
static gchar * GetBody (CRichText &richText)
Variables
CTOR_IMPL_CSensor_smsevent
Define Documentation
#define iLogDb ac_LogDb(iAppContext)
Definition at line 31 of file epoc-smsevent.cpp.
Function Documentation
static gchar* GetBody (CRichText & richText) [static]
Definition at line 85 of file epoc-smsevent.cpp.
References er_log_symbian, error(), and GetBodyL().
Referenced by CSensor_smsevent::LogEvent().
static gchar* GetBodyL (CRichText & richText) [static]
Definition at line 62 of file epoc-smsevent.cpp.
References er_fatal_oom.
Referenced by GetBody().
Variable Documentation
CTOR_IMPL_CSensor_smsevent
Definition at line 19 of file epoc-smsevent.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1