ContextLogger2 Logger Daemon Internals: epoc-cl2app-clientserver.hpp File Reference
epoc-cl2app-clientserver.hpp File Reference
Enumerations
enum TMyMessages {
ETickCountFresh, ETryEvalScript, EEvalGetResult, EEval,
EGetResultLength, EGetResult
}
Functions
_LIT (KMyServerName,"cl2daemon")
Variables
const TUid KServerUid3 = {0xE0000000}
Enumeration Type Documentation
enum TMyMessages
Enumerator:
ETickCountFresh
ETryEvalScript
EEvalGetResult
EEval
EGetResultLength
EGetResult
Definition at line 17 of file epoc-cl2app-clientserver.hpp.
Function Documentation
_LIT (KMyServerName , "cl2daemon")
Referenced by CCl2appAppUi::ConstructL(), CWatchdog::FindApp(), CWatchdog::FindAppByPattern(), GetNameFromContactItemL(), IsModemIapL(), LogSatelliteInfoL(), MagicFileExists(), CCl2appAppUi::Start(), CWatchdog::StartApp(), and CSensor_btprox::TryBtInitL().
Variable Documentation
const TUid KServerUid3 = {0xE0000000}
Definition at line 15 of file epoc-cl2app-clientserver.hpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1