ContextLogger2 Logger Daemon Internals: er_errors.c File Reference
er_errors.c File Reference
Defines
#define _er_log_impl(_errObj)
Functions
void er_fatal_quiet ()
void er_fatal ()
void er_fatal_msg (const char *msg)
void er_show_error_msg (const char *msg)
static void er_log_base (int opt, void *errObj, const char *func, const char *file, int line, const char *user_msg)
void _er_log_any (int opt, void *errObj, const char *func, const char *file, int line, const char *user_fmt,...)
void _er_log_int (int opt, int errObj, const char *func, const char *file, int line, const char *user_fmt,...)
void _er_log_gerror (int opt, GError *errObj, const char *func, const char *file, int line, const char *user_fmt,...)
void er_log_status_string (const char *log_msg)
void er_log_status_fmt (const char *user_fmt,...)
void gx_error_free (GError *error)
void gx_propagate_error (GError **dest, GError *src)
gchar * gx_error_to_string (GError *error)
void gx_txtlog_error (GError *error)
void gx_txtlog_error_free (GError *error)
void gx_txtlog_error_clear (GError **error)
gboolean gx_dblog_error_check (LogDb *logDb, GError *errorToLog, GError **error)
gboolean gx_dblog_error_free_check (LogDb *logDb, GError *errorToLog, GError **error)
gboolean gx_dblog_error_clear_check (LogDb *logDb, GError **errorToLog, GError **error)
void gx_dblog_fatal_error_free (LogDb *logDb, GError *errorToLog)
void gx_dblog_fatal_error_clear (LogDb *logDb, GError **errorToLog)
void gx_txtlog_fatal_error_free (GError *errorToLog)
void gx_txtlog_fatal_error_clear (GError **errorToLog)
void px_dblog_fatal_error (LogDb *logDb, int errCode)
void px_dblog_fatal_errno (LogDb *logDb)
void px_txtlog_fatal_error (int errCode)
void px_txtlog_fatal_errno ()
Define Documentation
#define _er_log_impl (_errObj)
Value:
{                 \
  char* user_msg = NULL;            \
  if (user_fmt) {             \
    SET_TRAP_OOM_FAIL();            \
    va_list argp;             \
    va_start(argp, user_fmt);           \
    g_vasprintf(&user_msg, user_fmt, argp);       \
    va_end(argp);             \
    UNSET_TRAP_OOM();             \
  }                 \
  er_log_base(opt, _errObj, func, file, line, user_msg);    \
  g_free(user_msg);             \
  return;               \
  WHEN_TRAP_OOM(fail:             \
    g_free(user_msg);         \
    er_log_base(er_NONE | er_OOM | opt, NULL,   \
          er_POSITION,        \
          "out of memory in _er_log_impl"));    \
}
Definition at line 145 of file er_errors.c.
Referenced by _er_log_any(), _er_log_gerror(), and _er_log_int().
Function Documentation
void _er_log_any (int opt, void * errObj, const char * func, const char * file, int line, const char * user_fmt, ...)
Definition at line 166 of file er_errors.c.
References _er_log_impl.
void _er_log_gerror (int opt, GError * errObj, const char * func, const char * file, int line, const char * user_fmt, ...)
Definition at line 180 of file er_errors.c.
References _er_log_impl.
void _er_log_int (int opt, int errObj, const char * func, const char * file, int line, const char * user_fmt, ...)
Definition at line 173 of file er_errors.c.
References _er_log_impl.
void er_fatal ()
Definition at line 15 of file er_errors.c.
References er_fatal_general.
Referenced by atpanic_txtlog_exit(), gx_dblog_fatal_error_clear(), gx_dblog_fatal_error_free(), gx_txtlog_fatal_error_clear(), gx_txtlog_fatal_error_free(), px_dblog_fatal_error(), and px_txtlog_fatal_error().
void er_fatal_msg (const char * msg)
Definition at line 20 of file er_errors.c.
References er_show_error_msg(), and EXIT_APPLICATION.
void er_fatal_quiet ()
Definition at line 10 of file er_errors.c.
References EXIT_APPLICATION.
Referenced by er_log_base(), and CBatteryObserver::HandleBattery().
static void er_log_base (int opt, void * errObj, const char * func, const char * file, int line, const char * user_msg) [static]
Definition at line 37 of file er_errors.c.
References ac_global_LogDb, er_FATAL, er_fatal_general, er_fatal_oom, er_fatal_quiet(), er_FREE, er_GERROR, er_NODB, er_NONE, er_OOM, er_POSIX, er_QUIET, er_SYMBIAN, error(), gx_error_free(), log_db_log_status_direct(), logg, logt, plat_error_strerror, SET_TRAP_OOM, and UNSET_TRAP_OOM.
void er_log_status_fmt (const char * user_fmt, ...)
Definition at line 204 of file er_errors.c.
References er_log_oom, er_log_status_string(), SET_TRAP_OOM_FAIL, UNSET_TRAP_OOM, and WHEN_TRAP_OOM.
void er_log_status_string (const char * log_msg)
Definition at line 191 of file er_errors.c.
References ac_global_LogDb, er_fatal_general, log_db_log_status_direct(), and logt.
Referenced by er_log_status_fmt().
void er_show_error_msg (const char * msg)
Definition at line 26 of file er_errors.c.
References logt, UNLESS_SYMBIAN, and WHEN_SYMBIAN.
Referenced by er_fatal_msg().
gboolean gx_dblog_error_check (LogDb * logDb, GError * errorToLog, GError ** error)
Definition at line 294 of file er_errors.c.
References gx_error_to_string(), and log_db_log_status_direct().
Referenced by gx_dblog_error_free_check().
gboolean gx_dblog_error_clear_check (LogDb * logDb, GError ** errorToLog, GError ** error)
Definition at line 322 of file er_errors.c.
References gx_dblog_error_free_check().
gboolean gx_dblog_error_free_check (LogDb * logDb, GError * errorToLog, GError ** error)
Definition at line 314 of file er_errors.c.
References gx_dblog_error_check(), and gx_error_free().
Referenced by gx_dblog_error_clear_check(), and CUploader::RefreshSnapshotTimeExpr().
void gx_dblog_fatal_error_clear (LogDb * logDb, GError ** errorToLog)
Definition at line 339 of file er_errors.c.
References er_fatal(), and gx_dblog_error_clear.
Referenced by CActiveLogErrG::RunError(), and CSensor_keypress::RunL().
void gx_dblog_fatal_error_free (LogDb * logDb, GError * errorToLog)
Definition at line 332 of file er_errors.c.
References er_fatal(), and gx_dblog_error_free.
Referenced by CSensor_profile::HandleProfileActivatedL(), and timerCallback().
void gx_error_free (GError * error)
Definition at line 230 of file er_errors.c.
Referenced by er_log_base(), gx_dblog_error_free_check(), gx_propagate_error(), CActiveLogErrG::Leave(), CUploader::RefreshSnapshotTimeExpr(), showFreeGerror(), CActiveLogErrG::~CActiveLogErrG(), and GException::~GException().
gchar* gx_error_to_string (GError * error)
Definition at line 246 of file er_errors.c.
References TRAP_OOM_FAIL.
Referenced by gx_dblog_error_check(), gx_txtlog_error(), lua_raise_gerror(), and showFreeGerror().
void gx_propagate_error (GError ** dest, GError * src)
Definition at line 236 of file er_errors.c.
References gx_error_free().
Referenced by get_lua_value_wd().
void gx_txtlog_error (GError * error)
Definition at line 265 of file er_errors.c.
References gx_error_to_string(), and logt.
Referenced by gx_txtlog_error_free().
void gx_txtlog_error_clear (GError ** error)
Definition at line 286 of file er_errors.c.
References gx_txtlog_error_free().
Referenced by cl2GlobalInit(), cl2RunOnceGetExitCode(), and gx_txtlog_fatal_error_clear().
void gx_txtlog_error_free (GError * error)
Definition at line 280 of file er_errors.c.
References gx_txtlog_error().
Referenced by gx_txtlog_error_clear(), gx_txtlog_fatal_error_free(), main(), CUploader::PosterEvent(), CUploader::SetSnapshotTimerL(), and CCl2appAppUi::Start().
void gx_txtlog_fatal_error_clear (GError ** errorToLog)
Definition at line 352 of file er_errors.c.
References er_fatal(), and gx_txtlog_error_clear().
void gx_txtlog_fatal_error_free (GError * errorToLog)
Definition at line 346 of file er_errors.c.
References er_fatal(), and gx_txtlog_error_free().
Referenced by CSensor_callstatus::ChangedData_CallStatus(), CSensor_smsevent::handle_close(), CSensor_smsevent::handle_error(), CSensor_indicator::HandleRead(), CSensor_smsevent::LogEvent(), CSensor_inactivity::RunL(), and timerCallback().
void px_dblog_fatal_errno (LogDb * logDb)
Definition at line 368 of file er_errors.c.
References px_dblog_fatal_error().
Referenced by CSensor_keypress::RunL().
void px_dblog_fatal_error (LogDb * logDb, int errCode)
Definition at line 362 of file er_errors.c.
References er_fatal(), and log_db_log_status().
Referenced by px_dblog_fatal_errno().
void px_txtlog_fatal_errno ()
Definition at line 379 of file er_errors.c.
References px_txtlog_fatal_error().
void px_txtlog_fatal_error (int errCode)
Definition at line 373 of file er_errors.c.
References er_fatal(), and logg.
Referenced by px_txtlog_fatal_errno().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1