ContextLogger2 Logger Daemon Internals: er_errors.h File Reference
er_errors.h File Reference
Defines
#define er_fatal_general er_fatal_msg("Fatal error (CL2 exited)")
#define er_fatal_oom er_fatal_msg("Out of memory (CL2 exited)")
#define er_fatal_battery_low er_fatal_msg("Battery low (CL2 exited)")
#define er_fatal_disk_low er_fatal_msg("Disk low (CL2 exited)")
#define er_fatal_disk_not_ready er_fatal_msg("Disk not ready (CL2 exited)")
#define er_NONE (1<< 0)
#define er_POSIX (1<< 1)
#define er_SYMBIAN (1<< 2)
#define er_GERROR (1<< 3)
#define er_FATAL (1<< 8)
#define er_FREE (1<< 9)
#define er_NODB (1<<10)
#define er_OOM (1<<11)
#define er_QUIET (1<<12)
#define er_POSITION __func__, __FILE__, __LINE__
#define er_log_int_(opt, err, fmt...) _er_log_int(opt, err, __func__, __FILE__, __LINE__, fmt)
#define er_log_any_(opt, err, fmt...) _er_log_any(opt, err, __func__, __FILE__, __LINE__, fmt)
#define er_log_none(opt, fmt...) er_log_any_((opt) | er_NONE, NULL, fmt)
#define er_log_posix(opt, val, fmt...) er_log_int_((opt) | er_POSIX, val, fmt)
#define er_log_errno(opt, fmt...) er_log_int_((opt) | er_POSIX, errno, fmt)
#define er_log_symbian(opt, val, fmt...) er_log_int_((opt) | er_SYMBIAN, val, fmt)
#define er_log_gerror(opt, val, fmt...) _er_log_gerror((opt) | er_GERROR, val, __func__, __FILE__, __LINE__, fmt)
#define er_log_oom er_log_none(er_OOM, "out of memory error")
#define er_log_oom_on_false(x) if (!(x)) { er_log_oom; }
#define dblogt(s) er_log_status_string(s)
#define dblogg(f...) er_log_status_fmt(f)
#define gx_dblog_error(_db, _err) gx_dblog_error_check(_db, _err, NULL)
#define gx_dblog_error_free(_db, _err) gx_dblog_error_free_check(_db, _err, NULL)
#define gx_dblog_error_clear(_db, _err) gx_dblog_error_clear_check(_db, _err, NULL)
#define new_not_found_error gx_error_new(domain_cl2app, code_not_found, "not found")
#define is_not_found_error(_errorptr) gx_error_is(_errorptr, domain_cl2app, code_not_found)
Functions
void er_fatal_quiet ()
void er_fatal ()
void er_fatal_msg (const char *msg)
void er_show_error_msg (const char *text)
void _er_log_any (int opt, void *errObj, const char *func, const char *file, int line, const char *user_fmt,...)
void _er_log_int (int opt, int errObj, const char *func, const char *file, int line, const char *user_fmt,...)
void _er_log_gerror (int opt, GError *errObj, const char *func, const char *file, int line, const char *user_fmt,...)
void er_log_status_string (const char *s)
void er_log_status_fmt (const char *fmt,...)
gchar * gx_error_to_string (GError *error)
void gx_error_free (GError *error)
void gx_txtlog_error (GError *error)
void gx_txtlog_error_free (GError *error)
void gx_txtlog_error_clear (GError **error)
gboolean gx_dblog_error_check (LogDb *logDb, GError *errorToLog, GError **error)
gboolean gx_dblog_error_free_check (LogDb *logDb, GError *errorToLog, GError **error)
gboolean gx_dblog_error_clear_check (LogDb *logDb, GError **errorToLog, GError **error)
void gx_dblog_fatal_error_free (LogDb *logDb, GError *errorToLog)
void gx_dblog_fatal_error_clear (LogDb *logDb, GError **errorToLog)
void gx_propagate_error (GError **dest, GError *src)
void gx_txtlog_fatal_error_free (GError *errorToLog)
void gx_txtlog_fatal_error_clear (GError **errorToLog)
void px_dblog_fatal_error (LogDb *logDb, int errCode)
void px_dblog_fatal_errno (LogDb *logDb)
void px_txtlog_fatal_error (int errCode)
void px_txtlog_fatal_errno ()
Define Documentation
#define dblogg (f...) er_log_status_fmt(f)
Definition at line 106 of file er_errors.h.
Referenced by CPosModuleStatAo::ChooseBestPositionerL(), CUploader::CreatePosterAoL(), CSensor_btprox::EnsureBtInit(), CUploader::HandleCommsError(), CSensor_profile::HandleProfileActivatedL(), CSensor_indicator::HandleRead(), CSensor_btprox::HandleScanEventL(), CUploader::PosterEvent(), CUploader::postingFinished(), CUploader::PostNowL(), CSensor_btprox::RefreshBaseScanIntervalSecs(), CUploader::SetPostRetryTimer(), and CUploader::SetPostTimer().
#define dblogt (s) er_log_status_string(s)
Definition at line 105 of file er_errors.h.
Referenced by CUploader::NextOldFileL(), CUploader::SetSnapshotTimerL(), and CUploader::TakeSnapshotNowL().
#define er_FATAL (1<< 8)
Definition at line 53 of file er_errors.h.
Referenced by CMainObj::AppContextReady(), CCl2appAppUi::AppContextReady(), atpanic_log_exit(), CUploader::CUploader(), er_log_base(), CUploader::FatalError(), CFlightModeObserver::HandleFlightMode(), MImmediateObserver::HandleImmediateError(), MImmediateObserver::HandleImmediateLeave(), CSensor_indicator::HandleTimer(), QAbsTimer::HandleTimerEvent(), log_text_to_db(), CUploader::NextOldFileL(), CSensor_cellpos::PositionerEventL(), CSensor_cellpos::PosModLeave(), CUploader::PosterEvent(), CSensor_cellid::PostNewData(), CObserverAo_NetworkInfo::RetryTimerExpired(), CObserverAo_SignalStrength::RetryTimerExpired(), CSensor_cellpos::RetryTimerExpired(), CUploader::TakeSnapshotNowL(), and TimeNow().
#define er_fatal_battery_low er_fatal_msg("Battery low (CL2 exited)")
Definition at line 42 of file er_errors.h.
Referenced by CBatteryObserver::HandleBattery().
#define er_fatal_disk_low er_fatal_msg("Disk low (CL2 exited)")
Definition at line 43 of file er_errors.h.
Referenced by CDiskObserver::DiskSpaceNotify().
#define er_fatal_disk_not_ready er_fatal_msg("Disk not ready (CL2 exited)")
Definition at line 44 of file er_errors.h.
Referenced by CDiskObserver::DiskSpaceNotify().
#define er_fatal_general er_fatal_msg("Fatal error (CL2 exited)")
Definition at line 40 of file er_errors.h.
Referenced by er_fatal(), er_log_base(), er_log_status_string(), and log_db_take_snapshot().
#define er_fatal_oom er_fatal_msg("Out of memory (CL2 exited)")
Definition at line 41 of file er_errors.h.
Referenced by er_log_base(), GetBodyL(), and CSensor_smsevent::LogEvent().
#define er_FREE (1<< 9)
Definition at line 54 of file er_errors.h.
Referenced by CMainObj::AppContextReady(), CCl2appAppUi::AppContextReady(), CUploader::CUploader(), er_log_base(), CUploader::NextOldFileL(), CSmsTrigger::RunL(), and CUploader::TakeSnapshotNowL().
#define er_GERROR (1<< 3)
Definition at line 50 of file er_errors.h.
Referenced by er_log_base().
#define er_log_any_ (opt, err, fmt...) _er_log_any(opt, err, __func__, __FILE__, __LINE__, fmt)
Definition at line 76 of file er_errors.h.
#define er_log_errno (opt, fmt...) er_log_int_((opt) | er_POSIX, errno, fmt)
Definition at line 84 of file er_errors.h.
Referenced by log_text_to_db(), CUploader::PosterEvent(), CUploader::TakeSnapshotNowL(), and TimeNow().
#define er_log_gerror (opt, val, fmt...) _er_log_gerror((opt) | er_GERROR, val, __func__, __FILE__, __LINE__, fmt)
Definition at line 88 of file er_errors.h.
Referenced by CMainObj::AppContextReady(), CCl2appAppUi::AppContextReady(), CUploader::CUploader(), CUploader::NextOldFileL(), CSmsTrigger::RunL(), and CUploader::TakeSnapshotNowL().
#define er_log_int_ (opt, err, fmt...) _er_log_int(opt, err, __func__, __FILE__, __LINE__, fmt)
Definition at line 72 of file er_errors.h.
#define er_log_none (opt, fmt...) er_log_any_((opt) | er_NONE, NULL, fmt)
Definition at line 80 of file er_errors.h.
Referenced by atpanic_log_exit(), CUploader::FatalError(), _rk_Remokon::gotJabberError(), CBatteryObserver::HandleBattery(), CUploader::PosterEvent(), and CUploader::postingFinished().
#define er_log_oom er_log_none(er_OOM, "out of memory error")
Definition at line 91 of file er_errors.h.
Referenced by er_log_status_fmt().
#define er_log_oom_on_false (x) if (!(x)) { er_log_oom; }
Definition at line 93 of file er_errors.h.
Referenced by kr_Controller_set_operator_name().
#define er_log_posix (opt, val, fmt...) er_log_int_((opt) | er_POSIX, val, fmt)
Definition at line 82 of file er_errors.h.
#define er_log_symbian (opt, val, fmt...) er_log_int_((opt) | er_SYMBIAN, val, fmt)
Definition at line 86 of file er_errors.h.
Referenced by CMainObj::AppContextReady(), CCl2appAppUi::AppContextReady(), CUploader::FatalError(), GetBody(), CBatteryObserver::HandleBattery(), CFlightModeObserver::HandleFlightMode(), MImmediateObserver::HandleImmediateError(), MImmediateObserver::HandleImmediateLeave(), CSensor_music::HandlePlaybackMessage(), CSensor_indicator::HandleTimer(), QAbsTimer::HandleTimerEvent(), CSensor_cellpos::PositionerEventL(), CSensor_cellpos::PosModChangeL(), CSensor_cellpos::PosModErrorL(), CSensor_cellpos::PosModLeave(), CSensor_cellid::PostNewData(), CObserverAo_NetworkInfo::RetryTimerExpired(), CObserverAo_SignalStrength::RetryTimerExpired(), CSensor_cellpos::RetryTimerExpired(), CSmsTrigger::RunError(), CSensor_httpurl::RunError(), and CSensor_httpurl::RunL().
#define er_NODB (1<<10)
Definition at line 55 of file er_errors.h.
Referenced by er_log_base().
#define er_NONE (1<< 0)
Definition at line 47 of file er_errors.h.
Referenced by er_log_base().
#define er_OOM (1<<11)
Definition at line 56 of file er_errors.h.
Referenced by er_log_base().
#define er_POSITION __func__, __FILE__, __LINE__
Definition at line 70 of file er_errors.h.
#define er_POSIX (1<< 1)
Definition at line 48 of file er_errors.h.
Referenced by er_log_base().
#define er_QUIET (1<<12)
Definition at line 57 of file er_errors.h.
Referenced by er_log_base().
#define er_SYMBIAN (1<< 2)
Definition at line 49 of file er_errors.h.
Referenced by er_log_base().
#define gx_dblog_error (_db, _err) gx_dblog_error_check(_db, _err, NULL)
Definition at line 135 of file er_errors.h.
#define gx_dblog_error_clear (_db, _err) gx_dblog_error_clear_check(_db, _err, NULL)
Definition at line 137 of file er_errors.h.
Referenced by gx_dblog_fatal_error_clear().
#define gx_dblog_error_free (_db, _err) gx_dblog_error_free_check(_db, _err, NULL)
Definition at line 136 of file er_errors.h.
Referenced by current_iap_is_cellular(), and gx_dblog_fatal_error_free().
#define is_not_found_error (_errorptr) gx_error_is(_errorptr, domain_cl2app, code_not_found)
Definition at line 201 of file er_errors.h.
Referenced by db_set(), f_config_get(), and get_lua_value_wd().
#define new_not_found_error gx_error_new(domain_cl2app, code_not_found, "not found")
Definition at line 198 of file er_errors.h.
Referenced by db_get().
Function Documentation
void _er_log_any (int opt, void * errObj, const char * func, const char * file, int line, const char * user_fmt, ...)
Definition at line 166 of file er_errors.c.
References _er_log_impl.
void _er_log_gerror (int opt, GError * errObj, const char * func, const char * file, int line, const char * user_fmt, ...)
Definition at line 180 of file er_errors.c.
References _er_log_impl.
void _er_log_int (int opt, int errObj, const char * func, const char * file, int line, const char * user_fmt, ...)
Definition at line 173 of file er_errors.c.
References _er_log_impl.
void er_fatal ()
Definition at line 15 of file er_errors.c.
References er_fatal_general.
Referenced by atpanic_txtlog_exit(), gx_dblog_fatal_error_clear(), gx_dblog_fatal_error_free(), gx_txtlog_fatal_error_clear(), gx_txtlog_fatal_error_free(), px_dblog_fatal_error(), and px_txtlog_fatal_error().
void er_fatal_msg (const char * msg)
Definition at line 20 of file er_errors.c.
References er_show_error_msg(), and EXIT_APPLICATION.
void er_fatal_quiet ()
Definition at line 10 of file er_errors.c.
References EXIT_APPLICATION.
Referenced by er_log_base(), and CBatteryObserver::HandleBattery().
void er_log_status_fmt (const char * fmt, ...)
Definition at line 204 of file er_errors.c.
References er_log_oom, er_log_status_string(), SET_TRAP_OOM_FAIL, UNSET_TRAP_OOM, and WHEN_TRAP_OOM.
void er_log_status_string (const char * s)
Definition at line 191 of file er_errors.c.
References ac_global_LogDb, er_fatal_general, log_db_log_status_direct(), and logt.
Referenced by er_log_status_fmt().
void er_show_error_msg (const char * text)
Definition at line 26 of file er_errors.c.
References logt, UNLESS_SYMBIAN, and WHEN_SYMBIAN.
Referenced by er_fatal_msg().
gboolean gx_dblog_error_check (LogDb * logDb, GError * errorToLog, GError ** error)
Definition at line 294 of file er_errors.c.
References gx_error_to_string(), and log_db_log_status_direct().
Referenced by gx_dblog_error_free_check().
gboolean gx_dblog_error_clear_check (LogDb * logDb, GError ** errorToLog, GError ** error)
Definition at line 322 of file er_errors.c.
References gx_dblog_error_free_check().
gboolean gx_dblog_error_free_check (LogDb * logDb, GError * errorToLog, GError ** error)
Definition at line 314 of file er_errors.c.
References gx_dblog_error_check(), and gx_error_free().
Referenced by gx_dblog_error_clear_check(), and CUploader::RefreshSnapshotTimeExpr().
void gx_dblog_fatal_error_clear (LogDb * logDb, GError ** errorToLog)
Definition at line 339 of file er_errors.c.
References er_fatal(), and gx_dblog_error_clear.
Referenced by CActiveLogErrG::RunError(), and CSensor_keypress::RunL().
void gx_dblog_fatal_error_free (LogDb * logDb, GError * errorToLog)
Definition at line 332 of file er_errors.c.
References er_fatal(), and gx_dblog_error_free.
Referenced by CSensor_profile::HandleProfileActivatedL(), and timerCallback().
void gx_error_free (GError * error)
Definition at line 230 of file er_errors.c.
Referenced by er_log_base(), gx_dblog_error_free_check(), gx_propagate_error(), CActiveLogErrG::Leave(), CUploader::RefreshSnapshotTimeExpr(), showFreeGerror(), CActiveLogErrG::~CActiveLogErrG(), and GException::~GException().
gchar* gx_error_to_string (GError * error)
Definition at line 246 of file er_errors.c.
References TRAP_OOM_FAIL.
Referenced by gx_dblog_error_check(), gx_txtlog_error(), lua_raise_gerror(), and showFreeGerror().
void gx_propagate_error (GError ** dest, GError * src)
Definition at line 236 of file er_errors.c.
References gx_error_free().
Referenced by get_lua_value_wd().
void gx_txtlog_error (GError * error)
Definition at line 265 of file er_errors.c.
References gx_error_to_string(), and logt.
Referenced by gx_txtlog_error_free().
void gx_txtlog_error_clear (GError ** error)
Definition at line 286 of file er_errors.c.
References gx_txtlog_error_free().
Referenced by cl2GlobalInit(), cl2RunOnceGetExitCode(), and gx_txtlog_fatal_error_clear().
void gx_txtlog_error_free (GError * error)
Definition at line 280 of file er_errors.c.
References gx_txtlog_error().
Referenced by gx_txtlog_error_clear(), gx_txtlog_fatal_error_free(), main(), CUploader::PosterEvent(), CUploader::SetSnapshotTimerL(), and CCl2appAppUi::Start().
void gx_txtlog_fatal_error_clear (GError ** errorToLog)
Definition at line 352 of file er_errors.c.
References er_fatal(), and gx_txtlog_error_clear().
void gx_txtlog_fatal_error_free (GError * errorToLog)
Definition at line 346 of file er_errors.c.
References er_fatal(), and gx_txtlog_error_free().
Referenced by CSensor_callstatus::ChangedData_CallStatus(), CSensor_smsevent::handle_close(), CSensor_smsevent::handle_error(), CSensor_indicator::HandleRead(), CSensor_smsevent::LogEvent(), CSensor_inactivity::RunL(), and timerCallback().
void px_dblog_fatal_errno (LogDb * logDb)
Definition at line 368 of file er_errors.c.
References px_dblog_fatal_error().
Referenced by CSensor_keypress::RunL().
void px_dblog_fatal_error (LogDb * logDb, int errCode)
Definition at line 362 of file er_errors.c.
References er_fatal(), and log_db_log_status().
Referenced by px_dblog_fatal_errno().
void px_txtlog_fatal_errno ()
Definition at line 379 of file er_errors.c.
References px_txtlog_fatal_error().
void px_txtlog_fatal_error (int errCode)
Definition at line 373 of file er_errors.c.
References er_fatal(), and logg.
Referenced by px_txtlog_fatal_errno().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1