ContextLogger2 Logger Daemon Internals: evq_event.h File Reference
evq_event.h File Reference
Classes
struct _Event
Defines
#define MAYBE_ERROR_RTYPE gboolean
#define MAYBE_ERROR_PARAM , GError** error
#define MAYBE_ERROR_SOLE_PARAM GError** error
#define MAYBE_ERROR_SOLE_ARG error
#define MAYBE_ERROR_INVOKE(func, args...) { if (!(func(args,error))) return FALSE; }
#define MAYBE_ERROR_RETURN return TRUE;
Typedefs
typedef struct _Event Event
typedef Queue EventQueue
Functions
void event_init (EventQueue *queue)
MAYBE_ERROR_RTYPE event_loop (EventQueue *queue MAYBE_ERROR_PARAM)
void event_put (EventQueue *queue, Event *event)
void event_remove (EventQueue *queue, Event *event)
void event_loop_stop (EventQueue *queue)
void event_close (EventQueue *queue)
void event_scheduler_install (MAYBE_ERROR_SOLE_PARAM)
void event_scheduler_uninstall ()
void event_scheduler_replace (MAYBE_ERROR_SOLE_PARAM)
Define Documentation
#define MAYBE_ERROR_INVOKE (func, args...) { if (!(func(args,error))) return FALSE; }
Definition at line 41 of file evq_event.h.
Referenced by event_cb().
#define MAYBE_ERROR_PARAM , GError** error
Definition at line 38 of file evq_event.h.
#define MAYBE_ERROR_RETURN return TRUE;
Definition at line 42 of file evq_event.h.
Referenced by event_cb().
#define MAYBE_ERROR_RTYPE gboolean
Definition at line 37 of file evq_event.h.
#define MAYBE_ERROR_SOLE_ARG error
Definition at line 40 of file evq_event.h.
Referenced by AoScheduler_install(), AoScheduler_replace(), event_scheduler_install(), and event_scheduler_replace().
#define MAYBE_ERROR_SOLE_PARAM GError** error
Definition at line 39 of file evq_event.h.
Typedef Documentation
typedef struct _Event Event
typedef Queue EventQueue
Definition at line 71 of file evq_event.h.
Function Documentation
void event_close (EventQueue * queue)
Definition at line 59 of file evq_event.c.
References queue_close().
void event_init (EventQueue * queue)
Definition at line 12 of file evq_event.c.
References queue_init().
MAYBE_ERROR_RTYPE event_loop (EventQueue *queue MAYBE_ERROR_PARAM)
void event_loop_stop (EventQueue * queue)
Definition at line 54 of file evq_event.c.
References queue_stop().
void event_put (EventQueue * queue, Event * event)
Definition at line 44 of file evq_event.c.
References queue_put().
Referenced by worker_task().
void event_remove (EventQueue * queue, Event * event)
Definition at line 49 of file evq_event.c.
References queue_remove().
Referenced by timer_cancel(), and timer_close().
void event_scheduler_install (MAYBE_ERROR_SOLE_PARAM)
Definition at line 141 of file evq_event.c.
References AoScheduler_install(), and MAYBE_ERROR_SOLE_ARG.
void event_scheduler_replace (MAYBE_ERROR_SOLE_PARAM)
Definition at line 158 of file evq_event.c.
References AoScheduler_replace(), and MAYBE_ERROR_SOLE_ARG.
void event_scheduler_uninstall ()
Definition at line 151 of file evq_event.c.
References AoScheduler_uninstall().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1