ContextLogger2 Logger Daemon Internals: evq_timer.h File Reference
evq_timer.h File Reference
Classes
struct Timer
Typedefs
typedef MAYBE_ERROR_RTYPE(TimerCallback)(int errCode, void *user_data MAYBE_ERROR_PARAM)
Functions
void timer_init (EventQueue *queue, Timer *timer)
void timer_at (Timer *timer, struct timespec *time, TimerCallback *callback, void *user_data)
void timer_cancel (Timer *timer)
void timer_close (Timer *timer)
Typedef Documentation
typedef MAYBE_ERROR_RTYPE(TimerCallback)(int errCode, void *user_data MAYBE_ERROR_PARAM)
Definition at line 12 of file evq_timer.h.
Function Documentation
void timer_at (Timer * timer, struct timespec * time, TimerCallback * callback, void * user_data)
Definition at line 60 of file evq_timer.c.
References Timer::active, Timer::callback, Timer::cond, Timer::mutex, Timer::time, and Timer::user_data.
void timer_cancel (Timer * timer)
Definition at line 72 of file evq_timer.c.
References Timer::active, Timer::cond, event_remove(), Timer::mutex, and Timer::queue.
Referenced by timer_close().
void timer_close (Timer * timer)
Definition at line 84 of file evq_timer.c.
References Timer::cond, event_remove(), Timer::mutex, Timer::queue, Timer::running, timer_cancel(), and Timer::worker.
void timer_init (EventQueue * queue, Timer * timer)
Definition at line 49 of file evq_timer.c.
References Timer::active, _Event::callback, Timer::cond, Timer::event, event_cb(), Timer::mutex, Timer::queue, Timer::running, Timer::worker, and worker_task().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1