ContextLogger2 Logger Daemon Internals: evq_event.c File Reference
evq_event.c File Reference
Functions
void event_init (EventQueue *queue)
gboolean event_loop (EventQueue *queue, GError **error)
void event_put (EventQueue *queue, Event *event)
void event_remove (EventQueue *queue, Event *event)
void event_loop_stop (EventQueue *queue)
void event_close (EventQueue *queue)
void event_scheduler_install (MAYBE_ERROR_SOLE_PARAM)
void event_scheduler_uninstall ()
void event_scheduler_replace (MAYBE_ERROR_SOLE_PARAM)
Function Documentation
void event_close (EventQueue * queue)
Definition at line 59 of file evq_event.c.
References queue_close().
void event_init (EventQueue * queue)
Definition at line 12 of file evq_event.c.
References queue_init().
gboolean event_loop (EventQueue * queue, GError ** error)
Definition at line 18 of file evq_event.c.
References _Event::callback, and queue_get().
void event_loop_stop (EventQueue * queue)
Definition at line 54 of file evq_event.c.
References queue_stop().
void event_put (EventQueue * queue, Event * event)
Definition at line 44 of file evq_event.c.
References queue_put().
Referenced by worker_task().
void event_remove (EventQueue * queue, Event * event)
Definition at line 49 of file evq_event.c.
References queue_remove().
Referenced by timer_cancel(), and timer_close().
void event_scheduler_install (MAYBE_ERROR_SOLE_PARAM)
Definition at line 141 of file evq_event.c.
References AoScheduler_install(), and MAYBE_ERROR_SOLE_ARG.
void event_scheduler_replace (MAYBE_ERROR_SOLE_PARAM)
Definition at line 158 of file evq_event.c.
References AoScheduler_replace(), and MAYBE_ERROR_SOLE_ARG.
void event_scheduler_uninstall ()
Definition at line 151 of file evq_event.c.
References AoScheduler_uninstall().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1