ContextLogger2 Logger Daemon Internals: evq_queue.h File Reference
evq_queue.h File Reference
Classes
struct __QueueItem
struct Queue
Typedefs
typedef struct __QueueItem QueueItem
Functions
void queue_init (Queue *q)
void queue_put (Queue *q, QueueItem *item)
void queue_remove (Queue *q, QueueItem *item)
QueueItem * queue_get (Queue *q)
void queue_stop (Queue *q)
void queue_close (Queue *q)
Typedef Documentation
typedef struct __QueueItem QueueItem
Function Documentation
void queue_close (Queue * q)
Definition at line 107 of file evq_queue.c.
References Queue::cond, cond_destroy, Queue::mutex, and mutex_destroy.
Referenced by event_close().
QueueItem* queue_get (Queue * q)
Definition at line 72 of file evq_queue.c.
References Queue::cond, cond_wait, Queue::head, _Event::item, Queue::mutex, mutex_lock, mutex_unlock, Queue::running, and unshift().
Referenced by event_loop().
void queue_init (Queue * q)
Definition at line 9 of file evq_queue.c.
References Queue::cond, cond_init, Queue::head, Queue::mutex, mutex_init, Queue::running, and Queue::tail.
Referenced by event_init().
void queue_put (Queue * q, QueueItem * item)
Definition at line 17 of file evq_queue.c.
References Queue::cond, cond_signal, Queue::head, Queue::mutex, mutex_lock, mutex_unlock, __QueueItem::next, Queue::running, and Queue::tail.
Referenced by event_put().
void queue_remove (Queue * q, QueueItem * item)
Definition at line 49 of file evq_queue.c.
References Queue::head, Queue::mutex, mutex_lock, mutex_unlock, __QueueItem::next, Queue::running, Queue::tail, and unshift().
Referenced by event_remove().
void queue_stop (Queue * q)
Definition at line 97 of file evq_queue.c.
References Queue::cond, cond_broadcast, Queue::mutex, mutex_lock, mutex_unlock, and Queue::running.
Referenced by event_loop_stop().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1