ContextLogger2 Logger Daemon Internals: fault.c File Reference
fault.c File Reference
Classes
struct BenignMallocHooks
Defines
#define wsdHooksInit
#define wsdHooks sqlite3Hooks
Typedefs
typedef struct BenignMallocHooks BenignMallocHooks
Functions
void sqlite3BenignMallocHooks (void(*xBenignBegin)(void), void(*xBenignEnd)(void))
void sqlite3BeginBenignMalloc (void)
void sqlite3EndBenignMalloc (void)
Variables
static SQLITE_WSD struct
BenignMallocHooks sqlite3Hooks
Define Documentation
#define wsdHooks sqlite3Hooks
Definition at line 56 of file fault.c.
Referenced by sqlite3BeginBenignMalloc(), sqlite3BenignMallocHooks(), and sqlite3EndBenignMalloc().
#define wsdHooksInit
Definition at line 55 of file fault.c.
Referenced by sqlite3BeginBenignMalloc(), sqlite3BenignMallocHooks(), and sqlite3EndBenignMalloc().
Typedef Documentation
typedef struct BenignMallocHooks BenignMallocHooks
Definition at line 38 of file fault.c.
Function Documentation
void sqlite3BeginBenignMalloc (void)
Definition at line 78 of file fault.c.
References wsdHooks, and wsdHooksInit.
Referenced by pagerUnlockAndRollback(), rehash(), setupLookaside(), sqlite3BitvecSet(), sqlite3PagerClose(), sqlite3RollbackAll(), sqlite3VdbeExec(), sqlite3VdbeReset(), and vdbeCommit().
void sqlite3BenignMallocHooks (void(*)(void) xBenignBegin, void(*)(void) xBenignEnd)
Definition at line 64 of file fault.c.
References wsdHooks, and wsdHooksInit.
Referenced by sqlite3_test_control().
void sqlite3EndBenignMalloc (void)
Definition at line 84 of file fault.c.
References wsdHooks, and wsdHooksInit.
Referenced by pagerUnlockAndRollback(), rehash(), setupLookaside(), sqlite3BitvecSet(), sqlite3PagerClose(), sqlite3RollbackAll(), sqlite3VdbeExec(), sqlite3VdbeReset(), and vdbeCommit().
Variable Documentation
SQLITE_WSD struct BenignMallocHooks sqlite3Hooks [static]
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1