ContextLogger2 Logger Daemon Internals: fts1_hash.c File Reference
fts1_hash.c File Reference
Functions
static void * malloc_and_zero (int n)
void sqlite3Fts1HashInit (fts1Hash *pNew, int keyClass, int copyKey)
void sqlite3Fts1HashClear (fts1Hash *pH)
static int strHash (const void *pKey, int nKey)
static int strCompare (const void *pKey1, int n1, const void *pKey2, int n2)
static int binHash (const void *pKey, int nKey)
static int binCompare (const void *pKey1, int n1, const void *pKey2, int n2)
static int(*)(const void *, int) hashFunction (int keyClass)
static int(*)(const void
*, int, const void *, int) compareFunction (int keyClass)
static void insertElement (fts1Hash *pH, struct _fts1ht *pEntry, fts1HashElem *pNew)
static void rehash (fts1Hash *pH, int new_size)
static fts1HashElem * findElementGivenHash (const fts1Hash *pH, const void *pKey, int nKey, int h)
static void removeElementGivenHash (fts1Hash *pH, fts1HashElem *elem, int h)
void * sqlite3Fts1HashFind (const fts1Hash *pH, const void *pKey, int nKey)
void * sqlite3Fts1HashInsert (fts1Hash *pH, const void *pKey, int nKey, void *data)
Function Documentation
static int binCompare (const void * pKey1, int n1, const void * pKey2, int n2) [static]
Definition at line 118 of file fts1_hash.c.
Referenced by compareFunction().
static int binHash (const void * pKey, int nKey) [static]
Definition at line 110 of file fts1_hash.c.
Referenced by hashFunction().
static int(*)(const void*, int, const void*, int) compareFunction (int keyClass) [static]
Definition at line 150 of file fts1_hash.c.
References binCompare(), FTS1_HASH_BINARY, FTS1_HASH_STRING, and strCompare().
Referenced by findElementGivenHash().
static fts1HashElem* findElementGivenHash (const fts1Hash * pH, const void * pKey, int nKey, int h) [static]
Definition at line 212 of file fts1_hash.c.
References compareFunction(), fts1Hash::ht, fts1Hash::keyClass, fts1HashElem::next, fts1HashElem::nKey, and fts1HashElem::pKey.
Referenced by sqlite3Fts1HashFind(), and sqlite3Fts1HashInsert().
static int(*)(const void*, int) hashFunction (int keyClass) [static]
Definition at line 135 of file fts1_hash.c.
References binHash(), FTS1_HASH_BINARY, FTS1_HASH_STRING, and strHash().
Referenced by rehash(), sqlite3Fts1HashFind(), and sqlite3Fts1HashInsert().
static void insertElement (fts1Hash * pH, struct _fts1ht * pEntry, fts1HashElem * pNew) [static]
Definition at line 161 of file fts1_hash.c.
References fts1Hash::first, fts1HashElem::next, and fts1HashElem::prev.
Referenced by rehash(), and sqlite3Fts1HashInsert().
static void* malloc_and_zero (int n) [static]
Definition at line 34 of file fts1_hash.c.
Referenced by sqlite3Fts1HashInit().
static void rehash (fts1Hash * pH, int new_size) [static]
Definition at line 189 of file fts1_hash.c.
References fts1Hash::first, hashFunction(), fts1Hash::ht, fts1Hash::htsize, insertElement(), fts1Hash::keyClass, fts1HashElem::next, fts1HashElem::nKey, fts1HashElem::pKey, fts1Hash::xFree, and fts1Hash::xMalloc.
Referenced by sqlite3Fts1HashInsert().
static void removeElementGivenHash (fts1Hash * pH, fts1HashElem * elem, int h) [static]
Definition at line 240 of file fts1_hash.c.
References fts1Hash::_fts1ht::chain, fts1Hash::copyKey, fts1Hash::count, fts1Hash::first, fts1HashClear, fts1Hash::ht, fts1HashElem::next, fts1HashElem::pKey, fts1HashElem::prev, and fts1Hash::xFree.
Referenced by sqlite3Fts1HashInsert().
void sqlite3Fts1HashClear (fts1Hash * pH)
Definition at line 69 of file fts1_hash.c.
References fts1Hash::copyKey, fts1Hash::count, fts1Hash::first, fts1Hash::ht, fts1Hash::htsize, fts1HashElem::next, fts1HashElem::pKey, and fts1Hash::xFree.
void* sqlite3Fts1HashFind (const fts1Hash * pH, const void * pKey, int nKey)
Definition at line 278 of file fts1_hash.c.
References fts1HashElem::data, findElementGivenHash(), hashFunction(), fts1Hash::ht, fts1Hash::htsize, and fts1Hash::keyClass.
void sqlite3Fts1HashInit (fts1Hash * pNew, int keyClass, int copyKey)
Definition at line 52 of file fts1_hash.c.
References fts1Hash::copyKey, fts1Hash::count, fts1Hash::first, FTS1_HASH_BINARY, FTS1_HASH_STRING, fts1Hash::ht, fts1Hash::htsize, fts1Hash::keyClass, malloc_and_zero(), fts1Hash::xFree, and fts1Hash::xMalloc.
void* sqlite3Fts1HashInsert (fts1Hash * pH, const void * pKey, int nKey, void * data)
Definition at line 307 of file fts1_hash.c.
References fts1Hash::copyKey, fts1Hash::count, fts1HashElem::data, findElementGivenHash(), hashFunction(), fts1Hash::ht, fts1Hash::htsize, insertElement(), fts1Hash::keyClass, fts1HashElem::nKey, fts1HashElem::pKey, rehash(), removeElementGivenHash(), fts1Hash::xFree, and fts1Hash::xMalloc.
static int strCompare (const void * pKey1, int n1, const void * pKey2, int n2) [static]
Definition at line 102 of file fts1_hash.c.
Referenced by compareFunction().
static int strHash (const void * pKey, int nKey) [static]
Definition at line 92 of file fts1_hash.c.
Referenced by hashFunction().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1