ContextLogger2 Logger Daemon Internals: fts2_tokenizer.c File Reference
fts2_tokenizer.c File Reference
Functions
static SQLITE_EXTENSION_INIT1 void scalarFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
int sqlite3Fts2InitHashTable (sqlite3 *db, fts2Hash *pHash, const char *zName)
Function Documentation
static SQLITE_EXTENSION_INIT1 void scalarFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 57 of file fts2_tokenizer.c.
References sqlite3_free(), sqlite3_mprintf(), sqlite3_result_blob(), sqlite3_result_error(), sqlite3_user_data(), sqlite3_value_blob(), sqlite3_value_bytes(), sqlite3_value_text(), sqlite3Fts2HashFind(), sqlite3Fts2HashInsert(), and SQLITE_TRANSIENT.
Referenced by sqlite3Fts2InitHashTable().
int sqlite3Fts2InitHashTable (sqlite3 * db, fts2Hash * pHash, const char * zName)
Definition at line 336 of file fts2_tokenizer.c.
References scalarFunc(), sqlite3_create_function(), sqlite3_free(), sqlite3_mprintf(), SQLITE_ANY, SQLITE_NOMEM, and SQLITE_OK.
Referenced by sqlite3Fts2Init().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1