ContextLogger2 Logger Daemon Internals: fts2.h File Reference
fts2.h File Reference
Functions
int sqlite3Fts2Init (sqlite3 *db)
Function Documentation
int sqlite3Fts2Init (sqlite3 * db)
Definition at line 6789 of file fts2.c.
References FTS2_HASH_STRING, hashDestroy(), sqlite3_create_module_v2(), sqlite3_free(), sqlite3_malloc(), sqlite3_overload_function(), sqlite3Fts2HashClear(), sqlite3Fts2HashInit(), sqlite3Fts2HashInsert(), sqlite3Fts2IcuTokenizerModule(), sqlite3Fts2InitHashTable(), sqlite3Fts2PorterTokenizerModule(), sqlite3Fts2SimpleTokenizerModule(), SQLITE_NOMEM, and SQLITE_OK.
Referenced by openDatabase(), and sqlite3_extension_init().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1