ContextLogger2 Logger Daemon Internals: fts2_hash.h File Reference
fts2_hash.h File Reference
Classes
struct fts2Hash
struct fts2Hash::_fts2ht
struct fts2HashElem
Defines
#define FTS2_HASH_STRING 1
#define FTS2_HASH_BINARY 2
#define fts2HashInit sqlite3Fts2HashInit
#define fts2HashInsert sqlite3Fts2HashInsert
#define fts2HashFind sqlite3Fts2HashFind
#define fts2HashClear sqlite3Fts2HashClear
#define fts2HashFirst(H) ((H)->first)
#define fts2HashNext(E) ((E)->next)
#define fts2HashData(E) ((E)->data)
#define fts2HashKey(E) ((E)->pKey)
#define fts2HashKeysize(E) ((E)->nKey)
#define fts2HashCount(H) ((H)->count)
Typedefs
typedef struct fts2Hash fts2Hash
typedef struct fts2HashElem fts2HashElem
Functions
void sqlite3Fts2HashInit (fts2Hash *, int keytype, int copyKey)
void * sqlite3Fts2HashInsert (fts2Hash *, const void *pKey, int nKey, void *pData)
void * sqlite3Fts2HashFind (const fts2Hash *, const void *pKey, int nKey)
void sqlite3Fts2HashClear (fts2Hash *)
Define Documentation
#define FTS2_HASH_BINARY 2
Definition at line 69 of file fts2_hash.h.
Referenced by compareFunction(), hashFunction(), and sqlite3Fts2HashInit().
#define FTS2_HASH_STRING 1
Definition at line 68 of file fts2_hash.h.
Referenced by compareFunction(), hashFunction(), initPendingTerms(), sqlite3Fts2HashInit(), and sqlite3Fts2Init().
#define fts2HashClear sqlite3Fts2HashClear
Definition at line 85 of file fts2_hash.h.
Referenced by clearPendingTerms(), and removeElementGivenHash().
#define fts2HashCount (H) ((H)->count)
Definition at line 108 of file fts2_hash.h.
Referenced by writeZeroSegment().
#define fts2HashData (E) ((E)->data)
Definition at line 101 of file fts2_hash.h.
Referenced by clearPendingTerms(), and writeZeroSegment().
#define fts2HashFind sqlite3Fts2HashFind
Definition at line 84 of file fts2_hash.h.
Referenced by buildTerms().
#define fts2HashFirst (H) ((H)->first)
Definition at line 99 of file fts2_hash.h.
Referenced by clearPendingTerms(), and writeZeroSegment().
#define fts2HashInit sqlite3Fts2HashInit
Definition at line 82 of file fts2_hash.h.
Referenced by initPendingTerms().
#define fts2HashInsert sqlite3Fts2HashInsert
Definition at line 83 of file fts2_hash.h.
Referenced by buildTerms().
#define fts2HashKey (E) ((E)->pKey)
Definition at line 102 of file fts2_hash.h.
Referenced by writeZeroSegment().
#define fts2HashKeysize (E) ((E)->nKey)
Definition at line 103 of file fts2_hash.h.
Referenced by writeZeroSegment().
#define fts2HashNext (E) ((E)->next)
Definition at line 100 of file fts2_hash.h.
Referenced by clearPendingTerms(), and writeZeroSegment().
Typedef Documentation
typedef struct fts2Hash fts2Hash
Definition at line 21 of file fts2_hash.h.
typedef struct fts2HashElem fts2HashElem
Definition at line 22 of file fts2_hash.h.
Function Documentation
void sqlite3Fts2HashClear (fts2Hash *)
Definition at line 74 of file fts2_hash.c.
References fts2Hash::copyKey, fts2Hash::count, fts2Hash::first, fts2HashFree(), fts2Hash::ht, fts2Hash::htsize, fts2HashElem::next, and fts2HashElem::pKey.
Referenced by hashDestroy(), and sqlite3Fts2Init().
void* sqlite3Fts2HashFind (const fts2Hash * , const void * pKey, int nKey)
Definition at line 283 of file fts2_hash.c.
References fts2HashElem::data, findElementGivenHash(), hashFunction(), fts2Hash::ht, fts2Hash::htsize, and fts2Hash::keyClass.
Referenced by constructVtab(), and scalarFunc().
void sqlite3Fts2HashInit (fts2Hash * , int keytype, int copyKey)
Definition at line 59 of file fts2_hash.c.
References fts2Hash::copyKey, fts2Hash::count, fts2Hash::first, FTS2_HASH_BINARY, FTS2_HASH_STRING, fts2Hash::ht, fts2Hash::htsize, and fts2Hash::keyClass.
Referenced by sqlite3Fts2Init().
void* sqlite3Fts2HashInsert (fts2Hash * , const void * pKey, int nKey, void * pData)
Definition at line 312 of file fts2_hash.c.
References fts2Hash::copyKey, fts2Hash::count, fts2HashElem::data, findElementGivenHash(), fts2HashFree(), fts2HashMalloc(), hashFunction(), fts2Hash::ht, fts2Hash::htsize, insertElement(), fts2Hash::keyClass, fts2HashElem::nKey, fts2HashElem::pKey, rehash(), and removeElementGivenHash().
Referenced by scalarFunc(), and sqlite3Fts2Init().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1