ContextLogger2 Logger Daemon Internals: fts3_hash.c File Reference
fts3_hash.c File Reference
Functions
static void * fts3HashMalloc (int n)
static void fts3HashFree (void *p)
void sqlite3Fts3HashInit (fts3Hash *pNew, int keyClass, int copyKey)
void sqlite3Fts3HashClear (fts3Hash *pH)
static int fts3StrHash (const void *pKey, int nKey)
static int fts3StrCompare (const void *pKey1, int n1, const void *pKey2, int n2)
static int fts3BinHash (const void *pKey, int nKey)
static int fts3BinCompare (const void *pKey1, int n1, const void *pKey2, int n2)
static int(*)(const void *, int) ftsHashFunction (int keyClass)
static int(*)(const void
*, int, const void *, int) ftsCompareFunction (int keyClass)
static void fts3HashInsertElement (fts3Hash *pH, struct _fts3ht *pEntry, fts3HashElem *pNew)
static void fts3Rehash (fts3Hash *pH, int new_size)
static fts3HashElem * fts3FindElementByHash (const fts3Hash *pH, const void *pKey, int nKey, int h)
static void fts3RemoveElementByHash (fts3Hash *pH, fts3HashElem *elem, int h)
void * sqlite3Fts3HashFind (const fts3Hash *pH, const void *pKey, int nKey)
void * sqlite3Fts3HashInsert (fts3Hash *pH, const void *pKey, int nKey, void *data)
Function Documentation
static int fts3BinCompare (const void * pKey1, int n1, const void * pKey2, int n2) [static]
Definition at line 123 of file fts3_hash.c.
Referenced by ftsCompareFunction().
static int fts3BinHash (const void * pKey, int nKey) [static]
Definition at line 115 of file fts3_hash.c.
Referenced by ftsHashFunction().
static fts3HashElem* fts3FindElementByHash (const fts3Hash * pH, const void * pKey, int nKey, int h) [static]
Definition at line 217 of file fts3_hash.c.
References ftsCompareFunction(), fts3Hash::ht, fts3Hash::keyClass, fts3HashElem::next, fts3HashElem::nKey, and fts3HashElem::pKey.
Referenced by sqlite3Fts3HashFind(), and sqlite3Fts3HashInsert().
static void fts3HashFree (void * p) [static]
Definition at line 45 of file fts3_hash.c.
References sqlite3_free().
Referenced by fts3Rehash(), fts3RemoveElementByHash(), sqlite3Fts3HashClear(), and sqlite3Fts3HashInsert().
static void fts3HashInsertElement (fts3Hash * pH, struct _fts3ht * pEntry, fts3HashElem * pNew) [static]
Definition at line 166 of file fts3_hash.c.
References fts3Hash::first, fts3HashElem::next, and fts3HashElem::prev.
Referenced by fts3Rehash(), and sqlite3Fts3HashInsert().
static void* fts3HashMalloc (int n) [static]
Definition at line 38 of file fts3_hash.c.
References sqlite3_malloc().
Referenced by fts3Rehash(), and sqlite3Fts3HashInsert().
static void fts3Rehash (fts3Hash * pH, int new_size) [static]
Definition at line 194 of file fts3_hash.c.
References fts3Hash::first, fts3HashFree(), fts3HashInsertElement(), fts3HashMalloc(), ftsHashFunction(), fts3Hash::ht, fts3Hash::htsize, fts3Hash::keyClass, fts3HashElem::next, fts3HashElem::nKey, and fts3HashElem::pKey.
Referenced by sqlite3Fts3HashInsert().
static void fts3RemoveElementByHash (fts3Hash * pH, fts3HashElem * elem, int h) [static]
Definition at line 245 of file fts3_hash.c.
References fts3Hash::_fts3ht::chain, fts3Hash::copyKey, fts3Hash::count, fts3Hash::first, fts3HashClear, fts3HashFree(), fts3Hash::ht, fts3HashElem::next, fts3HashElem::pKey, and fts3HashElem::prev.
Referenced by sqlite3Fts3HashInsert().
static int fts3StrCompare (const void * pKey1, int n1, const void * pKey2, int n2) [static]
Definition at line 107 of file fts3_hash.c.
Referenced by ftsCompareFunction().
static int fts3StrHash (const void * pKey, int nKey) [static]
Definition at line 97 of file fts3_hash.c.
Referenced by ftsHashFunction().
static int(*)(const void*, int, const void*, int) ftsCompareFunction (int keyClass) [static]
Definition at line 155 of file fts3_hash.c.
References FTS3_HASH_BINARY, FTS3_HASH_STRING, fts3BinCompare(), and fts3StrCompare().
Referenced by fts3FindElementByHash().
static int(*)(const void*, int) ftsHashFunction (int keyClass) [static]
Definition at line 140 of file fts3_hash.c.
References FTS3_HASH_BINARY, FTS3_HASH_STRING, fts3BinHash(), and fts3StrHash().
Referenced by fts3Rehash(), sqlite3Fts3HashFind(), and sqlite3Fts3HashInsert().
void sqlite3Fts3HashClear (fts3Hash * pH)
Definition at line 74 of file fts3_hash.c.
References fts3Hash::copyKey, fts3Hash::count, fts3Hash::first, fts3HashFree(), fts3Hash::ht, fts3Hash::htsize, fts3HashElem::next, and fts3HashElem::pKey.
Referenced by hashDestroy(), and sqlite3Fts3Init().
void* sqlite3Fts3HashFind (const fts3Hash * pH, const void * pKey, int nKey)
Definition at line 283 of file fts3_hash.c.
References fts3HashElem::data, fts3FindElementByHash(), ftsHashFunction(), fts3Hash::ht, fts3Hash::htsize, and fts3Hash::keyClass.
Referenced by constructVtab(), and scalarFunc().
void sqlite3Fts3HashInit (fts3Hash * pNew, int keyClass, int copyKey)
Definition at line 59 of file fts3_hash.c.
References fts3Hash::copyKey, fts3Hash::count, fts3Hash::first, FTS3_HASH_BINARY, FTS3_HASH_STRING, fts3Hash::ht, fts3Hash::htsize, and fts3Hash::keyClass.
Referenced by sqlite3Fts3Init().
void* sqlite3Fts3HashInsert (fts3Hash * pH, const void * pKey, int nKey, void * data)
Definition at line 312 of file fts3_hash.c.
References fts3Hash::copyKey, fts3Hash::count, fts3HashElem::data, fts3FindElementByHash(), fts3HashFree(), fts3HashInsertElement(), fts3HashMalloc(), fts3Rehash(), fts3RemoveElementByHash(), ftsHashFunction(), fts3Hash::ht, fts3Hash::htsize, fts3Hash::keyClass, fts3HashElem::nKey, and fts3HashElem::pKey.
Referenced by scalarFunc(), and sqlite3Fts3Init().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1