ContextLogger2 Logger Daemon Internals: fts3_hash.h File Reference
fts3_hash.h File Reference
Classes
struct fts3Hash
struct fts3Hash::_fts3ht
struct fts3HashElem
Defines
#define FTS3_HASH_STRING 1
#define FTS3_HASH_BINARY 2
#define fts3HashInit sqlite3Fts3HashInit
#define fts3HashInsert sqlite3Fts3HashInsert
#define fts3HashFind sqlite3Fts3HashFind
#define fts3HashClear sqlite3Fts3HashClear
#define fts3HashFirst(H) ((H)->first)
#define fts3HashNext(E) ((E)->next)
#define fts3HashData(E) ((E)->data)
#define fts3HashKey(E) ((E)->pKey)
#define fts3HashKeysize(E) ((E)->nKey)
#define fts3HashCount(H) ((H)->count)
Typedefs
typedef struct fts3Hash fts3Hash
typedef struct fts3HashElem fts3HashElem
Functions
void sqlite3Fts3HashInit (fts3Hash *, int keytype, int copyKey)
void * sqlite3Fts3HashInsert (fts3Hash *, const void *pKey, int nKey, void *pData)
void * sqlite3Fts3HashFind (const fts3Hash *, const void *pKey, int nKey)
void sqlite3Fts3HashClear (fts3Hash *)
Define Documentation
#define FTS3_HASH_BINARY 2
Definition at line 69 of file fts3_hash.h.
Referenced by ftsCompareFunction(), ftsHashFunction(), and sqlite3Fts3HashInit().
#define FTS3_HASH_STRING 1
Definition at line 68 of file fts3_hash.h.
Referenced by ftsCompareFunction(), ftsHashFunction(), initPendingTerms(), sqlite3Fts3HashInit(), and sqlite3Fts3Init().
#define fts3HashClear sqlite3Fts3HashClear
Definition at line 85 of file fts3_hash.h.
Referenced by clearPendingTerms(), and fts3RemoveElementByHash().
#define fts3HashCount (H) ((H)->count)
Definition at line 108 of file fts3_hash.h.
Referenced by writeZeroSegment().
#define fts3HashData (E) ((E)->data)
Definition at line 101 of file fts3_hash.h.
Referenced by clearPendingTerms(), and writeZeroSegment().
#define fts3HashFind sqlite3Fts3HashFind
Definition at line 84 of file fts3_hash.h.
Referenced by buildTerms().
#define fts3HashFirst (H) ((H)->first)
Definition at line 99 of file fts3_hash.h.
Referenced by clearPendingTerms(), and writeZeroSegment().
#define fts3HashInit sqlite3Fts3HashInit
Definition at line 82 of file fts3_hash.h.
Referenced by initPendingTerms().
#define fts3HashInsert sqlite3Fts3HashInsert
Definition at line 83 of file fts3_hash.h.
Referenced by buildTerms().
#define fts3HashKey (E) ((E)->pKey)
Definition at line 102 of file fts3_hash.h.
Referenced by writeZeroSegment().
#define fts3HashKeysize (E) ((E)->nKey)
Definition at line 103 of file fts3_hash.h.
Referenced by writeZeroSegment().
#define fts3HashNext (E) ((E)->next)
Definition at line 100 of file fts3_hash.h.
Referenced by clearPendingTerms(), and writeZeroSegment().
Typedef Documentation
typedef struct fts3Hash fts3Hash
Definition at line 21 of file fts3_hash.h.
typedef struct fts3HashElem fts3HashElem
Definition at line 22 of file fts3_hash.h.
Function Documentation
void sqlite3Fts3HashClear (fts3Hash *)
Definition at line 74 of file fts3_hash.c.
References fts3Hash::copyKey, fts3Hash::count, fts3Hash::first, fts3HashFree(), fts3Hash::ht, fts3Hash::htsize, fts3HashElem::next, and fts3HashElem::pKey.
Referenced by hashDestroy(), and sqlite3Fts3Init().
void* sqlite3Fts3HashFind (const fts3Hash * , const void * pKey, int nKey)
Definition at line 283 of file fts3_hash.c.
References fts3HashElem::data, fts3FindElementByHash(), ftsHashFunction(), fts3Hash::ht, fts3Hash::htsize, and fts3Hash::keyClass.
Referenced by constructVtab(), and scalarFunc().
void sqlite3Fts3HashInit (fts3Hash * , int keytype, int copyKey)
Definition at line 59 of file fts3_hash.c.
References fts3Hash::copyKey, fts3Hash::count, fts3Hash::first, FTS3_HASH_BINARY, FTS3_HASH_STRING, fts3Hash::ht, fts3Hash::htsize, and fts3Hash::keyClass.
Referenced by sqlite3Fts3Init().
void* sqlite3Fts3HashInsert (fts3Hash * , const void * pKey, int nKey, void * pData)
Definition at line 312 of file fts3_hash.c.
References fts3Hash::copyKey, fts3Hash::count, fts3HashElem::data, fts3FindElementByHash(), fts3HashFree(), fts3HashInsertElement(), fts3HashMalloc(), fts3Rehash(), fts3RemoveElementByHash(), ftsHashFunction(), fts3Hash::ht, fts3Hash::htsize, fts3Hash::keyClass, fts3HashElem::nKey, and fts3HashElem::pKey.
Referenced by scalarFunc(), and sqlite3Fts3Init().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1