ContextLogger2 Logger Daemon Internals: guilog.h File Reference
guilog.h File Reference
Functions
void guilogf (const char *fmt,...)
Function Documentation
void guilogf (const char * fmt, ...)
Definition at line 49 of file window_demo_qt.cpp.
References guilog().
Referenced by CSensor_cellpos::BbChangedL(), CSensor_btprox::BtDiscover(), CSensor_callstatus::ChangedData_CallStatus(), CPosModuleStatAo::ChooseBestPositionerL(), CSensor_music::HandleMediaL(), CSensor_music::HandlePlaybackMessage(), CSensor_profile::HandleProfileActivatedL(), CSensor_indicator::HandleRead(), Sensor_tap::handleReadingChanged(), Sensor_proximity::handleReadingChanged(), Sensor_light::handleReadingChanged(), CSensor_btprox::HandleScanEventL(), CSensor_smsevent::LogEvent(), LogSatelliteInfoL(), main(), CSensor_cellpos::PositionerEventL(), CSensor_cellid::PostNewDataL(), QtMainE(), CSensor_appfocus::RunGL(), CSensor_inactivity::RunL(), and CSensor_httpurl::RunL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1