ContextLogger2 Logger Daemon Internals: gx_maybe_string.h File Reference
gx_maybe_string.h File Reference
Classes
struct GMaybeString
Functions
void GMaybeString_init (GMaybeString *m)
const gchar * GMaybeString_get (GMaybeString *m)
gboolean GMaybeString_assign (GMaybeString *m, const gchar *rval, GError **error)
gboolean GMaybeString_is_nothing (GMaybeString *m)
gboolean GMaybeString_is (GMaybeString *m, const gchar *other)
void GMaybeString_free (GMaybeString *m)
Function Documentation
gboolean GMaybeString_assign (GMaybeString * m, const gchar * rval, GError ** error)
Definition at line 38 of file gx_maybe_string.c.
References gx_error_no_memory, GMaybeString::just, SET_TRAP_OOM, UNSET_TRAP_OOM, and GMaybeString::value.
Referenced by kr_Controller_set_operator_name().
void GMaybeString_free (GMaybeString * m)
Definition at line 60 of file gx_maybe_string.c.
References GMaybeString::just, and GMaybeString::value.
Referenced by free_uploads_allowed_state().
const gchar* GMaybeString_get (GMaybeString * m)
Definition at line 14 of file gx_maybe_string.c.
References GMaybeString::just, and GMaybeString::value.
Referenced by GMaybeString_is(), and GMaybeString_is_nothing().
void GMaybeString_init (GMaybeString * m)
Definition at line 8 of file gx_maybe_string.c.
References GMaybeString::just, and GMaybeString::value.
Referenced by init_uploads_allowed_state().
gboolean GMaybeString_is (GMaybeString * m, const gchar * other)
Definition at line 26 of file gx_maybe_string.c.
References GMaybeString_get().
Referenced by kr_Controller_set_operator_name(), recompute_netpos_allowed(), and recompute_uploads_allowed().
gboolean GMaybeString_is_nothing (GMaybeString * m)
Definition at line 21 of file gx_maybe_string.c.
References GMaybeString_get().
Referenced by recompute_netpos_allowed(), and recompute_uploads_allowed().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1