ContextLogger2 Logger Daemon Internals: gxerror.c File Reference
gxerror.c File Reference
Functions
GError * gx_error_new_valist (GQuark domain, gint code, const gchar *format, va_list args)
GError * gx_error_new (GQuark domain, gint code, const gchar *format,...)
GError * gx_error_new_literal (GQuark domain, gint code, const gchar *message)
Function Documentation
GError* gx_error_new (GQuark domain, gint code, const gchar * format, ...)
Definition at line 71 of file gxerror.c.
References error(), and gx_error_new_valist().
Referenced by code_means_no_error(), compress_file(), compress_ft(), create_database(), CUploader::CreatePosterAoL(), epoc_iap_by_name(), epoc_iap_is_modem(), get_bool_from_lua(), get_int_from_lua(), kr_PlatAo_new(), LocalServer_start(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_db_open_session(), log_db_take_snapshot(), mkdir_p(), open_config_db_session(), prepare_sql_statements(), rk_Remokon_send(), rm_file(), CSensor_btprox::RunGL(), sa_Array_sensor_start(), try_get_ConfigDb_str(), up_Uploader_new(), validate_lua_syntax(), and zerr().
GError* gx_error_new_literal (GQuark domain, gint code, const gchar * message)
Definition at line 90 of file gxerror.c.
References SET_TRAP_OOM_VALUE, and UNSET_TRAP_OOM.
Referenced by lua_get_gerror().
GError* gx_error_new_valist (GQuark domain, gint code, const gchar * format, va_list args)
Definition at line 44 of file gxerror.c.
References error(), SET_TRAP_OOM_FAIL, and UNSET_TRAP_OOM.
Referenced by gx_error_new().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1