ContextLogger2 Logger Daemon Internals: hash.h File Reference
hash.h File Reference
Classes
struct Hash
struct Hash::_ht
struct HashElem
Defines
#define sqliteHashFirst(H) ((H)->first)
#define sqliteHashNext(E) ((E)->next)
#define sqliteHashData(E) ((E)->data)
#define sqliteHashKey(E) ((E)->pKey)
#define sqliteHashKeysize(E) ((E)->nKey)
#define sqliteHashCount(H) ((H)->count)
Typedefs
typedef struct Hash Hash
typedef struct HashElem HashElem
Functions
void sqlite3HashInit (Hash *, int copyKey)
void * sqlite3HashInsert (Hash *, const void *pKey, int nKey, void *pData)
void * sqlite3HashFind (const Hash *, const void *pKey, int nKey)
HashElem * sqlite3HashFindElem (const Hash *, const void *pKey, int nKey)
void sqlite3HashClear (Hash *)
Define Documentation
#define sqliteHashCount (H) ((H)->count)
Definition at line 85 of file hash.h.
#define sqliteHashData (E) ((E)->data)
Definition at line 78 of file hash.h.
Referenced by analyzeDatabase(), reindexDatabases(), sqlite3_close(), sqlite3AnalysisLoad(), sqlite3Pragma(), sqlite3RootPageMoved(), sqlite3SchemaFree(), and sqliteViewResetAll().
#define sqliteHashFirst (H) ((H)->first)
Definition at line 76 of file hash.h.
Referenced by analyzeDatabase(), reindexDatabases(), sqlite3_close(), sqlite3AnalysisLoad(), sqlite3Pragma(), sqlite3RootPageMoved(), sqlite3SchemaFree(), and sqliteViewResetAll().
#define sqliteHashKey (E) ((E)->pKey)
Definition at line 79 of file hash.h.
#define sqliteHashKeysize (E) ((E)->nKey)
Definition at line 80 of file hash.h.
#define sqliteHashNext (E) ((E)->next)
Definition at line 77 of file hash.h.
Referenced by analyzeDatabase(), reindexDatabases(), sqlite3_close(), sqlite3AnalysisLoad(), sqlite3Pragma(), sqlite3RootPageMoved(), sqlite3SchemaFree(), and sqliteViewResetAll().
Typedef Documentation
typedef struct Hash Hash
Definition at line 21 of file hash.h.
typedef struct HashElem HashElem
Definition at line 22 of file hash.h.
Function Documentation
void sqlite3HashClear (Hash *)
Definition at line 40 of file hash.c.
References Hash::copyKey, Hash::count, Hash::first, Hash::ht, Hash::htsize, HashElem::next, HashElem::pKey, and sqlite3_free().
Referenced by removeElementGivenHash(), sqlite3_close(), and sqlite3SchemaFree().
void* sqlite3HashFind (const Hash * , const void * pKey, int nKey)
Definition at line 223 of file hash.c.
References HashElem::data, and sqlite3HashFindElem().
Referenced by createCollation(), findCollSeqEntry(), sqlite3BeginTrigger(), sqlite3DeleteTable(), sqlite3DropTrigger(), sqlite3EndTable(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3FinishTrigger(), sqlite3UnlinkAndDeleteTable(), sqlite3VtabFinishParse(), and tableOfTrigger().
HashElem* sqlite3HashFindElem (const Hash * , const void * pKey, int nKey)
Definition at line 209 of file hash.c.
References findElementGivenHash(), Hash::ht, Hash::htsize, and strHash().
Referenced by sqlite3HashFind().
void sqlite3HashInit (Hash * , int copyKey)
Definition at line 27 of file hash.c.
References Hash::copyKey, Hash::count, Hash::first, Hash::ht, and Hash::htsize.
Referenced by openDatabase(), sqlite3SchemaFree(), and sqlite3SchemaGet().
void* sqlite3HashInsert (Hash * , const void * pKey, int nKey, void * pData)
Definition at line 244 of file hash.c.
References Hash::copyKey, Hash::count, HashElem::data, findElementGivenHash(), Hash::ht, Hash::htsize, insertElement(), HashElem::nKey, HashElem::pKey, rehash(), removeElementGivenHash(), sqlite3_free(), sqlite3Malloc(), and strHash().
Referenced by createModule(), findCollSeqEntry(), sqlite3CreateIndex(), sqlite3EndTable(), sqlite3FinishTrigger(), sqlite3UnlinkAndDeleteIndex(), sqlite3UnlinkAndDeleteTable(), sqlite3UnlinkAndDeleteTrigger(), sqlite3VtabFinishParse(), and sqliteDeleteIndex().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1