ContextLogger2 Logger Daemon Internals: icu.c File Reference
icu.c File Reference
Defines
#define SQLITE_MAX_LIKE_PATTERN_LENGTH 50000
Functions
static void xFree (void *p)
static int icuLikeCompare (const uint8_t *zPattern, const uint8_t *zString, const UChar32 uEsc)
static void icuLikeFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void icuFunctionError (sqlite3_context *pCtx, const char *zName, UErrorCode e)
static void icuRegexpDelete (void *p)
static void icuRegexpFunc (sqlite3_context *p, int nArg, sqlite3_value **apArg)
static void icuCaseFunc16 (sqlite3_context *p, int nArg, sqlite3_value **apArg)
static void icuCollationDel (void *pCtx)
static int icuCollationColl (void *pCtx, int nLeft, const void *zLeft, int nRight, const void *zRight)
static void icuLoadCollation (sqlite3_context *p, int nArg, sqlite3_value **apArg)
int sqlite3IcuInit (sqlite3 *db)
int sqlite3_extension_init (sqlite3 *db, char **pzErrMsg, const sqlite3_api_routines *pApi)
Define Documentation
#define SQLITE_MAX_LIKE_PATTERN_LENGTH 50000
Definition at line 53 of file icu.c.
Referenced by icuLikeFunc().
Function Documentation
static void icuCaseFunc16 (sqlite3_context * p, int nArg, sqlite3_value ** apArg) [static]
Definition at line 325 of file icu.c.
References icuFunctionError(), sqlite3_malloc(), sqlite3_result_text16(), sqlite3_user_data(), sqlite3_value_bytes16(), sqlite3_value_text(), sqlite3_value_text16(), and xFree().
Referenced by sqlite3IcuInit().
static int icuCollationColl (void * pCtx, int nLeft, const void * zLeft, int nRight, const void * zRight) [static]
Definition at line 378 of file icu.c.
Referenced by icuLoadCollation().
static void icuCollationDel (void * pCtx) [static]
Definition at line 369 of file icu.c.
Referenced by icuLoadCollation().
static void icuFunctionError (sqlite3_context * pCtx, const char * zName, UErrorCode e) [static]
Definition at line 205 of file icu.c.
References sqlite3_result_error(), and sqlite3_snprintf().
Referenced by icuCaseFunc16(), icuLoadCollation(), and icuRegexpFunc().
static int icuLikeCompare (const uint8_t * zPattern, const uint8_t * zString, const UChar32 uEsc) [static]
Definition at line 68 of file icu.c.
Referenced by icuLikeFunc().
static void icuLikeFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 159 of file icu.c.
References icuLikeCompare(), sqlite3_result_error(), sqlite3_result_int(), sqlite3_value_bytes(), sqlite3_value_text(), and SQLITE_MAX_LIKE_PATTERN_LENGTH.
Referenced by sqlite3IcuInit().
static void icuLoadCollation (sqlite3_context * p, int nArg, sqlite3_value ** apArg) [static]
Definition at line 410 of file icu.c.
References db, icuCollationColl(), icuCollationDel(), icuFunctionError(), sqlite3_create_collation_v2(), sqlite3_result_error(), sqlite3_user_data(), sqlite3_value_text(), SQLITE_OK, and SQLITE_UTF16.
Referenced by sqlite3IcuInit().
static void icuRegexpDelete (void * p) [static]
Definition at line 220 of file icu.c.
Referenced by icuRegexpFunc().
static void icuRegexpFunc (sqlite3_context * p, int nArg, sqlite3_value ** apArg) [static]
Definition at line 244 of file icu.c.
References icuFunctionError(), icuRegexpDelete(), sqlite3_get_auxdata(), sqlite3_result_int(), sqlite3_set_auxdata(), and sqlite3_value_text16().
Referenced by sqlite3IcuInit().
int sqlite3_extension_init (sqlite3 * db, char ** pzErrMsg, const sqlite3_api_routines * pApi)
Definition at line 489 of file icu.c.
References sqlite3IcuInit(), and SQLITE_EXTENSION_INIT2.
int sqlite3IcuInit (sqlite3 * db)
Definition at line 449 of file icu.c.
References icuCaseFunc16(), icuLikeFunc(), icuLoadCollation(), icuRegexpFunc(), sqlite3_create_function(), SQLITE_ANY, SQLITE_OK, SQLITE_UTF16, and SQLITE_UTF8.
Referenced by openDatabase(), and sqlite3_extension_init().
static void xFree (void * p) [static]
Definition at line 59 of file icu.c.
References sqlite3_free().
Referenced by icuCaseFunc16(), and sqlite3BtreeSchema().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1