ContextLogger2 Logger Daemon Internals: interval_parser.c File Reference
interval_parser.c File Reference
Classes
struct time_range_t
struct tm_range_t
Defines
#define this_domain (this_quark())
#define CLEAR_RANGE(range) {(range).b = 0; (range).e = 0;}
#define CAND_RANGE_TO_TIME_T
#define SEEN_DATE_TO_TM(rec)
#define SEEN_TIME_TO_TM(rec)
#define DUR_IN_SECS ((durHour * 60 + durMin) * 60)
Enumerations
enum { code_parse_error = 1, code_incomplete_input }
Functions
static GQuark this_quark ()
static int zero_or_max (int x, int y)
static gboolean is_never (const time_range_t *r)
static void time_range_copy (time_range_t *dest, const time_range_t *src)
static gboolean time_range_overlap (const time_range_t *r1, const time_range_t *r2)
static void time_range_union (time_range_t *dest, const time_range_t *src)
gboolean parse_interval (const char *s, time_t ctx, time_t now, time_t *beg, time_t *end, GError **error)
Variables
static const char _fsm_actions []
static const short _fsm_key_offsets []
static const char _fsm_trans_keys []
static const char _fsm_single_lengths []
static const char _fsm_range_lengths []
static const short _fsm_index_offsets []
static const short _fsm_indicies []
static const short _fsm_trans_targs_wi []
static const short _fsm_trans_actions_wi []
static const int fsm_start = 1
static const int fsm_first_final = 2921
static const int fsm_error = 0
static const int fsm_en_main = 1
Define Documentation
#define CAND_RANGE_TO_TIME_T
Value:
cand.b = timegm(&cand_tm.b); \
  cand.e = timegm(&cand_tm.e);
Definition at line 74 of file interval_parser.c.
Referenced by parse_interval().
#define CLEAR_RANGE (range) {(range).b = 0; (range).e = 0;}
Definition at line 31 of file interval_parser.c.
Referenced by parse_interval().
#define DUR_IN_SECS ((durHour * 60 + durMin) * 60)
Definition at line 88 of file interval_parser.c.
Referenced by parse_interval().
#define SEEN_DATE_TO_TM (rec)
Value:
(rec).tm_year = seenYear; \
  (rec).tm_mon = seenMonth; \
  (rec).tm_mday = seenDay;
Definition at line 78 of file interval_parser.c.
Referenced by parse_interval().
#define SEEN_TIME_TO_TM (rec)
Value:
(rec).tm_hour = seenHour; \
  (rec).tm_min = seenMin; \
  (rec).tm_sec = seenSec;
Definition at line 83 of file interval_parser.c.
Referenced by parse_interval().
#define this_domain (this_quark())
Definition at line 14 of file interval_parser.c.
Referenced by parse_interval(), and parse_moment().
Enumeration Type Documentation
anonymous enum
Enumerator:
code_parse_error
code_incomplete_input
Definition at line 16 of file interval_parser.c.
Function Documentation
static gboolean is_never (const time_range_t * r) [static]
Definition at line 40 of file interval_parser.c.
References time_range_t::b, and time_range_t::e.
Referenced by parse_interval().
gboolean parse_interval (const char * s, time_t ctx, time_t now, time_t * beg, time_t * end, GError ** error)
Definition at line 4351 of file interval_parser.c.
References _fsm_actions, _fsm_index_offsets, _fsm_indicies, _fsm_key_offsets, _fsm_range_lengths, _fsm_single_lengths, _fsm_trans_actions_wi, _fsm_trans_keys, _fsm_trans_targs_wi, ATOI_RANGE, tm_range_t::b, time_range_t::b, CAND_RANGE_TO_TIME_T, CLEAR_RANGE, code_incomplete_input, code_parse_error, DUR_IN_SECS, tm_range_t::e, time_range_t::e, fsm_error, fsm_first_final, fsm_start, is_never(), num_days_till_next_wday(), SEEN_DATE_TO_TM, SEEN_TIME_T, SEEN_TIME_TO_TM, seenDay, seenHour, seenMin, seenMonth, seenSec, seenYear, SET_SEEN_DATE_PLUS_DAYS, SET_TODAY_TO_TM, this_domain, time_range_copy(), time_range_overlap(), and time_range_union().
Referenced by rb_parse_interval().
static GQuark this_quark () [static]
Definition at line 9 of file interval_parser.c.
static void time_range_copy (time_range_t * dest, const time_range_t * src) [static]
Definition at line 45 of file interval_parser.c.
Referenced by parse_interval().
static gboolean time_range_overlap (const time_range_t * r1, const time_range_t * r2) [static]
Definition at line 50 of file interval_parser.c.
References time_range_t::b, and time_range_t::e.
Referenced by parse_interval().
static void time_range_union (time_range_t * dest, const time_range_t * src) [static]
Definition at line 68 of file interval_parser.c.
References time_range_t::b, time_range_t::e, MIN, and zero_or_max().
Referenced by parse_interval().
static int zero_or_max (int x, int y) [static]
Definition at line 33 of file interval_parser.c.
References MAX.
Referenced by time_range_union().
Variable Documentation
const char _fsm_actions[] [static]
Definition at line 95 of file interval_parser.c.
Referenced by parse_interval().
const short _fsm_index_offsets[] [static]
Definition at line 2055 of file interval_parser.c.
Referenced by parse_interval().
const short _fsm_indicies[] [static]
Definition at line 2424 of file interval_parser.c.
Referenced by parse_interval().
const short _fsm_key_offsets[] [static]
Definition at line 162 of file interval_parser.c.
Referenced by parse_interval().
const char _fsm_range_lengths[] [static]
Definition at line 1686 of file interval_parser.c.
Referenced by parse_interval().
const char _fsm_single_lengths[] [static]
Definition at line 1317 of file interval_parser.c.
Referenced by parse_interval().
const short _fsm_trans_actions_wi[] [static]
Definition at line 3887 of file interval_parser.c.
Referenced by parse_interval().
const char _fsm_trans_keys[] [static]
Definition at line 531 of file interval_parser.c.
Referenced by parse_interval().
const short _fsm_trans_targs_wi[] [static]
Definition at line 3439 of file interval_parser.c.
Referenced by parse_interval().
const int fsm_en_main = 1 [static]
Definition at line 4339 of file interval_parser.c.
const int fsm_error = 0 [static]
Definition at line 4337 of file interval_parser.c.
Referenced by parse_interval().
const int fsm_first_final = 2921 [static]
Definition at line 4336 of file interval_parser.c.
Referenced by parse_interval().
const int fsm_start = 1 [static]
Definition at line 4335 of file interval_parser.c.
Referenced by parse_interval().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1