ContextLogger2 Logger Daemon Internals: interval_parser.h File Reference
interval_parser.h File Reference
Functions
gboolean parse_interval (const char *s, time_t ctx, time_t now, time_t *beg, time_t *end, GError **error)
Function Documentation
gboolean parse_interval (const char * s, time_t ctx, time_t now, time_t * beg, time_t * end, GError ** error)
Definition at line 4351 of file interval_parser.c.
References _fsm_actions, _fsm_index_offsets, _fsm_indicies, _fsm_key_offsets, _fsm_range_lengths, _fsm_single_lengths, _fsm_trans_actions_wi, _fsm_trans_keys, _fsm_trans_targs_wi, ATOI_RANGE, tm_range_t::b, time_range_t::b, CAND_RANGE_TO_TIME_T, CLEAR_RANGE, code_incomplete_input, code_parse_error, DUR_IN_SECS, tm_range_t::e, time_range_t::e, fsm_error, fsm_first_final, fsm_start, is_never(), num_days_till_next_wday(), SEEN_DATE_TO_TM, SEEN_TIME_T, SEEN_TIME_TO_TM, seenDay, seenHour, seenMin, seenMonth, seenSec, seenYear, SET_SEEN_DATE_PLUS_DAYS, SET_TODAY_TO_TM, this_domain, time_range_copy(), time_range_overlap(), and time_range_union().
Referenced by rb_parse_interval().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1