ContextLogger2 Logger Daemon Internals: keywordhash.h File Reference
keywordhash.h File Reference
Functions
static int keywordCode (const char *z, int n)
int sqlite3KeywordCode (const unsigned char *z, int n)
Function Documentation
static int keywordCode (const char * z, int n) [static]
Definition at line 15 of file keywordhash.h.
References charMap, sqlite3StrNICmp(), TK_ABORT, TK_ADD, TK_AFTER, TK_ALL, TK_ALTER, TK_ANALYZE, TK_AND, TK_AS, TK_ASC, TK_ATTACH, TK_AUTOINCR, TK_BEFORE, TK_BEGIN, TK_BETWEEN, TK_BY, TK_CASCADE, TK_CASE, TK_CAST, TK_CHECK, TK_COLLATE, TK_COLUMNKW, TK_COMMIT, TK_CONFLICT, TK_CONSTRAINT, TK_CREATE, TK_CTIME_KW, TK_DATABASE, TK_DEFAULT, TK_DEFERRABLE, TK_DEFERRED, TK_DELETE, TK_DESC, TK_DETACH, TK_DISTINCT, TK_DROP, TK_EACH, TK_ELSE, TK_END, TK_ESCAPE, TK_EXCEPT, TK_EXCLUSIVE, TK_EXISTS, TK_EXPLAIN, TK_FAIL, TK_FOR, TK_FOREIGN, TK_FROM, TK_GROUP, TK_HAVING, TK_ID, TK_IF, TK_IGNORE, TK_IMMEDIATE, TK_IN, TK_INDEX, TK_INDEXED, TK_INITIALLY, TK_INSERT, TK_INSTEAD, TK_INTERSECT, TK_INTO, TK_IS, TK_ISNULL, TK_JOIN, TK_JOIN_KW, TK_KEY, TK_LIKE_KW, TK_LIMIT, TK_MATCH, TK_NOT, TK_NOTNULL, TK_NULL, TK_OF, TK_OFFSET, TK_ON, TK_OR, TK_ORDER, TK_PLAN, TK_PRAGMA, TK_PRIMARY, TK_QUERY, TK_RAISE, TK_REFERENCES, TK_REINDEX, TK_RENAME, TK_REPLACE, TK_RESTRICT, TK_ROLLBACK, TK_ROW, TK_SELECT, TK_SET, TK_TABLE, TK_TEMP, TK_THEN, TK_TO, TK_TRANSACTION, TK_TRIGGER, TK_UNION, TK_UNIQUE, TK_UPDATE, TK_USING, TK_VACUUM, TK_VALUES, TK_VIEW, TK_VIRTUAL, TK_WHEN, and TK_WHERE.
Referenced by sqlite3GetToken(), and sqlite3KeywordCode().
int sqlite3KeywordCode (const unsigned char * z, int n)
Definition at line 110 of file keywordhash.h.
References keywordCode().
Referenced by identPut().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1