ContextLogger2 Logger Daemon Internals: kr_plat_ao_epoc.cpp File Reference
kr_plat_ao_epoc.cpp File Reference
Classes
class CDiskObserver
class CRegistrationObserver
class CNetworkObserver
class CSignalObserver
struct _kr_PlatAo
Defines
#define CTOR_DECL_CDiskObserver
#define CTOR_IMPL_CDiskObserver
#define CTOR_DECL_CRegistrationObserver
#define CTOR_IMPL_CRegistrationObserver
#define This CRegistrationObserver
#define CTOR_DECL_CNetworkObserver
#define CTOR_IMPL_CNetworkObserver
#define This CNetworkObserver
#define CTOR_DECL_CSignalObserver
#define CTOR_IMPL_CSignalObserver
#define This CSignalObserver
Functions
static void SignalObserverFlightModeChanged (bb_Blackboard *bb, enum bb_DataType dt, gpointer data, int len, gpointer arg)
kr_PlatAo * kr_PlatAo_new (GError **error)
void kr_PlatAo_destroy (kr_PlatAo *self)
Variables
CTOR_IMPL_CDiskObserver
CTOR_IMPL_CRegistrationObserver
CTOR_IMPL_CNetworkObserver
CTOR_IMPL_CSignalObserver
Define Documentation
#define CTOR_DECL_CDiskObserver
Value:
public: static CDiskObserver* NewLC(); \
public: static CDiskObserver* NewL(); \
private: CDiskObserver(); \
private: void ConstructL();
Definition at line 28 of file kr_plat_ao_epoc.cpp.
#define CTOR_DECL_CNetworkObserver
Value:
public: static CNetworkObserver* NewLC(); \
public: static CNetworkObserver* NewL(); \
private: CNetworkObserver(); \
private: void ConstructL();
Definition at line 232 of file kr_plat_ao_epoc.cpp.
#define CTOR_DECL_CRegistrationObserver
Value:
public: static CRegistrationObserver* NewLC(); \
public: static CRegistrationObserver* NewL(); \
private: CRegistrationObserver(); \
private: void ConstructL();
Definition at line 132 of file kr_plat_ao_epoc.cpp.
#define CTOR_DECL_CSignalObserver
Value:
public: static CSignalObserver* NewLC(); \
public: static CSignalObserver* NewL(); \
private: CSignalObserver(); \
private: void ConstructL();
Definition at line 386 of file kr_plat_ao_epoc.cpp.
#define CTOR_IMPL_CDiskObserver
Value:
CDiskObserver* CDiskObserver::NewLC() \
{ \
  CDiskObserver* obj = new (ELeave) CDiskObserver(); \
  CleanupStack::PushL(obj); \
  obj->ConstructL(); \
  return obj; \
} \
 \
CDiskObserver* CDiskObserver::NewL() \
{ \
  CDiskObserver* obj = CDiskObserver::NewLC(); \
  CleanupStack::Pop(obj); \
  return obj; \
} \
 \
CDiskObserver::CDiskObserver() \
{}
Definition at line 34 of file kr_plat_ao_epoc.cpp.
#define CTOR_IMPL_CNetworkObserver
Value:
CNetworkObserver* CNetworkObserver::NewLC() \
{ \
  CNetworkObserver* obj = new (ELeave) CNetworkObserver(); \
  CleanupStack::PushL(obj); \
  obj->ConstructL(); \
  return obj; \
} \
 \
CNetworkObserver* CNetworkObserver::NewL() \
{ \
  CNetworkObserver* obj = CNetworkObserver::NewLC(); \
  CleanupStack::Pop(obj); \
  return obj; \
} \
 \
CNetworkObserver::CNetworkObserver() \
{}
Definition at line 238 of file kr_plat_ao_epoc.cpp.
#define CTOR_IMPL_CRegistrationObserver
Value:
CRegistrationObserver* CRegistrationObserver::NewLC() \
{ \
  CRegistrationObserver* obj = new (ELeave) CRegistrationObserver(); \
  CleanupStack::PushL(obj); \
  obj->ConstructL(); \
  return obj; \
} \
 \
CRegistrationObserver* CRegistrationObserver::NewL() \
{ \
  CRegistrationObserver* obj = CRegistrationObserver::NewLC(); \
  CleanupStack::Pop(obj); \
  return obj; \
} \
 \
CRegistrationObserver::CRegistrationObserver() \
{}
Definition at line 138 of file kr_plat_ao_epoc.cpp.
#define CTOR_IMPL_CSignalObserver
Value:
CSignalObserver* CSignalObserver::NewLC() \
{ \
  CSignalObserver* obj = new (ELeave) CSignalObserver(); \
  CleanupStack::PushL(obj); \
  obj->ConstructL(); \
  return obj; \
} \
 \
CSignalObserver* CSignalObserver::NewL() \
{ \
  CSignalObserver* obj = CSignalObserver::NewLC(); \
  CleanupStack::Pop(obj); \
  return obj; \
} \
 \
CSignalObserver::CSignalObserver() \
{}
Definition at line 392 of file kr_plat_ao_epoc.cpp.
#define This CSignalObserver
Definition at line 412 of file kr_plat_ao_epoc.cpp.
#define This CNetworkObserver
Definition at line 412 of file kr_plat_ao_epoc.cpp.
#define This CRegistrationObserver
Definition at line 412 of file kr_plat_ao_epoc.cpp.
Referenced by SignalObserverFlightModeChanged().
Function Documentation
void kr_PlatAo_destroy (kr_PlatAo * self)
Definition at line 677 of file kr_plat_ao_epoc.cpp.
Referenced by kr_Controller_destroy(), and kr_PlatAo_new().
kr_PlatAo* kr_PlatAo_new (GError ** error)
Definition at line 610 of file kr_plat_ao_epoc.cpp.
References ac_get_global_AppContext(), domain_symbian, gx_error_new(), gx_error_no_memory, kr_PlatAo_destroy(), and plat_error_strerror.
Referenced by kr_Controller_new().
static void SignalObserverFlightModeChanged (bb_Blackboard * bb, enum bb_DataType dt, gpointer data, int len, gpointer arg) [static]
Definition at line 475 of file kr_plat_ao_epoc.cpp.
References This.
Variable Documentation
CTOR_IMPL_CDiskObserver
Definition at line 68 of file kr_plat_ao_epoc.cpp.
CTOR_IMPL_CNetworkObserver
Definition at line 281 of file kr_plat_ao_epoc.cpp.
CTOR_IMPL_CRegistrationObserver
Definition at line 178 of file kr_plat_ao_epoc.cpp.
CTOR_IMPL_CSignalObserver
Definition at line 451 of file kr_plat_ao_epoc.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1