ContextLogger2 Logger Daemon Internals: kr_controller.c File Reference
kr_controller.c File Reference
Defines
#define NAME_STARTS_WITH(lit) (pfx = lit, strncmp(pfx, name, strlen(pfx)) == 0)
#define NAME_EQUALS(lit) (strcmp(lit, name) == 0)
Functions
static gboolean start_uploader (kr_Controller *self, GError **error)
static void stop_uploader (kr_Controller *self)
static gboolean current_iap_is_cellular ()
static void log_uploads_allowed (kr_Controller *self)
static void uploads_allowed_update_board (gboolean value)
static void uploads_allowed_changed (kr_Controller *self)
static void netpos_allowed_update_board (gboolean value)
static void recompute_netpos_allowed (kr_Controller *self)
static void init_uploads_allowed_state (kr_Controller *self)
static void free_uploads_allowed_state (kr_Controller *self)
static void recompute_uploads_allowed (kr_Controller *self)
static void iap_config_changed (kr_Controller *self)
void kr_Controller_set_signal_strength (kr_Controller *self, int strength)
void kr_Controller_set_current_mcc (kr_Controller *self, int mcc)
void kr_Controller_set_operator_name (kr_Controller *self, const char *name)
kr_Controller * kr_Controller_new (GError **error)
void kr_Controller_destroy (kr_Controller *self)
gboolean kr_Controller_start (kr_Controller *self, GError **error)
void kr_Controller_stop (kr_Controller *self)
gboolean kr_Controller_run (kr_Controller *self, GError **error)
gboolean kr_Controller_reconfigure (kr_Controller *self, const gchar *name, const gchar *value, GError **error)
Define Documentation
#define NAME_EQUALS (lit) (strcmp(lit, name) == 0)
Definition at line 490 of file kr_controller.c.
Referenced by kr_Controller_reconfigure().
#define NAME_STARTS_WITH (lit) (pfx = lit, strncmp(pfx, name, strlen(pfx)) == 0)
Definition at line 487 of file kr_controller.c.
Referenced by kr_Controller_reconfigure().
Function Documentation
static gboolean current_iap_is_cellular () [static]
Definition at line 47 of file kr_controller.c.
References ac_global_LogDb, epoc_iap_is_modem(), error(), get_config_iap_id(), gx_dblog_error_free, log_db_log_status(), and logg.
Referenced by iap_config_changed(), and init_uploads_allowed_state().
static void free_uploads_allowed_state (kr_Controller * self) [static]
Definition at line 138 of file kr_controller.c.
References GMaybeString_free().
Referenced by kr_Controller_destroy().
static void iap_config_changed (kr_Controller * self) [static]
Definition at line 216 of file kr_controller.c.
References current_iap_is_cellular(), and recompute_uploads_allowed().
Referenced by kr_Controller_reconfigure().
static void init_uploads_allowed_state (kr_Controller * self) [static]
Definition at line 115 of file kr_controller.c.
References current_iap_is_cellular(), GMaybeString_init(), logg, recompute_netpos_allowed(), uploads_allowed_changed(), and WHEN_LOGGING.
Referenced by kr_Controller_new().
void kr_Controller_destroy (kr_Controller * self)
Definition at line 386 of file kr_controller.c.
References ac_AppContext_set_controller(), ConfigDb_destroy(), free_uploads_allowed_state(), FREE_Z, kr_PlatAo_destroy(), LocalServer_destroy(), LogDb_destroy(), rk_Remokon_destroy(), sa_Array_destroy(), and stop_uploader().
Referenced by cl2RunOnce(), CCl2appAppUi::DestroyLogger(), kr_Controller_new(), main(), and CMainObj::~CMainObj().
kr_Controller* kr_Controller_new (GError ** error)
Definition at line 265 of file kr_controller.c.
References ac_AppContext_configure(), ac_AppContext_set_controller(), ac_get_global_AppContext(), assert_error_unset, ConfigDb_new(), gx_error_no_memory, init_uploads_allowed_state(), kr_Controller_destroy(), kr_PlatAo_new(), LocalServer_new(), LogDb_new(), logt, rk_Remokon_new(), sa_Array_new(), and start_uploader().
Referenced by CMainObj::AppContextReady(), CCl2appAppUi::AppContextReady(), cl2RunOnce(), and main().
gboolean kr_Controller_reconfigure (kr_Controller * self, const gchar * name, const gchar * value, GError ** error)
Definition at line 493 of file kr_controller.c.
References iap_config_changed(), NAME_EQUALS, NAME_STARTS_WITH, rk_Remokon_reconfigure(), sa_Array_reconfigure(), and up_Uploader_reconfigure().
Referenced by ConfigDb_set_generic().
gboolean kr_Controller_run (kr_Controller * self, GError ** error)
Definition at line 475 of file kr_controller.c.
Referenced by cl2RunOnce().
void kr_Controller_set_current_mcc (kr_Controller * self, int mcc)
Definition at line 236 of file kr_controller.c.
References logg, recompute_netpos_allowed(), and recompute_uploads_allowed().
void kr_Controller_set_operator_name (kr_Controller * self, const char * name)
Definition at line 247 of file kr_controller.c.
References er_log_oom_on_false, GMaybeString_assign(), GMaybeString_is(), logg, recompute_netpos_allowed(), and recompute_uploads_allowed().
void kr_Controller_set_signal_strength (kr_Controller * self, int strength)
Definition at line 226 of file kr_controller.c.
References recompute_uploads_allowed().
gboolean kr_Controller_start (kr_Controller * self, GError ** error)
Definition at line 439 of file kr_controller.c.
References LocalServer_start(), logt, rk_Remokon_is_autostart_enabled(), rk_Remokon_start(), and sa_Array_start().
Referenced by CMainObj::AppContextReady(), cl2RunOnce(), main(), and CCl2appAppUi::Start().
void kr_Controller_stop (kr_Controller * self)
Definition at line 462 of file kr_controller.c.
References LocalServer_stop(), rk_Remokon_stop(), and sa_Array_stop().
Referenced by cl2RunOnce(), and CCl2appAppUi::Stop().
static void log_uploads_allowed (kr_Controller * self) [static]
Definition at line 76 of file kr_controller.c.
References ac_global_LogDb, boolstr_yes, and log_db_log_status().
Referenced by uploads_allowed_changed().
static void netpos_allowed_update_board (gboolean value) [static]
Definition at line 101 of file kr_controller.c.
References ac_global_Blackboard, ac_global_LogDb, bb_Blackboard_board(), bb_Blackboard_notify(), bb_dt_netpos_allowed, boolstr_yes, log_db_log_status(), and bb_Board::netpos_allowed.
Referenced by recompute_netpos_allowed().
static void recompute_netpos_allowed (kr_Controller * self) [static]
Definition at line 143 of file kr_controller.c.
References GMaybeString_is(), GMaybeString_is_nothing(), and netpos_allowed_update_board().
Referenced by init_uploads_allowed_state(), kr_Controller_set_current_mcc(), and kr_Controller_set_operator_name().
static void recompute_uploads_allowed (kr_Controller * self) [static]
Definition at line 175 of file kr_controller.c.
References GMaybeString_is(), GMaybeString_is_nothing(), and uploads_allowed_changed().
Referenced by iap_config_changed(), kr_Controller_set_current_mcc(), kr_Controller_set_operator_name(), and kr_Controller_set_signal_strength().
static gboolean start_uploader (kr_Controller * self, GError ** error) [static]
Definition at line 23 of file kr_controller.c.
References up_Uploader_new().
Referenced by kr_Controller_new().
static void stop_uploader (kr_Controller * self) [static]
Definition at line 35 of file kr_controller.c.
References up_Uploader_destroy().
Referenced by kr_Controller_destroy().
static void uploads_allowed_changed (kr_Controller * self) [static]
Definition at line 95 of file kr_controller.c.
References log_uploads_allowed(), and uploads_allowed_update_board().
Referenced by init_uploads_allowed_state(), and recompute_uploads_allowed().
static void uploads_allowed_update_board (gboolean value) [static]
Definition at line 85 of file kr_controller.c.
References ac_global_Blackboard, bb_Blackboard_board(), bb_Blackboard_notify(), bb_dt_uploads_allowed, and bb_Board::uploads_allowed.
Referenced by uploads_allowed_changed().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1