ContextLogger2 Logger Daemon Internals: kr_sms_trigger_epoc.cpp File Reference
kr_sms_trigger_epoc.cpp File Reference
Functions
_LIT8 (KControlTag,"##cl")
Variables
CTOR_IMPL_CSmsTrigger
Function Documentation
_LIT8 (KControlTag , "##cl")
Referenced by BtDevAddrToString(), CFileDataSupplier::OpenL(), and CPosterAo::PostGenericL().
Variable Documentation
CTOR_IMPL_CSmsTrigger
Definition at line 17 of file kr_sms_trigger_epoc.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1