ContextLogger2 Logger Daemon Internals: lauxlib.c File Reference
lauxlib.c File Reference
Classes
struct LoadF
struct LoadS
Defines
#define lauxlib_c
#define LUA_LIB
#define FREELIST_REF 0
#define abs_index(L, i)
#define bufflen(B) ((B)->p - (B)->buffer)
#define bufffree(B) ((size_t)(LUAL_BUFFERSIZE - bufflen(B)))
#define LIMIT (LUA_MINSTACK/2)
Functions
LUALIB_API int luaL_argerror (lua_State *L, int narg, const char *extramsg)
LUALIB_API int luaL_typerror (lua_State *L, int narg, const char *tname)
static void tag_error (lua_State *L, int narg, int tag)
LUALIB_API void luaL_where (lua_State *L, int level)
LUALIB_API int luaL_error (lua_State *L, const char *fmt,...)
LUALIB_API int luaL_checkoption (lua_State *L, int narg, const char *def, const char *const lst[])
LUALIB_API int luaL_newmetatable (lua_State *L, const char *tname)
LUALIB_API void * luaL_checkudata (lua_State *L, int ud, const char *tname)
LUALIB_API void luaL_checkstack (lua_State *L, int space, const char *mes)
LUALIB_API void luaL_checktype (lua_State *L, int narg, int t)
LUALIB_API void luaL_checkany (lua_State *L, int narg)
LUALIB_API const char * luaL_checklstring (lua_State *L, int narg, size_t *len)
LUALIB_API const char * luaL_optlstring (lua_State *L, int narg, const char *def, size_t *len)
LUALIB_API lua_Number luaL_checknumber (lua_State *L, int narg)
LUALIB_API lua_Number luaL_optnumber (lua_State *L, int narg, lua_Number def)
LUALIB_API lua_Integer luaL_checkinteger (lua_State *L, int narg)
LUALIB_API lua_Integer luaL_optinteger (lua_State *L, int narg, lua_Integer def)
LUALIB_API int luaL_getmetafield (lua_State *L, int obj, const char *event)
LUALIB_API int luaL_callmeta (lua_State *L, int obj, const char *event)
LUALIB_API void() luaL_register (lua_State *L, const char *libname, const luaL_Reg *l)
static int libsize (const luaL_Reg *l)
LUALIB_API void luaI_openlib (lua_State *L, const char *libname, const luaL_Reg *l, int nup)
LUALIB_API const char * luaL_gsub (lua_State *L, const char *s, const char *p, const char *r)
LUALIB_API const char * luaL_findtable (lua_State *L, int idx, const char *fname, int szhint)
static int emptybuffer (luaL_Buffer *B)
static void adjuststack (luaL_Buffer *B)
LUALIB_API char * luaL_prepbuffer (luaL_Buffer *B)
LUALIB_API void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l)
LUALIB_API void luaL_addstring (luaL_Buffer *B, const char *s)
LUALIB_API void luaL_pushresult (luaL_Buffer *B)
LUALIB_API void luaL_addvalue (luaL_Buffer *B)
LUALIB_API void luaL_buffinit (lua_State *L, luaL_Buffer *B)
LUALIB_API int luaL_ref (lua_State *L, int t)
LUALIB_API void luaL_unref (lua_State *L, int t, int ref)
static const char * getF (lua_State *L, void *ud, size_t *size)
static int errfile (lua_State *L, const char *what, int fnameindex)
LUALIB_API int luaL_loadfile (lua_State *L, const char *filename)
static const char * getS (lua_State *L, void *ud, size_t *size)
LUALIB_API int luaL_loadbuffer (lua_State *L, const char *buff, size_t size, const char *name)
LUALIB_API int() luaL_loadstring (lua_State *L, const char *s)
static void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
static int atpanic_print (lua_State *L)
LUALIB_API lua_State * luaL_newstate (void)
Define Documentation
#define abs_index (L, i)
Value:
((i) > 0 || (i) <= LUA_REGISTRYINDEX ? (i) : \
          lua_gettop(L) + (i) + 1)
Definition at line 31 of file lauxlib.c.
Referenced by luaL_callmeta(), luaL_ref(), and luaL_unref().
#define bufffree (B) ((size_t)(LUAL_BUFFERSIZE - bufflen(B)))
Definition at line 392 of file lauxlib.c.
Referenced by luaL_addvalue().
#define bufflen (B) ((B)->p - (B)->buffer)
Definition at line 391 of file lauxlib.c.
Referenced by emptybuffer().
#define FREELIST_REF 0
Definition at line 27 of file lauxlib.c.
Referenced by luaL_ref(), and luaL_unref().
#define lauxlib_c
Definition at line 20 of file lauxlib.c.
#define LIMIT (LUA_MINSTACK/2)
Definition at line 394 of file lauxlib.c.
Referenced by adjuststack().
#define LUA_LIB
Definition at line 21 of file lauxlib.c.
Function Documentation
static void adjuststack (luaL_Buffer * B) [static]
Definition at line 409 of file lauxlib.c.
References luaL_Buffer::L, LIMIT, lua_concat(), lua_strlen, and luaL_Buffer::lvl.
Referenced by luaL_addvalue(), and luaL_prepbuffer().
static int atpanic_print (lua_State * L) [static]
Definition at line 638 of file lauxlib.c.
References lua_tostring.
Referenced by luaL_newstate().
static int emptybuffer (luaL_Buffer * B) [static]
Definition at line 397 of file lauxlib.c.
References luaL_Buffer::buffer, bufflen, luaL_Buffer::L, lua_pushlstring(), luaL_Buffer::lvl, and luaL_Buffer::p.
Referenced by luaL_addvalue(), luaL_prepbuffer(), and luaL_pushresult().
static int errfile (lua_State * L, const char * what, int fnameindex) [static]
Definition at line 542 of file lauxlib.c.
References LUA_ERRFILE, lua_pushfstring(), lua_remove(), and lua_tostring.
Referenced by luaL_loadfile().
static const char* getF (lua_State * L, void * ud, size_t * size) [static]
Definition at line 528 of file lauxlib.c.
References LoadF::buff, LoadF::extraline, and LoadF::f.
Referenced by luaL_loadfile().
static const char* getS (lua_State * L, void * ud, size_t * size) [static]
Definition at line 598 of file lauxlib.c.
References LoadS::s, and LoadS::size.
Referenced by luaL_loadbuffer().
static void* l_alloc (void * ud, void * ptr, size_t osize, size_t nsize) [static]
Definition at line 626 of file lauxlib.c.
static int libsize (const luaL_Reg * l) [static]
Definition at line 234 of file lauxlib.c.
References luaL_Reg::name.
Referenced by luaI_openlib().
LUALIB_API void luaI_openlib (lua_State * L, const char * libname, const luaL_Reg * l, int nup)
Definition at line 241 of file lauxlib.c.
References luaL_Reg::func, libsize(), lua_getfield(), LUA_GLOBALSINDEX, lua_insert(), lua_istable, lua_pop, lua_pushcclosure(), lua_pushvalue(), LUA_QS, LUA_REGISTRYINDEX, lua_remove(), lua_setfield(), luaL_error(), luaL_findtable(), and luaL_Reg::name.
Referenced by luaL_register().
LUALIB_API void luaL_addlstring (luaL_Buffer * B, const char * s, size_t l)
Definition at line 435 of file lauxlib.c.
References luaL_addchar.
Referenced by add_s(), addquoted(), luaL_addstring(), luaL_gsub(), os_date(), str_format(), str_gsub(), str_rep(), tconcat(), and writer().
LUALIB_API void luaL_addstring (luaL_Buffer * B, const char * s)
Definition at line 441 of file lauxlib.c.
References luaL_addlstring().
Referenced by luaL_gsub().
LUALIB_API void luaL_addvalue (luaL_Buffer * B)
Definition at line 453 of file lauxlib.c.
References adjuststack(), bufffree, emptybuffer(), luaL_Buffer::L, lua_insert(), lua_pop, lua_tolstring(), luaL_Buffer::lvl, and luaL_Buffer::p.
Referenced by add_s(), add_value(), addfield(), and str_format().
LUALIB_API int luaL_argerror (lua_State * L, int narg, const char * extramsg)
Definition at line 42 of file lauxlib.c.
References lua_getinfo(), lua_getstack(), LUA_QS, luaL_error(), lua_Debug::name, and lua_Debug::namewhat.
Referenced by db_getinfo(), db_getlocal(), db_setlocal(), fileerror(), FUNC(), g_read(), getfunc(), luaL_checkany(), luaL_checkoption(), and luaL_typerror().
LUALIB_API void luaL_buffinit (lua_State * L, luaL_Buffer * B)
Definition at line 471 of file lauxlib.c.
References luaL_Buffer::buffer, luaL_Buffer::L, luaL_Buffer::lvl, and luaL_Buffer::p.
Referenced by luaL_gsub(), os_date(), read_chars(), read_line(), str_char(), str_dump(), str_format(), str_gsub(), str_lower(), str_rep(), str_reverse(), str_upper(), and tconcat().
LUALIB_API int luaL_callmeta (lua_State * L, int obj, const char * event)
Definition at line 218 of file lauxlib.c.
References abs_index, lua_call(), lua_pushvalue(), and luaL_getmetafield().
Referenced by luaB_tostring().
LUALIB_API void luaL_checkany (lua_State * L, int narg)
Definition at line 151 of file lauxlib.c.
References LUA_TNONE, lua_type(), and luaL_argerror().
Referenced by db_getmetatable(), db_setlocal(), db_setupvalue(), io_type(), luaB_assert(), luaB_getmetatable(), luaB_pcall(), luaB_rawequal(), luaB_rawget(), luaB_rawset(), luaB_tonumber(), luaB_tostring(), luaB_type(), and luaB_xpcall().
LUALIB_API lua_Integer luaL_checkinteger (lua_State * L, int narg)
Definition at line 188 of file lauxlib.c.
References d(), lua_isnumber(), LUA_TNUMBER, lua_tointeger(), and tag_error().
Referenced by luaL_optinteger(), and str_sub().
LUALIB_API const char* luaL_checklstring (lua_State * L, int narg, size_t * len)
Definition at line 157 of file lauxlib.c.
References lua_tolstring(), LUA_TSTRING, and tag_error().
Referenced by addquoted(), f_config_get(), f_config_set(), f_iap_id_by_name(), f_is_ascii_ident(), f_is_sensor_running(), f_is_sensor_supported(), f_log(), f_log_message(), f_sensor_start(), f_sensor_stop(), f_static_get_str(), g_write(), luaB_loadstring(), luaL_optlstring(), str_byte(), str_find_aux(), str_format(), str_gsub(), str_len(), str_lower(), str_rep(), str_reverse(), str_sub(), and str_upper().
LUALIB_API lua_Number luaL_checknumber (lua_State * L, int narg)
Definition at line 175 of file lauxlib.c.
References d(), lua_isnumber(), LUA_TNUMBER, lua_tonumber(), and tag_error().
Referenced by luaL_optnumber(), math_abs(), math_acos(), math_asin(), math_atan(), math_atan2(), math_ceil(), math_cos(), math_cosh(), math_deg(), math_exp(), math_floor(), math_fmod(), math_frexp(), math_ldexp(), math_log(), math_log10(), math_max(), math_min(), math_modf(), math_pow(), math_rad(), math_sin(), math_sinh(), math_sqrt(), math_tan(), math_tanh(), os_date(), os_difftime(), and str_format().
LUALIB_API int luaL_checkoption (lua_State * L, int narg, const char * def, const char *const lst[])
Definition at line 98 of file lauxlib.c.
References lua_pushfstring(), LUA_QS, luaL_argerror(), luaL_checkstring, and luaL_optstring.
Referenced by f_seek(), f_setvbuf(), luaB_collectgarbage(), and os_setlocale().
LUALIB_API void luaL_checkstack (lua_State * L, int space, const char * mes)
Definition at line 139 of file lauxlib.c.
References lua_checkstack(), and luaL_error().
Referenced by g_read(), generic_reader(), getargs(), push_captures(), sort(), and str_byte().
LUALIB_API void luaL_checktype (lua_State * L, int narg, int t)
Definition at line 145 of file lauxlib.c.
References lua_type(), and tag_error().
Referenced by auxupvalue(), db_setfenv(), db_sethook(), foreach(), foreachi(), ipairsaux(), ll_seeall(), luaB_ipairs(), luaB_load(), luaB_next(), luaB_pairs(), luaB_rawget(), luaB_rawset(), luaB_setfenv(), luaB_setmetatable(), luaB_unpack(), maxn(), os_time(), setn(), sort(), str_dump(), and tconcat().
LUALIB_API void* luaL_checkudata (lua_State * L, int ud, const char * tname)
Definition at line 123 of file lauxlib.c.
References lua_getfield(), lua_getmetatable(), lua_pop, lua_rawequal(), LUA_REGISTRYINDEX, lua_touserdata(), and luaL_typerror().
Referenced by gctm().
LUALIB_API int luaL_error (lua_State * L, const char * fmt, ...)
Definition at line 85 of file lauxlib.c.
References lua_concat(), lua_error(), lua_pushvfstring(), and luaL_where().
Referenced by add_value(), addfield(), auxresume(), auxsort(), capture_to_close(), check_capture(), classend(), db_setfenv(), findfile(), generic_reader(), getfield(), getfunc(), getiofile(), gfind_nodef(), io_readline(), ll_module(), ll_require(), loader_preload(), loaderror(), lstop(), luaB_assert(), luaB_print(), luaB_setfenv(), luaB_setmetatable(), luaB_unpack(), luaI_openlib(), luaL_argerror(), luaL_checkstack(), match(), matchbalance(), math_random(), os_tmpname(), push_onecapture(), scanformat(), setfenv(), setn(), start_capture(), str_byte(), str_dump(), str_format(), tinsert(), and tofile().
LUALIB_API const char* luaL_findtable (lua_State * L, int idx, const char * fname, int szhint)
Definition at line 356 of file lauxlib.c.
References lua_createtable(), lua_isnil, lua_istable, lua_pop, lua_pushlstring(), lua_pushvalue(), lua_rawget(), lua_remove(), and lua_settable().
Referenced by ll_module(), luaI_openlib(), and luaopen_package().
LUALIB_API int luaL_getmetafield (lua_State * L, int obj, const char * event)
Definition at line 202 of file lauxlib.c.
References lua_getmetatable(), lua_isnil, lua_pop, lua_pushstring(), lua_rawget(), and lua_remove().
Referenced by luaB_getmetatable(), luaB_setmetatable(), and luaL_callmeta().
LUALIB_API const char* luaL_gsub (lua_State * L, const char * s, const char * p, const char * r)
Definition at line 339 of file lauxlib.c.
References lua_tostring, luaL_addlstring(), luaL_addstring(), luaL_buffinit(), and luaL_pushresult().
Referenced by findfile(), mkfuncname(), and setpath().
LUALIB_API int luaL_loadbuffer (lua_State * L, const char * buff, size_t size, const char * name)
Definition at line 608 of file lauxlib.c.
References getS(), lua_load(), LoadS::s, and LoadS::size.
Referenced by db_debug(), dostring(), loadline(), luaB_loadstring(), and luaL_loadstring().
LUALIB_API int luaL_loadfile (lua_State * L, const char * filename)
Definition at line 551 of file lauxlib.c.
References errfile(), LoadF::extraline, LoadF::f, getF(), lua_gettop(), lua_load(), lua_pushfstring(), lua_pushliteral, lua_remove(), lua_settop(), LUA_SIGNATURE, and lua_tostring.
Referenced by dofile(), handle_script(), loader_Lua(), luaB_dofile(), luaB_loadfile(), and pmain().
LUALIB_API int() luaL_loadstring (lua_State * L, const char * s)
Definition at line 617 of file lauxlib.c.
References luaL_loadbuffer().
Referenced by eval_lua_str(), _rk_Remokon::gotJabberMessage(), CCliapiSession::ServiceL(), and validate_lua_syntax().
LUALIB_API int luaL_newmetatable (lua_State * L, const char * tname)
Definition at line 111 of file lauxlib.c.
References lua_getfield(), lua_isnil, lua_newtable, lua_pop, lua_pushvalue(), LUA_REGISTRYINDEX, and lua_setfield().
Referenced by createmeta(), and luaopen_package().
LUALIB_API lua_State* luaL_newstate (void)
Definition at line 646 of file lauxlib.c.
References atpanic_print(), l_alloc(), lua_atpanic(), and lua_newstate().
LUALIB_API lua_Integer luaL_optinteger (lua_State * L, int narg, lua_Integer def)
Definition at line 196 of file lauxlib.c.
References luaL_checkinteger(), and luaL_opt.
Referenced by f_setvbuf(), str_byte(), str_find_aux(), and str_sub().
LUALIB_API const char* luaL_optlstring (lua_State * L, int narg, const char * def, size_t * len)
Definition at line 164 of file lauxlib.c.
References lua_isnoneornil, and luaL_checklstring().
Referenced by tconcat().
LUALIB_API lua_Number luaL_optnumber (lua_State * L, int narg, lua_Number def)
Definition at line 183 of file lauxlib.c.
References luaL_checknumber(), and luaL_opt.
Referenced by os_difftime().
LUALIB_API char* luaL_prepbuffer (luaL_Buffer * B)
Definition at line 428 of file lauxlib.c.
References adjuststack(), luaL_Buffer::buffer, and emptybuffer().
Referenced by read_chars(), and read_line().
LUALIB_API void luaL_pushresult (luaL_Buffer * B)
Definition at line 446 of file lauxlib.c.
References emptybuffer(), luaL_Buffer::L, lua_concat(), and luaL_Buffer::lvl.
Referenced by luaL_gsub(), os_date(), read_chars(), read_line(), str_char(), str_dump(), str_format(), str_gsub(), str_lower(), str_rep(), str_reverse(), str_upper(), and tconcat().
LUALIB_API int luaL_ref (lua_State * L, int t)
Definition at line 480 of file lauxlib.c.
References abs_index, FREELIST_REF, lua_isnil, lua_objlen(), lua_pop, lua_rawgeti(), lua_rawseti(), LUA_REFNIL, and lua_tointeger().
LUALIB_API void() luaL_register (lua_State * L, const char * libname, const luaL_Reg * l)
Definition at line 228 of file lauxlib.c.
References luaI_openlib().
Referenced by base_open(), createmeta(), luaopen_base(), luaopen_cl2(), luaopen_debug(), luaopen_io(), luaopen_math(), luaopen_os(), luaopen_package(), luaopen_string(), and luaopen_table().
LUALIB_API int luaL_typerror (lua_State * L, int narg, const char * tname)
Definition at line 60 of file lauxlib.c.
References lua_pushfstring(), luaL_argerror(), and luaL_typename.
Referenced by checknilornoneorfunc(), checkudata(), luaL_checkudata(), and tag_error().
LUALIB_API void luaL_unref (lua_State * L, int t, int ref)
Definition at line 503 of file lauxlib.c.
References abs_index, FREELIST_REF, lua_pushinteger(), lua_rawgeti(), and lua_rawseti().
LUALIB_API void luaL_where (lua_State * L, int level)
Definition at line 72 of file lauxlib.c.
References lua_Debug::currentline, lua_getinfo(), lua_getstack(), lua_pushfstring(), lua_pushliteral, and lua_Debug::short_src.
Referenced by luaB_auxwrap(), luaB_error(), and luaL_error().
static void tag_error (lua_State * L, int narg, int tag) [static]
Definition at line 67 of file lauxlib.c.
References lua_typename(), and luaL_typerror().
Referenced by luaL_checkinteger(), luaL_checklstring(), luaL_checknumber(), and luaL_checktype().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1