ContextLogger2 Logger Daemon Internals: ld_create.c File Reference
ld_create.c File Reference
Functions
gboolean create_log_db (GError **error)
gboolean ensure_log_db_created (GError **error)
Function Documentation
gboolean create_log_db (GError ** error)
Definition at line 16 of file ld_create.c.
References assert_error_unset, create_database(), get_create_tables_sql(), LOGDB_DIR, and LOGDB_FILE.
Referenced by ensure_log_db_created(), and log_db_take_snapshot().
gboolean ensure_log_db_created (GError ** error)
Definition at line 27 of file ld_create.c.
References assert_error_unset, create_log_db(), and LOGDB_FILE.
Referenced by LogDb_new().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1