ContextLogger2 Logger Daemon Internals: ld_log_db.c File Reference
ld_log_db.c File Reference
Defines
#define set_sqlite_error
Functions
static void log_db_close_session (LogDb *self)
static gboolean log_db_open_session (LogDb *self, GError **error)
static gboolean log_text_to_db (LogDb *self, const char *text, sqlite3_stmt *stmt, const char *errorFmt, GError **error)
LogDb * LogDb_new (GError **error)
void LogDb_destroy (LogDb *self)
gboolean log_db_log_status_direct (LogDb *self, GError **error, const char *text)
gboolean log_db_log_status (LogDb *self, GError **error, const char *fmt,...)
gboolean log_db_take_snapshot (LogDb *self, gchar *pathname, gboolean *renamed, GError **error)
Define Documentation
#define set_sqlite_error
Value:
{           \
    if (error)                \
      *error = gx_error_new(domain_cl2app, code_database_command, errorFmt, \
          sqlite3_errmsg(self->db), sqlite3_errcode(self->db)); \
  }
Referenced by log_text_to_db().
Function Documentation
static void log_db_close_session (LogDb * self) [static]
Definition at line 22 of file ld_log_db.c.
References destroy_sql_statements(), logg, and sqlite3_close().
Referenced by log_db_open_session(), log_db_take_snapshot(), and LogDb_destroy().
gboolean log_db_log_status (LogDb * self, GError ** error, const char * fmt, ...)
Definition at line 160 of file ld_log_db.c.
References gx_error_no_memory, log_db_log_status_direct(), SET_TRAP_OOM, and UNSET_TRAP_OOM.
Referenced by CSensor_callstatus::ChangedData_CallStatus(), CSensor_callstatus::ChangedData_FlightMode(), current_iap_is_cellular(), CSensor_callstatus::GotData_FlightMode(), CSensor_smsevent::handle_close(), CSensor_smsevent::handle_error(), Sensor_tap::handleActiveChanged(), ClQtEventSensorBase::handleActiveChanged(), Sensor_tap::handleBusyChanged(), ClQtEventSensorBase::handleBusyChanged(), CSensor_indicator::HandleRead(), Sensor_tap::handleSensorError(), ClQtEventSensorBase::handleSensorError(), log_uploads_allowed(), netpos_allowed_update_board(), CSensor_cellpos::PositionerEventL(), CUploader::PosterEvent(), CUploader::postingFinished(), px_dblog_fatal_error(), CUploader::RefreshIap(), CUploader::RefreshSnapshotTimeExpr(), CSensor_callstatus::RetryTimerExpired(), CActiveLogErrG::RunError(), CActiveLogErr::RunError(), CSensor_appfocus::RunGL(), CSensor_keypress::RunL(), CSensor_inactivity::RunL(), _rk_Remokon::runTimeout(), CSensor_btprox::StartL(), CSensor_btprox::Stop(), and CUploader::TakeSnapshotNowL().
gboolean log_db_log_status_direct (LogDb * self, GError ** error, const char * text)
Definition at line 153 of file ld_log_db.c.
References log_text_to_db().
Referenced by er_log_base(), er_log_status_string(), gx_dblog_error_check(), and log_db_log_status().
static gboolean log_db_open_session (LogDb * self, GError ** error) [static]
Definition at line 42 of file ld_log_db.c.
References code_database_open, domain_cl2app, gx_error_new(), log_db_close_session(), LOGDB_FILE, prepare_sql_statements(), sqlite3_open(), and sqlite_get_error_string.
Referenced by log_db_take_snapshot(), and LogDb_new().
gboolean log_db_take_snapshot (LogDb * self, gchar * pathname, gboolean * renamed, GError ** error)
Definition at line 188 of file ld_log_db.c.
References ac_STATIC_GET, compress_file(), create_log_db(), domain_posix, er_fatal_general, gx_error_new(), log_db_close_session(), log_db_open_session(), LOGDB_FILE, logg, and logt.
Referenced by CUploader::TakeSnapshotNowL().
static gboolean log_text_to_db (LogDb * self, const char * text, sqlite3_stmt * stmt, const char * errorFmt, GError ** error) [static]
Definition at line 70 of file ld_log_db.c.
References assert_error_unset, er_FATAL, er_log_errno, logt, set_sqlite_error, sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by log_db_log_status_direct().
void LogDb_destroy (LogDb * self)
Definition at line 144 of file ld_log_db.c.
References log_db_close_session().
Referenced by kr_Controller_destroy(), and LogDb_new().
LogDb* LogDb_new (GError ** error)
Definition at line 122 of file ld_log_db.c.
References assert_error_unset, ensure_log_db_created(), gx_error_no_memory, log_db_open_session(), and LogDb_destroy().
Referenced by kr_Controller_new().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1