ContextLogger2 Logger Daemon Internals: ldebug.h File Reference
ldebug.h File Reference
Defines
#define pcRel(pc, p) (cast(int, (pc) - (p)->code) - 1)
#define getline(f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : 0)
#define resethookcount(L) (L->hookcount = L->basehookcount)
#define luaG_runerror_1(_L, _s) luaG_runerror_ok(_L, _s)
#define luaG_runerror_m(_L, rest...) luaG_runerror_ok(_L, rest)
Functions
LUAI_FUNC void luaG_typeerror (lua_State *L, const TValue *o, const char *opname)
LUAI_FUNC void luaG_concaterror (lua_State *L, StkId p1, StkId p2)
LUAI_FUNC void luaG_aritherror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC int luaG_ordererror (lua_State *L, const TValue *p1, const TValue *p2)
LUAI_FUNC void luaG_errormsg (lua_State *L)
LUAI_FUNC int luaG_checkcode (const Proto *pt)
LUAI_FUNC int luaG_checkopenop (Instruction i)
LUAI_FUNC void luaG_runerror_ok (lua_State *L, const char *fmt,...)
Define Documentation
#define getline (f, pc) (((f)->lineinfo) ? (f)->lineinfo[pc] : 0)
Definition at line 17 of file ldebug.h.
Referenced by currentline(), PrintCode(), and traceexec().
#define luaG_runerror_1 (_L, _s) luaG_runerror_ok(_L, _s)
Definition at line 40 of file ldebug.h.
Referenced by findindex(), growCI(), lua_replace(), lua_yield(), luaD_call(), luaH_set(), luaM_growaux_(), luaM_toobig(), luaV_concat(), luaV_execute(), luaV_gettable(), luaV_settable(), and setnodevector().
#define luaG_runerror_m (_L, rest...) luaG_runerror_ok(_L, rest)
Definition at line 41 of file ldebug.h.
Referenced by luaG_ordererror(), and luaG_typeerror().
#define pcRel (pc, p) (cast(int, (pc) - (p)->code) - 1)
Definition at line 15 of file ldebug.h.
Referenced by currentpc(), and traceexec().
#define resethookcount (L) (L->hookcount = L->basehookcount)
Definition at line 19 of file ldebug.h.
Referenced by lua_sethook(), luaE_newthread(), preinit_state(), and traceexec().
Function Documentation
LUAI_FUNC void luaG_aritherror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 593 of file ldebug.c.
References luaG_typeerror(), and luaV_tonumber().
Referenced by Arith().
LUAI_FUNC int luaG_checkcode (const Proto * pt)
Definition at line 485 of file ldebug.c.
References NO_REG, Proto::sizecode, and symbexec().
Referenced by close_func(), and LoadFunction().
LUAI_FUNC int luaG_checkopenop (Instruction i)
Definition at line 291 of file ldebug.c.
References check, GET_OPCODE, GETARG_B, OP_CALL, OP_RETURN, OP_SETLIST, and OP_TAILCALL.
Referenced by luaV_execute().
LUAI_FUNC void luaG_concaterror (lua_State * L, StkId p1, StkId p2)
Definition at line 586 of file ldebug.c.
References lua_assert, luaG_typeerror(), ttisnumber, and ttisstring.
Referenced by luaV_concat().
LUAI_FUNC void luaG_errormsg (lua_State * L)
Definition at line 620 of file ldebug.c.
References lua_State::errfunc, incr_top, LUA_ERRERR, LUA_ERRRUN, luaD_call(), luaD_throw(), restorestack, setobjs2s, lua_State::top, and ttisfunction.
Referenced by lua_error(), and luaG_runerror_ok().
LUAI_FUNC int luaG_ordererror (lua_State * L, const TValue * p1, const TValue * p2)
Definition at line 601 of file ldebug.c.
References incr_top, LUA_ERRRUN, luaD_throw(), luaG_runerror_m, luaS_new, luaT_typenames, setsvalue2s, lua_State::top, and ttype.
Referenced by lessequal(), and luaV_lessthan().
LUAI_FUNC void luaG_runerror_ok (lua_State * L, const char * fmt, ...)
Definition at line 665 of file ldebug.c.
References addinfo(), luaG_errormsg(), and luaO_pushvfstring().
LUAI_FUNC void luaG_typeerror (lua_State * L, const TValue * o, const char * opname)
Definition at line 568 of file ldebug.c.
References lua_State::base, cast_int, lua_State::ci, getobjname(), isinstack(), LUA_QS, luaG_runerror_m, luaT_typenames, and ttype.
Referenced by luaG_aritherror(), luaG_concaterror(), luaV_execute(), luaV_gettable(), luaV_settable(), and tryfuncTM().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1