ContextLogger2 Logger Daemon Internals: legacy.c File Reference
legacy.c File Reference
Functions
EXPORT_C int sqlite3_exec (sqlite3 *db, const char *zSql, sqlite3_callback xCallback, void *pArg, char **pzErrMsg)
Function Documentation
EXPORT_C int sqlite3_exec (sqlite3 * db, const char * zSql, sqlite3_callback xCallback, void * pArg, char ** pzErrMsg)
Definition at line 33 of file legacy.c.
References sqlite3::errMask, sqlite3::flags, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_column_count(), sqlite3_column_name(), sqlite3_column_text(), sqlite3_column_type(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_prepare(), sqlite3_step(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3Error(), sqlite3Malloc(), SQLITE_ABORT, SQLITE_DONE, SQLITE_NULL, SQLITE_NullCallback, SQLITE_OK, SQLITE_ROW, and SQLITE_SCHEMA.
Referenced by create_database(), DbObjCmd(), do_meta_command(), fulltextRename(), FUNC(), main(), process_input(), run_schema_dump_query(), sql_exec(), sqlite3_get_table(), sqlite3AnalysisLoad(), sqlite3InitCallback(), sqlite3InitOne(), and sqlite3VdbeExec().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1