ContextLogger2 Logger Daemon Internals: linit.c File Reference
linit.c File Reference
Defines
#define linit_c
#define LUA_LIB
Functions
LUALIB_API void luaL_openlibs (lua_State *L)
Variables
static const luaL_Reg lualibs []
Define Documentation
#define linit_c
Definition at line 8 of file linit.c.
#define LUA_LIB
Definition at line 9 of file linit.c.
Function Documentation
LUALIB_API void luaL_openlibs (lua_State * L)
Definition at line 29 of file linit.c.
References luaL_Reg::func, lua_call(), lua_pushcfunction, lua_pushstring(), and luaL_Reg::name.
Referenced by cl_lua_new_libs(), and pmain().
Variable Documentation
const luaL_Reg lualibs[] [static]
Initial value:
 {
  {"", luaopen_base},
  {LUA_LOADLIBNAME, luaopen_package},
  {LUA_TABLIBNAME, luaopen_table},
  {LUA_IOLIBNAME, luaopen_io},
  {LUA_OSLIBNAME, luaopen_os},
  {LUA_STRLIBNAME, luaopen_string},
  {LUA_MATHLIBNAME, luaopen_math},
  {LUA_DBLIBNAME, luaopen_debug},
  {NULL, NULL}
}
Definition at line 16 of file linit.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:59 2011 by Doxygen 1.6.1