ContextLogger2 Logger Daemon Internals: lmem.c File Reference
lmem.c File Reference
Defines
#define lmem_c
#define LUA_CORE
#define MINSIZEARRAY 4
Functions
void * luaM_growaux_ (lua_State *L, void *block, int *size, size_t size_elems, int limit, const char *errormsg)
void * luaM_toobig (lua_State *L)
void * luaM_realloc_ (lua_State *L, void *block, size_t osize, size_t nsize)
Define Documentation
#define lmem_c
Definition at line 10 of file lmem.c.
#define LUA_CORE
Definition at line 11 of file lmem.c.
#define MINSIZEARRAY 4
Definition at line 43 of file lmem.c.
Referenced by luaM_growaux_().
Function Documentation
void* luaM_growaux_ (lua_State * L, void * block, int * size, size_t size_elems, int limit, const char * errormsg)
Definition at line 46 of file lmem.c.
References luaG_runerror_1, luaM_reallocv, and MINSIZEARRAY.
void* luaM_realloc_ (lua_State * L, void * block, size_t osize, size_t nsize)
Definition at line 76 of file lmem.c.
References global_State::frealloc, G, lua_assert, LUA_ERRMEM, luaD_throw(), global_State::totalbytes, and global_State::ud.
void* luaM_toobig (lua_State * L)
Definition at line 66 of file lmem.c.
References luaG_runerror_1.
Referenced by luaS_newudata(), and newlstr().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1