ContextLogger2 Logger Daemon Internals: loadext.c File Reference
loadext.c File Reference
Classes
struct sqlite3ExtType
Defines
#define SQLITE_CORE 1
#define sqlite3_column_database_name 0
#define sqlite3_column_database_name16 0
#define sqlite3_column_table_name 0
#define sqlite3_column_table_name16 0
#define sqlite3_column_origin_name 0
#define sqlite3_column_origin_name16 0
#define sqlite3_table_column_metadata 0
#define wsdAutoextInit
#define wsdAutoext sqlite3Autoext
Typedefs
typedef struct sqlite3ExtType sqlite3ExtType
Functions
static int sqlite3LoadExtension (sqlite3 *db, const char *zFile, const char *zProc, char **pzErrMsg)
int sqlite3_load_extension (sqlite3 *db, const char *zFile, const char *zProc, char **pzErrMsg)
void sqlite3CloseExtensions (sqlite3 *db)
int sqlite3_enable_load_extension (sqlite3 *db, int onoff)
int sqlite3_auto_extension (void *xInit)
void sqlite3_reset_auto_extension (void)
int sqlite3AutoLoadExtensions (sqlite3 *db)
Variables
static const sqlite3_api_routines sqlite3Apis
static SQLITE_WSD struct
sqlite3ExtType sqlite3Autoext
Define Documentation
#define sqlite3_column_database_name 0
Definition at line 34 of file loadext.c.
#define sqlite3_column_database_name16 0
Definition at line 35 of file loadext.c.
#define sqlite3_column_origin_name 0
Definition at line 38 of file loadext.c.
#define sqlite3_column_origin_name16 0
Definition at line 39 of file loadext.c.
#define sqlite3_column_table_name 0
Definition at line 36 of file loadext.c.
#define sqlite3_column_table_name16 0
Definition at line 37 of file loadext.c.
#define sqlite3_table_column_metadata 0
Definition at line 40 of file loadext.c.
#define SQLITE_CORE 1
Definition at line 19 of file loadext.c.
#define wsdAutoext sqlite3Autoext
Definition at line 503 of file loadext.c.
Referenced by sqlite3_auto_extension(), sqlite3_reset_auto_extension(), and sqlite3AutoLoadExtensions().
#define wsdAutoextInit
Definition at line 502 of file loadext.c.
Referenced by sqlite3_auto_extension(), sqlite3_reset_auto_extension(), and sqlite3AutoLoadExtensions().
Typedef Documentation
typedef struct sqlite3ExtType sqlite3ExtType
Definition at line 485 of file loadext.c.
Function Documentation
int sqlite3_auto_extension (void * xInit)
Definition at line 511 of file loadext.c.
References sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_realloc(), sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_NOMEM, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
int sqlite3_enable_load_extension (sqlite3 * db, int onoff)
Definition at line 454 of file loadext.c.
References sqlite3::flags, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_LoadExtension, and SQLITE_OK.
Referenced by DbObjCmd(), and open_db().
int sqlite3_load_extension (sqlite3 * db, const char * zFile, const char * zProc, char ** pzErrMsg)
Definition at line 424 of file loadext.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3LoadExtension().
Referenced by do_meta_command(), and loadExt().
void sqlite3_reset_auto_extension (void)
Definition at line 550 of file loadext.c.
References sqlite3_free(), sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
int sqlite3AutoLoadExtensions (sqlite3 * db)
Definition at line 570 of file loadext.c.
References sqlite3_free(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3Error(), sqlite3MutexAlloc, SQLITE_ERROR, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
Referenced by openDatabase().
void sqlite3CloseExtensions (sqlite3 * db)
Definition at line 441 of file loadext.c.
References sqlite3::aExtension, sqlite3::mutex, sqlite3::nExtension, sqlite3::pVfs, sqlite3_mutex_held, sqlite3DbFree(), and sqlite3OsDlClose().
static int sqlite3LoadExtension (sqlite3 * db, const char * zFile, const char * zProc, char ** pzErrMsg) [static]
Definition at line 347 of file loadext.c.
References sqlite3::aExtension, sqlite3::flags, sqlite3::nExtension, sqlite3::pVfs, sqlite3_free(), sqlite3_mprintf(), sqlite3_snprintf(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DbStrDup(), sqlite3OsDlClose(), sqlite3OsDlError(), sqlite3OsDlOpen(), sqlite3OsDlSym(), SQLITE_ERROR, SQLITE_LoadExtension, SQLITE_NOMEM, and SQLITE_OK.
Referenced by sqlite3_load_extension().
Variable Documentation
const sqlite3_api_routines sqlite3Apis [static]
Definition at line 125 of file loadext.c.
SQLITE_WSD struct sqlite3ExtType sqlite3Autoext [static]
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1