ContextLogger2 Logger Daemon Internals: local_server.cpp File Reference
local_server.cpp File Reference
Classes
struct _LocalServer
Functions
LocalServer * LocalServer_new (GError **error)
gboolean LocalServer_start (LocalServer *self, GError **error)
void LocalServer_stop (LocalServer *self)
void LocalServer_destroy (LocalServer *self)
Function Documentation
void LocalServer_destroy (LocalServer * self)
Definition at line 72 of file local_server.cpp.
Referenced by kr_Controller_destroy().
LocalServer* LocalServer_new (GError ** error)
Definition at line 23 of file local_server.cpp.
References gx_error_no_memory.
Referenced by kr_Controller_new().
gboolean LocalServer_start (LocalServer * self, GError ** error)
Definition at line 36 of file local_server.cpp.
References domain_symbian, gx_error_new(), logt, CCliapiServer::NewL(), plat_error_strerror, and CCliapiServer::Start().
Referenced by kr_Controller_start().
void LocalServer_stop (LocalServer * self)
Definition at line 64 of file local_server.cpp.
Referenced by kr_Controller_stop().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1