ContextLogger2 Logger Daemon Internals: logging.cpp File Reference
logging.cpp File Reference
Functions
void log_text (const char *logfile, const char *s)
void __log_ctx (const char *logfile, const char *func, const char *file, int line, const char *s)
void log_fmt (const char *logfile, const char *fmt,...)
Function Documentation
void __log_ctx (const char * logfile, const char * func, const char * file, int line, const char * s)
Definition at line 96 of file logging.cpp.
void log_fmt (const char * logfile, const char * fmt, ...)
Definition at line 102 of file logging.cpp.
void log_text (const char * logfile, const char * s)
Definition at line 90 of file logging.cpp.
Referenced by cl2GlobalInit(), log_time_f(), and MainL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1