ContextLogger2 Logger Daemon Internals: lparser.h File Reference
lparser.h File Reference
Classes
struct expdesc
struct upvaldesc
struct FuncState
Enumerations
enum expkind {
VVOID, VNIL, VTRUE, VFALSE,
VK, VKNUM, VLOCAL, VUPVAL,
VGLOBAL, VINDEXED, VJMP, VRELOCABLE,
VNONRELOC, VCALL, VVARARG
}
Functions
LUAI_FUNC Proto * luaY_parser (lua_State *L, ZIO *z, Mbuffer *buff, const char *name)
Enumeration Type Documentation
enum expkind
Enumerator:
VVOID
VNIL
VTRUE
VFALSE
VK
VKNUM
VLOCAL
VUPVAL
VGLOBAL
VINDEXED
VJMP
VRELOCABLE
VNONRELOC
VCALL
VVARARG
Definition at line 19 of file lparser.h.
Function Documentation
LUAI_FUNC Proto* luaY_parser (lua_State * L, ZIO * z, Mbuffer * buff, const char * name)
Definition at line 383 of file lparser.c.
References LexState::buff, check, chunk(), close_func(), FuncState::f, LexState::fs, Proto::is_vararg, lua_assert, luaS_new, luaX_next(), luaX_setinput(), Proto::nups, open_func(), FuncState::prev, TK_EOS, and VARARG_ISVARARG.
Referenced by f_parser().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1