ContextLogger2 Logger Daemon Internals: lstring.c File Reference
lstring.c File Reference
Defines
#define lstring_c
#define LUA_CORE
Functions
void luaS_resize (lua_State *L, int newsize)
static TString * newlstr (lua_State *L, const char *str, size_t l, unsigned int h)
TString * luaS_newlstr (lua_State *L, const char *str, size_t l)
Udata * luaS_newudata (lua_State *L, size_t s, Table *e)
Define Documentation
#define lstring_c
Definition at line 10 of file lstring.c.
#define LUA_CORE
Definition at line 11 of file lstring.c.
Function Documentation
TString* luaS_newlstr (lua_State * L, const char * str, size_t l)
Definition at line 75 of file lstring.c.
References cast, changewhite, G, GCObject::gch, getstr, isdead, TString::len, lmod, newlstr(), rawgco2ts, and TString::tsv.
Referenced by LoadString(), lua_concat(), lua_pushlstring(), luaO_pushvfstring(), luaV_concat(), and luaX_newstring().
Udata* luaS_newudata (lua_State * L, size_t s, Table * e)
Definition at line 96 of file lstring.c.
References cast, Udata::env, G, Udata::len, LUA_TUSERDATA, luaC_white, luaM_malloc, luaM_toobig(), MAX_SIZET, Udata::metatable, obj2gco, and Udata::uv.
Referenced by lua_newuserdata().
void luaS_resize (lua_State * L, int newsize)
Definition at line 22 of file lstring.c.
References cast_int, G, GCObject::gch, gco2ts, GCSsweepstring, stringtable::hash, lmod, lua_assert, luaM_freearray, luaM_newvector, next, and stringtable::size.
Referenced by checkSizes(), f_luaopen(), and newlstr().
static TString* newlstr (lua_State * L, const char * str, size_t l, unsigned int h) [static]
Definition at line 50 of file lstring.c.
References cast, G, stringtable::hash, TString::hash, TString::len, lmod, LUA_TSTRING, luaC_white, luaM_malloc, luaM_toobig(), luaS_resize(), MAX_INT, MAX_SIZET, stringtable::nuse, obj2gco, TString::reserved, stringtable::size, and TString::tsv.
Referenced by luaS_newlstr().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1