ContextLogger2 Logger Daemon Internals: lua_bindings.cpp File Reference
lua_bindings.cpp File Reference
Defines
#define luai_check(L, cond) { if (!(cond)) { } }
#define luai_checknelems(L, n) luai_check(L, (n) <= (L->top - L->base))
#define throw_error_unsupported { return lua_error_unsupported(L); }
Functions
static int lua_error_unsupported (lua_State *L)
static int f_static_get_str (lua_State *L)
static int f_throw_unsupported (lua_State *L)
static int f_die_now (lua_State *L)
static int f_shutdown (lua_State *L)
static int f_log (lua_State *L)
static int f_is_ascii_ident (lua_State *L)
static int f_iap_id_by_name (lua_State *L)
static int f_get_username (lua_State *L)
static int f_config_get (lua_State *L)
static int f_config_set (lua_State *L)
static int f_all_sensor_names (lua_State *L)
static int f_is_sensor_supported (lua_State *L)
static int f_is_sensor_running (lua_State *L)
static int f_sensor_stop (lua_State *L)
static int f_sensor_start (lua_State *L)
static int f_upload_now (lua_State *L)
static int f_get_upload_time (lua_State *L)
static int f_remokon_start (lua_State *L)
static int f_remokon_timed (lua_State *L)
static int f_remokon_stop (lua_State *L)
static int f_log_message (lua_State *L)
static int f_are_uploads_allowed (lua_State *L)
int luaopen_cl2 (lua_State *L)
Variables
static const luaL_Reg function_table []
Define Documentation
#define luai_check (L, cond) { if (!(cond)) { } }
Definition at line 21 of file lua_bindings.cpp.
#define luai_checknelems (L, n) luai_check(L, (n) <= (L->top - L->base))
Definition at line 22 of file lua_bindings.cpp.
#define throw_error_unsupported { return lua_error_unsupported(L); }
Definition at line 31 of file lua_bindings.cpp.
Referenced by f_iap_id_by_name(), and f_throw_unsupported().
Function Documentation
static int f_all_sensor_names (lua_State * L) [static]
Definition at line 182 of file lua_bindings.cpp.
References ALL_SENSOR_NAMES_LITERAL_LIST, lua_createtable(), lua_pushstring(), lua_rawseti(), and NUM_ALL_SENSORS.
static int f_are_uploads_allowed (lua_State * L) [static]
Definition at line 337 of file lua_bindings.cpp.
References ac_global_Controller, _kr_Controller::are_uploads_allowed, and lua_pushboolean().
static int f_config_get (lua_State * L) [static]
Definition at line 142 of file lua_bindings.cpp.
References ac_DYNAMIC_GET_ERR, is_not_found_error, lua_pop, lua_pushnil(), lua_pushstring(), lua_raise_gerror(), and luaL_checklstring().
static int f_config_set (lua_State * L) [static]
Definition at line 163 of file lua_bindings.cpp.
References ac_DYNAMIC_SET_ERR, logg, logt, lua_pop, lua_raise_gerror(), and luaL_checklstring().
static int f_die_now (lua_State * L) [static]
Definition at line 64 of file lua_bindings.cpp.
References EXIT_APPLICATION.
static int f_get_upload_time (lua_State * L) [static]
Definition at line 262 of file lua_bindings.cpp.
References ac_global_Registry, lua_pushinteger(), and lua_pushnil().
static int f_get_username (lua_State * L) [static]
Definition at line 133 of file lua_bindings.cpp.
References ac_global_RcFile, and lua_pushstring().
static int f_iap_id_by_name (lua_State * L) [static]
Definition at line 104 of file lua_bindings.cpp.
References epoc_iap_by_name(), lua_pop, lua_pushinteger(), lua_pushnil(), lua_raise_gerror(), luaL_checklstring(), and throw_error_unsupported.
static int f_is_ascii_ident (lua_State * L) [static]
Definition at line 94 of file lua_bindings.cpp.
References is_ascii_ident(), lua_pushboolean(), and luaL_checklstring().
static int f_is_sensor_running (lua_State * L) [static]
Definition at line 208 of file lua_bindings.cpp.
References ac_global_Controller, lua_pushboolean(), luaL_checklstring(), sa_Array_sensor_is_running(), and _kr_Controller::scanner.
static int f_is_sensor_supported (lua_State * L) [static]
Definition at line 198 of file lua_bindings.cpp.
References lua_pushboolean(), luaL_checklstring(), and sa_sensor_is_supported().
static int f_log (lua_State * L) [static]
Definition at line 82 of file lua_bindings.cpp.
References logt, and luaL_checklstring().
static int f_log_message (lua_State * L) [static]
Definition at line 321 of file lua_bindings.cpp.
References ac_global_LogDb, log_db_log_appmessage(), lua_error_unsupported(), lua_raise_gerror(), and luaL_checklstring().
static int f_remokon_start (lua_State * L) [static]
Definition at line 275 of file lua_bindings.cpp.
References ac_global_Controller, lua_error_unsupported(), lua_raise_gerror(), _kr_Controller::remokon, and rk_Remokon_start().
static int f_remokon_stop (lua_State * L) [static]
Definition at line 308 of file lua_bindings.cpp.
References ac_global_Controller, lua_error_unsupported(), _kr_Controller::remokon, and rk_Remokon_stop().
static int f_remokon_timed (lua_State * L) [static]
Definition at line 291 of file lua_bindings.cpp.
References ac_global_Controller, lua_error_unsupported(), lua_raise_gerror(), luaL_checkint, _kr_Controller::remokon, and rk_Remokon_start_timed().
static int f_sensor_start (lua_State * L) [static]
Definition at line 229 of file lua_bindings.cpp.
References ac_global_Controller, lua_raise_gerror(), luaL_checklstring(), sa_Array_sensor_start(), and _kr_Controller::scanner.
static int f_sensor_stop (lua_State * L) [static]
Definition at line 219 of file lua_bindings.cpp.
References ac_global_Controller, luaL_checklstring(), sa_Array_sensor_stop(), and _kr_Controller::scanner.
static int f_shutdown (lua_State * L) [static]
Definition at line 73 of file lua_bindings.cpp.
References SHUTDOWN_APPLICATION.
static int f_static_get_str (lua_State * L) [static]
Definition at line 36 of file lua_bindings.cpp.
References ac_global_RcFile, lua_pushnil(), lua_pushstring(), and luaL_checklstring().
static int f_throw_unsupported (lua_State * L) [static]
Definition at line 57 of file lua_bindings.cpp.
References throw_error_unsupported.
static int f_upload_now (lua_State * L) [static]
Definition at line 242 of file lua_bindings.cpp.
References ac_global_Controller, lua_error(), lua_error_unsupported(), lua_pushstring(), lua_raise_gerror(), up_Uploader_upload_now(), and _kr_Controller::uploader.
static int lua_error_unsupported (lua_State * L) [static]
Definition at line 24 of file lua_bindings.cpp.
References lua_error(), and lua_pushstring().
Referenced by f_log_message(), f_remokon_start(), f_remokon_stop(), f_remokon_timed(), and f_upload_now().
int luaopen_cl2 (lua_State * L)
Definition at line 373 of file lua_bindings.cpp.
References __APP_NAME__, __COMPILER_NAME__, __VARIANT_NAME__, __VERSION_STRING__, LUA_CL2LIBNAME, lua_pushfstring(), lua_pushnil(), lua_pushstring(), lua_setfield(), and luaL_register().
Variable Documentation
const luaL_Reg function_table[] [static]
Initial value:
 {
  {"are_uploads_allowed", f_are_uploads_allowed},
  {"log_message", f_log_message},
  {"remokon_stop", f_remokon_stop},
  {"remokon_timed", f_remokon_timed},
  {"remokon_start", f_remokon_start},
  {"get_upload_time", f_get_upload_time},
  {"upload_now", f_upload_now},
  {"sensor_start", f_sensor_start},
  {"sensor_stop", f_sensor_stop},
  {"is_sensor_running", f_is_sensor_running},
  {"is_sensor_supported", f_is_sensor_supported},
  {"all_sensor_names", f_all_sensor_names},
  {"config_set", f_config_set},
  {"config_get", f_config_get},
  {"get_username", f_get_username},
  {"iap_id_by_name", f_iap_id_by_name},
  {"is_ascii_ident", f_is_ascii_ident},
  {"log", f_log},
  {"shutdown", f_shutdown},
  {"die_now", f_die_now},
  {"throw_unsupported", f_throw_unsupported},
  {"static_get_str", f_static_get_str},
  {NULL, NULL}
}
Definition at line 345 of file lua_bindings.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1