ContextLogger2 Logger Daemon Internals: lua_bindings.h File Reference
lua_bindings.h File Reference
Defines
#define LUA_CL2LIBNAME "cl2"
Functions
int luaopen_cl2 (lua_State *L)
Define Documentation
#define LUA_CL2LIBNAME "cl2"
Definition at line 10 of file lua_bindings.h.
Referenced by luaopen_cl2().
Function Documentation
int luaopen_cl2 (lua_State * L)
Definition at line 373 of file lua_bindings.cpp.
References __APP_NAME__, __COMPILER_NAME__, __VARIANT_NAME__, __VERSION_STRING__, LUA_CL2LIBNAME, lua_pushfstring(), lua_pushnil(), lua_pushstring(), lua_setfield(), and luaL_register().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1