ContextLogger2 Logger Daemon Internals: lua_cl2.cpp File Reference
lua_cl2.cpp File Reference
Functions
static void my_openlibs (lua_State *L)
lua_State * cl_lua_new ()
lua_State * cl_lua_new_libs ()
gboolean validate_lua_syntax (const gchar *value, GError **error)
int lua_raise_gerror (lua_State *L, GError *error)
GError * lua_get_gerror (lua_State *L)
void lua_set_gerror (lua_State *L, GError **error)
static void txtlog_lua_error (lua_State *L)
int atpanic_throw (lua_State *L)
int atpanic_txtlog_throw (lua_State *L)
int atpanic_txtlog_exit (lua_State *L)
int atpanic_log_exit (lua_State *L)
void * l_alloc (void *ud, void *ptr, size_t osize, size_t nsize)
Variables
static const luaL_Reg my_lualibs []
Function Documentation
int atpanic_log_exit (lua_State * L)
Definition at line 201 of file lua_cl2.cpp.
References er_FATAL, er_log_none, and lua_tostring.
Referenced by cl_lua_new().
int atpanic_throw (lua_State * L)
Definition at line 181 of file lua_cl2.cpp.
Referenced by atpanic_txtlog_throw().
int atpanic_txtlog_exit (lua_State * L)
Definition at line 194 of file lua_cl2.cpp.
References er_fatal(), and txtlog_lua_error().
int atpanic_txtlog_throw (lua_State * L)
Definition at line 188 of file lua_cl2.cpp.
References atpanic_throw(), and txtlog_lua_error().
lua_State* cl_lua_new ()
Definition at line 49 of file lua_cl2.cpp.
References atpanic_log_exit(), l_alloc(), lua_atpanic(), and lua_newstate().
Referenced by cl_lua_new_libs(), and validate_lua_syntax().
lua_State* cl_lua_new_libs ()
Definition at line 64 of file lua_cl2.cpp.
References cl_lua_new(), luaL_openlibs(), and my_openlibs().
Referenced by eval_lua_str(), new_my_lua(), and CCliapiSession::ServiceL().
void* l_alloc (void * ud, void * ptr, size_t osize, size_t nsize)
The code above this notice is covered by the following license:
Copyright 2009 Helsinki Institute for Information Technology (HIIT) and the authors. All rights reserved.
Authors: Tero Hasu <tero.hasu@hut.fi>
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Definition at line 266 of file lua_cl2.cpp.
Referenced by cl_lua_new(), and luaL_newstate().
GError* lua_get_gerror (lua_State * L)
Definition at line 132 of file lua_cl2.cpp.
References domain_lua, gx_error_new_literal(), and lua_tostring.
Referenced by lua_set_gerror().
int lua_raise_gerror (lua_State * L, GError * error)
Definition at line 115 of file lua_cl2.cpp.
References gx_error_to_string(), lua_error(), and lua_pushstring().
Referenced by f_config_get(), f_config_set(), f_iap_id_by_name(), f_log_message(), f_remokon_start(), f_remokon_timed(), f_sensor_start(), and f_upload_now().
void lua_set_gerror (lua_State * L, GError ** error)
Definition at line 140 of file lua_cl2.cpp.
References lua_get_gerror().
Referenced by eval_lua_str().
static void my_openlibs (lua_State * L) [static]
Definition at line 29 of file lua_cl2.cpp.
References luaL_Reg::func, lua_call(), lua_pushcfunction, lua_pushstring(), and luaL_Reg::name.
Referenced by cl_lua_new_libs().
static void txtlog_lua_error (lua_State * L) [static]
Definition at line 149 of file lua_cl2.cpp.
References logg, and lua_tostring.
Referenced by atpanic_txtlog_exit(), and atpanic_txtlog_throw().
gboolean validate_lua_syntax (const gchar * value, GError ** error)
Definition at line 74 of file lua_cl2.cpp.
References cl_lua_new(), domain_lua, gx_error_new(), gx_error_no_memory, lua_close(), LUA_ERRMEM, lua_tostring, and luaL_loadstring().
Referenced by db_set().
Variable Documentation
const luaL_Reg my_lualibs[] [static]
Initial value:
 {
  {LUA_CL2LIBNAME, luaopen_cl2},
  {NULL, NULL}
}
Definition at line 23 of file lua_cl2.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1