ContextLogger2 Logger Daemon Internals: luac.c File Reference
luac.c File Reference
Classes
struct Smain
Defines
#define luac_c
#define LUA_CORE
#define PROGNAME "luac"
#define OUTPUT PROGNAME ".out"
#define IS(s) (strcmp(argv[i],s)==0)
#define toproto(L, i) (clvalue(L->top+(i))->l.p)
Functions
static void fatal (const char *message)
static void cannot (const char *what)
static void usage (const char *message)
static int doargs (int argc, char *argv[])
static const Proto * combine (lua_State *L, int n)
static int writer (lua_State *L, const void *p, size_t size, void *u)
static int pmain (lua_State *L)
int main (int argc, char *argv[])
Variables
static int listing = 0
static int dumping = 1
static int stripping = 0
static char Output [] = { OUTPUT }
static const char * output = Output
static const char * progname = PROGNAME
Define Documentation
#define IS (s) (strcmp(argv[i],s)==0)
Definition at line 68 of file luac.c.
Referenced by doargs(), and pmain().
#define LUA_CORE
Definition at line 13 of file luac.c.
#define luac_c
Definition at line 12 of file luac.c.
#define OUTPUT PROGNAME ".out"
Definition at line 27 of file luac.c.
#define PROGNAME "luac"
Definition at line 26 of file luac.c.
Referenced by combine().
#define toproto (L, i) (clvalue(L->top+(i))->l.p)
Definition at line 117 of file luac.c.
Referenced by combine().
Function Documentation
static void cannot (const char * what) [static]
Definition at line 42 of file luac.c.
References output, and progname.
Referenced by pmain().
static const Proto* combine (lua_State * L, int n) [static]
Definition at line 119 of file luac.c.
References Proto::code, CREATE_ABC, CREATE_ABx, f(), incr_top, luaF_newproto(), luaM_newvector, luaS_newliteral, Proto::maxstacksize, OP_CALL, OP_CLOSURE, OP_RETURN, Proto::p, PROGNAME, setptvalue2s, Proto::sizecode, Proto::sizep, Proto::source, lua_State::top, and toproto.
Referenced by pmain().
static int doargs (int argc, char * argv[]) [static]
Definition at line 70 of file luac.c.
References dumping, IS, listing, LUA_COPYRIGHT, LUA_QL, LUA_RELEASE, Output, output, progname, stripping, and usage().
Referenced by main().
static void fatal (const char * message) [static]
Definition at line 36 of file luac.c.
References progname.
Referenced by main(), and pmain().
int main (int argc, char * argv[])
Definition at line 186 of file luac.c.
References Smain::argc, Smain::argv, doargs(), fatal(), lua_close(), lua_cpcall(), lua_open, lua_tostring, pmain(), and usage().
static int pmain (lua_State * L) [static]
Definition at line 158 of file luac.c.
References Smain::argc, Smain::argv, cannot(), combine(), dumping, f(), fatal(), IS, listing, lua_checkstack(), lua_lock, lua_tostring, lua_touserdata(), lua_unlock, luaL_loadfile(), luaU_dump(), luaU_print(), output, stripping, and writer().
Referenced by main().
static void usage (const char * message) [static]
Definition at line 48 of file luac.c.
References LUA_QL, LUA_QS, Output, and progname.
Referenced by doargs(), and main().
static int writer (lua_State * L, const void * p, size_t size, void * u) [static]
Definition at line 147 of file luac.c.
References UNUSED.
Referenced by pmain().
Variable Documentation
int dumping = 1 [static]
Definition at line 30 of file luac.c.
Referenced by doargs(), and pmain().
int listing = 0 [static]
Definition at line 29 of file luac.c.
Referenced by doargs(), and pmain().
const char* output = Output [static]
Definition at line 33 of file luac.c.
Referenced by cannot(), doargs(), LogSatelliteInfoL(), and pmain().
char Output[] = { OUTPUT } [static]
Definition at line 32 of file luac.c.
Referenced by doargs(), and usage().
const char* progname = PROGNAME [static]
Definition at line 34 of file luac.c.
Referenced by cannot(), doargs(), fatal(), and usage().
int stripping = 0 [static]
Definition at line 31 of file luac.c.
Referenced by doargs(), and pmain().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1