ContextLogger2 Logger Daemon Internals: lualib.h File Reference
lualib.h File Reference
Defines
#define LUA_FILEHANDLE "FILE*"
#define LUA_COLIBNAME "coroutine"
#define LUA_TABLIBNAME "table"
#define LUA_IOLIBNAME "io"
#define LUA_OSLIBNAME "os"
#define LUA_STRLIBNAME "string"
#define LUA_MATHLIBNAME "math"
#define LUA_DBLIBNAME "debug"
#define LUA_LOADLIBNAME "package"
Functions
LUALIB_API int() luaopen_base (lua_State *L)
LUALIB_API int() luaopen_table (lua_State *L)
LUALIB_API int() luaopen_io (lua_State *L)
LUALIB_API int() luaopen_os (lua_State *L)
LUALIB_API int() luaopen_string (lua_State *L)
LUALIB_API int() luaopen_math (lua_State *L)
LUALIB_API int() luaopen_debug (lua_State *L)
LUALIB_API int() luaopen_package (lua_State *L)
LUALIB_API void() luaL_openlibs (lua_State *L)
Define Documentation
#define LUA_COLIBNAME "coroutine"
Definition at line 18 of file lualib.h.
Referenced by luaopen_base().
#define LUA_DBLIBNAME "debug"
Definition at line 36 of file lualib.h.
Referenced by luaopen_debug().
#define LUA_FILEHANDLE "FILE*"
Definition at line 15 of file lualib.h.
Referenced by createmeta(), io_type(), and newfile().
#define LUA_IOLIBNAME "io"
Definition at line 24 of file lualib.h.
Referenced by luaopen_io().
#define LUA_LOADLIBNAME "package"
Definition at line 39 of file lualib.h.
Referenced by luaopen_package().
#define LUA_MATHLIBNAME "math"
Definition at line 33 of file lualib.h.
Referenced by luaopen_math().
#define LUA_OSLIBNAME "os"
Definition at line 27 of file lualib.h.
Referenced by luaopen_os().
#define LUA_STRLIBNAME "string"
Definition at line 30 of file lualib.h.
Referenced by luaopen_string().
#define LUA_TABLIBNAME "table"
Definition at line 21 of file lualib.h.
Referenced by luaopen_table().
Function Documentation
LUALIB_API void() luaL_openlibs (lua_State * L)
Definition at line 29 of file linit.c.
References luaL_Reg::func, lua_call(), lua_pushcfunction, lua_pushstring(), and luaL_Reg::name.
Referenced by cl_lua_new_libs(), and pmain().
LUALIB_API int() luaopen_base (lua_State * L)
Definition at line 675 of file lbaselib.c.
References base_open(), LUA_COLIBNAME, and luaL_register().
LUALIB_API int() luaopen_debug (lua_State * L)
Definition at line 393 of file ldblib.c.
References LUA_DBLIBNAME, and luaL_register().
LUALIB_API int() luaopen_io (lua_State * L)
Definition at line 534 of file liolib.c.
References createmeta(), createstdfile(), io_fclose(), IO_INPUT, io_noclose(), IO_OUTPUT, io_pclose(), LUA_ENVIRONINDEX, lua_getfield(), LUA_IOLIBNAME, lua_pop, lua_replace(), lua_setfenv(), luaL_register(), and newfenv().
LUALIB_API int() luaopen_math (lua_State * L)
Definition at line 251 of file lmathlib.c.
References lua_getfield(), LUA_MATHLIBNAME, lua_pushnumber(), lua_setfield(), luaL_register(), and PI.
LUALIB_API int() luaopen_os (lua_State * L)
Definition at line 243 of file loslib.c.
References LUA_OSLIBNAME, and luaL_register().
LUALIB_API int() luaopen_package (lua_State * L)
Definition at line 664 of file loadlib.c.
References gctm(), LUA_CPATH, LUA_CPATH_DEFAULT, lua_createtable(), LUA_DIRSEP, LUA_ENVIRONINDEX, LUA_EXECDIR, lua_getfield(), LUA_GLOBALSINDEX, LUA_IGMARK, LUA_LOADLIBNAME, lua_newtable, LUA_PATH, LUA_PATH_DEFAULT, LUA_PATH_MARK, LUA_PATHSEP, lua_pop, lua_pushcfunction, lua_pushliteral, lua_pushvalue(), lua_rawseti(), LUA_REGISTRYINDEX, lua_replace(), lua_setfield(), luaL_findtable(), luaL_newmetatable(), luaL_register(), and setpath().
LUALIB_API int() luaopen_string (lua_State * L)
Definition at line 865 of file lstrlib.c.
References createmetatable(), lua_getfield(), lua_setfield(), LUA_STRLIBNAME, and luaL_register().
LUALIB_API int() luaopen_table (lua_State * L)
Definition at line 283 of file ltablib.c.
References LUA_TABLIBNAME, and luaL_register().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1