ContextLogger2 Logger Daemon Internals: lundump.h File Reference
lundump.h File Reference
Defines
#define LUAC_VERSION 0x51
#define LUAC_FORMAT 0
#define LUAC_HEADERSIZE 12
Functions
LUAI_FUNC Proto * luaU_undump (lua_State *L, ZIO *Z, Mbuffer *buff, const char *name)
LUAI_FUNC void luaU_header (char *h)
LUAI_FUNC int luaU_dump (lua_State *L, const Proto *f, lua_Writer w, void *data, int strip)
LUAI_FUNC void luaU_print (const Proto *f, int full)
Define Documentation
#define LUAC_FORMAT 0
Definition at line 31 of file lundump.h.
Referenced by luaU_header().
#define LUAC_HEADERSIZE 12
Definition at line 34 of file lundump.h.
Referenced by DumpHeader(), and LoadHeader().
#define LUAC_VERSION 0x51
Definition at line 28 of file lundump.h.
Referenced by luaU_header().
Function Documentation
LUAI_FUNC int luaU_dump (lua_State * L, const Proto * f, lua_Writer w, void * data, int strip)
Definition at line 153 of file ldump.c.
References DumpState::data, DumpFunction(), DumpHeader(), DumpState::L, DumpState::status, DumpState::strip, and DumpState::writer.
Referenced by lua_dump(), and pmain().
LUAI_FUNC void luaU_header (char * h)
Definition at line 214 of file lundump.c.
References LUA_SIGNATURE, LUAC_FORMAT, and LUAC_VERSION.
Referenced by DumpHeader(), and LoadHeader().
LUAI_FUNC void luaU_print (const Proto * f, int full)
Referenced by pmain().
LUAI_FUNC Proto* luaU_undump (lua_State * L, ZIO * Z, Mbuffer * buff, const char * name)
Definition at line 195 of file lundump.c.
References LoadState::b, LoadState::L, LoadFunction(), LoadHeader(), LUA_SIGNATURE, luaS_newliteral, LoadState::name, S, and LoadState::Z.
Referenced by f_parser().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1