ContextLogger2 Logger Daemon Internals: main_epoc.cpp File Reference
main_epoc.cpp File Reference
Classes
class CMainObj
Functions
void ExitApplication ()
void ShutdownApplication ()
static TInt MainLoop ()
static TInt SubMain ()
GLDEF_C TInt E32Main ()
Variables
static CActiveSchedulerWait * globalLoop = NULL
Function Documentation
GLDEF_C TInt E32Main ()
Definition at line 154 of file main_epoc.cpp.
References SubMain(), WITH_ACTIVE_SCHEDULER, and WITH_CLEANUP_STACK.
void ExitApplication ()
Definition at line 20 of file main_epoc.cpp.
References logt.
static TInt MainLoop () [static]
Definition at line 101 of file main_epoc.cpp.
References globalLoop, and CMainObj::NewL().
Referenced by SubMain().
void ShutdownApplication ()
Definition at line 29 of file main_epoc.cpp.
References ExitApplication(), globalLoop, and logt.
static TInt SubMain () [static]
Definition at line 125 of file main_epoc.cpp.
References cl2GlobalCleanup(), cl2GlobalInit(), and MainLoop().
Referenced by E32Main().
Variable Documentation
CActiveSchedulerWait* globalLoop = NULL [static]
Definition at line 17 of file main_epoc.cpp.
Referenced by MainLoop(), and ShutdownApplication().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1