ContextLogger2 Logger Daemon Internals: main.c File Reference
main.c File Reference
Functions
const char * sqlite3_libversion (void)
int sqlite3_libversion_number (void)
int sqlite3_threadsafe (void)
int sqlite3_initialize (void)
int sqlite3_shutdown (void)
int sqlite3_config (int op,...)
static int setupLookaside (sqlite3 *db, void *pBuf, int sz, int cnt)
sqlite3_mutex * sqlite3_db_mutex (sqlite3 *db)
int sqlite3_db_config (sqlite3 *db, int op,...)
static int allSpaces (const char *z, int n)
static int binCollFunc (void *padFlag, int nKey1, const void *pKey1, int nKey2, const void *pKey2)
static int nocaseCollatingFunc (void *NotUsed, int nKey1, const void *pKey1, int nKey2, const void *pKey2)
sqlite_int64 sqlite3_last_insert_rowid (sqlite3 *db)
int sqlite3_changes (sqlite3 *db)
int sqlite3_total_changes (sqlite3 *db)
EXPORT_C int sqlite3_close (sqlite3 *db)
void sqlite3RollbackAll (sqlite3 *db)
const char * sqlite3ErrStr (int rc)
static int sqliteDefaultBusyCallback (void *ptr, int count)
int sqlite3InvokeBusyHandler (BusyHandler *p)
int sqlite3_busy_handler (sqlite3 *db, int(*xBusy)(void *, int), void *pArg)
void sqlite3_progress_handler (sqlite3 *db, int nOps, int(*xProgress)(void *), void *pArg)
int sqlite3_busy_timeout (sqlite3 *db, int ms)
void sqlite3_interrupt (sqlite3 *db)
int sqlite3CreateFunc (sqlite3 *db, const char *zFunctionName, int nArg, int enc, void *pUserData, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_create_function (sqlite3 *db, const char *zFunctionName, int nArg, int enc, void *p, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_create_function16 (sqlite3 *db, const void *zFunctionName, int nArg, int eTextRep, void *p, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_overload_function (sqlite3 *db, const char *zName, int nArg)
void * sqlite3_trace (sqlite3 *db, void(*xTrace)(void *, const char *), void *pArg)
void * sqlite3_profile (sqlite3 *db, void(*xProfile)(void *, const char *, sqlite_uint64), void *pArg)
void * sqlite3_commit_hook (sqlite3 *db, int(*xCallback)(void *), void *pArg)
void * sqlite3_update_hook (sqlite3 *db, void(*xCallback)(void *, int, char const *, char const *, sqlite_int64), void *pArg)
void * sqlite3_rollback_hook (sqlite3 *db, void(*xCallback)(void *), void *pArg)
int sqlite3BtreeFactory (const sqlite3 *db, const char *zFilename, int omitJournal, int nCache, int vfsFlags, Btree **ppBtree)
EXPORT_C const char * sqlite3_errmsg (sqlite3 *db)
const void * sqlite3_errmsg16 (sqlite3 *db)
int sqlite3_errcode (sqlite3 *db)
int sqlite3_extended_errcode (sqlite3 *db)
static int createCollation (sqlite3 *db, const char *zName, int enc, void *pCtx, int(*xCompare)(void *, int, const void *, int, const void *), void(*xDel)(void *))
int sqlite3_limit (sqlite3 *db, int limitId, int newLimit)
static int openDatabase (const char *zFilename, sqlite3 **ppDb, unsigned flags, const char *zVfs)
EXPORT_C int sqlite3_open (const char *zFilename, sqlite3 **ppDb)
int sqlite3_open_v2 (const char *filename, sqlite3 **ppDb, int flags, const char *zVfs)
int sqlite3_open16 (const void *zFilename, sqlite3 **ppDb)
int sqlite3_create_collation (sqlite3 *db, const char *zName, int enc, void *pCtx, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_create_collation_v2 (sqlite3 *db, const char *zName, int enc, void *pCtx, int(*xCompare)(void *, int, const void *, int, const void *), void(*xDel)(void *))
int sqlite3_create_collation16 (sqlite3 *db, const void *zName, int enc, void *pCtx, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_collation_needed (sqlite3 *db, void *pCollNeededArg, void(*xCollNeeded)(void *, sqlite3 *, int eTextRep, const char *))
int sqlite3_collation_needed16 (sqlite3 *db, void *pCollNeededArg, void(*xCollNeeded16)(void *, sqlite3 *, int eTextRep, const void *))
int sqlite3_global_recover (void)
int sqlite3_get_autocommit (sqlite3 *db)
void sqlite3_thread_cleanup (void)
int sqlite3_sleep (int ms)
EXPORT_C int sqlite3_extended_result_codes (sqlite3 *db, int onoff)
int sqlite3_file_control (sqlite3 *db, const char *zDbName, int op, void *pArg)
int sqlite3_test_control (int op,...)
Variables
const char sqlite3_version [] = SQLITE_VERSION
char * sqlite3_temp_directory = 0
static const int aHardLimit []
Function Documentation
static int allSpaces (const char * z, int n) [static]
Definition at line 455 of file main.c.
Referenced by binCollFunc().
static int binCollFunc (void * padFlag, int nKey1, const void * pKey1, int nKey2, const void * pKey2) [static]
Definition at line 467 of file main.c.
References allSpaces().
Referenced by openDatabase().
static int createCollation (sqlite3 * db, const char * zName, int enc, void * pCtx, int(*)(void *, int, const void *, int, const void *) xCompare, void(*)(void *) xDel) [static]
Definition at line 1282 of file main.c.
References sqlite3::aCollSeq, sqlite3::activeVdbeCnt, CollSeq::enc, sqlite3::mutex, CollSeq::pUser, sqlite3_mutex_held, sqlite3Error(), sqlite3ExpirePreparedStatements(), sqlite3FindCollSeq(), sqlite3HashFind(), sqlite3Strlen(), SQLITE_BUSY, SQLITE_MISUSE, SQLITE_OK, SQLITE_UTF16, SQLITE_UTF16_ALIGNED, SQLITE_UTF16NATIVE, CollSeq::xCmp, and CollSeq::xDel.
Referenced by openDatabase(), sqlite3_create_collation(), sqlite3_create_collation16(), and sqlite3_create_collation_v2().
static int nocaseCollatingFunc (void * NotUsed, int nKey1, const void * pKey1, int nKey2, const void * pKey2) [static]
Definition at line 497 of file main.c.
References sqlite3StrNICmp().
Referenced by openDatabase().
static int openDatabase (const char * zFilename, sqlite3 ** ppDb, unsigned flags, const char * zVfs) [static]
Definition at line 1438 of file main.c.
References sqlite3::aCollSeq, sqlite3::aDb, sqlite3::aDbStatic, sqlite3::aLimit, sqlite3::aModule, sqlite3::autoCommit, binCollFunc(), createCollation(), sqlite3::dfltLockMode, sqlite3::errMask, sqlite3::flags, sqlite3::magic, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::nDb, sqlite3::nextAutovac, sqlite3::nextPagesize, nocaseCollatingFunc(), sqlite3::openFlags, Db::pBt, sqlite3::pDfltColl, sqlite3::priorNewRowid, Db::pSchema, sqlite3::pVfs, Db::safety_level, setupLookaside(), sqlite3_close(), sqlite3_errcode(), sqlite3_free(), sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_vfs_find(), sqlite3ApiExit(), sqlite3AutoLoadExtensions(), sqlite3BtreeFactory(), sqlite3BtreePager(), sqlite3Error(), sqlite3FindCollSeq(), sqlite3Fts1Init(), sqlite3Fts2Init(), sqlite3Fts3Init(), sqlite3GlobalConfig, sqlite3HashInit(), sqlite3IcuInit(), sqlite3MallocZero(), sqlite3MutexAlloc, sqlite3PagerLockingMode(), sqlite3RegisterBuiltinFunctions(), sqlite3RtreeInit(), sqlite3SchemaGet(), SQLITE_COLL_BINARY, SQLITE_COLL_NOCASE, SQLITE_DEFAULT_CACHE_SIZE, SQLITE_ERROR, SQLITE_IOERR_NOMEM, SQLITE_LegacyFileFmt, SQLITE_LoadExtension, SQLITE_MAGIC_BUSY, SQLITE_MAGIC_OPEN, SQLITE_MAGIC_SICK, SQLITE_MUTEX_RECURSIVE, SQLITE_NOMEM, SQLITE_OK, SQLITE_OPEN_DELETEONCLOSE, SQLITE_OPEN_FULLMUTEX, SQLITE_OPEN_MAIN_DB, SQLITE_OPEN_MAIN_JOURNAL, SQLITE_OPEN_MASTER_JOURNAL, SQLITE_OPEN_NOMUTEX, SQLITE_OPEN_SUBJOURNAL, SQLITE_OPEN_TEMP_DB, SQLITE_OPEN_TEMP_JOURNAL, SQLITE_OPEN_TRANSIENT_DB, SQLITE_ShortColNames, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, CollSeq::type, and Db::zName.
Referenced by sqlite3_open(), sqlite3_open16(), and sqlite3_open_v2().
static int setupLookaside (sqlite3 * db, void * pBuf, int sz, int cnt) [static]
Definition at line 369 of file main.c.
References Lookaside::bEnabled, Lookaside::bMalloced, sqlite3::lookaside, Lookaside::nOut, Lookaside::pEnd, Lookaside::pFree, LookasideSlot::pNext, Lookaside::pStart, sqlite3_free(), sqlite3BeginBenignMalloc(), sqlite3EndBenignMalloc(), sqlite3Malloc(), SQLITE_BUSY, SQLITE_OK, and Lookaside::sz.
Referenced by openDatabase(), and sqlite3_db_config().
int sqlite3_busy_handler (sqlite3 * db, int(*)(void *, int) xBusy, void * pArg)
Definition at line 782 of file main.c.
References sqlite3::busyHandler, sqlite3::mutex, BusyHandler::nBusy, BusyHandler::pArg, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_OK, and BusyHandler::xFunc.
Referenced by DbObjCmd(), FUNC(), and sqlite3_busy_timeout().
int sqlite3_busy_timeout (sqlite3 * db, int ms)
Definition at line 826 of file main.c.
References sqlite3::busyTimeout, sqlite3_busy_handler(), SQLITE_OK, and sqliteDefaultBusyCallback().
Referenced by DbObjCmd(), do_meta_command(), and FUNC().
int sqlite3_changes (sqlite3 * db)
Definition at line 520 of file main.c.
References sqlite3::nChange.
Referenced by changes(), DbObjCmd(), and FUNC().
EXPORT_C int sqlite3_close (sqlite3 * db)
Definition at line 534 of file main.c.
References FuncDefHash::a, sqlite3::aCollSeq, sqlite3::aDb, sqlite3::aDbStatic, sqlite3::aFunc, sqlite3::aModule, ArraySize, Lookaside::bMalloced, sqlite3::lookaside, sqlite3::magic, sqlite3::mutex, sqlite3::nDb, Lookaside::nOut, Module::pAux, Db::pBt, sqlite3::pErr, FuncDef::pHash, FuncDef::pNext, Db::pSchema, Lookaside::pStart, sqlite3::pVdbe, sqlite3_free(), sqlite3_mutex_enter, sqlite3_mutex_free, sqlite3_mutex_leave, sqlite3BtreeClose(), sqlite3CloseExtensions, sqlite3DbFree(), sqlite3Error(), sqlite3HashClear(), sqlite3ResetInternalSchema(), sqlite3SafetyCheckSickOrOk(), sqlite3ValueFree(), sqlite3VtabRollback(), SQLITE_BUSY, SQLITE_MAGIC_CLOSED, SQLITE_MAGIC_ERROR, SQLITE_MISUSE, SQLITE_OK, sqliteHashData, sqliteHashFirst, sqliteHashNext, CollSeq::xDel, and Module::xDestroy.
Referenced by close_config_db_session(), create_database(), DbDeleteCmd(), DbMain(), log_db_close_session(), main(), and openDatabase().
int sqlite3_collation_needed (sqlite3 * db, void * pCollNeededArg, void(*)(void *, sqlite3 *, int eTextRep, const char *) xCollNeeded)
Definition at line 1780 of file main.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_OK, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_collation_needed16 (sqlite3 * db, void * pCollNeededArg, void(*)(void *, sqlite3 *, int eTextRep, const void *) xCollNeeded16)
Definition at line 1798 of file main.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_OK, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
void* sqlite3_commit_hook (sqlite3 * db, int(*)(void *) xCallback, void * pArg)
Definition at line 1054 of file main.c.
References sqlite3::mutex, sqlite3::pCommitArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xCommitCallback.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_config (int op, ...)
Definition at line 234 of file main.c.
References sqlite3GlobalConfig, sqlite3MemGetMemsys3(), sqlite3MemGetMemsys5(), sqlite3MemSetDefault(), SQLITE_CONFIG_GETMALLOC, SQLITE_CONFIG_GETMUTEX, SQLITE_CONFIG_HEAP, SQLITE_CONFIG_LOOKASIDE, SQLITE_CONFIG_MALLOC, SQLITE_CONFIG_MEMSTATUS, SQLITE_CONFIG_MULTITHREAD, SQLITE_CONFIG_MUTEX, SQLITE_CONFIG_PAGECACHE, SQLITE_CONFIG_SCRATCH, SQLITE_CONFIG_SERIALIZED, SQLITE_CONFIG_SINGLETHREAD, SQLITE_ERROR, SQLITE_MISUSE, and SQLITE_OK.
int sqlite3_create_collation (sqlite3 * db, const char * zName, int enc, void * pCtx, int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 1714 of file main.c.
References createCollation(), sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3ApiExit().
Referenced by DbObjCmd(), and FUNC().
int sqlite3_create_collation16 (sqlite3 * db, const void * zName, int enc, void * pCtx, int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 1754 of file main.c.
References createCollation(), sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3DbFree(), sqlite3Utf16to8(), and SQLITE_OK.
int sqlite3_create_collation_v2 (sqlite3 * db, const char * zName, int enc, void * pCtx, int(*)(void *, int, const void *, int, const void *) xCompare, void(*)(void *) xDel)
Definition at line 1733 of file main.c.
References createCollation(), sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3ApiExit().
Referenced by icuLoadCollation().
int sqlite3_create_function (sqlite3 * db, const char * zFunctionName, int nArg, int enc, void * p, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 935 of file main.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), and sqlite3CreateFunc().
Referenced by DbObjCmd(), FUNC(), open_db(), sqlite3Fts2InitHashTable(), sqlite3Fts3InitHashTable(), and sqlite3IcuInit().
int sqlite3_create_function16 (sqlite3 * db, const void * zFunctionName, int nArg, int eTextRep, void * p, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 954 of file main.c.
References sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3DbFree(), and sqlite3Utf16to8().
int sqlite3_db_config (sqlite3 * db, int op, ...)
Definition at line 420 of file main.c.
References setupLookaside(), SQLITE_DBCONFIG_LOOKASIDE, and SQLITE_ERROR.
sqlite3_mutex* sqlite3_db_mutex (sqlite3 * db)
Definition at line 413 of file main.c.
References sqlite3::mutex.
int sqlite3_errcode (sqlite3 * db)
Definition at line 1259 of file main.c.
References sqlite3::errCode, sqlite3::errMask, sqlite3::mallocFailed, sqlite3SafetyCheckSickOrOk(), SQLITE_MISUSE, and SQLITE_NOMEM.
Referenced by DbMain(), DbObjCmd(), execSql(), FUNC(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), open_db(), openDatabase(), prepare_sql_statements(), and sqlite3_exec().
EXPORT_C const char* sqlite3_errmsg (sqlite3 * db)
Definition at line 1185 of file main.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_value_text(), sqlite3ErrStr(), sqlite3SafetyCheckSickOrOk(), SQLITE_MISUSE, and SQLITE_NOMEM.
Referenced by createIncrblobChannel(), DbMain(), DbObjCmd(), do_meta_command(), FUNC(), incrblobClose(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), main(), open_db(), optimizeFunc(), prepare_sql_statements(), process_input(), sqlite3_blob_open(), and sqlite3_exec().
const void* sqlite3_errmsg16 (sqlite3 * db)
Definition at line 1209 of file main.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_value_text16(), sqlite3ErrStr(), sqlite3SafetyCheckSickOrOk(), sqlite3ValueSetStr(), SQLITE_STATIC, SQLITE_UTF16LE, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
int sqlite3_extended_errcode (sqlite3 * db)
Definition at line 1268 of file main.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3SafetyCheckSickOrOk(), SQLITE_MISUSE, and SQLITE_NOMEM.
EXPORT_C int sqlite3_extended_result_codes (sqlite3 * db, int onoff)
Definition at line 1993 of file main.c.
References sqlite3::errMask, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and SQLITE_OK.
int sqlite3_file_control (sqlite3 * db, const char * zDbName, int op, void * pArg)
Definition at line 2003 of file main.c.
References sqlite3::aDb, sqlite3::mutex, sqlite3::nDb, Db::pBt, sqlite3_file::pMethods, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3BtreeEnter, sqlite3BtreeLeave, sqlite3BtreePager(), sqlite3OsFileControl(), sqlite3PagerFile(), SQLITE_ERROR, and Db::zName.
Referenced by sqlite3Pragma().
int sqlite3_get_autocommit (sqlite3 * db)
Definition at line 1832 of file main.c.
References sqlite3::autoCommit.
Referenced by DbObjCmd().
int sqlite3_global_recover (void)
Definition at line 1818 of file main.c.
References SQLITE_OK.
int sqlite3_initialize (void)
Definition at line 90 of file main.c.
References GLOBAL, sqlite3_mutex_enter, sqlite3_mutex_free, sqlite3_mutex_leave, sqlite3_os_init(), sqlite3GlobalConfig, sqlite3GlobalFunctions, sqlite3IsNaN(), sqlite3MallocInit(), sqlite3MutexAlloc, sqlite3MutexInit, sqlite3PCacheBufferSetup(), sqlite3PcacheInitialize(), sqlite3RegisterGlobalFunctions(), SQLITE_MUTEX_RECURSIVE, SQLITE_MUTEX_STATIC_MASTER, SQLITE_NOMEM, and SQLITE_OK.
Referenced by openDatabase(), sqlite3_auto_extension(), sqlite3_complete16(), sqlite3_malloc(), sqlite3_mprintf(), sqlite3_mutex_alloc(), sqlite3_open16(), sqlite3_realloc(), sqlite3_reset_auto_extension(), sqlite3_soft_heap_limit(), sqlite3_vfs_find(), sqlite3_vfs_register(), and sqlite3_vmprintf().
void sqlite3_interrupt (sqlite3 * db)
Definition at line 839 of file main.c.
References sqlite3::isInterrupted, and sqlite3::u1.
Referenced by DbObjCmd(), FUNC(), and sqlite3VdbeExec().
sqlite_int64 sqlite3_last_insert_rowid (sqlite3 * db)
Definition at line 513 of file main.c.
References sqlite3::lastRowid.
Referenced by block_insert(), DbObjCmd(), FUNC(), index_insert(), and last_insert_rowid().
const char* sqlite3_libversion (void)
Definition at line 36 of file main.c.
References sqlite3_version.
Referenced by DbObjCmd(), FUNC(), and main().
int sqlite3_libversion_number (void)
Definition at line 37 of file main.c.
References SQLITE_VERSION_NUMBER.
int sqlite3_limit (sqlite3 * db, int limitId, int newLimit)
Definition at line 1418 of file main.c.
References sqlite3::aLimit, and SQLITE_N_LIMIT.
EXPORT_C int sqlite3_open (const char * zFilename, sqlite3 ** ppDb)
Definition at line 1657 of file main.c.
References openDatabase(), SQLITE_OPEN_CREATE, and SQLITE_OPEN_READWRITE.
Referenced by create_database(), log_db_open_session(), open_config_db_session(), and open_db().
int sqlite3_open16 (const void * zFilename, sqlite3 ** ppDb)
Definition at line 1677 of file main.c.
References DB_SchemaLoaded, DbHasProperty, ENC, openDatabase(), sqlite3_initialize(), sqlite3ApiExit(), sqlite3ValueFree(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3ValueText(), SQLITE_NOMEM, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_READWRITE, SQLITE_STATIC, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
int sqlite3_open_v2 (const char * filename, sqlite3 ** ppDb, int flags, const char * zVfs)
Definition at line 1664 of file main.c.
References openDatabase().
Referenced by DbMain().
int sqlite3_overload_function (sqlite3 * db, const char * zName, int nArg)
Definition at line 990 of file main.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3FindFunction(), sqlite3InvalidFunction(), sqlite3Strlen(), SQLITE_OK, and SQLITE_UTF8.
Referenced by sqlite3Fts1Init(), sqlite3Fts2Init(), sqlite3Fts3Init(), and sqlite3RegisterBuiltinFunctions().
void* sqlite3_profile (sqlite3 * db, void(*)(void *, const char *, sqlite_uint64) xProfile, void * pArg)
Definition at line 1033 of file main.c.
References sqlite3::mutex, sqlite3::pProfileArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xProfile.
Referenced by DbObjCmd().
void sqlite3_progress_handler (sqlite3 * db, int nOps, int(*)(void *) xProgress, void * pArg)
Definition at line 801 of file main.c.
References sqlite3::mutex, sqlite3::nProgressOps, sqlite3::pProgressArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xProgress.
Referenced by DbObjCmd(), and FUNC().
void* sqlite3_rollback_hook (sqlite3 * db, void(*)(void *) xCallback, void * pArg)
Definition at line 1090 of file main.c.
References sqlite3::mutex, sqlite3::pRollbackArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xRollbackCallback.
Referenced by DbObjCmd().
int sqlite3_shutdown (void)
Definition at line 213 of file main.c.
References sqlite3_os_end(), sqlite3GlobalConfig, sqlite3MallocEnd(), sqlite3MutexEnd, sqlite3PcacheShutdown(), and SQLITE_OK.
int sqlite3_sleep (int ms)
Definition at line 1977 of file main.c.
References sqlite3_vfs_find(), and sqlite3OsSleep().
int sqlite3_test_control (int op, ...)
Definition at line 2037 of file main.c.
References sqlite3BenignMallocHooks(), sqlite3BitvecBuiltinTest(), sqlite3PrngResetState(), sqlite3PrngRestoreState(), sqlite3PrngSaveState(), SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS, SQLITE_TESTCTRL_BITVEC_TEST, SQLITE_TESTCTRL_PRNG_RESET, SQLITE_TESTCTRL_PRNG_RESTORE, and SQLITE_TESTCTRL_PRNG_SAVE.
void sqlite3_thread_cleanup (void)
Definition at line 1855 of file main.c.
int sqlite3_threadsafe (void)
Definition at line 38 of file main.c.
References SQLITE_THREADSAFE.
int sqlite3_total_changes (sqlite3 * db)
Definition at line 527 of file main.c.
References sqlite3::nTotalChange.
Referenced by DbObjCmd(), FUNC(), and total_changes().
void* sqlite3_trace (sqlite3 * db, void(*)(void *, const char *) xTrace, void * pArg)
Definition at line 1016 of file main.c.
References sqlite3::mutex, sqlite3::pTraceArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xTrace.
Referenced by DbObjCmd(), and FUNC().
void* sqlite3_update_hook (sqlite3 * db, void(*)(void *, int, char const *, char const *, sqlite_int64) xCallback, void * pArg)
Definition at line 1072 of file main.c.
References sqlite3::mutex, sqlite3::pUpdateArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xUpdateCallback.
Referenced by DbObjCmd().
int sqlite3BtreeFactory (const sqlite3 * db, const char * zFilename, int omitJournal, int nCache, int vfsFlags, Btree ** ppBtree)
Definition at line 1129 of file main.c.
References BTREE_NO_READLOCK, BTREE_OMIT_JOURNAL, sqlite3::flags, sqlite3::mutex, sqlite3_mutex_held, sqlite3BtreeOpen(), sqlite3BtreeSchema(), sqlite3BtreeSetCacheSize(), SQLITE_NoReadlock, SQLITE_OK, SQLITE_OPEN_MAIN_DB, SQLITE_OPEN_TEMP_DB, and sqlite3::temp_store.
Referenced by attachFunc(), openDatabase(), sqlite3OpenTempDatabase(), and sqlite3VdbeExec().
int sqlite3CreateFunc (sqlite3 * db, const char * zFunctionName, int nArg, int enc, void * pUserData, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 850 of file main.c.
References sqlite3::activeVdbeCnt, FuncDef::flags, FuncDef::iPrefEnc, sqlite3::mallocFailed, sqlite3::mutex, FuncDef::nArg, FuncDef::pUserData, sqlite3_mutex_held, sqlite3CreateFunc(), sqlite3Error(), sqlite3ExpirePreparedStatements(), sqlite3FindFunction(), sqlite3Strlen(), SQLITE_ANY, SQLITE_BUSY, SQLITE_ERROR, SQLITE_MAX_FUNCTION_ARG, SQLITE_NOMEM, SQLITE_OK, SQLITE_UTF16, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF16NATIVE, SQLITE_UTF8, FuncDef::xFinalize, FuncDef::xFunc, and FuncDef::xStep.
Referenced by sqlite3_create_function(), sqlite3_create_function16(), sqlite3_overload_function(), sqlite3AlterFunctions(), sqlite3CreateFunc(), and sqlite3RegisterLikeFunctions().
const char* sqlite3ErrStr (int rc)
Definition at line 680 of file main.c.
References SQLITE_ABORT, SQLITE_AUTH, SQLITE_BUSY, SQLITE_CANTOPEN, SQLITE_CONSTRAINT, SQLITE_CORRUPT, SQLITE_DONE, SQLITE_EMPTY, SQLITE_ERROR, SQLITE_FORMAT, SQLITE_FULL, SQLITE_INTERRUPT, SQLITE_IOERR, SQLITE_LOCKED, SQLITE_MISMATCH, SQLITE_MISUSE, SQLITE_NOLFS, SQLITE_NOMEM, SQLITE_NOTADB, SQLITE_OK, SQLITE_PERM, SQLITE_RANGE, SQLITE_READONLY, SQLITE_ROW, SQLITE_SCHEMA, and SQLITE_TOOBIG.
Referenced by bestVirtualIndex(), DbObjCmd(), sqlite3_errmsg(), sqlite3_errmsg16(), sqlite3InitOne(), sqlite3RunParser(), sqlite3VdbeExec(), and sqlite3VdbeList().
int sqlite3InvokeBusyHandler (BusyHandler * p)
Definition at line 766 of file main.c.
References BusyHandler::nBusy, NEVER, BusyHandler::pArg, and BusyHandler::xFunc.
Referenced by pager_wait_on_lock(), and sqlite3BtreeInvokeBusyHandler().
void sqlite3RollbackAll (sqlite3 * db)
Definition at line 648 of file main.c.
References sqlite3::aDb, sqlite3::autoCommit, sqlite3::flags, Db::inTrans, sqlite3::mutex, sqlite3::nDb, Db::pBt, sqlite3::pRollbackArg, sqlite3_mutex_held, sqlite3BeginBenignMalloc(), sqlite3BtreeIsInTrans(), sqlite3BtreeRollback(), sqlite3EndBenignMalloc(), sqlite3ExpirePreparedStatements(), sqlite3ResetInternalSchema(), sqlite3VtabRollback(), SQLITE_InternChanges, and sqlite3::xRollbackCallback.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeHalt().
static int sqliteDefaultBusyCallback (void * ptr, int count) [static]
Definition at line 720 of file main.c.
References sqlite3::busyTimeout, db, sqlite3::pVfs, and sqlite3OsSleep().
Referenced by sqlite3_busy_timeout().
Variable Documentation
const int aHardLimit[] [static]
Initial value:
 {
  SQLITE_MAX_LENGTH,
  SQLITE_MAX_SQL_LENGTH,
  SQLITE_MAX_COLUMN,
  SQLITE_MAX_EXPR_DEPTH,
  SQLITE_MAX_COMPOUND_SELECT,
  SQLITE_MAX_VDBE_OP,
  SQLITE_MAX_FUNCTION_ARG,
  SQLITE_MAX_ATTACHED,
  SQLITE_MAX_LIKE_PATTERN_LENGTH,
  SQLITE_MAX_VARIABLE_NUMBER,
}
Definition at line 1360 of file main.c.
char* sqlite3_temp_directory = 0
Definition at line 57 of file main.c.
Referenced by getTempname(), and sqlite3Pragma().
const char sqlite3_version[] = SQLITE_VERSION
Definition at line 35 of file main.c.
Referenced by DbMain(), sqlite3_libversion(), and versionFunc().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1