ContextLogger2 Logger Daemon Internals: main_qt.cpp File Reference
main_qt.cpp File Reference
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 8 of file main_qt.cpp.
References cl2GlobalInit(), gx_txtlog_error_free(), kr_Controller_new(), kr_Controller_start(), logg, and logt.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1