ContextLogger2 Logger Daemon Internals: main_epoc_qt.cpp File Reference
main_epoc_qt.cpp File Reference
Classes
class CMainObj
Functions
void ExitApplication ()
void ShutdownApplication ()
static TInt QtMainE (int argc, char *argv[], char *envp[])
static TInt QtMainWrapper ()
GLDEF_C TInt E32Main ()
Function Documentation
GLDEF_C TInt E32Main ()
Definition at line 175 of file main_epoc_qt.cpp.
References QtMainWrapper().
void ExitApplication ()
Definition at line 31 of file main_epoc_qt.cpp.
References logt.
static TInt QtMainE (int argc, char * argv[], char * envp[]) [static]
Definition at line 109 of file main_epoc_qt.cpp.
References cl2GlobalCleanup(), cl2GlobalInit(), logg, logt, and CMainObj::NewL().
Referenced by QtMainWrapper().
static TInt QtMainWrapper () [static]
Definition at line 162 of file main_epoc_qt.cpp.
References QtMainE().
Referenced by E32Main().
void ShutdownApplication ()
Definition at line 40 of file main_epoc_qt.cpp.
References logt.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1