ContextLogger2 Logger Daemon Internals: main.cpp File Reference
main.cpp File Reference
Functions
void MainLoopL ()
static TBool IsAppInstalledL ()
static TBool MagicFileExists (RFs &fs)
static void WaitWhile ()
static void MainL ()
GLDEF_C TInt E32Main ()
Function Documentation
GLDEF_C TInt E32Main ()
Definition at line 212 of file main.cpp.
References MainL(), WITH_ACTIVE_SCHEDULER_ERR, and WITH_CLEANUP_STACK_ERR.
static TBool IsAppInstalledL () [static]
Definition at line 135 of file main.cpp.
References APP_UID_CL2_LOGGER_DAEMON.
Referenced by MainL().
static TBool MagicFileExists (RFs & fs) [static]
Definition at line 159 of file main.cpp.
References _LIT().
Referenced by MainL().
static void MainL () [static]
Definition at line 171 of file main.cpp.
References IsAppInstalledL(), log_clear, log_ctx, log_text(), logg, logt, MagicFileExists(), MainLoopL(), PRIMARY_LOG_FILENAME, and WaitWhile().
Referenced by E32Main().
void MainLoopL ()
Definition at line 118 of file main.cpp.
References CWatchdog::NewLC(), and CWatchdog::Start().
Referenced by MainL().
static void WaitWhile () [static]
Definition at line 166 of file main.cpp.
Referenced by MainL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1