ContextLogger2 Logger Daemon Internals: main_demo_qt.cpp File Reference
main_demo_qt.cpp File Reference
Functions
void ExitApplication ()
void ShutdownApplication ()
int main (int argc, char *argv[])
Function Documentation
void ExitApplication ()
Definition at line 22 of file main_demo_qt.cpp.
References logt.
int main (int argc, char * argv[])
Definition at line 41 of file main_demo_qt.cpp.
References __APP_NAME__, __CERT_NAME__, __VARIANT_NAME__, __VERSION_STRING__, cl2GlobalCleanup(), cl2GlobalInit(), guilog(), guilogf(), gx_txtlog_error_free(), kr_Controller_destroy(), kr_Controller_new(), kr_Controller_start(), logg, and logt.
void ShutdownApplication ()
Definition at line 31 of file main_demo_qt.cpp.
References logt.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1