ContextLogger2 Logger Daemon Internals: memjournal.c File Reference
memjournal.c File Reference
Classes
struct FileChunk
struct FilePoint
struct MemJournal
Defines
#define JOURNAL_CHUNKSIZE 1024
#define MIN(x, y) ((x)<(y)?(x):(y))
Typedefs
typedef struct MemJournal MemJournal
typedef struct FilePoint FilePoint
typedef struct FileChunk FileChunk
Functions
static int memjrnlRead (sqlite3_file *pJfd, void *zBuf, int iAmt, sqlite_int64 iOfst)
static int memjrnlWrite (sqlite3_file *pJfd, const void *zBuf, int iAmt, sqlite_int64 iOfst)
static int memjrnlTruncate (sqlite3_file *pJfd, sqlite_int64 size)
static int memjrnlClose (sqlite3_file *pJfd)
static int memjrnlSync (sqlite3_file *pJfd, int flags)
static int memjrnlFileSize (sqlite3_file *pJfd, sqlite_int64 *pSize)
void sqlite3MemJournalOpen (sqlite3_file *pJfd)
int sqlite3IsMemJournal (sqlite3_file *pJfd)
int sqlite3MemJournalSize ()
Variables
static struct sqlite3_io_methods MemJournalMethods
Define Documentation
#define JOURNAL_CHUNKSIZE 1024
Definition at line 29 of file memjournal.c.
Referenced by memjrnlRead(), and memjrnlWrite().
#define MIN (x, y) ((x)<(y)?(x):(y))
Definition at line 34 of file memjournal.c.
Referenced by g_ptr_array_cmp(), memjrnlRead(), memjrnlWrite(), and time_range_union().
Typedef Documentation
typedef struct FileChunk FileChunk
Definition at line 24 of file memjournal.c.
typedef struct FilePoint FilePoint
Definition at line 23 of file memjournal.c.
typedef struct MemJournal MemJournal
Definition at line 22 of file memjournal.c.
Function Documentation
static int memjrnlClose (sqlite3_file * pJfd) [static]
Definition at line 178 of file memjournal.c.
References memjrnlTruncate(), and SQLITE_OK.
static int memjrnlFileSize (sqlite3_file * pJfd, sqlite_int64 * pSize) [static]
Definition at line 194 of file memjournal.c.
References MemJournal::endpoint, FilePoint::iOffset, and SQLITE_OK.
static int memjrnlRead (sqlite3_file * pJfd, void * zBuf, int iAmt, sqlite_int64 iOfst) [static]
Definition at line 68 of file memjournal.c.
References FilePoint::iOffset, JOURNAL_CHUNKSIZE, MIN, FilePoint::pChunk, MemJournal::pFirst, FileChunk::pNext, MemJournal::readpoint, SQLITE_OK, and FileChunk::zChunk.
static int memjrnlSync (sqlite3_file * pJfd, int flags) [static]
Definition at line 187 of file memjournal.c.
References SQLITE_OK.
static int memjrnlTruncate (sqlite3_file * pJfd, sqlite_int64 size) [static]
Definition at line 161 of file memjournal.c.
References MemJournal::pFirst, FileChunk::pNext, sqlite3_free(), sqlite3MemJournalOpen(), and SQLITE_OK.
Referenced by memjrnlClose().
static int memjrnlWrite (sqlite3_file * pJfd, const void * zBuf, int iAmt, sqlite_int64 iOfst) [static]
Definition at line 112 of file memjournal.c.
References MemJournal::endpoint, FilePoint::iOffset, JOURNAL_CHUNKSIZE, MIN, FilePoint::pChunk, MemJournal::pFirst, FileChunk::pNext, sqlite3_malloc(), SQLITE_IOERR_NOMEM, SQLITE_OK, and FileChunk::zChunk.
int sqlite3IsMemJournal (sqlite3_file * pJfd)
Definition at line 232 of file memjournal.c.
References sqlite3_file::pMethods.
Referenced by pager_end_transaction(), and sqlite3PagerStmtCommit().
void sqlite3MemJournalOpen (sqlite3_file * pJfd)
Definition at line 222 of file memjournal.c.
References MemJournal::pMethod, and sqlite3MemJournalSize().
Referenced by memjrnlTruncate(), pager_open_journal(), and pagerStmtBegin().
int sqlite3MemJournalSize ()
Definition at line 240 of file memjournal.c.
Referenced by sqlite3MemJournalOpen(), and sqlite3PagerOpen().
Variable Documentation
struct sqlite3_io_methods MemJournalMethods [static]
Initial value:
 {
  1,
  memjrnlClose,
  memjrnlRead,
  memjrnlWrite,
  memjrnlTruncate,
  memjrnlSync,
  memjrnlFileSize,
  0,
  0,
  0,
  0,
  0,
  0
}
Definition at line 203 of file memjournal.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1