ContextLogger2 Logger Daemon Internals: moment_parser.h File Reference
moment_parser.h File Reference
Functions
gboolean parse_moment (const char *s, time_t ctx, time_t now, time_t *result, GError **error)
Function Documentation
gboolean parse_moment (const char * s, time_t ctx, time_t now, time_t * result, GError ** error)
Definition at line 1515 of file moment_parser.c.
References _fsm_actions, _fsm_index_offsets, _fsm_key_offsets, _fsm_range_lengths, _fsm_single_lengths, _fsm_trans_actions_wi, _fsm_trans_keys, _fsm_trans_targs_wi, ATOI_RANGE, code_incomplete_input, code_parse_error, DEF_NOW_DAY_WITH_SEEN_TIME, fsm_error, fsm_first_final, fsm_start, num_days_till_next_wday(), SEEN_TIME_T, seenDay, seenHour, seenMin, seenMonth, seenSec, seenYear, SET_SEEN_DATE_PLUS_DAYS, SET_SEEN_DATETIME_FROM_TIME_T, and this_domain.
Referenced by rb_parse_moment(), and CUploader::SetSnapshotTimerL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1