ContextLogger2 Logger Daemon Internals: os.c File Reference
os.c File Reference
Defines
#define _SQLITE_OS_C_ 1
#define DO_OS_MALLOC_TEST
#define vfsList GLOBAL(sqlite3_vfs *, vfsList)
Functions
int sqlite3OsClose (sqlite3_file *pId)
int sqlite3OsRead (sqlite3_file *id, void *pBuf, int amt, i64 offset)
int sqlite3OsWrite (sqlite3_file *id, const void *pBuf, int amt, i64 offset)
int sqlite3OsTruncate (sqlite3_file *id, i64 size)
int sqlite3OsSync (sqlite3_file *id, int flags)
int sqlite3OsFileSize (sqlite3_file *id, i64 *pSize)
int sqlite3OsLock (sqlite3_file *id, int lockType)
int sqlite3OsUnlock (sqlite3_file *id, int lockType)
int sqlite3OsCheckReservedLock (sqlite3_file *id, int *pResOut)
int sqlite3OsFileControl (sqlite3_file *id, int op, void *pArg)
int sqlite3OsSectorSize (sqlite3_file *id)
int sqlite3OsDeviceCharacteristics (sqlite3_file *id)
int sqlite3OsOpen (sqlite3_vfs *pVfs, const char *zPath, sqlite3_file *pFile, int flags, int *pFlagsOut)
int sqlite3OsDelete (sqlite3_vfs *pVfs, const char *zPath, int dirSync)
int sqlite3OsAccess (sqlite3_vfs *pVfs, const char *zPath, int flags, int *pResOut)
int sqlite3OsFullPathname (sqlite3_vfs *pVfs, const char *zPath, int nPathOut, char *zPathOut)
void * sqlite3OsDlOpen (sqlite3_vfs *pVfs, const char *zPath)
void sqlite3OsDlError (sqlite3_vfs *pVfs, int nByte, char *zBufOut)
void * sqlite3OsDlSym (sqlite3_vfs *pVfs, void *pHandle, const char *zSymbol)
void sqlite3OsDlClose (sqlite3_vfs *pVfs, void *pHandle)
int sqlite3OsRandomness (sqlite3_vfs *pVfs, int nByte, char *zBufOut)
int sqlite3OsSleep (sqlite3_vfs *pVfs, int nMicro)
int sqlite3OsCurrentTime (sqlite3_vfs *pVfs, double *pTimeOut)
int sqlite3OsOpenMalloc (sqlite3_vfs *pVfs, const char *zFile, sqlite3_file **ppFile, int flags, int *pOutFlags)
int sqlite3OsCloseFree (sqlite3_file *pFile)
sqlite3_vfs * sqlite3_vfs_find (const char *zVfs)
static void vfsUnlink (sqlite3_vfs *pVfs)
int sqlite3_vfs_register (sqlite3_vfs *pVfs, int makeDflt)
int sqlite3_vfs_unregister (sqlite3_vfs *pVfs)
Variables
static sqlite3_vfs *SQLITE_WSD vfsList = 0
Define Documentation
#define _SQLITE_OS_C_ 1
Definition at line 18 of file os.c.
#define DO_OS_MALLOC_TEST
Definition at line 46 of file os.c.
Referenced by sqlite3OsAccess(), sqlite3OsCheckReservedLock(), sqlite3OsFileSize(), sqlite3OsLock(), sqlite3OsOpen(), sqlite3OsRead(), sqlite3OsSync(), and sqlite3OsWrite().
#define vfsList GLOBAL(sqlite3_vfs *, vfsList)
Definition at line 194 of file os.c.
Referenced by sqlite3_vfs_find(), sqlite3_vfs_register(), and vfsUnlink().
Function Documentation
sqlite3_vfs* sqlite3_vfs_find (const char * zVfs)
Definition at line 200 of file os.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, vfsList, and sqlite3_vfs::zName.
Referenced by openDatabase(), randomByte(), and sqlite3_sleep().
int sqlite3_vfs_register (sqlite3_vfs * pVfs, int makeDflt)
Definition at line 246 of file os.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, vfsList, and vfsUnlink().
Referenced by sqlite3_os_init().
int sqlite3_vfs_unregister (sqlite3_vfs * pVfs)
Definition at line 270 of file os.c.
References sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, and vfsUnlink().
int sqlite3OsAccess (sqlite3_vfs * pVfs, const char * zPath, int flags, int * pResOut)
Definition at line 121 of file os.c.
References DO_OS_MALLOC_TEST, and sqlite3_vfs::xAccess.
Referenced by hasHotJournal(), pager_delmaster(), pager_playback(), pagerSharedLock(), sqlite3Pragma(), and vdbeCommit().
int sqlite3OsCheckReservedLock (sqlite3_file * id, int * pResOut)
Definition at line 89 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by hasHotJournal().
int sqlite3OsClose (sqlite3_file * pId)
Definition at line 55 of file os.c.
References sqlite3_file::pMethods, SQLITE_OK, and sqlite3_io_methods::xClose.
Referenced by pager_delmaster(), pager_end_transaction(), pager_unlock(), pagerSharedLock(), sqlite3OsCloseFree(), sqlite3PagerClose(), and sqlite3PagerOpen().
int sqlite3OsCloseFree (sqlite3_file * pFile)
Definition at line 182 of file os.c.
References sqlite3_free(), sqlite3OsClose(), and SQLITE_OK.
Referenced by vdbeCommit().
int sqlite3OsCurrentTime (sqlite3_vfs * pVfs, double * pTimeOut)
Definition at line 158 of file os.c.
References sqlite3_vfs::xCurrentTime.
Referenced by setDateTimeToCurrent(), and sqlite3Step().
int sqlite3OsDelete (sqlite3_vfs * pVfs, const char * zPath, int dirSync)
Definition at line 118 of file os.c.
References sqlite3_vfs::xDelete.
Referenced by hasHotJournal(), pager_delmaster(), pager_end_transaction(), pager_open_journal(), and vdbeCommit().
int sqlite3OsDeviceCharacteristics (sqlite3_file * id)
Definition at line 100 of file os.c.
Referenced by pagerStress(), sqlite3PagerOpen(), syncJournal(), vdbeCommit(), and writeJournalHdr().
void sqlite3OsDlClose (sqlite3_vfs * pVfs, void * pHandle)
Definition at line 148 of file os.c.
References sqlite3_vfs::xDlClose.
Referenced by sqlite3CloseExtensions(), and sqlite3LoadExtension().
void sqlite3OsDlError (sqlite3_vfs * pVfs, int nByte, char * zBufOut)
Definition at line 142 of file os.c.
References sqlite3_vfs::xDlError.
Referenced by sqlite3LoadExtension().
void* sqlite3OsDlOpen (sqlite3_vfs * pVfs, const char * zPath)
Definition at line 139 of file os.c.
References sqlite3_vfs::xDlOpen.
Referenced by sqlite3LoadExtension().
void* sqlite3OsDlSym (sqlite3_vfs * pVfs, void * pHandle, const char * zSymbol)
Definition at line 145 of file os.c.
References sqlite3_vfs::xDlSym.
Referenced by sqlite3LoadExtension().
int sqlite3OsFileControl (sqlite3_file * id, int op, void * pArg)
Definition at line 93 of file os.c.
Referenced by sqlite3_file_control().
int sqlite3OsFileSize (sqlite3_file * id, i64 * pSize)
Definition at line 78 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by pager_delmaster(), pager_playback(), pager_truncate(), readMasterJournal(), sqlite3PagerPagecount(), writeMasterJournal(), and zeroJournalHdr().
int sqlite3OsFullPathname (sqlite3_vfs * pVfs, const char * zPath, int nPathOut, char * zPathOut)
Definition at line 130 of file os.c.
References sqlite3_vfs::xFullPathname.
Referenced by sqlite3BtreeOpen(), and sqlite3PagerOpen().
int sqlite3OsLock (sqlite3_file * id, int lockType)
Definition at line 82 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by pager_wait_on_lock(), pagerSharedLock(), and sqlite3PagerBegin().
int sqlite3OsOpen (sqlite3_vfs * pVfs, const char * zPath, sqlite3_file * pFile, int flags, int * pFlagsOut)
Definition at line 108 of file os.c.
References DO_OS_MALLOC_TEST, and sqlite3_vfs::xOpen.
Referenced by pager_delmaster(), pager_open_journal(), pagerSharedLock(), sqlite3OsOpenMalloc(), sqlite3PagerOpen(), and sqlite3PagerOpentemp().
int sqlite3OsOpenMalloc (sqlite3_vfs * pVfs, const char * zFile, sqlite3_file ** ppFile, int flags, int * pOutFlags)
Definition at line 162 of file os.c.
References sqlite3_free(), sqlite3Malloc(), sqlite3OsOpen(), SQLITE_NOMEM, SQLITE_OK, and sqlite3_vfs::szOsFile.
Referenced by vdbeCommit().
int sqlite3OsRandomness (sqlite3_vfs * pVfs, int nByte, char * zBufOut)
Definition at line 152 of file os.c.
References sqlite3_vfs::xRandomness.
Referenced by randomByte().
int sqlite3OsRead (sqlite3_file * id, void * pBuf, int amt, i64 offset)
Definition at line 63 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by pager_delmaster(), pager_playback_one_page(), pagerSharedLock(), read32bits(), readDbPage(), readJournalHdr(), readMasterJournal(), and sqlite3PagerReadFileheader().
int sqlite3OsSectorSize (sqlite3_file * id)
Definition at line 96 of file os.c.
References sqlite3_file::pMethods, SQLITE_DEFAULT_SECTOR_SIZE, and sqlite3_io_methods::xSectorSize.
Referenced by setSectorSize(), and sqlite3PagerOpen().
int sqlite3OsSleep (sqlite3_vfs * pVfs, int nMicro)
Definition at line 155 of file os.c.
References sqlite3_vfs::xSleep.
Referenced by sqlite3_sleep(), and sqliteDefaultBusyCallback().
int sqlite3OsSync (sqlite3_file * id, int flags)
Definition at line 74 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by sqlite3PagerCommitPhaseOne(), sqlite3PagerSync(), syncJournal(), vdbeCommit(), and zeroJournalHdr().
int sqlite3OsTruncate (sqlite3_file * id, i64 size)
Definition at line 71 of file os.c.
Referenced by btreeCopyFile(), pager_end_transaction(), pager_truncate(), sqlite3PagerStmtCommit(), writeMasterJournal(), and zeroJournalHdr().
int sqlite3OsUnlock (sqlite3_file * id, int lockType)
Definition at line 86 of file os.c.
Referenced by osUnlock().
int sqlite3OsWrite (sqlite3_file * id, const void * pBuf, int amt, i64 offset)
Definition at line 67 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by btreeCopyFile(), pager_incr_changecounter(), pager_playback_one_page(), pager_truncate(), pager_write(), pager_write_pagelist(), vdbeCommit(), write32bits(), writeJournalHdr(), writeMasterJournal(), and zeroJournalHdr().
static void vfsUnlink (sqlite3_vfs * pVfs) [static]
Definition at line 224 of file os.c.
References sqlite3_vfs::pNext, sqlite3_mutex_held, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, and vfsList.
Referenced by sqlite3_vfs_register(), and sqlite3_vfs_unregister().
Variable Documentation
sqlite3_vfs* SQLITE_WSD vfsList = 0 [static]
Definition at line 193 of file os.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1