ContextLogger2 Logger Daemon Internals: os.h File Reference
os.h File Reference
Defines
#define SQLITE_OS_OTHER 0
#define SQLITE_OS_WIN 0
#define SQLITE_OS_UNIX 1
#define SQLITE_OS_OS2 0
#define SQLITE_OS_WINCE 0
#define SQLITE_TEMPNAME_SIZE 200
#define SET_FULLSYNC(x, y)
#define SQLITE_DEFAULT_SECTOR_SIZE 512
#define SQLITE_TEMP_FILE_PREFIX "etilqs_"
#define NO_LOCK 0
#define SHARED_LOCK 1
#define RESERVED_LOCK 2
#define PENDING_LOCK 3
#define EXCLUSIVE_LOCK 4
#define PENDING_BYTE 0x40000000
#define RESERVED_BYTE (PENDING_BYTE+1)
#define SHARED_FIRST (PENDING_BYTE+2)
#define SHARED_SIZE 510
Functions
int sqlite3OsClose (sqlite3_file *)
int sqlite3OsRead (sqlite3_file *, void *, int amt, i64 offset)
int sqlite3OsWrite (sqlite3_file *, const void *, int amt, i64 offset)
int sqlite3OsTruncate (sqlite3_file *, i64 size)
int sqlite3OsSync (sqlite3_file *, int)
int sqlite3OsFileSize (sqlite3_file *, i64 *pSize)
int sqlite3OsLock (sqlite3_file *, int)
int sqlite3OsUnlock (sqlite3_file *, int)
int sqlite3OsCheckReservedLock (sqlite3_file *id, int *pResOut)
int sqlite3OsFileControl (sqlite3_file *, int, void *)
int sqlite3OsSectorSize (sqlite3_file *id)
int sqlite3OsDeviceCharacteristics (sqlite3_file *id)
int sqlite3OsOpen (sqlite3_vfs *, const char *, sqlite3_file *, int, int *)
int sqlite3OsDelete (sqlite3_vfs *, const char *, int)
int sqlite3OsAccess (sqlite3_vfs *, const char *, int, int *pResOut)
int sqlite3OsFullPathname (sqlite3_vfs *, const char *, int, char *)
void * sqlite3OsDlOpen (sqlite3_vfs *, const char *)
void sqlite3OsDlError (sqlite3_vfs *, int, char *)
void * sqlite3OsDlSym (sqlite3_vfs *, void *, const char *)
void sqlite3OsDlClose (sqlite3_vfs *, void *)
int sqlite3OsRandomness (sqlite3_vfs *, int, char *)
int sqlite3OsSleep (sqlite3_vfs *, int)
int sqlite3OsCurrentTime (sqlite3_vfs *, double *)
int sqlite3OsOpenMalloc (sqlite3_vfs *, const char *, sqlite3_file **, int, int *)
int sqlite3OsCloseFree (sqlite3_file *)
Define Documentation
#define EXCLUSIVE_LOCK 4
Definition at line 165 of file os.h.
Referenced by pager_wait_on_lock(), pager_write_pagelist(), pagerSharedLock(), sqlite3PagerBegin(), sqlite3PagerTruncate(), and unixLock().
#define NO_LOCK 0
Definition at line 161 of file os.h.
Referenced by pager_unlock(), unixClose(), unixLock(), and unixUnlock().
#define PENDING_BYTE 0x40000000
Definition at line 225 of file os.h.
Referenced by pager_write(), sqlite3PagerPagecount(), unixLock(), and unixUnlock().
#define PENDING_LOCK 3
Definition at line 164 of file os.h.
Referenced by unixLock().
#define RESERVED_BYTE (PENDING_BYTE+1)
Definition at line 231 of file os.h.
Referenced by unixCheckReservedLock(), unixLock(), and unixUnlock().
#define RESERVED_LOCK 2
Definition at line 163 of file os.h.
Referenced by pager_wait_on_lock(), sqlite3PagerBegin(), and unixLock().
#define SET_FULLSYNC (x, y)
Definition at line 109 of file os.h.
#define SHARED_FIRST (PENDING_BYTE+2)
Definition at line 232 of file os.h.
Referenced by unixLock(), and unixUnlock().
#define SHARED_LOCK 1
Definition at line 162 of file os.h.
Referenced by pager_end_transaction(), pager_wait_on_lock(), pagerSharedLock(), unixCheckReservedLock(), unixLock(), and unixUnlock().
#define SHARED_SIZE 510
Definition at line 233 of file os.h.
Referenced by unixLock(), and unixUnlock().
#define SQLITE_DEFAULT_SECTOR_SIZE 512
Definition at line 116 of file os.h.
Referenced by sqlite3OsSectorSize(), and unixSectorSize().
#define SQLITE_OS_OS2 0
Definition at line 58 of file os.h.
#define SQLITE_OS_OTHER 0
Definition at line 45 of file os.h.
#define SQLITE_OS_UNIX 1
Definition at line 57 of file os.h.
#define SQLITE_OS_WIN 0
Definition at line 56 of file os.h.
#define SQLITE_OS_WINCE 0
Definition at line 77 of file os.h.
#define SQLITE_TEMP_FILE_PREFIX "etilqs_"
Definition at line 141 of file os.h.
Referenced by getTempname().
#define SQLITE_TEMPNAME_SIZE 200
Definition at line 102 of file os.h.
Function Documentation
int sqlite3OsAccess (sqlite3_vfs * , const char * , int , int * pResOut)
Definition at line 121 of file os.c.
References DO_OS_MALLOC_TEST, and sqlite3_vfs::xAccess.
Referenced by hasHotJournal(), pager_delmaster(), pager_playback(), pagerSharedLock(), sqlite3Pragma(), and vdbeCommit().
int sqlite3OsCheckReservedLock (sqlite3_file * id, int * pResOut)
Definition at line 89 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by hasHotJournal().
int sqlite3OsClose (sqlite3_file *)
Definition at line 55 of file os.c.
References sqlite3_file::pMethods, SQLITE_OK, and sqlite3_io_methods::xClose.
Referenced by pager_delmaster(), pager_end_transaction(), pager_unlock(), pagerSharedLock(), sqlite3OsCloseFree(), sqlite3PagerClose(), and sqlite3PagerOpen().
int sqlite3OsCloseFree (sqlite3_file *)
Definition at line 182 of file os.c.
References sqlite3_free(), sqlite3OsClose(), and SQLITE_OK.
Referenced by vdbeCommit().
int sqlite3OsCurrentTime (sqlite3_vfs * , double *)
Definition at line 158 of file os.c.
References sqlite3_vfs::xCurrentTime.
Referenced by setDateTimeToCurrent(), and sqlite3Step().
int sqlite3OsDelete (sqlite3_vfs * , const char * , int)
Definition at line 118 of file os.c.
References sqlite3_vfs::xDelete.
Referenced by hasHotJournal(), pager_delmaster(), pager_end_transaction(), pager_open_journal(), and vdbeCommit().
int sqlite3OsDeviceCharacteristics (sqlite3_file * id)
Definition at line 100 of file os.c.
Referenced by pagerStress(), sqlite3PagerOpen(), syncJournal(), vdbeCommit(), and writeJournalHdr().
void sqlite3OsDlClose (sqlite3_vfs * , void *)
Definition at line 148 of file os.c.
References sqlite3_vfs::xDlClose.
Referenced by sqlite3CloseExtensions(), and sqlite3LoadExtension().
void sqlite3OsDlError (sqlite3_vfs * , int , char *)
Definition at line 142 of file os.c.
References sqlite3_vfs::xDlError.
Referenced by sqlite3LoadExtension().
void* sqlite3OsDlOpen (sqlite3_vfs * , const char *)
Definition at line 139 of file os.c.
References sqlite3_vfs::xDlOpen.
Referenced by sqlite3LoadExtension().
void* sqlite3OsDlSym (sqlite3_vfs * , void * , const char *)
Definition at line 145 of file os.c.
References sqlite3_vfs::xDlSym.
Referenced by sqlite3LoadExtension().
int sqlite3OsFileControl (sqlite3_file * , int , void *)
Definition at line 93 of file os.c.
Referenced by sqlite3_file_control().
int sqlite3OsFileSize (sqlite3_file * , i64 * pSize)
Definition at line 78 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by pager_delmaster(), pager_playback(), pager_truncate(), readMasterJournal(), sqlite3PagerPagecount(), writeMasterJournal(), and zeroJournalHdr().
int sqlite3OsFullPathname (sqlite3_vfs * , const char * , int , char *)
Definition at line 130 of file os.c.
References sqlite3_vfs::xFullPathname.
Referenced by sqlite3BtreeOpen(), and sqlite3PagerOpen().
int sqlite3OsLock (sqlite3_file * , int)
Definition at line 82 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by pager_wait_on_lock(), pagerSharedLock(), and sqlite3PagerBegin().
int sqlite3OsOpen (sqlite3_vfs * , const char * , sqlite3_file * , int , int *)
Definition at line 108 of file os.c.
References DO_OS_MALLOC_TEST, and sqlite3_vfs::xOpen.
Referenced by pager_delmaster(), pager_open_journal(), pagerSharedLock(), sqlite3OsOpenMalloc(), sqlite3PagerOpen(), and sqlite3PagerOpentemp().
int sqlite3OsOpenMalloc (sqlite3_vfs * , const char * , sqlite3_file ** , int , int *)
Definition at line 162 of file os.c.
References sqlite3_free(), sqlite3Malloc(), sqlite3OsOpen(), SQLITE_NOMEM, SQLITE_OK, and sqlite3_vfs::szOsFile.
Referenced by vdbeCommit().
int sqlite3OsRandomness (sqlite3_vfs * , int , char *)
Definition at line 152 of file os.c.
References sqlite3_vfs::xRandomness.
Referenced by randomByte().
int sqlite3OsRead (sqlite3_file * , void * , int amt, i64 offset)
Definition at line 63 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by pager_delmaster(), pager_playback_one_page(), pagerSharedLock(), read32bits(), readDbPage(), readJournalHdr(), readMasterJournal(), and sqlite3PagerReadFileheader().
int sqlite3OsSectorSize (sqlite3_file * id)
Definition at line 96 of file os.c.
References sqlite3_file::pMethods, SQLITE_DEFAULT_SECTOR_SIZE, and sqlite3_io_methods::xSectorSize.
Referenced by setSectorSize(), and sqlite3PagerOpen().
int sqlite3OsSleep (sqlite3_vfs * , int)
Definition at line 155 of file os.c.
References sqlite3_vfs::xSleep.
Referenced by sqlite3_sleep(), and sqliteDefaultBusyCallback().
int sqlite3OsSync (sqlite3_file * , int)
Definition at line 74 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by sqlite3PagerCommitPhaseOne(), sqlite3PagerSync(), syncJournal(), vdbeCommit(), and zeroJournalHdr().
int sqlite3OsTruncate (sqlite3_file * , i64 size)
Definition at line 71 of file os.c.
Referenced by btreeCopyFile(), pager_end_transaction(), pager_truncate(), sqlite3PagerStmtCommit(), writeMasterJournal(), and zeroJournalHdr().
int sqlite3OsUnlock (sqlite3_file * , int)
Definition at line 86 of file os.c.
Referenced by osUnlock().
int sqlite3OsWrite (sqlite3_file * , const void * , int amt, i64 offset)
Definition at line 67 of file os.c.
References DO_OS_MALLOC_TEST.
Referenced by btreeCopyFile(), pager_incr_changecounter(), pager_playback_one_page(), pager_truncate(), pager_write(), pager_write_pagelist(), vdbeCommit(), write32bits(), writeJournalHdr(), writeMasterJournal(), and zeroJournalHdr().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1