ContextLogger2 Logger Daemon Internals: os_symbian.c File Reference
os_symbian.c File Reference
Classes
struct unixFile
Defines
#define SQLITE_DEFAULT_FILE_PERMISSIONS 0644
#define MAX_PATHNAME 256
#define O_LARGEFILE 0
#define O_NOFOLLOW 0
#define O_BINARY 0
#define SEP_CH '/'
#define SEP_STR "/"
#define fdatasync fsync
#define HAVE_FULLFSYNC 0
#define IOMETHODS(xClose, xLock, xUnlock, xCheckReservedLock)
#define UNIXVFS(zVfsName, pVfsAppData)
Typedefs
typedef struct unixFile unixFile
typedef void nolockLockingContext
Functions
static int seekAndRead (unixFile *id, sqlite3_int64 offset, void *pBuf, int cnt)
static int unixRead (sqlite3_file *id, void *pBuf, int amt, sqlite3_int64 offset)
static int seekAndWrite (unixFile *id, i64 offset, const void *pBuf, int cnt)
static int unixWrite (sqlite3_file *id, const void *pBuf, int amt, sqlite3_int64 offset)
static int full_fsync (int fd, int fullSync, int dataOnly)
static int unixSync (sqlite3_file *id, int flags)
static int unixTruncate (sqlite3_file *id, i64 nByte)
static int unixFileSize (sqlite3_file *id, i64 *pSize)
static int closeUnixFile (sqlite3_file *id)
static int nolockCheckReservedLock (sqlite3_file *id, int *pResOut)
static int nolockLock (sqlite3_file *id, int locktype)
static int nolockUnlock (sqlite3_file *id, int locktype)
static int nolockClose (sqlite3_file *id)
static int unixFileControl (sqlite3_file *id, int op, void *pArg)
static int unixSectorSize (sqlite3_file *id)
static int unixDeviceCharacteristics (sqlite3_file *id)
static int fillInUnixFile (sqlite3_vfs *pVfs, int h, sqlite3_file *pId, const char *zFilename)
static int getTempname (int nBuf, char *zBuf)
static int unixOpen (sqlite3_vfs *pVfs, const char *zPath, sqlite3_file *pFile, int flags, int *pOutFlags)
static int unixDelete (sqlite3_vfs *pVfs, const char *zPath, int dirSync)
static int unixAccess (sqlite3_vfs *pVfs, const char *zPath, int flags, int *pResOut)
static int unixFullPathname (sqlite3_vfs *pVfs, const char *zPath, int nOut, char *zOut)
static int unixRandomness (sqlite3_vfs *pVfs, int nBuf, char *zBuf)
static int unixSleep (sqlite3_vfs *pVfs, int microseconds)
static int unixCurrentTime (sqlite3_vfs *pVfs, double *prNow)
static int unixGetLastError (sqlite3_vfs *pVfs, int nBuf, char *zBuf)
int sqlite3_os_init (void)
int sqlite3_os_end (void)
Define Documentation
#define fdatasync fsync
Definition at line 255 of file os_symbian.c.
Referenced by full_fsync().
#define HAVE_FULLFSYNC 0
Definition at line 266 of file os_symbian.c.
Referenced by unixSync().
#define IOMETHODS (xClose, xLock, xUnlock, xCheckReservedLock)
Value:
{    \
    1,                          /* iVersion */                           \
    xClose,                     /* xClose */                             \
    unixRead,                   /* xRead */                              \
    unixWrite,                  /* xWrite */                             \
    unixTruncate,               /* xTruncate */                          \
    unixSync,                   /* xSync */                              \
    unixFileSize,               /* xFileSize */                          \
    xLock,                      /* xLock */                              \
    xUnlock,                    /* xUnlock */                            \
    xCheckReservedLock,         /* xCheckReservedLock */                 \
    unixFileControl,            /* xFileControl */                       \
    unixSectorSize,             /* xSectorSize */                        \
    unixDeviceCharacteristics   /* xDeviceCapabilities */                \
  }
Referenced by fillInUnixFile().
#define MAX_PATHNAME 256
Definition at line 78 of file os_symbian.c.
Referenced by openDirectory(), unixFullPathname(), and unixOpen().
#define O_BINARY 0
Definition at line 117 of file os_symbian.c.
Referenced by openDirectory(), and unixOpen().
#define O_LARGEFILE 0
Definition at line 107 of file os_symbian.c.
Referenced by unixOpen().
#define O_NOFOLLOW 0
Definition at line 114 of file os_symbian.c.
Referenced by unixOpen().
#define SEP_CH '/'
Definition at line 124 of file os_symbian.c.
Referenced by unixFullPathname().
#define SEP_STR "/"
Definition at line 125 of file os_symbian.c.
Referenced by getTempname(), and unixFullPathname().
#define SQLITE_DEFAULT_FILE_PERMISSIONS 0644
Definition at line 67 of file os_symbian.c.
Referenced by unixOpen().
#define UNIXVFS (zVfsName, pVfsAppData)
Value:
{                  \
    1,                    /* iVersion */                    \
    sizeof(unixFile),     /* szOsFile */                    \
    MAX_PATHNAME,         /* mxPathname */                  \
    0,                    /* pNext */                       \
    zVfsName,             /* zName */                       \
    (void *)pVfsAppData,  /* pAppData */                    \
    unixOpen,             /* xOpen */                       \
    unixDelete,           /* xDelete */                     \
    unixAccess,           /* xAccess */                     \
    unixFullPathname,     /* xFullPathname */               \
    unixDlOpen,           /* xDlOpen */                     \
    unixDlError,          /* xDlError */                    \
    unixDlSym,            /* xDlSym */                      \
    unixDlClose,          /* xDlClose */                    \
    unixRandomness,       /* xRandomness */                 \
    unixSleep,            /* xSleep */                      \
    unixCurrentTime,      /* xCurrentTime */                \
    unixGetLastError      /* xGetLastError */               \
  }
Referenced by sqlite3_os_init().
Typedef Documentation
typedef void nolockLockingContext
Definition at line 433 of file os_symbian.c.
typedef struct unixFile unixFile
Definition at line 85 of file os_symbian.c.
Function Documentation
static int closeUnixFile (sqlite3_file * id) [static]
Definition at line 417 of file os_symbian.c.
References unixFile::h, OpenCounter, OSTRACE2, and SQLITE_OK.
Referenced by nolockClose().
static int fillInUnixFile (sqlite3_vfs * pVfs, int h, sqlite3_file * pId, const char * zFilename) [static]
Definition at line 498 of file os_symbian.c.
References unixFile::h, IOMETHODS, unixFile::lastErrno, nolockCheckReservedLock(), nolockClose(), nolockLock(), nolockUnlock(), OpenCounter, OSTRACE3, unixFile::pMethod, and SQLITE_OK.
Referenced by unixOpen().
static int full_fsync (int fd, int fullSync, int dataOnly) [static]
Definition at line 281 of file os_symbian.c.
References fdatasync, and SQLITE_OK.
Referenced by unixSync().
static int getTempname (int nBuf, char * zBuf) [static]
Definition at line 549 of file os_symbian.c.
References SEP_STR, SimulateIOError, sqlite3_randomness(), sqlite3_snprintf(), sqlite3_temp_directory, SQLITE_ERROR, SQLITE_IOERR, SQLITE_OK, and SQLITE_TEMP_FILE_PREFIX.
Referenced by unixOpen().
static int nolockCheckReservedLock (sqlite3_file * id, int * pResOut) [static]
Definition at line 435 of file os_symbian.c.
References SQLITE_OK.
Referenced by fillInUnixFile().
static int nolockClose (sqlite3_file * id) [static]
Definition at line 451 of file os_symbian.c.
References closeUnixFile().
Referenced by fillInUnixFile().
static int nolockLock (sqlite3_file * id, int locktype) [static]
Definition at line 440 of file os_symbian.c.
References SQLITE_OK.
Referenced by fillInUnixFile().
static int nolockUnlock (sqlite3_file * id, int locktype) [static]
Definition at line 444 of file os_symbian.c.
References SQLITE_OK.
Referenced by fillInUnixFile().
static int seekAndRead (unixFile * id, sqlite3_int64 offset, void * pBuf, int cnt) [static]
Definition at line 138 of file os_symbian.c.
References unixFile::h, OSTRACE5, SimulateIOError, TIMER_ELAPSED, TIMER_END, and TIMER_START.
Referenced by unixRead().
static int seekAndWrite (unixFile * id, i64 offset, const void * pBuf, int cnt) [static]
Definition at line 190 of file os_symbian.c.
References unixFile::h, OSTRACE5, TIMER_ELAPSED, TIMER_END, and TIMER_START.
Referenced by unixWrite().
int sqlite3_os_end (void)
Definition at line 952 of file os_symbian.c.
Referenced by sqlite3_shutdown().
int sqlite3_os_init (void)
Definition at line 917 of file os_symbian.c.
Referenced by sqlite3_initialize().
static int unixAccess (sqlite3_vfs * pVfs, const char * zPath, int flags, int * pResOut) [static]
Definition at line 746 of file os_symbian.c.
References SimulateIOError, SQLITE_ACCESS_EXISTS, SQLITE_ACCESS_READ, SQLITE_ACCESS_READWRITE, SQLITE_IOERR_ACCESS, and SQLITE_OK.
static int unixCurrentTime (sqlite3_vfs * pVfs, double * prNow) [static]
Definition at line 892 of file os_symbian.c.
static int unixDelete (sqlite3_vfs * pVfs, const char * zPath, int dirSync) [static]
Definition at line 729 of file os_symbian.c.
References SimulateIOError, SQLITE_IOERR_DELETE, and SQLITE_OK.
static int unixDeviceCharacteristics (sqlite3_file * id) [static]
Definition at line 486 of file os_symbian.c.
static int unixFileControl (sqlite3_file * id, int op, void * pArg) [static]
Definition at line 459 of file os_symbian.c.
References SQLITE_ERROR, SQLITE_FCNTL_LOCKSTATE, SQLITE_LOCK_NONE, and SQLITE_OK.
static int unixFileSize (sqlite3_file * id, i64 * pSize) [static]
Definition at line 388 of file os_symbian.c.
References SimulateIOError, SQLITE_IOERR_FSTAT, and SQLITE_OK.
static int unixFullPathname (sqlite3_vfs * pVfs, const char * zPath, int nOut, char * zOut) [static]
Definition at line 782 of file os_symbian.c.
References MAX_PATHNAME, sqlite3_vfs::mxPathname, SEP_CH, SEP_STR, SimulateIOError, sqlite3_snprintf(), SQLITE_CANTOPEN, SQLITE_ERROR, and SQLITE_OK.
static int unixGetLastError (sqlite3_vfs * pVfs, int nBuf, char * zBuf) [static]
Definition at line 910 of file os_symbian.c.
static int unixOpen (sqlite3_vfs * pVfs, const char * zPath, sqlite3_file * pFile, int flags, int * pOutFlags) [static]
Definition at line 629 of file os_symbian.c.
References fillInUnixFile(), getTempname(), MAX_PATHNAME, O_BINARY, O_LARGEFILE, O_NOFOLLOW, SQLITE_CANTOPEN, SQLITE_DEFAULT_FILE_PERMISSIONS, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_DELETEONCLOSE, SQLITE_OPEN_EXCLUSIVE, SQLITE_OPEN_MAIN_DB, SQLITE_OPEN_MAIN_JOURNAL, SQLITE_OPEN_MASTER_JOURNAL, SQLITE_OPEN_READONLY, SQLITE_OPEN_READWRITE, SQLITE_OPEN_SUBJOURNAL, SQLITE_OPEN_TEMP_DB, SQLITE_OPEN_TEMP_JOURNAL, and SQLITE_OPEN_TRANSIENT_DB.
static int unixRandomness (sqlite3_vfs * pVfs, int nBuf, char * zBuf) [static]
Definition at line 827 of file os_symbian.c.
static int unixRead (sqlite3_file * id, void * pBuf, int amt, sqlite3_int64 offset) [static]
Definition at line 166 of file os_symbian.c.
References seekAndRead(), SQLITE_IOERR_READ, SQLITE_IOERR_SHORT_READ, and SQLITE_OK.
static int unixSectorSize (sqlite3_file * id) [static]
Definition at line 479 of file os_symbian.c.
References SQLITE_DEFAULT_SECTOR_SIZE.
static int unixSleep (sqlite3_vfs * pVfs, int microseconds) [static]
Definition at line 868 of file os_symbian.c.
static int unixSync (sqlite3_file * id, int flags) [static]
Definition at line 343 of file os_symbian.c.
References full_fsync(), unixFile::h, OSTRACE2, SimulateDiskfullError, SimulateIOError, SQLITE_FULL, SQLITE_IOERR_FSYNC, SQLITE_OK, SQLITE_SYNC_DATAONLY, SQLITE_SYNC_FULL, and SQLITE_SYNC_NORMAL.
static int unixTruncate (sqlite3_file * id, i64 nByte) [static]
Definition at line 373 of file os_symbian.c.
References SimulateIOError, SQLITE_IOERR_TRUNCATE, and SQLITE_OK.
static int unixWrite (sqlite3_file * id, const void * pBuf, int amt, sqlite3_int64 offset) [static]
Definition at line 215 of file os_symbian.c.
References seekAndWrite(), SimulateDiskfullError, SimulateIOError, SQLITE_FULL, SQLITE_IOERR_WRITE, and SQLITE_OK.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:00 2011 by Doxygen 1.6.1