ContextLogger2 Logger Daemon Internals: pager.h File Reference
pager.h File Reference
Defines
#define SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT -1
#define PAGER_OMIT_JOURNAL 0x0001
#define PAGER_NO_READLOCK 0x0002
#define PAGER_LOCKINGMODE_QUERY -1
#define PAGER_LOCKINGMODE_NORMAL 0
#define PAGER_LOCKINGMODE_EXCLUSIVE 1
#define PAGER_JOURNALMODE_QUERY -1
#define PAGER_JOURNALMODE_DELETE 0
#define PAGER_JOURNALMODE_PERSIST 1
#define PAGER_JOURNALMODE_OFF 2
#define PAGER_JOURNALMODE_TRUNCATE 3
#define PAGER_JOURNALMODE_MEMORY 4
#define sqlite3PagerGet(A, B, C) sqlite3PagerAcquire(A,B,C,0)
#define disable_simulated_io_errors()
#define enable_simulated_io_errors()
Typedefs
typedef u32 Pgno
typedef struct Pager Pager
typedef struct PgHdr DbPage
Functions
int sqlite3PagerOpen (sqlite3_vfs *, Pager **ppPager, const char *, int, int, int)
void sqlite3PagerSetBusyhandler (Pager *, BusyHandler *pBusyHandler)
void sqlite3PagerSetReiniter (Pager *, void(*)(DbPage *))
int sqlite3PagerSetPagesize (Pager *, u16 *)
int sqlite3PagerMaxPageCount (Pager *, int)
int sqlite3PagerReadFileheader (Pager *, int, unsigned char *)
void sqlite3PagerSetCachesize (Pager *, int)
int sqlite3PagerClose (Pager *pPager)
int sqlite3PagerAcquire (Pager *pPager, Pgno pgno, DbPage **ppPage, int clrFlag)
DbPage * sqlite3PagerLookup (Pager *pPager, Pgno pgno)
int sqlite3PagerPageRefcount (DbPage *)
int sqlite3PagerRef (DbPage *)
int sqlite3PagerUnref (DbPage *)
int sqlite3PagerWrite (DbPage *)
int sqlite3PagerPagecount (Pager *, int *)
int sqlite3PagerTruncate (Pager *, Pgno)
int sqlite3PagerBegin (DbPage *, int exFlag)
int sqlite3PagerCommitPhaseOne (Pager *, const char *zMaster, Pgno, int)
int sqlite3PagerCommitPhaseTwo (Pager *)
int sqlite3PagerRollback (Pager *)
int sqlite3PagerIsreadonly (Pager *)
int sqlite3PagerStmtBegin (Pager *)
int sqlite3PagerStmtCommit (Pager *)
int sqlite3PagerStmtRollback (Pager *)
void sqlite3PagerDontRollback (DbPage *)
int sqlite3PagerDontWrite (DbPage *)
int sqlite3PagerRefcount (Pager *)
void sqlite3PagerSetSafetyLevel (Pager *, int, int)
const char * sqlite3PagerFilename (Pager *)
const sqlite3_vfs * sqlite3PagerVfs (Pager *)
sqlite3_file * sqlite3PagerFile (Pager *)
const char * sqlite3PagerDirname (Pager *)
const char * sqlite3PagerJournalname (Pager *)
int sqlite3PagerNosync (Pager *)
int sqlite3PagerMovepage (Pager *, DbPage *, Pgno, int)
void * sqlite3PagerGetData (DbPage *)
void * sqlite3PagerGetExtra (DbPage *)
int sqlite3PagerLockingMode (Pager *, int)
int sqlite3PagerJournalMode (Pager *, int)
i64 sqlite3PagerJournalSizeLimit (Pager *, i64)
void * sqlite3PagerTempSpace (Pager *)
int sqlite3PagerSync (Pager *pPager)
Define Documentation
#define disable_simulated_io_errors ()
Definition at line 138 of file pager.h.
#define enable_simulated_io_errors ()
Definition at line 139 of file pager.h.
#define PAGER_JOURNALMODE_DELETE 0
Definition at line 65 of file pager.h.
Referenced by pager_end_transaction(), sqlite3PagerCommitPhaseOne(), sqlite3PagerCommitPhaseTwo(), sqlite3PagerJournalMode(), and sqlite3Pragma().
#define PAGER_JOURNALMODE_MEMORY 4
Definition at line 69 of file pager.h.
Referenced by pager_end_transaction(), pager_open_journal(), pagerStmtBegin(), pagerStress(), sqlite3PagerJournalMode(), sqlite3PagerOpen(), sqlite3Pragma(), syncJournal(), writeJournalHdr(), and writeMasterJournal().
#define PAGER_JOURNALMODE_OFF 2
Definition at line 67 of file pager.h.
Referenced by pager_write(), sqlite3PagerBegin(), sqlite3PagerCommitPhaseOne(), sqlite3PagerJournalMode(), and sqlite3Pragma().
#define PAGER_JOURNALMODE_PERSIST 1
Definition at line 66 of file pager.h.
Referenced by pager_end_transaction(), sqlite3PagerJournalMode(), and sqlite3Pragma().
#define PAGER_JOURNALMODE_QUERY -1
Definition at line 64 of file pager.h.
Referenced by sqlite3PagerJournalMode(), and sqlite3Pragma().
#define PAGER_JOURNALMODE_TRUNCATE 3
Definition at line 68 of file pager.h.
Referenced by pager_end_transaction(), sqlite3PagerJournalMode(), and sqlite3Pragma().
#define PAGER_LOCKINGMODE_EXCLUSIVE 1
Definition at line 59 of file pager.h.
Referenced by getLockingMode(), sqlite3PagerLockingMode(), sqlite3PagerOpen(), and sqlite3Pragma().
#define PAGER_LOCKINGMODE_NORMAL 0
Definition at line 58 of file pager.h.
Referenced by getLockingMode(), sqlite3PagerLockingMode(), sqlite3PagerOpen(), and sqlite3Pragma().
#define PAGER_LOCKINGMODE_QUERY -1
Definition at line 57 of file pager.h.
Referenced by getLockingMode(), sqlite3PagerLockingMode(), and sqlite3Pragma().
#define PAGER_NO_READLOCK 0x0002
Definition at line 52 of file pager.h.
Referenced by sqlite3PagerOpen().
#define PAGER_OMIT_JOURNAL 0x0001
Definition at line 51 of file pager.h.
Referenced by sqlite3PagerOpen().
#define sqlite3PagerGet (A, B, C) sqlite3PagerAcquire(A,B,C,0)
Definition at line 84 of file pager.h.
Referenced by accessPayload(), btreeCopyFile(), checkList(), pager_incr_changecounter(), ptrmapGet(), ptrmapPut(), sqlite3BtreeGetMeta(), sqlite3PagerCommitPhaseOne(), sqlite3PagerMovepage(), and sqlite3PagerWrite().
#define SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT -1
Definition at line 27 of file pager.h.
Referenced by sqlite3PagerOpen().
Typedef Documentation
typedef struct PgHdr DbPage
Definition at line 44 of file pager.h.
typedef struct Pager Pager
Definition at line 39 of file pager.h.
typedef u32 Pgno
Definition at line 34 of file pager.h.
Function Documentation
int sqlite3PagerAcquire (Pager * pPager, Pgno pgno, DbPage ** ppPage, int clrFlag)
Definition at line 2808 of file pager.c.
References PgHdr::flags, IOTRACE, MEMDB, Pager::mxPgno, Pager::nExtra, pager_get_content(), PAGER_INCR, PAGER_MAX_PGNO, PAGER_MJ_PGNO, pager_pagehash, PAGER_UNLOCK, pagerDropPage(), pagerSharedLock(), Pager::pageSize, PgHdr::pData, PgHdr::pExtra, PGHDR_IN_JOURNAL, PGHDR_NEED_READ, Pager::pInJournal, PgHdr::pPager, Pager::pPCache, readDbPage(), sqlite3BitvecTest(), sqlite3PagerPagecount(), sqlite3PagerUnref(), sqlite3PcacheFetch(), sqlite3PcacheRefCount(), SQLITE_CORRUPT_BKPT, SQLITE_FULL, SQLITE_IOERR_SHORT_READ, SQLITE_OK, and Pager::state.
Referenced by sqlite3BtreeGetPage().
int sqlite3PagerBegin (DbPage * , int exFlag)
Definition at line 3053 of file pager.c.
References Pager::dbSize, Pager::dirtyCache, EXCLUSIVE_LOCK, Pager::fd, Pager::journalMode, Pager::journalOff, Pager::journalOpen, MEMDB, Pager::nRec, PgHdr::nRef, Pager::origDbSize, PAGER_JOURNALMODE_OFF, pager_open_journal(), PAGER_RESERVED, PAGER_SHARED, PAGER_UNLOCK, pager_wait_on_lock(), PAGERID, PAGERTRACE2, PGHDR_IN_JOURNAL, Pager::pInJournal, PgHdr::pPager, Pager::pPCache, RESERVED_LOCK, sqlite3BitvecCreate(), sqlite3OsLock(), sqlite3PagerPagecount(), sqlite3PcacheAssertFlags, SQLITE_NOMEM, SQLITE_OK, Pager::state, Pager::tempFile, Pager::useJournal, and writeJournalHdr().
Referenced by pager_write(), and sqlite3BtreeBeginTrans().
int sqlite3PagerClose (Pager * pPager)
Definition at line 2213 of file pager.c.
References disable_simulated_io_errors, enable_simulated_io_errors, Pager::errCode, Pager::exclusiveMode, Pager::fd, IOTRACE, Pager::jfd, Pager::journalOpen, MEMDB, pager_reset(), PAGERID, PAGERTRACE2, pagerUnlockAndRollback(), Pager::pAlwaysRollback, Pager::pInJournal, Pager::pPCache, Pager::pTmpSpace, sqlite3_free(), sqlite3BeginBenignMalloc(), sqlite3BitvecDestroy(), sqlite3EndBenignMalloc(), sqlite3OsClose(), sqlite3PageFree(), sqlite3PcacheClose(), SQLITE_OK, Pager::stfd, and Pager::stmtOpen.
Referenced by sqlite3BtreeClose(), and sqlite3BtreeOpen().
int sqlite3PagerCommitPhaseOne (Pager * , const char * zMaster, Pgno , int)
Definition at line 3608 of file pager.c.
References aJournalMagic, Pager::dbModified, Pager::dirtyCache, Pager::errCode, Pager::exclusiveMode, Pager::fd, IOTRACE, Pager::jfd, Pager::journalHdr, Pager::journalMode, Pager::journalOff, Pager::journalOpen, MEMDB, Pager::noSync, Pager::nRec, Pager::origDbSize, pager_incr_changecounter(), PAGER_JOURNALMODE_DELETE, PAGER_JOURNALMODE_OFF, PAGER_MJ_PGNO, PAGER_SYNCED, pager_write_pagelist(), PAGERTRACE4, PgHdr::pDirty, Pager::pInJournal, Pager::pPCache, Pager::setMaster, sqlite3BitvecTest(), sqlite3OsSync(), sqlite3PagerGet, sqlite3PagerTruncate(), sqlite3PagerUnref(), sqlite3PagerWrite(), sqlite3PcacheCleanAll(), sqlite3PcacheDirtyList(), SQLITE_BUSY, SQLITE_IOERR_BLOCKED, SQLITE_OK, Pager::state, Pager::sync_flags, syncJournal(), write32bits(), writeMasterJournal(), and Pager::zFilename.
Referenced by btreeCopyFile(), and sqlite3BtreeCommitPhaseOne().
int sqlite3PagerCommitPhaseTwo (Pager *)
Definition at line 3772 of file pager.c.
References Pager::dbModified, Pager::dirtyCache, Pager::errCode, Pager::exclusiveMode, Pager::journalMode, Pager::journalOpen, MEMDB, pager_end_transaction(), pager_error(), PAGER_JOURNALMODE_DELETE, PAGER_RESERVED, PAGER_SYNCED, PAGERID, PAGERTRACE2, Pager::setMaster, SQLITE_ERROR, SQLITE_OK, and Pager::state.
Referenced by sqlite3BtreeCommitPhaseTwo().
const char* sqlite3PagerDirname (Pager *)
Definition at line 4003 of file pager.c.
References Pager::zDirectory.
Referenced by sqlite3BtreeGetDirname().
void sqlite3PagerDontRollback (DbPage *)
Definition at line 3482 of file pager.c.
References PgHdr::flags, IOTRACE, Pager::journalOpen, Pager::origDbSize, PAGER_RESERVED, PAGERID, PAGERTRACE3, Pager::pAlwaysRollback, PGHDR_IN_JOURNAL, PGHDR_NEED_READ, PgHdr::pgno, Pager::pInJournal, Pager::pInStmt, PgHdr::pPager, sqlite3BitvecSet(), sqlite3BitvecTest(), Pager::state, Pager::stmtInUse, and Pager::stmtSize.
Referenced by allocateBtreePage().
int sqlite3PagerDontWrite (DbPage *)
Definition at line 3431 of file pager.c.
References Pager::dbSize, PgHdr::flags, IOTRACE, Pager::origDbSize, pager_pagehash, PAGER_SHARED, PAGERID, PAGERTRACE3, Pager::pAlwaysRollback, PGHDR_DIRTY, PGHDR_DONT_WRITE, PgHdr::pgno, Pager::pInJournal, PgHdr::pPager, sqlite3BitvecCreate(), sqlite3BitvecSet(), SQLITE_NOMEM, SQLITE_OK, Pager::state, and Pager::stmtInUse.
Referenced by btreeCopyFile(), and freePage().
sqlite3_file* sqlite3PagerFile (Pager *)
Definition at line 3996 of file pager.c.
References Pager::fd.
Referenced by btreeCopyFile(), sqlite3_file_control(), and sqlite3RunVacuum().
const char* sqlite3PagerFilename (Pager *)
Definition at line 3980 of file pager.c.
References Pager::zFilename.
Referenced by sqlite3BtreeGetFilename(), and sqlite3BtreeOpen().
void* sqlite3PagerGetData (DbPage *)
Definition at line 4153 of file pager.c.
References Pager::memDb, PgHdr::nRef, PgHdr::pData, and PgHdr::pPager.
Referenced by accessPayload(), btreeCopyFile(), btreePageFromDbPage(), checkList(), ptrmapGet(), ptrmapPut(), releasePage(), sqlite3BtreeGetMeta(), sqlite3BtreeInitPage(), unlockBtreeIfUnused(), and zeroPage().
void* sqlite3PagerGetExtra (DbPage *)
Definition at line 4162 of file pager.c.
References PgHdr::pExtra, and PgHdr::pPager.
Referenced by btreeCopyFile(), btreePageFromDbPage(), pageReinit(), releasePage(), sqlite3BtreeInitPage(), and zeroPage().
int sqlite3PagerIsreadonly (Pager *)
Definition at line 3845 of file pager.c.
References Pager::readOnly.
Referenced by sqlite3BtreeOpen().
int sqlite3PagerJournalMode (Pager * , int)
Definition at line 4204 of file pager.c.
References Pager::journalMode, MEMDB, PAGER_JOURNALMODE_DELETE, PAGER_JOURNALMODE_MEMORY, PAGER_JOURNALMODE_OFF, PAGER_JOURNALMODE_PERSIST, PAGER_JOURNALMODE_QUERY, and PAGER_JOURNALMODE_TRUNCATE.
Referenced by attachFunc(), sqlite3OpenTempDatabase(), and sqlite3Pragma().
const char* sqlite3PagerJournalname (Pager *)
Definition at line 4010 of file pager.c.
References Pager::zJournal.
Referenced by sqlite3BtreeGetJournalname().
i64 sqlite3PagerJournalSizeLimit (Pager * , i64)
Definition at line 4225 of file pager.c.
References Pager::journalSizeLimit.
Referenced by sqlite3Pragma().
int sqlite3PagerLockingMode (Pager * , int)
Definition at line 4177 of file pager.c.
References Pager::exclusiveMode, PAGER_LOCKINGMODE_EXCLUSIVE, PAGER_LOCKINGMODE_NORMAL, PAGER_LOCKINGMODE_QUERY, and Pager::tempFile.
Referenced by attachFunc(), openDatabase(), and sqlite3Pragma().
DbPage* sqlite3PagerLookup (Pager * pPager, Pgno pgno)
Definition at line 2915 of file pager.c.
References Pager::errCode, PAGER_UNLOCK, Pager::pPCache, sqlite3PcacheFetch(), SQLITE_FULL, SQLITE_OK, and Pager::state.
Referenced by getAndInitPage().
int sqlite3PagerMaxPageCount (Pager * , int)
Definition at line 2017 of file pager.c.
References Pager::mxPgno, and sqlite3PagerPagecount().
Referenced by sqlite3BtreeMaxPageCount().
int sqlite3PagerMovepage (Pager * , DbPage * , Pgno , int)
Definition at line 4059 of file pager.c.
References Pager::dbModified, Pager::dirtyCache, PgHdr::flags, IOTRACE, makeDirty(), MEMDB, Pager::needSync, Pager::noSync, PgHdr::nRef, Pager::origDbSize, pager_get_content(), pager_lookup(), PAGERID, PAGERTRACE5, PGHDR_DIRTY, PGHDR_IN_JOURNAL, PGHDR_NEED_SYNC, PgHdr::pgno, Pager::pInJournal, sqlite3BitvecClear(), sqlite3BitvecTest(), sqlite3PagerGet, sqlite3PagerUnref(), sqlite3PcacheMove(), sqlite3PcacheRelease(), and SQLITE_OK.
Referenced by relocatePage().
int sqlite3PagerNosync (Pager *)
Definition at line 4018 of file pager.c.
References Pager::noSync.
Referenced by sqlite3BtreeSyncDisabled().
int sqlite3PagerOpen (sqlite3_vfs * , Pager ** ppPager, const char * , int , int , int)
Definition at line 1732 of file pager.c.
References Pager::fd, FILEHANDLEID, FORCE_ALIGNMENT, IOTRACE, Pager::jfd, sqlite3_vfs::mxPathname, PAGER_EXCLUSIVE, PAGER_JOURNALMODE_MEMORY, PAGER_LOCKINGMODE_EXCLUSIVE, PAGER_LOCKINGMODE_NORMAL, PAGER_NO_READLOCK, PAGER_OMIT_JOURNAL, PAGER_UNLOCK, pagerStress(), PAGERTRACE3, Pager::pPCache, Pager::pTmpSpace, Pager::pVfs, setSectorSize(), sqlite3_free(), sqlite3JournalSize, sqlite3Malloc(), sqlite3MallocZero(), sqlite3MemJournalSize(), sqlite3OsClose(), sqlite3OsDeviceCharacteristics(), sqlite3OsFullPathname(), sqlite3OsOpen(), sqlite3OsSectorSize(), sqlite3PageMalloc(), sqlite3PcacheOpen(), sqlite3PcacheSize(), SQLITE_CANTOPEN, SQLITE_DEFAULT_JOURNAL_SIZE_LIMIT, SQLITE_DEFAULT_PAGE_SIZE, SQLITE_IOCAP_ATOMIC, SQLITE_IOCAP_ATOMIC512, SQLITE_IOCAP_ATOMIC64K, SQLITE_MAX_DEFAULT_PAGE_SIZE, SQLITE_MAX_PAGE_COUNT, SQLITE_NOMEM, SQLITE_OK, SQLITE_OPEN_READONLY, SQLITE_SYNC_NORMAL, Pager::state, Pager::stfd, sqlite3_vfs::szOsFile, Pager::vfsFlags, Pager::zDirectory, Pager::zFilename, and Pager::zJournal.
Referenced by sqlite3BtreeOpen().
int sqlite3PagerPagecount (Pager * , int *)
Definition at line 2082 of file pager.c.
References Pager::dbSize, Pager::errCode, Pager::fd, Pager::mxPgno, pager_error(), PAGER_UNLOCK, Pager::pageSize, PENDING_BYTE, sqlite3_file::pMethods, sqlite3OsFileSize(), SQLITE_OK, Pager::state, and Pager::tempFile.
Referenced by hasHotJournal(), lockBtree(), newDatabase(), pager_open_journal(), pagerPagecount(), pagerSharedLock(), sqlite3PagerAcquire(), sqlite3PagerBegin(), sqlite3PagerMaxPageCount(), sqlite3PagerTruncate(), sqlite3PagerWrite(), and sqlite3VdbeExec().
int sqlite3PagerPageRefcount (DbPage *)
Definition at line 3859 of file pager.c.
References sqlite3PcachePageRefcount().
Referenced by allocateBtreePage(), and pageReinit().
int sqlite3PagerReadFileheader (Pager * , int , unsigned char *)
Definition at line 2059 of file pager.c.
References Pager::fd, IOTRACE, sqlite3_file::pMethods, sqlite3OsRead(), SQLITE_IOERR_SHORT_READ, SQLITE_OK, and Pager::tempFile.
Referenced by sqlite3BtreeOpen().
int sqlite3PagerRef (DbPage *)
Definition at line 2261 of file pager.c.
References sqlite3PcacheRef(), and SQLITE_OK.
Referenced by sqlite3BtreeGetTempCursor().
int sqlite3PagerRefcount (Pager *)
Definition at line 3852 of file pager.c.
References Pager::pPCache, and sqlite3PcacheRefCount().
Referenced by autoVacuumCommit(), sqlite3BtreeIntegrityCheck(), and unlockBtreeIfUnused().
int sqlite3PagerRollback (Pager *)
Definition at line 3806 of file pager.c.
References Pager::dbSize, Pager::dirtyCache, Pager::errCode, Pager::journalOpen, MEMDB, pager_end_transaction(), pager_error(), PAGER_EXCLUSIVE, pager_playback(), PAGER_RESERVED, PAGERID, PAGERTRACE2, Pager::setMaster, SQLITE_FULL, SQLITE_OK, and Pager::state.
Referenced by autoVacuumCommit(), pagerUnlockAndRollback(), and sqlite3BtreeRollback().
void sqlite3PagerSetBusyhandler (Pager * , BusyHandler * pBusyHandler)
Definition at line 1952 of file pager.c.
References Pager::pBusyHandler.
Referenced by sqlite3BtreeOpen().
void sqlite3PagerSetCachesize (Pager * , int)
Definition at line 1643 of file pager.c.
References Pager::pPCache, and sqlite3PcacheSetCachesize().
Referenced by sqlite3BtreeSetCacheSize().
int sqlite3PagerSetPagesize (Pager * , u16 *)
Definition at line 1972 of file pager.c.
References Pager::dbSize, Pager::errCode, Pager::memDb, pager_reset(), Pager::pageSize, Pager::pPCache, Pager::pTmpSpace, setSectorSize(), sqlite3PageFree(), sqlite3PageMalloc(), sqlite3PcacheRefCount(), sqlite3PcacheSetPageSize(), SQLITE_MAX_PAGE_SIZE, SQLITE_NOMEM, and SQLITE_OK.
Referenced by lockBtree(), readJournalHdr(), sqlite3BtreeOpen(), and sqlite3BtreeSetPageSize().
void sqlite3PagerSetReiniter (Pager * , void(*)(DbPage *))
Definition at line 1963 of file pager.c.
References Pager::xReiniter.
Referenced by sqlite3BtreeOpen().
void sqlite3PagerSetSafetyLevel (Pager * , int , int)
Definition at line 1674 of file pager.c.
References Pager::fullSync, Pager::needSync, Pager::noSync, SQLITE_SYNC_FULL, SQLITE_SYNC_NORMAL, Pager::sync_flags, and Pager::tempFile.
Referenced by sqlite3BtreeSetSafetyLevel().
int sqlite3PagerStmtBegin (Pager *)
Definition at line 3937 of file pager.c.
References pagerStmtBegin().
Referenced by pager_open_journal(), and sqlite3BtreeBeginStmt().
int sqlite3PagerStmtCommit (Pager *)
Definition at line 3946 of file pager.c.
References PAGERID, PAGERTRACE2, Pager::pInStmt, sqlite3BitvecDestroy(), sqlite3IsMemJournal(), sqlite3OsTruncate(), SQLITE_OK, Pager::stfd, Pager::stmtAutoopen, Pager::stmtInUse, and Pager::stmtNRec.
Referenced by pager_end_transaction(), sqlite3BtreeCommitStmt(), and sqlite3PagerStmtRollback().
int sqlite3PagerStmtRollback (Pager *)
Definition at line 3964 of file pager.c.
References pager_stmt_playback(), PAGERID, PAGERTRACE2, sqlite3PagerStmtCommit(), SQLITE_OK, Pager::stmtAutoopen, and Pager::stmtInUse.
Referenced by sqlite3BtreeRollbackStmt().
int sqlite3PagerSync (Pager * pPager)
Definition at line 3576 of file pager.c.
References Pager::fd, MEMDB, sqlite3OsSync(), SQLITE_OK, and Pager::sync_flags.
Referenced by btreeCopyFile().
void* sqlite3PagerTempSpace (Pager *)
Definition at line 2006 of file pager.c.
References Pager::pTmpSpace.
Referenced by defragmentPage().
int sqlite3PagerTruncate (Pager * , Pgno)
Definition at line 2178 of file pager.c.
References Pager::dbSize, Pager::errCode, EXCLUSIVE_LOCK, PAGER_SHARED, pager_truncate(), pager_wait_on_lock(), sqlite3PagerPagecount(), SQLITE_OK, Pager::state, and syncJournal().
Referenced by btreeCopyFile(), and sqlite3PagerCommitPhaseOne().
int sqlite3PagerUnref (DbPage *)
Definition at line 2937 of file pager.c.
References pagerUnlockIfUnused(), PgHdr::pPager, sqlite3PcacheRelease(), and SQLITE_OK.
Referenced by accessPayload(), btreeCopyFile(), btreeCreateTable(), checkList(), clearCell(), pager_incr_changecounter(), ptrmapGet(), ptrmapPut(), releasePage(), sqlite3BtreeGetMeta(), sqlite3BtreeReleaseTempCursor(), sqlite3PagerAcquire(), sqlite3PagerCommitPhaseOne(), sqlite3PagerMovepage(), and sqlite3PagerWrite().
const sqlite3_vfs* sqlite3PagerVfs (Pager *)
Definition at line 3987 of file pager.c.
References Pager::pVfs.
Referenced by sqlite3BtreeOpen().
int sqlite3PagerWrite (DbPage *)
Definition at line 3309 of file pager.c.
References Pager::doNotSync, PgHdr::flags, MEMDB, Pager::needSync, Pager::noSync, pager_lookup(), PAGER_MJ_PGNO, pager_write(), Pager::pageSize, PGHDR_NEED_SYNC, PgHdr::pgno, Pager::pInJournal, PgHdr::pPager, Pager::sectorSize, sqlite3BitvecTest(), sqlite3PagerGet, sqlite3PagerPagecount(), sqlite3PagerUnref(), and SQLITE_OK.
Referenced by allocateBtreePage(), autoVacuumCommit(), balance(), balance_nonroot(), btreeCopyFile(), btreeCreateTable(), clearDatabasePage(), copyPayload(), freePage(), incrVacuumStep(), insertCell(), newDatabase(), pager_incr_changecounter(), ptrmapPut(), relocatePage(), sqlite3BtreeDelete(), sqlite3BtreeInsert(), sqlite3BtreeUpdateMeta(), and sqlite3PagerCommitPhaseOne().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1