ContextLogger2 Logger Daemon Internals: parse.c File Reference
parse.c File Reference
Classes
struct LimitVal
struct LikeOp
struct TrigEvent
struct AttachKey
union YYMINORTYPE
struct yyStackEntry
struct yyParser
Defines
#define INTERFACE 1
#define YYCODETYPE unsigned char
#define YYNOCODE 249
#define YYACTIONTYPE unsigned short int
#define YYWILDCARD 59
#define sqlite3ParserTOKENTYPE Token
#define YYSTACKDEPTH 100
#define sqlite3ParserARG_SDECL Parse *pParse;
#define sqlite3ParserARG_PDECL ,Parse *pParse
#define sqlite3ParserARG_FETCH Parse *pParse = yypParser->pParse
#define sqlite3ParserARG_STORE yypParser->pParse = pParse
#define YYNSTATE 598
#define YYNRULE 315
#define YYFALLBACK 1
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
#define YY_SHIFT_USE_DFLT (-99)
#define YY_SHIFT_MAX 396
#define YY_REDUCE_USE_DFLT (-144)
#define YY_REDUCE_MAX 295
#define YY_SZ_ACTTAB (int)(sizeof(yy_action)/sizeof(yy_action[0]))
#define TOKEN (yyminor.yy0)
Typedefs
typedef struct yyStackEntry yyStackEntry
typedef struct yyParser yyParser
Functions
void * sqlite3ParserAlloc (void *(*mallocProc)(size_t))
static void yy_destructor (yyParser *yypParser, YYCODETYPE yymajor, YYMINORTYPE *yypminor)
static int yy_pop_parser_stack (yyParser *pParser)
void sqlite3ParserFree (void *p, void(*freeProc)(void *))
static int yy_find_shift_action (yyParser *pParser, YYCODETYPE iLookAhead)
static int yy_find_reduce_action (int stateno, YYCODETYPE iLookAhead)
static void yyStackOverflow (yyParser *yypParser, YYMINORTYPE *yypMinor)
static void yy_shift (yyParser *yypParser, int yyNewState, int yyMajor, YYMINORTYPE *yypMinor)
static void yy_accept (yyParser *)
static void yy_reduce (yyParser *yypParser, int yyruleno)
static void yy_parse_failed (yyParser *yypParser)
static void yy_syntax_error (yyParser *yypParser, int yymajor, YYMINORTYPE yyminor)
void sqlite3Parser (void *yyp, int yymajor, sqlite3ParserTOKENTYPE yyminorsqlite3ParserARG_PDECL)
Variables
static const YYMINORTYPE yyzerominor
static const YYACTIONTYPE yy_action []
static const YYCODETYPE yy_lookahead []
static const short yy_shift_ofst []
static const short yy_reduce_ofst []
static const YYACTIONTYPE yy_default []
static const YYCODETYPE yyFallback []
struct {
YYCODETYPE lhs
unsigned char nrhs
} yyRuleInfo []
Define Documentation
#define INTERFACE 1
Definition at line 59 of file parse.c.
#define sqlite3ParserARG_FETCH Parse *pParse = yypParser->pParse
Definition at line 119 of file parse.c.
Referenced by yy_accept(), yy_destructor(), yy_parse_failed(), yy_reduce(), yy_syntax_error(), and yyStackOverflow().
#define sqlite3ParserARG_PDECL ,Parse *pParse
Definition at line 118 of file parse.c.
#define sqlite3ParserARG_SDECL Parse *pParse;
Definition at line 117 of file parse.c.
#define sqlite3ParserARG_STORE yypParser->pParse = pParse
Definition at line 120 of file parse.c.
Referenced by sqlite3Parser(), yy_accept(), yy_parse_failed(), yy_syntax_error(), and yyStackOverflow().
#define sqlite3ParserTOKENTYPE Token
Definition at line 99 of file parse.c.
#define TOKEN (yyminor.yy0)
Referenced by yy_syntax_error().
#define YY_ACCEPT_ACTION (YYNSTATE+YYNRULE+1)
Definition at line 125 of file parse.c.
#define YY_ERROR_ACTION (YYNSTATE+YYNRULE)
Definition at line 126 of file parse.c.
Referenced by sqlite3Parser().
#define YY_NO_ACTION (YYNSTATE+YYNRULE+2)
Definition at line 124 of file parse.c.
#define YY_REDUCE_MAX 295
Definition at line 504 of file parse.c.
Referenced by yy_find_reduce_action().
#define YY_REDUCE_USE_DFLT (-144)
Definition at line 503 of file parse.c.
Referenced by yy_find_reduce_action().
#define YY_SHIFT_MAX 396
Definition at line 460 of file parse.c.
Referenced by yy_find_shift_action().
#define YY_SHIFT_USE_DFLT (-99)
Definition at line 459 of file parse.c.
Referenced by yy_find_shift_action().
#define YY_SZ_ACTTAB (int)(sizeof(yy_action)/sizeof(yy_action[0]))
Definition at line 599 of file parse.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
#define YYACTIONTYPE unsigned short int
Definition at line 97 of file parse.c.
#define YYCODETYPE unsigned char
Definition at line 95 of file parse.c.
Referenced by yy_pop_parser_stack().
#define YYFALLBACK 1
Definition at line 123 of file parse.c.
#define YYNOCODE 249
Definition at line 96 of file parse.c.
Referenced by sqlite3Parser(), yy_find_reduce_action(), and yy_find_shift_action().
#define YYNRULE 315
Definition at line 122 of file parse.c.
Referenced by sqlite3Parser(), and yy_reduce().
#define YYNSTATE 598
Definition at line 121 of file parse.c.
Referenced by sqlite3Parser(), and yy_reduce().
#define YYSTACKDEPTH 100
Definition at line 115 of file parse.c.
Referenced by yy_shift().
#define YYWILDCARD 59
Definition at line 98 of file parse.c.
Referenced by yy_find_shift_action().
Typedef Documentation
typedef struct yyParser yyParser
Definition at line 792 of file parse.c.
typedef struct yyStackEntry yyStackEntry
Definition at line 774 of file parse.c.
Function Documentation
void sqlite3Parser (void * yyp, int yymajor, sqlite3ParserTOKENTYPE yyminor sqlite3ParserARG_PDECL)
Definition at line 3429 of file parse.c.
References yyStackEntry::major, sqlite3ParserARG_STORE, yyStackEntry::stateno, YYMINORTYPE::yy0, yy_destructor(), YY_ERROR_ACTION, yy_find_reduce_action(), yy_find_shift_action(), yy_parse_failed(), yy_pop_parser_stack(), yy_reduce(), yy_shift(), yy_syntax_error(), yyParser::yyerrcnt, yyParser::yyidx, YYNOCODE, YYNRULE, YYNSTATE, yyParser::yystack, and yyStackOverflow().
Referenced by sqlite3RunParser().
void* sqlite3ParserAlloc (void *(*)(size_t) mallocProc)
Definition at line 1253 of file parse.c.
References yyParser::yyidx.
Referenced by sqlite3RunParser().
void sqlite3ParserFree (void * p, void(*)(void *) freeProc)
Definition at line 1410 of file parse.c.
References yy_pop_parser_stack(), yyParser::yyidx, and yyParser::yystack.
Referenced by sqlite3RunParser().
static void yy_accept (yyParser * yypParser) [static]
Definition at line 3395 of file parse.c.
References sqlite3ParserARG_FETCH, sqlite3ParserARG_STORE, yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by yy_reduce().
static void yy_destructor (yyParser * yypParser, YYCODETYPE yymajor, YYMINORTYPE * yypminor) [static]
Definition at line 1273 of file parse.c.
References sqlite3DeleteTriggerStep(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlite3IdListDelete(), sqlite3ParserARG_FETCH, sqlite3SelectDelete(), sqlite3SrcListDelete(), YYMINORTYPE::yy242, YYMINORTYPE::yy352, YYMINORTYPE::yy354, YYMINORTYPE::yy419, YYMINORTYPE::yy43, YYMINORTYPE::yy450, and YYMINORTYPE::yy75.
Referenced by sqlite3Parser(), and yy_pop_parser_stack().
static int yy_find_reduce_action (int stateno, YYCODETYPE iLookAhead) [static]
Definition at line 1497 of file parse.c.
References yy_action, yy_default, yy_lookahead, YY_REDUCE_MAX, yy_reduce_ofst, YY_REDUCE_USE_DFLT, YY_SZ_ACTTAB, and YYNOCODE.
Referenced by sqlite3Parser(), and yy_reduce().
static int yy_find_shift_action (yyParser * pParser, YYCODETYPE iLookAhead) [static]
Definition at line 1441 of file parse.c.
References yyStackEntry::stateno, yy_action, yy_default, yy_lookahead, YY_SHIFT_MAX, yy_shift_ofst, YY_SHIFT_USE_DFLT, YY_SZ_ACTTAB, yyFallback, yyParser::yyidx, YYNOCODE, yyParser::yystack, and YYWILDCARD.
Referenced by sqlite3Parser().
static void yy_parse_failed (yyParser * yypParser) [static]
Definition at line 3358 of file parse.c.
References sqlite3ParserARG_FETCH, sqlite3ParserARG_STORE, yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by sqlite3Parser().
static int yy_pop_parser_stack (yyParser * pParser) [static]
Definition at line 1380 of file parse.c.
References yyStackEntry::major, yyStackEntry::minor, yy_destructor(), YYCODETYPE, yyParser::yyidx, and yyParser::yystack.
Referenced by sqlite3Parser(), sqlite3ParserFree(), yy_accept(), yy_parse_failed(), and yyStackOverflow().
static void yy_reduce (yyParser * yypParser, int yyruleno) [static]
Definition at line 1922 of file parse.c.
References TrigEvent::a, ExprList::a, SrcList::a, TrigEvent::b, LikeOp::eOperator, EP_Distinct, EP_InfixFunc, Expr::flags, Expr::iColumn, SrcList::SrcList_item::jointype, JT_INNER, yyStackEntry::major, YYMINORTYPE::mask, yyStackEntry::minor, Token::n, ExprList::nExpr, LikeOp::not, SrcList::nSrc, OE_Abort, OE_Cascade, OE_Default, OE_Fail, OE_Ignore, OE_None, OE_Replace, OE_Restrict, OE_Rollback, OE_SetDflt, OE_SetNull, Expr::op, Select::op, TriggerStep::pLast, LimitVal::pLimit, Expr::pList, TriggerStep::pNext, LimitVal::pOffset, Select::pPrior, Expr::pSelect, ExprList::ExprList_item::sortOrder, Expr::span, sqlite3AddCheckConstraint(), sqlite3AddCollateType(), sqlite3AddColumn(), sqlite3AddColumnType(), sqlite3AddDefaultValue(), sqlite3AddNotNull(), sqlite3AddPrimaryKey(), sqlite3AlterBeginAddColumn(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3Analyze(), sqlite3Attach(), sqlite3BeginParse(), sqlite3BeginTransaction(), sqlite3BeginTrigger(), sqlite3CommitTransaction(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3DbMallocZero(), sqlite3DeferForeignKey(), sqlite3DeleteFrom(), sqlite3Detach(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTrigger(), sqlite3EndTable(), sqlite3ErrorMsg(), sqlite3ExprAssignVarNumber(), sqlite3ExprFunction(), sqlite3ExprListAppend(), sqlite3ExprListCheckLength(), sqlite3ExprListDelete(), sqlite3ExprSetColl(), sqlite3ExprSetHeight, sqlite3ExprSpan(), sqlite3FinishCoding(), sqlite3FinishTrigger(), sqlite3IdListAppend(), sqlite3Insert(), sqlite3JoinType(), sqlite3ParserARG_FETCH, sqlite3PExpr(), sqlite3Pragma(), sqlite3RegisterExpr(), sqlite3Reindex(), sqlite3RollbackTransaction(), sqlite3Select(), sqlite3SelectDelete(), sqlite3SelectNew(), sqlite3SrcListAppend(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListDelete(), sqlite3SrcListIndexedBy(), sqlite3SrcListShiftJoinType(), sqlite3StartTable(), sqlite3TriggerDeleteStep(), sqlite3TriggerInsertStep(), sqlite3TriggerSelectStep(), sqlite3TriggerUpdateStep(), sqlite3Update(), sqlite3Vacuum(), sqlite3VtabArgExtend(), sqlite3VtabArgInit(), sqlite3VtabBeginParse(), sqlite3VtabFinishParse(), SQLITE_MAX_FUNCTION_ARG, SQLITE_SO_ASC, SQLITE_SO_DESC, SRT_Output, yyStackEntry::stateno, TK_AFTER, TK_ALL, TK_BEFORE, TK_BETWEEN, TK_CASE, TK_CAST, TK_COLUMN, TK_CONST_FUNC, TK_DEFERRED, TK_DOT, TK_EXISTS, TK_ID, TK_IN, TK_INSTEAD, TK_ISNULL, TK_NOT, TK_NOTNULL, TK_RAISE, TK_SELECT, TK_STRING, TK_UMINUS, TK_UPDATE, TK_UPLUS, TK_VARIABLE, YYMINORTYPE::value, YYMINORTYPE::yy0, YYMINORTYPE::yy207, YYMINORTYPE::yy242, YYMINORTYPE::yy316, YYMINORTYPE::yy352, YYMINORTYPE::yy354, YYMINORTYPE::yy419, YYMINORTYPE::yy43, YYMINORTYPE::yy450, YYMINORTYPE::yy75, YYMINORTYPE::yy84, YYMINORTYPE::yy86, yy_accept(), yy_find_reduce_action(), yy_shift(), yyParser::yyidx, YYNRULE, YYNSTATE, yyRuleInfo, yyParser::yystack, and Token::z.
Referenced by sqlite3Parser().
static void yy_shift (yyParser * yypParser, int yyNewState, int yyMajor, YYMINORTYPE * yypMinor) [static]
Definition at line 1549 of file parse.c.
References yyStackEntry::major, yyStackEntry::minor, yyStackEntry::stateno, yyParser::yyidx, yyParser::yystack, YYSTACKDEPTH, and yyStackOverflow().
Referenced by sqlite3Parser(), and yy_reduce().
static void yy_syntax_error (yyParser * yypParser, int yymajor, YYMINORTYPE yyminor) [static]
Definition at line 3376 of file parse.c.
References sqlite3ErrorMsg(), sqlite3ParserARG_FETCH, sqlite3ParserARG_STORE, and TOKEN.
Referenced by sqlite3Parser().
static void yyStackOverflow (yyParser * yypParser, YYMINORTYPE * yypMinor) [static]
Definition at line 1527 of file parse.c.
References sqlite3ErrorMsg(), sqlite3ParserARG_FETCH, sqlite3ParserARG_STORE, yy_pop_parser_stack(), and yyParser::yyidx.
Referenced by sqlite3Parser(), and yy_shift().
Variable Documentation
YYCODETYPE lhs
Definition at line 1596 of file parse.c.
unsigned char nrhs
Definition at line 1597 of file parse.c.
const YYACTIONTYPE yy_action[] [static]
Definition at line 183 of file parse.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
const YYACTIONTYPE yy_default[] [static]
Definition at line 537 of file parse.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
const YYCODETYPE yy_lookahead[] [static]
Definition at line 321 of file parse.c.
Referenced by yy_find_reduce_action(), and yy_find_shift_action().
const short yy_reduce_ofst[] [static]
Definition at line 505 of file parse.c.
Referenced by yy_find_reduce_action().
const short yy_shift_ofst[] [static]
Definition at line 461 of file parse.c.
Referenced by yy_find_shift_action().
const YYCODETYPE yyFallback[] [static]
Definition at line 612 of file parse.c.
Referenced by yy_find_shift_action().
struct { ... } yyRuleInfo[] [static]
Referenced by yy_reduce().
const YYMINORTYPE yyzerominor [static]
Definition at line 133 of file parse.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1