ContextLogger2 Logger Daemon Internals: pcache.h File Reference
pcache.h File Reference
Classes
struct PgHdr
Defines
#define PGHDR_IN_JOURNAL 0x001
#define PGHDR_DIRTY 0x002
#define PGHDR_NEED_SYNC 0x004
#define PGHDR_NEED_READ 0x008
#define PGHDR_REUSE_UNLIKELY 0x010
#define PGHDR_DONT_WRITE 0x020
#define sqlite3PcacheAssertFlags(A, B, C)
Typedefs
typedef struct PgHdr PgHdr
typedef struct PCache PCache
Functions
int sqlite3PcacheInitialize (void)
void sqlite3PcacheShutdown (void)
void sqlite3PCacheBufferSetup (void *, int sz, int n)
void * sqlite3PCacheMalloc (int sz)
void sqlite3PCacheFree (void *)
void sqlite3PcacheOpen (int szPage, int szExtra, int bPurgeable, int(*xStress)(void *, PgHdr *), void *pStress, PCache *pToInit)
void sqlite3PcacheSetPageSize (PCache *, int)
int sqlite3PcacheSize (void)
int sqlite3PcacheFetch (PCache *, Pgno, int createFlag, PgHdr **)
void sqlite3PcacheRelease (PgHdr *)
void sqlite3PcacheDrop (PgHdr *)
void sqlite3PcacheMakeDirty (PgHdr *)
void sqlite3PcacheMakeClean (PgHdr *)
void sqlite3PcacheCleanAll (PCache *)
void sqlite3PcacheMove (PgHdr *, Pgno)
void sqlite3PcacheTruncate (PCache *, Pgno x)
PgHdr * sqlite3PcacheDirtyList (PCache *)
void sqlite3PcacheClose (PCache *)
void sqlite3PcacheClearFlags (PCache *, int mask)
int sqlite3PcacheZeroOrOneDirtyPages (PCache *)
int sqlite3PcacheClear (PCache *)
int sqlite3PcacheRefCount (PCache *)
void sqlite3PcacheRef (PgHdr *)
int sqlite3PcachePageRefcount (PgHdr *)
int sqlite3PcachePagecount (PCache *)
int sqlite3PcacheGetCachesize (PCache *)
void sqlite3PcacheSetCachesize (PCache *, int)
Define Documentation
#define PGHDR_DIRTY 0x002
Definition at line 56 of file pcache.h.
Referenced by pagerStress(), pcacheAddToLruList(), pcacheMakeClean(), pcacheRecyclePage(), pcacheRemoveFromLruList(), sqlite3PagerDontWrite(), sqlite3PagerMovepage(), sqlite3PcacheCleanAll(), sqlite3PcacheDrop(), sqlite3PcacheFetch(), sqlite3PcacheMakeClean(), sqlite3PcacheMakeDirty(), sqlite3PcacheMove(), sqlite3PcacheRelease(), and sqlite3PcacheTruncate().
#define PGHDR_DONT_WRITE 0x020
Definition at line 61 of file pcache.h.
Referenced by pager_write_pagelist(), sqlite3PagerDontWrite(), and sqlite3PcacheMakeDirty().
#define PGHDR_IN_JOURNAL 0x001
Definition at line 55 of file pcache.h.
Referenced by pager_end_transaction(), pager_write(), sqlite3PagerAcquire(), sqlite3PagerBegin(), sqlite3PagerDontRollback(), and sqlite3PagerMovepage().
#define PGHDR_NEED_READ 0x008
Definition at line 59 of file pcache.h.
Referenced by pager_get_content(), sqlite3PagerAcquire(), and sqlite3PagerDontRollback().
#define PGHDR_NEED_SYNC 0x004
Definition at line 57 of file pcache.h.
Referenced by pager_end_transaction(), pager_playback_one_page(), pager_write(), pagerStress(), pcacheAddToList(), pcacheRecycleOrAlloc(), pcacheRemoveFromList(), sqlite3PagerMovepage(), sqlite3PagerWrite(), sqlite3PcacheClearFlags(), and syncJournal().
#define PGHDR_REUSE_UNLIKELY 0x010
Definition at line 60 of file pcache.h.
Referenced by pcacheAddToLruList(), and sqlite3PcacheMove().
#define sqlite3PcacheAssertFlags (A, B, C)
Definition at line 125 of file pcache.h.
Referenced by sqlite3PagerBegin(), sqlite3PcacheCleanAll(), and syncJournal().
Typedef Documentation
typedef struct PCache PCache
Definition at line 21 of file pcache.h.
typedef struct PgHdr PgHdr
Definition at line 20 of file pcache.h.
Function Documentation
void sqlite3PCacheBufferSetup (void * , int sz, int n)
Definition at line 388 of file pcache.c.
References pcache_g, and PgFreeslot::pNext.
Referenced by sqlite3_initialize().
void sqlite3PcacheCleanAll (PCache *)
Definition at line 838 of file pcache.c.
References expensive_assert, PgHdr::flags, PCache::nPinned, PgHdr::nRef, pcacheAddToList(), pcacheAddToLruList(), pcacheEnterMutex, pcacheExitMutex, pcacheRemoveFromList(), PCache::pClean, PCache::pDirty, PGHDR_DIRTY, and sqlite3PcacheAssertFlags.
Referenced by pager_end_transaction(), and sqlite3PagerCommitPhaseOne().
int sqlite3PcacheClear (PCache *)
Definition at line 985 of file pcache.c.
References PCache::nRef, pcacheClear(), pcacheEnterMutex, pcacheExitMutex, and SQLITE_OK.
Referenced by pager_reset().
void sqlite3PcacheClearFlags (PCache * , int mask)
Definition at line 1117 of file pcache.c.
References PgHdr::flags, pcacheEnterMutex, pcacheExitMutex, PCache::pClean, PCache::pDirty, PCache::pDirtyTail, PGHDR_NEED_SYNC, PgHdr::pNext, and PCache::pSynced.
Referenced by pager_end_transaction(), and syncJournal().
void sqlite3PcacheClose (PCache *)
Definition at line 950 of file pcache.c.
References PCache::apHash, PCache::bPurgeable, PCache::nMax, PCache::nMin, pcache_g, pcacheClear(), pcacheEnforceMaxPage(), pcacheEnterMutex, pcacheExitMutex, and sqlite3_free().
Referenced by sqlite3PagerClose().
PgHdr* sqlite3PcacheDirtyList (PCache *)
Definition at line 1070 of file pcache.c.
References pcacheSortDirtyList(), PgHdr::pDirty, PCache::pDirty, and PgHdr::pNext.
Referenced by sqlite3PagerCommitPhaseOne().
void sqlite3PcacheDrop (PgHdr *)
Definition at line 778 of file pcache.c.
References PgHdr::flags, PCache::nPinned, PCache::nRef, PgHdr::nRef, PgHdr::pCache, pcacheEnterMutex, pcacheExitMutex, pcachePageFree(), pcacheRemoveFromHash(), pcacheRemoveFromList(), PCache::pClean, and PGHDR_DIRTY.
Referenced by pagerDropPage().
int sqlite3PcacheFetch (PCache * , Pgno , int createFlag, PgHdr **)
Definition at line 676 of file pcache.c.
References PCache::apHash, expensive_assert, PgHdr::flags, PCache::nHash, PCache::nPage, PCache::nPinned, PCache::nRef, PgHdr::nRef, PgHdr::pCache, pcache_g, pcacheAddToHash(), pcacheAddToList(), pcacheEnterMutex, pcacheExitMutex, pcacheRecycleOrAlloc(), pcacheRemoveFromLruList(), pcacheResizeHash(), PCache::pClean, PgHdr::pDirty, PGHDR_DIRTY, PgHdr::pgno, PgHdr::pNextHash, PgHdr::pPager, and SQLITE_OK.
Referenced by pager_lookup(), sqlite3PagerAcquire(), and sqlite3PagerLookup().
void sqlite3PCacheFree (void *)
int sqlite3PcacheGetCachesize (PCache *)
Definition at line 1144 of file pcache.c.
References PCache::nMax.
int sqlite3PcacheInitialize (void)
Definition at line 612 of file pcache.c.
References pcache, pcache_g, sqlite3_mutex_alloc, sqlite3GlobalConfig, SQLITE_MUTEX_STATIC_LRU, and SQLITE_OK.
Referenced by sqlite3_initialize().
void sqlite3PcacheMakeClean (PgHdr *)
Definition at line 827 of file pcache.c.
References PgHdr::flags, pcacheEnterMutex, pcacheExitMutex, pcacheMakeClean(), and PGHDR_DIRTY.
Referenced by makeClean(), and pagerStress().
void sqlite3PcacheMakeDirty (PgHdr *)
Definition at line 796 of file pcache.c.
References PgHdr::flags, PgHdr::nRef, PgHdr::pCache, pcacheAddToList(), pcacheEnterMutex, pcacheExitMutex, pcacheRemoveFromList(), PCache::pClean, PCache::pDirty, PGHDR_DIRTY, and PGHDR_DONT_WRITE.
Referenced by makeDirty().
void* sqlite3PCacheMalloc (int sz)
void sqlite3PcacheMove (PgHdr * , Pgno)
Definition at line 860 of file pcache.c.
References PgHdr::flags, PgHdr::nRef, pcacheAddToHash(), pcacheEnterMutex, pcacheExitMutex, pcacheMakeClean(), pcacheRemoveFromHash(), PGHDR_DIRTY, PGHDR_REUSE_UNLIKELY, and PgHdr::pgno.
Referenced by sqlite3PagerMovepage().
void sqlite3PcacheOpen (int szPage, int szExtra, int bPurgeable, int(*)(void *, PgHdr *) xStress, void * pStress, PCache * pToInit)
Definition at line 637 of file pcache.c.
References PCache::bPurgeable, PCache::nMax, PCache::nMin, pcache_g, pcacheEnterMutex, pcacheExitMutex, PCache::pStress, PCache::szExtra, PCache::szPage, and PCache::xStress.
Referenced by sqlite3PagerOpen().
int sqlite3PcachePagecount (PCache *)
Definition at line 1092 of file pcache.c.
References PCache::nPage.
Referenced by pagerSharedLock().
int sqlite3PcachePageRefcount (PgHdr *)
Definition at line 1085 of file pcache.c.
References PgHdr::nRef.
Referenced by sqlite3PagerPageRefcount().
void sqlite3PcacheRef (PgHdr *)
Definition at line 768 of file pcache.c.
References PgHdr::nRef.
Referenced by sqlite3PagerRef().
int sqlite3PcacheRefCount (PCache *)
Definition at line 1081 of file pcache.c.
References PCache::nRef.
Referenced by pager_error(), pagerSharedLock(), pagerUnlockIfUnused(), sqlite3PagerAcquire(), sqlite3PagerRefcount(), and sqlite3PagerSetPagesize().
void sqlite3PcacheRelease (PgHdr *)
Definition at line 743 of file pcache.c.
References PgHdr::flags, PCache::nPinned, PCache::nRef, PgHdr::nRef, PgHdr::pCache, pcache_g, pcacheAddToList(), pcacheAddToLruList(), pcacheEnterMutex, pcacheExitMutex, pcachePageFree(), pcacheRemoveFromHash(), pcacheRemoveFromList(), PCache::pClean, PCache::pDirty, and PGHDR_DIRTY.
Referenced by pager_playback_one_page(), sqlite3PagerMovepage(), and sqlite3PagerUnref().
void sqlite3PcacheSetCachesize (PCache * , int)
Definition at line 1151 of file pcache.c.
References PCache::bPurgeable, PCache::nMax, pcache_g, pcacheEnforceMaxPage(), pcacheEnterMutex, and pcacheExitMutex.
Referenced by sqlite3PagerSetCachesize().
void sqlite3PcacheSetPageSize (PCache * , int)
Definition at line 668 of file pcache.c.
References PCache::nPage, and PCache::szPage.
Referenced by sqlite3PagerSetPagesize().
void sqlite3PcacheShutdown (void)
Definition at line 624 of file pcache.c.
References pcache, and pcache_g.
Referenced by sqlite3_shutdown().
int sqlite3PcacheSize (void)
Definition at line 631 of file pcache.c.
Referenced by sqlite3PagerOpen().
void sqlite3PcacheTruncate (PCache * , Pgno x)
Definition at line 902 of file pcache.c.
References PgHdr::flags, PCache::nPinned, PgHdr::nRef, pcacheEnterMutex, pcacheExitMutex, pcachePageFree(), pcacheRemoveFromHash(), pcacheRemoveFromList(), pcacheRemoveFromLruList(), PCache::pClean, PgHdr::pData, PCache::pDirty, PGHDR_DIRTY, PgHdr::pgno, PgHdr::pNext, and PCache::szPage.
Referenced by pager_truncate_cache().
int sqlite3PcacheZeroOrOneDirtyPages (PCache *)
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1