ContextLogger2 Logger Daemon Internals: pragma.c File Reference
pragma.c File Reference
Defines
#define SQLITE_INTEGRITY_CHECK_ERROR_MAX 100
Functions
static int getSafetyLevel (const char *z)
static int getBoolean (const char *z)
static int getLockingMode (const char *z)
static int getAutoVacuum (const char *z)
static int getTempStore (const char *z)
static int invalidateTempStorage (Parse *pParse)
static int changeTempStorage (Parse *pParse, const char *zStorageType)
static void returnSingleInt (Parse *pParse, const char *zLabel, int value)
static int flagPragma (Parse *pParse, const char *zLeft, const char *zRight)
static const char * actionName (u8 action)
void sqlite3Pragma (Parse *pParse, Token *pId1, Token *pId2, Token *pValue, int minusFlag)
Define Documentation
#define SQLITE_INTEGRITY_CHECK_ERROR_MAX 100
Referenced by sqlite3Pragma().
Function Documentation
static const char* actionName (u8 action) [static]
Definition at line 224 of file pragma.c.
References OE_Cascade, OE_Restrict, OE_SetDflt, and OE_SetNull.
Referenced by sqlite3Pragma().
static int changeTempStorage (Parse * pParse, const char * zStorageType) [static]
Definition at line 133 of file pragma.c.
References Parse::db, db, getTempStore(), invalidateTempStorage(), SQLITE_ERROR, SQLITE_OK, and sqlite3::temp_store.
Referenced by sqlite3Pragma().
static int flagPragma (Parse * pParse, const char * zLeft, const char * zRight) [static]
Definition at line 165 of file pragma.c.
References Parse::db, db, sqlite3::flags, getBoolean(), OP_Expire, returnSingleInt(), sqlite3GetVdbe(), sqlite3StrICmp(), sqlite3VdbeAddOp2(), SQLITE_CountRows, SQLITE_FullColNames, SQLITE_FullFSync, SQLITE_IgnoreChecks, SQLITE_LegacyFileFmt, SQLITE_NoReadlock, SQLITE_NullCallback, SQLITE_ReadUncommitted, SQLITE_RecoveryMode, SQLITE_ShortColNames, SQLITE_SqlTrace, SQLITE_VdbeListing, SQLITE_VdbeTrace, and SQLITE_WriteSchema.
Referenced by sqlite3Pragma().
static int getAutoVacuum (const char * z) [static]
Definition at line 77 of file pragma.c.
References BTREE_AUTOVACUUM_FULL, BTREE_AUTOVACUUM_INCR, BTREE_AUTOVACUUM_NONE, and sqlite3StrICmp().
Referenced by sqlite3Pragma().
static int getBoolean (const char * z) [static]
Definition at line 55 of file pragma.c.
References getSafetyLevel().
Referenced by flagPragma(), and sqlite3Pragma().
static int getLockingMode (const char * z) [static]
Definition at line 62 of file pragma.c.
References PAGER_LOCKINGMODE_EXCLUSIVE, PAGER_LOCKINGMODE_NORMAL, PAGER_LOCKINGMODE_QUERY, and sqlite3StrICmp().
Referenced by sqlite3Pragma().
static int getSafetyLevel (const char * z) [static]
Definition at line 33 of file pragma.c.
References sqlite3StrNICmp().
Referenced by getBoolean(), and sqlite3Pragma().
static int getTempStore (const char * z) [static]
Definition at line 93 of file pragma.c.
References sqlite3StrICmp().
Referenced by changeTempStorage().
static int invalidateTempStorage (Parse * pParse) [static]
Definition at line 111 of file pragma.c.
References sqlite3::aDb, sqlite3::autoCommit, Parse::db, db, Db::pBt, sqlite3BtreeClose(), sqlite3BtreeIsInReadTrans(), sqlite3ErrorMsg(), sqlite3ResetInternalSchema(), SQLITE_ERROR, and SQLITE_OK.
Referenced by changeTempStorage(), and sqlite3Pragma().
static void returnSingleInt (Parse * pParse, const char * zLabel, int value) [static]
Definition at line 148 of file pragma.c.
References COLNAME_NAME, Parse::explain, Parse::nMem, OP_Integer, OP_ResultRow, sqlite3GetVdbe(), sqlite3VdbeAddOp2(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), and SQLITE_STATIC.
Referenced by flagPragma(), and sqlite3Pragma().
void sqlite3Pragma (Parse * pParse, Token * pId1, Token * pId2, Token * pValue, int minusFlag)
Definition at line 249 of file pragma.c.
References FKey::aCol, Table::aCol, sqlite3::aCollSeq, actionName(), sqlite3::aDb, Index::aiColumn, ArraySize, sqlite3::autoCommit, Schema::cache_size, changeTempStorage(), COLNAME_NAME, Parse::db, db, DB_Empty, DB_SchemaLoaded, DbHasProperty, FKey::deleteConf, sqlite3::dfltJournalMode, sqlite3::dfltLockMode, ENC, flagPragma(), sqlite3::flags, getAutoVacuum(), getBoolean(), getLockingMode(), getSafetyLevel(), FKey::sColMap::iFrom, invalidateTempStorage(), IsHiddenColumn, Column::isPrimKey, sqlite3::mallocFailed, Token::n, FKey::nCol, Table::nCol, Index::nColumn, sqlite3::nDb, sqlite3::nextAutovac, sqlite3::nextPagesize, Parse::nMem, Column::notNull, OE_Abort, OE_None, OMIT_TEMPDB, Index::onError, OP_AddImm, OP_Concat, OP_Eq, OP_Expire, OP_Found, OP_Halt, OP_If, OP_IfNeg, OP_IfPos, OP_IncrVacuum, OP_Integer, OP_IntegrityCk, OP_IsNull, OP_Move, OP_Next, OP_Null, OP_OpenRead, OP_Pagecount, OP_ReadCookie, OP_ResultRow, OP_Rewind, OP_Rowid, OP_SetCookie, OP_String8, OP_Subtract, OP_Transaction, P4_DYNAMIC, P4_STATIC, PAGER_JOURNALMODE_DELETE, PAGER_JOURNALMODE_MEMORY, PAGER_JOURNALMODE_OFF, PAGER_JOURNALMODE_PERSIST, PAGER_JOURNALMODE_QUERY, PAGER_JOURNALMODE_TRUNCATE, PAGER_LOCKINGMODE_EXCLUSIVE, PAGER_LOCKINGMODE_NORMAL, PAGER_LOCKINGMODE_QUERY, Db::pBt, Column::pDflt, Table::pFKey, Table::pIndex, Index::pNext, FKey::pNextFrom, Db::pSchema, Index::pTable, Parse::pVdbe, sqlite3::pVfs, returnSingleInt(), Db::safety_level, Expr::span, sqlite3_file_control(), sqlite3_free(), sqlite3_key(), sqlite3_temp_directory, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3BtreeGetAutoVacuum(), sqlite3BtreeGetFilename(), sqlite3BtreeGetPageSize(), sqlite3BtreeMaxPageCount(), sqlite3BtreePager(), sqlite3BtreeSetAutoVacuum(), sqlite3BtreeSetCacheSize(), sqlite3BtreeSetPageSize(), sqlite3BtreeSetSafetyLevel(), sqlite3CodeVerifySchema(), sqlite3DbFree(), sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GenerateIndexKey(), sqlite3GetInt32(), sqlite3GetVdbe(), sqlite3MPrintf(), sqlite3NameFromToken(), sqlite3OpenTableAndIndices(), sqlite3OpenTempDatabase(), sqlite3OsAccess(), sqlite3PagerJournalMode(), sqlite3PagerJournalSizeLimit(), sqlite3PagerLockingMode(), sqlite3ReadSchema(), sqlite3RegisterLikeFunctions(), sqlite3StrICmp(), sqlite3StrNICmp(), sqlite3TwoPartName(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeAddOpList(), sqlite3VdbeChangeP1(), sqlite3VdbeChangeP2(), sqlite3VdbeChangeP3(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), sqlite3VdbeCreate(), sqlite3VdbeJumpHere(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3VdbeUsesBtree(), sqlite3ViewGetColumnNames(), SQLITE_ACCESS_READWRITE, SQLITE_DEFAULT_AUTOVACUUM, SQLITE_DEFAULT_CACHE_SIZE, SQLITE_FCNTL_LOCKSTATE, SQLITE_FullFSync, SQLITE_INTEGRITY_CHECK_ERROR_MAX, SQLITE_NOMEM, SQLITE_OK, SQLITE_PRAGMA, SQLITE_STATIC, SQLITE_TEMP_STORE, SQLITE_TRANSIENT, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF16NATIVE, SQLITE_UTF8, sqliteHashData, sqliteHashFirst, sqliteHashNext, Schema::tblHash, sqlite3::temp_store, Index::tnum, Table::tnum, FKey::updateConf, Token::z, FKey::sColMap::zCol, CollSeq::zName, Index::zName, Column::zName, Db::zName, FKey::zTo, and Column::zType.
Referenced by yy_reduce().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1