ContextLogger2 Logger Daemon Internals: prepare.c File Reference
prepare.c File Reference
Functions
static void corruptSchema (InitData *pData, const char *zObj, const char *zExtra)
int sqlite3InitCallback (void *pInit, int argc, char **argv, char **azColName)
static int sqlite3InitOne (sqlite3 *db, int iDb, char **pzErrMsg)
int sqlite3Init (sqlite3 *db, char **pzErrMsg)
int sqlite3ReadSchema (Parse *pParse)
static int schemaIsValid (sqlite3 *db)
int sqlite3SchemaToIndex (sqlite3 *db, Schema *pSchema)
static int sqlite3Prepare (sqlite3 *db, const char *zSql, int nBytes, int saveSqlFlag, sqlite3_stmt **ppStmt, const char **pzTail)
static int sqlite3LockAndPrepare (sqlite3 *db, const char *zSql, int nBytes, int saveSqlFlag, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3Reprepare (Vdbe *p)
int sqlite3_prepare (sqlite3 *db, const char *zSql, int nBytes, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare_v2 (sqlite3 *db, const char *zSql, int nBytes, sqlite3_stmt **ppStmt, const char **pzTail)
static int sqlite3Prepare16 (sqlite3 *db, const void *zSql, int nBytes, int saveSqlFlag, sqlite3_stmt **ppStmt, const void **pzTail)
int sqlite3_prepare16 (sqlite3 *db, const void *zSql, int nBytes, sqlite3_stmt **ppStmt, const void **pzTail)
int sqlite3_prepare16_v2 (sqlite3 *db, const void *zSql, int nBytes, sqlite3_stmt **ppStmt, const void **pzTail)
Function Documentation
static void corruptSchema (InitData * pData, const char * zObj, const char * zExtra) [static]
Definition at line 25 of file prepare.c.
References InitData::db, db, sqlite3::flags, sqlite3::mallocFailed, InitData::pzErrMsg, InitData::rc, sqlite3MAppendf(), sqlite3SetString(), SQLITE_CORRUPT, and SQLITE_RecoveryMode.
Referenced by sqlite3InitCallback().
static int schemaIsValid (sqlite3 * db) [static]
Definition at line 451 of file prepare.c.
References sqlite3::aDb, sqlite3::mallocFailed, MASTER_ROOT, sqlite3::mutex, sqlite3::nDb, Db::pBt, Db::pSchema, Schema::schema_cookie, sqlite3_free(), sqlite3_mutex_held, sqlite3BtreeCloseCursor(), sqlite3BtreeCursor(), sqlite3BtreeCursorSize(), sqlite3BtreeGetMeta(), sqlite3Malloc(), SQLITE_IOERR_NOMEM, SQLITE_NOMEM, and SQLITE_OK.
Referenced by sqlite3Prepare().
int sqlite3_prepare (sqlite3 * db, const char * zSql, int nBytes, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 708 of file prepare.c.
References sqlite3LockAndPrepare(), and SQLITE_OK.
Referenced by DbObjCmd(), do_meta_command(), dump_callback(), execExecSql(), execSql(), FUNC(), run_table_dump_query(), sql_prepare(), and sqlite3_exec().
int sqlite3_prepare16 (sqlite3 * db, const void * zSql, int nBytes, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 786 of file prepare.c.
References sqlite3Prepare16(), and SQLITE_OK.
int sqlite3_prepare16_v2 (sqlite3 * db, const void * zSql, int nBytes, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 798 of file prepare.c.
References sqlite3Prepare16(), and SQLITE_OK.
int sqlite3_prepare_v2 (sqlite3 * db, const char * zSql, int nBytes, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 720 of file prepare.c.
References sqlite3LockAndPrepare(), and SQLITE_OK.
Referenced by DbObjCmd(), and sql_prepare().
int sqlite3Init (sqlite3 * db, char ** pzErrMsg)
Definition at line 391 of file prepare.c.
References sqlite3::sqlite3InitInfo::busy, DB_SchemaLoaded, DbHasProperty, sqlite3::flags, sqlite3::init, sqlite3::mutex, sqlite3::nDb, sqlite3_mutex_held, sqlite3CommitInternalChanges(), sqlite3InitOne(), sqlite3ResetInternalSchema(), SQLITE_InternChanges, and SQLITE_OK.
Referenced by attachFunc(), and sqlite3ReadSchema().
int sqlite3InitCallback (void * pInit, int argc, char ** argv, char ** azColName)
Definition at line 55 of file prepare.c.
References sqlite3::aDb, Lookaside::bEnabled, sqlite3::sqlite3InitInfo::busy, corruptSchema(), InitData::db, db, DB_Empty, DbClearProperty, sqlite3::sqlite3InitInfo::iDb, InitData::iDb, sqlite3::init, sqlite3::lookaside, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::sqlite3InitInfo::newTnum, InitData::rc, sqlite3_exec(), sqlite3_mutex_held, sqlite3DbFree(), sqlite3FindIndex(), SQLITE_INTERRUPT, SQLITE_NOMEM, SQLITE_OK, Index::tnum, and Db::zName.
Referenced by sqlite3InitOne(), and sqlite3VdbeExec().
static int sqlite3InitOne (sqlite3 * db, int iDb, char ** pzErrMsg) [static]
Definition at line 132 of file prepare.c.
References sqlite3::aDb, sqlite3::sqlite3InitInfo::busy, Schema::cache_size, InitData::db, DB_Empty, DB_SchemaLoaded, DbSetProperty, Schema::enc, ENC, Schema::file_format, sqlite3::flags, InitData::iDb, sqlite3::init, sqlite3::mallocFailed, MASTER_ROOT, sqlite3::mutex, OMIT_TEMPDB, Db::pBt, sqlite3::pDfltColl, Db::pSchema, InitData::pzErrMsg, InitData::rc, Schema::schema_cookie, SCHEMA_TABLE, sqlite3_exec(), sqlite3_free(), sqlite3_mutex_held, sqlite3AnalysisLoad(), sqlite3BtreeCloseCursor(), sqlite3BtreeCursor(), sqlite3BtreeCursorSize(), sqlite3BtreeEnter, sqlite3BtreeGetMeta(), sqlite3BtreeLeave, sqlite3BtreeSetCacheSize(), sqlite3DbFree(), sqlite3ErrStr(), sqlite3FindCollSeq(), sqlite3FindTable(), sqlite3InitCallback(), sqlite3MallocZero(), sqlite3MPrintf(), sqlite3ResetInternalSchema(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3SetString(), SQLITE_DEFAULT_CACHE_SIZE, SQLITE_EMPTY, SQLITE_ERROR, SQLITE_IOERR_NOMEM, SQLITE_LegacyFileFmt, SQLITE_MAX_FILE_FORMAT, SQLITE_NOMEM, SQLITE_OK, SQLITE_RecoveryMode, SQLITE_UTF8, Table::tabFlags, TF_Readonly, sqlite3::xAuth, and Db::zName.
Referenced by sqlite3Init().
static int sqlite3LockAndPrepare (sqlite3 * db, const char * zSql, int nBytes, int saveSqlFlag, sqlite3_stmt ** ppStmt, const char ** pzTail) [static]
Definition at line 646 of file prepare.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3BtreeEnterAll, sqlite3BtreeLeaveAll, sqlite3Prepare(), sqlite3SafetyCheckOk(), and SQLITE_MISUSE.
Referenced by sqlite3_prepare(), sqlite3_prepare_v2(), sqlite3Prepare16(), and sqlite3Reprepare().
static int sqlite3Prepare (sqlite3 * db, const char * zSql, int nBytes, int saveSqlFlag, sqlite3_stmt ** ppStmt, const char ** pzTail) [static]
Definition at line 522 of file prepare.c.
References sqlite3::aDb, sqlite3::aLimit, Parse::checkSchema, COLNAME_NAME, Parse::db, sqlite3::errMask, Parse::explain, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::nDb, Db::pBt, Parse::pVdbe, Parse::rc, schemaIsValid(), sqlite3_finalize(), sqlite3_mutex_held, sqlite3ApiExit(), sqlite3BtreeSchemaLocked(), sqlite3DbFree(), sqlite3DbStrNDup(), sqlite3Error(), sqlite3ResetInternalSchema(), sqlite3RunParser(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3VdbeSetSql(), SQLITE_DONE, SQLITE_LIMIT_SQL_LENGTH, SQLITE_LOCKED, SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_OK, SQLITE_SCHEMA, SQLITE_STATIC, SQLITE_TOOBIG, Db::zName, and Parse::zTail.
Referenced by sqlite3LockAndPrepare().
static int sqlite3Prepare16 (sqlite3 * db, const void * zSql, int nBytes, int saveSqlFlag, sqlite3_stmt ** ppStmt, const void ** pzTail) [static]
Definition at line 738 of file prepare.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3DbFree(), sqlite3LockAndPrepare(), sqlite3SafetyCheckOk(), sqlite3Utf16ByteLen(), sqlite3Utf16to8(), sqlite3Utf8CharLen(), SQLITE_MISUSE, and SQLITE_OK.
Referenced by sqlite3_prepare16(), and sqlite3_prepare16_v2().
int sqlite3ReadSchema (Parse * pParse)
Definition at line 432 of file prepare.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::init, sqlite3::mutex, Parse::nErr, Parse::rc, sqlite3_mutex_held, sqlite3Init(), SQLITE_OK, and Parse::zErrMsg.
Referenced by sqlite3Analyze(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTrigger(), sqlite3LocateTable(), sqlite3Pragma(), sqlite3Reindex(), and sqlite3StartTable().
int sqlite3Reprepare (Vdbe * p)
Definition at line 671 of file prepare.c.
References db, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_held, sqlite3_sql(), sqlite3LockAndPrepare(), sqlite3TransferBindings(), sqlite3VdbeDb(), sqlite3VdbeFinalize(), sqlite3VdbeResetStepResult(), sqlite3VdbeSwap(), and SQLITE_NOMEM.
int sqlite3SchemaToIndex (sqlite3 * db, Schema * pSchema)
Definition at line 494 of file prepare.c.
References sqlite3::aDb, sqlite3::mutex, sqlite3::nDb, Db::pSchema, and sqlite3_mutex_held.
Referenced by analyzeOneTable(), analyzeTable(), columnType(), destroyTable(), lookupName(), reindexTable(), reloadTableSchema(), sqlite3_blob_open(), sqlite3AlterBeginAddColumn(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AuthRead(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3FindInIndex(), sqlite3FinishTrigger(), sqlite3Insert(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Update(), sqlite3VtabBeginParse(), sqlite3VtabFinishParse(), sqlite3WhereBegin(), targetSrcList(), and xferOptimization().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1