ContextLogger2 Logger Daemon Internals: printf.c File Reference
printf.c File Reference
Classes
struct et_info
Defines
#define etRADIX 1
#define etFLOAT 2
#define etEXP 3
#define etGENERIC 4
#define etSIZE 5
#define etSTRING 6
#define etDYNSTRING 7
#define etPERCENT 8
#define etCHARX 9
#define etSQLESCAPE 10
#define etSQLESCAPE2 11
#define etTOKEN 12
#define etSRCLIST 13
#define etPOINTER 14
#define etSQLESCAPE3 15
#define etORDINAL 16
#define FLAG_SIGNED 1
#define FLAG_INTERN 2
#define FLAG_STRING 4
#define etNINFO (sizeof(fmtinfo)/sizeof(fmtinfo[0]))
#define SQLITE_PRINT_BUF_SIZE 350
#define etBUFSIZE SQLITE_PRINT_BUF_SIZE
Typedefs
typedef unsigned char etByte
Functions
static int et_getdigit (LONGDOUBLE_TYPE *val, int *cnt)
static void appendSpace (StrAccum *pAccum, int N)
void sqlite3VXPrintf (StrAccum *pAccum, int useExtended, const char *fmt, va_list ap)
void sqlite3StrAccumAppend (StrAccum *p, const char *z, int N)
char * sqlite3StrAccumFinish (StrAccum *p)
void sqlite3StrAccumReset (StrAccum *p)
void sqlite3StrAccumInit (StrAccum *p, char *zBase, int n, int mx)
char * sqlite3VMPrintf (sqlite3 *db, const char *zFormat, va_list ap)
char * sqlite3MPrintf (sqlite3 *db, const char *zFormat,...)
char * sqlite3MAppendf (sqlite3 *db, char *zStr, const char *zFormat,...)
char * sqlite3_vmprintf (const char *zFormat, va_list ap)
char * sqlite3_mprintf (const char *zFormat,...)
char * sqlite3_snprintf (int n, char *zBuf, const char *zFormat,...)
Variables
static const char aDigits [] = "0123456789ABCDEF0123456789abcdef"
static const char aPrefix [] = "-x0\000X0"
static const et_info fmtinfo []
Define Documentation
#define etBUFSIZE SQLITE_PRINT_BUF_SIZE
Definition at line 194 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etCHARX 9
Definition at line 69 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etDYNSTRING 7
Definition at line 67 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etEXP 3
Definition at line 63 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etFLOAT 2
Definition at line 62 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etGENERIC 4
Definition at line 64 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etNINFO (sizeof(fmtinfo)/sizeof(fmtinfo[0]))
Definition at line 140 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etORDINAL 16
Definition at line 78 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etPERCENT 8
Definition at line 68 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etPOINTER 14
Definition at line 76 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etRADIX 1
Definition at line 61 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etSIZE 5
Definition at line 65 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etSQLESCAPE 10
Definition at line 71 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etSQLESCAPE2 11
Definition at line 72 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etSQLESCAPE3 15
Definition at line 77 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etSRCLIST 13
Definition at line 75 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etSTRING 6
Definition at line 66 of file printf.c.
Referenced by sqlite3VXPrintf().
#define etTOKEN 12
Definition at line 74 of file printf.c.
Referenced by sqlite3VXPrintf().
#define FLAG_INTERN 2
Definition at line 103 of file printf.c.
Referenced by sqlite3VXPrintf().
#define FLAG_SIGNED 1
Definition at line 102 of file printf.c.
Referenced by sqlite3VXPrintf().
#define FLAG_STRING 4
Definition at line 104 of file printf.c.
Referenced by sqlite3VXPrintf().
#define SQLITE_PRINT_BUF_SIZE 350
Definition at line 192 of file printf.c.
Referenced by sqlite3_vmprintf(), and sqlite3VMPrintf().
Typedef Documentation
typedef unsigned char etByte
Definition at line 84 of file printf.c.
Function Documentation
static void appendSpace (StrAccum * pAccum, int N) [static]
Definition at line 175 of file printf.c.
References sqlite3StrAccumAppend().
Referenced by sqlite3VXPrintf().
static int et_getdigit (LONGDOUBLE_TYPE * val, int * cnt) [static]
Definition at line 160 of file printf.c.
References d(), and LONGDOUBLE_TYPE.
Referenced by sqlite3VXPrintf().
char* sqlite3_mprintf (const char * zFormat, ...)
Definition at line 878 of file printf.c.
References sqlite3_initialize(), and sqlite3_vmprintf().
Referenced by constructVtab(), DbMain(), DbObjCmd(), do_meta_command(), dump_callback(), fulltextFilter(), fulltextRename(), fulltextSchema(), parseSpec(), scalarFunc(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3Fts2InitHashTable(), sqlite3Fts3InitHashTable(), and sqlite3LoadExtension().
char* sqlite3_snprintf (int n, char * zBuf, const char * zFormat, ...)
Definition at line 896 of file printf.c.
References sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), and StrAccum::useMalloc.
Referenced by attachFunc(), checkTreePage(), createIncrblobChannel(), createTableStmt(), dateFunc(), datetimeFunc(), DbBusyHandler(), DbObjCmd(), DbProfileHandler(), detachFunc(), displayP4(), do_meta_command(), fillInUnixFile(), find_home_dir(), getTempname(), icuFunctionError(), main(), main_init(), openDirectory(), optimizeFunc(), process_input(), process_sqliterc(), roundFunc(), run_schema_dump_query(), snippetOffsetText(), sqlite3_blob_open(), sqlite3CreateIndex(), sqlite3GenerateConstraintChecks(), sqlite3LoadExtension(), sqlite3VdbeList(), sqlite3VdbeMemStringify(), strftimeFunc(), timeFunc(), unixDlError(), and unixFullPathname().
char* sqlite3_vmprintf (const char * zFormat, va_list ap)
Definition at line 861 of file printf.c.
References sqlite3_initialize(), sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), SQLITE_MAX_LENGTH, and SQLITE_PRINT_BUF_SIZE.
Referenced by sqlite3_mprintf().
char* sqlite3MAppendf (sqlite3 * db, char * zStr, const char * zFormat, ...)
Definition at line 847 of file printf.c.
References sqlite3DbFree(), and sqlite3VMPrintf().
Referenced by corruptSchema(), and sqlite3WhereBegin().
char* sqlite3MPrintf (sqlite3 * db, const char * zFormat, ...)
Definition at line 830 of file printf.c.
References sqlite3VMPrintf().
Referenced by generateColumnNames(), reloadTableSchema(), renameTableFunc(), renameTriggerFunc(), selectColumnsFromExprList(), selectExpander(), setQuotedToken(), sqlite3AnalysisLoad(), sqlite3CodeRowTrigger(), sqlite3CreateIndex(), sqlite3EndTable(), sqlite3FinishTrigger(), sqlite3GenerateConstraintChecks(), sqlite3InitOne(), sqlite3InvalidFunction(), sqlite3Pragma(), sqlite3RunParser(), sqlite3VdbeExec(), sqlite3VtabCallCreate(), sqlite3VtabFinishParse(), sqlite3WhereBegin(), vdbeCommit(), vtabCallConstructor(), and whereTempTriggers().
void sqlite3StrAccumAppend (StrAccum * p, const char * z, int N)
Definition at line 719 of file printf.c.
References StrAccum::db, StrAccum::mallocFailed, StrAccum::mxAlloc, StrAccum::nAlloc, StrAccum::nChar, sqlite3DbMallocRaw(), sqlite3StrAccumReset(), StrAccum::tooBig, StrAccum::useMalloc, and StrAccum::zText.
Referenced by appendSpace(), checkAppendMsg(), groupConcatStep(), and sqlite3VXPrintf().
char* sqlite3StrAccumFinish (StrAccum * p)
Definition at line 768 of file printf.c.
References StrAccum::db, StrAccum::mallocFailed, StrAccum::nChar, sqlite3DbMallocRaw(), StrAccum::useMalloc, StrAccum::zBase, and StrAccum::zText.
Referenced by groupConcatFinalize(), sqlite3_snprintf(), sqlite3_vmprintf(), sqlite3BtreeIntegrityCheck(), and sqlite3VMPrintf().
void sqlite3StrAccumInit (StrAccum * p, char * zBase, int n, int mx)
Definition at line 796 of file printf.c.
References StrAccum::db, StrAccum::mallocFailed, StrAccum::mxAlloc, StrAccum::nAlloc, StrAccum::nChar, StrAccum::tooBig, StrAccum::useMalloc, StrAccum::zBase, and StrAccum::zText.
Referenced by sqlite3_snprintf(), sqlite3_vmprintf(), sqlite3BtreeIntegrityCheck(), and sqlite3VMPrintf().
void sqlite3StrAccumReset (StrAccum * p)
Definition at line 786 of file printf.c.
References StrAccum::db, sqlite3DbFree(), StrAccum::zBase, and StrAccum::zText.
Referenced by sqlite3BtreeIntegrityCheck(), and sqlite3StrAccumAppend().
char* sqlite3VMPrintf (sqlite3 * db, const char * zFormat, va_list ap)
Definition at line 811 of file printf.c.
References sqlite3::aLimit, StrAccum::db, sqlite3::mallocFailed, StrAccum::mallocFailed, sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), SQLITE_LIMIT_LENGTH, SQLITE_MAX_LENGTH, and SQLITE_PRINT_BUF_SIZE.
Referenced by sqlite3Error(), sqlite3ErrorMsg(), sqlite3MAppendf(), sqlite3MPrintf(), sqlite3NestedParse(), and sqlite3SetString().
void sqlite3VXPrintf (StrAccum * pAccum, int useExtended, const char * fmt, va_list ap)
Definition at line 223 of file printf.c.
References SrcList::a, aDigits, appendSpace(), aPrefix, et_info::base, et_info::charset, et_getdigit(), etBUFSIZE, etCHARX, etDYNSTRING, etEXP, etFLOAT, etGENERIC, etNINFO, etORDINAL, etPERCENT, etPOINTER, etRADIX, etSIZE, etSQLESCAPE, etSQLESCAPE2, etSQLESCAPE3, etSRCLIST, etSTRING, etTOKEN, FLAG_INTERN, FLAG_SIGNED, FLAG_STRING, et_info::flags, LONGDOUBLE_TYPE, Token::n, StrAccum::nChar, et_info::prefix, sqlite3_free(), sqlite3IsNaN(), sqlite3Malloc(), sqlite3StrAccumAppend(), et_info::type, and Token::z.
Referenced by checkAppendMsg(), sqlite3_snprintf(), sqlite3_vmprintf(), and sqlite3VMPrintf().
Variable Documentation
const char aDigits[] = "0123456789ABCDEF0123456789abcdef" [static]
Definition at line 111 of file printf.c.
Referenced by sqlite3VXPrintf().
const char aPrefix[] = "-x0\000X0" [static]
Definition at line 112 of file printf.c.
Referenced by sqlite3VXPrintf().
const et_info fmtinfo[] [static]
Initial value:
 {
  {  'd', 10, 1, etRADIX,      0,  0 },
  {  's',  0, 4, etSTRING,     0,  0 },
  {  'g',  0, 1, etGENERIC,    30, 0 },
  {  'z',  0, 4, etDYNSTRING,  0,  0 },
  {  'q',  0, 4, etSQLESCAPE,  0,  0 },
  {  'Q',  0, 4, etSQLESCAPE2, 0,  0 },
  {  'w',  0, 4, etSQLESCAPE3, 0,  0 },
  {  'c',  0, 0, etCHARX,      0,  0 },
  {  'o',  8, 0, etRADIX,      0,  2 },
  {  'u', 10, 0, etRADIX,      0,  0 },
  {  'x', 16, 0, etRADIX,      16, 1 },
  {  'X', 16, 0, etRADIX,      0,  4 },
  {  'f',  0, 1, etFLOAT,      0,  0 },
  {  'e',  0, 1, etEXP,        30, 0 },
  {  'E',  0, 1, etEXP,        14, 0 },
  {  'G',  0, 1, etGENERIC,    14, 0 },
  {  'i', 10, 1, etRADIX,      0,  0 },
  {  'n',  0, 0, etSIZE,       0,  0 },
  {  '%',  0, 0, etPERCENT,    0,  0 },
  {  'p', 16, 0, etPOINTER,    0,  1 },
  {  'T',  0, 2, etTOKEN,      0,  0 },
  {  'S',  0, 2, etSRCLIST,    0,  0 },
  {  'r', 10, 3, etORDINAL,    0,  0 },
}
Definition at line 113 of file printf.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1