ContextLogger2 Logger Daemon Internals: random.c File Reference
random.c File Reference
Classes
struct sqlite3PrngType
Defines
#define wsdPrng sqlite3Prng
Functions
static int randomByte (void)
void sqlite3_randomness (int N, void *pBuf)
void sqlite3PrngSaveState (void)
void sqlite3PrngRestoreState (void)
void sqlite3PrngResetState (void)
Variables
static SQLITE_WSD struct
sqlite3PrngType sqlite3Prng
static SQLITE_WSD struct
sqlite3PrngType sqlite3SavedPrng = { 0, }
Define Documentation
#define wsdPrng sqlite3Prng
Referenced by randomByte().
Function Documentation
static int randomByte (void) [static]
Definition at line 48 of file random.c.
References GLOBAL, sqlite3PrngType::i, sqlite3_vfs_find(), sqlite3OsRandomness(), sqlite3Prng, and wsdPrng.
Referenced by sqlite3_randomness().
void sqlite3_randomness (int N, void * pBuf)
Definition at line 107 of file random.c.
References randomByte(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, and SQLITE_MUTEX_STATIC_PRNG.
Referenced by getTempname(), randomBlob(), randomFunc(), sqlite3BitvecBuiltinTest(), sqlite3VdbeExec(), vdbeCommit(), and writeJournalHdr().
void sqlite3PrngResetState (void)
Definition at line 144 of file random.c.
References GLOBAL, and sqlite3Prng.
Referenced by sqlite3_test_control().
void sqlite3PrngRestoreState (void)
Definition at line 137 of file random.c.
References GLOBAL, and sqlite3Prng.
Referenced by sqlite3_test_control().
void sqlite3PrngSaveState (void)
Definition at line 130 of file random.c.
References GLOBAL, and sqlite3Prng.
Referenced by sqlite3_test_control().
Variable Documentation
SQLITE_WSD struct sqlite3PrngType sqlite3Prng [static]
Referenced by randomByte(), sqlite3PrngResetState(), sqlite3PrngRestoreState(), and sqlite3PrngSaveState().
SQLITE_WSD struct sqlite3PrngType sqlite3SavedPrng = { 0, } [static]
Definition at line 129 of file random.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1