ContextLogger2 Logger Daemon Internals: rk_remokon_qt.cpp File Reference
rk_remokon_qt.cpp File Reference
Classes
class LuaStack
Defines
#define TRAPFATAL(_stm)
#define GTRAP(_ret, _stm)
#define TOCSTR(exp) ((exp).toUtf8().data())
#define no_config_error
Functions
static lua_State * new_my_lua ()
static int SecsToMsecs (int secs)
rk_Remokon * rk_Remokon_new (GError **error)
void rk_Remokon_destroy (rk_Remokon *self)
gboolean rk_Remokon_is_autostart_enabled (rk_Remokon *self)
gboolean rk_Remokon_start (rk_Remokon *self, GError **error)
void rk_Remokon_stop (rk_Remokon *self)
gboolean rk_Remokon_start_timed (rk_Remokon *self, int secs, GError **error)
gboolean rk_Remokon_reconfigure (rk_Remokon *self, const gchar *key, const gchar *value, GError **error)
gboolean rk_Remokon_is_started (rk_Remokon *self)
gboolean rk_Remokon_is_connected (rk_Remokon *self)
gboolean rk_Remokon_send (rk_Remokon *self, const char *toJid, const char *msgText, GError **error)
Define Documentation
#define GTRAP (_ret, _stm)
Value:
{         \
    try {             \
      _stm ;              \
    } catch (const std::exception &ex) {      \
      if (error)            \
  *error = gx_error_new(domain_qt, -1,      \
            "remokon: %s", ex.what());  \
      return _ret;            \
    }               \
  }
Definition at line 28 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_new(), rk_Remokon_send(), rk_Remokon_start(), and rk_Remokon_start_timed().
#define no_config_error
Value:
gx_error_new(domain_cl2app, code_no_configuration, \
         "some Jabber config missing")
Definition at line 319 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_start(), and rk_Remokon_start_timed().
#define TOCSTR (exp) ((exp).toUtf8().data())
Definition at line 228 of file rk_remokon_qt.cpp.
Referenced by _rk_Remokon::gotJabberMessage().
#define TRAPFATAL (_stm)
Value:
{         \
    try {             \
      _stm ;              \
    } catch (const std::exception &ex) {      \
      er_log_none(er_FATAL, "remokon: %s", ex.what());    \
    }               \
  }
Definition at line 20 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_stop(), and _rk_Remokon::runTimeout().
Function Documentation
static lua_State* new_my_lua () [static]
Definition at line 43 of file rk_remokon_qt.cpp.
References cl_lua_new_libs(), and _rk_Remokon::L.
void rk_Remokon_destroy (rk_Remokon * self)
Definition at line 307 of file rk_remokon_qt.cpp.
Referenced by kr_Controller_destroy().
gboolean rk_Remokon_is_autostart_enabled (rk_Remokon * self)
Definition at line 313 of file rk_remokon_qt.cpp.
Referenced by kr_Controller_start().
gboolean rk_Remokon_is_connected (rk_Remokon * self)
Definition at line 393 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_send().
gboolean rk_Remokon_is_started (rk_Remokon * self)
Definition at line 387 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_start().
rk_Remokon* rk_Remokon_new (GError ** error)
Definition at line 294 of file rk_remokon_qt.cpp.
References GTRAP.
Referenced by kr_Controller_new().
gboolean rk_Remokon_reconfigure (rk_Remokon * self, const gchar * key, const gchar * value, GError ** error)
Definition at line 365 of file rk_remokon_qt.cpp.
References force_lua_eval_bool(), and force_lua_eval_int().
Referenced by kr_Controller_reconfigure().
gboolean rk_Remokon_send (rk_Remokon * self, const char * toJid, const char * msgText, GError ** error)
Definition at line 399 of file rk_remokon_qt.cpp.
References code_not_connected, domain_cl2app, GTRAP, gx_error_new(), and rk_Remokon_is_connected().
gboolean rk_Remokon_start (rk_Remokon * self, GError ** error)
Definition at line 325 of file rk_remokon_qt.cpp.
References GTRAP, no_config_error, and rk_Remokon_is_started().
Referenced by f_remokon_start(), and kr_Controller_start().
gboolean rk_Remokon_start_timed (rk_Remokon * self, int secs, GError ** error)
Definition at line 349 of file rk_remokon_qt.cpp.
References GTRAP, and no_config_error.
Referenced by f_remokon_timed(), MainWindow::remokonNow(), and CSmsTrigger::RunL().
void rk_Remokon_stop (rk_Remokon * self)
Definition at line 343 of file rk_remokon_qt.cpp.
References TRAPFATAL.
Referenced by f_remokon_stop(), and kr_Controller_stop().
static int SecsToMsecs (int secs) [static]
Definition at line 137 of file rk_remokon_qt.cpp.
Referenced by _rk_Remokon::resetRunTimer().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1