ContextLogger2 Logger Daemon Internals: rk_remokon.h File Reference
rk_remokon.h File Reference
Defines
#define ac_global_Remokon ac_get_Remokon(ac_get_global_AppContext())
Typedefs
typedef struct _rk_Remokon rk_Remokon
Functions
rk_Remokon * rk_Remokon_new (GError **error)
void rk_Remokon_destroy (rk_Remokon *self)
gboolean rk_Remokon_start (rk_Remokon *self, GError **error)
void rk_Remokon_stop (rk_Remokon *self)
gboolean rk_Remokon_start_timed (rk_Remokon *self, int secs, GError **error)
gboolean rk_Remokon_reconfigure (rk_Remokon *object, const gchar *key, const gchar *value, GError **error)
gboolean rk_Remokon_is_started (rk_Remokon *self)
gboolean rk_Remokon_is_autostart_enabled (rk_Remokon *self)
gboolean rk_Remokon_is_connected (rk_Remokon *self)
gboolean rk_Remokon_send (rk_Remokon *self, const char *toJid, const char *msgText, GError **error)
rk_Remokon * ac_get_Remokon (ac_AppContext *self)
Define Documentation
#define ac_global_Remokon ac_get_Remokon(ac_get_global_AppContext())
Definition at line 62 of file rk_remokon.h.
Referenced by MainWindow::remokonNow().
Typedef Documentation
typedef struct _rk_Remokon rk_Remokon
Definition at line 14 of file rk_remokon.h.
Function Documentation
rk_Remokon* ac_get_Remokon (ac_AppContext * self)
Definition at line 187 of file ac_app_context.cpp.
Referenced by CSmsTrigger::RunL().
void rk_Remokon_destroy (rk_Remokon * self)
Definition at line 307 of file rk_remokon_qt.cpp.
Referenced by kr_Controller_destroy().
gboolean rk_Remokon_is_autostart_enabled (rk_Remokon * self)
Definition at line 313 of file rk_remokon_qt.cpp.
Referenced by kr_Controller_start().
gboolean rk_Remokon_is_connected (rk_Remokon * self)
Definition at line 393 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_send().
gboolean rk_Remokon_is_started (rk_Remokon * self)
Definition at line 387 of file rk_remokon_qt.cpp.
Referenced by rk_Remokon_start().
rk_Remokon* rk_Remokon_new (GError ** error)
Definition at line 294 of file rk_remokon_qt.cpp.
References GTRAP.
Referenced by kr_Controller_new().
gboolean rk_Remokon_reconfigure (rk_Remokon * object, const gchar * key, const gchar * value, GError ** error)
Definition at line 365 of file rk_remokon_qt.cpp.
References force_lua_eval_bool(), and force_lua_eval_int().
Referenced by kr_Controller_reconfigure().
gboolean rk_Remokon_send (rk_Remokon * self, const char * toJid, const char * msgText, GError ** error)
Definition at line 399 of file rk_remokon_qt.cpp.
References code_not_connected, domain_cl2app, GTRAP, gx_error_new(), and rk_Remokon_is_connected().
gboolean rk_Remokon_start (rk_Remokon * self, GError ** error)
Definition at line 325 of file rk_remokon_qt.cpp.
References GTRAP, no_config_error, and rk_Remokon_is_started().
Referenced by f_remokon_start(), and kr_Controller_start().
gboolean rk_Remokon_start_timed (rk_Remokon * self, int secs, GError ** error)
Definition at line 349 of file rk_remokon_qt.cpp.
References GTRAP, and no_config_error.
Referenced by f_remokon_timed(), MainWindow::remokonNow(), and CSmsTrigger::RunL().
void rk_Remokon_stop (rk_Remokon * self)
Definition at line 343 of file rk_remokon_qt.cpp.
References TRAPFATAL.
Referenced by f_remokon_stop(), and kr_Controller_stop().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1