ContextLogger2 Logger Daemon Internals: sa_array.h File Reference
sa_array.h File Reference
Typedefs
typedef struct _sa_Array sa_Array
Functions
sa_Array * sa_Array_new (ac_AppContext *ac, GError **error)
void sa_Array_start (sa_Array *self)
void sa_Array_stop (sa_Array *self)
void sa_Array_destroy (sa_Array *self)
gboolean sa_sensor_is_supported (const gchar *name)
gboolean sa_Array_sensor_is_running (sa_Array *self, const gchar *name)
void sa_Array_sensor_stop (sa_Array *self, const gchar *name)
gboolean sa_Array_sensor_start (sa_Array *self, const gchar *name, GError **error)
gboolean sa_Array_reconfigure (sa_Array *self, const gchar *key, const gchar *value, GError **error)
Typedef Documentation
typedef struct _sa_Array sa_Array
Definition at line 12 of file sa_array.h.
Function Documentation
void sa_Array_destroy (sa_Array * self)
Destroys a sensor array. Naturally all the sensors in it are stopped.
Definition at line 307 of file sa_array.cpp.
References DESTROY_ALL_SENSORS, and logt.
Referenced by kr_Controller_destroy(), and sa_Array_new().
sa_Array* sa_Array_new (ac_AppContext * ac, GError ** error)
Instantiates a sensor array consisting of all supported sensors. Does not yet start the sensors.
Instantiates a sensor array consisting of all supported sensors.
Definition at line 263 of file sa_array.cpp.
References ac_LogDb(), CREATE_ALL_SENSORS_OR_FAIL, gx_error_no_memory, logt, and sa_Array_destroy().
Referenced by kr_Controller_new().
gboolean sa_Array_reconfigure (sa_Array * self, const gchar * key, const gchar * value, GError ** error)
Definition at line 359 of file sa_array.cpp.
References RECONFIGURE_MATCHING_SENSOR.
Referenced by kr_Controller_reconfigure().
gboolean sa_Array_sensor_is_running (sa_Array * self, const gchar * name)
Definition at line 327 of file sa_array.cpp.
References RETURN_WHETHER_NAMED_SENSOR_IS_RUNNING.
Referenced by f_is_sensor_running().
gboolean sa_Array_sensor_start (sa_Array * self, const gchar * name, GError ** error)
Definition at line 346 of file sa_array.cpp.
References code_not_supported, domain_cl2app, gx_error_new(), and START_NAMED_SENSOR_OR_FAIL.
Referenced by f_sensor_start().
void sa_Array_sensor_stop (sa_Array * self, const gchar * name)
Definition at line 337 of file sa_array.cpp.
References STOP_NAMED_SENSOR.
Referenced by f_sensor_stop().
void sa_Array_start (sa_Array * self)
Starts all supported sensors.
Definition at line 290 of file sa_array.cpp.
References error(), and TRY_START_ALL_SUPPORTED_SENSORS.
Referenced by kr_Controller_start().
void sa_Array_stop (sa_Array * self)
Stops all supported sensors.
Definition at line 301 of file sa_array.cpp.
References STOP_ALL_SUPPORTED_SENSORS.
Referenced by kr_Controller_stop().
gboolean sa_sensor_is_supported (const gchar * name)
Returns FALSE for unknown names.
Definition at line 321 of file sa_array.cpp.
References RETURN_WHETHER_NAMED_SENSOR_IS_SUPPORTED.
Referenced by f_is_sensor_supported().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1