ContextLogger2 Logger Daemon Internals: sa_sensor_list_log_db.h File Reference
sa_sensor_list_log_db.h File Reference
Classes
struct _PreparedStmts
Typedefs
typedef struct _PreparedStmts PreparedStmts
Functions
G_BEGIN_DECLS char const * get_create_tables_sql ()
gboolean prepare_sql_statements (LogDb *self, GError **error)
void destroy_sql_statements (LogDb *self)
gboolean log_db_log_mark (LogDb *self, char const *msgText, GError **error)
gboolean log_db_log_appmessage (LogDb *self, char const *msgText, GError **error)
gboolean log_db_log_light (LogDb *self, int level, GError **error)
gboolean log_db_log_tap (LogDb *self, int direction, gboolean isDouble, GError **error)
gboolean log_db_log_proximity (LogDb *self, gboolean isClose, GError **error)
gboolean log_db_log_musicplayer (LogDb *self, int eventId, char const *detail, GError **error)
gboolean log_db_log_musictrack (LogDb *self, char const *url, char const *title, char const *artist, char const *album, GError **error)
gboolean log_db_log_httpurl (LogDb *self, char const *url, GError **error)
gboolean log_db_log_profile (LogDb *self, int profileId, char const *profileName, GError **error)
gboolean log_db_log_cellid (LogDb *self, char const *countryCode, char const *networkCode, int areaCode, int cellId, GError **error)
gboolean log_db_log_position (LogDb *self, double latitude, double longitude, double altitude, double verticalAccuracy, double horizontalAccuracy, char const *course, char const *satellites, GError **error)
gboolean log_db_log_appfocus (LogDb *self, sqlite3_int64 appUid, char const *appCaption, GError **error)
gboolean log_db_log_keypress (LogDb *self, char const *aPressTimes, GError **error)
gboolean log_db_log_inactivity (LogDb *self, gboolean value, GError **error)
gboolean log_db_log_indicator (LogDb *self, guint32 value, guint32 caps, GError **error)
gboolean log_db_log_callstatus (LogDb *self, int value, char const *aNumber, char const *aContactName, int aStartTime, int aOsTerm, int aNetTerm, GError **error)
gboolean log_db_log_smsevent (LogDb *self, char const *aEvType, char const *aNumber, char const *aContactName, char const *aBodyText, GError **error)
Typedef Documentation
typedef struct _PreparedStmts PreparedStmts
Definition at line 110 of file sa_sensor_list_log_db.h.
Function Documentation
void destroy_sql_statements (LogDb * self)
Definition at line 240 of file sa_sensor_list_log_db.c.
References sqlite3_finalize().
G_BEGIN_DECLS char const* get_create_tables_sql ()
Definition at line 145 of file sa_sensor_list_log_db.c.
References create_tables_sql.
Referenced by create_log_db().
gboolean log_db_log_appfocus (LogDb * self, sqlite3_int64 appUid, char const * appCaption, GError ** error)
Definition at line 634 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_int64(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_appfocus::RunGL().
gboolean log_db_log_appmessage (LogDb * self, char const * msgText, GError ** error)
Definition at line 345 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by f_log_message().
gboolean log_db_log_callstatus (LogDb * self, int value, char const * aNumber, char const * aContactName, int aStartTime, int aOsTerm, int aNetTerm, GError ** error)
Definition at line 700 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_int_ltez, sqlite3_bind_int_neqz, sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_callstatus::ChangedData_CallStatus().
gboolean log_db_log_cellid (LogDb * self, char const * countryCode, char const * networkCode, int areaCode, int cellId, GError ** error)
Definition at line 593 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_cellid::PostNewDataL().
gboolean log_db_log_httpurl (LogDb * self, char const * url, GError ** error)
Definition at line 543 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_httpurl::RunL().
gboolean log_db_log_inactivity (LogDb * self, gboolean value, GError ** error)
Definition at line 667 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by CSensor_inactivity::RunL().
gboolean log_db_log_indicator (LogDb * self, guint32 value, guint32 caps, GError ** error)
Definition at line 683 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by CSensor_indicator::HandleRead().
gboolean log_db_log_keypress (LogDb * self, char const * aPressTimes, GError ** error)
Definition at line 651 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_keypress::LogAndClear().
gboolean log_db_log_light (LogDb * self, int level, GError ** error)
Definition at line 458 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by Sensor_light::handleReadingChanged().
gboolean log_db_log_mark (LogDb * self, char const * msgText, GError ** error)
Definition at line 329 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by sa_Sensor_mark_start(), sa_Sensor_mark_stop(), and timerCallback().
gboolean log_db_log_musicplayer (LogDb * self, int eventId, char const * detail, GError ** error)
Definition at line 507 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_music::HandlePlaybackMessage().
gboolean log_db_log_musictrack (LogDb * self, char const * url, char const * title, char const * artist, char const * album, GError ** error)
Definition at line 524 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_music::HandleMediaL().
gboolean log_db_log_position (LogDb * self, double latitude, double longitude, double altitude, double verticalAccuracy, double horizontalAccuracy, char const * course, char const * satellites, GError ** error)
Definition at line 612 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by LogSatelliteInfoL().
gboolean log_db_log_profile (LogDb * self, int profileId, char const * profileName, GError ** error)
Definition at line 576 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_profile::HandleProfileActivatedL().
gboolean log_db_log_proximity (LogDb * self, gboolean isClose, GError ** error)
Definition at line 491 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by Sensor_proximity::handleReadingChanged().
gboolean log_db_log_smsevent (LogDb * self, char const * aEvType, char const * aNumber, char const * aContactName, char const * aBodyText, GError ** error)
Definition at line 721 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_smsevent::LogEvent().
gboolean log_db_log_tap (LogDb * self, int direction, gboolean isDouble, GError ** error)
Definition at line 474 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by Sensor_tap::handleReadingChanged().
gboolean prepare_sql_statements (LogDb * self, GError ** error)
Definition at line 150 of file sa_sensor_list_log_db.c.
References code_database_state_init, domain_cl2app, gx_error_new(), LOGDB_FILE, sqlite3_errcode(), sqlite3_errmsg(), and sqlite_prepare.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1