ContextLogger2 Logger Daemon Internals: sa_sensor_list_log_db.c File Reference
sa_sensor_list_log_db.c File Reference
Functions
char const * get_create_tables_sql ()
gboolean prepare_sql_statements (LogDb *self, GError **error)
void destroy_sql_statements (LogDb *self)
gboolean log_db_log_mark (LogDb *self, char const *msgText, GError **error)
gboolean log_db_log_appmessage (LogDb *self, char const *msgText, GError **error)
gboolean log_db_log_light (LogDb *self, int level, GError **error)
gboolean log_db_log_tap (LogDb *self, int direction, gboolean isDouble, GError **error)
gboolean log_db_log_proximity (LogDb *self, gboolean isClose, GError **error)
gboolean log_db_log_musicplayer (LogDb *self, int eventId, char const *detail, GError **error)
gboolean log_db_log_musictrack (LogDb *self, char const *url, char const *title, char const *artist, char const *album, GError **error)
gboolean log_db_log_httpurl (LogDb *self, char const *url, GError **error)
gboolean log_db_log_profile (LogDb *self, int profileId, char const *profileName, GError **error)
gboolean log_db_log_cellid (LogDb *self, char const *countryCode, char const *networkCode, int areaCode, int cellId, GError **error)
gboolean log_db_log_position (LogDb *self, double latitude, double longitude, double altitude, double verticalAccuracy, double horizontalAccuracy, char const *course, char const *satellites, GError **error)
gboolean log_db_log_appfocus (LogDb *self, sqlite3_int64 appUid, char const *appCaption, GError **error)
gboolean log_db_log_keypress (LogDb *self, char const *aPressTimes, GError **error)
gboolean log_db_log_inactivity (LogDb *self, gboolean value, GError **error)
gboolean log_db_log_indicator (LogDb *self, guint32 value, guint32 caps, GError **error)
gboolean log_db_log_callstatus (LogDb *self, int value, char const *aNumber, char const *aContactName, int aStartTime, int aOsTerm, int aNetTerm, GError **error)
gboolean log_db_log_smsevent (LogDb *self, char const *aEvType, char const *aNumber, char const *aContactName, char const *aBodyText, GError **error)
Variables
static const char create_tables_sql []
Function Documentation
void destroy_sql_statements (LogDb * self)
Definition at line 240 of file sa_sensor_list_log_db.c.
References sqlite3_finalize().
char const* get_create_tables_sql ()
Definition at line 145 of file sa_sensor_list_log_db.c.
References create_tables_sql.
Referenced by create_log_db().
gboolean log_db_log_appfocus (LogDb * self, sqlite3_int64 appUid, char const * appCaption, GError ** error)
Definition at line 634 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_int64(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_appfocus::RunGL().
gboolean log_db_log_appmessage (LogDb * self, char const * msgText, GError ** error)
Definition at line 345 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by f_log_message().
gboolean log_db_log_callstatus (LogDb * self, int value, char const * aNumber, char const * aContactName, int aStartTime, int aOsTerm, int aNetTerm, GError ** error)
Definition at line 700 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_int_ltez, sqlite3_bind_int_neqz, sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_callstatus::ChangedData_CallStatus().
gboolean log_db_log_cellid (LogDb * self, char const * countryCode, char const * networkCode, int areaCode, int cellId, GError ** error)
Definition at line 593 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_cellid::PostNewDataL().
gboolean log_db_log_httpurl (LogDb * self, char const * url, GError ** error)
Definition at line 543 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_httpurl::RunL().
gboolean log_db_log_inactivity (LogDb * self, gboolean value, GError ** error)
Definition at line 667 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by CSensor_inactivity::RunL().
gboolean log_db_log_indicator (LogDb * self, guint32 value, guint32 caps, GError ** error)
Definition at line 683 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by CSensor_indicator::HandleRead().
gboolean log_db_log_keypress (LogDb * self, char const * aPressTimes, GError ** error)
Definition at line 651 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_keypress::LogAndClear().
gboolean log_db_log_light (LogDb * self, int level, GError ** error)
Definition at line 458 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by Sensor_light::handleReadingChanged().
gboolean log_db_log_mark (LogDb * self, char const * msgText, GError ** error)
Definition at line 329 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by sa_Sensor_mark_start(), sa_Sensor_mark_stop(), and timerCallback().
gboolean log_db_log_musicplayer (LogDb * self, int eventId, char const * detail, GError ** error)
Definition at line 507 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_music::HandlePlaybackMessage().
gboolean log_db_log_musictrack (LogDb * self, char const * url, char const * title, char const * artist, char const * album, GError ** error)
Definition at line 524 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_music::HandleMediaL().
gboolean log_db_log_position (LogDb * self, double latitude, double longitude, double altitude, double verticalAccuracy, double horizontalAccuracy, char const * course, char const * satellites, GError ** error)
Definition at line 612 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_double(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by LogSatelliteInfoL().
gboolean log_db_log_profile (LogDb * self, int profileId, char const * profileName, GError ** error)
Definition at line 576 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_profile::HandleProfileActivatedL().
gboolean log_db_log_proximity (LogDb * self, gboolean isClose, GError ** error)
Definition at line 491 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by Sensor_proximity::handleReadingChanged().
gboolean log_db_log_smsevent (LogDb * self, char const * aEvType, char const * aNumber, char const * aContactName, char const * aBodyText, GError ** error)
Definition at line 721 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_bind_text(), sqlite3_bind_text_or_null, sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), SQLITE_DONE, and SQLITE_STATIC.
Referenced by CSensor_smsevent::LogEvent().
gboolean log_db_log_tap (LogDb * self, int direction, gboolean isDouble, GError ** error)
Definition at line 474 of file sa_sensor_list_log_db.c.
References code_database_command, code_time_query, domain_cl2app, gx_error_new(), sqlite3_bind_int(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_reset(), sqlite3_step(), and SQLITE_DONE.
Referenced by Sensor_tap::handleReadingChanged().
gboolean prepare_sql_statements (LogDb * self, GError ** error)
Definition at line 150 of file sa_sensor_list_log_db.c.
References code_database_state_init, domain_cl2app, gx_error_new(), LOGDB_FILE, sqlite3_errcode(), sqlite3_errmsg(), and sqlite_prepare.
Variable Documentation
const char create_tables_sql[] [static]
Initial value:
"create table status_log (unixtime INTEGER, message TEXT);"
"create table mark_log (unixtime INTEGER, message TEXT);"
"create table appmessage_log (unixtime INTEGER, message TEXT);"
"create table timer_scan (unixtime INTEGER);"
"create table flightmode_scan (unixtime INTEGER, value INTEGER);"
"create table battery_scan (unixtime INTEGER, status INTEGER, level INTEGER);"
"create table registration_scan (unixtime INTEGER, status INTEGER);"
"create table signal_scan (unixtime INTEGER, dbm INTEGER, bars INTEGER);"
"create table operator_scan (unixtime INTEGER, name TEXT);"
"create table light_scan (unixtime INTEGER, level INTEGER);"
"create table tap_scan (unixtime INTEGER, direction INTEGER, is_dbl INTEGER);"
"create table proximity_scan (unixtime INTEGER, close INTEGER);"
"create table musicplayer_scan (unixtime INTEGER, event INTEGER, detail TEXT);"
"create table musictrack_scan (unixtime INTEGER, url TEXT, title TEXT, artist TEXT, album TEXT);"
"create table httpurl_scan (unixtime INTEGER, url TEXT);"
"create table weburl_scan (unixtime INTEGER, name TEXT, url TEXT);"
"create table profile_scan (unixtime INTEGER, value INTEGER, name TEXT);"
"create table cellid_scan (unixtime INTEGER, country_code TEXT, network_code TEXT, area_code INTEGER, cell_id INTEGER);"
"create table btprox_scan (unixtime INTEGER, scan_id INTEGER not null primary key AUTOINCREMENT);"
"create table btprox_item (scan_id INTEGER not null, address TEXT not null, name TEXT not null);"
"create table position_scan (unixtime INTEGER, latitude REAL, longitude REAL, altitude REAL, vertical_accuracy REAL, horizontal_accuracy REAL, course TEXT, satellites TEXT);"
"create table appfocus_scan (unixtime INTEGER, uid INTEGER, caption TEXT);"
"create table keypress_scan (unixtime INTEGER, presstimes TEXT);"
"create table inactivity_scan (unixtime INTEGER, value INTEGER);"
"create table indicator_scan (unixtime INTEGER, value INTEGER, caps INTEGER);"
"create table callstatus_scan (unixtime INTEGER not null, value INTEGER not null, number TEXT, contact_name TEXT, starttime INTEGER, osterm INTEGER, netterm INTEGER);"
"create table smsevent_scan (unixtime INTEGER not null, evtype TEXT not null, number TEXT, contact_name TEXT, body TEXT);"
""
Definition at line 19 of file sa_sensor_list_log_db.c.
Referenced by get_create_tables_sql().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1