ContextLogger2 Logger Daemon Internals: sa_sensor_mark.c File Reference
sa_sensor_mark.c File Reference
Classes
struct _sa_Sensor_mark
Functions
static void timerCallback (void *userdata, GError *timerError)
static gboolean setTimer (sa_Sensor_mark *self, GError **error)
EXTERN_C sa_Sensor_mark * sa_Sensor_mark_new (LogDb *log, GError **error)
EXTERN_C void sa_Sensor_mark_destroy (sa_Sensor_mark *self)
EXTERN_C gboolean sa_Sensor_mark_start (sa_Sensor_mark *self, GError **error)
EXTERN_C void sa_Sensor_mark_stop (sa_Sensor_mark *self)
EXTERN_C gboolean sa_Sensor_mark_is_active (sa_Sensor_mark *self)
Function Documentation
EXTERN_C void sa_Sensor_mark_destroy (sa_Sensor_mark * self)
Definition at line 79 of file sa_sensor_mark.c.
References sa_Sensor_mark_stop(), and ut_Timer_destroy().
Referenced by sa_Sensor_mark_new().
EXTERN_C gboolean sa_Sensor_mark_is_active (sa_Sensor_mark * self)
Definition at line 112 of file sa_sensor_mark.c.
References ut_Timer_is_active().
Referenced by sa_Sensor_mark_start(), and sa_Sensor_mark_stop().
EXTERN_C sa_Sensor_mark* sa_Sensor_mark_new (LogDb * log, GError ** error)
Definition at line 63 of file sa_sensor_mark.c.
References gx_error_no_memory, sa_Sensor_mark_destroy(), timerCallback(), and ut_Timer_new().
EXTERN_C gboolean sa_Sensor_mark_start (sa_Sensor_mark * self, GError ** error)
Definition at line 90 of file sa_sensor_mark.c.
References log_db_log_mark(), sa_Sensor_mark_is_active(), and setTimer().
EXTERN_C void sa_Sensor_mark_stop (sa_Sensor_mark * self)
Definition at line 103 of file sa_sensor_mark.c.
References log_db_log_mark(), sa_Sensor_mark_is_active(), and ut_Timer_cancel().
Referenced by sa_Sensor_mark_destroy().
static gboolean setTimer (sa_Sensor_mark * self, GError ** error) [static]
Definition at line 27 of file sa_sensor_mark.c.
References ut_Timer_set_after().
Referenced by sa_Sensor_mark_start(), and timerCallback().
static void timerCallback (void * userdata, GError * timerError) [static]
Definition at line 34 of file sa_sensor_mark.c.
References gx_dblog_fatal_error_free(), gx_txtlog_fatal_error_free(), log_db_log_mark(), and setTimer().
Referenced by sa_Sensor_mark_new().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1