ContextLogger2 Logger Daemon Internals: sa_sensor_mark.h File Reference
sa_sensor_mark.h File Reference
Typedefs
typedef struct _sa_Sensor_mark sa_Sensor_mark
Functions
sa_Sensor_mark * sa_Sensor_mark_new (LogDb *log, GError **error)
void sa_Sensor_mark_destroy (sa_Sensor_mark *self)
gboolean sa_Sensor_mark_start (sa_Sensor_mark *self, GError **error)
void sa_Sensor_mark_stop (sa_Sensor_mark *self)
gboolean sa_Sensor_mark_is_active (sa_Sensor_mark *self)
Typedef Documentation
typedef struct _sa_Sensor_mark sa_Sensor_mark
Definition at line 16 of file sa_sensor_mark.h.
Function Documentation
void sa_Sensor_mark_destroy (sa_Sensor_mark * self)
Definition at line 79 of file sa_sensor_mark.c.
References sa_Sensor_mark_stop(), and ut_Timer_destroy().
Referenced by sa_Sensor_mark_new().
gboolean sa_Sensor_mark_is_active (sa_Sensor_mark * self)
Definition at line 112 of file sa_sensor_mark.c.
References ut_Timer_is_active().
Referenced by sa_Sensor_mark_start(), and sa_Sensor_mark_stop().
sa_Sensor_mark* sa_Sensor_mark_new (LogDb * log, GError ** error)
Definition at line 63 of file sa_sensor_mark.c.
References gx_error_no_memory, sa_Sensor_mark_destroy(), timerCallback(), and ut_Timer_new().
gboolean sa_Sensor_mark_start (sa_Sensor_mark * self, GError ** error)
Definition at line 90 of file sa_sensor_mark.c.
References log_db_log_mark(), sa_Sensor_mark_is_active(), and setTimer().
void sa_Sensor_mark_stop (sa_Sensor_mark * self)
Definition at line 103 of file sa_sensor_mark.c.
References log_db_log_mark(), sa_Sensor_mark_is_active(), and ut_Timer_cancel().
Referenced by sa_Sensor_mark_destroy().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:01 2011 by Doxygen 1.6.1