ContextLogger2 Logger Daemon Internals: epoc-time.cpp File Reference
shared/common/epoc-time.cpp File Reference
Functions
TTime UnixEpochTime ()
time_t UtcEpocTimeToUnixTime (const TTime &epocTime)
time_t LocalEpocTimeToUnixTime (const TTime &epocTime)
void UnixTimeToUtcEpocTime (TTime &epocTime, time_t unixTime)
void UnixTimeToLocalEpocTime (TTime &epocTime, time_t unixTime)
TTimeIntervalMicroSeconds32 SecsToUsecs (TInt secs)
Function Documentation
time_t LocalEpocTimeToUnixTime (const TTime & epocTime)
Definition at line 17 of file shared/common/epoc-time.cpp.
References UtcEpocTimeToUnixTime().
Referenced by CSensor_callstatus::ChangedData_CallStatus(), and LogSatelliteInfoL().
TTimeIntervalMicroSeconds32 SecsToUsecs (TInt secs)
Definition at line 37 of file shared/common/epoc-time.cpp.
Referenced by CUploader::SetPostRetryTimer(), CSensor_indicator::SetTimer(), CSensor_btprox::SetTimer(), ut_Timer_set_after(), CRetryAo::WaitInterval(), CActiveRetry::WaitInterval(), and CWatchdog::WaitWhile().
TTime UnixEpochTime ()
Definition at line 3 of file shared/common/epoc-time.cpp.
Referenced by UnixTimeToUtcEpocTime(), and UtcEpocTimeToUnixTime().
void UnixTimeToLocalEpocTime (TTime & epocTime, time_t unixTime)
Definition at line 29 of file shared/common/epoc-time.cpp.
References UnixTimeToUtcEpocTime().
Referenced by CUploader::SetSnapshotTimerL().
void UnixTimeToUtcEpocTime (TTime & epocTime, time_t unixTime)
Definition at line 24 of file shared/common/epoc-time.cpp.
References UnixEpochTime().
Referenced by CUploader::SetSnapshotTimerL(), QAbsTimer::start(), and UnixTimeToLocalEpocTime().
time_t UtcEpocTimeToUnixTime (const TTime & epocTime)
Definition at line 11 of file shared/common/epoc-time.cpp.
References UnixEpochTime().
Referenced by LocalEpocTimeToUnixTime().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:49:58 2011 by Doxygen 1.6.1