ContextLogger2 Logger Daemon Internals: sqliteInt.h File Reference
sqliteInt.h File Reference
Classes
struct BusyHandler
struct Db
struct Schema
struct Lookaside
struct LookasideSlot
struct FuncDefHash
struct sqlite3
struct sqlite3::sqlite3InitInfo
struct FuncDef
struct Module
struct Column
struct CollSeq
struct Table
struct FKey
struct FKey::sColMap
struct KeyInfo
struct UnpackedRecord
struct Index
struct Token
struct AggInfo
struct AggInfo::AggInfo_col
struct AggInfo::AggInfo_func
struct Expr
struct ExprList
struct ExprList::ExprList_item
struct IdList
struct IdList::IdList_item
struct SrcList
struct SrcList::SrcList_item
struct WhereLevel
struct WhereLevel::InLoop
struct WhereInfo
struct NameContext
struct Select
struct SelectDest
struct Parse
struct Parse::yColCache
struct AuthContext
struct Trigger
struct TriggerStep
struct TriggerStack
struct DbFixer
struct StrAccum
struct InitData
struct Sqlite3Config
struct Walker
Defines
#define testcase(X)
#define ALWAYS(X) (X)
#define NEVER(X) (X)
#define likely(X) !!(X)
#define unlikely(X) !!(X)
#define SQLITE_INT_TO_PTR(X) ((void*)&((char*)0)[X])
#define SQLITE_PTR_TO_INT(X) ((int)(((char*)X)-(char*)0))
#define SQLITE_DEFAULT_MEMSTATUS 1
#define SQLITE_SYSTEM_MALLOC 1
#define SQLITE_BIG_DBL (1e99)
#define OMIT_TEMPDB 0
#define NULL_DISTINCT_FOR_UNIQUE 1
#define SQLITE_MAX_FILE_FORMAT 4
#define SQLITE_DEFAULT_FILE_FORMAT 1
#define SQLITE_TEMP_STORE 1
#define offsetof(STRUCTURE, FIELD) ((int)((char*)&((STRUCTURE*)0)->FIELD))
#define SQLITE_ASCII 1
#define UINT32_TYPE uint32_t
#define UINT16_TYPE uint16_t
#define INT16_TYPE int16_t
#define UINT8_TYPE uint8_t
#define INT8_TYPE int8_t
#define LONGDOUBLE_TYPE long double
#define SQLITE_BIGENDIAN (*(char *)(&sqlite3one)==0)
#define SQLITE_LITTLEENDIAN (*(char *)(&sqlite3one)==1)
#define SQLITE_UTF16NATIVE (SQLITE_BIGENDIAN?SQLITE_UTF16BE:SQLITE_UTF16LE)
#define LARGEST_INT64 (0xffffffff|(((i64)0x7fffffff)<<32))
#define SMALLEST_INT64 (((i64)-1) - LARGEST_INT64)
#define MASTER_NAME "sqlite_master"
#define TEMP_MASTER_NAME "sqlite_temp_master"
#define MASTER_ROOT 1
#define SCHEMA_TABLE(x) ((!OMIT_TEMPDB)&&(x==1)?TEMP_MASTER_NAME:MASTER_NAME)
#define ArraySize(X) (sizeof(X)/sizeof(X[0]))
#define SQLITE_DYNAMIC ((sqlite3_destructor_type)sqlite3DbFree)
#define SQLITE_WSD
#define GLOBAL(t, v) v
#define sqlite3GlobalConfig sqlite3Config
#define DbHasProperty(D, I, P) (((D)->aDb[I].pSchema->flags&(P))==(P))
#define DbHasAnyProperty(D, I, P) (((D)->aDb[I].pSchema->flags&(P))!=0)
#define DbSetProperty(D, I, P) (D)->aDb[I].pSchema->flags|=(P)
#define DbClearProperty(D, I, P) (D)->aDb[I].pSchema->flags&=~(P)
#define DB_SchemaLoaded 0x0001
#define DB_UnresetViews 0x0002
#define DB_Empty 0x0004
#define SQLITE_N_LIMIT (SQLITE_LIMIT_VARIABLE_NUMBER+1)
#define ENC(db) ((db)->aDb[0].pSchema->enc)
#define SQLITE_VdbeTrace 0x00000001
#define SQLITE_InTrans 0x00000008
#define SQLITE_InternChanges 0x00000010
#define SQLITE_FullColNames 0x00000020
#define SQLITE_ShortColNames 0x00000040
#define SQLITE_CountRows 0x00000080
#define SQLITE_NullCallback 0x00000100
#define SQLITE_SqlTrace 0x00000200
#define SQLITE_VdbeListing 0x00000400
#define SQLITE_WriteSchema 0x00000800
#define SQLITE_NoReadlock 0x00001000
#define SQLITE_IgnoreChecks 0x00002000
#define SQLITE_ReadUncommitted 0x00004000
#define SQLITE_LegacyFileFmt 0x00008000
#define SQLITE_FullFSync 0x00010000
#define SQLITE_LoadExtension 0x00020000
#define SQLITE_RecoveryMode 0x00040000
#define SQLITE_SharedCache 0x00080000
#define SQLITE_Vtab 0x00100000
#define SQLITE_MAGIC_OPEN 0xa029a697
#define SQLITE_MAGIC_CLOSED 0x9f3c2d33
#define SQLITE_MAGIC_SICK 0x4b771290
#define SQLITE_MAGIC_BUSY 0xf03b7906
#define SQLITE_MAGIC_ERROR 0xb5357930
#define SQLITE_FUNC_LIKE 0x01
#define SQLITE_FUNC_CASE 0x02
#define SQLITE_FUNC_EPHEM 0x04
#define SQLITE_FUNC_NEEDCOLL 0x08
#define FUNCTION(zName, nArg, iArg, bNC, xFunc) {nArg, SQLITE_UTF8, bNC*8, SQLITE_INT_TO_PTR(iArg), 0, xFunc, 0, 0, #zName}
#define STR_FUNCTION(zName, nArg, pArg, bNC, xFunc) {nArg, SQLITE_UTF8, bNC*8, pArg, 0, xFunc, 0, 0, #zName}
#define LIKEFUNC(zName, nArg, arg, flags) {nArg, SQLITE_UTF8, flags, (void *)arg, 0, likeFunc, 0, 0, #zName}
#define AGGREGATE(zName, nArg, arg, nc, xStep, xFinal) {nArg, SQLITE_UTF8, nc*8, SQLITE_INT_TO_PTR(arg), 0, 0, xStep,xFinal, #zName}
#define SQLITE_COLL_BINARY 1
#define SQLITE_COLL_NOCASE 2
#define SQLITE_COLL_REVERSE 3
#define SQLITE_COLL_USER 0
#define SQLITE_SO_ASC 0
#define SQLITE_SO_DESC 1
#define SQLITE_AFF_TEXT 'a'
#define SQLITE_AFF_NONE 'b'
#define SQLITE_AFF_NUMERIC 'c'
#define SQLITE_AFF_INTEGER 'd'
#define SQLITE_AFF_REAL 'e'
#define sqlite3IsNumericAffinity(X) ((X)>=SQLITE_AFF_NUMERIC)
#define SQLITE_AFF_MASK 0x67
#define SQLITE_JUMPIFNULL 0x08
#define SQLITE_STOREP2 0x10
#define TF_Readonly 0x01
#define TF_Ephemeral 0x02
#define TF_HasPrimaryKey 0x04
#define TF_Autoincrement 0x08
#define TF_Virtual 0x10
#define TF_NeedMetadata 0x20
#define IsVirtual(X) (((X)->tabFlags & TF_Virtual)!=0)
#define IsHiddenColumn(X) ((X)->isHidden)
#define OE_None 0
#define OE_Rollback 1
#define OE_Abort 2
#define OE_Fail 3
#define OE_Ignore 4
#define OE_Replace 5
#define OE_Restrict 6
#define OE_SetNull 7
#define OE_SetDflt 8
#define OE_Cascade 9
#define OE_Default 99
#define UNPACKED_NEED_FREE 0x0001
#define UNPACKED_NEED_DESTROY 0x0002
#define UNPACKED_IGNORE_ROWID 0x0004
#define UNPACKED_INCRKEY 0x0008
#define UNPACKED_PREFIX_MATCH 0x0010
#define EP_FromJoin 0x0001
#define EP_Agg 0x0002
#define EP_Resolved 0x0004
#define EP_Error 0x0008
#define EP_Distinct 0x0010
#define EP_VarSelect 0x0020
#define EP_Dequoted 0x0040
#define EP_InfixFunc 0x0080
#define EP_ExpCollate 0x0100
#define EP_AnyAff 0x0200
#define EP_FixedDest 0x0400
#define EP_IntValue 0x0800
#define ExprHasProperty(E, P) (((E)->flags&(P))==(P))
#define ExprHasAnyProperty(E, P) (((E)->flags&(P))!=0)
#define ExprSetProperty(E, P) (E)->flags|=(P)
#define ExprClearProperty(E, P) (E)->flags&=~(P)
#define JT_INNER 0x0001
#define JT_CROSS 0x0002
#define JT_NATURAL 0x0004
#define JT_LEFT 0x0008
#define JT_RIGHT 0x0010
#define JT_OUTER 0x0020
#define JT_ERROR 0x0040
#define WHERE_ORDERBY_NORMAL 0
#define WHERE_ORDERBY_MIN 1
#define WHERE_ORDERBY_MAX 2
#define WHERE_ONEPASS_DESIRED 4
#define SF_Distinct 0x0001
#define SF_Resolved 0x0002
#define SF_Aggregate 0x0004
#define SF_UsesEphemeral 0x0008
#define SF_Expanded 0x0010
#define SF_HasTypeInfo 0x0020
#define SRT_Union 1
#define SRT_Except 2
#define SRT_Exists 3
#define SRT_Discard 4
#define IgnorableOrderby(X) ((X->eDest)<=SRT_Discard)
#define SRT_Output 5
#define SRT_Mem 6
#define SRT_Set 7
#define SRT_Table 8
#define SRT_EphemTab 9
#define SRT_Coroutine 10
#define IN_DECLARE_VTAB (pParse->declareVtab)
#define OPFLAG_NCHANGE 1
#define OPFLAG_LASTROWID 2
#define OPFLAG_ISUPDATE 4
#define OPFLAG_APPEND 8
#define TRIGGER_BEFORE 1
#define TRIGGER_AFTER 2
#define WRC_Continue 0
#define WRC_Prune 1
#define WRC_Abort 2
#define SQLITE_SKIP_UTF8(zIn)
#define SQLITE_CORRUPT_BKPT SQLITE_CORRUPT
#define sqlite3SafetyOn(A) 0
#define sqlite3SafetyOff(A) 0
#define getVarint32(A, B) ((*(A)<(unsigned char)0x80) ? ((B) = (u32)*(A)),1 : sqlite3GetVarint32((A), &(B)))
#define putVarint32(A, B) (((B)<(u32)0x80) ? (*(A) = (unsigned char)(B)),1 : sqlite3PutVarint32((A), (B)))
#define getVarint sqlite3GetVarint
#define putVarint sqlite3PutVarint
#define sqlite3CloseExtensions(X)
#define SQLITE_FAULTINJECTOR_MALLOC 0
#define SQLITE_FAULTINJECTOR_COUNT 1
#define IN_INDEX_ROWID 1
#define IN_INDEX_EPH 2
#define IN_INDEX_INDEX 3
#define sqlite3JournalSize(pVfs) ((pVfs)->szOsFile)
#define sqlite3ExprSetHeight(x, y)
#define sqlite3SelectExprHeight(x) 0
#define sqlite3ExprCheckHeight(x, y)
#define IOTRACE(A)
#define sqlite3VdbeIOTraceSql(X)
Typedefs
typedef sqlite_int64 i64
typedef sqlite_uint64 u64
typedef UINT32_TYPE u32
typedef UINT16_TYPE u16
typedef INT16_TYPE i16
typedef UINT8_TYPE u8
typedef INT8_TYPE i8
typedef struct BusyHandler BusyHandler
typedef struct AggInfo AggInfo
typedef struct AuthContext AuthContext
typedef struct Bitvec Bitvec
typedef struct CollSeq CollSeq
typedef struct Column Column
typedef struct Db Db
typedef struct Schema Schema
typedef struct Expr Expr
typedef struct ExprList ExprList
typedef struct FKey FKey
typedef struct FuncDef FuncDef
typedef struct FuncDefHash FuncDefHash
typedef struct IdList IdList
typedef struct Index Index
typedef struct KeyClass KeyClass
typedef struct KeyInfo KeyInfo
typedef struct Lookaside Lookaside
typedef struct LookasideSlot LookasideSlot
typedef struct Module Module
typedef struct NameContext NameContext
typedef struct Parse Parse
typedef struct Select Select
typedef struct SrcList SrcList
typedef struct StrAccum StrAccum
typedef struct Table Table
typedef struct TableLock TableLock
typedef struct Token Token
typedef struct TriggerStack TriggerStack
typedef struct TriggerStep TriggerStep
typedef struct Trigger Trigger
typedef struct UnpackedRecord UnpackedRecord
typedef struct Walker Walker
typedef struct WhereInfo WhereInfo
typedef struct WhereLevel WhereLevel
typedef u64 Bitmask
typedef struct SelectDest SelectDest
typedef struct DbFixer DbFixer
Functions
int sqlite3WalkExpr (Walker *, Expr *)
int sqlite3WalkExprList (Walker *, ExprList *)
int sqlite3WalkSelect (Walker *, Select *)
int sqlite3WalkSelectExpr (Walker *, Select *)
int sqlite3WalkSelectFrom (Walker *, Select *)
int sqlite3StrICmp (const char *, const char *)
int sqlite3StrNICmp (const char *, const char *, int)
int sqlite3IsNumber (const char *, int *, u8)
int sqlite3Strlen (sqlite3 *, const char *)
int sqlite3MallocInit (void)
void sqlite3MallocEnd (void)
void * sqlite3Malloc (int)
void * sqlite3MallocZero (int)
void * sqlite3DbMallocZero (sqlite3 *, int)
void * sqlite3DbMallocRaw (sqlite3 *, int)
char * sqlite3DbStrDup (sqlite3 *, const char *)
char * sqlite3DbStrNDup (sqlite3 *, const char *, int)
void * sqlite3Realloc (void *, int)
void * sqlite3DbReallocOrFree (sqlite3 *, void *, int)
void * sqlite3DbRealloc (sqlite3 *, void *, int)
void sqlite3DbFree (sqlite3 *, void *)
int sqlite3MallocSize (void *)
int sqlite3DbMallocSize (sqlite3 *, void *)
void * sqlite3ScratchMalloc (int)
void sqlite3ScratchFree (void *)
void * sqlite3PageMalloc (int)
void sqlite3PageFree (void *)
void sqlite3MemSetDefault (void)
const sqlite3_mem_methods * sqlite3MemGetMemsys3 (void)
const sqlite3_mem_methods * sqlite3MemGetMemsys5 (void)
void sqlite3BenignMallocHooks (void(*)(void), void(*)(void))
int sqlite3MemoryAlarm (void(*)(void *, sqlite3_int64, int), void *, sqlite3_int64)
int sqlite3StatusValue (int)
void sqlite3StatusAdd (int, int)
void sqlite3StatusSet (int, int)
int sqlite3IsNaN (double)
void sqlite3VXPrintf (StrAccum *, int, const char *, va_list)
char * sqlite3MPrintf (sqlite3 *, const char *,...)
char * sqlite3VMPrintf (sqlite3 *, const char *, va_list)
char * sqlite3MAppendf (sqlite3 *, char *, const char *,...)
void sqlite3SetString (char **, sqlite3 *, const char *,...)
void sqlite3ErrorMsg (Parse *, const char *,...)
void sqlite3ErrorClear (Parse *)
void sqlite3Dequote (char *)
void sqlite3DequoteExpr (sqlite3 *, Expr *)
int sqlite3KeywordCode (const unsigned char *, int)
int sqlite3RunParser (Parse *, const char *, char **)
void sqlite3FinishCoding (Parse *)
int sqlite3GetTempReg (Parse *)
void sqlite3ReleaseTempReg (Parse *, int)
int sqlite3GetTempRange (Parse *, int)
void sqlite3ReleaseTempRange (Parse *, int, int)
Expr * sqlite3Expr (sqlite3 *, int, Expr *, Expr *, const Token *)
Expr * sqlite3PExpr (Parse *, int, Expr *, Expr *, const Token *)
Expr * sqlite3RegisterExpr (Parse *, Token *)
Expr * sqlite3ExprAnd (sqlite3 *, Expr *, Expr *)
void sqlite3ExprSpan (Expr *, Token *, Token *)
Expr * sqlite3ExprFunction (Parse *, ExprList *, Token *)
void sqlite3ExprAssignVarNumber (Parse *, Expr *)
void sqlite3ExprClear (sqlite3 *, Expr *)
void sqlite3ExprDelete (sqlite3 *, Expr *)
ExprList * sqlite3ExprListAppend (Parse *, ExprList *, Expr *, Token *)
void sqlite3ExprListDelete (sqlite3 *, ExprList *)
int sqlite3Init (sqlite3 *, char **)
int sqlite3InitCallback (void *, int, char **, char **)
void sqlite3Pragma (Parse *, Token *, Token *, Token *, int)
void sqlite3ResetInternalSchema (sqlite3 *, int)
void sqlite3BeginParse (Parse *, int)
void sqlite3CommitInternalChanges (sqlite3 *)
Table * sqlite3ResultSetOfSelect (Parse *, Select *)
void sqlite3OpenMasterTable (Parse *, int)
void sqlite3StartTable (Parse *, Token *, Token *, int, int, int, int)
void sqlite3AddColumn (Parse *, Token *)
void sqlite3AddNotNull (Parse *, int)
void sqlite3AddPrimaryKey (Parse *, ExprList *, int, int, int)
void sqlite3AddCheckConstraint (Parse *, Expr *)
void sqlite3AddColumnType (Parse *, Token *)
void sqlite3AddDefaultValue (Parse *, Expr *)
void sqlite3AddCollateType (Parse *, Token *)
void sqlite3EndTable (Parse *, Token *, Token *, Select *)
Bitvec * sqlite3BitvecCreate (u32)
int sqlite3BitvecTest (Bitvec *, u32)
int sqlite3BitvecSet (Bitvec *, u32)
void sqlite3BitvecClear (Bitvec *, u32)
void sqlite3BitvecDestroy (Bitvec *)
int sqlite3BitvecBuiltinTest (int, int *)
void sqlite3CreateView (Parse *, Token *, Token *, Token *, Select *, int, int)
int sqlite3ViewGetColumnNames (Parse *, Table *)
void sqlite3DropTable (Parse *, SrcList *, int, int)
void sqlite3DeleteTable (Table *)
void sqlite3Insert (Parse *, SrcList *, ExprList *, Select *, IdList *, int)
void * sqlite3ArrayAllocate (sqlite3 *, void *, int, int, int *, int *, int *)
IdList * sqlite3IdListAppend (sqlite3 *, IdList *, Token *)
int sqlite3IdListIndex (IdList *, const char *)
SrcList * sqlite3SrcListEnlarge (sqlite3 *, SrcList *, int, int)
SrcList * sqlite3SrcListAppend (sqlite3 *, SrcList *, Token *, Token *)
SrcList * sqlite3SrcListAppendFromTerm (Parse *, SrcList *, Token *, Token *, Token *, Select *, Expr *, IdList *)
void sqlite3SrcListIndexedBy (Parse *, SrcList *, Token *)
int sqlite3IndexedByLookup (Parse *, struct SrcList_item *)
void sqlite3SrcListShiftJoinType (SrcList *)
void sqlite3SrcListAssignCursors (Parse *, SrcList *)
void sqlite3IdListDelete (sqlite3 *, IdList *)
void sqlite3SrcListDelete (sqlite3 *, SrcList *)
void sqlite3CreateIndex (Parse *, Token *, Token *, SrcList *, ExprList *, int, Token *, Token *, int, int)
void sqlite3DropIndex (Parse *, SrcList *, int)
int sqlite3Select (Parse *, Select *, SelectDest *)
Select * sqlite3SelectNew (Parse *, ExprList *, SrcList *, Expr *, ExprList *, Expr *, ExprList *, int, Expr *, Expr *)
void sqlite3SelectDelete (sqlite3 *, Select *)
Table * sqlite3SrcListLookup (Parse *, SrcList *)
int sqlite3IsReadOnly (Parse *, Table *, int)
void sqlite3OpenTable (Parse *, int iCur, int iDb, Table *, int)
void sqlite3DeleteFrom (Parse *, SrcList *, Expr *)
void sqlite3Update (Parse *, SrcList *, ExprList *, Expr *, int)
WhereInfo * sqlite3WhereBegin (Parse *, SrcList *, Expr *, ExprList **, u8)
void sqlite3WhereEnd (WhereInfo *)
int sqlite3ExprCodeGetColumn (Parse *, Table *, int, int, int, int)
void sqlite3ExprCodeMove (Parse *, int, int, int)
void sqlite3ExprCodeCopy (Parse *, int, int, int)
void sqlite3ExprClearColumnCache (Parse *, int)
void sqlite3ExprCacheAffinityChange (Parse *, int, int)
int sqlite3ExprWritableRegister (Parse *, int, int)
void sqlite3ExprHardCopy (Parse *, int, int)
int sqlite3ExprCode (Parse *, Expr *, int)
int sqlite3ExprCodeTemp (Parse *, Expr *, int *)
int sqlite3ExprCodeTarget (Parse *, Expr *, int)
int sqlite3ExprCodeAndCache (Parse *, Expr *, int)
void sqlite3ExprCodeConstants (Parse *, Expr *)
int sqlite3ExprCodeExprList (Parse *, ExprList *, int, int)
void sqlite3ExprIfTrue (Parse *, Expr *, int, int)
void sqlite3ExprIfFalse (Parse *, Expr *, int, int)
Table * sqlite3FindTable (sqlite3 *, const char *, const char *)
Table * sqlite3LocateTable (Parse *, int isView, const char *, const char *)
Index * sqlite3FindIndex (sqlite3 *, const char *, const char *)
void sqlite3UnlinkAndDeleteTable (sqlite3 *, int, const char *)
void sqlite3UnlinkAndDeleteIndex (sqlite3 *, int, const char *)
void sqlite3Vacuum (Parse *)
int sqlite3RunVacuum (char **, sqlite3 *)
char * sqlite3NameFromToken (sqlite3 *, Token *)
int sqlite3ExprCompare (Expr *, Expr *)
void sqlite3ExprAnalyzeAggregates (NameContext *, Expr *)
void sqlite3ExprAnalyzeAggList (NameContext *, ExprList *)
Vdbe * sqlite3GetVdbe (Parse *)
Expr * sqlite3CreateIdExpr (Parse *, const char *)
void sqlite3PrngSaveState (void)
void sqlite3PrngRestoreState (void)
void sqlite3PrngResetState (void)
void sqlite3RollbackAll (sqlite3 *)
void sqlite3CodeVerifySchema (Parse *, int)
void sqlite3BeginTransaction (Parse *, int)
void sqlite3CommitTransaction (Parse *)
void sqlite3RollbackTransaction (Parse *)
int sqlite3ExprIsConstant (Expr *)
int sqlite3ExprIsConstantNotJoin (Expr *)
int sqlite3ExprIsConstantOrFunction (Expr *)
int sqlite3ExprIsInteger (Expr *, int *)
int sqlite3IsRowid (const char *)
void sqlite3GenerateRowDelete (Parse *, Table *, int, int, int)
void sqlite3GenerateRowIndexDelete (Parse *, Table *, int, int *)
int sqlite3GenerateIndexKey (Parse *, Index *, int, int, int)
void sqlite3GenerateConstraintChecks (Parse *, Table *, int, int, int *, int, int, int, int)
void sqlite3CompleteInsertion (Parse *, Table *, int, int, int *, int, int, int, int)
int sqlite3OpenTableAndIndices (Parse *, Table *, int, int)
void sqlite3BeginWriteOperation (Parse *, int, int)
Expr * sqlite3ExprDup (sqlite3 *, Expr *)
void sqlite3TokenCopy (sqlite3 *, Token *, Token *)
ExprList * sqlite3ExprListDup (sqlite3 *, ExprList *)
SrcList * sqlite3SrcListDup (sqlite3 *, SrcList *)
IdList * sqlite3IdListDup (sqlite3 *, IdList *)
Select * sqlite3SelectDup (sqlite3 *, Select *)
void sqlite3FuncDefInsert (FuncDefHash *, FuncDef *)
FuncDef * sqlite3FindFunction (sqlite3 *, const char *, int, int, u8, int)
void sqlite3RegisterBuiltinFunctions (sqlite3 *)
void sqlite3RegisterDateTimeFunctions (void)
void sqlite3RegisterGlobalFunctions (void)
int sqlite3GetBuiltinFunction (const char *, int, FuncDef **)
int sqlite3SafetyCheckOk (sqlite3 *)
int sqlite3SafetyCheckSickOrOk (sqlite3 *)
void sqlite3ChangeCookie (Parse *, int)
void sqlite3MaterializeView (Parse *, Table *, Expr *, int)
void sqlite3BeginTrigger (Parse *, Token *, Token *, int, int, IdList *, SrcList *, Expr *, int, int)
void sqlite3FinishTrigger (Parse *, TriggerStep *, Token *)
void sqlite3DropTrigger (Parse *, SrcList *, int)
void sqlite3DropTriggerPtr (Parse *, Trigger *)
int sqlite3TriggersExist (Parse *, Table *, int, ExprList *)
int sqlite3CodeRowTrigger (Parse *, int, ExprList *, int, Table *, int, int, int, int, u32 *, u32 *)
void sqliteViewTriggers (Parse *, Table *, Expr *, int, ExprList *)
void sqlite3DeleteTriggerStep (sqlite3 *, TriggerStep *)
TriggerStep * sqlite3TriggerSelectStep (sqlite3 *, Select *)
TriggerStep * sqlite3TriggerInsertStep (sqlite3 *, Token *, IdList *, ExprList *, Select *, int)
TriggerStep * sqlite3TriggerUpdateStep (sqlite3 *, Token *, ExprList *, Expr *, int)
TriggerStep * sqlite3TriggerDeleteStep (sqlite3 *, Token *, Expr *)
void sqlite3DeleteTrigger (sqlite3 *, Trigger *)
void sqlite3UnlinkAndDeleteTrigger (sqlite3 *, int, const char *)
int sqlite3JoinType (Parse *, Token *, Token *, Token *)
void sqlite3CreateForeignKey (Parse *, ExprList *, Token *, ExprList *, int)
void sqlite3DeferForeignKey (Parse *, int)
void sqlite3AuthRead (Parse *, Expr *, Schema *, SrcList *)
int sqlite3AuthCheck (Parse *, int, const char *, const char *, const char *)
void sqlite3AuthContextPush (Parse *, AuthContext *, const char *)
void sqlite3AuthContextPop (AuthContext *)
void sqlite3Attach (Parse *, Expr *, Expr *, Expr *)
void sqlite3Detach (Parse *, Expr *)
int sqlite3BtreeFactory (const sqlite3 *db, const char *zFilename, int omitJournal, int nCache, int flags, Btree **ppBtree)
int sqlite3FixInit (DbFixer *, Parse *, int, const char *, const Token *)
int sqlite3FixSrcList (DbFixer *, SrcList *)
int sqlite3FixSelect (DbFixer *, Select *)
int sqlite3FixExpr (DbFixer *, Expr *)
int sqlite3FixExprList (DbFixer *, ExprList *)
int sqlite3FixTriggerStep (DbFixer *, TriggerStep *)
int sqlite3AtoF (const char *z, double *)
int sqlite3GetInt32 (const char *, int *)
int sqlite3FitsIn64Bits (const char *, int)
int sqlite3Utf16ByteLen (const void *pData, int nChar)
int sqlite3Utf8CharLen (const char *pData, int nByte)
int sqlite3Utf8Read (const u8 *, const u8 *, const u8 **)
int sqlite3PutVarint (unsigned char *, u64)
int sqlite3PutVarint32 (unsigned char *, u32)
int sqlite3GetVarint (const unsigned char *, u64 *)
int sqlite3GetVarint32 (const unsigned char *, u32 *)
int sqlite3VarintLen (u64 v)
void sqlite3IndexAffinityStr (Vdbe *, Index *)
void sqlite3TableAffinityStr (Vdbe *, Table *)
char sqlite3CompareAffinity (Expr *pExpr, char aff2)
int sqlite3IndexAffinityOk (Expr *pExpr, char idx_affinity)
char sqlite3ExprAffinity (Expr *pExpr)
int sqlite3Atoi64 (const char *, i64 *)
void sqlite3Error (sqlite3 *, int, const char *,...)
void * sqlite3HexToBlob (sqlite3 *, const char *z, int n)
int sqlite3TwoPartName (Parse *, Token *, Token *, Token **)
const char * sqlite3ErrStr (int)
int sqlite3ReadSchema (Parse *pParse)
CollSeq * sqlite3FindCollSeq (sqlite3 *, u8 enc, const char *, int, int)
CollSeq * sqlite3LocateCollSeq (Parse *pParse, const char *zName, int nName)
CollSeq * sqlite3ExprCollSeq (Parse *pParse, Expr *pExpr)
Expr * sqlite3ExprSetColl (Parse *pParse, Expr *, Token *)
int sqlite3CheckCollSeq (Parse *, CollSeq *)
int sqlite3CheckObjectName (Parse *, const char *)
void sqlite3VdbeSetChanges (sqlite3 *, int)
const void * sqlite3ValueText (sqlite3_value *, u8)
int sqlite3ValueBytes (sqlite3_value *, u8)
void sqlite3ValueSetStr (sqlite3_value *, int, const void *, u8, void(*)(void *))
void sqlite3ValueFree (sqlite3_value *)
sqlite3_value * sqlite3ValueNew (sqlite3 *)
char * sqlite3Utf16to8 (sqlite3 *, const void *, int)
int sqlite3ValueFromExpr (sqlite3 *, Expr *, u8, u8, sqlite3_value **)
void sqlite3ValueApplyAffinity (sqlite3_value *, u8, u8)
void sqlite3RootPageMoved (Db *, int, int)
void sqlite3Reindex (Parse *, Token *, Token *)
void sqlite3AlterFunctions (sqlite3 *)
void sqlite3AlterRenameTable (Parse *, SrcList *, Token *)
int sqlite3GetToken (const unsigned char *, int *)
void sqlite3NestedParse (Parse *, const char *,...)
void sqlite3ExpirePreparedStatements (sqlite3 *)
void sqlite3CodeSubselect (Parse *, Expr *, int, int)
void sqlite3SelectPrep (Parse *, Select *, NameContext *)
int sqlite3ResolveExprNames (NameContext *, Expr *)
void sqlite3ResolveSelectNames (Parse *, Select *, NameContext *)
int sqlite3ResolveOrderGroupBy (Parse *, Select *, ExprList *, const char *)
void sqlite3ColumnDefault (Vdbe *, Table *, int)
void sqlite3AlterFinishAddColumn (Parse *, Token *)
void sqlite3AlterBeginAddColumn (Parse *, SrcList *)
CollSeq * sqlite3GetCollSeq (sqlite3 *, CollSeq *, const char *, int)
char sqlite3AffinityType (const Token *)
void sqlite3Analyze (Parse *, Token *, Token *)
int sqlite3InvokeBusyHandler (BusyHandler *)
int sqlite3FindDb (sqlite3 *, Token *)
int sqlite3AnalysisLoad (sqlite3 *, int iDB)
void sqlite3DefaultRowEst (Index *)
void sqlite3RegisterLikeFunctions (sqlite3 *, int)
int sqlite3IsLikeFunction (sqlite3 *, Expr *, int *, char *)
void sqlite3MinimumFileFormat (Parse *, int, int)
void sqlite3SchemaFree (void *)
Schema * sqlite3SchemaGet (sqlite3 *, Btree *)
int sqlite3SchemaToIndex (sqlite3 *db, Schema *)
KeyInfo * sqlite3IndexKeyinfo (Parse *, Index *)
int sqlite3CreateFunc (sqlite3 *, const char *, int, int, void *, void(*)(sqlite3_context *, int, sqlite3_value **), void(*)(sqlite3_context *, int, sqlite3_value **), void(*)(sqlite3_context *))
int sqlite3ApiExit (sqlite3 *db, int)
int sqlite3OpenTempDatabase (Parse *)
void sqlite3StrAccumInit (StrAccum *, char *, int, int)
void sqlite3StrAccumAppend (StrAccum *, const char *, int)
char * sqlite3StrAccumFinish (StrAccum *)
void sqlite3StrAccumReset (StrAccum *)
void sqlite3SelectDestInit (SelectDest *, int, int)
void * sqlite3ParserAlloc (void *(*)(size_t))
void sqlite3ParserFree (void *, void(*)(void *))
void sqlite3Parser (void *, int, Token, Parse *)
int sqlite3AutoLoadExtensions (sqlite3 *)
void sqlite3TableLock (Parse *, int, int, u8, const char *)
void sqlite3VtabClear (Table *)
int sqlite3VtabSync (sqlite3 *db, char **)
int sqlite3VtabRollback (sqlite3 *db)
int sqlite3VtabCommit (sqlite3 *db)
void sqlite3VtabMakeWritable (Parse *, Table *)
void sqlite3VtabLock (sqlite3_vtab *)
void sqlite3VtabUnlock (sqlite3 *, sqlite3_vtab *)
void sqlite3VtabBeginParse (Parse *, Token *, Token *, Token *)
void sqlite3VtabFinishParse (Parse *, Token *)
void sqlite3VtabArgInit (Parse *)
void sqlite3VtabArgExtend (Parse *, Token *)
int sqlite3VtabCallCreate (sqlite3 *, int, const char *, char **)
int sqlite3VtabCallConnect (Parse *, Table *)
int sqlite3VtabCallDestroy (sqlite3 *, int, const char *)
int sqlite3VtabBegin (sqlite3 *, sqlite3_vtab *)
FuncDef * sqlite3VtabOverloadFunction (sqlite3 *, FuncDef *, int nArg, Expr *)
void sqlite3InvalidFunction (sqlite3_context *, int, sqlite3_value **)
int sqlite3TransferBindings (sqlite3_stmt *, sqlite3_stmt *)
int sqlite3Reprepare (Vdbe *)
void sqlite3ExprListCheckLength (Parse *, ExprList *, const char *)
CollSeq * sqlite3BinaryCompareCollSeq (Parse *, Expr *, Expr *)
void sqlite3BeginBenignMalloc (void)
void sqlite3EndBenignMalloc (void)
int sqlite3FindInIndex (Parse *, Expr *, int *)
void sqlite3MemJournalOpen (sqlite3_file *)
int sqlite3MemJournalSize ()
int sqlite3IsMemJournal (sqlite3_file *)
u32 sqlite3Get4byte (const u8 *)
void sqlite3Put4byte (u8 *, u32)
Variables
const int sqlite3one
const unsigned char sqlite3UpperToLower []
SQLITE_WSD struct Sqlite3Config sqlite3Config
SQLITE_WSD FuncDefHash sqlite3GlobalFunctions
Define Documentation
#define AGGREGATE (zName, nArg, arg, nc, xStep, xFinal) {nArg, SQLITE_UTF8, nc*8, SQLITE_INT_TO_PTR(arg), 0, 0, xStep,xFinal, #zName}
Definition at line 854 of file sqliteInt.h.
Referenced by sqlite3RegisterGlobalFunctions().
#define ALWAYS (X) (X)
Definition at line 82 of file sqliteInt.h.
Referenced by bestIndex(), disableTerm(), and removeFromSharingList().
#define ArraySize (X) (sizeof(X)/sizeof(X[0]))
Definition at line 445 of file sqliteInt.h.
#define DB_Empty 0x0004
Definition at line 596 of file sqliteInt.h.
Referenced by sqlite3InitCallback(), sqlite3InitOne(), and sqlite3Pragma().
#define DB_SchemaLoaded 0x0001
Definition at line 594 of file sqliteInt.h.
Referenced by sqlite3_open16(), sqlite3Init(), sqlite3InitOne(), sqlite3Pragma(), sqlite3SchemaFree(), and sqlite3VdbeExec().
#define DB_UnresetViews 0x0002
Definition at line 595 of file sqliteInt.h.
Referenced by sqlite3ViewGetColumnNames(), and sqliteViewResetAll().
#define DbClearProperty (D, I, P) (D)->aDb[I].pSchema->flags&=~(P)
Definition at line 582 of file sqliteInt.h.
Referenced by sqlite3InitCallback(), and sqliteViewResetAll().
#define DbHasAnyProperty (D, I, P) (((D)->aDb[I].pSchema->flags&(P))!=0)
Definition at line 580 of file sqliteInt.h.
#define DbHasProperty (D, I, P) (((D)->aDb[I].pSchema->flags&(P))==(P))
Definition at line 579 of file sqliteInt.h.
Referenced by sqlite3_open16(), sqlite3Init(), sqlite3Pragma(), sqlite3VdbeExec(), and sqliteViewResetAll().
#define DbSetProperty (D, I, P) (D)->aDb[I].pSchema->flags|=(P)
Definition at line 581 of file sqliteInt.h.
Referenced by sqlite3InitOne().
#define ENC (db) ((db)->aDb[0].pSchema->enc)
Definition at line 751 of file sqliteInt.h.
Referenced by analyzeAggregate(), attachFunc(), bindText(), callCollNeeded(), keyInfoFromExprList(), multiSelect(), multiSelectOrderBy(), resolveExprStep(), sqlite3_bind_value(), sqlite3_open16(), sqlite3ColumnDefault(), sqlite3ExprCodeTarget(), sqlite3ExprCollSeq(), sqlite3FindInIndex(), sqlite3GetCollSeq(), sqlite3InitOne(), sqlite3LocateCollSeq(), sqlite3Pragma(), sqlite3Reindex(), sqlite3StartTable(), and sqlite3VdbeExec().
#define EP_Agg 0x0002
Definition at line 1349 of file sqliteInt.h.
Referenced by lookupName(), resolveSelectStep(), and sqlite3ResolveExprNames().
#define EP_AnyAff 0x0200
Definition at line 1357 of file sqliteInt.h.
Referenced by codeCompareOperands(), and sqlite3ExprCodeTarget().
#define EP_Dequoted 0x0040
Definition at line 1354 of file sqliteInt.h.
Referenced by exprAnalyze(), and sqlite3DequoteExpr().
#define EP_Distinct 0x0010
Definition at line 1352 of file sqliteInt.h.
Referenced by analyzeAggregate(), sqlite3ExprCompare(), and yy_reduce().
#define EP_Error 0x0008
Definition at line 1351 of file sqliteInt.h.
Referenced by sqlite3ResolveExprNames().
#define EP_ExpCollate 0x0100
Definition at line 1356 of file sqliteInt.h.
Referenced by exprCommute(), multiSelectOrderBy(), resolveAlias(), resolveCompoundOrderBy(), sqlite3BinaryCompareCollSeq(), sqlite3Expr(), and sqlite3ExprSetColl().
#define EP_FixedDest 0x0400
Definition at line 1358 of file sqliteInt.h.
Referenced by evalConstExpr(), and isAppropriateForFactoring().
#define EP_FromJoin 0x0001
Definition at line 1348 of file sqliteInt.h.
Referenced by addWhereTerm(), disableTerm(), exprAnalyze(), exprNodeIsConstant(), setJoinExpr(), sqlite3WhereBegin(), and transferJoinMarkings().
#define EP_InfixFunc 0x0080
Definition at line 1355 of file sqliteInt.h.
Referenced by sqlite3ExprCodeTarget(), and yy_reduce().
#define EP_IntValue 0x0800
Definition at line 1359 of file sqliteInt.h.
Referenced by codeInteger(), multiSelectOrderBy(), resolveCompoundOrderBy(), and sqlite3ExprIsInteger().
#define EP_Resolved 0x0004
Definition at line 1350 of file sqliteInt.h.
Referenced by resolveAlias(), and resolveExprStep().
#define EP_VarSelect 0x0020
Definition at line 1353 of file sqliteInt.h.
Referenced by resolveExprStep(), and sqlite3CodeSubselect().
#define ExprClearProperty (E, P) (E)->flags&=~(P)
Definition at line 1367 of file sqliteInt.h.
#define ExprHasAnyProperty (E, P) (((E)->flags&(P))!=0)
Definition at line 1365 of file sqliteInt.h.
Referenced by exprNodeIsConstant(), resolveExprStep(), sqlite3CodeSubselect(), and sqlite3DequoteExpr().
#define ExprHasProperty (E, P) (((E)->flags&(P))==(P))
Definition at line 1364 of file sqliteInt.h.
Referenced by disableTerm(), exprAnalyze(), lookupName(), resolveSelectStep(), sqlite3ResolveExprNames(), and sqlite3WhereBegin().
#define ExprSetProperty (E, P) (E)->flags|=(P)
Definition at line 1366 of file sqliteInt.h.
Referenced by addWhereTerm(), resolveExprStep(), setJoinExpr(), sqlite3DequoteExpr(), and sqlite3ResolveExprNames().
#define FUNCTION (zName, nArg, iArg, bNC, xFunc) {nArg, SQLITE_UTF8, bNC*8, SQLITE_INT_TO_PTR(iArg), 0, xFunc, 0, 0, #zName}
Definition at line 848 of file sqliteInt.h.
Referenced by sqlite3RegisterDateTimeFunctions(), and sqlite3RegisterGlobalFunctions().
#define getVarint sqlite3GetVarint
Definition at line 2337 of file sqliteInt.h.
Referenced by dlrPosData(), dlrPosDataLen(), dlrStep(), dlwAppend(), getVarint32(), interiorReaderInit(), peekDocid(), readDocid(), sqlite3BtreeMovetoUnpacked(), and sqlite3BtreeParseCellPtr().
#define getVarint32 (A, B) ((*(A)<(unsigned char)0x80) ? ((B) = (u32)*(A)),1 : sqlite3GetVarint32((A), &(B)))
Definition at line 2335 of file sqliteInt.h.
Referenced by dlrStep(), interiorReaderInit(), interiorReaderStep(), leafReaderData(), leafReaderDataBytes(), leafReaderInit(), leafReaderStep(), leafWriterInternalFlush(), plrStep(), readPosition(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeParseCellPtr(), sqlite3VdbeExec(), sqlite3VdbeIdxRowid(), sqlite3VdbeRecordCompare(), and sqlite3VdbeRecordUnpack().
#define GLOBAL (t, v) v
Definition at line 475 of file sqliteInt.h.
Referenced by randomByte(), removeFromSharingList(), sqlite3_initialize(), sqlite3BtreeOpen(), sqlite3FindFunction(), sqlite3PrngResetState(), sqlite3PrngRestoreState(), sqlite3PrngSaveState(), sqlite3RegisterDateTimeFunctions(), and sqlite3RegisterGlobalFunctions().
#define IgnorableOrderby (X) ((X->eDest)<=SRT_Discard)
Definition at line 1642 of file sqliteInt.h.
Referenced by sqlite3Select().
#define IN_DECLARE_VTAB (pParse->declareVtab)
Definition at line 1752 of file sqliteInt.h.
Referenced by sqlite3AddCheckConstraint(), sqlite3AddPrimaryKey(), sqlite3AuthCheck(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3RunParser(), and sqlite3StartTable().
#define IN_INDEX_EPH 2
Definition at line 2492 of file sqliteInt.h.
Referenced by sqlite3FindInIndex().
#define IN_INDEX_INDEX 3
Definition at line 2493 of file sqliteInt.h.
Referenced by sqlite3FindInIndex().
#define IN_INDEX_ROWID 1
Definition at line 2491 of file sqliteInt.h.
Referenced by codeEqualityTerm(), sqlite3ExprCodeTarget(), and sqlite3FindInIndex().
#define INT16_TYPE int16_t
Definition at line 349 of file sqliteInt.h.
#define INT8_TYPE int8_t
Definition at line 363 of file sqliteInt.h.
#define IOTRACE (A)
Definition at line 2539 of file sqliteInt.h.
Referenced by pager_unlock(), pager_wait_on_lock(), pager_write(), pager_write_pagelist(), pagerSharedLock(), readDbPage(), sqlite3PagerAcquire(), sqlite3PagerClose(), sqlite3PagerCommitPhaseOne(), sqlite3PagerDontRollback(), sqlite3PagerDontWrite(), sqlite3PagerMovepage(), sqlite3PagerOpen(), sqlite3PagerReadFileheader(), syncJournal(), writeJournalHdr(), and zeroJournalHdr().
#define IsHiddenColumn (X) ((X)->isHidden)
Definition at line 1046 of file sqliteInt.h.
Referenced by selectExpander(), sqlite3Insert(), and sqlite3Pragma().
#define IsVirtual (X) (((X)->tabFlags & TF_Virtual)!=0)
Definition at line 1045 of file sqliteInt.h.
Referenced by isCandidateForInOpt(), selectExpander(), sqlite3_blob_open(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropTable(), sqlite3ExprCodeGetColumn(), sqlite3Insert(), sqlite3OpenTable(), sqlite3OpenTableAndIndices(), sqlite3TriggersExist(), sqlite3Update(), sqlite3ViewGetColumnNames(), sqlite3VtabMakeWritable(), and sqlite3WhereBegin().
#define JT_CROSS 0x0002
Definition at line 1465 of file sqliteInt.h.
Referenced by sqlite3JoinType(), and sqlite3WhereBegin().
#define JT_ERROR 0x0040
Definition at line 1470 of file sqliteInt.h.
Referenced by sqlite3JoinType().
#define JT_INNER 0x0001
Definition at line 1464 of file sqliteInt.h.
Referenced by sqlite3JoinType(), and yy_reduce().
#define JT_LEFT 0x0008
Definition at line 1467 of file sqliteInt.h.
Referenced by bestIndex(), sqlite3JoinType(), and sqlite3WhereBegin().
#define JT_NATURAL 0x0004
Definition at line 1466 of file sqliteInt.h.
Referenced by lookupName(), selectExpander(), sqlite3JoinType(), and sqliteProcessJoin().
#define JT_OUTER 0x0020
Definition at line 1469 of file sqliteInt.h.
Referenced by flattenSubquery(), sqlite3JoinType(), and sqliteProcessJoin().
#define JT_RIGHT 0x0010
Definition at line 1468 of file sqliteInt.h.
Referenced by sqlite3JoinType().
#define LARGEST_INT64 (0xffffffff|(((i64)0x7fffffff)<<32))
Definition at line 404 of file sqliteInt.h.
Referenced by doubleToInt64().
#define LIKEFUNC (zName, nArg, arg, flags) {nArg, SQLITE_UTF8, flags, (void *)arg, 0, likeFunc, 0, 0, #zName}
Definition at line 852 of file sqliteInt.h.
Referenced by sqlite3RegisterGlobalFunctions().
#define likely (X) !!(X)
Definition at line 96 of file sqliteInt.h.
Referenced by sqlite3BtreeParseCellPtr().
#define LONGDOUBLE_TYPE long double
Definition at line 369 of file sqliteInt.h.
Referenced by et_getdigit(), sqlite3AtoF(), and sqlite3VXPrintf().
#define MASTER_NAME "sqlite_master"
Definition at line 428 of file sqliteInt.h.
#define MASTER_ROOT 1
Definition at line 434 of file sqliteInt.h.
Referenced by lockTable(), queryTableLock(), schemaIsValid(), sqlite3BtreeSchemaLocked(), sqlite3InitOne(), sqlite3OpenMasterTable(), and sqlite3VdbeExec().
#define NEVER (X) (X)
Definition at line 83 of file sqliteInt.h.
Referenced by codeAllEqualityTerms(), findTerm(), and sqlite3InvokeBusyHandler().
#define NULL_DISTINCT_FOR_UNIQUE 1
Definition at line 287 of file sqliteInt.h.
#define OE_Abort 2
Definition at line 1120 of file sqliteInt.h.
Referenced by resolveP2Values(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3VdbeExec(), sqlite3VdbeHalt(), sqlite3VdbeMakeReady(), xferOptimization(), and yy_reduce().
#define OE_Cascade 9
Definition at line 1128 of file sqliteInt.h.
Referenced by actionName(), and yy_reduce().
#define OE_Default 99
Definition at line 1130 of file sqliteInt.h.
Referenced by codeTriggerProgram(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3GenerateConstraintChecks(), sqlite3TriggerDeleteStep(), sqlite3TriggerSelectStep(), xferOptimization(), and yy_reduce().
#define OE_Fail 3
Definition at line 1121 of file sqliteInt.h.
Referenced by sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3VdbeHalt(), and yy_reduce().
#define OE_Ignore 4
Definition at line 1122 of file sqliteInt.h.
Referenced by sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), and yy_reduce().
#define OE_None 0
Definition at line 1118 of file sqliteInt.h.
Referenced by bestIndex(), isSortingIndex(), sqlite3CreateIndex(), sqlite3DefaultRowEst(), sqlite3FindInIndex(), sqlite3GenerateConstraintChecks(), sqlite3Pragma(), sqlite3RefillIndex(), xferOptimization(), and yy_reduce().
#define OE_Replace 5
Definition at line 1123 of file sqliteInt.h.
Referenced by sqlite3CreateIndex(), sqlite3GenerateConstraintChecks(), sqlite3Update(), and yy_reduce().
#define OE_Restrict 6
Definition at line 1125 of file sqliteInt.h.
Referenced by actionName(), and yy_reduce().
#define OE_Rollback 1
Definition at line 1119 of file sqliteInt.h.
Referenced by sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), xferOptimization(), and yy_reduce().
#define OE_SetDflt 8
Definition at line 1127 of file sqliteInt.h.
Referenced by actionName(), and yy_reduce().
#define OE_SetNull 7
Definition at line 1126 of file sqliteInt.h.
Referenced by actionName(), and yy_reduce().
#define offsetof (STRUCTURE, FIELD) ((int)((char*)&((STRUCTURE*)0)->FIELD))
Definition at line 313 of file sqliteInt.h.
Referenced by sqlite3VtabCommit(), and sqlite3VtabRollback().
#define OMIT_TEMPDB 0
Definition at line 272 of file sqliteInt.h.
Referenced by createTableStmt(), sqlite3BeginWriteOperation(), sqlite3CodeVerifySchema(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTrigger(), sqlite3FindDb(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3InitOne(), sqlite3Pragma(), and sqlite3StartTable().
#define OPFLAG_APPEND 8
Definition at line 1770 of file sqliteInt.h.
Referenced by analyzeOneTable(), autoIncEnd(), generateOutputSubroutine(), generateSortTail(), selectInnerLoop(), sqlite3CompleteInsertion(), sqlite3StartTable(), sqlite3VdbeExec(), and xferOptimization().
#define OPFLAG_ISUPDATE 4
Definition at line 1769 of file sqliteInt.h.
Referenced by sqlite3CompleteInsertion(), and sqlite3VdbeExec().
#define OPFLAG_LASTROWID 2
Definition at line 1768 of file sqliteInt.h.
Referenced by sqlite3CompleteInsertion(), sqlite3VdbeExec(), and xferOptimization().
#define OPFLAG_NCHANGE 1
Definition at line 1767 of file sqliteInt.h.
Referenced by sqlite3CompleteInsertion(), sqlite3GenerateRowDelete(), sqlite3VdbeExec(), and xferOptimization().
#define putVarint sqlite3PutVarint
Definition at line 2338 of file sqliteInt.h.
Referenced by appendVarint(), dlcAddDoclist(), dlwAdd(), dlwAppend(), fillInCell(), interiorBlockNew(), interiorWriterAppend(), leafWriterEncodeTerm(), leafWriterInlineFlush(), leafWriterStepMerge(), plwAdd(), plwInit(), and plwTerminate().
#define putVarint32 (A, B) (((B)<(u32)0x80) ? (*(A) = (unsigned char)(B)),1 : sqlite3PutVarint32((A), (B)))
Definition at line 2336 of file sqliteInt.h.
Referenced by sqlite3VdbeExec().
#define SCHEMA_TABLE (x) ((!OMIT_TEMPDB)&&(x==1)?TEMP_MASTER_NAME:MASTER_NAME)
Definition at line 439 of file sqliteInt.h.
Referenced by destroyRootPage(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3FinishTrigger(), sqlite3InitOne(), sqlite3OpenMasterTable(), sqlite3StartTable(), sqlite3VdbeExec(), and sqlite3VtabFinishParse().
#define SF_Aggregate 0x0004
Definition at line 1626 of file sqliteInt.h.
Referenced by flattenSubquery(), isCandidateForInOpt(), resolveSelectStep(), and sqlite3Select().
#define SF_Distinct 0x0001
Definition at line 1624 of file sqliteInt.h.
Referenced by flattenSubquery(), isCandidateForInOpt(), sqlite3Select(), sqlite3SelectNew(), and xferOptimization().
#define SF_Expanded 0x0010
Definition at line 1628 of file sqliteInt.h.
Referenced by resolveSelectStep(), and selectExpander().
#define SF_HasTypeInfo 0x0020
Definition at line 1629 of file sqliteInt.h.
Referenced by selectAddSubqueryTypeInfo(), and sqlite3SelectPrep().
#define SF_Resolved 0x0002
Definition at line 1625 of file sqliteInt.h.
Referenced by resolveSelectStep(), selectAddColumnTypeAndCollation(), and selectAddSubqueryTypeInfo().
#define SF_UsesEphemeral 0x0008
Definition at line 1627 of file sqliteInt.h.
Referenced by multiSelect(), and sqlite3SelectDup().
#define SMALLEST_INT64 (((i64)-1) - LARGEST_INT64)
Definition at line 405 of file sqliteInt.h.
Referenced by doubleToInt64(), and sqlite3VdbeExec().
#define sqlite3CloseExtensions (X)
Definition at line 2429 of file sqliteInt.h.
Referenced by sqlite3_close().
#define sqlite3ExprCheckHeight (x, y)
Definition at line 2515 of file sqliteInt.h.
Referenced by sqlite3PExpr(), and sqlite3ResolveExprNames().
#define sqlite3ExprSetHeight (x, y)
Definition at line 2513 of file sqliteInt.h.
Referenced by sqlite3ExprFunction(), and yy_reduce().
#define sqlite3GlobalConfig sqlite3Config
Definition at line 476 of file sqliteInt.h.
Referenced by mallocWithAlarm(), openDatabase(), sqlite3_config(), sqlite3_enable_shared_cache(), sqlite3_free(), sqlite3_initialize(), sqlite3_mutex_alloc(), sqlite3_mutex_enter(), sqlite3_mutex_free(), sqlite3_mutex_leave(), sqlite3_mutex_try(), sqlite3_shutdown(), sqlite3BtreeOpen(), sqlite3DbMallocSize(), sqlite3Malloc(), sqlite3MallocEnd(), sqlite3MallocInit(), sqlite3MallocSize(), sqlite3MutexAlloc(), sqlite3MutexEnd(), sqlite3MutexInit(), sqlite3PcacheInitialize(), sqlite3Realloc(), sqlite3ScratchFree(), and sqlite3ScratchMalloc().
#define sqlite3IsNumericAffinity (X) ((X)>=SQLITE_AFF_NUMERIC)
Definition at line 951 of file sqliteInt.h.
Referenced by sqlite3CompareAffinity(), and sqlite3IndexAffinityOk().
#define sqlite3JournalSize (pVfs) ((pVfs)->szOsFile)
Definition at line 2501 of file sqliteInt.h.
Referenced by sqlite3PagerOpen().
#define sqlite3SafetyOff (A) 0
Definition at line 2238 of file sqliteInt.h.
Referenced by attachFunc(), bestVirtualIndex(), sqlite3_blob_open(), sqlite3AnalysisLoad(), sqlite3InitOne(), sqlite3Prepare(), sqlite3Step(), sqlite3VdbeExec(), sqlite3VdbeFreeCursor(), sqlite3VdbeReset(), sqlite3VtabCallDestroy(), sqlite3VtabSync(), sqlite3VtabUnlock(), vdbeCommit(), and vtabCallConstructor().
#define sqlite3SafetyOn (A) 0
Definition at line 2237 of file sqliteInt.h.
Referenced by attachFunc(), bestVirtualIndex(), sqlite3_blob_open(), sqlite3AnalysisLoad(), sqlite3InitOne(), sqlite3Prepare(), sqlite3Step(), sqlite3VdbeExec(), sqlite3VdbeFreeCursor(), sqlite3VdbeReset(), sqlite3VtabCallDestroy(), sqlite3VtabSync(), sqlite3VtabUnlock(), vdbeCommit(), and vtabCallConstructor().
#define sqlite3SelectExprHeight (x) 0
Definition at line 2514 of file sqliteInt.h.
Referenced by sqlite3Select().
#define sqlite3VdbeIOTraceSql (X)
Definition at line 2540 of file sqliteInt.h.
Referenced by sqlite3VdbeExec().
#define SQLITE_AFF_INTEGER 'd'
Definition at line 948 of file sqliteInt.h.
Referenced by applyAffinity(), lookupName(), resolveExprStep(), sqlite3AffinityType(), sqlite3ExprAffinity(), and sqlite3ExprCodeTarget().
#define SQLITE_AFF_MASK 0x67
Definition at line 957 of file sqliteInt.h.
Referenced by codeCompare(), and sqlite3VdbeExec().
#define SQLITE_AFF_NONE 'b'
Definition at line 946 of file sqliteInt.h.
Referenced by applyAffinity(), codeCompare(), comparisonAffinity(), sqlite3AddColumn(), sqlite3AffinityType(), sqlite3AlterFinishAddColumn(), sqlite3CodeSubselect(), sqlite3CompareAffinity(), sqlite3ExprCodeTarget(), sqlite3FindInIndex(), sqlite3IndexAffinityOk(), sqlite3IndexAffinityStr(), and sqlite3ValueFromExpr().
#define SQLITE_AFF_NUMERIC 'c'
Definition at line 947 of file sqliteInt.h.
Referenced by applyAffinity(), sqlite3AffinityType(), sqlite3CompareAffinity(), sqlite3ExprCodeTarget(), sqlite3ValueFromExpr(), sqlite3VdbeExec(), and sqlite3WhereBegin().
#define SQLITE_AFF_REAL 'e'
Definition at line 949 of file sqliteInt.h.
Referenced by applyAffinity(), sqlite3AffinityType(), sqlite3ExprCodeGetColumn(), and sqlite3ExprCodeTarget().
#define SQLITE_AFF_TEXT 'a'
Definition at line 945 of file sqliteInt.h.
Referenced by applyAffinity(), sqlite3AffinityType(), sqlite3ExprCodeTarget(), sqlite3IndexAffinityOk(), and sqlite3VdbeExec().
#define SQLITE_ASCII 1
Definition at line 323 of file sqliteInt.h.
#define SQLITE_BIG_DBL (1e99)
Definition at line 261 of file sqliteInt.h.
Referenced by bestIndex(), bestVirtualIndex(), and sqlite3WhereBegin().
#define SQLITE_BIGENDIAN (*(char *)(&sqlite3one)==0)
Definition at line 394 of file sqliteInt.h.
#define SQLITE_COLL_BINARY 1
Definition at line 920 of file sqliteInt.h.
Referenced by isLikeOrGlob(), and openDatabase().
#define SQLITE_COLL_NOCASE 2
Definition at line 921 of file sqliteInt.h.
Referenced by isLikeOrGlob(), and openDatabase().
#define SQLITE_COLL_REVERSE 3
Definition at line 922 of file sqliteInt.h.
#define SQLITE_COLL_USER 0
Definition at line 923 of file sqliteInt.h.
#define SQLITE_CORRUPT_BKPT SQLITE_CORRUPT
Definition at line 2025 of file sqliteInt.h.
Referenced by accessPayload(), allocateBtreePage(), autoVacuumCommit(), clearCell(), clearDatabasePage(), decodeFlags(), defragmentPage(), dropCell(), getAndInitPage(), incrVacuumStep(), insertCell(), modifyPagePointer(), moveToChild(), pager_playback(), ptrmapGet(), ptrmapPut(), sqlite3BtreeInitPage(), sqlite3BtreeKey(), sqlite3BtreeMovetoUnpacked(), sqlite3PagerAcquire(), sqlite3VdbeExec(), and sqlite3VdbeIdxRowid().
#define SQLITE_CountRows 0x00000080
Definition at line 765 of file sqliteInt.h.
Referenced by flagPragma(), sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
#define SQLITE_DEFAULT_FILE_FORMAT 1
Definition at line 297 of file sqliteInt.h.
#define SQLITE_DEFAULT_MEMSTATUS 1
Definition at line 165 of file sqliteInt.h.
#define SQLITE_DYNAMIC ((sqlite3_destructor_type)sqlite3DbFree)
Definition at line 451 of file sqliteInt.h.
Referenced by generateColumnNames(), renameTableFunc(), renameTriggerFunc(), sqlite3Error(), sqlite3ValueFromExpr(), sqlite3VdbeMemSetStr(), sqlite3VdbeSetColName(), and strftimeFunc().
#define SQLITE_FAULTINJECTOR_COUNT 1
Definition at line 2476 of file sqliteInt.h.
#define SQLITE_FAULTINJECTOR_MALLOC 0
Definition at line 2475 of file sqliteInt.h.
#define SQLITE_FullColNames 0x00000020
Definition at line 763 of file sqliteInt.h.
Referenced by flagPragma(), generateColumnNames(), selectExpander(), and sqlite3ResultSetOfSelect().
#define SQLITE_FullFSync 0x00010000
Definition at line 778 of file sqliteInt.h.
Referenced by flagPragma(), and sqlite3Pragma().
#define SQLITE_FUNC_CASE 0x02
Definition at line 819 of file sqliteInt.h.
Referenced by sqlite3IsLikeFunction(), sqlite3RegisterGlobalFunctions(), and sqlite3RegisterLikeFunctions().
#define SQLITE_FUNC_EPHEM 0x04
Definition at line 820 of file sqliteInt.h.
Referenced by freeEphemeralFunction(), and sqlite3VtabOverloadFunction().
#define SQLITE_FUNC_LIKE 0x01
Definition at line 818 of file sqliteInt.h.
Referenced by sqlite3IsLikeFunction(), sqlite3RegisterGlobalFunctions(), and sqlite3RegisterLikeFunctions().
#define SQLITE_FUNC_NEEDCOLL 0x08
Definition at line 821 of file sqliteInt.h.
Referenced by sqlite3ExprCodeTarget(), sqlite3VdbeExec(), and updateAccumulator().
#define SQLITE_IgnoreChecks 0x00002000
Definition at line 775 of file sqliteInt.h.
Referenced by flagPragma(), sqlite3GenerateConstraintChecks(), and sqlite3RunVacuum().
#define SQLITE_INT_TO_PTR (X) ((void*)&((char*)0)[X])
Definition at line 114 of file sqliteInt.h.
Referenced by sqlite3_get_table(), sqlite3GenerateConstraintChecks(), sqlite3RefillIndex(), and sqlite3WhereBegin().
#define SQLITE_InternChanges 0x00000010
Definition at line 762 of file sqliteInt.h.
Referenced by sqlite3CommitInternalChanges(), sqlite3CreateIndex(), sqlite3EndTable(), sqlite3Init(), sqlite3ResetInternalSchema(), sqlite3RollbackAll(), sqlite3UnlinkAndDeleteIndex(), sqlite3UnlinkAndDeleteTable(), sqlite3UnlinkAndDeleteTrigger(), sqlite3VdbeExec(), and sqlite3VdbeHalt().
#define SQLITE_InTrans 0x00000008
Definition at line 761 of file sqliteInt.h.
Referenced by sqlite3OpenTempDatabase().
#define SQLITE_JUMPIFNULL 0x08
Definition at line 963 of file sqliteInt.h.
Referenced by analyzeOneTable(), autoIncBegin(), sqlite3CodeRowTrigger(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3GenerateConstraintChecks(), sqlite3Select(), sqlite3VdbeExec(), and sqlite3WhereBegin().
#define SQLITE_LegacyFileFmt 0x00008000
Definition at line 777 of file sqliteInt.h.
Referenced by flagPragma(), openDatabase(), sqlite3InitOne(), and sqlite3StartTable().
#define SQLITE_LITTLEENDIAN (*(char *)(&sqlite3one)==1)
Definition at line 395 of file sqliteInt.h.
#define SQLITE_LoadExtension 0x00020000
Definition at line 779 of file sqliteInt.h.
Referenced by openDatabase(), sqlite3_enable_load_extension(), and sqlite3LoadExtension().
#define SQLITE_MAGIC_BUSY 0xf03b7906
Definition at line 793 of file sqliteInt.h.
Referenced by openDatabase(), sqlite3SafetyCheckOk(), sqlite3SafetyCheckSickOrOk(), sqlite3VdbeExec(), sqlite3VdbeList(), and sqlite3VtabUnlock().
#define SQLITE_MAGIC_CLOSED 0x9f3c2d33
Definition at line 791 of file sqliteInt.h.
Referenced by sqlite3_close().
#define SQLITE_MAGIC_ERROR 0xb5357930
Definition at line 794 of file sqliteInt.h.
Referenced by sqlite3_close().
#define SQLITE_MAGIC_OPEN 0xa029a697
Definition at line 790 of file sqliteInt.h.
Referenced by openDatabase(), sqlite3SafetyCheckOk(), and sqlite3SafetyCheckSickOrOk().
#define SQLITE_MAGIC_SICK 0x4b771290
Definition at line 792 of file sqliteInt.h.
Referenced by openDatabase(), and sqlite3SafetyCheckSickOrOk().
#define SQLITE_MAX_FILE_FORMAT 4
Definition at line 295 of file sqliteInt.h.
Referenced by sqlite3InitOne(), and sqlite3StartTable().
#define SQLITE_N_LIMIT (SQLITE_LIMIT_VARIABLE_NUMBER+1)
Definition at line 602 of file sqliteInt.h.
Referenced by sqlite3_limit().
#define SQLITE_NoReadlock 0x00001000
Definition at line 773 of file sqliteInt.h.
Referenced by flagPragma(), and sqlite3BtreeFactory().
#define SQLITE_NullCallback 0x00000100
Definition at line 768 of file sqliteInt.h.
Referenced by flagPragma(), and sqlite3_exec().
#define SQLITE_PTR_TO_INT (X) ((int)(((char*)X)-(char*)0))
Definition at line 115 of file sqliteInt.h.
Referenced by detectLockingStyle(), sqlite3_free_table(), sqlite3ValueText(), sqlite3VdbeChangeP4(), and trimFunc().
#define SQLITE_ReadUncommitted 0x00004000
Definition at line 776 of file sqliteInt.h.
Referenced by checkReadLocks(), flagPragma(), lockTable(), and queryTableLock().
#define SQLITE_RecoveryMode 0x00040000
Definition at line 781 of file sqliteInt.h.
Referenced by corruptSchema(), flagPragma(), and sqlite3InitOne().
#define SQLITE_SharedCache 0x00080000
Definition at line 782 of file sqliteInt.h.
Referenced by sqlite3BtreeOpen(), and sqlite3VtabBeginParse().
#define SQLITE_ShortColNames 0x00000040
Definition at line 764 of file sqliteInt.h.
Referenced by flagPragma(), generateColumnNames(), openDatabase(), selectExpander(), and sqlite3ResultSetOfSelect().
#define SQLITE_SKIP_UTF8 (zIn)
Value:
{                        \
  if( (*(zIn++))>=0xc0 ){                              \
    while( (*zIn & 0xc0)==0x80 ){ zIn++; }             \
  }                                                    \
}
Definition at line 2009 of file sqliteInt.h.
Referenced by lengthFunc(), patternCompare(), sqlite3Utf8CharLen(), substrFunc(), and trimFunc().
#define SQLITE_SO_ASC 0
Definition at line 928 of file sqliteInt.h.
Referenced by sqlite3AddPrimaryKey(), sqlite3WhereBegin(), and yy_reduce().
#define SQLITE_SO_DESC 1
Definition at line 929 of file sqliteInt.h.
Referenced by yy_reduce().
#define SQLITE_SqlTrace 0x00000200
Definition at line 770 of file sqliteInt.h.
Referenced by flagPragma(), and sqlite3VdbeExec().
#define SQLITE_STOREP2 0x10
Definition at line 964 of file sqliteInt.h.
Referenced by sqlite3ExprCodeTarget(), and sqlite3VdbeExec().
#define SQLITE_SYSTEM_MALLOC 1
Definition at line 191 of file sqliteInt.h.
#define SQLITE_TEMP_STORE 1
Definition at line 305 of file sqliteInt.h.
Referenced by sqlite3Pragma().
#define SQLITE_UTF16NATIVE (SQLITE_BIGENDIAN?SQLITE_UTF16BE:SQLITE_UTF16LE)
Definition at line 396 of file sqliteInt.h.
Referenced by callCollNeeded(), createCollation(), sqlite3_bind_text16(), sqlite3_complete16(), sqlite3_errmsg16(), sqlite3_open16(), sqlite3_result_error16(), sqlite3_result_text16(), sqlite3_value_bytes16(), sqlite3_value_text16(), sqlite3CreateFunc(), sqlite3Pragma(), sqlite3Utf16ByteLen(), and sqlite3Utf16to8().
#define SQLITE_VdbeListing 0x00000400
Definition at line 771 of file sqliteInt.h.
Referenced by flagPragma(), and sqlite3VdbeExec().
#define SQLITE_VdbeTrace 0x00000001
Definition at line 760 of file sqliteInt.h.
Referenced by flagPragma(), and sqlite3FinishCoding().
#define SQLITE_Vtab 0x00100000
Definition at line 783 of file sqliteInt.h.
Referenced by sqlite3BtreeOpen().
#define SQLITE_WriteSchema 0x00000800
Definition at line 772 of file sqliteInt.h.
Referenced by flagPragma(), sqlite3CheckObjectName(), sqlite3IsReadOnly(), and sqlite3RunVacuum().
#define SQLITE_WSD
Definition at line 474 of file sqliteInt.h.
Referenced by sqlite3RegisterDateTimeFunctions(), and sqlite3RegisterGlobalFunctions().
#define SRT_Coroutine 10
Definition at line 1649 of file sqliteInt.h.
Referenced by generateOutputSubroutine(), generateSortTail(), multiSelectOrderBy(), selectInnerLoop(), and sqlite3Insert().
#define SRT_Discard 4
Definition at line 1639 of file sqliteInt.h.
Referenced by codeTriggerProgram(), selectInnerLoop(), and sqlite3Select().
#define SRT_EphemTab 9
Definition at line 1648 of file sqliteInt.h.
Referenced by generateOutputSubroutine(), generateSortTail(), multiSelect(), selectInnerLoop(), sqlite3MaterializeView(), and sqlite3Select().
#define SRT_Except 2
Definition at line 1637 of file sqliteInt.h.
Referenced by multiSelect(), selectInnerLoop(), and sqlite3Select().
#define SRT_Exists 3
Definition at line 1638 of file sqliteInt.h.
Referenced by generateOutputSubroutine(), selectInnerLoop(), sqlite3CodeSubselect(), and sqlite3Select().
#define SRT_Mem 6
Definition at line 1645 of file sqliteInt.h.
Referenced by checkForMultiColumnSelectError(), generateOutputSubroutine(), generateSortTail(), selectInnerLoop(), and sqlite3CodeSubselect().
#define SRT_Output 5
Definition at line 1644 of file sqliteInt.h.
Referenced by generateOutputSubroutine(), generateSortTail(), multiSelect(), multiSelectOrderBy(), selectInnerLoop(), sqlite3Select(), and yy_reduce().
#define SRT_Set 7
Definition at line 1646 of file sqliteInt.h.
Referenced by checkForMultiColumnSelectError(), generateOutputSubroutine(), generateSortTail(), selectInnerLoop(), and sqlite3CodeSubselect().
#define SRT_Table 8
Definition at line 1647 of file sqliteInt.h.
Referenced by generateOutputSubroutine(), generateSortTail(), multiSelect(), selectInnerLoop(), sqlite3EndTable(), and updateVirtualTable().
#define SRT_Union 1
Definition at line 1636 of file sqliteInt.h.
Referenced by multiSelect(), selectInnerLoop(), and sqlite3Select().
#define STR_FUNCTION (zName, nArg, pArg, bNC, xFunc) {nArg, SQLITE_UTF8, bNC*8, pArg, 0, xFunc, 0, 0, #zName}
Definition at line 850 of file sqliteInt.h.
Referenced by sqlite3RegisterDateTimeFunctions().
#define TEMP_MASTER_NAME "sqlite_temp_master"
Definition at line 429 of file sqliteInt.h.
#define testcase (X)
Definition at line 62 of file sqliteInt.h.
Referenced by analyzeAggregate(), bestVirtualIndex(), codeAllEqualityTerms(), exprNodeIsConstant(), isAppropriateForFactoring(), lookupName(), sqlite3BtreeDelete(), sqlite3ExprAssignVarNumber(), sqlite3ExprClearColumnCache(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3ExprListCheckLength(), and sqlite3WhereBegin().
#define TF_Autoincrement 0x08
Definition at line 1033 of file sqliteInt.h.
Referenced by autoIncBegin(), autoIncEnd(), sqlite3AddPrimaryKey(), sqlite3DropTable(), sqlite3EndTable(), and xferOptimization().
#define TF_Ephemeral 0x02
Definition at line 1031 of file sqliteInt.h.
Referenced by selectAddSubqueryTypeInfo(), selectExpander(), sqlite3WhereBegin(), and sqlite3WhereEnd().
#define TF_HasPrimaryKey 0x04
Definition at line 1032 of file sqliteInt.h.
Referenced by sqlite3AddPrimaryKey().
#define TF_NeedMetadata 0x20
Definition at line 1035 of file sqliteInt.h.
#define TF_Readonly 0x01
Definition at line 1030 of file sqliteInt.h.
Referenced by sqlite3InitOne(), and sqlite3IsReadOnly().
#define TF_Virtual 0x10
Definition at line 1034 of file sqliteInt.h.
Referenced by sqlite3_declare_vtab(), sqlite3VtabBeginParse(), sqlite3VtabCallConnect(), sqlite3VtabCallCreate(), sqlite3VtabOverloadFunction(), and xferOptimization().
#define TRIGGER_AFTER 2
Definition at line 1810 of file sqliteInt.h.
Referenced by sqlite3BeginTrigger(), sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
#define TRIGGER_BEFORE 1
Definition at line 1809 of file sqliteInt.h.
Referenced by sqlite3BeginTrigger(), sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
#define UINT16_TYPE uint16_t
Definition at line 342 of file sqliteInt.h.
#define UINT32_TYPE uint32_t
Definition at line 335 of file sqliteInt.h.
#define UINT8_TYPE uint8_t
Definition at line 356 of file sqliteInt.h.
#define unlikely (X) !!(X)
Definition at line 97 of file sqliteInt.h.
#define UNPACKED_IGNORE_ROWID 0x0004
Definition at line 1172 of file sqliteInt.h.
Referenced by sqlite3VdbeExec(), sqlite3VdbeIdxKeyCompare(), and sqlite3VdbeRecordCompare().
#define UNPACKED_INCRKEY 0x0008
Definition at line 1173 of file sqliteInt.h.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeRecordCompare().
#define UNPACKED_NEED_DESTROY 0x0002
Definition at line 1171 of file sqliteInt.h.
Referenced by sqlite3VdbeDeleteUnpackedRecord(), and sqlite3VdbeRecordUnpack().
#define UNPACKED_NEED_FREE 0x0001
Definition at line 1170 of file sqliteInt.h.
Referenced by sqlite3VdbeDeleteUnpackedRecord(), and sqlite3VdbeRecordUnpack().
#define UNPACKED_PREFIX_MATCH 0x0010
Definition at line 1174 of file sqliteInt.h.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeRecordCompare().
#define WHERE_ONEPASS_DESIRED 4
Definition at line 1525 of file sqliteInt.h.
Referenced by sqlite3Update(), and sqlite3WhereBegin().
#define WHERE_ORDERBY_MAX 2
Definition at line 1524 of file sqliteInt.h.
Referenced by minMaxQuery().
#define WHERE_ORDERBY_MIN 1
Definition at line 1523 of file sqliteInt.h.
Referenced by minMaxQuery(), sqlite3Select(), and sqlite3WhereBegin().
#define WHERE_ORDERBY_NORMAL 0
Definition at line 1522 of file sqliteInt.h.
Referenced by minMaxQuery().
#define WRC_Abort 2
Definition at line 2003 of file sqliteInt.h.
Referenced by exprNodeIsConstant(), resolveExprStep(), resolveSelectStep(), selectExpander(), selectNodeIsConstant(), sqlite3WalkExpr(), sqlite3WalkExprList(), sqlite3WalkSelect(), sqlite3WalkSelectExpr(), and sqlite3WalkSelectFrom().
#define WRC_Continue 0
Definition at line 2001 of file sqliteInt.h.
Referenced by analyzeAggregate(), analyzeAggregatesInSelect(), evalConstExpr(), exprNodeIsConstant(), exprWalkNoop(), resolveExprStep(), selectAddSubqueryTypeInfo(), selectExpander(), sqlite3WalkExpr(), sqlite3WalkExprList(), sqlite3WalkSelect(), sqlite3WalkSelectExpr(), and sqlite3WalkSelectFrom().
#define WRC_Prune 1
Definition at line 2002 of file sqliteInt.h.
Referenced by analyzeAggregate(), analyzeAggregatesInSelect(), evalConstExpr(), resolveExprStep(), resolveSelectStep(), and selectExpander().
Typedef Documentation
typedef struct AggInfo AggInfo
Definition at line 482 of file sqliteInt.h.
typedef struct AuthContext AuthContext
Definition at line 483 of file sqliteInt.h.
typedef u64 Bitmask
Definition at line 1422 of file sqliteInt.h.
typedef struct Bitvec Bitvec
Definition at line 484 of file sqliteInt.h.
typedef struct BusyHandler BusyHandler
Definition at line 416 of file sqliteInt.h.
typedef struct CollSeq CollSeq
Definition at line 485 of file sqliteInt.h.
typedef struct Column Column
Definition at line 486 of file sqliteInt.h.
typedef struct Db Db
Definition at line 487 of file sqliteInt.h.
typedef struct DbFixer DbFixer
Definition at line 1910 of file sqliteInt.h.
typedef struct Expr Expr
Definition at line 489 of file sqliteInt.h.
typedef struct ExprList ExprList
Definition at line 490 of file sqliteInt.h.
typedef struct FKey FKey
Definition at line 491 of file sqliteInt.h.
typedef struct FuncDef FuncDef
Definition at line 492 of file sqliteInt.h.
typedef struct FuncDefHash FuncDefHash
Definition at line 493 of file sqliteInt.h.
typedef INT16_TYPE i16
Definition at line 375 of file sqliteInt.h.
typedef sqlite_int64 i64
Definition at line 371 of file sqliteInt.h.
typedef INT8_TYPE i8
Definition at line 377 of file sqliteInt.h.
typedef struct IdList IdList
Definition at line 494 of file sqliteInt.h.
typedef struct Index Index
Definition at line 495 of file sqliteInt.h.
typedef struct KeyClass KeyClass
Definition at line 496 of file sqliteInt.h.
typedef struct KeyInfo KeyInfo
Definition at line 497 of file sqliteInt.h.
typedef struct Lookaside Lookaside
Definition at line 498 of file sqliteInt.h.
typedef struct LookasideSlot LookasideSlot
Definition at line 499 of file sqliteInt.h.
typedef struct Module Module
Definition at line 500 of file sqliteInt.h.
typedef struct NameContext NameContext
Definition at line 501 of file sqliteInt.h.
typedef struct Parse Parse
Definition at line 502 of file sqliteInt.h.
typedef struct Schema Schema
Definition at line 488 of file sqliteInt.h.
typedef struct Select Select
Definition at line 503 of file sqliteInt.h.
typedef struct SelectDest SelectDest
Definition at line 1655 of file sqliteInt.h.
typedef struct SrcList SrcList
Definition at line 504 of file sqliteInt.h.
typedef struct StrAccum StrAccum
Definition at line 505 of file sqliteInt.h.
typedef struct Table Table
Definition at line 506 of file sqliteInt.h.
typedef struct TableLock TableLock
Definition at line 507 of file sqliteInt.h.
typedef struct Token Token
Definition at line 508 of file sqliteInt.h.
typedef struct Trigger Trigger
Definition at line 511 of file sqliteInt.h.
typedef struct TriggerStack TriggerStack
Definition at line 509 of file sqliteInt.h.
typedef struct TriggerStep TriggerStep
Definition at line 510 of file sqliteInt.h.
typedef UINT16_TYPE u16
Definition at line 374 of file sqliteInt.h.
typedef UINT32_TYPE u32
Definition at line 373 of file sqliteInt.h.
typedef sqlite_uint64 u64
Definition at line 372 of file sqliteInt.h.
typedef UINT8_TYPE u8
Definition at line 376 of file sqliteInt.h.
typedef struct UnpackedRecord UnpackedRecord
Definition at line 512 of file sqliteInt.h.
typedef struct Walker Walker
Definition at line 513 of file sqliteInt.h.
typedef struct WhereInfo WhereInfo
Definition at line 514 of file sqliteInt.h.
typedef struct WhereLevel WhereLevel
Definition at line 515 of file sqliteInt.h.
Function Documentation
void sqlite3AddCheckConstraint (Parse * , Expr *)
Definition at line 1192 of file build.c.
References Parse::db, db, IN_DECLARE_VTAB, Table::pCheck, Parse::pNewTable, sqlite3ExprAnd(), sqlite3ExprDelete(), and sqlite3ExprDup().
Referenced by yy_reduce().
void sqlite3AddCollateType (Parse * , Token *)
Definition at line 1214 of file build.c.
References Table::aCol, Index::aiColumn, Index::azColl, Parse::db, db, Table::nCol, Index::nColumn, Table::pIndex, Parse::pNewTable, Index::pNext, sqlite3DbFree(), sqlite3LocateCollSeq(), sqlite3NameFromToken(), and Column::zColl.
Referenced by yy_reduce().
void sqlite3AddColumn (Parse * , Token *)
Definition at line 938 of file build.c.
References Table::aCol, Column::affinity, sqlite3::aLimit, Parse::db, db, Table::nCol, Parse::pNewTable, sqlite3DbFree(), sqlite3DbRealloc(), sqlite3ErrorMsg(), sqlite3NameFromToken(), SQLITE_AFF_NONE, SQLITE_LIMIT_COLUMN, STRICMP, Column::zName, and Table::zName.
Referenced by yy_reduce().
void sqlite3AddColumnType (Parse * , Token *)
Definition at line 1067 of file build.c.
References Table::aCol, Column::affinity, Parse::db, db, Table::nCol, Parse::pNewTable, sqlite3AffinityType(), sqlite3DbFree(), sqlite3NameFromToken(), and Column::zType.
Referenced by yy_reduce().
void sqlite3AddDefaultValue (Parse * , Expr *)
Definition at line 1093 of file build.c.
References Table::aCol, Parse::db, db, Table::nCol, Column::pDflt, Parse::pNewTable, Expr::span, sqlite3ErrorMsg(), sqlite3ExprDelete(), sqlite3ExprDup(), sqlite3ExprIsConstantOrFunction(), sqlite3TokenCopy(), and Column::zName.
Referenced by yy_reduce().
void sqlite3AddNotNull (Parse * , int)
Definition at line 987 of file build.c.
References Table::aCol, Table::nCol, Column::notNull, and Parse::pNewTable.
Referenced by yy_reduce().
void sqlite3AddPrimaryKey (Parse * , ExprList * , int , int , int)
Definition at line 1132 of file build.c.
References ExprList::a, Table::aCol, Parse::db, IN_DECLARE_VTAB, Table::iPKey, Column::isPrimKey, Table::keyConf, Table::nCol, ExprList::nExpr, Parse::pNewTable, sqlite3CreateIndex(), sqlite3ErrorMsg(), sqlite3ExprListDelete(), sqlite3StrICmp(), SQLITE_SO_ASC, Table::tabFlags, TF_Autoincrement, TF_HasPrimaryKey, Column::zName, ExprList::ExprList_item::zName, Table::zName, and Column::zType.
Referenced by yy_reduce().
char sqlite3AffinityType (const Token *)
Definition at line 1020 of file build.c.
References Token::n, sqlite3UpperToLower, SQLITE_AFF_INTEGER, SQLITE_AFF_NONE, SQLITE_AFF_NUMERIC, SQLITE_AFF_REAL, SQLITE_AFF_TEXT, and Token::z.
Referenced by sqlite3AddColumnType(), sqlite3ExprAffinity(), and sqlite3ExprCodeTarget().
void sqlite3AlterBeginAddColumn (Parse * , SrcList *)
Definition at line 549 of file alter.c.
References SrcList::a, Table::aCol, sqlite3::aDb, Table::addColOffset, Table::db, Parse::db, db, IsVirtual, sqlite3::mallocFailed, Table::nCol, Table::nRef, Column::pDflt, Parse::pNewTable, Db::pSchema, Table::pSchema, Table::pSelect, sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3DbMallocZero(), sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3GetVdbe(), sqlite3LocateTable(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), Column::zColl, SrcList::SrcList_item::zDatabase, Column::zName, Table::zName, SrcList::SrcList_item::zName, and Column::zType.
Referenced by yy_reduce().
void sqlite3AlterFinishAddColumn (Parse * , Token *)
Definition at line 433 of file alter.c.
References Table::aCol, sqlite3::aDb, Table::addColOffset, Parse::db, db, Column::isPrimKey, sqlite3::mallocFailed, Token::n, Table::nCol, Parse::nErr, Column::notNull, Expr::op, Column::pDflt, Table::pIndex, Parse::pNewTable, Table::pSchema, reloadTableSchema(), SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3DbFree(), sqlite3DbStrNDup(), sqlite3ErrorMsg(), sqlite3FindTable(), sqlite3MinimumFileFormat(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3ValueFree(), sqlite3ValueFromExpr(), SQLITE_AFF_NONE, SQLITE_ALTER_TABLE, SQLITE_UTF8, TK_NULL, Token::z, Table::zName, and Db::zName.
Referenced by yy_reduce().
void sqlite3AlterFunctions (sqlite3 *)
Definition at line 166 of file alter.c.
References renameTableFunc(), renameTriggerFunc(), sqlite3CreateFunc(), and SQLITE_UTF8.
Referenced by sqlite3RegisterBuiltinFunctions().
void sqlite3AlterRenameTable (Parse * , SrcList * , Token *)
Definition at line 262 of file alter.c.
References SrcList::a, sqlite3::aDb, Parse::db, db, IsVirtual, sqlite3::mallocFailed, Parse::nMem, SrcList::nSrc, OP_String8, OP_VRename, P4_VTAB, Table::pMod, Module::pModule, Table::pSchema, Table::pSelect, Table::pVtab, reloadTableSchema(), SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3LocateTable(), sqlite3NameFromToken(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3StrNICmp(), sqlite3Utf8CharLen(), sqlite3VdbeAddOp4(), sqlite3ViewGetColumnNames(), SQLITE_ALTER_TABLE, SQLITE_OK, whereTempTriggers(), sqlite3_module::xRename, SrcList::SrcList_item::zDatabase, Table::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
int sqlite3AnalysisLoad (sqlite3 * , int iDB)
Definition at line 390 of file analyze.c.
References sqlite3::aDb, analysisLoader(), analysisInfo::db, Schema::idxHash, Db::pBt, Db::pSchema, sqlite3_exec(), sqlite3DbFree(), sqlite3DefaultRowEst(), sqlite3FindTable(), sqlite3MPrintf(), sqlite3SafetyOff, sqlite3SafetyOn, SQLITE_ERROR, sqliteHashData, sqliteHashFirst, sqliteHashNext, analysisInfo::zDatabase, and Db::zName.
Referenced by sqlite3InitOne(), and sqlite3VdbeExec().
void sqlite3Analyze (Parse * , Token * , Token *)
Definition at line 289 of file analyze.c.
References sqlite3::aDb, analyzeDatabase(), analyzeTable(), Parse::db, db, Token::n, sqlite3::nDb, sqlite3DbFree(), sqlite3FindDb(), sqlite3LocateTable(), sqlite3NameFromToken(), sqlite3ReadSchema(), sqlite3TwoPartName(), SQLITE_OK, and Db::zName.
Referenced by yy_reduce().
int sqlite3ApiExit (sqlite3 * db, int)
Definition at line 775 of file malloc.c.
References sqlite3::errMask, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_held, sqlite3Error(), SQLITE_IOERR_NOMEM, and SQLITE_NOMEM.
Referenced by bindText(), blobReadWrite(), columnMallocFailure(), createModule(), openDatabase(), sqlite3_bind_value(), sqlite3_blob_open(), sqlite3_complete16(), sqlite3_create_collation(), sqlite3_create_collation16(), sqlite3_create_collation_v2(), sqlite3_create_function(), sqlite3_create_function16(), sqlite3_declare_vtab(), sqlite3_exec(), sqlite3_open16(), sqlite3_overload_function(), sqlite3_step(), sqlite3Prepare(), sqlite3Prepare16(), and sqlite3Step().
void* sqlite3ArrayAllocate (sqlite3 * , void * , int , int , int * , int * , int *)
Definition at line 2909 of file build.c.
References sqlite3DbRealloc().
Referenced by addAggInfoColumn(), addAggInfoFunc(), and sqlite3IdListAppend().
int sqlite3AtoF (const char * z, double *)
Definition at line 252 of file util.c.
References LONGDOUBLE_TYPE, and sqlite3Atoi64().
Referenced by codeReal(), roundFunc(), and sqlite3VdbeRealValue().
int sqlite3Atoi64 (const char * , i64 *)
Definition at line 357 of file util.c.
References compare2pow63().
Referenced by applyNumericAffinity(), codeInteger(), sqlite3AtoF(), and sqlite3VdbeIntValue().
void sqlite3Attach (Parse * , Expr * , Expr * , Expr *)
Definition at line 376 of file attach.c.
References attachFunc(), codeAttach(), SQLITE_ATTACH, and SQLITE_UTF8.
Referenced by yy_reduce().
int sqlite3AuthCheck (Parse * , int , const char * , const char * , const char *)
Definition at line 175 of file auth.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, IN_DECLARE_VTAB, sqlite3::init, sqlite3::pAuthArg, Parse::rc, sqlite3ErrorMsg(), SQLITE_AUTH, SQLITE_DENY, SQLITE_IGNORE, SQLITE_OK, sqliteAuthBadReturnCode(), sqlite3::xAuth, and Parse::zAuthContext.
Referenced by analyzeOneTable(), codeAttach(), flattenSubquery(), resolveExprStep(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTransaction(), sqlite3BeginTrigger(), sqlite3CommitTransaction(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3Insert(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3RollbackTransaction(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), and sqlite3VtabBeginParse().
void sqlite3AuthContextPop (AuthContext *)
Definition at line 227 of file auth.c.
References AuthContext::pParse, AuthContext::zAuthContext, and Parse::zAuthContext.
Referenced by sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), and sqlite3Update().
void sqlite3AuthContextPush (Parse * , AuthContext * , const char *)
Definition at line 211 of file auth.c.
References AuthContext::pParse, Parse::zAuthContext, and AuthContext::zAuthContext.
Referenced by sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), and sqlite3Update().
void sqlite3AuthRead (Parse * , Expr * , Schema * , SrcList *)
Definition at line 105 of file auth.c.
References SrcList::a, Table::aCol, sqlite3::aDb, Parse::db, Expr::iColumn, SrcList::SrcList_item::iCursor, Table::iPKey, Expr::iTable, Table::nCol, sqlite3::nDb, TriggerStack::newIdx, SrcList::nSrc, TriggerStack::oldIdx, Expr::op, sqlite3::pAuthArg, TriggerStack::pTab, SrcList::SrcList_item::pTab, Parse::rc, sqlite3ErrorMsg(), sqlite3SchemaToIndex(), SQLITE_AUTH, SQLITE_DENY, SQLITE_IGNORE, SQLITE_OK, SQLITE_READ, sqliteAuthBadReturnCode(), TK_COLUMN, TK_NULL, Parse::trigStack, sqlite3::xAuth, Parse::zAuthContext, Table::zName, Db::zName, and Column::zName.
Referenced by lookupName().
int sqlite3AutoLoadExtensions (sqlite3 *)
Definition at line 570 of file loadext.c.
References sqlite3_free(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3Error(), sqlite3MutexAlloc, SQLITE_ERROR, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
Referenced by openDatabase().
void sqlite3BeginBenignMalloc (void)
Definition at line 78 of file fault.c.
References wsdHooks, and wsdHooksInit.
Referenced by pagerUnlockAndRollback(), rehash(), setupLookaside(), sqlite3BitvecSet(), sqlite3PagerClose(), sqlite3RollbackAll(), sqlite3VdbeExec(), sqlite3VdbeReset(), and vdbeCommit().
void sqlite3BeginParse (Parse * , int)
Definition at line 34 of file build.c.
References Parse::explain, and Parse::nVar.
Referenced by yy_reduce().
void sqlite3BeginTransaction (Parse * , int)
Definition at line 3249 of file build.c.
References sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, sqlite3::nDb, Parse::nErr, OP_AutoCommit, OP_Transaction, Db::pBt, sqlite3AuthCheck(), sqlite3GetVdbe(), sqlite3VdbeAddOp2(), sqlite3VdbeUsesBtree(), SQLITE_TRANSACTION, TK_DEFERRED, and TK_EXCLUSIVE.
Referenced by yy_reduce().
void sqlite3BeginTrigger (Parse * , Token * , Token * , int , int , IdList * , SrcList * , Expr * , int , int)
Definition at line 44 of file trigger.c.
References SrcList::a, sqlite3::aDb, Parse::db, db, IsVirtual, sqlite3::mallocFailed, Token::n, Trigger::name, Trigger::nameToken, Parse::nErr, SrcList::nSrc, Trigger::op, Trigger::pColumns, Parse::pNewTrigger, Trigger::pSchema, Db::pSchema, Table::pSchema, Table::pSelect, Trigger::pTabSchema, Trigger::pWhen, SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DbStrDup(), sqlite3DeleteTrigger(), sqlite3ErrorMsg(), sqlite3ExprDelete(), sqlite3ExprDup(), sqlite3FixInit(), sqlite3FixSrcList(), sqlite3HashFind(), sqlite3IdListDelete(), sqlite3IdListDup(), sqlite3NameFromToken(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StrNICmp(), sqlite3TokenCopy(), sqlite3TwoPartName(), SQLITE_CREATE_TEMP_TRIGGER, SQLITE_CREATE_TRIGGER, SQLITE_INSERT, SQLITE_OK, Trigger::table, TK_BEFORE, TK_INSTEAD, Trigger::tr_tm, TRIGGER_AFTER, TRIGGER_BEFORE, Schema::trigHash, SrcList::SrcList_item::zName, Db::zName, and Table::zName.
Referenced by yy_reduce().
void sqlite3BeginWriteOperation (Parse * , int , int)
Definition at line 3400 of file build.c.
References sqlite3::aDb, Parse::db, Parse::nested, OMIT_TEMPDB, OP_Statement, Db::pBt, sqlite3BeginWriteOperation(), sqlite3CodeVerifySchema(), sqlite3GetVdbe(), sqlite3VdbeAddOp1(), and Parse::writeMask.
Referenced by analyzeDatabase(), analyzeTable(), reindexTable(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginWriteOperation(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3FinishTrigger(), sqlite3Insert(), sqlite3Pragma(), sqlite3Reindex(), sqlite3StartTable(), and sqlite3Update().
void sqlite3BenignMallocHooks (void(*)(void) , void(*)(void))
Definition at line 64 of file fault.c.
References wsdHooks, and wsdHooksInit.
Referenced by sqlite3_test_control().
CollSeq* sqlite3BinaryCompareCollSeq (Parse * , Expr * , Expr *)
Definition at line 209 of file expr.c.
References EP_ExpCollate, Expr::flags, Expr::pColl, and sqlite3ExprCollSeq().
Referenced by codeCompare(), findTerm(), sqlite3CodeSubselect(), and sqlite3FindInIndex().
int sqlite3BitvecBuiltinTest (int , int *)
Definition at line 269 of file bitvec.c.
References CLEARBIT, SETBIT, sqlite3_free(), sqlite3_malloc(), sqlite3_randomness(), sqlite3BitvecClear(), sqlite3BitvecCreate(), sqlite3BitvecDestroy(), sqlite3BitvecSet(), sqlite3BitvecTest(), and TESTBIT.
Referenced by sqlite3_test_control().
void sqlite3BitvecClear (Bitvec * , u32)
Definition at line 188 of file bitvec.c.
References Bitvec::aBitmap, Bitvec::aHash, Bitvec::apSub, BITVEC_NBIT, BITVEC_NINT, Bitvec::iDivisor, Bitvec::iSize, Bitvec::nSet, sqlite3BitvecClear(), sqlite3BitvecSet(), and Bitvec::u.
Referenced by sqlite3BitvecBuiltinTest(), sqlite3BitvecClear(), and sqlite3PagerMovepage().
Bitvec* sqlite3BitvecCreate (u32)
Definition at line 90 of file bitvec.c.
References BITVEC_SZ, Bitvec::iSize, and sqlite3MallocZero().
Referenced by pager_open_journal(), pagerStmtBegin(), sqlite3BitvecBuiltinTest(), sqlite3BitvecSet(), sqlite3PagerBegin(), and sqlite3PagerDontWrite().
void sqlite3BitvecDestroy (Bitvec *)
Definition at line 217 of file bitvec.c.
References Bitvec::apSub, BITVEC_NPTR, Bitvec::iDivisor, sqlite3_free(), sqlite3BitvecDestroy(), and Bitvec::u.
Referenced by pager_end_transaction(), pager_open_journal(), pager_unlock(), pagerStmtBegin(), sqlite3BitvecBuiltinTest(), sqlite3BitvecDestroy(), sqlite3PagerClose(), and sqlite3PagerStmtCommit().
int sqlite3BitvecSet (Bitvec * , u32)
Definition at line 139 of file bitvec.c.
References Bitvec::aBitmap, Bitvec::aHash, Bitvec::apSub, BITVEC_HASH, BITVEC_MXHASH, BITVEC_NBIT, BITVEC_NINT, BITVEC_NPTR, Bitvec::iDivisor, Bitvec::iSize, Bitvec::nSet, sqlite3BeginBenignMalloc(), sqlite3BitvecCreate(), sqlite3BitvecSet(), sqlite3EndBenignMalloc(), SQLITE_NOMEM, SQLITE_OK, and Bitvec::u.
Referenced by pager_write(), sqlite3BitvecBuiltinTest(), sqlite3BitvecClear(), sqlite3BitvecSet(), sqlite3PagerDontRollback(), and sqlite3PagerDontWrite().
int sqlite3BitvecTest (Bitvec * , u32)
Definition at line 105 of file bitvec.c.
References Bitvec::aBitmap, Bitvec::aHash, Bitvec::apSub, BITVEC_HASH, BITVEC_NBIT, BITVEC_NINT, Bitvec::iDivisor, Bitvec::iSize, sqlite3BitvecTest(), and Bitvec::u.
Referenced by pageInStatement(), sqlite3BitvecBuiltinTest(), sqlite3BitvecTest(), sqlite3PagerAcquire(), sqlite3PagerCommitPhaseOne(), sqlite3PagerDontRollback(), sqlite3PagerMovepage(), and sqlite3PagerWrite().
int sqlite3BtreeFactory (const sqlite3 * db, const char * zFilename, int omitJournal, int nCache, int flags, Btree ** ppBtree)
Definition at line 1129 of file main.c.
References BTREE_NO_READLOCK, BTREE_OMIT_JOURNAL, sqlite3::flags, sqlite3::mutex, sqlite3_mutex_held, sqlite3BtreeOpen(), sqlite3BtreeSchema(), sqlite3BtreeSetCacheSize(), SQLITE_NoReadlock, SQLITE_OK, SQLITE_OPEN_MAIN_DB, SQLITE_OPEN_TEMP_DB, and sqlite3::temp_store.
Referenced by attachFunc(), openDatabase(), sqlite3OpenTempDatabase(), and sqlite3VdbeExec().
void sqlite3ChangeCookie (Parse * , int)
Definition at line 1301 of file build.c.
References sqlite3::aDb, Parse::db, db, OP_Integer, OP_SetCookie, Db::pSchema, Parse::pVdbe, Schema::schema_cookie, sqlite3GetTempReg(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp2(), and sqlite3VdbeAddOp3().
Referenced by sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3FinishTrigger(), and sqlite3VtabFinishParse().
int sqlite3CheckCollSeq (Parse * , CollSeq *)
Definition at line 123 of file callback.c.
References Parse::db, Parse::nErr, sqlite3ErrorMsg(), sqlite3GetCollSeq(), SQLITE_ERROR, SQLITE_OK, and CollSeq::zName.
Referenced by sqlite3ExprCollSeq().
int sqlite3CheckObjectName (Parse * , const char *)
Definition at line 696 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, sqlite3::flags, sqlite3::init, Parse::nested, sqlite3ErrorMsg(), sqlite3StrNICmp(), SQLITE_ERROR, SQLITE_OK, and SQLITE_WriteSchema.
Referenced by sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CreateIndex(), and sqlite3StartTable().
int sqlite3CodeRowTrigger (Parse * , int , ExprList * , int , Table * , int , int , int , int , u32 * , u32 *)
Definition at line 755 of file trigger.c.
References sqlite3::aDb, checkColumnOverLap(), codeTriggerProgram(), Parse::db, db, TriggerStack::ignoreJump, sqlite3::mallocFailed, Trigger::name, TriggerStack::newColMask, TriggerStack::newIdx, TriggerStack::oldColMask, TriggerStack::oldIdx, Trigger::op, OP_Trace, P4_DYNAMIC, Trigger::pColumns, TriggerStack::pNext, Trigger::pNext, NameContext::pParse, Db::pSchema, Trigger::pSchema, TriggerStack::pTab, Trigger::pTabSchema, TriggerStack::pTrigger, Table::pTrigger, Parse::pVdbe, Trigger::pWhen, sqlite3AuthContextPop(), sqlite3AuthContextPush(), sqlite3ErrorMsg(), sqlite3ExprDelete(), sqlite3ExprDup(), sqlite3ExprIfFalse(), sqlite3MPrintf(), sqlite3ResolveExprNames(), sqlite3VdbeAddOp4(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), SQLITE_ERROR, SQLITE_JUMPIFNULL, Trigger::step_list, TK_DELETE, TK_INSERT, TK_UPDATE, Trigger::tr_tm, TRIGGER_AFTER, TRIGGER_BEFORE, and Parse::trigStack.
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
void sqlite3CodeSubselect (Parse * , Expr * , int , int)
Definition at line 1263 of file expr.c.
References ExprList::a, KeyInfo::aColl, SelectDest::affinity, Parse::db, Parse::disableColCache, SelectDest::eDest, EP_VarSelect, ExprHasAnyProperty, Expr::iColumn, SelectDest::iParm, Expr::iTable, sqlite3::mallocFailed, ExprList::nExpr, KeyInfo::nField, Parse::nMem, Parse::nTab, Expr::op, OP_IdxInsert, OP_If, OP_Insert, OP_Integer, OP_MakeRecord, OP_MustBeInt, OP_Null, OP_OpenEphemeral, P4_KEYINFO, Select::pEList, ExprList::ExprList_item::pExpr, Expr::pLeft, Select::pLimit, Expr::pList, Expr::pSelect, sqlite3BinaryCompareCollSeq(), sqlite3ExprAffinity(), sqlite3ExprCacheAffinityChange(), sqlite3ExprCodeTarget(), sqlite3ExprCollSeq(), sqlite3ExprDelete(), sqlite3ExprIsConstant(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3PExpr(), sqlite3ReleaseTempReg(), sqlite3Select(), sqlite3SelectDestInit(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeToNoop(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), SQLITE_AFF_NONE, SRT_Exists, SRT_Mem, SRT_Set, TK_EXISTS, TK_IN, TK_INTEGER, TK_SELECT, Parse::trigStack, and VdbeComment.
Referenced by sqlite3ExprCodeTarget(), and sqlite3FindInIndex().
void sqlite3CodeVerifySchema (Parse * , int)
Definition at line 3356 of file build.c.
References sqlite3::aDb, Parse::cookieGoto, Parse::cookieMask, Parse::cookieValue, Parse::db, db, OMIT_TEMPDB, OP_Goto, Db::pBt, Db::pSchema, Schema::schema_cookie, sqlite3GetVdbe(), sqlite3OpenTempDatabase(), sqlite3VdbeAddOp2(), and SQLITE_MAX_ATTACHED.
Referenced by sqlite3BeginWriteOperation(), sqlite3Pragma(), sqlite3WhereBegin(), and xferOptimization().
void sqlite3ColumnDefault (Vdbe * , Table * , int)
Definition at line 57 of file update.c.
References Table::aCol, Column::affinity, ENC, P4_MEM, Column::pDflt, Table::pSelect, sqlite3ValueFromExpr(), sqlite3VdbeChangeP4(), sqlite3VdbeDb(), VdbeComment, Column::zName, and Table::zName.
Referenced by sqlite3ExprCodeGetColumn(), sqlite3GenerateIndexKey(), and sqlite3Update().
void sqlite3CommitInternalChanges (sqlite3 *)
Definition at line 472 of file build.c.
References sqlite3::flags, and SQLITE_InternChanges.
Referenced by sqlite3Init(), and sqlite3VdbeHalt().
void sqlite3CommitTransaction (Parse *)
Definition at line 3272 of file build.c.
References sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, Parse::nErr, OP_AutoCommit, Db::pBt, sqlite3AuthCheck(), sqlite3GetVdbe(), sqlite3VdbeAddOp2(), and SQLITE_TRANSACTION.
Referenced by yy_reduce().
char sqlite3CompareAffinity (Expr * pExpr, char aff2)
Definition at line 123 of file expr.c.
References sqlite3ExprAffinity(), sqlite3IsNumericAffinity, SQLITE_AFF_NONE, and SQLITE_AFF_NUMERIC.
Referenced by binaryCompareP5(), comparisonAffinity(), generateOutputSubroutine(), and selectInnerLoop().
void sqlite3CompleteInsertion (Parse * , Table * , int , int , int * , int , int , int , int)
Definition at line 1325 of file insert.c.
References Table::nCol, Parse::nested, OP_IdxInsert, OP_Insert, OP_MakeRecord, OPFLAG_APPEND, OPFLAG_ISUPDATE, OPFLAG_LASTROWID, OPFLAG_NCHANGE, P4_STATIC, Table::pIndex, Index::pNext, Table::pSelect, sqlite3ExprCacheAffinityChange(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3TableAffinityStr(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), and Table::zName.
Referenced by sqlite3Insert(), and sqlite3Update().
void sqlite3CreateForeignKey (Parse * , ExprList * , Token * , ExprList * , int)
Definition at line 2133 of file build.c.
References ExprList::a, FKey::aCol, Table::aCol, Parse::db, db, FKey::deleteConf, FKey::sColMap::iFrom, IN_DECLARE_VTAB, FKey::insertConf, FKey::isDeferred, Token::n, FKey::nCol, Table::nCol, Parse::nErr, ExprList::nExpr, Table::pFKey, FKey::pFrom, Parse::pNewTable, FKey::pNextFrom, FKey::pNextTo, sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3ErrorMsg(), sqlite3ExprListDelete(), sqlite3StrICmp(), FKey::updateConf, Token::z, FKey::sColMap::zCol, ExprList::ExprList_item::zName, Column::zName, and FKey::zTo.
Referenced by yy_reduce().
int sqlite3CreateFunc (sqlite3 * , const char * , int , int , void * , void(*)(sqlite3_context *, int, sqlite3_value **) , void(*)(sqlite3_context *, int, sqlite3_value **) , void(*)(sqlite3_context *))
Definition at line 850 of file main.c.
References sqlite3::activeVdbeCnt, FuncDef::flags, FuncDef::iPrefEnc, sqlite3::mallocFailed, sqlite3::mutex, FuncDef::nArg, FuncDef::pUserData, sqlite3_mutex_held, sqlite3CreateFunc(), sqlite3Error(), sqlite3ExpirePreparedStatements(), sqlite3FindFunction(), sqlite3Strlen(), SQLITE_ANY, SQLITE_BUSY, SQLITE_ERROR, SQLITE_MAX_FUNCTION_ARG, SQLITE_NOMEM, SQLITE_OK, SQLITE_UTF16, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF16NATIVE, SQLITE_UTF8, FuncDef::xFinalize, FuncDef::xFunc, and FuncDef::xStep.
Referenced by sqlite3_create_function(), sqlite3_create_function16(), sqlite3_overload_function(), sqlite3AlterFunctions(), sqlite3CreateFunc(), and sqlite3RegisterLikeFunctions().
Expr* sqlite3CreateIdExpr (Parse * , const char *)
Definition at line 237 of file select.c.
References setToken(), sqlite3PExpr(), and TK_ID.
Referenced by addWhereTerm(), and updateVirtualTable().
void sqlite3CreateIndex (Parse * , Token * , Token * , SrcList * , ExprList * , int , Token * , Token * , int , int)
Definition at line 2336 of file build.c.
References ExprList::a, SrcList::a, Table::aCol, sqlite3::aDb, Index::aiColumn, Index::aiRowEst, Index::aSortOrder, Index::autoIndex, Index::azColl, sqlite3::sqlite3InitInfo::busy, Parse::db, db, Schema::file_format, sqlite3::flags, freeIndex(), Schema::idxHash, IN_DECLARE_VTAB, sqlite3::init, IsVirtual, sqlite3::mallocFailed, Token::n, Table::nCol, Index::nColumn, Parse::nErr, sqlite3::sqlite3InitInfo::newTnum, ExprList::nExpr, Parse::nMem, OE_Default, OE_None, OE_Replace, OMIT_TEMPDB, Index::onError, OP_CreateIndex, OP_Expire, OP_ParseSchema, P4_DYNAMIC, Expr::pColl, sqlite3::pDfltColl, ExprList::ExprList_item::pExpr, Table::pIndex, Parse::pNewTable, Index::pNext, Index::pSchema, Db::pSchema, Table::pSchema, Table::pSelect, Index::pTable, SCHEMA_TABLE, ExprList::ExprList_item::sortOrder, sqlite3_snprintf(), sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DefaultRowEst(), sqlite3ErrorMsg(), sqlite3ExprListAppend(), sqlite3ExprListDelete(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3FixInit(), sqlite3FixSrcList(), sqlite3GetVdbe(), sqlite3HashInsert(), sqlite3LocateCollSeq(), sqlite3LocateTable(), sqlite3MPrintf(), sqlite3NameFromToken(), sqlite3NestedParse(), sqlite3ReadSchema(), sqlite3RefillIndex(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StrICmp(), sqlite3StrNICmp(), sqlite3TwoPartName(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), SQLITE_CREATE_INDEX, SQLITE_CREATE_TEMP_INDEX, SQLITE_INSERT, SQLITE_InternChanges, SQLITE_OK, Index::tnum, Token::z, Column::zColl, SrcList::SrcList_item::zDatabase, Index::zName, CollSeq::zName, Column::zName, Db::zName, Table::zName, and SrcList::SrcList_item::zName.
Referenced by sqlite3AddPrimaryKey(), and yy_reduce().
void sqlite3CreateView (Parse * , Token * , Token * , Token * , Select * , int , int)
Definition at line 1645 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::init, sqlite3::mallocFailed, Token::n, Parse::nErr, Parse::nVar, Parse::pNewTable, Table::pSchema, Table::pSelect, Parse::sLastToken, sqlite3EndTable(), sqlite3ErrorMsg(), sqlite3FixInit(), sqlite3FixSelect(), sqlite3SchemaToIndex(), sqlite3SelectDelete(), sqlite3SelectDup(), sqlite3StartTable(), sqlite3TwoPartName(), sqlite3ViewGetColumnNames(), and Token::z.
Referenced by yy_reduce().
void sqlite3DbFree (sqlite3 * , void *)
Definition at line 532 of file malloc.c.
References isLookaside(), sqlite3::lookaside, Lookaside::nOut, Lookaside::pFree, LookasideSlot::pNext, and sqlite3_free().
Referenced by addModuleArgument(), attachFunc(), bestVirtualIndex(), callCollNeeded(), callFinaliser(), Cleanup(), codeAttach(), createModule(), findCollSeqEntry(), flattenSubquery(), freeEphemeralFunction(), freeIndex(), freeP4(), lookupName(), multiSelect(), releaseMemArray(), replaceFunc(), resolveAlias(), resolveAsName(), resolveP2Values(), selectColumnsFromExprList(), selectExpander(), sqlite3_blob_close(), sqlite3_blob_open(), sqlite3_close(), sqlite3_create_collation16(), sqlite3_create_function16(), sqlite3_declare_vtab(), sqlite3_exec(), sqlite3_step(), sqlite3AddCollateType(), sqlite3AddColumn(), sqlite3AddColumnType(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AnalysisLoad(), sqlite3Analyze(), sqlite3BeginTrigger(), sqlite3CloseExtensions(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3DbRealloc(), sqlite3DbReallocOrFree(), sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3DeleteTriggerStep(), sqlite3EndTable(), sqlite3ErrorClear(), sqlite3ErrorMsg(), sqlite3ExprClear(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlite3ExprListDup(), sqlite3ExprSetColl(), sqlite3FindDb(), sqlite3FinishTrigger(), sqlite3IdListDelete(), sqlite3IdListDup(), sqlite3IndexKeyinfo(), sqlite3InitCallback(), sqlite3InitOne(), sqlite3Insert(), sqlite3LoadExtension(), sqlite3MAppendf(), sqlite3NestedParse(), sqlite3Pragma(), sqlite3Prepare(), sqlite3Prepare16(), sqlite3Reindex(), sqlite3ResetInternalSchema(), sqlite3RunParser(), sqlite3Select(), sqlite3SelectDelete(), sqlite3SelectNew(), sqlite3SetString(), sqlite3SrcListDelete(), sqlite3StartTable(), sqlite3StrAccumReset(), sqlite3TokenCopy(), sqlite3Update(), sqlite3ValueFree(), sqlite3ValueFromExpr(), sqlite3VdbeDelete(), sqlite3VdbeDeleteUnpackedRecord(), sqlite3VdbeExec(), sqlite3VdbeFifoClear(), sqlite3VdbeFifoPop(), sqlite3VdbeFreeCursor(), sqlite3VdbeHalt(), sqlite3VdbeMemFinalize(), sqlite3VdbeMemGrow(), sqlite3VdbeMemRelease(), sqlite3VdbeReset(), sqlite3VdbeSetNumCols(), sqlite3VtabCallConnect(), sqlite3VtabClear(), sqlite3VtabFinishParse(), sqlite3VtabOverloadFunction(), sqlite3VtabSync(), sqlite3WhereEnd(), sqliteResetColumnNames(), vdbeCommit(), vtabCallConstructor(), whereClauseClear(), whereClauseInsert(), whereInfoFree(), and whereTempTriggers().
void* sqlite3DbMallocRaw (sqlite3 * , int)
Definition at line 638 of file malloc.c.
References Lookaside::bEnabled, sqlite3::lookaside, sqlite3::mallocFailed, Lookaside::mxOut, Lookaside::nOut, Lookaside::pFree, LookasideSlot::pNext, and sqlite3Malloc().
Referenced by allocateFifoPage(), attachFunc(), createModule(), dup8bytes(), multiSelectOrderBy(), sqlite3DbMallocZero(), sqlite3DbRealloc(), sqlite3DbStrDup(), sqlite3DbStrNDup(), sqlite3ExprDup(), sqlite3ExprListDup(), sqlite3HexToBlob(), sqlite3IdListDup(), sqlite3Insert(), sqlite3SelectDup(), sqlite3SrcListDup(), sqlite3StrAccumAppend(), sqlite3StrAccumFinish(), sqlite3Update(), sqlite3VdbeExec(), sqlite3VdbeMemGrow(), sqlite3VdbeMemTranslate(), sqlite3VdbeRecordUnpack(), strftimeFunc(), and whereClauseInsert().
int sqlite3DbMallocSize (sqlite3 * , void *)
Definition at line 505 of file malloc.c.
References isLookaside(), sqlite3::lookaside, sqlite3GlobalConfig, and Lookaside::sz.
Referenced by sqlite3VdbeMemGrow().
void* sqlite3DbMallocZero (sqlite3 * , int)
Definition at line 612 of file malloc.c.
References sqlite3DbMallocRaw().
Referenced by bestVirtualIndex(), codeAlias(), findCollSeqEntry(), keyInfoFromExprList(), multiSelect(), multiSelectOrderBy(), selectColumnsFromExprList(), selectExpander(), sqlite3_blob_open(), sqlite3_exec(), sqlite3AlterBeginAddColumn(), sqlite3BeginTrigger(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3Expr(), sqlite3ExprFunction(), sqlite3ExprListAppend(), sqlite3FindFunction(), sqlite3IdListAppend(), sqlite3IndexKeyinfo(), sqlite3LoadExtension(), sqlite3ResultSetOfSelect(), sqlite3SelectNew(), sqlite3SrcListAppend(), sqlite3StartTable(), sqlite3TriggerDeleteStep(), sqlite3TriggerInsertStep(), sqlite3TriggerSelectStep(), sqlite3TriggerUpdateStep(), sqlite3ValueNew(), sqlite3VdbeCreate(), sqlite3VdbeMakeReady(), sqlite3VdbeSetNumCols(), sqlite3VtabOverloadFunction(), sqlite3WhereBegin(), and yy_reduce().
void* sqlite3DbRealloc (sqlite3 * , void * , int)
Definition at line 672 of file malloc.c.
References isLookaside(), sqlite3::lookaside, sqlite3::mallocFailed, sqlite3_realloc(), sqlite3DbFree(), sqlite3DbMallocRaw(), and Lookaside::sz.
Referenced by addModuleArgument(), addToVTrans(), attachFunc(), resizeOpArray(), sqlite3_set_auxdata(), sqlite3AddColumn(), sqlite3ArrayAllocate(), sqlite3DbReallocOrFree(), sqlite3ExprListAppend(), and sqlite3SrcListEnlarge().
void* sqlite3DbReallocOrFree (sqlite3 * , void * , int)
Definition at line 701 of file malloc.c.
References sqlite3DbFree(), and sqlite3DbRealloc().
Referenced by codeEqualityTerm(), sqlite3ExprAssignVarNumber(), sqlite3TableLock(), sqlite3VdbeExec(), sqlite3VdbeMakeLabel(), and sqlite3VdbeMemGrow().
char* sqlite3DbStrDup (sqlite3 * , const char *)
Definition at line 717 of file malloc.c.
References sqlite3DbMallocRaw().
Referenced by attachFunc(), selectAddColumnTypeAndCollation(), selectColumnsFromExprList(), sqlite3_step(), sqlite3AlterBeginAddColumn(), sqlite3BeginTrigger(), sqlite3BtreeIntegrityCheck(), sqlite3ExprListDup(), sqlite3FixSrcList(), sqlite3IdListDup(), sqlite3LoadExtension(), sqlite3Pragma(), sqlite3SrcListDup(), sqlite3Utf16to8(), sqlite3VdbeExec(), sqlite3VtabBeginParse(), and sqlite3VtabOverloadFunction().
char* sqlite3DbStrNDup (sqlite3 * , const char * , int)
Definition at line 731 of file malloc.c.
References sqlite3DbMallocRaw().
Referenced by addArgumentToVtab(), callCollNeeded(), flattenSubquery(), generateColumnNames(), sqlite3AlterFinishAddColumn(), sqlite3ExprDup(), sqlite3FinishTrigger(), sqlite3NameFromToken(), sqlite3Prepare(), sqlite3TokenCopy(), sqlite3ValueFromExpr(), sqlite3VdbeChangeP4(), sqlite3VdbeSetSql(), and sqlitePersistTriggerStep().
void sqlite3DefaultRowEst (Index *)
Definition at line 2806 of file build.c.
References Index::aiRowEst, Index::nColumn, OE_None, and Index::onError.
Referenced by sqlite3AnalysisLoad(), and sqlite3CreateIndex().
void sqlite3DeferForeignKey (Parse * , int)
Definition at line 2242 of file build.c.
References FKey::isDeferred, Table::pFKey, and Parse::pNewTable.
Referenced by yy_reduce().
void sqlite3DeleteFrom (Parse * , SrcList * , Expr *)
Definition at line 218 of file delete.c.
References SrcList::a, sqlite3::aDb, COLNAME_NAME, Parse::db, db, sqlite3::flags, SrcList::SrcList_item::iCursor, IsVirtual, sqlite3::mallocFailed, Table::nCol, Parse::nErr, Parse::nested, Parse::nMem, SrcList::nSrc, Parse::nTab, OE_Default, OP_AddImm, OP_Clear, OP_Close, OP_FifoRead, OP_FifoWrite, OP_Goto, OP_Insert, OP_Integer, OP_NotExists, OP_Null, OP_OpenPseudo, OP_OpenWrite, OP_ResultRow, OP_RowData, OP_Rowid, OP_SetNumColumns, OP_VRowid, OP_VUpdate, TriggerStack::orconf, P4_STATIC, P4_VTAB, Table::pIndex, Index::pNext, NameContext::pParse, AuthContext::pParse, Index::pSchema, Table::pSchema, Table::pSelect, NameContext::pSrcList, Table::pVtab, sqlite3AuthCheck(), sqlite3AuthContextPop(), sqlite3AuthContextPush(), sqlite3BeginWriteOperation(), sqlite3CodeRowTrigger(), sqlite3ExprDelete(), sqlite3GenerateRowDelete(), sqlite3GetVdbe(), sqlite3IsReadOnly(), sqlite3MaterializeView(), sqlite3OpenTableAndIndices(), sqlite3ResolveExprNames(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3TriggersExist(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeCountChanges(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3ViewGetColumnNames(), sqlite3VtabMakeWritable(), sqlite3WhereBegin(), sqlite3WhereEnd(), SQLITE_CountRows, SQLITE_DELETE, SQLITE_DENY, SQLITE_IGNORE, SQLITE_OK, SQLITE_STATIC, TK_DELETE, Index::tnum, Table::tnum, TRIGGER_AFTER, TRIGGER_BEFORE, Parse::trigStack, Table::zName, and Db::zName.
Referenced by codeTriggerProgram(), and yy_reduce().
void sqlite3DeleteTable (Table *)
Definition at line 507 of file build.c.
References Schema::aFKey, Table::db, db, Table::nRef, Table::pCheck, Table::pFKey, Table::pIndex, Index::pNext, FKey::pNextFrom, Table::pSchema, Index::pSchema, Table::pSelect, sqlite3DbFree(), sqlite3ExprDelete(), sqlite3HashFind(), sqlite3SelectDelete(), sqlite3VtabClear(), sqliteDeleteIndex(), sqliteResetColumnNames(), Table::zColAff, Table::zName, and FKey::zTo.
Referenced by sqlite3_declare_vtab(), sqlite3EndTable(), sqlite3ResultSetOfSelect(), sqlite3RunParser(), sqlite3SchemaFree(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StartTable(), sqlite3UnlinkAndDeleteTable(), and sqlite3ViewGetColumnNames().
void sqlite3DeleteTrigger (sqlite3 * , Trigger *)
Definition at line 430 of file trigger.c.
References Token::dyn, Trigger::name, Trigger::nameToken, Trigger::pColumns, Trigger::pWhen, sqlite3DbFree(), sqlite3DeleteTriggerStep(), sqlite3ExprDelete(), sqlite3IdListDelete(), Trigger::step_list, Trigger::table, and Token::z.
Referenced by sqlite3BeginTrigger(), sqlite3FinishTrigger(), sqlite3RunParser(), sqlite3SchemaFree(), and sqlite3UnlinkAndDeleteTrigger().
void sqlite3DeleteTriggerStep (sqlite3 * , TriggerStep *)
Definition at line 21 of file trigger.c.
References Token::dyn, TriggerStep::pExprList, TriggerStep::pIdList, TriggerStep::pNext, TriggerStep::pSelect, TriggerStep::pWhere, sqlite3DbFree(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlite3IdListDelete(), sqlite3SelectDelete(), TriggerStep::target, and Token::z.
Referenced by sqlite3DeleteTrigger(), sqlite3FinishTrigger(), and yy_destructor().
void sqlite3Dequote (char *)
Definition at line 157 of file util.c.
Referenced by selectColumnsFromExprList(), sqlite3DequoteExpr(), sqlite3NameFromToken(), and sqlite3ValueFromExpr().
void sqlite3DequoteExpr (sqlite3 * , Expr *)
Definition at line 631 of file expr.c.
References Token::dyn, EP_Dequoted, ExprHasAnyProperty, ExprSetProperty, sqlite3Dequote(), sqlite3TokenCopy(), Expr::token, and Token::z.
Referenced by isLikeOrGlob(), and sqlite3ExprCodeTarget().
void sqlite3Detach (Parse * , Expr *)
Definition at line 355 of file attach.c.
References codeAttach(), detachFunc(), SQLITE_DETACH, and SQLITE_UTF8.
Referenced by yy_reduce().
void sqlite3DropIndex (Parse * , SrcList * , int)
Definition at line 2827 of file build.c.
References SrcList::a, sqlite3::aDb, Index::autoIndex, Parse::checkSchema, Parse::db, db, destroyRootPage(), sqlite3::mallocFailed, Parse::nErr, SrcList::nSrc, OMIT_TEMPDB, OP_DropIndex, Index::pSchema, Index::pTable, SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3NestedParse(), sqlite3ReadSchema(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3VdbeAddOp4(), SQLITE_DELETE, SQLITE_DROP_INDEX, SQLITE_DROP_TEMP_INDEX, SQLITE_OK, Index::tnum, SrcList::SrcList_item::zDatabase, Table::zName, Index::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
void sqlite3DropTable (Parse * , SrcList * , int , int)
Definition at line 1952 of file build.c.
References SrcList::a, sqlite3::aDb, Parse::db, db, destroyTable(), IsVirtual, sqlite3::mallocFailed, Parse::nErr, SrcList::nSrc, OMIT_TEMPDB, OP_DropTable, OP_VBegin, OP_VDestroy, Table::pMod, Trigger::pNext, Db::pSchema, Trigger::pSchema, Table::pSchema, Table::pSelect, Table::pTrigger, SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3DropTriggerPtr(), sqlite3ErrorClear(), sqlite3ErrorMsg(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3LocateTable(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3StrNICmp(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp4(), sqlite3ViewGetColumnNames(), SQLITE_DELETE, SQLITE_DROP_TABLE, SQLITE_DROP_TEMP_TABLE, SQLITE_DROP_TEMP_VIEW, SQLITE_DROP_VIEW, SQLITE_DROP_VTABLE, sqliteViewResetAll(), Table::tabFlags, TF_Autoincrement, SrcList::SrcList_item::zDatabase, Table::zName, Module::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
void sqlite3DropTrigger (Parse * , SrcList * , int)
Definition at line 449 of file trigger.c.
References SrcList::a, sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, sqlite3::nDb, SrcList::nSrc, OMIT_TEMPDB, Db::pSchema, sqlite3DropTriggerPtr(), sqlite3ErrorMsg(), sqlite3HashFind(), sqlite3ReadSchema(), sqlite3SrcListDelete(), sqlite3StrICmp(), SQLITE_OK, Schema::trigHash, SrcList::SrcList_item::zDatabase, Db::zName, and SrcList::SrcList_item::zName.
Referenced by yy_reduce().
void sqlite3DropTriggerPtr (Parse * , Trigger *)
Definition at line 497 of file trigger.c.
References sqlite3::aDb, ADDR, ArraySize, Parse::db, db, Trigger::name, OP_Close, OP_Column, OP_Delete, OP_DropTrigger, OP_Ne, OP_Next, OP_Rewind, OP_String8, P4_STATIC, Table::pSchema, Trigger::pSchema, SCHEMA_TABLE, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3GetVdbe(), sqlite3OpenMasterTable(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), sqlite3VdbeAddOpList(), sqlite3VdbeChangeP4(), SQLITE_DELETE, SQLITE_DROP_TEMP_TRIGGER, SQLITE_DROP_TRIGGER, tableOfTrigger(), Table::zName, and Db::zName.
Referenced by sqlite3DropTable(), and sqlite3DropTrigger().
void sqlite3EndBenignMalloc (void)
Definition at line 84 of file fault.c.
References wsdHooks, and wsdHooksInit.
Referenced by pagerUnlockAndRollback(), rehash(), setupLookaside(), sqlite3BitvecSet(), sqlite3PagerClose(), sqlite3RollbackAll(), sqlite3VdbeExec(), sqlite3VdbeReset(), and vdbeCommit().
void sqlite3EndTable (Parse * , Token * , Token * , Select *)
Definition at line 1424 of file build.c.
References SrcList::a, Table::aCol, sqlite3::aDb, Table::addColOffset, Schema::aFKey, sqlite3::sqlite3InitInfo::busy, createTableStmt(), Parse::db, db, sqlite3::flags, SrcList::SrcList_item::iCursor, sqlite3::init, NameContext::isCheck, sqlite3::mallocFailed, Table::nCol, Parse::nErr, sqlite3::sqlite3InitInfo::newTnum, SrcList::nSrc, Parse::nTab, sqlite3::nTable, OP_Close, OP_OpenWrite, OP_ParseSchema, P4_DYNAMIC, Table::pCheck, Table::pFKey, Parse::pNewTable, FKey::pNextFrom, FKey::pNextTo, NameContext::pParse, Db::pSchema, Table::pSchema, Table::pSelect, Schema::pSeqTab, NameContext::pSrcList, SrcList::SrcList_item::pTab, Parse::regRoot, Parse::regRowid, SCHEMA_TABLE, Parse::sNameToken, sqlite3ChangeCookie(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3GetVdbe(), sqlite3HashFind(), sqlite3HashInsert(), sqlite3MPrintf(), sqlite3NestedParse(), sqlite3ResolveExprNames(), sqlite3ResultSetOfSelect(), sqlite3SchemaToIndex(), sqlite3Select(), sqlite3SelectDestInit(), sqlite3Utf8CharLen(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP5(), SQLITE_InternChanges, SRT_Table, Table::tabFlags, Schema::tblHash, TF_Autoincrement, Table::tnum, Token::z, Db::zName, Table::zName, SrcList::SrcList_item::zName, and FKey::zTo.
Referenced by sqlite3CreateView(), and yy_reduce().
void sqlite3Error (sqlite3 * , int , const char * , ...)
Definition at line 92 of file util.c.
References sqlite3::errCode, sqlite3::pErr, sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3VMPrintf(), SQLITE_DYNAMIC, SQLITE_STATIC, and SQLITE_UTF8.
Referenced by bindText(), blobReadWrite(), columnMem(), createCollation(), openDatabase(), sqlite3_blob_open(), sqlite3_close(), sqlite3_declare_vtab(), sqlite3_exec(), sqlite3ApiExit(), sqlite3AutoLoadExtensions(), sqlite3CreateFunc(), sqlite3Prepare(), sqlite3VdbeReset(), sqlite3VtabOverloadFunction(), and vdbeUnbind().
void sqlite3ErrorClear (Parse *)
Definition at line 141 of file util.c.
References Parse::db, Parse::nErr, sqlite3DbFree(), and Parse::zErrMsg.
Referenced by resolveOrderByTermToExprList(), and sqlite3DropTable().
void sqlite3ErrorMsg (Parse * , const char * , ...)
Definition at line 125 of file util.c.
References Parse::db, db, Parse::nErr, Parse::rc, sqlite3DbFree(), sqlite3VMPrintf(), SQLITE_ERROR, SQLITE_OK, and Parse::zErrMsg.
Referenced by bestVirtualIndex(), checkForMultiColumnSelectError(), invalidateTempStorage(), lookupName(), multiSelect(), resetAccumulator(), resolveAttachExpr(), resolveCompoundOrderBy(), resolveExprStep(), resolveOutOfRangeError(), resolveSelectStep(), selectExpander(), sqlite3_blob_open(), sqlite3AddColumn(), sqlite3AddDefaultValue(), sqlite3AddPrimaryKey(), sqlite3AlterBeginAddColumn(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AuthCheck(), sqlite3AuthRead(), sqlite3BeginTrigger(), sqlite3CheckCollSeq(), sqlite3CheckObjectName(), sqlite3CodeRowTrigger(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTrigger(), sqlite3ExprAssignVarNumber(), sqlite3ExprCodeTarget(), sqlite3ExprListCheckLength(), sqlite3FixSrcList(), sqlite3IndexedByLookup(), sqlite3Insert(), sqlite3IsReadOnly(), sqlite3JoinType(), sqlite3LocateCollSeq(), sqlite3LocateTable(), sqlite3OpenTempDatabase(), sqlite3Pragma(), sqlite3RegisterExpr(), sqlite3Reindex(), sqlite3ResolveOrderGroupBy(), sqlite3Select(), sqlite3StartTable(), sqlite3TwoPartName(), sqlite3Update(), sqlite3ViewGetColumnNames(), sqlite3VtabBeginParse(), sqlite3VtabCallConnect(), sqlite3WhereBegin(), sqliteAuthBadReturnCode(), sqliteProcessJoin(), yy_reduce(), yy_syntax_error(), and yyStackOverflow().
const char* sqlite3ErrStr (int)
Definition at line 680 of file main.c.
References SQLITE_ABORT, SQLITE_AUTH, SQLITE_BUSY, SQLITE_CANTOPEN, SQLITE_CONSTRAINT, SQLITE_CORRUPT, SQLITE_DONE, SQLITE_EMPTY, SQLITE_ERROR, SQLITE_FORMAT, SQLITE_FULL, SQLITE_INTERRUPT, SQLITE_IOERR, SQLITE_LOCKED, SQLITE_MISMATCH, SQLITE_MISUSE, SQLITE_NOLFS, SQLITE_NOMEM, SQLITE_NOTADB, SQLITE_OK, SQLITE_PERM, SQLITE_RANGE, SQLITE_READONLY, SQLITE_ROW, SQLITE_SCHEMA, and SQLITE_TOOBIG.
Referenced by bestVirtualIndex(), DbObjCmd(), sqlite3_errmsg(), sqlite3_errmsg16(), sqlite3InitOne(), sqlite3RunParser(), sqlite3VdbeExec(), and sqlite3VdbeList().
void sqlite3ExpirePreparedStatements (sqlite3 *)
Definition at line 2477 of file vdbeaux.c.
References Vdbe::expired, Vdbe::pNext, and sqlite3::pVdbe.
Referenced by createCollation(), sqlite3_set_authorizer(), sqlite3CreateFunc(), sqlite3RollbackAll(), and sqlite3VdbeExec().
Expr* sqlite3Expr (sqlite3 * , int , Expr * , Expr * , const Token *)
Definition at line 382 of file expr.c.
References Token::dyn, EP_ExpCollate, exprSetHeight, Expr::flags, Expr::iAgg, Expr::op, Expr::pColl, Expr::pLeft, Expr::pRight, Expr::span, sqlite3DbMallocZero(), sqlite3ExprDelete(), sqlite3ExprSpan(), Expr::token, and Token::z.
Referenced by exprAnalyze(), resolveCompoundOrderBy(), sqlite3ExprAnd(), sqlite3PExpr(), and sqlite3SelectNew().
char sqlite3ExprAffinity (Expr * pExpr)
Definition at line 36 of file expr.c.
References ExprList::a, Table::aCol, Expr::affinity, Column::affinity, Expr::iColumn, Table::nCol, Expr::op, Select::pEList, ExprList::ExprList_item::pExpr, Expr::pSelect, Expr::pTab, sqlite3AffinityType(), sqlite3ExprAffinity(), SQLITE_AFF_INTEGER, TK_AGG_COLUMN, TK_CAST, TK_COLUMN, TK_REGISTER, TK_SELECT, and Expr::token.
Referenced by binaryCompareP5(), comparisonAffinity(), orTermIsOptCandidate(), selectAddColumnTypeAndCollation(), sqlite3CodeSubselect(), sqlite3CompareAffinity(), and sqlite3ExprAffinity().
void sqlite3ExprAnalyzeAggList (NameContext * , ExprList *)
Definition at line 3052 of file expr.c.
References ExprList::a, and sqlite3ExprAnalyzeAggregates().
Referenced by sqlite3Select().
void sqlite3ExprAnalyzeAggregates (NameContext * , Expr *)
Definition at line 3038 of file expr.c.
References analyzeAggregate(), analyzeAggregatesInSelect(), Walker::pNC, sqlite3WalkExpr(), Walker::u, Walker::xExprCallback, and Walker::xSelectCallback.
Referenced by sqlite3ExprAnalyzeAggList(), and sqlite3Select().
Expr* sqlite3ExprAnd (sqlite3 * , Expr * , Expr *)
Definition at line 476 of file expr.c.
References sqlite3Expr(), and TK_AND.
Referenced by addWhereTerm(), flattenSubquery(), sqlite3AddCheckConstraint(), and sqliteProcessJoin().
void sqlite3ExprAssignVarNumber (Parse * , Expr *)
Definition at line 539 of file expr.c.
References sqlite3::aLimit, Parse::apVarExpr, Parse::db, db, Expr::iTable, sqlite3::mallocFailed, Token::n, Parse::nErr, Parse::nVar, Parse::nVarExpr, Parse::nVarExprAlloc, sqlite3DbReallocOrFree(), sqlite3ErrorMsg(), SQLITE_LIMIT_VARIABLE_NUMBER, testcase, Expr::token, and Token::z.
Referenced by yy_reduce().
void sqlite3ExprCacheAffinityChange (Parse * , int , int)
Definition at line 1605 of file expr.c.
References Parse::aColCache, Parse::yColCache::affChange, Parse::yColCache::iReg, and Parse::nColCache.
Referenced by codeApplyAffinity(), codeCompare(), generateOutputSubroutine(), generateSortTail(), selectInnerLoop(), sqlite3CodeSubselect(), sqlite3CompleteInsertion(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3GenerateIndexKey(), sqlite3Update(), and updateAccumulator().
void sqlite3ExprClear (sqlite3 * , Expr *)
Definition at line 609 of file expr.c.
References Token::dyn, Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, Expr::span, sqlite3DbFree(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlite3SelectDelete(), Expr::token, and Token::z.
Referenced by resolveAlias(), and sqlite3ExprDelete().
void sqlite3ExprClearColumnCache (Parse * , int)
Definition at line 1585 of file expr.c.
References Parse::aColCache, Parse::iColCache, Parse::yColCache::iTable, Parse::nColCache, and testcase.
Referenced by sqlite3WhereBegin(), and sqlite3WhereEnd().
int sqlite3ExprCode (Parse * , Expr * , int)
Definition at line 2340 of file expr.c.
References Parse::db, sqlite3::mallocFailed, OP_SCopy, Parse::pVdbe, sqlite3ExprCodeTarget(), and sqlite3VdbeAddOp2().
Referenced by codeAlias(), codeAttach(), computeLimitRegisters(), sqlite3ExprCodeAndCache(), sqlite3ExprCodeExprList(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), and updateAccumulator().
int sqlite3ExprCodeAndCache (Parse * , Expr * , int)
Definition at line 2364 of file expr.c.
References Expr::iTable, Parse::nMem, Expr::op, OP_Copy, Parse::pVdbe, sqlite3ExprCode(), sqlite3VdbeAddOp2(), and TK_REGISTER.
Referenced by sqlite3Insert(), and sqlite3Update().
void sqlite3ExprCodeConstants (Parse * , Expr *)
Definition at line 2485 of file expr.c.
References evalConstExpr(), Walker::pParse, sqlite3WalkExpr(), Walker::xExprCallback, and Walker::xSelectCallback.
Referenced by sqlite3WhereBegin().
void sqlite3ExprCodeCopy (Parse * , int , int , int)
Definition at line 1636 of file expr.c.
References OP_Copy, Parse::pVdbe, and sqlite3VdbeAddOp2().
Referenced by generateOutputSubroutine().
int sqlite3ExprCodeExprList (Parse * , ExprList * , int , int)
Definition at line 2500 of file expr.c.
References ExprList::a, codeAlias(), ExprList::nExpr, OP_SCopy, sqlite3ExprCode(), sqlite3ExprHardCopy(), sqlite3GetVdbe(), and sqlite3VdbeAddOp2().
Referenced by pushOntoSorter(), selectInnerLoop(), sqlite3ExprCodeTarget(), sqlite3Select(), and updateAccumulator().
int sqlite3ExprCodeGetColumn (Parse * , Table * , int , int , int , int)
Definition at line 1528 of file expr.c.
References Table::aCol, Parse::aColCache, Column::affinity, ArraySize, Parse::disableColCache, Parse::iColCache, IsVirtual, Parse::yColCache::iTable, Parse::nColCache, OP_Column, OP_Noop, OP_RealAffinity, OP_Rowid, OP_VColumn, OP_VRowid, Parse::pVdbe, sqlite3ColumnDefault(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), SQLITE_AFF_REAL, and VdbeComment.
Referenced by sqlite3ExprCodeTarget(), and sqlite3Select().
void sqlite3ExprCodeMove (Parse * , int , int , int)
Definition at line 1620 of file expr.c.
References Parse::aColCache, Parse::yColCache::iReg, Parse::nColCache, OP_Move, Parse::pVdbe, and sqlite3VdbeAddOp3().
Referenced by generateOutputSubroutine(), generateSortTail(), pushOntoSorter(), selectInnerLoop(), and sqlite3Select().
int sqlite3ExprCodeTarget (Parse * , Expr * , int)
Definition at line 1756 of file expr.c.
References ExprList::a, AggInfo::aCol, AggInfo::aFunc, Parse::ckBase, codeAlias(), codeCompare(), codeCompareOperands(), codeInteger(), codeReal(), comparisonAffinity(), Parse::db, db, AggInfo::directMode, Parse::disableColCache, ENC, EP_AnyAff, EP_InfixFunc, FuncDef::flags, Expr::flags, Expr::iAgg, Expr::iColumn, TriggerStack::ignoreJump, AggInfo::AggInfo_func::iMem, IN_INDEX_ROWID, Expr::iTable, sqlite3::mallocFailed, Token::n, ExprList::nExpr, Parse::nMem, OE_Abort, OE_Fail, OE_Ignore, OE_Rollback, Expr::op, OP_Add, OP_AddImm, OP_And, OP_BitAnd, OP_BitNot, OP_BitOr, OP_Blob, OP_CollSeq, OP_Column, OP_Concat, OP_ContextPop, OP_Copy, OP_Divide, OP_Eq, OP_Found, OP_Function, OP_Ge, OP_Goto, OP_Gt, OP_Halt, OP_Integer, OP_IsNull, OP_Le, OP_Lt, OP_MakeRecord, OP_MustBeInt, OP_Ne, OP_Not, OP_NotExists, OP_NotNull, OP_Null, OP_Or, OP_Remainder, OP_SCopy, OP_ShiftLeft, OP_ShiftRight, OP_String8, OP_Subtract, OP_ToBlob, OP_ToInt, OP_ToNumeric, OP_ToReal, OP_ToText, OP_Variable, P4_COLLSEQ, P4_DYNAMIC, P4_FUNCDEF, P4_STATIC, Expr::pAggInfo, sqlite3::pDfltColl, ExprList::ExprList_item::pExpr, Expr::pLeft, Expr::pList, Expr::pRight, Expr::pTab, Parse::pVdbe, AggInfo::sortingIdx, Expr::span, sqlite3AffinityType(), sqlite3CodeSubselect(), sqlite3DequoteExpr(), sqlite3ErrorMsg(), sqlite3ExprCacheAffinityChange(), sqlite3ExprCode(), sqlite3ExprCodeExprList(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeTarget(), sqlite3ExprCodeTemp(), sqlite3ExprCollSeq(), sqlite3ExprIfFalse(), sqlite3ExprIsConstant(), sqlite3ExprWritableRegister(), sqlite3FindFunction(), sqlite3FindInIndex(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3HexToBlob(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), sqlite3VdbeDb(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3VtabOverloadFunction(), SQLITE_AFF_INTEGER, SQLITE_AFF_NONE, SQLITE_AFF_NUMERIC, SQLITE_AFF_REAL, SQLITE_AFF_TEXT, SQLITE_CONSTRAINT, SQLITE_FUNC_NEEDCOLL, SQLITE_JUMPIFNULL, SQLITE_STOREP2, testcase, TK_AGG_COLUMN, TK_AGG_FUNCTION, TK_AND, TK_AS, TK_BETWEEN, TK_BITAND, TK_BITNOT, TK_BITOR, TK_BLOB, TK_CASE, TK_CAST, TK_COLUMN, TK_CONCAT, TK_CONST_FUNC, TK_EQ, TK_EXISTS, TK_FLOAT, TK_FUNCTION, TK_GE, TK_GT, TK_IN, TK_INTEGER, TK_ISNULL, TK_LE, TK_LSHIFT, TK_LT, TK_MINUS, TK_NE, TK_NOT, TK_NOTNULL, TK_NULL, TK_OR, TK_PLUS, TK_RAISE, TK_REGISTER, TK_REM, TK_RSHIFT, TK_SELECT, TK_SLASH, TK_STAR, TK_STRING, TK_UMINUS, TK_UPLUS, TK_VARIABLE, Expr::token, Parse::trigStack, usedAsColumnCache(), AggInfo::useSortingIdx, VdbeComment, VdbeNoopComment, and Token::z.
Referenced by codeAlias(), codeEqualityTerm(), evalConstExpr(), sqlite3CodeSubselect(), sqlite3ExprCode(), sqlite3ExprCodeTarget(), and sqlite3ExprCodeTemp().
int sqlite3ExprCodeTemp (Parse * , Expr * , int *)
Definition at line 2323 of file expr.c.
References sqlite3ExprCodeTarget(), sqlite3GetTempReg(), and sqlite3ReleaseTempReg().
Referenced by codeCompareOperands(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), and sqlite3ExprIfTrue().
CollSeq* sqlite3ExprCollSeq (Parse * pParse, Expr * pExpr)
Definition at line 86 of file expr.c.
References Table::aCol, Parse::db, db, ENC, Expr::iColumn, Expr::op, Expr::pColl, Expr::pLeft, Expr::pTab, sqlite3CheckCollSeq(), sqlite3FindCollSeq(), TK_AGG_COLUMN, TK_CAST, TK_COLUMN, TK_REGISTER, TK_UPLUS, and Column::zColl.
Referenced by exprCommute(), isLikeOrGlob(), isSortingIndex(), keyInfoFromExprList(), multiSelectCollSeq(), selectAddColumnTypeAndCollation(), sqlite3BinaryCompareCollSeq(), sqlite3CodeSubselect(), sqlite3ExprCodeTarget(), and updateAccumulator().
int sqlite3ExprCompare (Expr * , Expr *)
Definition at line 2827 of file expr.c.
References ExprList::a, EP_Distinct, Expr::flags, Expr::iColumn, Expr::iTable, Token::n, ExprList::nExpr, Expr::op, ExprList::ExprList_item::pExpr, Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, sqlite3ExprCompare(), sqlite3StrNICmp(), TK_COLUMN, Expr::token, and Token::z.
Referenced by analyzeAggregate(), resolveOrderByTermToExprList(), sqlite3ExprCompare(), and xferOptimization().
void sqlite3ExprDelete (sqlite3 * , Expr *)
Definition at line 621 of file expr.c.
References sqlite3DbFree(), and sqlite3ExprClear().
Referenced by clearSelect(), codeAttach(), exprAnalyze(), lookupName(), multiSelect(), multiSelectOrderBy(), resolveCompoundOrderBy(), sqlite3AddCheckConstraint(), sqlite3AddDefaultValue(), sqlite3BeginTrigger(), sqlite3CodeRowTrigger(), sqlite3CodeSubselect(), sqlite3DeleteFrom(), sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3DeleteTriggerStep(), sqlite3Expr(), sqlite3ExprClear(), sqlite3ExprListAppend(), sqlite3ExprListDelete(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListDelete(), sqlite3TriggerDeleteStep(), sqlite3TriggerUpdateStep(), sqlite3Update(), sqlitePersistTriggerStep(), sqliteResetColumnNames(), whereClauseClear(), whereClauseInsert(), and yy_destructor().
Expr* sqlite3ExprDup (sqlite3 * , Expr *)
Definition at line 654 of file expr.c.
References Token::dyn, Token::n, Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, Expr::span, sqlite3DbMallocRaw(), sqlite3DbStrNDup(), sqlite3ExprDup(), sqlite3ExprListDup(), sqlite3SelectDup(), Expr::token, and Token::z.
Referenced by codeTriggerProgram(), exprAnalyze(), flattenSubquery(), resolveAlias(), resolveCompoundOrderBy(), sqlite3AddCheckConstraint(), sqlite3AddDefaultValue(), sqlite3BeginTrigger(), sqlite3CodeRowTrigger(), sqlite3ExprDup(), sqlite3ExprListDup(), sqlite3MaterializeView(), sqlite3SelectDup(), sqlite3SrcListDup(), sqlitePersistTriggerStep(), substExpr(), and updateVirtualTable().
Expr* sqlite3ExprFunction (Parse * , ExprList * , Token *)
Definition at line 504 of file expr.c.
References Parse::db, db, Token::dyn, Expr::op, Expr::pList, Expr::span, sqlite3DbMallocZero(), sqlite3ExprListDelete(), sqlite3ExprSetHeight, TK_FUNCTION, and Expr::token.
Referenced by yy_reduce().
void sqlite3ExprHardCopy (Parse * , int , int)
Definition at line 1692 of file expr.c.
References Parse::db, sqlite3::mallocFailed, OP_Copy, OP_SCopy, VdbeOp::opcode, VdbeOp::p1, Parse::pVdbe, sqlite3VdbeCurrentAddr(), and sqlite3VdbeGetOp().
Referenced by sqlite3ExprCodeExprList().
void sqlite3ExprIfFalse (Parse * , Expr * , int , int)
Definition at line 2671 of file expr.c.
References ExprList::a, codeCompare(), codeCompareOperands(), Parse::disableColCache, Expr::iTable, Expr::op, OP_Eq, OP_Ge, OP_Gt, OP_IfNot, OP_IsNull, OP_Le, OP_Lt, OP_Ne, OP_NotNull, ExprList::ExprList_item::pExpr, Expr::pLeft, Expr::pList, Expr::pRight, Parse::pVdbe, sqlite3ExprCodeTemp(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), SQLITE_JUMPIFNULL, testcase, TK_AND, TK_BETWEEN, TK_EQ, TK_GE, TK_GT, TK_ISNULL, TK_LE, TK_LT, TK_NE, TK_NOT, TK_NOTNULL, TK_OR, and TK_REGISTER.
Referenced by sqlite3CodeRowTrigger(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3Select(), and sqlite3WhereBegin().
void sqlite3ExprIfTrue (Parse * , Expr * , int , int)
Definition at line 2542 of file expr.c.
References ExprList::a, codeCompare(), codeCompareOperands(), Parse::disableColCache, Expr::iTable, Expr::op, OP_Eq, OP_Ge, OP_Gt, OP_If, OP_IsNull, OP_Le, OP_Lt, OP_Ne, OP_NotNull, ExprList::ExprList_item::pExpr, Expr::pLeft, Expr::pList, Expr::pRight, Parse::pVdbe, sqlite3ExprCodeTemp(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), SQLITE_JUMPIFNULL, testcase, TK_AND, TK_BETWEEN, TK_EQ, TK_GE, TK_GT, TK_ISNULL, TK_LE, TK_LT, TK_NE, TK_NOT, TK_NOTNULL, TK_OR, and TK_REGISTER.
Referenced by sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), and sqlite3GenerateConstraintChecks().
int sqlite3ExprIsConstant (Expr *)
Definition at line 963 of file expr.c.
References exprIsConst().
Referenced by resolveAttachExpr(), sqlite3CodeSubselect(), and sqlite3ExprCodeTarget().
int sqlite3ExprIsConstantNotJoin (Expr *)
Definition at line 973 of file expr.c.
References exprIsConst().
Referenced by isAppropriateForFactoring(), and sqlite3WhereBegin().
int sqlite3ExprIsConstantOrFunction (Expr *)
Definition at line 986 of file expr.c.
References exprIsConst().
Referenced by sqlite3AddDefaultValue().
int sqlite3ExprIsInteger (Expr * , int *)
Definition at line 996 of file expr.c.
References EP_IntValue, Expr::flags, Expr::iTable, Expr::op, Expr::pLeft, sqlite3ExprIsInteger(), sqlite3GetInt32(), TK_INTEGER, TK_UMINUS, TK_UPLUS, Expr::token, and Token::z.
Referenced by resolveCompoundOrderBy(), resolveOrderByTermToExprList(), resolveOrderGroupBy(), and sqlite3ExprIsInteger().
ExprList* sqlite3ExprListAppend (Parse * , ExprList * , Expr * , Token *)
Definition at line 816 of file expr.c.
References ExprList::a, Parse::db, db, ExprList::nAlloc, ExprList::nExpr, sqlite3DbMallocZero(), sqlite3DbRealloc(), sqlite3ExprDelete(), sqlite3ExprListDelete(), and sqlite3NameFromToken().
Referenced by exprAnalyze(), multiSelectOrderBy(), selectExpander(), sqlite3CreateIndex(), sqlite3SelectNew(), updateVirtualTable(), and yy_reduce().
void sqlite3ExprListCheckLength (Parse * , ExprList * , const char *)
Definition at line 861 of file expr.c.
References sqlite3::aLimit, Parse::db, ExprList::nExpr, sqlite3ErrorMsg(), SQLITE_LIMIT_COLUMN, and testcase.
Referenced by yy_reduce().
void sqlite3ExprListDelete (sqlite3 * , ExprList *)
Definition at line 877 of file expr.c.
References ExprList::a, ExprList::nAlloc, ExprList::nExpr, sqlite3DbFree(), and sqlite3ExprDelete().
Referenced by clearSelect(), exprAnalyze(), multiSelect(), selectExpander(), sqlite3AddPrimaryKey(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3DeleteTriggerStep(), sqlite3ExprClear(), sqlite3ExprFunction(), sqlite3ExprListAppend(), sqlite3Insert(), sqlite3Select(), sqlite3TriggerInsertStep(), sqlite3TriggerUpdateStep(), sqlite3Update(), sqlitePersistTriggerStep(), yy_destructor(), and yy_reduce().
ExprList* sqlite3ExprListDup (sqlite3 * , ExprList *)
Definition at line 683 of file expr.c.
References ExprList::a, ExprList::iECursor, sqlite3::mallocFailed, ExprList::nAlloc, ExprList::nExpr, ExprList::ExprList_item::pExpr, Expr::span, sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3DbStrDup(), sqlite3ExprDup(), sqlite3TokenCopy(), and Token::z.
Referenced by codeTriggerProgram(), flattenSubquery(), multiSelectOrderBy(), sqlite3ExprDup(), sqlite3Select(), sqlite3SelectDup(), sqlitePersistTriggerStep(), and substExpr().
Expr* sqlite3ExprSetColl (Parse * pParse, Expr * , Token *)
Definition at line 66 of file expr.c.
References Parse::db, db, EP_ExpCollate, Expr::flags, Expr::pColl, sqlite3DbFree(), sqlite3LocateCollSeq(), and sqlite3NameFromToken().
Referenced by yy_reduce().
void sqlite3ExprSpan (Expr * , Token * , Token *)
Definition at line 491 of file expr.c.
References Token::n, Expr::span, and Token::z.
Referenced by sqlite3Expr(), and yy_reduce().
int sqlite3ExprWritableRegister (Parse * , int , int)
Definition at line 1669 of file expr.c.
References Parse::aColCache, Parse::iColCache, Parse::yColCache::iReg, Parse::nColCache, OP_SCopy, Parse::pVdbe, sqlite3VdbeAddOp2(), and usedAsColumnCache().
Referenced by sqlite3ExprCodeTarget(), and sqlite3ReleaseTempReg().
CollSeq* sqlite3FindCollSeq (sqlite3 * , u8 enc, const char * , int , int)
Definition at line 206 of file callback.c.
References findCollSeqEntry(), sqlite3::pDfltColl, SQLITE_UTF16BE, SQLITE_UTF16LE, and SQLITE_UTF8.
Referenced by createCollation(), openDatabase(), sqlite3ExprCollSeq(), sqlite3FindInIndex(), sqlite3GetCollSeq(), sqlite3InitOne(), sqlite3LocateCollSeq(), sqlite3Reindex(), and synthCollSeq().
int sqlite3FindDb (sqlite3 * , Token *)
Definition at line 627 of file build.c.
References sqlite3::aDb, sqlite3::nDb, OMIT_TEMPDB, sqlite3DbFree(), sqlite3NameFromToken(), sqlite3StrICmp(), and Db::zName.
Referenced by sqlite3Analyze(), and sqlite3TwoPartName().
FuncDef* sqlite3FindFunction (sqlite3 * , const char * , int , int , u8 , int)
Definition at line 326 of file callback.c.
References FuncDefHash::a, sqlite3::aFunc, ArraySize, functionSearch(), GLOBAL, FuncDef::iPrefEnc, matchQuality(), FuncDef::nArg, FuncDef::pNext, sqlite3DbMallocZero(), sqlite3FuncDefInsert(), sqlite3GlobalFunctions, sqlite3UpperToLower, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, FuncDef::xFunc, FuncDef::xStep, and FuncDef::zName.
Referenced by analyzeAggregate(), resolveExprStep(), setLikeOptFlag(), sqlite3_overload_function(), sqlite3CreateFunc(), sqlite3ExprCodeTarget(), and sqlite3IsLikeFunction().
Index* sqlite3FindIndex (sqlite3 * , const char * , const char *)
Definition at line 334 of file build.c.
References sqlite3::aDb, Schema::idxHash, sqlite3::nDb, OMIT_TEMPDB, Db::pBt, Db::pSchema, sqlite3HashFind(), sqlite3StrICmp(), sqlite3Strlen(), and Db::zName.
Referenced by analysisLoader(), sqlite3AlterRenameTable(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3InitCallback(), sqlite3Pragma(), sqlite3Reindex(), and sqlite3StartTable().
int sqlite3FindInIndex (Parse * , Expr * , int *)
Definition at line 1140 of file expr.c.
References SrcList::a, ExprList::a, Table::aCol, Column::affinity, Index::aiColumn, Index::azColl, comparisonAffinity(), Parse::db, db, ENC, Expr::iColumn, IN_INDEX_EPH, IN_INDEX_INDEX, IN_INDEX_ROWID, isCandidateForInOpt(), Expr::iTable, Index::nColumn, Parse::nMem, Column::notNull, Parse::nTab, OE_None, Index::onError, OP_If, OP_Integer, OP_OpenRead, OP_SetNumColumns, P4_KEYINFO_HANDOFF, Select::pEList, ExprList::ExprList_item::pExpr, Table::pIndex, Expr::pLeft, Index::pNext, Index::pSchema, Table::pSchema, Expr::pSelect, Select::pSrc, SrcList::SrcList_item::pTab, sqlite3BinaryCompareCollSeq(), sqlite3CodeSubselect(), sqlite3FindCollSeq(), sqlite3GetVdbe(), sqlite3IndexKeyinfo(), sqlite3OpenTable(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), sqlite3VdbeJumpHere(), sqlite3VdbeUsesBtree(), SQLITE_AFF_NONE, Index::tnum, VdbeComment, and Index::zName.
Referenced by codeEqualityTerm(), and sqlite3ExprCodeTarget().
Table* sqlite3FindTable (sqlite3 * , const char * , const char *)
Definition at line 270 of file build.c.
References sqlite3::aDb, sqlite3::nDb, OMIT_TEMPDB, Db::pSchema, sqlite3HashFind(), sqlite3StrICmp(), sqlite3Strlen(), Schema::tblHash, and Db::zName.
Referenced by openStatTable(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AnalysisLoad(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3InitOne(), sqlite3LocateTable(), sqlite3Pragma(), sqlite3Reindex(), sqlite3StartTable(), sqlite3VtabCallCreate(), and sqlite3VtabCallDestroy().
void sqlite3FinishCoding (Parse *)
Definition at line 132 of file build.c.
References Parse::apVtabLock, sqlite3::sqlite3InitInfo::busy, codeTableLocks(), Parse::colNamesSet, Parse::cookieGoto, Parse::cookieMask, Parse::cookieValue, Parse::db, db, Parse::disableColCache, Parse::explain, sqlite3::flags, sqlite3::init, sqlite3::mallocFailed, sqlite3::nDb, Parse::nErr, Parse::nested, Parse::nMem, Parse::nSet, Parse::nTab, Parse::nVar, Parse::nVtabLock, OP_Goto, OP_Halt, OP_Trace, OP_Transaction, OP_VBegin, OP_VerifyCookie, VdbeOp::opcode, P4_VTAB, Table::pVtab, Parse::rc, sqlite3GetVdbe(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeGetOp(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeReady(), sqlite3VdbeUsesBtree(), SQLITE_DONE, SQLITE_ERROR, SQLITE_OK, SQLITE_VdbeTrace, Parse::writeMask, Parse::zSql, and Parse::zTail.
Referenced by yy_reduce().
void sqlite3FinishTrigger (Parse * , TriggerStep * , Token *)
Definition at line 204 of file trigger.c.
References sqlite3::aDb, sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::init, sqlite3::mallocFailed, Token::n, Trigger::name, Trigger::nameToken, Parse::nErr, OP_ParseSchema, P4_DYNAMIC, Parse::pNewTrigger, Trigger::pNext, TriggerStep::pNext, Db::pSchema, Trigger::pSchema, Trigger::pTabSchema, TriggerStep::pTrig, Table::pTrigger, SCHEMA_TABLE, sqlite3BeginWriteOperation(), sqlite3ChangeCookie(), sqlite3DbFree(), sqlite3DbStrNDup(), sqlite3DeleteTrigger(), sqlite3DeleteTriggerStep(), sqlite3FixInit(), sqlite3FixTriggerStep(), sqlite3GetVdbe(), sqlite3HashFind(), sqlite3HashInsert(), sqlite3MPrintf(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp4(), Trigger::step_list, Trigger::table, Schema::tblHash, Schema::trigHash, Token::z, and Db::zName.
Referenced by yy_reduce().
int sqlite3FitsIn64Bits (const char * , int)
Definition at line 404 of file util.c.
References compare2pow63().
Referenced by codeInteger().
int sqlite3FixExpr (DbFixer * , Expr *)
Definition at line 481 of file attach.c.
References Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, sqlite3FixExpr(), sqlite3FixExprList(), and sqlite3FixSelect().
Referenced by sqlite3FixExpr(), sqlite3FixExprList(), sqlite3FixSelect(), sqlite3FixSrcList(), and sqlite3FixTriggerStep().
int sqlite3FixExprList (DbFixer * , ExprList *)
Definition at line 499 of file attach.c.
References ExprList::a, and sqlite3FixExpr().
Referenced by sqlite3FixExpr(), sqlite3FixSelect(), and sqlite3FixTriggerStep().
int sqlite3FixInit (DbFixer * , Parse * , int , const char * , const Token *)
Definition at line 400 of file attach.c.
References sqlite3::aDb, Parse::db, db, sqlite3::nDb, DbFixer::pName, DbFixer::pParse, DbFixer::zDb, Db::zName, and DbFixer::zType.
Referenced by sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3CreateView(), and sqlite3FinishTrigger().
int sqlite3FixSelect (DbFixer * , Select *)
Definition at line 460 of file attach.c.
References Select::pEList, Select::pHaving, Select::pPrior, Select::pSrc, Select::pWhere, sqlite3FixExpr(), sqlite3FixExprList(), and sqlite3FixSrcList().
Referenced by sqlite3CreateView(), sqlite3FixExpr(), sqlite3FixSrcList(), and sqlite3FixTriggerStep().
int sqlite3FixSrcList (DbFixer * , SrcList *)
Definition at line 433 of file attach.c.
References SrcList::a, Parse::db, DbFixer::pName, DbFixer::pParse, sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3FixExpr(), sqlite3FixSelect(), sqlite3StrICmp(), DbFixer::zDb, and DbFixer::zType.
Referenced by sqlite3BeginTrigger(), sqlite3CreateIndex(), and sqlite3FixSelect().
int sqlite3FixTriggerStep (DbFixer * , TriggerStep *)
Definition at line 516 of file attach.c.
References TriggerStep::pExprList, TriggerStep::pNext, TriggerStep::pSelect, TriggerStep::pWhere, sqlite3FixExpr(), sqlite3FixExprList(), and sqlite3FixSelect().
Referenced by sqlite3FinishTrigger().
void sqlite3FuncDefInsert (FuncDefHash * , FuncDef *)
Definition at line 285 of file callback.c.
References FuncDefHash::a, ArraySize, functionSearch(), FuncDef::pHash, FuncDef::pNext, sqlite3UpperToLower, and FuncDef::zName.
Referenced by sqlite3FindFunction(), sqlite3RegisterDateTimeFunctions(), and sqlite3RegisterGlobalFunctions().
void sqlite3GenerateConstraintChecks (Parse * , Table * , int , int , int * , int , int , int , int)
Definition at line 1083 of file insert.c.
References Table::aCol, Index::aiColumn, Parse::ckBase, Parse::db, sqlite3::flags, Table::iPKey, Table::keyConf, Table::nCol, Index::nColumn, Column::notNull, OE_Abort, OE_Default, OE_Fail, OE_Ignore, OE_None, OE_Replace, OE_Rollback, Index::onError, OP_Eq, OP_Goto, OP_Halt, OP_IsNull, OP_IsUnique, OP_MakeRecord, OP_NotExists, OP_NotNull, OP_SCopy, P4_DYNAMIC, P4_INT32, P4_STATIC, Table::pCheck, Column::pDflt, Table::pIndex, Index::pNext, Table::pSelect, sqlite3_snprintf(), sqlite3ExprCacheAffinityChange(), sqlite3ExprCode(), sqlite3ExprIfTrue(), sqlite3GenerateRowDelete(), sqlite3GenerateRowIndexDelete(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3IndexAffinityStr(), sqlite3MPrintf(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP4(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), SQLITE_CONSTRAINT, SQLITE_IgnoreChecks, SQLITE_INT_TO_PTR, SQLITE_JUMPIFNULL, Column::zName, and Table::zName.
Referenced by sqlite3Insert(), and sqlite3Update().
int sqlite3GenerateIndexKey (Parse * , Index * , int , int , int)
Definition at line 598 of file delete.c.
References Index::aiColumn, Table::iPKey, Index::nColumn, OP_Column, OP_MakeRecord, OP_Rowid, OP_SCopy, Index::pTable, Parse::pVdbe, sqlite3ColumnDefault(), sqlite3ExprCacheAffinityChange(), sqlite3GetTempRange(), sqlite3IndexAffinityStr(), sqlite3ReleaseTempRange(), sqlite3VdbeAddOp2(), and sqlite3VdbeAddOp3().
Referenced by sqlite3GenerateRowIndexDelete(), sqlite3Pragma(), and sqlite3RefillIndex().
void sqlite3GenerateRowDelete (Parse * , Table * , int , int , int)
Definition at line 534 of file delete.c.
References OP_Delete, OP_NotExists, OPFLAG_NCHANGE, P4_STATIC, Parse::pVdbe, sqlite3GenerateRowIndexDelete(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeChangeP4(), sqlite3VdbeJumpHere(), and Table::zName.
Referenced by sqlite3DeleteFrom(), and sqlite3GenerateConstraintChecks().
void sqlite3GenerateRowIndexDelete (Parse * , Table * , int , int *)
Definition at line 570 of file delete.c.
References Index::nColumn, OP_IdxDelete, Table::pIndex, Index::pNext, Parse::pVdbe, sqlite3GenerateIndexKey(), and sqlite3VdbeAddOp3().
Referenced by sqlite3GenerateConstraintChecks(), sqlite3GenerateRowDelete(), and sqlite3Update().
u32 sqlite3Get4byte (const u8 *)
Definition at line 810 of file util.c.
Referenced by pager_incr_changecounter(), and read32bits().
int sqlite3GetBuiltinFunction (const char * , int , FuncDef **)
CollSeq* sqlite3GetCollSeq (sqlite3 * , CollSeq * , const char * , int)
Definition at line 86 of file callback.c.
References callCollNeeded(), ENC, sqlite3FindCollSeq(), synthCollSeq(), and CollSeq::xCmp.
Referenced by sqlite3CheckCollSeq(), and sqlite3LocateCollSeq().
int sqlite3GetInt32 (const char * , int *)
Definition at line 438 of file util.c.
Referenced by codeInteger(), sqlite3ExprIsInteger(), and sqlite3Pragma().
int sqlite3GetTempRange (Parse * , int)
Definition at line 3081 of file expr.c.
References Parse::iRangeReg, Parse::nMem, Parse::nRangeReg, and usedAsColumnCache().
Referenced by codeAttach(), generateOutputSubroutine(), multiSelectOrderBy(), pushOntoSorter(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3GenerateIndexKey(), sqlite3Insert(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), and updateAccumulator().
int sqlite3GetTempReg (Parse *)
Definition at line 3065 of file expr.c.
References Parse::aTempReg, Parse::nMem, and Parse::nTempReg.
Referenced by codeDistinct(), destroyRootPage(), generateOutputSubroutine(), generateSortTail(), multiSelect(), pushOntoSorter(), selectInnerLoop(), sqlite3ChangeCookie(), sqlite3CodeSubselect(), sqlite3CompleteInsertion(), sqlite3ExprCodeTarget(), sqlite3ExprCodeTemp(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3MinimumFileFormat(), sqlite3RefillIndex(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), and xferOptimization().
int sqlite3GetToken (const unsigned char * , int *)
Definition at line 123 of file tokenize.c.
References IdChar, keywordCode(), TK_BITAND, TK_BITNOT, TK_BITOR, TK_BLOB, TK_COMMA, TK_CONCAT, TK_DOT, TK_EQ, TK_FLOAT, TK_GE, TK_GT, TK_ID, TK_ILLEGAL, TK_INTEGER, TK_LE, TK_LP, TK_LSHIFT, TK_LT, TK_MINUS, TK_NE, TK_PLUS, TK_REGISTER, TK_REM, TK_RP, TK_RSHIFT, TK_SEMI, TK_SLASH, TK_SPACE, TK_STAR, TK_STRING, and TK_VARIABLE.
Referenced by renameTableFunc(), renameTriggerFunc(), and sqlite3RunParser().
int sqlite3GetVarint (const unsigned char * , u64 *)
Definition at line 552 of file util.c.
Referenced by sqlite3GetVarint32().
int sqlite3GetVarint32 (const unsigned char * , u32 *)
Definition at line 714 of file util.c.
References sqlite3GetVarint().
Vdbe* sqlite3GetVdbe (Parse *)
Definition at line 1303 of file select.c.
References Parse::db, OP_Trace, Parse::pVdbe, sqlite3VdbeAddOp0(), and sqlite3VdbeCreate().
Referenced by analyzeOneTable(), codeAttach(), codeTableLocks(), computeLimitRegisters(), destroyRootPage(), flagPragma(), loadAnalysis(), multiSelect(), openStatTable(), reloadTableSchema(), returnSingleInt(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTransaction(), sqlite3BeginWriteOperation(), sqlite3CodeSubselect(), sqlite3CodeVerifySchema(), sqlite3CommitTransaction(), sqlite3CompleteInsertion(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3ExprCodeExprList(), sqlite3FindInIndex(), sqlite3FinishCoding(), sqlite3FinishTrigger(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3MinimumFileFormat(), sqlite3OpenMasterTable(), sqlite3OpenTable(), sqlite3OpenTableAndIndices(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3RollbackTransaction(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), sqlite3Vacuum(), sqlite3VtabFinishParse(), and xferOptimization().
void* sqlite3HexToBlob (sqlite3 * , const char * z, int n)
Definition at line 847 of file util.c.
References hexToInt(), and sqlite3DbMallocRaw().
Referenced by sqlite3ExprCodeTarget(), and sqlite3ValueFromExpr().
IdList* sqlite3IdListAppend (sqlite3 * , IdList * , Token *)
Definition at line 2944 of file build.c.
References IdList::a, IdList::nAlloc, IdList::nId, sqlite3ArrayAllocate(), sqlite3DbMallocZero(), sqlite3IdListDelete(), sqlite3NameFromToken(), and IdList::IdList_item::zName.
Referenced by yy_reduce().
void sqlite3IdListDelete (sqlite3 * , IdList *)
Definition at line 2971 of file build.c.
References IdList::a, IdList::nId, sqlite3DbFree(), and IdList::IdList_item::zName.
Referenced by sqlite3BeginTrigger(), sqlite3DeleteTrigger(), sqlite3DeleteTriggerStep(), sqlite3IdListAppend(), sqlite3Insert(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListDelete(), sqlite3TriggerInsertStep(), sqlitePersistTriggerStep(), and yy_destructor().
IdList* sqlite3IdListDup (sqlite3 * , IdList *)
Definition at line 760 of file expr.c.
References IdList::a, IdList::nAlloc, IdList::nId, sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3DbStrDup(), and IdList::IdList_item::zName.
Referenced by codeTriggerProgram(), sqlite3BeginTrigger(), sqlite3SrcListDup(), and sqlitePersistTriggerStep().
int sqlite3IdListIndex (IdList * , const char *)
Definition at line 2985 of file build.c.
References IdList::a, IdList::nId, sqlite3StrICmp(), and IdList::IdList_item::zName.
Referenced by checkColumnOverLap(), and selectExpander().
int sqlite3IndexAffinityOk (Expr * pExpr, char idx_affinity)
Definition at line 175 of file expr.c.
References comparisonAffinity(), sqlite3IsNumericAffinity, SQLITE_AFF_NONE, and SQLITE_AFF_TEXT.
Referenced by findTerm().
void sqlite3IndexAffinityStr (Vdbe * , Index *)
Definition at line 35 of file insert.c.
References Table::aCol, Column::affinity, Index::aiColumn, db, sqlite3::mallocFailed, Index::nColumn, Index::pTable, sqlite3Malloc(), sqlite3VdbeChangeP4(), sqlite3VdbeDb(), SQLITE_AFF_NONE, and Index::zColAff.
Referenced by codeApplyAffinity(), sqlite3GenerateConstraintChecks(), and sqlite3GenerateIndexKey().
int sqlite3IndexedByLookup (Parse * , struct SrcList_item *)
Definition at line 2949 of file select.c.
References Table::pIndex, Index::pNext, sqlite3ErrorMsg(), sqlite3StrICmp(), SQLITE_ERROR, SQLITE_OK, and Index::zName.
Referenced by selectExpander(), and sqlite3SrcListLookup().
KeyInfo* sqlite3IndexKeyinfo (Parse * , Index *)
Definition at line 3551 of file build.c.
References KeyInfo::aColl, Index::aSortOrder, KeyInfo::aSortOrder, Index::azColl, KeyInfo::db, Parse::db, db, Index::nColumn, Parse::nErr, sqlite3DbFree(), sqlite3DbMallocZero(), and sqlite3LocateCollSeq().
Referenced by analyzeOneTable(), sqlite3FindInIndex(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Update(), sqlite3WhereBegin(), and xferOptimization().
int sqlite3Init (sqlite3 * , char **)
Definition at line 391 of file prepare.c.
References sqlite3::sqlite3InitInfo::busy, DB_SchemaLoaded, DbHasProperty, sqlite3::flags, sqlite3::init, sqlite3::mutex, sqlite3::nDb, sqlite3_mutex_held, sqlite3CommitInternalChanges(), sqlite3InitOne(), sqlite3ResetInternalSchema(), SQLITE_InternChanges, and SQLITE_OK.
Referenced by attachFunc(), and sqlite3ReadSchema().
int sqlite3InitCallback (void * , int , char ** , char **)
Definition at line 55 of file prepare.c.
References sqlite3::aDb, Lookaside::bEnabled, sqlite3::sqlite3InitInfo::busy, corruptSchema(), InitData::db, db, DB_Empty, DbClearProperty, sqlite3::sqlite3InitInfo::iDb, InitData::iDb, sqlite3::init, sqlite3::lookaside, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::sqlite3InitInfo::newTnum, InitData::rc, sqlite3_exec(), sqlite3_mutex_held, sqlite3DbFree(), sqlite3FindIndex(), SQLITE_INTERRUPT, SQLITE_NOMEM, SQLITE_OK, Index::tnum, and Db::zName.
Referenced by sqlite3InitOne(), and sqlite3VdbeExec().
void sqlite3Insert (Parse * , SrcList * , ExprList * , Select * , IdList * , int)
Definition at line 359 of file insert.c.
References IdList::a, ExprList::a, SrcList::a, Table::aCol, sqlite3::aDb, autoIncBegin(), autoIncEnd(), autoIncStep(), COLNAME_NAME, Parse::db, db, sqlite3::flags, IdList::IdList_item::idx, SelectDest::iMem, SelectDest::iParm, Table::iPKey, IsHiddenColumn, IsVirtual, sqlite3::mallocFailed, Table::nCol, Parse::nErr, Parse::nested, ExprList::nExpr, IdList::nId, SelectDest::nMem, Parse::nMem, SrcList::nSrc, Parse::nTab, OE_Abort, OP_AddImm, OP_Close, OP_Column, OP_Goto, OP_Halt, OP_If, OP_Insert, OP_Integer, OP_IsNull, OP_MakeRecord, OP_MustBeInt, OP_NewRowid, OP_Next, OP_NotNull, OP_Null, OP_OpenEphemeral, OP_OpenPseudo, OP_OpenWrite, OP_ResultRow, OP_Rewind, OP_SCopy, OP_SetNumColumns, OP_VUpdate, OP_Yield, VdbeOp::opcode, VdbeOp::p1, VdbeOp::p2, VdbeOp::p3, P4_VTAB, Column::pDflt, Select::pEList, ExprList::ExprList_item::pExpr, Table::pIndex, Index::pNext, NameContext::pParse, Table::pSchema, Table::pSelect, Table::pVtab, readsTable(), sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3CodeRowTrigger(), sqlite3CompleteInsertion(), sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3ErrorMsg(), sqlite3ExprCode(), sqlite3ExprCodeAndCache(), sqlite3ExprListDelete(), sqlite3GenerateConstraintChecks(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3IdListDelete(), sqlite3IsReadOnly(), sqlite3IsRowid(), sqlite3OpenTableAndIndices(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3ResolveExprNames(), sqlite3SchemaToIndex(), sqlite3Select(), sqlite3SelectDelete(), sqlite3SelectDestInit(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StrICmp(), sqlite3TableAffinityStr(), sqlite3TriggersExist(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeCountChanges(), sqlite3VdbeCurrentAddr(), sqlite3VdbeGetOp(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3ViewGetColumnNames(), sqlite3VtabMakeWritable(), SQLITE_CountRows, SQLITE_INSERT, SQLITE_INTERNAL, SQLITE_STATIC, SRT_Coroutine, TK_INSERT, TRIGGER_AFTER, TRIGGER_BEFORE, Parse::trigStack, VdbeComment, xferOptimization(), Column::zName, IdList::IdList_item::zName, Table::zName, Db::zName, and SrcList::SrcList_item::zName.
Referenced by codeTriggerProgram(), and yy_reduce().
void sqlite3InvalidFunction (sqlite3_context * , int , sqlite3_value **)
Definition at line 602 of file vdbeapi.c.
References sqlite3_context::pFunc, sqlite3_free(), sqlite3_result_error(), sqlite3MPrintf(), and FuncDef::zName.
Referenced by sqlite3_overload_function().
int sqlite3InvokeBusyHandler (BusyHandler *)
Definition at line 766 of file main.c.
References BusyHandler::nBusy, NEVER, BusyHandler::pArg, and BusyHandler::xFunc.
Referenced by pager_wait_on_lock(), and sqlite3BtreeInvokeBusyHandler().
int sqlite3IsLikeFunction (sqlite3 * , Expr * , int * , char *)
Definition at line 1271 of file func.c.
References FuncDef::flags, compareInfo::matchAll, Token::n, ExprList::nExpr, Expr::op, Expr::pList, FuncDef::pUserData, sqlite3FindFunction(), SQLITE_FUNC_CASE, SQLITE_FUNC_LIKE, SQLITE_UTF8, TK_FUNCTION, Expr::token, and Token::z.
Referenced by isLikeOrGlob().
int sqlite3IsMemJournal (sqlite3_file *)
Definition at line 232 of file memjournal.c.
References sqlite3_file::pMethods.
Referenced by pager_end_transaction(), and sqlite3PagerStmtCommit().
int sqlite3IsNaN (double)
Definition at line 27 of file util.c.
Referenced by codeReal(), sqlite3_initialize(), sqlite3VdbeExec(), sqlite3VdbeMemSetDouble(), sqlite3VdbeSerialGet(), and sqlite3VXPrintf().
int sqlite3IsNumber (const char * , int * , u8)
Definition at line 214 of file util.c.
References SQLITE_UTF16BE, and SQLITE_UTF8.
Referenced by applyNumericAffinity(), and parseDateOrTime().
int sqlite3IsReadOnly (Parse * , Table * , int)
Definition at line 45 of file delete.c.
References Parse::db, sqlite3::flags, Parse::nested, Table::pMod, Module::pModule, Table::pSelect, sqlite3ErrorMsg(), SQLITE_WriteSchema, Table::tabFlags, TF_Readonly, sqlite3_module::xUpdate, and Table::zName.
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
int sqlite3IsRowid (const char *)
Definition at line 1032 of file expr.c.
References sqlite3StrICmp().
Referenced by lookupName(), sqlite3Insert(), and sqlite3Update().
int sqlite3JoinType (Parse * , Token * , Token * , Token *)
Definition at line 124 of file select.c.
References JT_CROSS, JT_ERROR, JT_INNER, JT_LEFT, JT_NATURAL, JT_OUTER, JT_RIGHT, Token::n, sqlite3ErrorMsg(), sqlite3StrNICmp(), and Token::z.
Referenced by yy_reduce().
int sqlite3KeywordCode (const unsigned char * , int)
Definition at line 110 of file keywordhash.h.
References keywordCode().
Referenced by identPut().
CollSeq* sqlite3LocateCollSeq (Parse * pParse, const char * zName, int nName)
Definition at line 1263 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, ENC, sqlite3::init, sqlite3ErrorMsg(), sqlite3FindCollSeq(), sqlite3GetCollSeq(), sqlite3Strlen(), and CollSeq::xCmp.
Referenced by sqlite3AddCollateType(), sqlite3CreateIndex(), sqlite3ExprSetColl(), and sqlite3IndexKeyinfo().
Table* sqlite3LocateTable (Parse * , int isView, const char * , const char *)
Definition at line 295 of file build.c.
References Parse::checkSchema, Parse::db, sqlite3ErrorMsg(), sqlite3FindTable(), sqlite3ReadSchema(), and SQLITE_OK.
Referenced by selectExpander(), sqlite3_blob_open(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3Analyze(), sqlite3CreateIndex(), sqlite3DropTable(), sqlite3SrcListLookup(), and xferOptimization().
void* sqlite3Malloc (int)
Definition at line 264 of file malloc.c.
References mallocWithAlarm(), mem0, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3GlobalConfig.
Referenced by balance_shallower(), contextMalloc(), createTableStmt(), pager_delmaster(), pcacheMalloc(), pcacheResizeHash(), saveCursorPosition(), schemaIsValid(), setupLookaside(), sqlite3_exec(), sqlite3_malloc(), sqlite3BtreeIntegrityCheck(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeOpen(), sqlite3DbMallocRaw(), sqlite3HashInsert(), sqlite3IndexAffinityStr(), sqlite3MallocZero(), sqlite3OsOpenMalloc(), sqlite3PagerOpen(), sqlite3Realloc(), sqlite3RunParser(), sqlite3TableAffinityStr(), sqlite3VdbeChangeP4(), sqlite3VdbeExec(), and sqlite3VXPrintf().
void sqlite3MallocEnd (void)
Definition at line 154 of file malloc.c.
References mem0, and sqlite3GlobalConfig.
Referenced by sqlite3_shutdown().
int sqlite3MallocInit (void)
Definition at line 112 of file malloc.c.
References mem0, sqlite3GlobalConfig, sqlite3MemSetDefault(), sqlite3MutexAlloc, and SQLITE_MUTEX_STATIC_MEM.
Referenced by sqlite3_initialize().
int sqlite3MallocSize (void *)
Definition at line 502 of file malloc.c.
References sqlite3GlobalConfig.
Referenced by mallocWithAlarm(), pcacheFree(), pcacheMalloc(), sqlite3_free(), sqlite3Realloc(), and sqlite3ScratchFree().
void* sqlite3MallocZero (int)
Definition at line 600 of file malloc.c.
References sqlite3Malloc().
Referenced by accessPayload(), lockTable(), openDatabase(), rehash(), sqlite3BitvecCreate(), sqlite3BtreeOpen(), sqlite3BtreeSchema(), sqlite3InitOne(), sqlite3PagerOpen(), and sqlite3SchemaGet().
char* sqlite3MAppendf (sqlite3 * , char * , const char * , ...)
Definition at line 847 of file printf.c.
References sqlite3DbFree(), and sqlite3VMPrintf().
Referenced by corruptSchema(), and sqlite3WhereBegin().
void sqlite3MaterializeView (Parse * , Table * , Expr * , int)
Definition at line 92 of file delete.c.
References Parse::db, db, Token::n, Table::pSelect, sqlite3ExprDup(), sqlite3Select(), sqlite3SelectDelete(), sqlite3SelectDestInit(), sqlite3SelectDup(), sqlite3SelectNew(), sqlite3SrcListAppendFromTerm(), SRT_EphemTab, Token::z, and Table::zName.
Referenced by sqlite3DeleteFrom(), and sqlite3Update().
const sqlite3_mem_methods* sqlite3MemGetMemsys3 (void)
Referenced by sqlite3_config().
const sqlite3_mem_methods* sqlite3MemGetMemsys5 (void)
Referenced by sqlite3_config().
void sqlite3MemJournalOpen (sqlite3_file *)
Definition at line 222 of file memjournal.c.
References MemJournal::pMethod, and sqlite3MemJournalSize().
Referenced by memjrnlTruncate(), pager_open_journal(), and pagerStmtBegin().
int sqlite3MemJournalSize ()
Definition at line 240 of file memjournal.c.
Referenced by sqlite3MemJournalOpen(), and sqlite3PagerOpen().
int sqlite3MemoryAlarm (void(*)(void *, sqlite3_int64, int) , void * , sqlite3_int64)
void sqlite3MemSetDefault (void)
Referenced by sqlite3_config(), and sqlite3MallocInit().
void sqlite3MinimumFileFormat (Parse * , int , int)
Definition at line 2770 of file build.c.
References OP_Ge, OP_Integer, OP_ReadCookie, OP_SetCookie, sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3ReleaseTempReg(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeJumpHere(), and sqlite3VdbeUsesBtree().
Referenced by sqlite3AlterFinishAddColumn().
char* sqlite3MPrintf (sqlite3 * , const char * , ...)
Definition at line 830 of file printf.c.
References sqlite3VMPrintf().
Referenced by generateColumnNames(), reloadTableSchema(), renameTableFunc(), renameTriggerFunc(), selectColumnsFromExprList(), selectExpander(), setQuotedToken(), sqlite3AnalysisLoad(), sqlite3CodeRowTrigger(), sqlite3CreateIndex(), sqlite3EndTable(), sqlite3FinishTrigger(), sqlite3GenerateConstraintChecks(), sqlite3InitOne(), sqlite3InvalidFunction(), sqlite3Pragma(), sqlite3RunParser(), sqlite3VdbeExec(), sqlite3VtabCallCreate(), sqlite3VtabFinishParse(), sqlite3WhereBegin(), vdbeCommit(), vtabCallConstructor(), and whereTempTriggers().
char* sqlite3NameFromToken (sqlite3 * , Token *)
Definition at line 599 of file build.c.
References Token::n, sqlite3DbStrNDup(), sqlite3Dequote(), Token::z, and Db::zName.
Referenced by codeAttach(), lookupName(), resolveAsName(), selectExpander(), sqlite3AddCollateType(), sqlite3AddColumn(), sqlite3AddColumnType(), sqlite3AlterRenameTable(), sqlite3Analyze(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3ExprListAppend(), sqlite3ExprSetColl(), sqlite3FindDb(), sqlite3IdListAppend(), sqlite3Pragma(), sqlite3Reindex(), sqlite3SrcListAppend(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListIndexedBy(), sqlite3StartTable(), and sqlite3VtabBeginParse().
void sqlite3NestedParse (Parse * , const char * , ...)
Definition at line 232 of file build.c.
References Parse::db, db, Parse::nErr, Parse::nested, Parse::nVar, SAVE_SZ, sqlite3DbFree(), sqlite3RunParser(), and sqlite3VMPrintf().
Referenced by destroyRootPage(), openStatTable(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3EndTable(), sqlite3FinishTrigger(), and sqlite3VtabFinishParse().
void sqlite3OpenMasterTable (Parse * , int)
Definition at line 614 of file build.c.
References MASTER_ROOT, OP_OpenWrite, OP_SetNumColumns, SCHEMA_TABLE, sqlite3GetVdbe(), sqlite3TableLock(), sqlite3VdbeAddOp2(), and sqlite3VdbeAddOp3().
Referenced by sqlite3DropTriggerPtr(), and sqlite3StartTable().
void sqlite3OpenTable (Parse * , int iCur, int iDb, Table * , int)
Definition at line 68 of file delete.c.
References IsVirtual, Table::nCol, OP_OpenRead, OP_OpenWrite, OP_SetNumColumns, sqlite3GetVdbe(), sqlite3TableLock(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), Table::tnum, VdbeComment, and Table::zName.
Referenced by autoIncBegin(), autoIncEnd(), sqlite3FindInIndex(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Update(), sqlite3WhereBegin(), and xferOptimization().
int sqlite3OpenTableAndIndices (Parse * , Table * , int , int)
Definition at line 1385 of file insert.c.
References Parse::db, IsVirtual, Parse::nTab, P4_KEYINFO_HANDOFF, Table::pIndex, Index::pNext, Index::pSchema, Table::pSchema, sqlite3GetVdbe(), sqlite3IndexKeyinfo(), sqlite3OpenTable(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp4(), Index::tnum, VdbeComment, and Index::zName.
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Pragma().
int sqlite3OpenTempDatabase (Parse *)
Definition at line 3307 of file build.c.
References sqlite3::aDb, sqlite3::autoCommit, Parse::db, db, sqlite3::dfltJournalMode, Parse::explain, sqlite3::flags, Db::pBt, Db::pSchema, Parse::rc, sqlite3BtreeFactory(), sqlite3BtreePager(), sqlite3ErrorMsg(), sqlite3PagerJournalMode(), SQLITE_DEFAULT_CACHE_SIZE, SQLITE_InTrans, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_DELETEONCLOSE, SQLITE_OPEN_EXCLUSIVE, SQLITE_OPEN_READWRITE, and SQLITE_OPEN_TEMP_DB.
Referenced by sqlite3CodeVerifySchema(), and sqlite3Pragma().
void sqlite3PageFree (void *)
Definition at line 462 of file pcache.c.
References pcacheEnterMutex, pcacheExitMutex, and pcacheFree().
Referenced by balance_nonroot(), checkTreePage(), freeTempSpace(), sqlite3PagerClose(), and sqlite3PagerSetPagesize().
void* sqlite3PageMalloc (int)
Definition at line 436 of file pcache.c.
References pcacheEnterMutex, pcacheExitMutex, and pcacheMalloc().
Referenced by allocateTempSpace(), balance_nonroot(), checkTreePage(), sqlite3PagerOpen(), and sqlite3PagerSetPagesize().
void sqlite3Parser (void * , int , Token , Parse *)
void* sqlite3ParserAlloc (void * *)(size_t)
void sqlite3ParserFree (void * , void(*)(void *))
Definition at line 1410 of file parse.c.
References yy_pop_parser_stack(), yyParser::yyidx, and yyParser::yystack.
Referenced by sqlite3RunParser().
Expr* sqlite3PExpr (Parse * , int , Expr * , Expr * , const Token *)
Definition at line 432 of file expr.c.
References Parse::db, sqlite3Expr(), and sqlite3ExprCheckHeight.
Referenced by addWhereTerm(), exprAnalyze(), multiSelectOrderBy(), resolveAlias(), selectExpander(), sqlite3CodeSubselect(), sqlite3CreateIdExpr(), sqlite3RegisterExpr(), and yy_reduce().
void sqlite3Pragma (Parse * , Token * , Token * , Token * , int)
Definition at line 249 of file pragma.c.
References FKey::aCol, Table::aCol, sqlite3::aCollSeq, actionName(), sqlite3::aDb, Index::aiColumn, ArraySize, sqlite3::autoCommit, Schema::cache_size, changeTempStorage(), COLNAME_NAME, Parse::db, db, DB_Empty, DB_SchemaLoaded, DbHasProperty, FKey::deleteConf, sqlite3::dfltJournalMode, sqlite3::dfltLockMode, ENC, flagPragma(), sqlite3::flags, getAutoVacuum(), getBoolean(), getLockingMode(), getSafetyLevel(), FKey::sColMap::iFrom, invalidateTempStorage(), IsHiddenColumn, Column::isPrimKey, sqlite3::mallocFailed, Token::n, FKey::nCol, Table::nCol, Index::nColumn, sqlite3::nDb, sqlite3::nextAutovac, sqlite3::nextPagesize, Parse::nMem, Column::notNull, OE_Abort, OE_None, OMIT_TEMPDB, Index::onError, OP_AddImm, OP_Concat, OP_Eq, OP_Expire, OP_Found, OP_Halt, OP_If, OP_IfNeg, OP_IfPos, OP_IncrVacuum, OP_Integer, OP_IntegrityCk, OP_IsNull, OP_Move, OP_Next, OP_Null, OP_OpenRead, OP_Pagecount, OP_ReadCookie, OP_ResultRow, OP_Rewind, OP_Rowid, OP_SetCookie, OP_String8, OP_Subtract, OP_Transaction, P4_DYNAMIC, P4_STATIC, PAGER_JOURNALMODE_DELETE, PAGER_JOURNALMODE_MEMORY, PAGER_JOURNALMODE_OFF, PAGER_JOURNALMODE_PERSIST, PAGER_JOURNALMODE_QUERY, PAGER_JOURNALMODE_TRUNCATE, PAGER_LOCKINGMODE_EXCLUSIVE, PAGER_LOCKINGMODE_NORMAL, PAGER_LOCKINGMODE_QUERY, Db::pBt, Column::pDflt, Table::pFKey, Table::pIndex, Index::pNext, FKey::pNextFrom, Db::pSchema, Index::pTable, Parse::pVdbe, sqlite3::pVfs, returnSingleInt(), Db::safety_level, Expr::span, sqlite3_file_control(), sqlite3_free(), sqlite3_key(), sqlite3_temp_directory, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3BtreeGetAutoVacuum(), sqlite3BtreeGetFilename(), sqlite3BtreeGetPageSize(), sqlite3BtreeMaxPageCount(), sqlite3BtreePager(), sqlite3BtreeSetAutoVacuum(), sqlite3BtreeSetCacheSize(), sqlite3BtreeSetPageSize(), sqlite3BtreeSetSafetyLevel(), sqlite3CodeVerifySchema(), sqlite3DbFree(), sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GenerateIndexKey(), sqlite3GetInt32(), sqlite3GetVdbe(), sqlite3MPrintf(), sqlite3NameFromToken(), sqlite3OpenTableAndIndices(), sqlite3OpenTempDatabase(), sqlite3OsAccess(), sqlite3PagerJournalMode(), sqlite3PagerJournalSizeLimit(), sqlite3PagerLockingMode(), sqlite3ReadSchema(), sqlite3RegisterLikeFunctions(), sqlite3StrICmp(), sqlite3StrNICmp(), sqlite3TwoPartName(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeAddOpList(), sqlite3VdbeChangeP1(), sqlite3VdbeChangeP2(), sqlite3VdbeChangeP3(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), sqlite3VdbeCreate(), sqlite3VdbeJumpHere(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3VdbeUsesBtree(), sqlite3ViewGetColumnNames(), SQLITE_ACCESS_READWRITE, SQLITE_DEFAULT_AUTOVACUUM, SQLITE_DEFAULT_CACHE_SIZE, SQLITE_FCNTL_LOCKSTATE, SQLITE_FullFSync, SQLITE_INTEGRITY_CHECK_ERROR_MAX, SQLITE_NOMEM, SQLITE_OK, SQLITE_PRAGMA, SQLITE_STATIC, SQLITE_TEMP_STORE, SQLITE_TRANSIENT, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF16NATIVE, SQLITE_UTF8, sqliteHashData, sqliteHashFirst, sqliteHashNext, Schema::tblHash, sqlite3::temp_store, Index::tnum, Table::tnum, FKey::updateConf, Token::z, FKey::sColMap::zCol, CollSeq::zName, Index::zName, Column::zName, Db::zName, FKey::zTo, and Column::zType.
Referenced by yy_reduce().
void sqlite3PrngResetState (void)
Definition at line 144 of file random.c.
References GLOBAL, and sqlite3Prng.
Referenced by sqlite3_test_control().
void sqlite3PrngRestoreState (void)
Definition at line 137 of file random.c.
References GLOBAL, and sqlite3Prng.
Referenced by sqlite3_test_control().
void sqlite3PrngSaveState (void)
Definition at line 130 of file random.c.
References GLOBAL, and sqlite3Prng.
Referenced by sqlite3_test_control().
void sqlite3Put4byte (u8 * , u32)
int sqlite3PutVarint (unsigned char * , u64)
Definition at line 500 of file util.c.
Referenced by sqlite3PutVarint32().
int sqlite3PutVarint32 (unsigned char * , u32)
Definition at line 533 of file util.c.
References sqlite3PutVarint().
int sqlite3ReadSchema (Parse * pParse)
Definition at line 432 of file prepare.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::init, sqlite3::mutex, Parse::nErr, Parse::rc, sqlite3_mutex_held, sqlite3Init(), SQLITE_OK, and Parse::zErrMsg.
Referenced by sqlite3Analyze(), sqlite3CreateIndex(), sqlite3DropIndex(), sqlite3DropTrigger(), sqlite3LocateTable(), sqlite3Pragma(), sqlite3Reindex(), and sqlite3StartTable().
void* sqlite3Realloc (void * , int)
Definition at line 546 of file malloc.c.
References mem0, sqlite3_free(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3GlobalConfig, sqlite3Malloc(), sqlite3MallocAlarm(), sqlite3MallocSize(), sqlite3StatusAdd(), sqlite3StatusSet(), sqlite3StatusValue(), SQLITE_STATUS_MALLOC_SIZE, and SQLITE_STATUS_MEMORY_USED.
Referenced by sqlite3_realloc().
void sqlite3RegisterBuiltinFunctions (sqlite3 *)
Definition at line 1216 of file func.c.
References sqlite3::mallocFailed, sqlite3_overload_function(), sqlite3AlterFunctions(), SQLITE_NOMEM, and SQLITE_OK.
Referenced by openDatabase().
void sqlite3RegisterDateTimeFunctions (void)
Definition at line 1055 of file date.c.
References ArraySize, cdateFunc(), ctimeFunc(), ctimestampFunc(), dateFunc(), datetimeFunc(), FUNCTION, GLOBAL, juliandayFunc(), sqlite3FuncDefInsert(), sqlite3GlobalFunctions, SQLITE_WSD, STR_FUNCTION, strftimeFunc(), and timeFunc().
Referenced by sqlite3RegisterGlobalFunctions().
Expr* sqlite3RegisterExpr (Parse * , Token *)
Definition at line 456 of file expr.c.
References Expr::iTable, Parse::nested, Parse::pVdbe, sqlite3ErrorMsg(), sqlite3PExpr(), TK_NULL, TK_REGISTER, and Token::z.
Referenced by yy_reduce().
void sqlite3RegisterGlobalFunctions (void)
Definition at line 1304 of file func.c.
References absFunc(), AGGREGATE, ArraySize, avgFinalize(), changes(), countFinalize(), countStep(), FUNCTION, GLOBAL, groupConcatFinalize(), groupConcatStep(), hexFunc(), ifnullFunc(), last_insert_rowid(), lengthFunc(), LIKEFUNC, loadExt(), lowerFunc(), minMaxFinalize(), minmaxFunc(), minmaxStep(), nullifFunc(), quoteFunc(), randomBlob(), randomFunc(), replaceFunc(), roundFunc(), sqlite3FuncDefInsert(), sqlite3GlobalFunctions, sqlite3RegisterDateTimeFunctions(), SQLITE_FUNC_CASE, SQLITE_FUNC_LIKE, SQLITE_WSD, substrFunc(), sumFinalize(), sumStep(), total_changes(), totalFinalize(), trimFunc(), typeofFunc(), upperFunc(), versionFunc(), and zeroblobFunc().
Referenced by sqlite3_initialize().
void sqlite3RegisterLikeFunctions (sqlite3 * , int)
Definition at line 1248 of file func.c.
References likeFunc(), setLikeOptFlag(), sqlite3CreateFunc(), SQLITE_FUNC_CASE, SQLITE_FUNC_LIKE, and SQLITE_UTF8.
Referenced by sqlite3Pragma().
void sqlite3Reindex (Parse * , Token * , Token *)
Definition at line 3485 of file build.c.
References sqlite3::aDb, Parse::db, db, ENC, reindexDatabases(), reindexTable(), sqlite3BeginWriteOperation(), sqlite3DbFree(), sqlite3ErrorMsg(), sqlite3FindCollSeq(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3NameFromToken(), sqlite3ReadSchema(), sqlite3RefillIndex(), sqlite3TwoPartName(), SQLITE_OK, Token::z, and Db::zName.
Referenced by yy_reduce().
void sqlite3ReleaseTempRange (Parse * , int , int)
Definition at line 3094 of file expr.c.
References Parse::iRangeReg, and Parse::nRangeReg.
Referenced by multiSelectOrderBy(), pushOntoSorter(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3GenerateIndexKey(), sqlite3Insert(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), and updateAccumulator().
void sqlite3ReleaseTempReg (Parse * , int)
Definition at line 3071 of file expr.c.
References ArraySize, Parse::aTempReg, Parse::nTempReg, and sqlite3ExprWritableRegister().
Referenced by codeDistinct(), destroyRootPage(), evalConstExpr(), generateOutputSubroutine(), generateSortTail(), multiSelect(), pushOntoSorter(), selectInnerLoop(), sqlite3ChangeCookie(), sqlite3CodeSubselect(), sqlite3ExprCodeTarget(), sqlite3ExprCodeTemp(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3MinimumFileFormat(), sqlite3RefillIndex(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), and xferOptimization().
int sqlite3Reprepare (Vdbe *)
Definition at line 671 of file prepare.c.
References db, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_held, sqlite3_sql(), sqlite3LockAndPrepare(), sqlite3TransferBindings(), sqlite3VdbeDb(), sqlite3VdbeFinalize(), sqlite3VdbeResetStepResult(), sqlite3VdbeSwap(), and SQLITE_NOMEM.
void sqlite3ResetInternalSchema (sqlite3 * , int)
Definition at line 416 of file build.c.
References sqlite3::aDb, sqlite3::aDbStatic, sqlite3::flags, sqlite3::nDb, Db::pAux, Db::pBt, Db::pSchema, sqlite3BtreeEnterAll, sqlite3BtreeLeaveAll, sqlite3DbFree(), sqlite3SchemaFree(), SQLITE_InternChanges, Db::xFreeAux, and Db::zName.
Referenced by attachFunc(), createModule(), detachFunc(), invalidateTempStorage(), sqlite3_close(), sqlite3Init(), sqlite3InitOne(), sqlite3Prepare(), sqlite3RollbackAll(), sqlite3RunVacuum(), sqlite3VdbeExec(), and sqlite3VdbeHalt().
int sqlite3ResolveExprNames (NameContext * , Expr *)
Definition at line 1105 of file resolve.c.
References EP_Agg, EP_Error, ExprHasProperty, ExprSetProperty, NameContext::hasAgg, NameContext::nErr, Parse::nHeight, Walker::pNC, Walker::pParse, NameContext::pParse, resolveExprStep(), resolveSelectStep(), sqlite3ExprCheckHeight, sqlite3WalkExpr(), Walker::u, Walker::xExprCallback, and Walker::xSelectCallback.
Referenced by resolveAttachExpr(), resolveOrderByTermToExprList(), resolveOrderGroupBy(), resolveSelectStep(), sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), sqlite3EndTable(), sqlite3Insert(), and sqlite3Update().
int sqlite3ResolveOrderGroupBy (Parse * , Select * , ExprList * , const char *)
Definition at line 787 of file resolve.c.
References ExprList::a, sqlite3::aLimit, Parse::db, db, sqlite3::mallocFailed, ExprList::nExpr, Select::pEList, resolveAlias(), resolveOutOfRangeError(), sqlite3ErrorMsg(), and SQLITE_LIMIT_COLUMN.
Referenced by multiSelectOrderBy(), and resolveOrderGroupBy().
void sqlite3ResolveSelectNames (Parse * , Select * , NameContext *)
Definition at line 1156 of file resolve.c.
References Walker::pNC, Walker::pParse, resolveExprStep(), resolveSelectStep(), sqlite3WalkSelect(), Walker::u, Walker::xExprCallback, and Walker::xSelectCallback.
Referenced by resolveSelectStep(), and sqlite3SelectPrep().
Table* sqlite3ResultSetOfSelect (Parse * , Select *)
Definition at line 1270 of file select.c.
References Table::aCol, Table::db, Parse::db, db, sqlite3::flags, Table::iPKey, sqlite3::mallocFailed, Table::nCol, Parse::nErr, Table::nRef, Select::pEList, Select::pPrior, selectAddColumnTypeAndCollation(), selectColumnsFromExprList(), sqlite3DbMallocZero(), sqlite3DeleteTable(), sqlite3SelectPrep(), SQLITE_FullColNames, SQLITE_ShortColNames, and Table::zName.
Referenced by sqlite3EndTable(), and sqlite3ViewGetColumnNames().
void sqlite3RollbackAll (sqlite3 *)
Definition at line 648 of file main.c.
References sqlite3::aDb, sqlite3::autoCommit, sqlite3::flags, Db::inTrans, sqlite3::mutex, sqlite3::nDb, Db::pBt, sqlite3::pRollbackArg, sqlite3_mutex_held, sqlite3BeginBenignMalloc(), sqlite3BtreeIsInTrans(), sqlite3BtreeRollback(), sqlite3EndBenignMalloc(), sqlite3ExpirePreparedStatements(), sqlite3ResetInternalSchema(), sqlite3VtabRollback(), SQLITE_InternChanges, and sqlite3::xRollbackCallback.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeHalt().
void sqlite3RollbackTransaction (Parse *)
Definition at line 3289 of file build.c.
References sqlite3::aDb, Parse::db, db, sqlite3::mallocFailed, Parse::nErr, OP_AutoCommit, Db::pBt, sqlite3AuthCheck(), sqlite3GetVdbe(), sqlite3VdbeAddOp2(), and SQLITE_TRANSACTION.
Referenced by yy_reduce().
void sqlite3RootPageMoved (Db * , int , int)
Definition at line 1842 of file build.c.
References Schema::idxHash, Db::pSchema, sqliteHashData, sqliteHashFirst, sqliteHashNext, Schema::tblHash, Index::tnum, and Table::tnum.
Referenced by sqlite3VdbeExec().
int sqlite3RunParser (Parse * , const char * , char **)
Definition at line 384 of file tokenize.c.
References Parse::aAlias, sqlite3::activeVdbeCnt, sqlite3::aLimit, Parse::apVarExpr, Parse::apVtabLock, Parse::aTableLock, Parse::db, db, Token::dyn, IN_DECLARE_VTAB, sqlite3::isInterrupted, sqlite3::mallocFailed, Token::n, Parse::nErr, Parse::nested, Parse::nTableLock, Parse::nVar, Parse::nVarExpr, Parse::nVarExprAlloc, Parse::pNewTable, Parse::pNewTrigger, Table::pNextZombie, Parse::pVdbe, Parse::pZombieTab, Parse::rc, Parse::sLastToken, sqlite3_free(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3ErrStr(), sqlite3GetToken(), sqlite3Malloc(), sqlite3MPrintf(), sqlite3Parser(), sqlite3ParserAlloc(), sqlite3ParserFree(), sqlite3SetString(), sqlite3StatusSet(), sqlite3VdbeDelete(), SQLITE_DONE, SQLITE_ERROR, SQLITE_INTERRUPT, SQLITE_LIMIT_SQL_LENGTH, SQLITE_NOMEM, SQLITE_OK, SQLITE_STATUS_PARSER_STACK, SQLITE_TOOBIG, TK_ILLEGAL, TK_SEMI, TK_SPACE, sqlite3::u1, Token::z, Parse::zErrMsg, Parse::zSql, and Parse::zTail.
Referenced by sqlite3_declare_vtab(), sqlite3NestedParse(), and sqlite3Prepare().
int sqlite3RunVacuum (char ** , sqlite3 *)
Definition at line 81 of file vacuum.c.
References sqlite3::aDb, sqlite3::autoCommit, execExecSql(), execSql(), sqlite3::flags, sqlite3::mallocFailed, sqlite3::nChange, sqlite3::nDb, sqlite3::nextAutovac, sqlite3::nextPagesize, sqlite3::nTotalChange, Db::pBt, sqlite3_file::pMethods, Db::pSchema, sqlite3BtreeClose(), sqlite3BtreeCommit(), sqlite3BtreeCopyFile(), sqlite3BtreeGetAutoVacuum(), sqlite3BtreeGetMeta(), sqlite3BtreeGetPageSize(), sqlite3BtreeGetReserve(), sqlite3BtreeIsInTrans(), sqlite3BtreePager(), sqlite3BtreeSetAutoVacuum(), sqlite3BtreeSetPageSize(), sqlite3BtreeUpdateMeta(), sqlite3PagerFile(), sqlite3ResetInternalSchema(), sqlite3SetString(), SQLITE_ERROR, SQLITE_IgnoreChecks, SQLITE_NOMEM, SQLITE_OK, SQLITE_WriteSchema, and Db::zName.
Referenced by sqlite3VdbeExec().
int sqlite3SafetyCheckOk (sqlite3 *)
Definition at line 936 of file util.c.
References sqlite3::magic, SQLITE_MAGIC_BUSY, and SQLITE_MAGIC_OPEN.
Referenced by sqlite3LockAndPrepare(), sqlite3Prepare16(), and sqlite3VtabUnlock().
int sqlite3SafetyCheckSickOrOk (sqlite3 *)
Definition at line 944 of file util.c.
References sqlite3::magic, SQLITE_MAGIC_BUSY, SQLITE_MAGIC_OPEN, and SQLITE_MAGIC_SICK.
Referenced by sqlite3_close(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_errmsg16(), and sqlite3_extended_errcode().
void sqlite3SchemaFree (void *)
Definition at line 405 of file callback.c.
References Schema::aFKey, DB_SchemaLoaded, Schema::flags, Schema::idxHash, Schema::pSeqTab, sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3HashClear(), sqlite3HashInit(), sqliteHashData, sqliteHashFirst, sqliteHashNext, Schema::tblHash, and Schema::trigHash.
Referenced by sqlite3ResetInternalSchema(), and sqlite3SchemaGet().
Schema* sqlite3SchemaGet (sqlite3 * , Btree *)
Definition at line 434 of file callback.c.
References Schema::aFKey, Schema::enc, Schema::file_format, Schema::idxHash, sqlite3::mallocFailed, sqlite3BtreeSchema(), sqlite3HashInit(), sqlite3MallocZero(), sqlite3SchemaFree(), SQLITE_UTF8, Schema::tblHash, and Schema::trigHash.
Referenced by attachFunc(), and openDatabase().
int sqlite3SchemaToIndex (sqlite3 * db, Schema *)
Definition at line 494 of file prepare.c.
References sqlite3::aDb, sqlite3::mutex, sqlite3::nDb, Db::pSchema, and sqlite3_mutex_held.
Referenced by analyzeOneTable(), analyzeTable(), columnType(), destroyTable(), lookupName(), reindexTable(), reloadTableSchema(), sqlite3_blob_open(), sqlite3AlterBeginAddColumn(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AuthRead(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3FindInIndex(), sqlite3FinishTrigger(), sqlite3Insert(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Update(), sqlite3VtabBeginParse(), sqlite3VtabFinishParse(), sqlite3WhereBegin(), targetSrcList(), and xferOptimization().
void sqlite3ScratchFree (void *)
Definition at line 359 of file malloc.c.
References mem0, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3GlobalConfig, sqlite3MallocSize(), sqlite3StatusAdd(), SQLITE_STATUS_MEMORY_USED, SQLITE_STATUS_SCRATCH_OVERFLOW, and SQLITE_STATUS_SCRATCH_USED.
Referenced by balance_nonroot().
void* sqlite3ScratchMalloc (int)
Definition at line 309 of file malloc.c.
References mallocWithAlarm(), mem0, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3GlobalConfig, sqlite3StatusAdd(), sqlite3StatusSet(), SQLITE_STATUS_SCRATCH_OVERFLOW, SQLITE_STATUS_SCRATCH_SIZE, and SQLITE_STATUS_SCRATCH_USED.
Referenced by balance_nonroot().
int sqlite3Select (Parse * , Select * , SelectDest *)
Definition at line 3498 of file select.c.
References ExprList::a, SrcList::a, AggInfo::aCol, Select::addrOpenEphm, AggInfo::aFunc, sqlite3::aLimit, checkForMultiColumnSelectError(), computeLimitRegisters(), Parse::db, db, AggInfo::directMode, SelectDest::eDest, finalizeAggFunctions(), flattenSubquery(), generateColumnNames(), generateSortTail(), WhereInfo::iBreak, WhereInfo::iContinue, ExprList::iECursor, IgnorableOrderby, SelectDest::iParm, AggInfo::AggInfo_col::iSorterColumn, keyInfoFromExprList(), sqlite3::mallocFailed, minMaxQuery(), multiSelect(), AggInfo::nAccumulator, AggInfo::nColumn, Parse::nErr, ExprList::nExpr, AggInfo::nFunc, Parse::nHeight, Parse::nMem, AggInfo::nSortingColumn, SrcList::nSrc, Parse::nTab, Expr::op, OP_Column, OP_Compare, OP_Gosub, OP_Goto, OP_IdxInsert, OP_IfPos, OP_Integer, OP_Jump, OP_MakeRecord, OP_Next, OP_OpenEphemeral, OP_Return, OP_SCopy, OP_Sequence, OP_Sort, P4_KEYINFO, P4_KEYINFO_HANDOFF, NameContext::pAggInfo, Select::pEList, ExprList::ExprList_item::pExpr, AggInfo::AggInfo_func::pExpr, AggInfo::pGroupBy, Select::pGroupBy, Select::pHaving, Expr::pList, Select::pNext, Select::pOrderBy, NameContext::pParse, Select::pPrior, Select::pRightmost, SrcList::SrcList_item::pSelect, Select::pSrc, NameContext::pSrcList, Select::pWhere, resetAccumulator(), selectInnerLoop(), Select::selFlags, SF_Aggregate, SF_Distinct, AggInfo::sortingIdx, ExprList::ExprList_item::sortOrder, sqlite3AuthCheck(), sqlite3DbFree(), sqlite3ErrorMsg(), sqlite3ExprAnalyzeAggList(), sqlite3ExprAnalyzeAggregates(), sqlite3ExprCode(), sqlite3ExprCodeExprList(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeMove(), sqlite3ExprIfFalse(), sqlite3ExprListDelete(), sqlite3ExprListDup(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3Select(), sqlite3SelectDestInit(), sqlite3SelectExprHeight, sqlite3SelectPrep(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeToNoop(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3WhereBegin(), sqlite3WhereEnd(), SQLITE_JUMPIFNULL, SQLITE_LIMIT_COMPOUND_SELECT, SQLITE_OK, SQLITE_SELECT, SRT_Discard, SRT_EphemTab, SRT_Except, SRT_Exists, SRT_Output, SRT_Union, TK_COLUMN, updateAccumulator(), AggInfo::useSortingIdx, VdbeComment, and WHERE_ORDERBY_MIN.
Referenced by codeTriggerProgram(), multiSelect(), multiSelectOrderBy(), sqlite3CodeSubselect(), sqlite3EndTable(), sqlite3Insert(), sqlite3MaterializeView(), sqlite3Select(), updateVirtualTable(), and yy_reduce().
void sqlite3SelectDelete (sqlite3 * , Select *)
Definition at line 100 of file select.c.
References clearSelect(), and sqlite3DbFree().
Referenced by clearSelect(), codeTriggerProgram(), flattenSubquery(), multiSelect(), multiSelectOrderBy(), sqlite3CreateView(), sqlite3DeleteTable(), sqlite3DeleteTriggerStep(), sqlite3ExprClear(), sqlite3Insert(), sqlite3MaterializeView(), sqlite3SrcListAppendFromTerm(), sqlite3SrcListDelete(), sqlite3TriggerInsertStep(), sqlite3TriggerSelectStep(), sqlite3ViewGetColumnNames(), sqlitePersistTriggerStep(), updateVirtualTable(), yy_destructor(), and yy_reduce().
void sqlite3SelectDestInit (SelectDest * , int , int)
Definition at line 39 of file select.c.
References SelectDest::affinity, SelectDest::eDest, SelectDest::iMem, SelectDest::iParm, and SelectDest::nMem.
Referenced by codeTriggerProgram(), multiSelect(), multiSelectOrderBy(), sqlite3CodeSubselect(), sqlite3EndTable(), sqlite3Insert(), sqlite3MaterializeView(), sqlite3Select(), and updateVirtualTable().
Select* sqlite3SelectDup (sqlite3 * , Select *)
Definition at line 780 of file expr.c.
References Select::addrOpenEphm, Select::iLimit, Select::iOffset, Select::op, Select::pEList, Select::pGroupBy, Select::pHaving, Select::pLimit, Select::pOffset, Select::pOrderBy, Select::pPrior, Select::pRightmost, Select::pSrc, Select::pWhere, Select::selFlags, SF_UsesEphemeral, sqlite3DbMallocRaw(), sqlite3ExprDup(), sqlite3ExprListDup(), sqlite3SelectDup(), and sqlite3SrcListDup().
Referenced by codeTriggerProgram(), flattenSubquery(), selectExpander(), sqlite3CreateView(), sqlite3ExprDup(), sqlite3MaterializeView(), sqlite3SelectDup(), sqlite3SrcListDup(), sqlite3ViewGetColumnNames(), sqlitePersistTriggerStep(), and substExpr().
Select* sqlite3SelectNew (Parse * , ExprList * , SrcList * , Expr * , ExprList * , Expr * , ExprList * , int , Expr * , Expr *)
Definition at line 52 of file select.c.
References Select::addrOpenEphm, clearSelect(), Parse::db, db, sqlite3::mallocFailed, Select::op, Select::pEList, Select::pGroupBy, Select::pHaving, Select::pLimit, Select::pOffset, Select::pOrderBy, Select::pSrc, Select::pWhere, Select::selFlags, SF_Distinct, sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3Expr(), sqlite3ExprListAppend(), TK_ALL, and TK_SELECT.
Referenced by sqlite3MaterializeView(), updateVirtualTable(), and yy_reduce().
void sqlite3SelectPrep (Parse * , Select * , NameContext *)
Definition at line 3321 of file select.c.
References Parse::db, db, sqlite3::mallocFailed, Parse::nErr, Select::selFlags, SF_HasTypeInfo, sqlite3ResolveSelectNames(), sqlite3SelectAddTypeInfo(), and sqlite3SelectExpand().
Referenced by resolveSelectStep(), sqlite3ResultSetOfSelect(), and sqlite3Select().
void sqlite3SetString (char ** , sqlite3 * , const char * , ...)
Definition at line 750 of file malloc.c.
References sqlite3DbFree(), and sqlite3VMPrintf().
Referenced by corruptSchema(), sqlite3InitOne(), sqlite3RunParser(), sqlite3RunVacuum(), sqlite3VdbeExec(), and sqlite3VdbeList().
SrcList* sqlite3SrcListAppend (sqlite3 * , SrcList * , Token * , Token *)
Definition at line 3089 of file build.c.
References SrcList::a, sqlite3::mallocFailed, SrcList::nAlloc, SrcList::nSrc, sqlite3DbMallocZero(), sqlite3NameFromToken(), sqlite3SrcListDelete(), sqlite3SrcListEnlarge(), and Token::z.
Referenced by flattenSubquery(), sqlite3SrcListAppendFromTerm(), targetSrcList(), and yy_reduce().
SrcList* sqlite3SrcListAppendFromTerm (Parse * , SrcList * , Token * , Token * , Token * , Select * , Expr * , IdList *)
Definition at line 3174 of file build.c.
References SrcList::a, Parse::db, db, Token::n, SrcList::nSrc, sqlite3ExprDelete(), sqlite3IdListDelete(), sqlite3NameFromToken(), sqlite3SelectDelete(), sqlite3SrcListAppend(), and SrcList::SrcList_item::zAlias.
Referenced by sqlite3MaterializeView(), and yy_reduce().
void sqlite3SrcListAssignCursors (Parse * , SrcList *)
Definition at line 3123 of file build.c.
References SrcList::a, Parse::db, sqlite3::mallocFailed, Parse::nTab, and sqlite3SrcListAssignCursors().
Referenced by selectExpander(), sqlite3SrcListAssignCursors(), and sqlite3ViewGetColumnNames().
void sqlite3SrcListDelete (sqlite3 * , SrcList *)
Definition at line 3141 of file build.c.
References SrcList::a, sqlite3DbFree(), sqlite3DeleteTable(), sqlite3ExprDelete(), sqlite3IdListDelete(), and sqlite3SelectDelete().
Referenced by clearSelect(), sqlite3AlterBeginAddColumn(), sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTrigger(), sqlite3Insert(), sqlite3SrcListAppend(), sqlite3Update(), yy_destructor(), and yy_reduce().
SrcList* sqlite3SrcListDup (sqlite3 * , SrcList *)
Definition at line 727 of file expr.c.
References SrcList::a, Table::nRef, SrcList::nSrc, sqlite3DbMallocRaw(), sqlite3DbStrDup(), sqlite3ExprDup(), sqlite3IdListDup(), sqlite3SelectDup(), and SrcList::SrcList_item::zDatabase.
Referenced by sqlite3SelectDup().
SrcList* sqlite3SrcListEnlarge (sqlite3 * , SrcList * , int , int)
Definition at line 3013 of file build.c.
References SrcList::a, SrcList::SrcList_item::iCursor, sqlite3::mallocFailed, SrcList::nAlloc, SrcList::nSrc, and sqlite3DbRealloc().
Referenced by flattenSubquery(), and sqlite3SrcListAppend().
void sqlite3SrcListIndexedBy (Parse * , SrcList * , Token *)
Definition at line 3207 of file build.c.
References SrcList::a, Parse::db, Token::n, SrcList::nSrc, sqlite3NameFromToken(), and Token::z.
Referenced by yy_reduce().
Table* sqlite3SrcListLookup (Parse * , SrcList *)
Definition at line 24 of file delete.c.
References SrcList::a, Table::nRef, SrcList::nSrc, sqlite3DeleteTable(), sqlite3IndexedByLookup(), and sqlite3LocateTable().
Referenced by sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
void sqlite3SrcListShiftJoinType (SrcList *)
Definition at line 3236 of file build.c.
References SrcList::a, SrcList::SrcList_item::jointype, and SrcList::nSrc.
Referenced by yy_reduce().
void sqlite3StartTable (Parse * , Token * , Token * , int , int , int , int)
Definition at line 722 of file build.c.
References sqlite3::aDb, sqlite3::sqlite3InitInfo::busy, Table::db, Parse::db, db, ENC, sqlite3::flags, sqlite3::sqlite3InitInfo::iDb, IN_DECLARE_VTAB, sqlite3::init, Table::iPKey, sqlite3::mallocFailed, Parse::nErr, Parse::nested, Parse::nMem, Table::nRef, OMIT_TEMPDB, OP_Close, OP_CreateTable, OP_If, OP_Insert, OP_Integer, OP_NewRowid, OP_Null, OP_ReadCookie, OP_SetCookie, OP_VBegin, OPFLAG_APPEND, Parse::pNewTable, Db::pSchema, Table::pSchema, Schema::pSeqTab, Parse::rc, Parse::regRoot, Parse::regRowid, SCHEMA_TABLE, Parse::sNameToken, sqlite3AuthCheck(), sqlite3BeginWriteOperation(), sqlite3CheckObjectName(), sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DeleteTable(), sqlite3ErrorMsg(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3GetVdbe(), sqlite3NameFromToken(), sqlite3OpenMasterTable(), sqlite3ReadSchema(), sqlite3TwoPartName(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeChangeP5(), sqlite3VdbeJumpHere(), sqlite3VdbeUsesBtree(), SQLITE_CREATE_TABLE, SQLITE_CREATE_TEMP_TABLE, SQLITE_CREATE_TEMP_VIEW, SQLITE_CREATE_VIEW, SQLITE_INSERT, SQLITE_LegacyFileFmt, SQLITE_MAX_FILE_FORMAT, SQLITE_NOMEM, SQLITE_OK, Table::zName, and Db::zName.
Referenced by sqlite3CreateView(), sqlite3VtabBeginParse(), and yy_reduce().
void sqlite3StatusAdd (int , int)
Definition at line 57 of file status.c.
References ArraySize, wsdStat, and wsdStatInit.
Referenced by mallocWithAlarm(), pcacheFree(), pcacheMalloc(), sqlite3_free(), sqlite3Realloc(), sqlite3ScratchFree(), and sqlite3ScratchMalloc().
void sqlite3StatusSet (int , int)
Definition at line 69 of file status.c.
References ArraySize, wsdStat, and wsdStatInit.
Referenced by mallocWithAlarm(), pcacheMalloc(), sqlite3Realloc(), sqlite3RunParser(), and sqlite3ScratchMalloc().
int sqlite3StatusValue (int)
Definition at line 47 of file status.c.
References ArraySize, wsdStat, and wsdStatInit.
Referenced by mallocWithAlarm(), sqlite3MallocAlarm(), and sqlite3Realloc().
void sqlite3StrAccumAppend (StrAccum * , const char * , int)
Definition at line 719 of file printf.c.
References StrAccum::db, StrAccum::mallocFailed, StrAccum::mxAlloc, StrAccum::nAlloc, StrAccum::nChar, sqlite3DbMallocRaw(), sqlite3StrAccumReset(), StrAccum::tooBig, StrAccum::useMalloc, and StrAccum::zText.
Referenced by appendSpace(), checkAppendMsg(), groupConcatStep(), and sqlite3VXPrintf().
char* sqlite3StrAccumFinish (StrAccum *)
Definition at line 768 of file printf.c.
References StrAccum::db, StrAccum::mallocFailed, StrAccum::nChar, sqlite3DbMallocRaw(), StrAccum::useMalloc, StrAccum::zBase, and StrAccum::zText.
Referenced by groupConcatFinalize(), sqlite3_snprintf(), sqlite3_vmprintf(), sqlite3BtreeIntegrityCheck(), and sqlite3VMPrintf().
void sqlite3StrAccumInit (StrAccum * , char * , int , int)
Definition at line 796 of file printf.c.
References StrAccum::db, StrAccum::mallocFailed, StrAccum::mxAlloc, StrAccum::nAlloc, StrAccum::nChar, StrAccum::tooBig, StrAccum::useMalloc, StrAccum::zBase, and StrAccum::zText.
Referenced by sqlite3_snprintf(), sqlite3_vmprintf(), sqlite3BtreeIntegrityCheck(), and sqlite3VMPrintf().
void sqlite3StrAccumReset (StrAccum *)
Definition at line 786 of file printf.c.
References StrAccum::db, sqlite3DbFree(), StrAccum::zBase, and StrAccum::zText.
Referenced by sqlite3BtreeIntegrityCheck(), and sqlite3StrAccumAppend().
int sqlite3StrICmp (const char * , const char *)
Definition at line 191 of file util.c.
References UpperToLower.
Referenced by attachFunc(), collationMatch(), columnIndex(), detachFunc(), findTerm(), flagPragma(), getAutoVacuum(), getLockingMode(), getTempStore(), isSortingIndex(), lookupName(), parseDateOrTime(), resolveAsName(), selectColumnsFromExprList(), selectExpander(), sqlite3_blob_open(), sqlite3AddPrimaryKey(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3DropTrigger(), sqlite3FindDb(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3FixSrcList(), sqlite3IdListIndex(), sqlite3IndexedByLookup(), sqlite3Insert(), sqlite3IsRowid(), sqlite3Pragma(), sqlite3Update(), and xferCompatibleCollation().
int sqlite3Strlen (sqlite3 * , const char *)
Definition at line 57 of file util.c.
References sqlite3::aLimit, and SQLITE_LIMIT_LENGTH.
Referenced by callCollNeeded(), createCollation(), findCollSeqEntry(), sqlite3_overload_function(), sqlite3CreateFunc(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3LocateCollSeq(), and sqlite3UnlinkAndDeleteIndex().
int sqlite3StrNICmp (const char * , const char * , int)
Definition at line 198 of file util.c.
References UpperToLower.
Referenced by functionSearch(), getSafetyLevel(), isMatchOfColumn(), keywordCode(), minMaxQuery(), nocaseCollatingFunc(), sqlite3_complete(), sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CheckObjectName(), sqlite3CreateIndex(), sqlite3DropTable(), sqlite3ExprCompare(), sqlite3JoinType(), sqlite3Pragma(), strCompare(), and vtabCallConstructor().
void sqlite3TableAffinityStr (Vdbe * , Table *)
Definition at line 77 of file insert.c.
References Table::aCol, Column::affinity, db, sqlite3::mallocFailed, Table::nCol, sqlite3Malloc(), sqlite3VdbeChangeP4(), sqlite3VdbeDb(), and Table::zColAff.
Referenced by sqlite3CompleteInsertion(), sqlite3Insert(), and sqlite3Update().
void sqlite3TableLock (Parse * , int , int , u8 , const char *)
Definition at line 61 of file build.c.
References Parse::aTableLock, Parse::db, TableLock::iDb, TableLock::isWriteLock, TableLock::iTab, sqlite3::mallocFailed, Parse::nTableLock, sqlite3DbReallocOrFree(), and TableLock::zName.
Referenced by analyzeOneTable(), openStatTable(), sqlite3OpenMasterTable(), sqlite3OpenTable(), sqlite3RefillIndex(), and sqlite3WhereBegin().
void sqlite3TokenCopy (sqlite3 * , Token * , Token *)
Definition at line 673 of file expr.c.
References Token::dyn, Token::n, sqlite3DbFree(), sqlite3DbStrNDup(), and Token::z.
Referenced by exprAnalyze(), sqlite3AddDefaultValue(), sqlite3BeginTrigger(), sqlite3DequoteExpr(), sqlite3ExprListDup(), and substExpr().
int sqlite3TransferBindings (sqlite3_stmt * , sqlite3_stmt *)
Definition at line 1241 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, Vdbe::magic, sqlite3::mutex, Vdbe::nVar, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeMemMove(), SQLITE_ERROR, SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_OK, VDBE_MAGIC_HALT, and VDBE_MAGIC_RUN.
Referenced by sqlite3_transfer_bindings(), and sqlite3Reprepare().
TriggerStep* sqlite3TriggerDeleteStep (sqlite3 * , Token * , Expr *)
Definition at line 407 of file trigger.c.
References OE_Default, TriggerStep::op, TriggerStep::orconf, TriggerStep::pWhere, sqlite3DbMallocZero(), sqlite3ExprDelete(), sqlitePersistTriggerStep(), TriggerStep::target, and TK_DELETE.
Referenced by yy_reduce().
TriggerStep* sqlite3TriggerInsertStep (sqlite3 * , Token * , IdList * , ExprList * , Select * , int)
Definition at line 342 of file trigger.c.
References sqlite3::mallocFailed, TriggerStep::op, TriggerStep::orconf, TriggerStep::pExprList, TriggerStep::pIdList, TriggerStep::pSelect, sqlite3DbMallocZero(), sqlite3ExprListDelete(), sqlite3IdListDelete(), sqlite3SelectDelete(), sqlitePersistTriggerStep(), TriggerStep::target, and TK_INSERT.
Referenced by yy_reduce().
TriggerStep* sqlite3TriggerSelectStep (sqlite3 * , Select *)
Definition at line 320 of file trigger.c.
References OE_Default, TriggerStep::op, TriggerStep::orconf, TriggerStep::pSelect, sqlite3DbMallocZero(), sqlite3SelectDelete(), sqlitePersistTriggerStep(), and TK_SELECT.
Referenced by yy_reduce().
int sqlite3TriggersExist (Parse * , Table * , int , ExprList *)
Definition at line 605 of file trigger.c.
References checkColumnOverLap(), IsVirtual, Trigger::op, Trigger::pColumns, Trigger::pNext, Table::pTrigger, and Trigger::tr_tm.
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
TriggerStep* sqlite3TriggerUpdateStep (sqlite3 * , Token * , ExprList * , Expr * , int)
Definition at line 378 of file trigger.c.
References TriggerStep::op, TriggerStep::orconf, TriggerStep::pExprList, TriggerStep::pWhere, sqlite3DbMallocZero(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlitePersistTriggerStep(), TriggerStep::target, and TK_UPDATE.
Referenced by yy_reduce().
int sqlite3TwoPartName (Parse * , Token * , Token * , Token **)
Definition at line 663 of file build.c.
References sqlite3::sqlite3InitInfo::busy, Parse::db, db, sqlite3::sqlite3InitInfo::iDb, sqlite3::init, Token::n, Parse::nErr, sqlite3ErrorMsg(), and sqlite3FindDb().
Referenced by sqlite3Analyze(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3Pragma(), sqlite3Reindex(), and sqlite3StartTable().
void sqlite3UnlinkAndDeleteIndex (sqlite3 * , int , const char *)
Definition at line 383 of file build.c.
References sqlite3::aDb, sqlite3::flags, freeIndex(), Schema::idxHash, Table::pIndex, Index::pNext, Db::pSchema, Index::pTable, sqlite3HashInsert(), sqlite3Strlen(), and SQLITE_InternChanges.
Referenced by sqlite3VdbeExec().
void sqlite3UnlinkAndDeleteTable (sqlite3 * , int , const char *)
Definition at line 559 of file build.c.
References sqlite3::aDb, Schema::aFKey, sqlite3::flags, Table::pFKey, FKey::pNextFrom, FKey::pNextTo, Db::pSchema, sqlite3DeleteTable(), sqlite3HashFind(), sqlite3HashInsert(), SQLITE_InternChanges, Schema::tblHash, and FKey::zTo.
Referenced by sqlite3VdbeExec().
void sqlite3UnlinkAndDeleteTrigger (sqlite3 * , int , const char *)
Definition at line 552 of file trigger.c.
References sqlite3::aDb, sqlite3::flags, Trigger::pNext, Db::pSchema, Table::pTrigger, sqlite3DeleteTrigger(), sqlite3HashInsert(), SQLITE_InternChanges, tableOfTrigger(), and Schema::trigHash.
Referenced by sqlite3VdbeExec().
void sqlite3Update (Parse * , SrcList * , ExprList * , Expr * , int)
Definition at line 79 of file update.c.
References ExprList::a, SrcList::a, Table::aCol, sqlite3::aDb, Index::aiColumn, COLNAME_NAME, Parse::db, db, sqlite3::flags, SrcList::SrcList_item::iCursor, Table::iPKey, IsVirtual, sqlite3::mallocFailed, Table::nCol, Index::nColumn, Parse::nErr, Parse::nested, ExprList::nExpr, Parse::nMem, SrcList::nSrc, Parse::nTab, OE_Replace, WhereInfo::okOnePass, Index::onError, OP_AddImm, OP_Close, OP_Column, OP_Delete, OP_FifoRead, OP_FifoWrite, OP_Goto, OP_Insert, OP_Integer, OP_MakeRecord, OP_MustBeInt, OP_NotExists, OP_NotNull, OP_Null, OP_OpenPseudo, OP_OpenWrite, OP_ResultRow, OP_RowData, OP_Rowid, OP_SetNumColumns, OP_VRowid, P4_KEYINFO_HANDOFF, ExprList::ExprList_item::pExpr, Table::pIndex, Index::pNext, NameContext::pParse, AuthContext::pParse, Table::pSchema, Table::pSelect, NameContext::pSrcList, sqlite3AuthCheck(), sqlite3AuthContextPop(), sqlite3AuthContextPush(), sqlite3BeginWriteOperation(), sqlite3CodeRowTrigger(), sqlite3ColumnDefault(), sqlite3CompleteInsertion(), sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3ErrorMsg(), sqlite3ExprCacheAffinityChange(), sqlite3ExprCode(), sqlite3ExprCodeAndCache(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlite3GenerateConstraintChecks(), sqlite3GenerateRowIndexDelete(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3IndexKeyinfo(), sqlite3IsReadOnly(), sqlite3IsRowid(), sqlite3MaterializeView(), sqlite3OpenTable(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3ResolveExprNames(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StrICmp(), sqlite3TableAffinityStr(), sqlite3TriggersExist(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeCountChanges(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3ViewGetColumnNames(), sqlite3WhereBegin(), sqlite3WhereEnd(), SQLITE_CountRows, SQLITE_DENY, SQLITE_IGNORE, SQLITE_STATIC, SQLITE_UPDATE, TK_UPDATE, Index::tnum, TRIGGER_AFTER, TRIGGER_BEFORE, Parse::trigStack, updateVirtualTable(), WHERE_ONEPASS_DESIRED, Db::zName, Table::zName, ExprList::ExprList_item::zName, and Column::zName.
Referenced by codeTriggerProgram(), and yy_reduce().
int sqlite3Utf16ByteLen (const void * pData, int nChar)
Definition at line 452 of file utf.c.
References READ_UTF16BE, READ_UTF16LE, SQLITE_UTF16BE, and SQLITE_UTF16NATIVE.
Referenced by sqlite3Prepare16().
char* sqlite3Utf16to8 (sqlite3 * , const void * , int)
Definition at line 430 of file utf.c.
References Mem::db, Mem::flags, sqlite3::mallocFailed, MEM_Dyn, MEM_Str, MEM_Term, sqlite3DbStrDup(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemRelease(), sqlite3VdbeMemSetStr(), SQLITE_STATIC, SQLITE_UTF16NATIVE, SQLITE_UTF8, and Mem::z.
Referenced by sqlite3_create_collation16(), sqlite3_create_function16(), and sqlite3Prepare16().
int sqlite3Utf8CharLen (const char * pData, int nByte)
Definition at line 375 of file utf.c.
References SQLITE_SKIP_UTF8.
Referenced by likeFunc(), sqlite3AlterRenameTable(), sqlite3EndTable(), and sqlite3Prepare16().
int sqlite3Utf8Read (const u8 * , const u8 * , const u8 **)
Referenced by likeFunc(), and patternCompare().
void sqlite3Vacuum (Parse *)
Definition at line 70 of file vacuum.c.
References OP_Vacuum, sqlite3GetVdbe(), and sqlite3VdbeAddOp2().
Referenced by yy_reduce().
void sqlite3ValueApplyAffinity (sqlite3_value * , u8 , u8)
Definition at line 337 of file vdbe.c.
References applyAffinity().
Referenced by sqlite3ValueFromExpr().
int sqlite3ValueBytes (sqlite3_value * , u8)
Definition at line 1037 of file vdbemem.c.
References Mem::flags, Mem::i, MEM_Blob, MEM_Zero, Mem::n, sqlite3ValueText(), and Mem::u.
Referenced by sqlite3_value_bytes(), and sqlite3_value_bytes16().
void sqlite3ValueFree (sqlite3_value *)
Definition at line 1027 of file vdbemem.c.
References db, sqlite3DbFree(), and sqlite3VdbeMemRelease().
Referenced by callCollNeeded(), freeP4(), sqlite3_close(), sqlite3_complete16(), sqlite3_open16(), sqlite3AlterFinishAddColumn(), and sqlite3ValueFromExpr().
int sqlite3ValueFromExpr (sqlite3 * , Expr * , u8 , u8 , sqlite3_value **)
Definition at line 950 of file vdbemem.c.
References Mem::i, sqlite3::mallocFailed, Token::n, Expr::op, Expr::pLeft, Mem::r, sqlite3DbFree(), sqlite3DbStrNDup(), sqlite3Dequote(), sqlite3HexToBlob(), sqlite3ValueApplyAffinity(), sqlite3ValueFree(), sqlite3ValueFromExpr(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3VdbeMemSetStr(), SQLITE_AFF_NONE, SQLITE_AFF_NUMERIC, SQLITE_DYNAMIC, SQLITE_NOMEM, SQLITE_OK, SQLITE_UTF8, TK_BLOB, TK_FLOAT, TK_INTEGER, TK_STRING, TK_UMINUS, Expr::token, Mem::u, and Token::z.
Referenced by sqlite3AlterFinishAddColumn(), sqlite3ColumnDefault(), and sqlite3ValueFromExpr().
sqlite3_value* sqlite3ValueNew (sqlite3 *)
Definition at line 930 of file vdbemem.c.
References Mem::db, Mem::flags, MEM_Null, sqlite3DbMallocZero(), SQLITE_NULL, and Mem::type.
Referenced by callCollNeeded(), sqlite3_complete16(), sqlite3_open16(), sqlite3Error(), and sqlite3ValueFromExpr().
void sqlite3ValueSetStr (sqlite3_value * , int , const void * , u8 , void(*)(void *))
Definition at line 1014 of file vdbemem.c.
References sqlite3VdbeMemSetStr().
Referenced by callCollNeeded(), sqlite3_complete16(), sqlite3_errmsg16(), sqlite3_open16(), sqlite3Error(), sqlite3ValueFromExpr(), and sqlite3VdbeReset().
const void* sqlite3ValueText (sqlite3_value * , u8)
Definition at line 892 of file vdbemem.c.
References Mem::db, Mem::enc, expandBlob, Mem::flags, sqlite3::mallocFailed, MEM_Blob, MEM_Ephem, MEM_Null, MEM_Static, sqlite3::mutex, sqlite3_mutex_held, sqlite3VdbeChangeEncoding(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemStringify(), SQLITE_OK, SQLITE_PTR_TO_INT, SQLITE_UTF16_ALIGNED, and Mem::z.
Referenced by callCollNeeded(), sqlite3_complete16(), sqlite3_open16(), sqlite3_value_text(), sqlite3_value_text16(), sqlite3_value_text16be(), sqlite3_value_text16le(), sqlite3MemCompare(), and sqlite3ValueBytes().
int sqlite3VarintLen (u64 v)
Definition at line 797 of file util.c.
Referenced by sqlite3VdbeExec().
void sqlite3VdbeSetChanges (sqlite3 * , int)
Definition at line 2453 of file vdbeaux.c.
References sqlite3::mutex, sqlite3::nChange, sqlite3::nTotalChange, and sqlite3_mutex_held.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeHalt().
int sqlite3ViewGetColumnNames (Parse * , Table *)
Definition at line 1723 of file build.c.
References Table::aCol, Parse::db, db, DB_UnresetViews, Schema::flags, IsVirtual, Table::nCol, Parse::nTab, Table::pSchema, Table::pSelect, Select::pSrc, sqlite3DeleteTable(), sqlite3ErrorMsg(), sqlite3ResultSetOfSelect(), sqlite3SelectDelete(), sqlite3SelectDup(), sqlite3SrcListAssignCursors(), sqlite3VtabCallConnect(), SQLITE_ERROR, sqlite3::xAuth, and Table::zName.
Referenced by selectExpander(), sqlite3AlterRenameTable(), sqlite3CreateView(), sqlite3DeleteFrom(), sqlite3DropTable(), sqlite3Insert(), sqlite3Pragma(), and sqlite3Update().
char* sqlite3VMPrintf (sqlite3 * , const char * , va_list)
Definition at line 811 of file printf.c.
References sqlite3::aLimit, StrAccum::db, sqlite3::mallocFailed, StrAccum::mallocFailed, sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), SQLITE_LIMIT_LENGTH, SQLITE_MAX_LENGTH, and SQLITE_PRINT_BUF_SIZE.
Referenced by sqlite3Error(), sqlite3ErrorMsg(), sqlite3MAppendf(), sqlite3MPrintf(), sqlite3NestedParse(), and sqlite3SetString().
void sqlite3VtabArgExtend (Parse * , Token *)
Definition at line 327 of file vtab.c.
References Token::n, Parse::sArg, and Token::z.
Referenced by yy_reduce().
void sqlite3VtabArgInit (Parse *)
Definition at line 317 of file vtab.c.
References addArgumentToVtab(), Token::n, Parse::sArg, and Token::z.
Referenced by yy_reduce().
int sqlite3VtabBegin (sqlite3 * , sqlite3_vtab *)
Definition at line 704 of file vtab.c.
References addToVTrans(), sqlite3::aVTrans, sqlite3::nVTrans, sqlite3_vtab::pModule, SQLITE_LOCKED, SQLITE_OK, and sqlite3_module::xBegin.
Referenced by sqlite3VdbeExec().
void sqlite3VtabBeginParse (Parse * , Token * , Token * , Token *)
Definition at line 165 of file vtab.c.
References sqlite3::aDb, addModuleArgument(), Table::azModuleArg, Parse::db, sqlite3::flags, Token::n, Parse::nErr, Table::nModuleArg, Table::pIndex, Parse::pNewTable, Table::pSchema, Parse::sNameToken, sqlite3AuthCheck(), sqlite3DbStrDup(), sqlite3ErrorMsg(), sqlite3NameFromToken(), sqlite3SchemaToIndex(), sqlite3StartTable(), SQLITE_CREATE_VTABLE, SQLITE_SharedCache, Table::tabFlags, TF_Virtual, Token::z, Table::zName, and Db::zName.
Referenced by yy_reduce().
int sqlite3VtabCallConnect (Parse * , Table *)
Definition at line 441 of file vtab.c.
References Table::azModuleArg, Parse::db, Table::pMod, Module::pModule, Table::pVtab, sqlite3DbFree(), sqlite3ErrorMsg(), SQLITE_ERROR, SQLITE_OK, Table::tabFlags, TF_Virtual, vtabCallConstructor(), and sqlite3_module::xConnect.
Referenced by sqlite3ViewGetColumnNames().
int sqlite3VtabCallCreate (sqlite3 * , int , const char * , char **)
Definition at line 499 of file vtab.c.
References sqlite3::aDb, addToVTrans(), Table::azModuleArg, Table::pMod, Module::pModule, Table::pVtab, sqlite3FindTable(), sqlite3MPrintf(), SQLITE_ERROR, SQLITE_OK, Table::tabFlags, TF_Virtual, vtabCallConstructor(), sqlite3_module::xCreate, and Db::zName.
Referenced by sqlite3VdbeExec().
int sqlite3VtabCallDestroy (sqlite3 * , int , const char *)
Definition at line 588 of file vtab.c.
References sqlite3::aDb, sqlite3::aVTrans, sqlite3::nVTrans, Table::pMod, Module::pModule, Table::pVtab, sqlite3FindTable(), sqlite3SafetyOff, sqlite3SafetyOn, SQLITE_OK, sqlite3_module::xDestroy, and Db::zName.
Referenced by sqlite3VdbeExec().
void sqlite3VtabClear (Table *)
Definition at line 117 of file vtab.c.
References Table::azModuleArg, Table::db, Table::nModuleArg, Table::pMod, Module::pModule, Table::pVtab, sqlite3DbFree(), and sqlite3VtabUnlock().
Referenced by sqlite3DeleteTable().
int sqlite3VtabCommit (sqlite3 * db)
Definition at line 691 of file vtab.c.
References callFinaliser(), offsetof, and SQLITE_OK.
Referenced by vdbeCommit().
void sqlite3VtabFinishParse (Parse * , Token *)
Definition at line 227 of file vtab.c.
References sqlite3::aDb, addArgumentToVtab(), sqlite3::aModule, Table::azModuleArg, sqlite3::sqlite3InitInfo::busy, Schema::db, Parse::db, sqlite3::init, sqlite3::mallocFailed, Token::n, Table::nModuleArg, OP_Expire, OP_ParseSchema, OP_VCreate, P4_DYNAMIC, Table::pMod, Parse::pNewTable, Table::pSchema, Parse::regRowid, Parse::sArg, SCHEMA_TABLE, Parse::sNameToken, sqlite3ChangeCookie(), sqlite3DbFree(), sqlite3GetVdbe(), sqlite3HashFind(), sqlite3HashInsert(), sqlite3MPrintf(), sqlite3NestedParse(), sqlite3SchemaToIndex(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), Schema::tblHash, Token::z, Table::zName, and Db::zName.
Referenced by yy_reduce().
void sqlite3VtabLock (sqlite3_vtab *)
Definition at line 89 of file vtab.c.
References sqlite3_vtab::nRef.
Referenced by addToVTrans(), and sqlite3VdbeExec().
void sqlite3VtabMakeWritable (Parse * , Table *)
Definition at line 824 of file vtab.c.
References Parse::apVtabLock, Parse::db, IsVirtual, sqlite3::mallocFailed, Parse::nVtabLock, and sqlite3_realloc().
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and updateVirtualTable().
FuncDef* sqlite3VtabOverloadFunction (sqlite3 * , FuncDef * , int nArg, Expr *)
Definition at line 754 of file vtab.c.
References FuncDef::flags, Expr::op, sqlite3_vtab::pModule, Expr::pTab, FuncDef::pUserData, Table::pVtab, sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3DbStrDup(), sqlite3Error(), sqlite3UpperToLower, SQLITE_FUNC_EPHEM, Table::tabFlags, TF_Virtual, TK_COLUMN, sqlite3_module::xFindFunction, FuncDef::xFunc, sqlite3_vtab::zErrMsg, and FuncDef::zName.
Referenced by sqlite3ExprCodeTarget().
int sqlite3VtabRollback (sqlite3 * db)
Definition at line 682 of file vtab.c.
References callFinaliser(), offsetof, and SQLITE_OK.
Referenced by sqlite3_close(), and sqlite3RollbackAll().
int sqlite3VtabSync (sqlite3 * db, char **)
Definition at line 650 of file vtab.c.
References sqlite3::aVTrans, sqlite3::nVTrans, sqlite3_vtab::pModule, sqlite3DbFree(), sqlite3SafetyOff, sqlite3SafetyOn, SQLITE_OK, sqlite3_module::xSync, and sqlite3_vtab::zErrMsg.
Referenced by vdbeCommit().
void sqlite3VtabUnlock (sqlite3 * , sqlite3_vtab *)
Definition at line 97 of file vtab.c.
References sqlite3::magic, sqlite3_vtab::nRef, sqlite3_vtab::pModule, sqlite3SafetyCheckOk(), sqlite3SafetyOff, sqlite3SafetyOn, SQLITE_MAGIC_BUSY, and sqlite3_module::xDisconnect.
Referenced by callFinaliser(), sqlite3VdbeExec(), and sqlite3VtabClear().
void sqlite3VXPrintf (StrAccum * , int , const char * , va_list)
Definition at line 223 of file printf.c.
References SrcList::a, aDigits, appendSpace(), aPrefix, et_info::base, et_info::charset, et_getdigit(), etBUFSIZE, etCHARX, etDYNSTRING, etEXP, etFLOAT, etGENERIC, etNINFO, etORDINAL, etPERCENT, etPOINTER, etRADIX, etSIZE, etSQLESCAPE, etSQLESCAPE2, etSQLESCAPE3, etSRCLIST, etSTRING, etTOKEN, FLAG_INTERN, FLAG_SIGNED, FLAG_STRING, et_info::flags, LONGDOUBLE_TYPE, Token::n, StrAccum::nChar, et_info::prefix, sqlite3_free(), sqlite3IsNaN(), sqlite3Malloc(), sqlite3StrAccumAppend(), et_info::type, and Token::z.
Referenced by checkAppendMsg(), sqlite3_snprintf(), sqlite3_vmprintf(), and sqlite3VMPrintf().
int sqlite3WalkExpr (Walker * , Expr *)
Definition at line 41 of file walker.c.
References Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, sqlite3WalkExpr(), sqlite3WalkExprList(), sqlite3WalkSelect(), WRC_Abort, WRC_Continue, and Walker::xExprCallback.
Referenced by exprIsConst(), sqlite3ExprAnalyzeAggregates(), sqlite3ExprCodeConstants(), sqlite3ResolveExprNames(), sqlite3WalkExpr(), sqlite3WalkExprList(), and sqlite3WalkSelectExpr().
int sqlite3WalkExprList (Walker * , ExprList *)
Definition at line 60 of file walker.c.
References ExprList::a, ExprList::nExpr, sqlite3WalkExpr(), WRC_Abort, and WRC_Continue.
Referenced by resolveExprStep(), sqlite3WalkExpr(), and sqlite3WalkSelectExpr().
int sqlite3WalkSelect (Walker * , Select *)
Definition at line 122 of file walker.c.
References Select::pPrior, sqlite3WalkSelectExpr(), sqlite3WalkSelectFrom(), WRC_Abort, WRC_Continue, and Walker::xSelectCallback.
Referenced by analyzeAggregatesInSelect(), resolveExprStep(), selectExpander(), sqlite3ResolveSelectNames(), sqlite3SelectAddTypeInfo(), sqlite3SelectExpand(), sqlite3WalkExpr(), and sqlite3WalkSelectFrom().
int sqlite3WalkSelectExpr (Walker * , Select *)
Definition at line 77 of file walker.c.
References Select::pEList, Select::pGroupBy, Select::pHaving, Select::pLimit, Select::pOffset, Select::pOrderBy, Select::pWhere, sqlite3WalkExpr(), sqlite3WalkExprList(), WRC_Abort, and WRC_Continue.
Referenced by sqlite3WalkSelect().
int sqlite3WalkSelectFrom (Walker * , Select *)
Definition at line 95 of file walker.c.
References SrcList::a, SrcList::nSrc, Select::pSrc, sqlite3WalkSelect(), WRC_Abort, and WRC_Continue.
Referenced by sqlite3WalkSelect().
WhereInfo* sqlite3WhereBegin (Parse * , SrcList * , Expr * , ExprList ** , u8)
Definition at line 2037 of file where.c.
References ExprList::a, WhereClause::a, WhereInfo::a, SrcList::a, sqlite3_index_info::aConstraint, sqlite3_index_info::aConstraintUsage, Index::aiColumn, WhereLevel::aInLoop, Index::aSortOrder, bestIndex(), bestVirtualIndex(), BMS, WhereLevel::brk, codeAllEqualityTerms(), codeApplyAffinity(), codeEqualityTerm(), WhereLevel::cont, createMask(), Parse::db, db, Parse::disableColCache, disableTerm(), WhereTerm::eOperator, EP_FromJoin, Parse::explain, exprAnalyzeAll(), ExprHasProperty, findTerm(), WhereTerm::flags, WhereLevel::flags, getMask(), WhereInfo::iBreak, Expr::iColumn, WhereInfo::iContinue, SrcList::SrcList_item::iCursor, sqlite3_index_info::idxNum, sqlite3_index_info::idxStr, WhereLevel::iFrom, WhereLevel::iIdxCur, WhereLevel::iLeftJoin, WhereLevel::iMem, initMaskSet, IsVirtual, WhereLevel::iTabCur, WhereInfo::iTop, JT_CROSS, JT_LEFT, WhereTerm::leftCursor, sqlite3::mallocFailed, Table::nCol, Index::nColumn, sqlite3_index_info::nConstraint, sqlite3_index_info::needToFreeIdxStr, WhereLevel::nEq, ExprList::nExpr, WhereLevel::nIn, WhereInfo::nLevel, Parse::nMem, SrcList::nSrc, Parse::nTab, WhereClause::nTerm, WhereLevel::nxt, WhereInfo::okOnePass, Expr::op, WhereLevel::op, OP_Column, OP_Explain, OP_ForceInt, OP_Ge, OP_Gt, OP_IdxGE, OP_IdxLT, OP_IdxRowid, OP_Integer, OP_IsNull, OP_Last, OP_Le, OP_Lt, OP_MoveGe, OP_MoveGt, OP_MoveLe, OP_MoveLt, OP_MustBeInt, OP_Next, OP_Noop, OP_NotExists, OP_Null, OP_OpenRead, OP_OpenWrite, OP_Prev, OP_Rewind, OP_Rowid, OP_SetNumColumns, OP_VFilter, OP_VNext, OP_VOpen, sqlite3_index_info::orderByConsumed, WhereLevel::p1, WhereLevel::p2, P4_DYNAMIC, P4_INT32, P4_KEYINFO_HANDOFF, P4_MPRINTF, P4_STATIC, P4_VTAB, WhereLevel::p5, WhereLevel::pBestIdx, ExprList::ExprList_item::pExpr, WhereTerm::pExpr, WhereLevel::pIdx, WhereLevel::pIdxInfo, SrcList::SrcList_item::pIndex, WhereInfo::pParse, WhereTerm::prereqAll, Expr::pRight, Index::pSchema, Table::pSchema, Table::pSelect, WhereInfo::pTabList, Parse::pVdbe, Table::pVtab, sqlite3CodeVerifySchema(), sqlite3DbMallocZero(), sqlite3ErrorMsg(), sqlite3ExprClearColumnCache(), sqlite3ExprCode(), sqlite3ExprCodeConstants(), sqlite3ExprIfFalse(), sqlite3ExprIsConstantNotJoin(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3IndexKeyinfo(), sqlite3MAppendf(), sqlite3MPrintf(), sqlite3OpenTable(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3SchemaToIndex(), sqlite3TableLock(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeChangeP2(), sqlite3VdbeChangeP5(), sqlite3VdbeCurrentAddr(), sqlite3VdbeMakeLabel(), SQLITE_AFF_NUMERIC, SQLITE_BIG_DBL, SQLITE_INT_TO_PTR, SQLITE_JUMPIFNULL, SQLITE_SO_ASC, SQLITE_STMTSTATUS_FULLSCAN_STEP, SWAP, Table::tabFlags, TERM_CODED, TERM_VIRTUAL, testcase, TF_Ephemeral, TK_AND, TK_GT, TK_LE, TK_LT, Index::tnum, Table::tnum, WhereLevel::top, VdbeComment, WHERE_BTM_LIMIT, WHERE_COLUMN_EQ, WHERE_COLUMN_RANGE, WHERE_IDX_ONLY, WHERE_ONEPASS_DESIRED, WHERE_ORDERBY, WHERE_ORDERBY_MIN, WHERE_REVERSE, WHERE_ROWID_EQ, WHERE_ROWID_RANGE, WHERE_TOP_LIMIT, WHERE_UNIQUE, WHERE_VIRTUALTABLE, whereClauseClear(), whereClauseInit(), whereInfoFree(), whereSplit(), WHERETRACE, WO_EQ, WO_GE, WO_GT, WO_IN, WO_LE, WO_LT, SrcList::SrcList_item::zAlias, Table::zName, and Index::zName.
Referenced by sqlite3DeleteFrom(), sqlite3Select(), and sqlite3Update().
void sqlite3WhereEnd (WhereInfo *)
Definition at line 2836 of file where.c.
References SrcList::a, WhereInfo::a, Index::aiColumn, WhereLevel::aInLoop, WhereLevel::brk, WhereLevel::cont, Parse::db, db, WhereLevel::flags, WhereInfo::iBreak, SrcList::SrcList_item::iCursor, WhereLevel::iFrom, WhereLevel::iIdxCur, WhereLevel::iLeftJoin, WhereLevel::iTabCur, WhereInfo::iTop, Index::nColumn, WhereLevel::nIn, SrcList::nSrc, WhereLevel::nxt, WhereInfo::okOnePass, WhereLevel::op, OP_Close, OP_Column, OP_Goto, OP_IdxRowid, OP_IfPos, OP_Next, OP_Noop, OP_NullRow, OP_Rowid, VdbeOp::opcode, VdbeOp::p1, WhereLevel::p1, VdbeOp::p2, WhereLevel::p2, WhereLevel::p5, WhereLevel::pIdx, WhereInfo::pParse, Table::pSelect, SrcList::SrcList_item::pTab, WhereInfo::pTabList, Parse::pVdbe, sqlite3DbFree(), sqlite3ExprClearColumnCache(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeChangeP5(), sqlite3VdbeCurrentAddr(), sqlite3VdbeGetOp(), sqlite3VdbeJumpHere(), sqlite3VdbeResolveLabel(), Table::tabFlags, TF_Ephemeral, WhereLevel::top, WHERE_IDX_ONLY, and whereInfoFree().
Referenced by sqlite3DeleteFrom(), sqlite3Select(), and sqlite3Update().
void sqliteViewTriggers (Parse * , Table * , Expr * , int , ExprList *)
Variable Documentation
SQLITE_WSD struct Sqlite3Config sqlite3Config
Definition at line 69 of file global.c.
SQLITE_WSD FuncDefHash sqlite3GlobalFunctions
Definition at line 85 of file global.c.
Referenced by sqlite3_initialize(), sqlite3FindFunction(), sqlite3RegisterDateTimeFunctions(), and sqlite3RegisterGlobalFunctions().
const int sqlite3one
Definition at line 46 of file utf.c.
const unsigned char sqlite3UpperToLower[]
Definition at line 27 of file global.c.
Referenced by exprAnalyze(), sqlite3AffinityType(), sqlite3FindFunction(), sqlite3FuncDefInsert(), sqlite3VtabOverloadFunction(), and strHash().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1