ContextLogger2 Logger Daemon Internals: sqliteicu.h File Reference
sqliteicu.h File Reference
Functions
int sqlite3IcuInit (sqlite3 *db)
Function Documentation
int sqlite3IcuInit (sqlite3 * db)
Definition at line 449 of file icu.c.
References icuCaseFunc16(), icuLikeFunc(), icuLoadCollation(), icuRegexpFunc(), sqlite3_create_function(), SQLITE_ANY, SQLITE_OK, SQLITE_UTF16, and SQLITE_UTF8.
Referenced by openDatabase(), and sqlite3_extension_init().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1