ContextLogger2 Logger Daemon Internals: sqlite3.h File Reference
sqlite3.h File Reference
Classes
struct sqlite3_file
struct sqlite3_io_methods
struct sqlite3_vfs
struct sqlite3_mem_methods
struct sqlite3_module
struct sqlite3_index_info
struct sqlite3_index_info::sqlite3_index_constraint
struct sqlite3_index_info::sqlite3_index_orderby
struct sqlite3_index_info::sqlite3_index_constraint_usage
struct sqlite3_vtab
struct sqlite3_vtab_cursor
struct sqlite3_mutex_methods
Defines
#define __SQLITE3H__ 1
#define IMPORT_C
#define EXPORT_C
#define SQLITE_EXTERN extern
#define SQLITE_DEPRECATED
#define SQLITE_EXPERIMENTAL
#define SQLITE_VERSION "3.6.5"
#define SQLITE_VERSION_NUMBER 3006005
#define SQLITE_OK 0
#define SQLITE_ERROR 1
#define SQLITE_INTERNAL 2
#define SQLITE_PERM 3
#define SQLITE_ABORT 4
#define SQLITE_BUSY 5
#define SQLITE_LOCKED 6
#define SQLITE_NOMEM 7
#define SQLITE_READONLY 8
#define SQLITE_INTERRUPT 9
#define SQLITE_IOERR 10
#define SQLITE_CORRUPT 11
#define SQLITE_NOTFOUND 12
#define SQLITE_FULL 13
#define SQLITE_CANTOPEN 14
#define SQLITE_PROTOCOL 15
#define SQLITE_EMPTY 16
#define SQLITE_SCHEMA 17
#define SQLITE_TOOBIG 18
#define SQLITE_CONSTRAINT 19
#define SQLITE_MISMATCH 20
#define SQLITE_MISUSE 21
#define SQLITE_NOLFS 22
#define SQLITE_AUTH 23
#define SQLITE_FORMAT 24
#define SQLITE_RANGE 25
#define SQLITE_NOTADB 26
#define SQLITE_ROW 100
#define SQLITE_DONE 101
#define SQLITE_IOERR_READ (SQLITE_IOERR | (1<<8))
#define SQLITE_IOERR_SHORT_READ (SQLITE_IOERR | (2<<8))
#define SQLITE_IOERR_WRITE (SQLITE_IOERR | (3<<8))
#define SQLITE_IOERR_FSYNC (SQLITE_IOERR | (4<<8))
#define SQLITE_IOERR_DIR_FSYNC (SQLITE_IOERR | (5<<8))
#define SQLITE_IOERR_TRUNCATE (SQLITE_IOERR | (6<<8))
#define SQLITE_IOERR_FSTAT (SQLITE_IOERR | (7<<8))
#define SQLITE_IOERR_UNLOCK (SQLITE_IOERR | (8<<8))
#define SQLITE_IOERR_RDLOCK (SQLITE_IOERR | (9<<8))
#define SQLITE_IOERR_DELETE (SQLITE_IOERR | (10<<8))
#define SQLITE_IOERR_BLOCKED (SQLITE_IOERR | (11<<8))
#define SQLITE_IOERR_NOMEM (SQLITE_IOERR | (12<<8))
#define SQLITE_IOERR_ACCESS (SQLITE_IOERR | (13<<8))
#define SQLITE_IOERR_CHECKRESERVEDLOCK (SQLITE_IOERR | (14<<8))
#define SQLITE_IOERR_LOCK (SQLITE_IOERR | (15<<8))
#define SQLITE_OPEN_READONLY 0x00000001
#define SQLITE_OPEN_READWRITE 0x00000002
#define SQLITE_OPEN_CREATE 0x00000004
#define SQLITE_OPEN_DELETEONCLOSE 0x00000008
#define SQLITE_OPEN_EXCLUSIVE 0x00000010
#define SQLITE_OPEN_MAIN_DB 0x00000100
#define SQLITE_OPEN_TEMP_DB 0x00000200
#define SQLITE_OPEN_TRANSIENT_DB 0x00000400
#define SQLITE_OPEN_MAIN_JOURNAL 0x00000800
#define SQLITE_OPEN_TEMP_JOURNAL 0x00001000
#define SQLITE_OPEN_SUBJOURNAL 0x00002000
#define SQLITE_OPEN_MASTER_JOURNAL 0x00004000
#define SQLITE_OPEN_NOMUTEX 0x00008000
#define SQLITE_OPEN_FULLMUTEX 0x00010000
#define SQLITE_IOCAP_ATOMIC 0x00000001
#define SQLITE_IOCAP_ATOMIC512 0x00000002
#define SQLITE_IOCAP_ATOMIC1K 0x00000004
#define SQLITE_IOCAP_ATOMIC2K 0x00000008
#define SQLITE_IOCAP_ATOMIC4K 0x00000010
#define SQLITE_IOCAP_ATOMIC8K 0x00000020
#define SQLITE_IOCAP_ATOMIC16K 0x00000040
#define SQLITE_IOCAP_ATOMIC32K 0x00000080
#define SQLITE_IOCAP_ATOMIC64K 0x00000100
#define SQLITE_IOCAP_SAFE_APPEND 0x00000200
#define SQLITE_IOCAP_SEQUENTIAL 0x00000400
#define SQLITE_LOCK_NONE 0
#define SQLITE_LOCK_SHARED 1
#define SQLITE_LOCK_RESERVED 2
#define SQLITE_LOCK_PENDING 3
#define SQLITE_LOCK_EXCLUSIVE 4
#define SQLITE_SYNC_NORMAL 0x00002
#define SQLITE_SYNC_FULL 0x00003
#define SQLITE_SYNC_DATAONLY 0x00010
#define SQLITE_FCNTL_LOCKSTATE 1
#define SQLITE_ACCESS_EXISTS 0
#define SQLITE_ACCESS_READWRITE 1
#define SQLITE_ACCESS_READ 2
#define SQLITE_CONFIG_SINGLETHREAD 1
#define SQLITE_CONFIG_MULTITHREAD 2
#define SQLITE_CONFIG_SERIALIZED 3
#define SQLITE_CONFIG_MALLOC 4
#define SQLITE_CONFIG_GETMALLOC 5
#define SQLITE_CONFIG_SCRATCH 6
#define SQLITE_CONFIG_PAGECACHE 7
#define SQLITE_CONFIG_HEAP 8
#define SQLITE_CONFIG_MEMSTATUS 9
#define SQLITE_CONFIG_MUTEX 10
#define SQLITE_CONFIG_GETMUTEX 11
#define SQLITE_CONFIG_LOOKASIDE 13
#define SQLITE_DBCONFIG_LOOKASIDE 1001
#define SQLITE_DENY 1
#define SQLITE_IGNORE 2
#define SQLITE_CREATE_INDEX 1
#define SQLITE_CREATE_TABLE 2
#define SQLITE_CREATE_TEMP_INDEX 3
#define SQLITE_CREATE_TEMP_TABLE 4
#define SQLITE_CREATE_TEMP_TRIGGER 5
#define SQLITE_CREATE_TEMP_VIEW 6
#define SQLITE_CREATE_TRIGGER 7
#define SQLITE_CREATE_VIEW 8
#define SQLITE_DELETE 9
#define SQLITE_DROP_INDEX 10
#define SQLITE_DROP_TABLE 11
#define SQLITE_DROP_TEMP_INDEX 12
#define SQLITE_DROP_TEMP_TABLE 13
#define SQLITE_DROP_TEMP_TRIGGER 14
#define SQLITE_DROP_TEMP_VIEW 15
#define SQLITE_DROP_TRIGGER 16
#define SQLITE_DROP_VIEW 17
#define SQLITE_INSERT 18
#define SQLITE_PRAGMA 19
#define SQLITE_READ 20
#define SQLITE_SELECT 21
#define SQLITE_TRANSACTION 22
#define SQLITE_UPDATE 23
#define SQLITE_ATTACH 24
#define SQLITE_DETACH 25
#define SQLITE_ALTER_TABLE 26
#define SQLITE_REINDEX 27
#define SQLITE_ANALYZE 28
#define SQLITE_CREATE_VTABLE 29
#define SQLITE_DROP_VTABLE 30
#define SQLITE_FUNCTION 31
#define SQLITE_COPY 0
#define SQLITE_LIMIT_LENGTH 0
#define SQLITE_LIMIT_SQL_LENGTH 1
#define SQLITE_LIMIT_COLUMN 2
#define SQLITE_LIMIT_EXPR_DEPTH 3
#define SQLITE_LIMIT_COMPOUND_SELECT 4
#define SQLITE_LIMIT_VDBE_OP 5
#define SQLITE_LIMIT_FUNCTION_ARG 6
#define SQLITE_LIMIT_ATTACHED 7
#define SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
#define SQLITE_LIMIT_VARIABLE_NUMBER 9
#define SQLITE_INTEGER 1
#define SQLITE_FLOAT 2
#define SQLITE_BLOB 4
#define SQLITE_NULL 5
#define SQLITE_TEXT 3
#define SQLITE3_TEXT 3
#define SQLITE_UTF8 1
#define SQLITE_UTF16LE 2
#define SQLITE_UTF16BE 3
#define SQLITE_UTF16 4
#define SQLITE_ANY 5
#define SQLITE_UTF16_ALIGNED 8
#define SQLITE_STATIC ((sqlite3_destructor_type)0)
#define SQLITE_TRANSIENT ((sqlite3_destructor_type)-1)
#define SQLITE_INDEX_CONSTRAINT_EQ 2
#define SQLITE_INDEX_CONSTRAINT_GT 4
#define SQLITE_INDEX_CONSTRAINT_LE 8
#define SQLITE_INDEX_CONSTRAINT_LT 16
#define SQLITE_INDEX_CONSTRAINT_GE 32
#define SQLITE_INDEX_CONSTRAINT_MATCH 64
#define SQLITE_MUTEX_FAST 0
#define SQLITE_MUTEX_RECURSIVE 1
#define SQLITE_MUTEX_STATIC_MASTER 2
#define SQLITE_MUTEX_STATIC_MEM 3
#define SQLITE_MUTEX_STATIC_MEM2 4
#define SQLITE_MUTEX_STATIC_PRNG 5
#define SQLITE_MUTEX_STATIC_LRU 6
#define SQLITE_MUTEX_STATIC_LRU2 7
#define SQLITE_TESTCTRL_PRNG_SAVE 5
#define SQLITE_TESTCTRL_PRNG_RESTORE 6
#define SQLITE_TESTCTRL_PRNG_RESET 7
#define SQLITE_TESTCTRL_BITVEC_TEST 8
#define SQLITE_TESTCTRL_FAULT_INSTALL 9
#define SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS 10
#define SQLITE_STATUS_MEMORY_USED 0
#define SQLITE_STATUS_PAGECACHE_USED 1
#define SQLITE_STATUS_PAGECACHE_OVERFLOW 2
#define SQLITE_STATUS_SCRATCH_USED 3
#define SQLITE_STATUS_SCRATCH_OVERFLOW 4
#define SQLITE_STATUS_MALLOC_SIZE 5
#define SQLITE_STATUS_PARSER_STACK 6
#define SQLITE_STATUS_PAGECACHE_SIZE 7
#define SQLITE_STATUS_SCRATCH_SIZE 8
#define SQLITE_DBSTATUS_LOOKASIDE_USED 0
#define SQLITE_STMTSTATUS_FULLSCAN_STEP 1
#define SQLITE_STMTSTATUS_SORT 2
Typedefs
typedef struct sqlite3 sqlite3
typedef long long int sqlite_int64
typedef unsigned long long int sqlite_uint64
typedef sqlite_int64 sqlite3_int64
typedef sqlite_uint64 sqlite3_uint64
typedef int(* sqlite3_callback)(void *, int, char **, char **)
typedef struct sqlite3_file sqlite3_file
typedef struct sqlite3_io_methods sqlite3_io_methods
typedef struct sqlite3_mutex sqlite3_mutex
typedef struct sqlite3_vfs sqlite3_vfs
typedef struct sqlite3_mem_methods sqlite3_mem_methods
typedef struct sqlite3_stmt sqlite3_stmt
typedef struct Mem sqlite3_value
typedef struct sqlite3_context sqlite3_context
typedef void(* sqlite3_destructor_type)(void *)
typedef struct sqlite3_vtab sqlite3_vtab
typedef struct sqlite3_index_info sqlite3_index_info
typedef struct sqlite3_vtab_cursor sqlite3_vtab_cursor
typedef struct sqlite3_module sqlite3_module
typedef struct sqlite3_blob sqlite3_blob
typedef struct
sqlite3_mutex_methods sqlite3_mutex_methods
Functions
const char * sqlite3_libversion (void)
int sqlite3_libversion_number (void)
int sqlite3_threadsafe (void)
IMPORT_C int sqlite3_close (sqlite3 *)
IMPORT_C int sqlite3_exec (sqlite3 *, const char *sql, int(*callback)(void *, int, char **, char **), void *, char **errmsg)
int sqlite3_initialize (void)
int sqlite3_shutdown (void)
int sqlite3_os_init (void)
int sqlite3_os_end (void)
SQLITE_EXPERIMENTAL int sqlite3_config (int,...)
SQLITE_EXPERIMENTAL int sqlite3_db_config (sqlite3 *, int op,...)
IMPORT_C int sqlite3_extended_result_codes (sqlite3 *, int onoff)
sqlite3_int64 sqlite3_last_insert_rowid (sqlite3 *)
int sqlite3_changes (sqlite3 *)
int sqlite3_total_changes (sqlite3 *)
void sqlite3_interrupt (sqlite3 *)
int sqlite3_complete (const char *sql)
int sqlite3_complete16 (const void *sql)
int sqlite3_busy_handler (sqlite3 *, int(*)(void *, int), void *)
int sqlite3_busy_timeout (sqlite3 *, int ms)
int sqlite3_get_table (sqlite3 *db, const char *zSql, char ***pazResult, int *pnRow, int *pnColumn, char **pzErrmsg)
void sqlite3_free_table (char **result)
char * sqlite3_mprintf (const char *,...)
char * sqlite3_vmprintf (const char *, va_list)
char * sqlite3_snprintf (int, char *, const char *,...)
IMPORT_C void * sqlite3_malloc (int)
void * sqlite3_realloc (void *, int)
IMPORT_C void sqlite3_free (void *)
sqlite3_int64 sqlite3_memory_used (void)
sqlite3_int64 sqlite3_memory_highwater (int resetFlag)
void sqlite3_randomness (int N, void *P)
int sqlite3_set_authorizer (sqlite3 *, int(*xAuth)(void *, int, const char *, const char *, const char *, const char *), void *pUserData)
SQLITE_EXPERIMENTAL void * sqlite3_trace (sqlite3 *, void(*xTrace)(void *, const char *), void *)
SQLITE_EXPERIMENTAL void * sqlite3_profile (sqlite3 *, void(*xProfile)(void *, const char *, sqlite3_uint64), void *)
void sqlite3_progress_handler (sqlite3 *, int, int(*)(void *), void *)
IMPORT_C int sqlite3_open (const char *filename, sqlite3 **ppDb)
int sqlite3_open16 (const void *filename, sqlite3 **ppDb)
int sqlite3_open_v2 (const char *filename, sqlite3 **ppDb, int flags, const char *zVfs)
int sqlite3_errcode (sqlite3 *db)
int sqlite3_extended_errcode (sqlite3 *db)
IMPORT_C const char * sqlite3_errmsg (sqlite3 *)
const void * sqlite3_errmsg16 (sqlite3 *)
int sqlite3_limit (sqlite3 *, int id, int newVal)
int sqlite3_prepare (sqlite3 *db, const char *zSql, int nByte, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare_v2 (sqlite3 *db, const char *zSql, int nByte, sqlite3_stmt **ppStmt, const char **pzTail)
int sqlite3_prepare16 (sqlite3 *db, const void *zSql, int nByte, sqlite3_stmt **ppStmt, const void **pzTail)
int sqlite3_prepare16_v2 (sqlite3 *db, const void *zSql, int nByte, sqlite3_stmt **ppStmt, const void **pzTail)
const char * sqlite3_sql (sqlite3_stmt *pStmt)
int sqlite3_bind_blob (sqlite3_stmt *, int, const void *, int n, void(*)(void *))
int sqlite3_bind_double (sqlite3_stmt *, int, double)
int sqlite3_bind_int (sqlite3_stmt *, int, int)
int sqlite3_bind_int64 (sqlite3_stmt *, int, sqlite3_int64)
int sqlite3_bind_null (sqlite3_stmt *, int)
int sqlite3_bind_text (sqlite3_stmt *, int, const char *, int n, void(*)(void *))
int sqlite3_bind_text16 (sqlite3_stmt *, int, const void *, int, void(*)(void *))
int sqlite3_bind_value (sqlite3_stmt *, int, const sqlite3_value *)
int sqlite3_bind_zeroblob (sqlite3_stmt *, int, int n)
int sqlite3_bind_parameter_count (sqlite3_stmt *)
const char * sqlite3_bind_parameter_name (sqlite3_stmt *, int)
int sqlite3_bind_parameter_index (sqlite3_stmt *, const char *zName)
int sqlite3_clear_bindings (sqlite3_stmt *)
int sqlite3_column_count (sqlite3_stmt *pStmt)
const char * sqlite3_column_name (sqlite3_stmt *, int N)
const void * sqlite3_column_name16 (sqlite3_stmt *, int N)
const char * sqlite3_column_database_name (sqlite3_stmt *, int)
const void * sqlite3_column_database_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_table_name (sqlite3_stmt *, int)
const void * sqlite3_column_table_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_origin_name (sqlite3_stmt *, int)
const void * sqlite3_column_origin_name16 (sqlite3_stmt *, int)
const char * sqlite3_column_decltype (sqlite3_stmt *, int)
const void * sqlite3_column_decltype16 (sqlite3_stmt *, int)
int sqlite3_step (sqlite3_stmt *)
int sqlite3_data_count (sqlite3_stmt *pStmt)
const void * sqlite3_column_blob (sqlite3_stmt *, int iCol)
int sqlite3_column_bytes (sqlite3_stmt *, int iCol)
int sqlite3_column_bytes16 (sqlite3_stmt *, int iCol)
double sqlite3_column_double (sqlite3_stmt *, int iCol)
int sqlite3_column_int (sqlite3_stmt *, int iCol)
sqlite3_int64 sqlite3_column_int64 (sqlite3_stmt *, int iCol)
const unsigned char * sqlite3_column_text (sqlite3_stmt *, int iCol)
const void * sqlite3_column_text16 (sqlite3_stmt *, int iCol)
int sqlite3_column_type (sqlite3_stmt *, int iCol)
sqlite3_value * sqlite3_column_value (sqlite3_stmt *, int iCol)
int sqlite3_finalize (sqlite3_stmt *pStmt)
int sqlite3_reset (sqlite3_stmt *pStmt)
int sqlite3_create_function (sqlite3 *db, const char *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
int sqlite3_create_function16 (sqlite3 *db, const void *zFunctionName, int nArg, int eTextRep, void *pApp, void(*xFunc)(sqlite3_context *, int, sqlite3_value **), void(*xStep)(sqlite3_context *, int, sqlite3_value **), void(*xFinal)(sqlite3_context *))
SQLITE_DEPRECATED int sqlite3_aggregate_count (sqlite3_context *)
SQLITE_DEPRECATED int sqlite3_expired (sqlite3_stmt *)
SQLITE_DEPRECATED int sqlite3_transfer_bindings (sqlite3_stmt *, sqlite3_stmt *)
SQLITE_DEPRECATED int sqlite3_global_recover (void)
SQLITE_DEPRECATED void sqlite3_thread_cleanup (void)
SQLITE_DEPRECATED int sqlite3_memory_alarm (void(*)(void *, sqlite3_int64, int), void *, sqlite3_int64)
const void * sqlite3_value_blob (sqlite3_value *)
int sqlite3_value_bytes (sqlite3_value *)
int sqlite3_value_bytes16 (sqlite3_value *)
double sqlite3_value_double (sqlite3_value *)
int sqlite3_value_int (sqlite3_value *)
sqlite3_int64 sqlite3_value_int64 (sqlite3_value *)
const unsigned char * sqlite3_value_text (sqlite3_value *)
const void * sqlite3_value_text16 (sqlite3_value *)
const void * sqlite3_value_text16le (sqlite3_value *)
const void * sqlite3_value_text16be (sqlite3_value *)
int sqlite3_value_type (sqlite3_value *)
int sqlite3_value_numeric_type (sqlite3_value *)
void * sqlite3_aggregate_context (sqlite3_context *, int nBytes)
void * sqlite3_user_data (sqlite3_context *)
sqlite3 * sqlite3_context_db_handle (sqlite3_context *)
void * sqlite3_get_auxdata (sqlite3_context *, int N)
void sqlite3_set_auxdata (sqlite3_context *, int N, void *, void(*)(void *))
void sqlite3_result_blob (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_double (sqlite3_context *, double)
void sqlite3_result_error (sqlite3_context *, const char *, int)
void sqlite3_result_error16 (sqlite3_context *, const void *, int)
void sqlite3_result_error_toobig (sqlite3_context *)
void sqlite3_result_error_nomem (sqlite3_context *)
void sqlite3_result_error_code (sqlite3_context *, int)
void sqlite3_result_int (sqlite3_context *, int)
void sqlite3_result_int64 (sqlite3_context *, sqlite3_int64)
void sqlite3_result_null (sqlite3_context *)
void sqlite3_result_text (sqlite3_context *, const char *, int, void(*)(void *))
void sqlite3_result_text16 (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_text16le (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_text16be (sqlite3_context *, const void *, int, void(*)(void *))
void sqlite3_result_value (sqlite3_context *, sqlite3_value *)
void sqlite3_result_zeroblob (sqlite3_context *, int n)
int sqlite3_create_collation (sqlite3 *, const char *zName, int eTextRep, void *, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_create_collation_v2 (sqlite3 *, const char *zName, int eTextRep, void *, int(*xCompare)(void *, int, const void *, int, const void *), void(*xDestroy)(void *))
int sqlite3_create_collation16 (sqlite3 *, const void *zName, int eTextRep, void *, int(*xCompare)(void *, int, const void *, int, const void *))
int sqlite3_collation_needed (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const char *))
int sqlite3_collation_needed16 (sqlite3 *, void *, void(*)(void *, sqlite3 *, int eTextRep, const void *))
int sqlite3_key (sqlite3 *db, const void *pKey, int nKey)
int sqlite3_rekey (sqlite3 *db, const void *pKey, int nKey)
int sqlite3_sleep (int)
int sqlite3_get_autocommit (sqlite3 *)
sqlite3 * sqlite3_db_handle (sqlite3_stmt *)
sqlite3_stmt * sqlite3_next_stmt (sqlite3 *pDb, sqlite3_stmt *pStmt)
void * sqlite3_commit_hook (sqlite3 *, int(*)(void *), void *)
void * sqlite3_rollback_hook (sqlite3 *, void(*)(void *), void *)
void * sqlite3_update_hook (sqlite3 *, void(*)(void *, int, char const *, char const *, sqlite3_int64), void *)
int sqlite3_enable_shared_cache (int)
int sqlite3_release_memory (int)
void sqlite3_soft_heap_limit (int)
int sqlite3_table_column_metadata (sqlite3 *db, const char *zDbName, const char *zTableName, const char *zColumnName, char const **pzDataType, char const **pzCollSeq, int *pNotNull, int *pPrimaryKey, int *pAutoinc)
int sqlite3_load_extension (sqlite3 *db, const char *zFile, const char *zProc, char **pzErrMsg)
int sqlite3_enable_load_extension (sqlite3 *db, int onoff)
int sqlite3_auto_extension (void *xEntryPoint)
void sqlite3_reset_auto_extension (void)
SQLITE_EXPERIMENTAL int sqlite3_create_module (sqlite3 *db, const char *zName, const sqlite3_module *, void *)
SQLITE_EXPERIMENTAL int sqlite3_create_module_v2 (sqlite3 *db, const char *zName, const sqlite3_module *, void *, void(*xDestroy)(void *))
SQLITE_EXPERIMENTAL int sqlite3_declare_vtab (sqlite3 *, const char *zCreateTable)
SQLITE_EXPERIMENTAL int sqlite3_overload_function (sqlite3 *, const char *zFuncName, int nArg)
int sqlite3_blob_open (sqlite3 *, const char *zDb, const char *zTable, const char *zColumn, sqlite3_int64 iRow, int flags, sqlite3_blob **ppBlob)
int sqlite3_blob_close (sqlite3_blob *)
int sqlite3_blob_bytes (sqlite3_blob *)
int sqlite3_blob_read (sqlite3_blob *, void *Z, int N, int iOffset)
int sqlite3_blob_write (sqlite3_blob *, const void *z, int n, int iOffset)
sqlite3_vfs * sqlite3_vfs_find (const char *zVfsName)
int sqlite3_vfs_register (sqlite3_vfs *, int makeDflt)
int sqlite3_vfs_unregister (sqlite3_vfs *)
sqlite3_mutex * sqlite3_mutex_alloc (int)
void sqlite3_mutex_free (sqlite3_mutex *)
void sqlite3_mutex_enter (sqlite3_mutex *)
int sqlite3_mutex_try (sqlite3_mutex *)
void sqlite3_mutex_leave (sqlite3_mutex *)
int sqlite3_mutex_held (sqlite3_mutex *)
int sqlite3_mutex_notheld (sqlite3_mutex *)
sqlite3_mutex * sqlite3_db_mutex (sqlite3 *)
int sqlite3_file_control (sqlite3 *, const char *zDbName, int op, void *)
int sqlite3_test_control (int op,...)
SQLITE_EXPERIMENTAL int sqlite3_status (int op, int *pCurrent, int *pHighwater, int resetFlag)
SQLITE_EXPERIMENTAL int sqlite3_db_status (sqlite3 *, int op, int *pCur, int *pHiwtr, int resetFlg)
SQLITE_EXPERIMENTAL int sqlite3_stmt_status (sqlite3_stmt *, int op, int resetFlg)
Variables
SQLITE_EXTERN const char sqlite3_version []
SQLITE_EXTERN char * sqlite3_temp_directory
Define Documentation
#define __SQLITE3H__ 1
Definition at line 48 of file sqlite3.h.
#define EXPORT_C
Definition at line 54 of file sqlite3.h.
#define IMPORT_C
Definition at line 53 of file sqlite3.h.
#define SQLITE3_TEXT 3
Definition at line 3708 of file sqlite3.h.
#define SQLITE_ABORT 4
Definition at line 444 of file sqlite3.h.
Referenced by blobReadWrite(), invalidateCursorsOnModifiedBtrees(), sqlite3_exec(), sqlite3_get_table(), sqlite3BtreeData(), sqlite3BtreePutData(), and sqlite3ErrStr().
#define SQLITE_ACCESS_EXISTS 0
Definition at line 907 of file sqlite3.h.
Referenced by hasHotJournal(), pager_delmaster(), pager_playback(), pagerSharedLock(), unixAccess(), and vdbeCommit().
#define SQLITE_ACCESS_READ 2
Definition at line 909 of file sqlite3.h.
Referenced by unixAccess().
#define SQLITE_ACCESS_READWRITE 1
Definition at line 908 of file sqlite3.h.
Referenced by sqlite3Pragma(), and unixAccess().
#define SQLITE_ALTER_TABLE 26
Definition at line 2393 of file sqlite3.h.
Referenced by auth_callback(), sqlite3AlterFinishAddColumn(), and sqlite3AlterRenameTable().
#define SQLITE_ANALYZE 28
Definition at line 2395 of file sqlite3.h.
Referenced by analyzeOneTable(), and auth_callback().
#define SQLITE_ANY 5
Definition at line 4155 of file sqlite3.h.
Referenced by sqlite3CreateFunc(), sqlite3Fts2InitHashTable(), sqlite3Fts3InitHashTable(), and sqlite3IcuInit().
#define SQLITE_ATTACH 24
Definition at line 2391 of file sqlite3.h.
Referenced by auth_callback(), codeAttach(), and sqlite3Attach().
#define SQLITE_AUTH 23
Definition at line 463 of file sqlite3.h.
Referenced by sqlite3AuthCheck(), sqlite3AuthRead(), and sqlite3ErrStr().
#define SQLITE_BLOB 4
Definition at line 3701 of file sqlite3.h.
Referenced by _storeTypeInfo(), attachFunc(), DbObjCmd(), FUNC(), lengthFunc(), optimizeFunc(), push_column(), quoteFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemSetZeroBlob(), substrFunc(), tclSqlFunc(), and typeofFunc().
#define SQLITE_BUSY 5
Definition at line 445 of file sqlite3.h.
Referenced by btreeCopyFile(), createCollation(), pager_wait_on_lock(), pagerSharedLock(), pcacheRecycleOrAlloc(), setupLookaside(), sql_step_statement(), sqlite3_close(), sqlite3BtreeBeginTrans(), sqlite3CreateFunc(), sqlite3ErrStr(), sqlite3PagerCommitPhaseOne(), sqlite3VdbeExec(), sqlite3VdbeHalt(), sqlite3VdbeList(), sqliteErrorFromPosixError(), and unixLock().
#define SQLITE_CANTOPEN 14
Definition at line 454 of file sqlite3.h.
Referenced by openDirectory(), pagerSharedLock(), sqlite3ErrStr(), sqlite3PagerOpen(), unixFullPathname(), and unixOpen().
#define SQLITE_CONFIG_GETMALLOC 5
Definition at line 1340 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_GETMUTEX 11
Definition at line 1346 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_HEAP 8
Definition at line 1343 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_LOOKASIDE 13
Definition at line 1348 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_MALLOC 4
Definition at line 1339 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_MEMSTATUS 9
Definition at line 1344 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_MULTITHREAD 2
Definition at line 1337 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_MUTEX 10
Definition at line 1345 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_PAGECACHE 7
Definition at line 1342 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_SCRATCH 6
Definition at line 1341 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_SERIALIZED 3
Definition at line 1338 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONFIG_SINGLETHREAD 1
Definition at line 1336 of file sqlite3.h.
Referenced by sqlite3_config().
#define SQLITE_CONSTRAINT 19
Definition at line 459 of file sqlite3.h.
Referenced by resolveP2Values(), sqlite3ErrStr(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3RefillIndex(), sqlite3VdbeHalt(), vdbeCommit(), and xferOptimization().
#define SQLITE_COPY 0
Definition at line 2399 of file sqlite3.h.
Referenced by auth_callback().
#define SQLITE_CORRUPT 11
Definition at line 451 of file sqlite3.h.
Referenced by corruptSchema(), dump_callback(), freePage(), pager_error(), run_schema_dump_query(), and sqlite3ErrStr().
#define SQLITE_CREATE_INDEX 1
Definition at line 2368 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3CreateIndex().
#define SQLITE_CREATE_TABLE 2
Definition at line 2369 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3StartTable().
#define SQLITE_CREATE_TEMP_INDEX 3
Definition at line 2370 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3CreateIndex().
#define SQLITE_CREATE_TEMP_TABLE 4
Definition at line 2371 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3StartTable().
#define SQLITE_CREATE_TEMP_TRIGGER 5
Definition at line 2372 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3BeginTrigger().
#define SQLITE_CREATE_TEMP_VIEW 6
Definition at line 2373 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3StartTable().
#define SQLITE_CREATE_TRIGGER 7
Definition at line 2374 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3BeginTrigger().
#define SQLITE_CREATE_VIEW 8
Definition at line 2375 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3StartTable().
#define SQLITE_CREATE_VTABLE 29
Definition at line 2396 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3VtabBeginParse().
#define SQLITE_DBCONFIG_LOOKASIDE 1001
Definition at line 1378 of file sqlite3.h.
Referenced by sqlite3_db_config().
#define SQLITE_DBSTATUS_LOOKASIDE_USED 0
Definition at line 6516 of file sqlite3.h.
Referenced by sqlite3_db_status().
#define SQLITE_DELETE 9
Definition at line 2376 of file sqlite3.h.
Referenced by auth_callback(), DbUpdateHandler(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), and sqlite3VdbeExec().
#define SQLITE_DENY 1
Definition at line 2323 of file sqlite3.h.
Referenced by auth_callback(), resolveExprStep(), sqlite3AuthCheck(), sqlite3AuthRead(), sqlite3DeleteFrom(), sqlite3Update(), and xauth_callback_wrapper().
#define SQLITE_DEPRECATED
Definition at line 79 of file sqlite3.h.
#define SQLITE_DETACH 25
Definition at line 2392 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3Detach().
#define SQLITE_DONE 101
Definition at line 468 of file sqlite3.h.
Referenced by autoVacuumCommit(), block_insert(), buildTerms(), content_exists(), content_select(), db_get(), db_set(), fulltextNext(), fulltextUpdate(), incrVacuumStep(), index_insert_term(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), optimizeFunc(), pager_playback(), pager_playback_one_page(), pager_stmt_playback(), porterNext(), readJournalHdr(), segdir_count(), segdir_delete(), segdir_max_index(), segdir_span(), segdirNextIndex(), simpleNext(), sql_single_step(), sql_single_step_statement(), sql_step_statement(), sqlite3_exec(), sqlite3BtreeIncrVacuum(), sqlite3ErrStr(), sqlite3FinishCoding(), sqlite3Prepare(), sqlite3RunParser(), sqlite3VdbeExec(), sqlite3VdbeFifoPop(), sqlite3VdbeList(), term_select(), term_select_all(), and termSelect().
#define SQLITE_DROP_INDEX 10
Definition at line 2377 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropIndex().
#define SQLITE_DROP_TABLE 11
Definition at line 2378 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTable().
#define SQLITE_DROP_TEMP_INDEX 12
Definition at line 2379 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropIndex().
#define SQLITE_DROP_TEMP_TABLE 13
Definition at line 2380 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTable().
#define SQLITE_DROP_TEMP_TRIGGER 14
Definition at line 2381 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTriggerPtr().
#define SQLITE_DROP_TEMP_VIEW 15
Definition at line 2382 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTable().
#define SQLITE_DROP_TRIGGER 16
Definition at line 2383 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTriggerPtr().
#define SQLITE_DROP_VIEW 17
Definition at line 2384 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTable().
#define SQLITE_DROP_VTABLE 30
Definition at line 2397 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3DropTable().
#define SQLITE_EMPTY 16
Definition at line 456 of file sqlite3.h.
Referenced by btreeCursor(), sqlite3ErrStr(), sqlite3InitOne(), and sqlite3VdbeExec().
#define SQLITE_ERROR 1
Definition at line 441 of file sqlite3.h.
Referenced by attachFunc(), blobReadWrite(), block_insert(), btreeCopyFile(), btreeCreateTable(), btreeDropTable(), buildTerms(), changeTempStorage(), constructVtab(), content_exists(), deleteTerms(), fulltextNext(), fulltextQuery(), fulltextUpdate(), getTempname(), index_insert_term(), invalidateTempStorage(), loadAndGetChildrenContaining(), openDatabase(), parseQuery(), resolveAttachExpr(), segdir_count(), segdir_max_index(), segdir_span(), simpleCreate(), sql_step_statement(), sqlite3_blob_open(), sqlite3_config(), sqlite3_db_config(), sqlite3_db_status(), sqlite3_declare_vtab(), sqlite3_file_control(), sqlite3_get_table_cb(), sqlite3_result_error(), sqlite3_result_error16(), sqlite3AnalysisLoad(), sqlite3AutoLoadExtensions(), sqlite3BtreeBeginStmt(), sqlite3BtreeClearTable(), sqlite3BtreeDelete(), sqlite3BtreeInsert(), sqlite3BtreePutData(), sqlite3BtreeUpdateMeta(), sqlite3CheckCollSeq(), sqlite3CheckObjectName(), sqlite3CodeRowTrigger(), sqlite3CreateFunc(), sqlite3ErrorMsg(), sqlite3ErrStr(), sqlite3FinishCoding(), sqlite3IndexedByLookup(), sqlite3InitOne(), sqlite3LoadExtension(), sqlite3PagerCommitPhaseTwo(), sqlite3RunParser(), sqlite3RunVacuum(), sqlite3Step(), sqlite3TransferBindings(), sqlite3VdbeChangeEncoding(), sqlite3VdbeExec(), sqlite3VdbeList(), sqlite3VdbeMemFinalize(), sqlite3ViewGetColumnNames(), sqlite3VtabCallConnect(), sqlite3VtabCallCreate(), sqliteAuthBadReturnCode(), synthCollSeq(), unixFileControl(), unixFullPathname(), and vtabCallConstructor().
#define SQLITE_EXPERIMENTAL
Definition at line 80 of file sqlite3.h.
#define SQLITE_EXTERN extern
Definition at line 63 of file sqlite3.h.
#define SQLITE_FCNTL_LOCKSTATE 1
Definition at line 737 of file sqlite3.h.
Referenced by sqlite3Pragma(), and unixFileControl().
#define SQLITE_FLOAT 2
Definition at line 3700 of file sqlite3.h.
Referenced by _storeTypeInfo(), attachFunc(), DbObjCmd(), FUNC(), isDate(), lengthFunc(), push_column(), quoteFunc(), sqlite3VdbeMemSetDouble(), tclSqlFunc(), and typeofFunc().
#define SQLITE_FORMAT 24
Definition at line 464 of file sqlite3.h.
Referenced by sqlite3ErrStr().
#define SQLITE_FULL 13
Definition at line 453 of file sqlite3.h.
Referenced by pager_error(), pager_open_journal(), pagerSharedLock(), sqlite3ErrStr(), sqlite3PagerAcquire(), sqlite3PagerLookup(), sqlite3PagerRollback(), sqlite3VdbeExec(), sqlite3VdbeHalt(), unixSync(), and unixWrite().
#define SQLITE_FUNCTION 31
Definition at line 2398 of file sqlite3.h.
Referenced by auth_callback(), and resolveExprStep().
#define SQLITE_IGNORE 2
Definition at line 2324 of file sqlite3.h.
Referenced by auth_callback(), sqlite3AuthCheck(), sqlite3AuthRead(), sqlite3DeleteFrom(), and sqlite3Update().
#define SQLITE_INDEX_CONSTRAINT_EQ 2
Definition at line 5596 of file sqlite3.h.
Referenced by bestVirtualIndex(), and fulltextBestIndex().
#define SQLITE_INDEX_CONSTRAINT_GE 32
Definition at line 5600 of file sqlite3.h.
Referenced by bestVirtualIndex().
#define SQLITE_INDEX_CONSTRAINT_GT 4
Definition at line 5597 of file sqlite3.h.
Referenced by bestVirtualIndex().
#define SQLITE_INDEX_CONSTRAINT_LE 8
Definition at line 5598 of file sqlite3.h.
Referenced by bestVirtualIndex().
#define SQLITE_INDEX_CONSTRAINT_LT 16
Definition at line 5599 of file sqlite3.h.
Referenced by bestVirtualIndex().
#define SQLITE_INDEX_CONSTRAINT_MATCH 64
Definition at line 5601 of file sqlite3.h.
Referenced by bestVirtualIndex(), and fulltextBestIndex().
#define SQLITE_INSERT 18
Definition at line 2385 of file sqlite3.h.
Referenced by auth_callback(), DbUpdateHandler(), sqlite3BeginTrigger(), sqlite3CreateIndex(), sqlite3Insert(), sqlite3StartTable(), and sqlite3VdbeExec().
#define SQLITE_INTEGER 1
Definition at line 3699 of file sqlite3.h.
Referenced by _storeTypeInfo(), absFunc(), attachFunc(), DbObjCmd(), fulltextUpdate(), FUNC(), isDate(), lengthFunc(), push_column(), quoteFunc(), sqlite3VdbeList(), sqlite3VdbeMemSetInt64(), sumStep(), tclSqlFunc(), and typeofFunc().
#define SQLITE_INTERNAL 2
Definition at line 442 of file sqlite3.h.
Referenced by sqlite3Insert().
#define SQLITE_INTERRUPT 9
Definition at line 449 of file sqlite3.h.
Referenced by sqlite3ErrStr(), sqlite3InitCallback(), sqlite3RunParser(), sqlite3VdbeExec(), sqlite3VdbeHalt(), and sqlite3VdbeList().
#define SQLITE_IOCAP_ATOMIC 0x00000001
Definition at line 566 of file sqlite3.h.
Referenced by sqlite3PagerOpen().
#define SQLITE_IOCAP_ATOMIC16K 0x00000040
Definition at line 572 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC1K 0x00000004
Definition at line 568 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC2K 0x00000008
Definition at line 569 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC32K 0x00000080
Definition at line 573 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC4K 0x00000010
Definition at line 570 of file sqlite3.h.
#define SQLITE_IOCAP_ATOMIC512 0x00000002
Definition at line 567 of file sqlite3.h.
Referenced by sqlite3PagerOpen().
#define SQLITE_IOCAP_ATOMIC64K 0x00000100
Definition at line 574 of file sqlite3.h.
Referenced by sqlite3PagerOpen().
#define SQLITE_IOCAP_ATOMIC8K 0x00000020
Definition at line 571 of file sqlite3.h.
#define SQLITE_IOCAP_SAFE_APPEND 0x00000200
Definition at line 575 of file sqlite3.h.
Referenced by pagerStress(), syncJournal(), and writeJournalHdr().
#define SQLITE_IOCAP_SEQUENTIAL 0x00000400
Definition at line 576 of file sqlite3.h.
Referenced by syncJournal(), and vdbeCommit().
#define SQLITE_IOERR 10
Definition at line 450 of file sqlite3.h.
Referenced by findLockInfo(), getTempname(), pager_error(), sqlite3ErrStr(), and sqlite3VdbeHalt().
#define SQLITE_IOERR_ACCESS (SQLITE_IOERR | (13<<8))
Definition at line 519 of file sqlite3.h.
Referenced by unixAccess().
#define SQLITE_IOERR_BLOCKED (SQLITE_IOERR | (11<<8))
Definition at line 517 of file sqlite3.h.
Referenced by sqlite3PagerCommitPhaseOne(), sqlite3VdbeHalt(), and sqliteErrorFromPosixError().
#define SQLITE_IOERR_CHECKRESERVEDLOCK (SQLITE_IOERR | (14<<8))
Definition at line 520 of file sqlite3.h.
Referenced by sqliteErrorFromPosixError(), and unixCheckReservedLock().
#define SQLITE_IOERR_DELETE (SQLITE_IOERR | (10<<8))
Definition at line 516 of file sqlite3.h.
Referenced by unixDelete().
#define SQLITE_IOERR_DIR_FSYNC (SQLITE_IOERR | (5<<8))
Definition at line 511 of file sqlite3.h.
Referenced by unixDelete().
#define SQLITE_IOERR_FSTAT (SQLITE_IOERR | (7<<8))
Definition at line 513 of file sqlite3.h.
Referenced by unixFileSize().
#define SQLITE_IOERR_FSYNC (SQLITE_IOERR | (4<<8))
Definition at line 510 of file sqlite3.h.
Referenced by unixSync().
#define SQLITE_IOERR_LOCK (SQLITE_IOERR | (15<<8))
Definition at line 521 of file sqlite3.h.
Referenced by sqliteErrorFromPosixError(), and unixLock().
#define SQLITE_IOERR_NOMEM (SQLITE_IOERR | (12<<8))
Definition at line 518 of file sqlite3.h.
Referenced by attachFunc(), memjrnlWrite(), openDatabase(), pager_open_journal(), schemaIsValid(), sqlite3ApiExit(), sqlite3InitOne(), and sqlite3VdbeExec().
#define SQLITE_IOERR_RDLOCK (SQLITE_IOERR | (9<<8))
Definition at line 515 of file sqlite3.h.
Referenced by sqliteErrorFromPosixError(), and unixUnlock().
#define SQLITE_IOERR_READ (SQLITE_IOERR | (1<<8))
Definition at line 507 of file sqlite3.h.
Referenced by unixRead().
#define SQLITE_IOERR_SHORT_READ (SQLITE_IOERR | (2<<8))
Definition at line 508 of file sqlite3.h.
Referenced by readDbPage(), sqlite3PagerAcquire(), sqlite3PagerReadFileheader(), and unixRead().
#define SQLITE_IOERR_TRUNCATE (SQLITE_IOERR | (6<<8))
Definition at line 512 of file sqlite3.h.
Referenced by unixTruncate().
#define SQLITE_IOERR_UNLOCK (SQLITE_IOERR | (8<<8))
Definition at line 514 of file sqlite3.h.
Referenced by sqliteErrorFromPosixError(), unixLock(), and unixUnlock().
#define SQLITE_IOERR_WRITE (SQLITE_IOERR | (3<<8))
Definition at line 509 of file sqlite3.h.
Referenced by unixWrite().
#define SQLITE_LIMIT_ATTACHED 7
Definition at line 2869 of file sqlite3.h.
Referenced by attachFunc().
#define SQLITE_LIMIT_COLUMN 2
Definition at line 2864 of file sqlite3.h.
Referenced by resolveCompoundOrderBy(), selectExpander(), sqlite3AddColumn(), sqlite3ExprListCheckLength(), and sqlite3ResolveOrderGroupBy().
#define SQLITE_LIMIT_COMPOUND_SELECT 4
Definition at line 2866 of file sqlite3.h.
Referenced by sqlite3Select().
#define SQLITE_LIMIT_EXPR_DEPTH 3
Definition at line 2865 of file sqlite3.h.
#define SQLITE_LIMIT_FUNCTION_ARG 6
Definition at line 2868 of file sqlite3.h.
#define SQLITE_LIMIT_LENGTH 0
Definition at line 2862 of file sqlite3.h.
Referenced by contextMalloc(), groupConcatStep(), replaceFunc(), sqlite3Strlen(), sqlite3VdbeExec(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemTooBig(), sqlite3VMPrintf(), strftimeFunc(), and substrFunc().
#define SQLITE_LIMIT_LIKE_PATTERN_LENGTH 8
Definition at line 2870 of file sqlite3.h.
Referenced by likeFunc().
#define SQLITE_LIMIT_SQL_LENGTH 1
Definition at line 2863 of file sqlite3.h.
Referenced by sqlite3Prepare(), and sqlite3RunParser().
#define SQLITE_LIMIT_VARIABLE_NUMBER 9
Definition at line 2871 of file sqlite3.h.
Referenced by sqlite3ExprAssignVarNumber().
#define SQLITE_LIMIT_VDBE_OP 5
Definition at line 2867 of file sqlite3.h.
#define SQLITE_LOCK_EXCLUSIVE 4
Definition at line 589 of file sqlite3.h.
#define SQLITE_LOCK_NONE 0
Definition at line 585 of file sqlite3.h.
Referenced by unixFileControl().
#define SQLITE_LOCK_PENDING 3
Definition at line 588 of file sqlite3.h.
#define SQLITE_LOCK_RESERVED 2
Definition at line 587 of file sqlite3.h.
#define SQLITE_LOCK_SHARED 1
Definition at line 586 of file sqlite3.h.
#define SQLITE_LOCKED 6
Definition at line 446 of file sqlite3.h.
Referenced by btreeCursor(), btreeDropTable(), checkReadLocks(), queryTableLock(), sqlite3BtreeDelete(), sqlite3BtreeInsert(), sqlite3BtreePutData(), sqlite3ErrStr(), sqlite3Prepare(), sqlite3VdbeExec(), and sqlite3VtabBegin().
#define SQLITE_MISMATCH 20
Definition at line 460 of file sqlite3.h.
Referenced by sqlite3ErrStr(), and sqlite3VdbeExec().
#define SQLITE_MISUSE 21
Definition at line 461 of file sqlite3.h.
Referenced by createCollation(), sqlite3_blob_open(), sqlite3_close(), sqlite3_config(), sqlite3_declare_vtab(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_extended_errcode(), sqlite3_status(), sqlite3_step(), sqlite3ErrStr(), sqlite3LockAndPrepare(), sqlite3Prepare(), sqlite3Prepare16(), sqlite3Step(), sqlite3TransferBindings(), sqlite3VdbeExec(), sqlite3VdbeFinalize(), sqlite3VdbeList(), unixUnlock(), and vdbeUnbind().
#define SQLITE_MUTEX_FAST 0
Definition at line 6281 of file sqlite3.h.
Referenced by sqlite3BtreeOpen().
#define SQLITE_MUTEX_RECURSIVE 1
Definition at line 6282 of file sqlite3.h.
Referenced by openDatabase(), and sqlite3_initialize().
#define SQLITE_MUTEX_STATIC_LRU 6
Definition at line 6287 of file sqlite3.h.
Referenced by sqlite3PcacheInitialize().
#define SQLITE_MUTEX_STATIC_LRU2 7
Definition at line 6288 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_MASTER 2
Definition at line 6283 of file sqlite3.h.
Referenced by enterMutex(), leaveMutex(), localtimeOffset(), removeFromSharingList(), sqlite3_auto_extension(), sqlite3_initialize(), sqlite3_reset_auto_extension(), sqlite3_vfs_find(), sqlite3_vfs_register(), sqlite3_vfs_unregister(), sqlite3AutoLoadExtensions(), sqlite3BtreeOpen(), sqlite3MutexInit(), and vfsUnlink().
#define SQLITE_MUTEX_STATIC_MEM 3
Definition at line 6284 of file sqlite3.h.
Referenced by sqlite3MallocInit().
#define SQLITE_MUTEX_STATIC_MEM2 4
Definition at line 6285 of file sqlite3.h.
#define SQLITE_MUTEX_STATIC_PRNG 5
Definition at line 6286 of file sqlite3.h.
Referenced by sqlite3_randomness().
#define SQLITE_NOLFS 22
Definition at line 462 of file sqlite3.h.
Referenced by findLockInfo(), and sqlite3ErrStr().
#define SQLITE_NOMEM 7
Definition at line 447 of file sqlite3.h.
Referenced by accessPayload(), addToVTrans(), attachFunc(), balance_nonroot(), balance_shallower(), bestVirtualIndex(), constructVtab(), execSql(), fillInUnixFile(), findLockInfo(), fulltextOpen(), fulltextRename(), loadSegmentLeavesInt(), lockTable(), multiSelect(), multiSelectOrderBy(), openDatabase(), pager_delmaster(), pager_open_journal(), pagerStmtBegin(), parseSpec(), pcacheRecycleOrAlloc(), pcacheResizeHash(), porterCreate(), porterNext(), porterOpen(), saveCursorPosition(), schemaIsValid(), selectColumnsFromExprList(), simpleCreate(), simpleNext(), simpleOpen(), sqlite3_auto_extension(), sqlite3_complete16(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_extended_errcode(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3_initialize(), sqlite3_open16(), sqlite3_result_error_nomem(), sqlite3_step(), sqlite3ApiExit(), sqlite3BitvecSet(), sqlite3BtreeDelete(), sqlite3BtreeInsert(), sqlite3BtreeMoveto(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeOpen(), sqlite3CreateFunc(), sqlite3ErrStr(), sqlite3Fts2Init(), sqlite3Fts2InitHashTable(), sqlite3Fts3Init(), sqlite3Fts3InitHashTable(), sqlite3InitCallback(), sqlite3InitOne(), sqlite3LoadExtension(), sqlite3OsOpenMalloc(), sqlite3PagerBegin(), sqlite3PagerDontWrite(), sqlite3PagerOpen(), sqlite3PagerSetPagesize(), sqlite3Pragma(), sqlite3Prepare(), sqlite3RegisterBuiltinFunctions(), sqlite3Reprepare(), sqlite3RunParser(), sqlite3RunVacuum(), sqlite3StartTable(), sqlite3Step(), sqlite3TransferBindings(), sqlite3ValueFromExpr(), sqlite3VdbeChangeEncoding(), sqlite3VdbeExec(), sqlite3VdbeFifoPush(), sqlite3VdbeHalt(), sqlite3VdbeList(), sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemGrow(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTranslate(), sqlite3VdbeSetColName(), vdbeCommit(), and vtabCallConstructor().
#define SQLITE_NOTADB 26
Definition at line 466 of file sqlite3.h.
Referenced by lockBtree(), and sqlite3ErrStr().
#define SQLITE_NOTFOUND 12
Definition at line 452 of file sqlite3.h.
#define SQLITE_NULL 5
Definition at line 3702 of file sqlite3.h.
Referenced by _storeTypeInfo(), absFunc(), attachFunc(), columnMem(), content_select(), countStep(), DbObjCmd(), fulltextUpdate(), FUNC(), groupConcatStep(), ifnullFunc(), lowerFunc(), minmaxFunc(), minmaxStep(), push_column(), quoteFunc(), roundFunc(), segdir_max_index(), segdir_span(), sqlite3_exec(), sqlite3ValueNew(), sqlite3VdbeList(), sqlite3VdbeMemSetNull(), sumStep(), tclSqlFunc(), trimFunc(), typeofFunc(), and upperFunc().
#define SQLITE_OK 0
Definition at line 439 of file sqlite3.h.
Referenced by accessPayload(), addToVTrans(), allocateBtreePage(), allocateCursor(), attachFunc(), auth_callback(), autoVacuumCommit(), balance(), balance_deeper(), balance_nonroot(), balance_quick(), balance_shallower(), bestVirtualIndex(), bindText(), block_delete(), block_insert(), btreeCopyFile(), btreeCreateTable(), btreeCursor(), btreeDropTable(), buildTerms(), changeTempStorage(), checkPtrmap(), checkReadLocks(), clearCell(), clearPendingTerms(), closeUnixFile(), codeAttach(), constructVtab(), content_delete(), content_exists(), content_insert(), content_select(), content_update(), copyPayload(), createCollation(), createIncrblobChannel(), createModule(), DbMain(), DbObjCmd(), decodeFlags(), defragmentPage(), deleteTerms(), do_meta_command(), docListOfTerm(), dropCell(), dump_callback(), execExecSql(), execSql(), fillInCell(), fillInUnixFile(), flushPendingTerms(), freePage(), full_fsync(), fulltextBestIndex(), fulltextClose(), fulltextColumn(), fulltextConnect(), fulltextCreate(), fulltextDestroy(), fulltextDisconnect(), fulltextFilter(), fulltextNext(), fulltextOpen(), fulltextQuery(), fulltextRowid(), fulltextUpdate(), FUNC(), getAndInitPage(), getOverflowPage(), getTempname(), hasHotJournal(), icuLoadCollation(), incrblobClose(), incrblobInput(), incrblobOutput(), incrVacuumStep(), index_delete(), index_insert(), index_insert_term(), index_update(), initPendingTerms(), insertCell(), insertTerms(), interiorWriterDestroy(), interiorWriterRootInfo(), invalidateTempStorage(), leafWriterFinalize(), leafWriterFlush(), leafWriterInternalFlush(), leafWriterRootInfo(), leafWriterStepMerge(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), loadSegment(), loadSegmentInt(), loadSegmentLeaf(), loadSegmentLeaves(), loadSegmentLeavesInt(), lockBtree(), lockBtreeWithRetry(), lockTable(), main(), memjrnlClose(), memjrnlFileSize(), memjrnlRead(), memjrnlSync(), memjrnlTruncate(), memjrnlWrite(), modifyPagePointer(), moveToChild(), moveToLeftmost(), moveToRightmost(), moveToRoot(), multiSelect(), multiSelectOrderBy(), newDatabase(), nolockCheckReservedLock(), nolockLock(), nolockUnlock(), open_db(), openDatabase(), openDirectory(), optimizeFunc(), optimizeInternal(), osUnlock(), pager_delmaster(), pager_end_transaction(), pager_error(), pager_get_content(), pager_incr_changecounter(), pager_open_journal(), pager_playback(), pager_playback_one_page(), pager_stmt_playback(), pager_truncate(), pager_unlock(), pager_wait_on_lock(), pager_write(), pager_write_pagelist(), pagerPagecount(), pagerSharedLock(), pagerStmtBegin(), pagerStress(), pagerUnlockAndRollback(), parseQuery(), parseSpec(), pcacheRecycleOrAlloc(), pcacheResizeHash(), porterClose(), porterCreate(), porterDestroy(), porterNext(), porterOpen(), ptrmapGet(), ptrmapPut(), ptrmapPutOvflPtr(), queryTableLock(), read32bits(), readJournalHdr(), readMasterJournal(), relocatePage(), resolveAttachExpr(), resolveExprStep(), run_table_dump_query(), saveAllCursors(), saveCursorPosition(), schemaIsValid(), segdir_count(), segdir_delete(), segdir_delete_all(), segdir_max_index(), segdir_set(), segdir_span(), segdirNextIndex(), segmentMerge(), selectColumnsFromExprList(), setChildPtrmaps(), setupLookaside(), simpleClose(), simpleCreate(), simpleDestroy(), simpleNext(), simpleOpen(), sql_get_leaf_statement(), sql_get_statement(), sql_single_step(), sql_single_step_statement(), sqlite3_auto_extension(), sqlite3_bind_double(), sqlite3_bind_int64(), sqlite3_bind_null(), sqlite3_bind_value(), sqlite3_bind_zeroblob(), sqlite3_blob_open(), sqlite3_busy_handler(), sqlite3_busy_timeout(), sqlite3_clear_bindings(), sqlite3_close(), sqlite3_collation_needed(), sqlite3_collation_needed16(), sqlite3_config(), sqlite3_create_collation16(), sqlite3_db_status(), sqlite3_declare_vtab(), sqlite3_enable_load_extension(), sqlite3_enable_shared_cache(), sqlite3_exec(), sqlite3_extended_result_codes(), sqlite3_finalize(), sqlite3_get_table(), sqlite3_global_recover(), sqlite3_initialize(), sqlite3_mutex_try(), sqlite3_open16(), sqlite3_os_end(), sqlite3_os_init(), sqlite3_overload_function(), sqlite3_prepare(), sqlite3_prepare16(), sqlite3_prepare16_v2(), sqlite3_prepare_v2(), sqlite3_release_memory(), sqlite3_reset(), sqlite3_reset_auto_extension(), sqlite3_set_authorizer(), sqlite3_shutdown(), sqlite3_status(), sqlite3_vfs_register(), sqlite3_vfs_unregister(), sqlite3AlterRenameTable(), sqlite3Analyze(), sqlite3AuthCheck(), sqlite3AuthRead(), sqlite3AutoLoadExtensions(), sqlite3BeginTrigger(), sqlite3BitvecSet(), sqlite3BtreeBeginStmt(), sqlite3BtreeBeginTrans(), sqlite3BtreeClearTable(), sqlite3BtreeClose(), sqlite3BtreeCloseCursor(), sqlite3BtreeCommit(), sqlite3BtreeCommitPhaseOne(), sqlite3BtreeCommitPhaseTwo(), sqlite3BtreeCommitStmt(), sqlite3BtreeCursorHasMoved(), sqlite3BtreeData(), sqlite3BtreeDataSize(), sqlite3BtreeDelete(), sqlite3BtreeFactory(), sqlite3BtreeFirst(), sqlite3BtreeGetMeta(), sqlite3BtreeGetPage(), sqlite3BtreeInitPage(), sqlite3BtreeInsert(), sqlite3BtreeIntegrityCheck(), sqlite3BtreeKey(), sqlite3BtreeKeySize(), sqlite3BtreeLast(), sqlite3BtreeLockTable(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeNext(), sqlite3BtreeOpen(), sqlite3BtreePrevious(), sqlite3BtreeRestoreCursorPosition(), sqlite3BtreeRollback(), sqlite3BtreeRollbackStmt(), sqlite3BtreeSchemaLocked(), sqlite3BtreeSetAutoVacuum(), sqlite3BtreeSetCacheSize(), sqlite3BtreeSetPageSize(), sqlite3BtreeSetSafetyLevel(), sqlite3BtreeUpdateMeta(), sqlite3CheckCollSeq(), sqlite3CheckObjectName(), sqlite3CreateFunc(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTrigger(), sqlite3ErrorMsg(), sqlite3ErrStr(), sqlite3FinishCoding(), sqlite3Fts2Init(), sqlite3Fts2InitHashTable(), sqlite3Fts3Init(), sqlite3Fts3InitHashTable(), sqlite3IcuInit(), sqlite3IndexedByLookup(), sqlite3Init(), sqlite3InitCallback(), sqlite3InitOne(), sqlite3LoadExtension(), sqlite3LocateTable(), sqlite3MemoryAlarm(), sqlite3MutexEnd(), sqlite3MutexInit(), sqlite3OpenTempDatabase(), sqlite3OsClose(), sqlite3OsCloseFree(), sqlite3OsOpenMalloc(), sqlite3PagerAcquire(), sqlite3PagerBegin(), sqlite3PagerClose(), sqlite3PagerCommitPhaseOne(), sqlite3PagerCommitPhaseTwo(), sqlite3PagerDontWrite(), sqlite3PagerLookup(), sqlite3PagerMovepage(), sqlite3PagerOpen(), sqlite3PagerOpentemp(), sqlite3PagerPagecount(), sqlite3PagerReadFileheader(), sqlite3PagerRef(), sqlite3PagerRollback(), sqlite3PagerSetPagesize(), sqlite3PagerStmtCommit(), sqlite3PagerStmtRollback(), sqlite3PagerSync(), sqlite3PagerTruncate(), sqlite3PagerUnref(), sqlite3PagerWrite(), sqlite3PcacheClear(), sqlite3PcacheFetch(), sqlite3PcacheInitialize(), sqlite3Pragma(), sqlite3Prepare(), sqlite3Prepare16(), sqlite3ReadSchema(), sqlite3RegisterBuiltinFunctions(), sqlite3Reindex(), sqlite3RunParser(), sqlite3RunVacuum(), sqlite3Select(), sqlite3StartTable(), sqlite3Step(), sqlite3TransferBindings(), sqlite3ValueFromExpr(), sqlite3ValueText(), sqlite3VdbeChangeEncoding(), sqlite3VdbeCursorMoveto(), sqlite3VdbeExec(), sqlite3VdbeFifoPop(), sqlite3VdbeFifoPush(), sqlite3VdbeFinalize(), sqlite3VdbeHalt(), sqlite3VdbeIdxKeyCompare(), sqlite3VdbeIdxRowid(), sqlite3VdbeList(), sqlite3VdbeMakeReady(), sqlite3VdbeMemCopy(), sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemFinalize(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemGrow(), sqlite3VdbeMemHandleBom(), sqlite3VdbeMemIntegerify(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemRealify(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTranslate(), sqlite3VdbeReset(), sqlite3VdbeResetStepResult(), sqlite3VtabBegin(), sqlite3VtabCallConnect(), sqlite3VtabCallCreate(), sqlite3VtabCallDestroy(), sqlite3VtabCommit(), sqlite3VtabRollback(), sqlite3VtabSync(), sqliteErrorFromPosixError(), syncJournal(), synthCollSeq(), term_delete(), term_insert(), term_select(), term_select_all(), term_update(), termSelect(), tokenizeSegment(), unixAccess(), unixCheckReservedLock(), unixClose(), unixDelete(), unixFileControl(), unixFileSize(), unixFullPathname(), unixLock(), unixOpen(), unixRead(), unixSync(), unixTruncate(), unixUnlock(), unixWrite(), vdbeCommit(), vdbeUnbind(), vtabCallConstructor(), writeJournalHdr(), writeMasterJournal(), writeZeroSegment(), xferOptimization(), and zeroJournalHdr().
#define SQLITE_OPEN_CREATE 0x00000004
Definition at line 533 of file sqlite3.h.
Referenced by DbMain(), pager_open_journal(), sqlite3_open(), sqlite3_open16(), sqlite3OpenTempDatabase(), sqlite3PagerOpentemp(), sqlite3VdbeExec(), unixOpen(), and vdbeCommit().
#define SQLITE_OPEN_DELETEONCLOSE 0x00000008
Definition at line 534 of file sqlite3.h.
Referenced by openDatabase(), pager_open_journal(), sqlite3OpenTempDatabase(), sqlite3PagerOpentemp(), sqlite3VdbeExec(), and unixOpen().
#define SQLITE_OPEN_EXCLUSIVE 0x00000010
Definition at line 535 of file sqlite3.h.
Referenced by pager_open_journal(), sqlite3OpenTempDatabase(), sqlite3PagerOpentemp(), sqlite3VdbeExec(), unixOpen(), and vdbeCommit().
#define SQLITE_OPEN_FULLMUTEX 0x00010000
Definition at line 544 of file sqlite3.h.
Referenced by DbMain(), and openDatabase().
#define SQLITE_OPEN_MAIN_DB 0x00000100
Definition at line 536 of file sqlite3.h.
Referenced by attachFunc(), openDatabase(), sqlite3BtreeFactory(), and unixOpen().
#define SQLITE_OPEN_MAIN_JOURNAL 0x00000800
Definition at line 539 of file sqlite3.h.
Referenced by openDatabase(), pager_delmaster(), pager_open_journal(), pagerSharedLock(), and unixOpen().
#define SQLITE_OPEN_MASTER_JOURNAL 0x00004000
Definition at line 542 of file sqlite3.h.
Referenced by openDatabase(), pager_delmaster(), unixOpen(), and vdbeCommit().
#define SQLITE_OPEN_NOMUTEX 0x00008000
Definition at line 543 of file sqlite3.h.
Referenced by DbMain(), and openDatabase().
#define SQLITE_OPEN_READONLY 0x00000001
Definition at line 531 of file sqlite3.h.
Referenced by DbMain(), pager_delmaster(), pagerSharedLock(), sqlite3PagerOpen(), and unixOpen().
#define SQLITE_OPEN_READWRITE 0x00000002
Definition at line 532 of file sqlite3.h.
Referenced by DbMain(), pager_open_journal(), pagerSharedLock(), sqlite3_open(), sqlite3_open16(), sqlite3OpenTempDatabase(), sqlite3PagerOpentemp(), sqlite3VdbeExec(), unixOpen(), and vdbeCommit().
#define SQLITE_OPEN_SUBJOURNAL 0x00002000
Definition at line 541 of file sqlite3.h.
Referenced by openDatabase(), pagerStmtBegin(), and unixOpen().
#define SQLITE_OPEN_TEMP_DB 0x00000200
Definition at line 537 of file sqlite3.h.
Referenced by openDatabase(), sqlite3BtreeFactory(), sqlite3OpenTempDatabase(), and unixOpen().
#define SQLITE_OPEN_TEMP_JOURNAL 0x00001000
Definition at line 540 of file sqlite3.h.
Referenced by openDatabase(), pager_open_journal(), and unixOpen().
#define SQLITE_OPEN_TRANSIENT_DB 0x00000400
Definition at line 538 of file sqlite3.h.
Referenced by openDatabase(), sqlite3VdbeExec(), and unixOpen().
#define SQLITE_PERM 3
Definition at line 443 of file sqlite3.h.
Referenced by pager_write(), sqlite3BtreeDelete(), sqlite3BtreeInsert(), sqlite3ErrStr(), and sqliteErrorFromPosixError().
#define SQLITE_PRAGMA 19
Definition at line 2386 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3Pragma().
#define SQLITE_PROTOCOL 15
Definition at line 455 of file sqlite3.h.
#define SQLITE_RANGE 25
Definition at line 465 of file sqlite3.h.
Referenced by columnMem(), sqlite3ErrStr(), and vdbeUnbind().
#define SQLITE_READ 20
Definition at line 2387 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3AuthRead().
#define SQLITE_READONLY 8
Definition at line 448 of file sqlite3.h.
Referenced by btreeCreateTable(), btreeCursor(), btreeDropTable(), sqlite3BtreeBeginStmt(), sqlite3BtreeBeginTrans(), sqlite3BtreeClearTable(), sqlite3BtreeDelete(), sqlite3BtreeInsert(), sqlite3BtreePutData(), sqlite3BtreeSetAutoVacuum(), sqlite3BtreeSetPageSize(), sqlite3BtreeUpdateMeta(), sqlite3ErrStr(), and sqlite3VdbeExec().
#define SQLITE_REINDEX 27
Definition at line 2394 of file sqlite3.h.
Referenced by auth_callback(), and sqlite3RefillIndex().
#define SQLITE_ROW 100
Definition at line 467 of file sqlite3.h.
Referenced by block_insert(), content_exists(), content_select(), db_get(), DbObjCmd(), dump_callback(), execExecSql(), execSql(), fulltextNext(), fulltextUpdate(), index_insert_term(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), optimizeFunc(), run_table_dump_query(), segdir_count(), segdir_delete(), segdir_max_index(), segdir_span(), segdirNextIndex(), sql_step_statement(), sqlite3_blob_open(), sqlite3_exec(), sqlite3ErrStr(), sqlite3Step(), sqlite3VdbeExec(), sqlite3VdbeList(), term_select(), term_select_all(), and termSelect().
#define SQLITE_SCHEMA 17
Definition at line 457 of file sqlite3.h.
Referenced by sqlite3_blob_open(), sqlite3_exec(), sqlite3_step(), sqlite3ErrStr(), sqlite3Prepare(), sqlite3Step(), and sqlite3VdbeExec().
#define SQLITE_SELECT 21
Definition at line 2388 of file sqlite3.h.
Referenced by auth_callback(), flattenSubquery(), and sqlite3Select().
#define SQLITE_STATIC ((sqlite3_destructor_type)0)
Definition at line 4468 of file sqlite3.h.
Referenced by block_insert(), callCollNeeded(), db_get(), db_set(), DbObjCmd(), do_meta_command(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_keypress(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_smsevent(), log_text_to_db(), optimizeFunc(), quoteFunc(), returnSingleInt(), segdir_set(), shellstaticFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_complete16(), sqlite3_errmsg16(), sqlite3_open16(), sqlite3_result_error_toobig(), sqlite3DeleteFrom(), sqlite3Error(), sqlite3Insert(), sqlite3Pragma(), sqlite3Prepare(), sqlite3Update(), sqlite3Utf16to8(), sqlite3VdbeExec(), sqlite3VdbeMemSetStr(), term_insert(), term_select(), term_select_all(), term_update(), trimFunc(), typeofFunc(), and versionFunc().
#define SQLITE_STATUS_MALLOC_SIZE 5
Definition at line 6479 of file sqlite3.h.
Referenced by mallocWithAlarm(), and sqlite3Realloc().
#define SQLITE_STATUS_MEMORY_USED 0
Definition at line 6474 of file sqlite3.h.
Referenced by mallocWithAlarm(), sqlite3_free(), sqlite3_memory_highwater(), sqlite3_memory_used(), sqlite3MallocAlarm(), sqlite3Realloc(), and sqlite3ScratchFree().
#define SQLITE_STATUS_PAGECACHE_OVERFLOW 2
Definition at line 6476 of file sqlite3.h.
Referenced by pcacheFree(), and pcacheMalloc().
#define SQLITE_STATUS_PAGECACHE_SIZE 7
Definition at line 6481 of file sqlite3.h.
Referenced by pcacheMalloc().
#define SQLITE_STATUS_PAGECACHE_USED 1
Definition at line 6475 of file sqlite3.h.
Referenced by pcacheFree(), and pcacheMalloc().
#define SQLITE_STATUS_PARSER_STACK 6
Definition at line 6480 of file sqlite3.h.
Referenced by sqlite3RunParser().
#define SQLITE_STATUS_SCRATCH_OVERFLOW 4
Definition at line 6478 of file sqlite3.h.
Referenced by sqlite3ScratchFree(), and sqlite3ScratchMalloc().
#define SQLITE_STATUS_SCRATCH_SIZE 8
Definition at line 6482 of file sqlite3.h.
Referenced by sqlite3ScratchMalloc().
#define SQLITE_STATUS_SCRATCH_USED 3
Definition at line 6477 of file sqlite3.h.
Referenced by sqlite3ScratchFree(), and sqlite3ScratchMalloc().
#define SQLITE_STMTSTATUS_FULLSCAN_STEP 1
Definition at line 6567 of file sqlite3.h.
Referenced by DbObjCmd(), and sqlite3WhereBegin().
#define SQLITE_STMTSTATUS_SORT 2
Definition at line 6568 of file sqlite3.h.
Referenced by DbObjCmd(), and sqlite3VdbeExec().
#define SQLITE_SYNC_DATAONLY 0x00010
Definition at line 606 of file sqlite3.h.
Referenced by syncJournal(), unixSync(), and zeroJournalHdr().
#define SQLITE_SYNC_FULL 0x00003
Definition at line 605 of file sqlite3.h.
Referenced by sqlite3PagerSetSafetyLevel(), syncJournal(), and unixSync().
#define SQLITE_SYNC_NORMAL 0x00002
Definition at line 604 of file sqlite3.h.
Referenced by sqlite3PagerOpen(), sqlite3PagerSetSafetyLevel(), unixSync(), and vdbeCommit().
#define SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS 10
Definition at line 6362 of file sqlite3.h.
Referenced by sqlite3_test_control().
#define SQLITE_TESTCTRL_BITVEC_TEST 8
Definition at line 6360 of file sqlite3.h.
Referenced by sqlite3_test_control().
#define SQLITE_TESTCTRL_FAULT_INSTALL 9
Definition at line 6361 of file sqlite3.h.
#define SQLITE_TESTCTRL_PRNG_RESET 7
Definition at line 6359 of file sqlite3.h.
Referenced by sqlite3_test_control().
#define SQLITE_TESTCTRL_PRNG_RESTORE 6
Definition at line 6358 of file sqlite3.h.
Referenced by sqlite3_test_control().
#define SQLITE_TESTCTRL_PRNG_SAVE 5
Definition at line 6357 of file sqlite3.h.
Referenced by sqlite3_test_control().
#define SQLITE_TEXT 3
Definition at line 3706 of file sqlite3.h.
Referenced by _storeTypeInfo(), attachFunc(), FUNC(), lengthFunc(), push_column(), quoteFunc(), sqlite3VdbeList(), sqlite3VdbeMemSetStr(), and typeofFunc().
#define SQLITE_TOOBIG 18
Definition at line 458 of file sqlite3.h.
Referenced by sqlite3_result_error_toobig(), sqlite3ErrStr(), sqlite3Prepare(), sqlite3RunParser(), sqlite3VdbeExec(), and sqlite3VdbeMemSetStr().
#define SQLITE_TRANSACTION 22
Definition at line 2389 of file sqlite3.h.
Referenced by auth_callback(), sqlite3BeginTransaction(), sqlite3CommitTransaction(), and sqlite3RollbackTransaction().
#define SQLITE_TRANSIENT ((sqlite3_destructor_type)-1)
Definition at line 4469 of file sqlite3.h.
Referenced by dateFunc(), datetimeFunc(), fulltextColumn(), FUNC(), generateColumnNames(), generateColumnTypes(), quoteFunc(), scalarFunc(), sqlite3_result_error(), sqlite3_result_error16(), sqlite3Pragma(), sqlite3VdbeMemSetStr(), sqlite3VdbeReset(), strftimeFunc(), substrFunc(), tclSqlFunc(), timeFunc(), and trimFunc().
#define SQLITE_UPDATE 23
Definition at line 2390 of file sqlite3.h.
Referenced by auth_callback(), DbUpdateHandler(), sqlite3Update(), and sqlite3VdbeExec().
#define SQLITE_UTF16 4
Definition at line 4154 of file sqlite3.h.
Referenced by createCollation(), icuLoadCollation(), sqlite3CreateFunc(), and sqlite3IcuInit().
#define SQLITE_UTF16_ALIGNED 8
Definition at line 4156 of file sqlite3.h.
Referenced by createCollation(), and sqlite3ValueText().
#define SQLITE_UTF16BE 3
Definition at line 4153 of file sqlite3.h.
Referenced by findCollSeqEntry(), matchQuality(), openDatabase(), sqlite3_result_text16be(), sqlite3_value_text16be(), sqlite3CreateFunc(), sqlite3FindCollSeq(), sqlite3FindFunction(), sqlite3IsNumber(), sqlite3MemCompare(), sqlite3Pragma(), sqlite3Utf16ByteLen(), sqlite3VdbeMemHandleBom(), sqlite3VdbeMemTranslate(), and synthCollSeq().
#define SQLITE_UTF16LE 2
Definition at line 4152 of file sqlite3.h.
Referenced by findCollSeqEntry(), matchQuality(), openDatabase(), sqlite3_errmsg16(), sqlite3_result_text16le(), sqlite3_value_text16le(), sqlite3CreateFunc(), sqlite3FindCollSeq(), sqlite3FindFunction(), sqlite3MemCompare(), sqlite3Pragma(), sqlite3VdbeMemHandleBom(), sqlite3VdbeMemTranslate(), and synthCollSeq().
#define SQLITE_UTF8 1
Definition at line 4151 of file sqlite3.h.
Referenced by applyNumericAffinity(), callCollNeeded(), DbObjCmd(), findCollSeqEntry(), FUNC(), open_db(), openDatabase(), parseDateOrTime(), setLikeOptFlag(), sqlite3_bind_text(), sqlite3_complete16(), sqlite3_errmsg16(), sqlite3_open16(), sqlite3_overload_function(), sqlite3_result_error(), sqlite3_result_error_toobig(), sqlite3_result_text(), sqlite3_value_bytes(), sqlite3_value_text(), sqlite3AlterFinishAddColumn(), sqlite3AlterFunctions(), sqlite3Attach(), sqlite3CreateFunc(), sqlite3Detach(), sqlite3Error(), sqlite3FindCollSeq(), sqlite3FindFunction(), sqlite3IcuInit(), sqlite3InitOne(), sqlite3IsLikeFunction(), sqlite3IsNumber(), sqlite3MemCompare(), sqlite3Pragma(), sqlite3RegisterLikeFunctions(), sqlite3SchemaGet(), sqlite3Utf16to8(), sqlite3ValueFromExpr(), sqlite3VdbeExec(), sqlite3VdbeIntValue(), sqlite3VdbeList(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemSetZeroBlob(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTranslate(), sqlite3VdbeRealValue(), sqlite3VdbeReset(), sqlite3VdbeSetColName(), and synthCollSeq().
#define SQLITE_VERSION "3.6.5"
Definition at line 122 of file sqlite3.h.
#define SQLITE_VERSION_NUMBER 3006005
Definition at line 123 of file sqlite3.h.
Referenced by sqlite3_libversion_number().
Typedef Documentation
typedef struct sqlite3 sqlite3
Definition at line 209 of file sqlite3.h.
typedef struct sqlite3_blob sqlite3_blob
Definition at line 5749 of file sqlite3.h.
typedef int(* sqlite3_callback)(void *, int, char **, char **)
Definition at line 309 of file sqlite3.h.
typedef struct sqlite3_context sqlite3_context
Definition at line 3082 of file sqlite3.h.
typedef void(* sqlite3_destructor_type)(void *)
Definition at line 4467 of file sqlite3.h.
typedef struct sqlite3_file sqlite3_file
Definition at line 618 of file sqlite3.h.
typedef struct sqlite3_index_info sqlite3_index_info
Definition at line 5473 of file sqlite3.h.
typedef sqlite_int64 sqlite3_int64
Definition at line 240 of file sqlite3.h.
typedef struct sqlite3_io_methods sqlite3_io_methods
Definition at line 704 of file sqlite3.h.
typedef struct sqlite3_mem_methods sqlite3_mem_methods
Definition at line 1191 of file sqlite3.h.
typedef struct sqlite3_module sqlite3_module
Definition at line 5475 of file sqlite3.h.
typedef struct sqlite3_mutex sqlite3_mutex
Definition at line 749 of file sqlite3.h.
typedef struct sqlite3_mutex_methods sqlite3_mutex_methods
Definition at line 6226 of file sqlite3.h.
typedef struct sqlite3_stmt sqlite3_stmt
Definition at line 2767 of file sqlite3.h.
typedef sqlite_uint64 sqlite3_uint64
Definition at line 241 of file sqlite3.h.
typedef struct Mem sqlite3_value
Definition at line 3068 of file sqlite3.h.
typedef struct sqlite3_vfs sqlite3_vfs
Definition at line 869 of file sqlite3.h.
typedef struct sqlite3_vtab sqlite3_vtab
Definition at line 5472 of file sqlite3.h.
typedef struct sqlite3_vtab_cursor sqlite3_vtab_cursor
Definition at line 5474 of file sqlite3.h.
typedef long long int sqlite_int64
Definition at line 237 of file sqlite3.h.
typedef unsigned long long int sqlite_uint64
Definition at line 238 of file sqlite3.h.
Function Documentation
void* sqlite3_aggregate_context (sqlite3_context * , int nBytes)
Definition at line 620 of file vdbeapi.c.
References Mem::db, Mem::flags, MEM_Agg, MEM_Null, sqlite3::mutex, Mem::pDef, sqlite3_context::pFunc, sqlite3_context::pMem, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemGrow(), sqlite3VdbeMemReleaseExternal(), Mem::u, FuncDef::xStep, and Mem::z.
Referenced by avgFinalize(), countFinalize(), countStep(), FUNC(), groupConcatFinalize(), groupConcatStep(), minMaxFinalize(), minmaxStep(), sumFinalize(), sumStep(), and totalFinalize().
SQLITE_DEPRECATED int sqlite3_aggregate_count (sqlite3_context *)
Definition at line 711 of file vdbeapi.c.
References Mem::n, sqlite3_context::pFunc, sqlite3_context::pMem, and FuncDef::xStep.
Referenced by FUNC().
int sqlite3_auto_extension (void * xEntryPoint)
Definition at line 511 of file loadext.c.
References sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_realloc(), sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_NOMEM, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
int sqlite3_bind_blob (sqlite3_stmt * , int , const void * , int n, void(*)(void *))
Definition at line 1080 of file vdbeapi.c.
References bindText().
Referenced by block_insert(), DbObjCmd(), FUNC(), segdir_set(), term_insert(), and term_update().
int sqlite3_bind_double (sqlite3_stmt * , int , double)
Definition at line 1089 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, sqlite3VdbeMemSetDouble(), SQLITE_OK, and vdbeUnbind().
Referenced by DbObjCmd(), FUNC(), and log_db_log_position().
int sqlite3_bind_int (sqlite3_stmt * , int , int)
Definition at line 1099 of file vdbeapi.c.
References sqlite3_bind_int64().
Referenced by DbObjCmd(), FUNC(), leavesReadersInit(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), segdir_max_index(), segdir_set(), segdir_span(), term_insert(), and term_select().
int sqlite3_bind_int64 (sqlite3_stmt * , int , sqlite3_int64)
Referenced by block_delete(), content_delete(), content_select(), content_update(), DbObjCmd(), fulltextFilter(), fulltextNext(), leavesReaderInit(), loadAndGetChildrenContaining(), log_db_log_appfocus(), segdir_delete(), segdir_set(), sqlite3_bind_int(), sqlite3_blob_open(), term_delete(), term_insert(), and term_update().
int sqlite3_bind_null (sqlite3_stmt * , int)
Definition at line 1112 of file vdbeapi.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, SQLITE_OK, and vdbeUnbind().
Referenced by DbObjCmd(), FUNC(), and term_insert().
int sqlite3_bind_parameter_count (sqlite3_stmt *)
Definition at line 1170 of file vdbeapi.c.
References Vdbe::nVar.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_bind_parameter_index (sqlite3_stmt * , const char * zName)
Definition at line 1218 of file vdbeapi.c.
References Vdbe::azVar, createVarMap(), and Vdbe::nVar.
const char* sqlite3_bind_parameter_name (sqlite3_stmt * , int)
Definition at line 1204 of file vdbeapi.c.
References Vdbe::azVar, createVarMap(), and Vdbe::nVar.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_bind_text (sqlite3_stmt * , int , const char * , int n, void(*)(void *))
Definition at line 1121 of file vdbeapi.c.
References bindText(), and SQLITE_UTF8.
Referenced by db_get(), db_set(), DbObjCmd(), do_meta_command(), FUNC(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_keypress(), log_db_log_mark(), log_db_log_position(), log_db_log_profile(), log_db_log_smsevent(), log_text_to_db(), term_insert(), term_select(), and term_select_all().
int sqlite3_bind_text16 (sqlite3_stmt * , int , const void * , int , void(*)(void *))
Definition at line 1131 of file vdbeapi.c.
References bindText(), and SQLITE_UTF16NATIVE.
int sqlite3_bind_value (sqlite3_stmt * , int , const sqlite3_value *)
Definition at line 1141 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, ENC, sqlite3::mutex, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemCopy(), SQLITE_OK, and vdbeUnbind().
Referenced by content_insert(), and content_update().
int sqlite3_bind_zeroblob (sqlite3_stmt * , int , int n)
Definition at line 1155 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, sqlite3VdbeMemSetZeroBlob(), SQLITE_OK, and vdbeUnbind().
int sqlite3_blob_bytes (sqlite3_blob *)
Definition at line 343 of file vdbeblob.c.
References Incrblob::nByte.
Referenced by incrblobInput(), incrblobOutput(), and incrblobSeek().
int sqlite3_blob_close (sqlite3_blob *)
Definition at line 266 of file vdbeblob.c.
References Incrblob::db, Incrblob::pStmt, sqlite3_finalize(), and sqlite3DbFree().
Referenced by incrblobClose().
int sqlite3_blob_open (sqlite3 * , const char * zDb, const char * zTable, const char * zColumn, sqlite3_int64 iRow, int flags, sqlite3_blob ** ppBlob)
Referenced by createIncrblobChannel().
int sqlite3_blob_read (sqlite3_blob * , void * Z, int N, int iOffset)
Definition at line 326 of file vdbeblob.c.
References blobReadWrite(), and sqlite3BtreeData().
Referenced by incrblobInput().
int sqlite3_blob_write (sqlite3_blob * , const void * z, int n, int iOffset)
Definition at line 333 of file vdbeblob.c.
References blobReadWrite(), and sqlite3BtreePutData().
Referenced by incrblobOutput().
int sqlite3_busy_handler (sqlite3 * , int(*)(void *, int) , void *)
Definition at line 782 of file main.c.
References sqlite3::busyHandler, sqlite3::mutex, BusyHandler::nBusy, BusyHandler::pArg, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_OK, and BusyHandler::xFunc.
Referenced by DbObjCmd(), FUNC(), and sqlite3_busy_timeout().
int sqlite3_busy_timeout (sqlite3 * , int ms)
Definition at line 826 of file main.c.
References sqlite3::busyTimeout, sqlite3_busy_handler(), SQLITE_OK, and sqliteDefaultBusyCallback().
Referenced by DbObjCmd(), do_meta_command(), and FUNC().
int sqlite3_changes (sqlite3 *)
Definition at line 520 of file main.c.
References sqlite3::nChange.
Referenced by changes(), DbObjCmd(), and FUNC().
int sqlite3_clear_bindings (sqlite3_stmt *)
Definition at line 245 of file vdbeapi.c.
References Vdbe::aVar, Mem::flags, MEM_Null, Vdbe::nVar, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeMemRelease(), and SQLITE_OK.
IMPORT_C int sqlite3_close (sqlite3 *)
Definition at line 534 of file main.c.
References FuncDefHash::a, sqlite3::aCollSeq, sqlite3::aDb, sqlite3::aDbStatic, sqlite3::aFunc, sqlite3::aModule, ArraySize, Lookaside::bMalloced, sqlite3::lookaside, sqlite3::magic, sqlite3::mutex, sqlite3::nDb, Lookaside::nOut, Module::pAux, Db::pBt, sqlite3::pErr, FuncDef::pHash, FuncDef::pNext, Db::pSchema, Lookaside::pStart, sqlite3::pVdbe, sqlite3_free(), sqlite3_mutex_enter, sqlite3_mutex_free, sqlite3_mutex_leave, sqlite3BtreeClose(), sqlite3CloseExtensions, sqlite3DbFree(), sqlite3Error(), sqlite3HashClear(), sqlite3ResetInternalSchema(), sqlite3SafetyCheckSickOrOk(), sqlite3ValueFree(), sqlite3VtabRollback(), SQLITE_BUSY, SQLITE_MAGIC_CLOSED, SQLITE_MAGIC_ERROR, SQLITE_MISUSE, SQLITE_OK, sqliteHashData, sqliteHashFirst, sqliteHashNext, CollSeq::xDel, and Module::xDestroy.
Referenced by close_config_db_session(), create_database(), DbDeleteCmd(), DbMain(), log_db_close_session(), main(), and openDatabase().
int sqlite3_collation_needed (sqlite3 * , void * , void(*)(void *, sqlite3 *, int eTextRep, const char *))
Definition at line 1780 of file main.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_OK, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_collation_needed16 (sqlite3 * , void * , void(*)(void *, sqlite3 *, int eTextRep, const void *))
Definition at line 1798 of file main.c.
References sqlite3::mutex, sqlite3::pCollNeededArg, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_OK, sqlite3::xCollNeeded, and sqlite3::xCollNeeded16.
const void* sqlite3_column_blob (sqlite3_stmt * , int iCol)
Definition at line 800 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_blob().
Referenced by DbObjCmd(), FUNC(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), optimizeFunc(), push_column(), term_select(), term_select_all(), and termSelect().
int sqlite3_column_bytes (sqlite3_stmt * , int iCol)
Definition at line 810 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_bytes().
Referenced by DbObjCmd(), l_sqlite3_column_text_or_blob(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), optimizeFunc(), push_column(), snippetAllOffsets(), snippetText(), term_select(), term_select_all(), and termSelect().
int sqlite3_column_bytes16 (sqlite3_stmt * , int iCol)
Definition at line 815 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_bytes16().
int sqlite3_column_count (sqlite3_stmt * pStmt)
Definition at line 720 of file vdbeapi.c.
References Vdbe::nResColumn.
Referenced by columnName(), computeColumnNames(), DbObjCmd(), do_meta_command(), FUNC(), and sqlite3_exec().
const char* sqlite3_column_database_name (sqlite3_stmt * , int)
const void* sqlite3_column_database_name16 (sqlite3_stmt * , int)
const char* sqlite3_column_decltype (sqlite3_stmt * , int)
Definition at line 945 of file vdbeapi.c.
References COLNAME_DECLTYPE, columnName(), and sqlite3_value_text().
Referenced by FUNC().
const void* sqlite3_column_decltype16 (sqlite3_stmt * , int)
Definition at line 950 of file vdbeapi.c.
References COLNAME_DECLTYPE, columnName(), and sqlite3_value_text16().
double sqlite3_column_double (sqlite3_stmt * , int iCol)
Definition at line 820 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_double().
Referenced by DbObjCmd(), FUNC(), and push_column().
int sqlite3_column_int (sqlite3_stmt * , int iCol)
Definition at line 825 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_int().
Referenced by FUNC(), push_column(), segdir_count(), and segdir_max_index().
sqlite3_int64 sqlite3_column_int64 (sqlite3_stmt * , int iCol)
Definition at line 830 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_int64().
Referenced by DbObjCmd(), fulltextRowid(), leavesReadersInit(), optimizeFunc(), segdir_span(), term_select(), and termSelect().
const char* sqlite3_column_name (sqlite3_stmt * , int N)
Definition at line 920 of file vdbeapi.c.
References COLNAME_NAME, columnName(), and sqlite3_value_text().
Referenced by computeColumnNames(), FUNC(), l_sqlite3_row_mode(), and sqlite3_exec().
const void* sqlite3_column_name16 (sqlite3_stmt * , int N)
Definition at line 925 of file vdbeapi.c.
References COLNAME_NAME, columnName(), and sqlite3_value_text16().
const char* sqlite3_column_origin_name (sqlite3_stmt * , int)
const void* sqlite3_column_origin_name16 (sqlite3_stmt * , int)
const char* sqlite3_column_table_name (sqlite3_stmt * , int)
const void* sqlite3_column_table_name16 (sqlite3_stmt * , int)
const unsigned char* sqlite3_column_text (sqlite3_stmt * , int iCol)
Definition at line 835 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_text().
Referenced by content_select(), db_get(), DbObjCmd(), dump_callback(), execExecSql(), FUNC(), push_column(), run_table_dump_query(), snippetAllOffsets(), snippetText(), and sqlite3_exec().
const void* sqlite3_column_text16 (sqlite3_stmt * , int iCol)
Definition at line 850 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_text16().
int sqlite3_column_type (sqlite3_stmt * , int iCol)
Definition at line 856 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_type().
Referenced by content_select(), DbObjCmd(), FUNC(), push_column(), segdir_max_index(), segdir_span(), and sqlite3_exec().
sqlite3_value* sqlite3_column_value (sqlite3_stmt * , int iCol)
Definition at line 840 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), Mem::flags, MEM_Ephem, and MEM_Static.
Referenced by fulltextColumn().
void* sqlite3_commit_hook (sqlite3 * , int(*)(void *) , void *)
Definition at line 1054 of file main.c.
References sqlite3::mutex, sqlite3::pCommitArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xCommitCallback.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_complete (const char * sql)
Definition at line 102 of file complete.c.
References IdChar, sqlite3StrNICmp(), tkCREATE, tkEND, tkEXPLAIN, tkOTHER, tkSEMI, tkTEMP, tkTRIGGER, and tkWS.
Referenced by DbObjCmd(), FUNC(), process_input(), and sqlite3_complete16().
int sqlite3_complete16 (const void * sql)
Definition at line 256 of file complete.c.
References sqlite3_complete(), sqlite3_initialize(), sqlite3ApiExit(), sqlite3ValueFree(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3ValueText(), SQLITE_NOMEM, SQLITE_STATIC, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
SQLITE_EXPERIMENTAL int sqlite3_config (int , ...)
Definition at line 234 of file main.c.
References sqlite3GlobalConfig, sqlite3MemGetMemsys3(), sqlite3MemGetMemsys5(), sqlite3MemSetDefault(), SQLITE_CONFIG_GETMALLOC, SQLITE_CONFIG_GETMUTEX, SQLITE_CONFIG_HEAP, SQLITE_CONFIG_LOOKASIDE, SQLITE_CONFIG_MALLOC, SQLITE_CONFIG_MEMSTATUS, SQLITE_CONFIG_MULTITHREAD, SQLITE_CONFIG_MUTEX, SQLITE_CONFIG_PAGECACHE, SQLITE_CONFIG_SCRATCH, SQLITE_CONFIG_SERIALIZED, SQLITE_CONFIG_SINGLETHREAD, SQLITE_ERROR, SQLITE_MISUSE, and SQLITE_OK.
sqlite3* sqlite3_context_db_handle (sqlite3_context *)
Definition at line 589 of file vdbeapi.c.
References Mem::db, sqlite3_context::pFunc, and sqlite3_context::s.
Referenced by attachFunc(), changes(), contextMalloc(), detachFunc(), groupConcatStep(), last_insert_rowid(), likeFunc(), loadExt(), optimizeFunc(), renameTableFunc(), renameTriggerFunc(), replaceFunc(), setDateTimeToCurrent(), strftimeFunc(), substrFunc(), and total_changes().
int sqlite3_create_collation (sqlite3 * , const char * zName, int eTextRep, void * , int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 1714 of file main.c.
References createCollation(), sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3ApiExit().
Referenced by DbObjCmd(), and FUNC().
int sqlite3_create_collation16 (sqlite3 * , const void * zName, int eTextRep, void * , int(*)(void *, int, const void *, int, const void *) xCompare)
Definition at line 1754 of file main.c.
References createCollation(), sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3DbFree(), sqlite3Utf16to8(), and SQLITE_OK.
int sqlite3_create_collation_v2 (sqlite3 * , const char * zName, int eTextRep, void * , int(*)(void *, int, const void *, int, const void *) xCompare, void(*)(void *) xDestroy)
Definition at line 1733 of file main.c.
References createCollation(), sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3ApiExit().
Referenced by icuLoadCollation().
int sqlite3_create_function (sqlite3 * db, const char * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 935 of file main.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), and sqlite3CreateFunc().
Referenced by DbObjCmd(), FUNC(), open_db(), sqlite3Fts2InitHashTable(), sqlite3Fts3InitHashTable(), and sqlite3IcuInit().
int sqlite3_create_function16 (sqlite3 * db, const void * zFunctionName, int nArg, int eTextRep, void * pApp, void(*)(sqlite3_context *, int, sqlite3_value **) xFunc, void(*)(sqlite3_context *, int, sqlite3_value **) xStep, void(*)(sqlite3_context *) xFinal)
Definition at line 954 of file main.c.
References sqlite3::mallocFailed, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3DbFree(), and sqlite3Utf16to8().
SQLITE_EXPERIMENTAL int sqlite3_create_module (sqlite3 * db, const char * zName, const sqlite3_module * , void *)
Definition at line 59 of file vtab.c.
References createModule().
Referenced by sqlite3Fts1Init().
SQLITE_EXPERIMENTAL int sqlite3_create_module_v2 (sqlite3 * db, const char * zName, const sqlite3_module * , void * , void(*)(void *) xDestroy)
Definition at line 71 of file vtab.c.
References createModule().
Referenced by sqlite3Fts2Init(), and sqlite3Fts3Init().
int sqlite3_data_count (sqlite3_stmt * pStmt)
Definition at line 729 of file vdbeapi.c.
References Vdbe::nResColumn, and Vdbe::pResultSet.
Referenced by columnMem(), FUNC(), and l_sqlite3_row_mode().
SQLITE_EXPERIMENTAL int sqlite3_db_config (sqlite3 * , int op, ...)
Definition at line 420 of file main.c.
References setupLookaside(), SQLITE_DBCONFIG_LOOKASIDE, and SQLITE_ERROR.
sqlite3* sqlite3_db_handle (sqlite3_stmt *)
Definition at line 1278 of file vdbeapi.c.
sqlite3_mutex* sqlite3_db_mutex (sqlite3 *)
Definition at line 413 of file main.c.
References sqlite3::mutex.
SQLITE_EXPERIMENTAL int sqlite3_db_status (sqlite3 * , int op, int * pCur, int * pHiwtr, int resetFlg)
Definition at line 101 of file status.c.
References sqlite3::lookaside, Lookaside::mxOut, Lookaside::nOut, SQLITE_DBSTATUS_LOOKASIDE_USED, SQLITE_ERROR, and SQLITE_OK.
SQLITE_EXPERIMENTAL int sqlite3_declare_vtab (sqlite3 * , const char * zCreateTable)
Definition at line 533 of file vtab.c.
References Table::aCol, Parse::db, Parse::declareVtab, sqlite3::mutex, Table::nCol, Parse::pNewTable, Table::pSelect, Parse::pVdbe, sqlite3::pVTab, sqlite3_finalize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3Error(), sqlite3RunParser(), SQLITE_ERROR, SQLITE_MISUSE, SQLITE_OK, Table::tabFlags, and TF_Virtual.
Referenced by constructVtab().
int sqlite3_enable_load_extension (sqlite3 * db, int onoff)
Definition at line 454 of file loadext.c.
References sqlite3::flags, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, SQLITE_LoadExtension, and SQLITE_OK.
Referenced by DbObjCmd(), and open_db().
int sqlite3_enable_shared_cache (int)
Definition at line 75 of file btree.c.
References sqlite3GlobalConfig, and SQLITE_OK.
int sqlite3_errcode (sqlite3 * db)
Definition at line 1259 of file main.c.
References sqlite3::errCode, sqlite3::errMask, sqlite3::mallocFailed, sqlite3SafetyCheckSickOrOk(), SQLITE_MISUSE, and SQLITE_NOMEM.
Referenced by DbMain(), DbObjCmd(), execSql(), FUNC(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), open_db(), openDatabase(), prepare_sql_statements(), and sqlite3_exec().
IMPORT_C const char* sqlite3_errmsg (sqlite3 *)
Definition at line 1185 of file main.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_value_text(), sqlite3ErrStr(), sqlite3SafetyCheckSickOrOk(), SQLITE_MISUSE, and SQLITE_NOMEM.
Referenced by createIncrblobChannel(), DbMain(), DbObjCmd(), do_meta_command(), FUNC(), incrblobClose(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), main(), open_db(), optimizeFunc(), prepare_sql_statements(), process_input(), sqlite3_blob_open(), and sqlite3_exec().
const void* sqlite3_errmsg16 (sqlite3 *)
Definition at line 1209 of file main.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_value_text16(), sqlite3ErrStr(), sqlite3SafetyCheckSickOrOk(), sqlite3ValueSetStr(), SQLITE_STATIC, SQLITE_UTF16LE, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
IMPORT_C int sqlite3_exec (sqlite3 * , const char * sql, int(*)(void *, int, char **, char **) callback, void * , char ** errmsg)
SQLITE_DEPRECATED int sqlite3_expired (sqlite3_stmt *)
Definition at line 186 of file vdbeapi.c.
References Vdbe::expired.
int sqlite3_extended_errcode (sqlite3 * db)
Definition at line 1268 of file main.c.
References sqlite3::errCode, sqlite3::mallocFailed, sqlite3SafetyCheckSickOrOk(), SQLITE_MISUSE, and SQLITE_NOMEM.
IMPORT_C int sqlite3_extended_result_codes (sqlite3 * , int onoff)
Definition at line 1993 of file main.c.
References sqlite3::errMask, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and SQLITE_OK.
int sqlite3_file_control (sqlite3 * , const char * zDbName, int op, void *)
Definition at line 2003 of file main.c.
References sqlite3::aDb, sqlite3::mutex, sqlite3::nDb, Db::pBt, sqlite3_file::pMethods, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3BtreeEnter, sqlite3BtreeLeave, sqlite3BtreePager(), sqlite3OsFileControl(), sqlite3PagerFile(), SQLITE_ERROR, and Db::zName.
Referenced by sqlite3Pragma().
int sqlite3_finalize (sqlite3_stmt * pStmt)
Definition at line 201 of file vdbeapi.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeFinalize(), SQLITE_OK, and stmtLruRemove.
Referenced by DbObjCmd(), destroy_sql_statements(), do_meta_command(), dump_callback(), execExecSql(), execSql(), flushStmtCache(), fulltext_vtab_destroy(), fulltextClose(), fulltextFilter(), FUNC(), leavesReaderDestroy(), run_table_dump_query(), sql_step_statement(), sqlite3_blob_close(), sqlite3_blob_open(), sqlite3_declare_vtab(), sqlite3_exec(), and sqlite3Prepare().
IMPORT_C void sqlite3_free (void *)
Definition at line 516 of file malloc.c.
References mem0, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3GlobalConfig, sqlite3MallocSize(), sqlite3StatusAdd(), and SQLITE_STATUS_MEMORY_USED.
Referenced by balance_shallower(), bestVirtualIndex(), clearTableSpec(), constructVtab(), dataBufferDestroy(), DbMain(), DbObjCmd(), dlcDelete(), do_meta_command(), dump_callback(), freeStringArray(), fts2HashFree(), fts3HashFree(), fulltext_vtab_destroy(), fulltextClose(), fulltextFilter(), fulltextRename(), fulltextSchema(), groupConcatFinalize(), hashDestroy(), hexFunc(), interiorWriterDestroy(), invalidateOverflowCache(), loadExt(), loadSegmentLeavesInt(), lowerFunc(), memjrnlTruncate(), openDatabase(), optimizeFunc(), pager_delmaster(), pcacheFree(), pcacheResizeHash(), porterClose(), porterDestroy(), process_input(), queryClear(), quoteFunc(), randomBlob(), rehash(), releaseLockInfo(), releaseOpenCnt(), removeElementGivenHash(), replaceFunc(), run_schema_dump_query(), saveCursorPosition(), scalarFunc(), schemaIsValid(), setupLookaside(), simpleClose(), simpleCreate(), simpleDestroy(), snippetClear(), snippetText(), sql_exec(), sql_get_statement(), sql_prepare(), sqlite3_close(), sqlite3_free_table(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3_reset_auto_extension(), sqlite3AutoLoadExtensions(), sqlite3BitvecBuiltinTest(), sqlite3BitvecDestroy(), sqlite3BtreeClearCursor(), sqlite3BtreeClose(), sqlite3BtreeIntegrityCheck(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeOpen(), sqlite3BtreeRestoreCursorPosition(), sqlite3DbFree(), sqlite3Fts2Init(), sqlite3Fts2InitHashTable(), sqlite3Fts3Init(), sqlite3Fts3InitHashTable(), sqlite3HashClear(), sqlite3HashInsert(), sqlite3InitOne(), sqlite3InvalidFunction(), sqlite3LoadExtension(), sqlite3OsCloseFree(), sqlite3OsOpenMalloc(), sqlite3PagerClose(), sqlite3PagerOpen(), sqlite3PcacheClose(), sqlite3Pragma(), sqlite3Realloc(), sqlite3RunParser(), sqlite3VdbeExec(), sqlite3VXPrintf(), tokenizeString(), trimFunc(), unixUnlock(), unlockAllTables(), upperFunc(), writeZeroSegment(), and xFree().
void sqlite3_free_table (char ** result)
Definition at line 188 of file table.c.
References sqlite3_free(), and SQLITE_PTR_TO_INT.
Referenced by do_meta_command(), and sqlite3_get_table().
int sqlite3_get_autocommit (sqlite3 *)
Definition at line 1832 of file main.c.
References sqlite3::autoCommit.
Referenced by DbObjCmd().
void* sqlite3_get_auxdata (sqlite3_context * , int N)
Definition at line 646 of file vdbeapi.c.
References VdbeFunc::apAux, Mem::db, sqlite3::mutex, VdbeFunc::nAux, VdbeFunc::AuxData::pAux, sqlite3_context::pVdbeFunc, sqlite3_context::s, and sqlite3_mutex_held.
Referenced by icuRegexpFunc().
int sqlite3_get_table (sqlite3 * db, const char * zSql, char *** pazResult, int * pnRow, int * pnColumn, char ** pzErrmsg)
Definition at line 121 of file table.c.
References TabResult::azResult, sqlite3::errCode, TabResult::nAlloc, TabResult::nColumn, TabResult::nData, TabResult::nResult, TabResult::nRow, TabResult::rc, sqlite3_exec(), sqlite3_free(), sqlite3_free_table(), sqlite3_get_table_cb(), sqlite3_malloc(), sqlite3_mprintf(), sqlite3_realloc(), SQLITE_ABORT, SQLITE_INT_TO_PTR, SQLITE_NOMEM, SQLITE_OK, and TabResult::zErrMsg.
Referenced by do_meta_command().
SQLITE_DEPRECATED int sqlite3_global_recover (void)
Definition at line 1818 of file main.c.
References SQLITE_OK.
int sqlite3_initialize (void)
Definition at line 90 of file main.c.
References GLOBAL, sqlite3_mutex_enter, sqlite3_mutex_free, sqlite3_mutex_leave, sqlite3_os_init(), sqlite3GlobalConfig, sqlite3GlobalFunctions, sqlite3IsNaN(), sqlite3MallocInit(), sqlite3MutexAlloc, sqlite3MutexInit, sqlite3PCacheBufferSetup(), sqlite3PcacheInitialize(), sqlite3RegisterGlobalFunctions(), SQLITE_MUTEX_RECURSIVE, SQLITE_MUTEX_STATIC_MASTER, SQLITE_NOMEM, and SQLITE_OK.
Referenced by openDatabase(), sqlite3_auto_extension(), sqlite3_complete16(), sqlite3_malloc(), sqlite3_mprintf(), sqlite3_mutex_alloc(), sqlite3_open16(), sqlite3_realloc(), sqlite3_reset_auto_extension(), sqlite3_soft_heap_limit(), sqlite3_vfs_find(), sqlite3_vfs_register(), and sqlite3_vmprintf().
void sqlite3_interrupt (sqlite3 *)
Definition at line 839 of file main.c.
References sqlite3::isInterrupted, and sqlite3::u1.
Referenced by DbObjCmd(), FUNC(), and sqlite3VdbeExec().
int sqlite3_key (sqlite3 * db, const void * pKey, int nKey)
Referenced by DbMain(), and sqlite3Pragma().
sqlite3_int64 sqlite3_last_insert_rowid (sqlite3 *)
Definition at line 513 of file main.c.
References sqlite3::lastRowid.
Referenced by block_insert(), DbObjCmd(), FUNC(), index_insert(), and last_insert_rowid().
const char* sqlite3_libversion (void)
Definition at line 36 of file main.c.
References sqlite3_version.
Referenced by DbObjCmd(), FUNC(), and main().
int sqlite3_libversion_number (void)
Definition at line 37 of file main.c.
References SQLITE_VERSION_NUMBER.
int sqlite3_limit (sqlite3 * , int id, int newVal)
Definition at line 1418 of file main.c.
References sqlite3::aLimit, and SQLITE_N_LIMIT.
int sqlite3_load_extension (sqlite3 * db, const char * zFile, const char * zProc, char ** pzErrMsg)
Definition at line 424 of file loadext.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3LoadExtension().
Referenced by do_meta_command(), and loadExt().
IMPORT_C void* sqlite3_malloc (int)
Definition at line 283 of file malloc.c.
References sqlite3_initialize(), and sqlite3Malloc().
Referenced by constructVtab(), content_select(), dataBufferInit(), dlcNew(), fillInUnixFile(), findLockInfo(), fts2HashMalloc(), fts3HashMalloc(), fulltextOpen(), icuCaseFunc16(), interiorBlockNew(), interiorWriterRootInfo(), loadSegmentLeavesInt(), memjrnlWrite(), optimizeFunc(), parseSpec(), porterCreate(), porterOpen(), queryAdd(), simpleCreate(), simpleOpen(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3BitvecBuiltinTest(), sqlite3Fts2Init(), sqlite3Fts3Init(), string_dup_n(), string_format(), tokenizeString(), and writeZeroSegment().
SQLITE_DEPRECATED int sqlite3_memory_alarm (void(*)(void *, sqlite3_int64, int) , void * , sqlite3_int64)
sqlite3_int64 sqlite3_memory_highwater (int resetFlag)
Definition at line 175 of file malloc.c.
References sqlite3_status(), and SQLITE_STATUS_MEMORY_USED.
sqlite3_int64 sqlite3_memory_used (void)
Definition at line 162 of file malloc.c.
References sqlite3_status(), and SQLITE_STATUS_MEMORY_USED.
Referenced by sqlite3_soft_heap_limit().
char* sqlite3_mprintf (const char * , ...)
Definition at line 878 of file printf.c.
References sqlite3_initialize(), and sqlite3_vmprintf().
Referenced by constructVtab(), DbMain(), DbObjCmd(), do_meta_command(), dump_callback(), fulltextFilter(), fulltextRename(), fulltextSchema(), parseSpec(), scalarFunc(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3Fts2InitHashTable(), sqlite3Fts3InitHashTable(), and sqlite3LoadExtension().
sqlite3_mutex* sqlite3_mutex_alloc (int)
Definition at line 77 of file mutex.c.
References sqlite3_initialize(), and sqlite3GlobalConfig.
void sqlite3_mutex_enter (sqlite3_mutex *)
Definition at line 104 of file mutex.c.
References sqlite3GlobalConfig.
void sqlite3_mutex_free (sqlite3_mutex *)
Definition at line 94 of file mutex.c.
References sqlite3GlobalConfig.
int sqlite3_mutex_held (sqlite3_mutex *)
void sqlite3_mutex_leave (sqlite3_mutex *)
Definition at line 128 of file mutex.c.
References sqlite3GlobalConfig.
int sqlite3_mutex_notheld (sqlite3_mutex *)
int sqlite3_mutex_try (sqlite3_mutex *)
Definition at line 114 of file mutex.c.
References sqlite3GlobalConfig, and SQLITE_OK.
sqlite3_stmt* sqlite3_next_stmt (sqlite3 * pDb, sqlite3_stmt * pStmt)
Definition at line 1288 of file vdbeapi.c.
References sqlite3::mutex, sqlite3::pVdbe, sqlite3_mutex_enter, and sqlite3_mutex_leave.
IMPORT_C int sqlite3_open (const char * filename, sqlite3 ** ppDb)
Definition at line 1657 of file main.c.
References openDatabase(), SQLITE_OPEN_CREATE, and SQLITE_OPEN_READWRITE.
Referenced by create_database(), log_db_open_session(), open_config_db_session(), and open_db().
int sqlite3_open16 (const void * filename, sqlite3 ** ppDb)
Definition at line 1677 of file main.c.
References DB_SchemaLoaded, DbHasProperty, ENC, openDatabase(), sqlite3_initialize(), sqlite3ApiExit(), sqlite3ValueFree(), sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3ValueText(), SQLITE_NOMEM, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_READWRITE, SQLITE_STATIC, SQLITE_UTF16NATIVE, and SQLITE_UTF8.
int sqlite3_open_v2 (const char * filename, sqlite3 ** ppDb, int flags, const char * zVfs)
Definition at line 1664 of file main.c.
References openDatabase().
Referenced by DbMain().
int sqlite3_os_end (void)
Definition at line 952 of file os_symbian.c.
References SQLITE_OK.
Referenced by sqlite3_shutdown().
int sqlite3_os_init (void)
Definition at line 917 of file os_symbian.c.
References LOCKING_STYLE_AFP, LOCKING_STYLE_DOTFILE, LOCKING_STYLE_FLOCK, LOCKING_STYLE_NONE, LOCKING_STYLE_POSIX, sqlite3_vfs_register(), SQLITE_OK, and UNIXVFS.
Referenced by sqlite3_initialize().
SQLITE_EXPERIMENTAL int sqlite3_overload_function (sqlite3 * , const char * zFuncName, int nArg)
Definition at line 990 of file main.c.
References sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3CreateFunc(), sqlite3FindFunction(), sqlite3InvalidFunction(), sqlite3Strlen(), SQLITE_OK, and SQLITE_UTF8.
Referenced by sqlite3Fts1Init(), sqlite3Fts2Init(), sqlite3Fts3Init(), and sqlite3RegisterBuiltinFunctions().
int sqlite3_prepare (sqlite3 * db, const char * zSql, int nByte, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 708 of file prepare.c.
References sqlite3LockAndPrepare(), and SQLITE_OK.
Referenced by DbObjCmd(), do_meta_command(), dump_callback(), execExecSql(), execSql(), FUNC(), run_table_dump_query(), sql_prepare(), and sqlite3_exec().
int sqlite3_prepare16 (sqlite3 * db, const void * zSql, int nByte, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 786 of file prepare.c.
References sqlite3Prepare16(), and SQLITE_OK.
int sqlite3_prepare16_v2 (sqlite3 * db, const void * zSql, int nByte, sqlite3_stmt ** ppStmt, const void ** pzTail)
Definition at line 798 of file prepare.c.
References sqlite3Prepare16(), and SQLITE_OK.
int sqlite3_prepare_v2 (sqlite3 * db, const char * zSql, int nByte, sqlite3_stmt ** ppStmt, const char ** pzTail)
Definition at line 720 of file prepare.c.
References sqlite3LockAndPrepare(), and SQLITE_OK.
Referenced by DbObjCmd(), and sql_prepare().
SQLITE_EXPERIMENTAL void* sqlite3_profile (sqlite3 * , void(*)(void *, const char *, sqlite3_uint64) xProfile, void *)
void sqlite3_progress_handler (sqlite3 * , int , int(*)(void *) , void *)
Definition at line 801 of file main.c.
References sqlite3::mutex, sqlite3::nProgressOps, sqlite3::pProgressArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xProgress.
Referenced by DbObjCmd(), and FUNC().
void sqlite3_randomness (int N, void * P)
Definition at line 107 of file random.c.
References randomByte(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, and SQLITE_MUTEX_STATIC_PRNG.
Referenced by getTempname(), randomBlob(), randomFunc(), sqlite3BitvecBuiltinTest(), sqlite3VdbeExec(), vdbeCommit(), and writeJournalHdr().
void* sqlite3_realloc (void * , int)
Definition at line 589 of file malloc.c.
References sqlite3_initialize(), and sqlite3Realloc().
Referenced by dataBufferExpand(), porterNext(), queryAdd(), replaceFunc(), simpleNext(), snippetAppendMatch(), sqlite3_auto_extension(), sqlite3_get_table(), sqlite3_get_table_cb(), sqlite3DbRealloc(), sqlite3VtabMakeWritable(), and unixClose().
int sqlite3_rekey (sqlite3 * db, const void * pKey, int nKey)
Referenced by DbObjCmd().
int sqlite3_release_memory (int)
Definition at line 63 of file malloc.c.
References SQLITE_OK.
Referenced by softHeapLimitEnforcer(), and sqlite3_soft_heap_limit().
int sqlite3_reset (sqlite3_stmt * pStmt)
Definition at line 226 of file vdbeapi.c.
References Vdbe::db, sqlite3::errMask, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeMakeReady(), sqlite3VdbeReset(), SQLITE_OK, and stmtLruAdd.
Referenced by db_get(), db_set(), DbObjCmd(), do_meta_command(), fulltextFilter(), fulltextNext(), FUNC(), leavesReaderReset(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), sql_get_leaf_statement(), sql_get_statement(), and sqlite3_step().
void sqlite3_reset_auto_extension (void)
Definition at line 550 of file loadext.c.
References sqlite3_free(), sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, wsdAutoext, and wsdAutoextInit.
void sqlite3_result_blob (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 314 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetStr().
Referenced by fulltextColumn(), FUNC(), randomBlob(), scalarFunc(), substrFunc(), and tclSqlFunc().
void sqlite3_result_double (sqlite3_context * , double)
Definition at line 324 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetDouble().
Referenced by absFunc(), avgFinalize(), FUNC(), juliandayFunc(), roundFunc(), sumFinalize(), tclSqlFunc(), and totalFinalize().
void sqlite3_result_error (sqlite3_context * , const char * , int)
Definition at line 328 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), SQLITE_ERROR, SQLITE_TRANSIENT, and SQLITE_UTF8.
Referenced by absFunc(), attachFunc(), detachFunc(), FUNC(), func_callback_wrapper(), icuFunctionError(), icuLikeFunc(), icuLoadCollation(), likeFunc(), loadExt(), optimizeFunc(), scalarFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3InvalidFunction(), sumFinalize(), and tclSqlFunc().
void sqlite3_result_error16 (sqlite3_context * , const void * , int)
Definition at line 334 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), SQLITE_ERROR, SQLITE_TRANSIENT, and SQLITE_UTF16NATIVE.
void sqlite3_result_error_code (sqlite3_context * , int)
Definition at line 398 of file vdbeapi.c.
References sqlite3_context::isError.
Referenced by attachFunc().
void sqlite3_result_error_nomem (sqlite3_context *)
Definition at line 411 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetNull(), and SQLITE_NOMEM.
Referenced by contextMalloc(), groupConcatFinalize(), replaceFunc(), and strftimeFunc().
void sqlite3_result_error_toobig (sqlite3_context *)
Definition at line 403 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), SQLITE_STATIC, SQLITE_TOOBIG, and SQLITE_UTF8.
Referenced by contextMalloc(), groupConcatFinalize(), replaceFunc(), strftimeFunc(), and zeroblobFunc().
void sqlite3_result_int (sqlite3_context * , int)
Definition at line 340 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetInt64().
Referenced by changes(), FUNC(), icuLikeFunc(), icuRegexpFunc(), lengthFunc(), likeFunc(), tclSqlFunc(), and total_changes().
void sqlite3_result_int64 (sqlite3_context * , sqlite3_int64)
Definition at line 344 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetInt64().
Referenced by absFunc(), countFinalize(), last_insert_rowid(), randomFunc(), sumFinalize(), and tclSqlFunc().
void sqlite3_result_null (sqlite3_context *)
Definition at line 348 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetNull().
Referenced by absFunc(), FUNC(), and lengthFunc().
void sqlite3_result_text (sqlite3_context * , const char * , int , void(*)(void *))
Definition at line 352 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF8.
Referenced by dateFunc(), datetimeFunc(), FUNC(), groupConcatFinalize(), hexFunc(), lowerFunc(), optimizeFunc(), quoteFunc(), renameTableFunc(), renameTriggerFunc(), replaceFunc(), shellstaticFunc(), snippetFunc(), snippetOffsetsFunc(), strftimeFunc(), substrFunc(), tclSqlFunc(), timeFunc(), trimFunc(), typeofFunc(), upperFunc(), and versionFunc().
void sqlite3_result_text16 (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 362 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF16NATIVE.
Referenced by icuCaseFunc16().
void sqlite3_result_text16be (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 371 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF16BE.
void sqlite3_result_text16le (sqlite3_context * , const void * , int , void(*)(void *))
Definition at line 380 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF16LE.
void sqlite3_result_value (sqlite3_context * , sqlite3_value *)
Definition at line 390 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemCopy().
Referenced by fulltextColumn(), FUNC(), ifnullFunc(), minMaxFinalize(), minmaxFunc(), nullifFunc(), and quoteFunc().
void sqlite3_result_zeroblob (sqlite3_context * , int n)
Definition at line 394 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetZeroBlob().
Referenced by zeroblobFunc().
void* sqlite3_rollback_hook (sqlite3 * , void(*)(void *) , void *)
Definition at line 1090 of file main.c.
References sqlite3::mutex, sqlite3::pRollbackArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xRollbackCallback.
Referenced by DbObjCmd().
int sqlite3_set_authorizer (sqlite3 * , int(*)(void *, int, const char *, const char *, const char *, const char *) xAuth, void * pUserData)
Definition at line 72 of file auth.c.
References sqlite3::mutex, sqlite3::pAuthArg, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ExpirePreparedStatements(), SQLITE_OK, and sqlite3::xAuth.
Referenced by DbObjCmd(), and FUNC().
void sqlite3_set_auxdata (sqlite3_context * , int N, void * , void(*)(void *))
Definition at line 662 of file vdbeapi.c.
References VdbeFunc::apAux, Mem::db, sqlite3::mutex, VdbeFunc::nAux, sqlite3_context::pFunc, VdbeFunc::pFunc, sqlite3_context::pVdbeFunc, sqlite3_context::s, sqlite3_mutex_held, sqlite3DbRealloc(), and VdbeFunc::AuxData::xDelete.
Referenced by icuRegexpFunc().
int sqlite3_shutdown (void)
Definition at line 213 of file main.c.
References sqlite3_os_end(), sqlite3GlobalConfig, sqlite3MallocEnd(), sqlite3MutexEnd, sqlite3PcacheShutdown(), and SQLITE_OK.
int sqlite3_sleep (int)
Definition at line 1977 of file main.c.
References sqlite3_vfs_find(), and sqlite3OsSleep().
char* sqlite3_snprintf (int , char * , const char * , ...)
Definition at line 896 of file printf.c.
References sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), and StrAccum::useMalloc.
Referenced by attachFunc(), checkTreePage(), createIncrblobChannel(), createTableStmt(), dateFunc(), datetimeFunc(), DbBusyHandler(), DbObjCmd(), DbProfileHandler(), detachFunc(), displayP4(), do_meta_command(), fillInUnixFile(), find_home_dir(), getTempname(), icuFunctionError(), main(), main_init(), openDirectory(), optimizeFunc(), process_input(), process_sqliterc(), roundFunc(), run_schema_dump_query(), snippetOffsetText(), sqlite3_blob_open(), sqlite3CreateIndex(), sqlite3GenerateConstraintChecks(), sqlite3LoadExtension(), sqlite3VdbeList(), sqlite3VdbeMemStringify(), strftimeFunc(), timeFunc(), unixDlError(), and unixFullPathname().
void sqlite3_soft_heap_limit (int)
Definition at line 38 of file malloc.c.
References softHeapLimitEnforcer(), sqlite3_initialize(), sqlite3_memory_used(), sqlite3_release_memory(), and sqlite3MemoryAlarm().
const char* sqlite3_sql (sqlite3_stmt * pStmt)
Definition at line 65 of file vdbeaux.c.
Referenced by DbObjCmd(), and sqlite3Reprepare().
SQLITE_EXPERIMENTAL int sqlite3_status (int op, int * pCurrent, int * pHighwater, int resetFlag)
Definition at line 85 of file status.c.
References ArraySize, SQLITE_MISUSE, SQLITE_OK, wsdStat, and wsdStatInit.
Referenced by sqlite3_memory_highwater(), and sqlite3_memory_used().
int sqlite3_step (sqlite3_stmt *)
Definition at line 538 of file vdbeapi.c.
References Vdbe::db, db, Vdbe::expired, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, Vdbe::rc, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_reset(), sqlite3_value_text(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DbStrDup(), sqlite3Step(), SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_SCHEMA, vdbeReprepare, Vdbe::zErrMsg, and Vdbe::zSql.
Referenced by block_insert(), content_exists(), content_select(), db_get(), db_set(), DbObjCmd(), do_meta_command(), dump_callback(), execExecSql(), execSql(), fulltextNext(), FUNC(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), optimizeFunc(), run_table_dump_query(), segdir_count(), segdir_max_index(), segdir_span(), sql_single_step(), sql_step_statement(), sqlite3_blob_open(), sqlite3_exec(), term_select(), and termSelect().
SQLITE_EXPERIMENTAL int sqlite3_stmt_status (sqlite3_stmt * , int op, int resetFlg)
Definition at line 1303 of file vdbeapi.c.
References Vdbe::aCounter.
Referenced by DbObjCmd().
int sqlite3_table_column_metadata (sqlite3 * db, const char * zDbName, const char * zTableName, const char * zColumnName, char const ** pzDataType, char const ** pzCollSeq, int * pNotNull, int * pPrimaryKey, int * pAutoinc)
int sqlite3_test_control (int op, ...)
Definition at line 2037 of file main.c.
References sqlite3BenignMallocHooks(), sqlite3BitvecBuiltinTest(), sqlite3PrngResetState(), sqlite3PrngRestoreState(), sqlite3PrngSaveState(), SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS, SQLITE_TESTCTRL_BITVEC_TEST, SQLITE_TESTCTRL_PRNG_RESET, SQLITE_TESTCTRL_PRNG_RESTORE, and SQLITE_TESTCTRL_PRNG_SAVE.
SQLITE_DEPRECATED void sqlite3_thread_cleanup (void)
Definition at line 1855 of file main.c.
int sqlite3_threadsafe (void)
Definition at line 38 of file main.c.
References SQLITE_THREADSAFE.
int sqlite3_total_changes (sqlite3 *)
Definition at line 527 of file main.c.
References sqlite3::nTotalChange.
Referenced by DbObjCmd(), FUNC(), and total_changes().
SQLITE_EXPERIMENTAL void* sqlite3_trace (sqlite3 * , void(*)(void *, const char *) xTrace, void *)
Definition at line 1016 of file main.c.
References sqlite3::mutex, sqlite3::pTraceArg, sqlite3_mutex_enter, sqlite3_mutex_leave, and sqlite3::xTrace.
Referenced by DbObjCmd(), and FUNC().
SQLITE_DEPRECATED int sqlite3_transfer_bindings (sqlite3_stmt * , sqlite3_stmt *)
Definition at line 1267 of file vdbeapi.c.
References sqlite3TransferBindings().
void* sqlite3_update_hook (sqlite3 * , void(*)(void *, int, char const *, char const *, sqlite3_int64) , void *)
void* sqlite3_user_data (sqlite3_context *)
Definition at line 580 of file vdbeapi.c.
References sqlite3_context::pFunc, and FuncDef::pUserData.
Referenced by func_callback_wrapper(), icuCaseFunc16(), icuLoadCollation(), likeFunc(), minmaxFunc(), minmaxStep(), scalarFunc(), tclSqlFunc(), and trimFunc().
const void* sqlite3_value_blob (sqlite3_value *)
Definition at line 266 of file vdbeapi.c.
References Mem::flags, MEM_Blob, MEM_Str, sqlite3_value_text(), sqlite3VdbeMemExpandBlob(), and Mem::z.
Referenced by attachFunc(), FUNC(), hexFunc(), optimizeFunc(), quoteFunc(), scalarFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_column_blob(), substrFunc(), and tclSqlFunc().
int sqlite3_value_bytes (sqlite3_value *)
Definition at line 277 of file vdbeapi.c.
References sqlite3ValueBytes(), and SQLITE_UTF8.
Referenced by attachFunc(), FUNC(), groupConcatStep(), hexFunc(), icuLikeFunc(), lengthFunc(), likeFunc(), lowerFunc(), optimizeFunc(), quoteFunc(), replaceFunc(), scalarFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_column_bytes(), substrFunc(), tclSqlFunc(), trimFunc(), and upperFunc().
int sqlite3_value_bytes16 (sqlite3_value *)
Definition at line 280 of file vdbeapi.c.
References sqlite3ValueBytes(), and SQLITE_UTF16NATIVE.
Referenced by icuCaseFunc16(), and sqlite3_column_bytes16().
double sqlite3_value_double (sqlite3_value *)
Definition at line 283 of file vdbeapi.c.
References sqlite3VdbeRealValue().
Referenced by absFunc(), FUNC(), isDate(), roundFunc(), sqlite3_column_double(), sumStep(), and tclSqlFunc().
int sqlite3_value_int (sqlite3_value *)
Definition at line 286 of file vdbeapi.c.
References sqlite3VdbeIntValue().
Referenced by FUNC(), randomBlob(), roundFunc(), sqlite3_column_int(), and substrFunc().
sqlite3_int64 sqlite3_value_int64 (sqlite3_value *)
Definition at line 289 of file vdbeapi.c.
References sqlite3VdbeIntValue().
Referenced by absFunc(), fulltextFilter(), fulltextUpdate(), sqlite3_column_int64(), sumStep(), tclSqlFunc(), and zeroblobFunc().
int sqlite3_value_numeric_type (sqlite3_value *)
Definition at line 326 of file vdbe.c.
References applyNumericAffinity(), storeTypeInfo, and Mem::type.
Referenced by sumStep().
const unsigned char* sqlite3_value_text (sqlite3_value *)
Definition at line 292 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF8.
Referenced by attachFunc(), detachFunc(), fulltextFilter(), FUNC(), groupConcatStep(), icuCaseFunc16(), icuLikeFunc(), icuLoadCollation(), insertTerms(), isDate(), lengthFunc(), likeFunc(), loadExt(), lowerFunc(), quoteFunc(), renameTableFunc(), renameTriggerFunc(), replaceFunc(), scalarFunc(), snippetFunc(), sqlite3_column_decltype(), sqlite3_column_name(), sqlite3_column_text(), sqlite3_errmsg(), sqlite3_step(), sqlite3_value_blob(), sqlite3VdbeExec(), strftimeFunc(), substrFunc(), tclSqlFunc(), trimFunc(), and upperFunc().
const void* sqlite3_value_text16 (sqlite3_value *)
Definition at line 296 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF16NATIVE.
Referenced by icuCaseFunc16(), icuRegexpFunc(), sqlite3_column_decltype16(), sqlite3_column_name16(), sqlite3_column_text16(), and sqlite3_errmsg16().
const void* sqlite3_value_text16be (sqlite3_value *)
Definition at line 299 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF16BE.
const void* sqlite3_value_text16le (sqlite3_value *)
Definition at line 302 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF16LE.
int sqlite3_value_type (sqlite3_value *)
Definition at line 306 of file vdbeapi.c.
References Mem::type.
Referenced by absFunc(), attachFunc(), countStep(), fulltextUpdate(), FUNC(), groupConcatStep(), ifnullFunc(), isDate(), lengthFunc(), lowerFunc(), minmaxFunc(), minmaxStep(), optimizeFunc(), quoteFunc(), roundFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_column_type(), substrFunc(), tclSqlFunc(), trimFunc(), typeofFunc(), and upperFunc().
sqlite3_vfs* sqlite3_vfs_find (const char * zVfsName)
Definition at line 200 of file os.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, vfsList, and sqlite3_vfs::zName.
Referenced by openDatabase(), randomByte(), and sqlite3_sleep().
int sqlite3_vfs_register (sqlite3_vfs * , int makeDflt)
Definition at line 246 of file os.c.
References sqlite3_vfs::pNext, sqlite3_initialize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, vfsList, and vfsUnlink().
Referenced by sqlite3_os_init().
int sqlite3_vfs_unregister (sqlite3_vfs *)
Definition at line 270 of file os.c.
References sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3MutexAlloc, SQLITE_MUTEX_STATIC_MASTER, SQLITE_OK, and vfsUnlink().
char* sqlite3_vmprintf (const char * , va_list)
Definition at line 861 of file printf.c.
References sqlite3_initialize(), sqlite3StrAccumFinish(), sqlite3StrAccumInit(), sqlite3VXPrintf(), SQLITE_MAX_LENGTH, and SQLITE_PRINT_BUF_SIZE.
Referenced by sqlite3_mprintf().
Variable Documentation
SQLITE_EXTERN char* sqlite3_temp_directory
Definition at line 4924 of file sqlite3.h.
SQLITE_EXTERN const char sqlite3_version[]
Definition at line 152 of file sqlite3.h.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1