ContextLogger2 Logger Daemon Internals: status.c File Reference
status.c File Reference
Classes
struct sqlite3StatType
Defines
#define wsdStatInit
#define wsdStat sqlite3Stat
Typedefs
typedef struct sqlite3StatType sqlite3StatType
Functions
int sqlite3StatusValue (int op)
void sqlite3StatusAdd (int op, int N)
void sqlite3StatusSet (int op, int X)
int sqlite3_status (int op, int *pCurrent, int *pHighwater, int resetFlag)
int sqlite3_db_status (sqlite3 *db, int op, int *pCurrent, int *pHighwater, int resetFlag)
Variables
static SQLITE_WSD struct
sqlite3StatType sqlite3Stat
Define Documentation
#define wsdStat sqlite3Stat
Definition at line 41 of file status.c.
Referenced by sqlite3_status(), sqlite3StatusAdd(), sqlite3StatusSet(), and sqlite3StatusValue().
#define wsdStatInit
Definition at line 40 of file status.c.
Referenced by sqlite3_status(), sqlite3StatusAdd(), sqlite3StatusSet(), and sqlite3StatusValue().
Typedef Documentation
typedef struct sqlite3StatType sqlite3StatType
Definition at line 23 of file status.c.
Function Documentation
int sqlite3_db_status (sqlite3 * db, int op, int * pCurrent, int * pHighwater, int resetFlag)
Definition at line 101 of file status.c.
References sqlite3::lookaside, Lookaside::mxOut, Lookaside::nOut, SQLITE_DBSTATUS_LOOKASIDE_USED, SQLITE_ERROR, and SQLITE_OK.
int sqlite3_status (int op, int * pCurrent, int * pHighwater, int resetFlag)
Definition at line 85 of file status.c.
References ArraySize, SQLITE_MISUSE, SQLITE_OK, wsdStat, and wsdStatInit.
Referenced by sqlite3_memory_highwater(), and sqlite3_memory_used().
void sqlite3StatusAdd (int op, int N)
Definition at line 57 of file status.c.
References ArraySize, wsdStat, and wsdStatInit.
Referenced by mallocWithAlarm(), pcacheFree(), pcacheMalloc(), sqlite3_free(), sqlite3Realloc(), sqlite3ScratchFree(), and sqlite3ScratchMalloc().
void sqlite3StatusSet (int op, int X)
Definition at line 69 of file status.c.
References ArraySize, wsdStat, and wsdStatInit.
Referenced by mallocWithAlarm(), pcacheMalloc(), sqlite3Realloc(), sqlite3RunParser(), and sqlite3ScratchMalloc().
int sqlite3StatusValue (int op)
Definition at line 47 of file status.c.
References ArraySize, wsdStat, and wsdStatInit.
Referenced by mallocWithAlarm(), sqlite3MallocAlarm(), and sqlite3Realloc().
Variable Documentation
SQLITE_WSD struct sqlite3StatType sqlite3Stat [static]
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1