ContextLogger2 Logger Daemon Internals: sqlite3_tokenizer_module Struct Reference
sqlite3_tokenizer_module Struct Reference
#include <fts1_tokenizer.h>
Public Attributes
int iVersion
int(* xCreate)(int argc, const char *const *argv, sqlite3_tokenizer **ppTokenizer)
int(* xDestroy)(sqlite3_tokenizer *pTokenizer)
int(* xOpen)(sqlite3_tokenizer *pTokenizer, const char *pInput, int nBytes, sqlite3_tokenizer_cursor **ppCursor)
int(* xClose)(sqlite3_tokenizer_cursor *pCursor)
int(* xNext)(sqlite3_tokenizer_cursor *pCursor, const char **ppToken, int *pnBytes, int *piStartOffset, int *piEndOffset, int *piPosition)
Detailed Description
Definition at line 36 of file fts1_tokenizer.h.
Member Data Documentation
int sqlite3_tokenizer_module::iVersion
Definition at line 37 of file fts1_tokenizer.h.
int(* sqlite3_tokenizer_module::xClose)(sqlite3_tokenizer_cursor *pCursor) (sqlite3_tokenizer_cursor * pCursor)
Referenced by buildTerms(), snippetOffsetsOfColumn(), and tokenizeSegment().
int(* sqlite3_tokenizer_module::xCreate)(int argc, const char *const *argv, sqlite3_tokenizer **ppTokenizer) (int argc, const char *const * argv, sqlite3_tokenizer ** ppTokenizer)
Referenced by constructVtab().
int(* sqlite3_tokenizer_module::xDestroy)(sqlite3_tokenizer *pTokenizer) (sqlite3_tokenizer * pTokenizer)
Referenced by fulltext_vtab_destroy().
int(* sqlite3_tokenizer_module::xNext)(sqlite3_tokenizer_cursor *pCursor, const char **ppToken, int *pnBytes, int *piStartOffset, int *piEndOffset, int *piPosition) (sqlite3_tokenizer_cursor * pCursor, const char ** ppToken, int * pnBytes, int * piStartOffset, int * piEndOffset, int * piPosition)
Referenced by buildTerms(), snippetOffsetsOfColumn(), and tokenizeSegment().
int(* sqlite3_tokenizer_module::xOpen)(sqlite3_tokenizer *pTokenizer, const char *pInput, int nBytes, sqlite3_tokenizer_cursor **ppCursor) (sqlite3_tokenizer * pTokenizer, const char * pInput, int nBytes, sqlite3_tokenizer_cursor ** ppCursor)
Referenced by buildTerms(), snippetOffsetsOfColumn(), and tokenizeSegment().
The documentation for this struct was generated from the following files:
fts1_tokenizer.h
fts2_tokenizer.h
fts3_tokenizer.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1