ContextLogger2 Logger Daemon Internals: sqlite3_mutex_methods Struct Reference
sqlite3_mutex_methods Struct Reference
#include <sqlite3.h>
Public Attributes
int(* xMutexInit)(void)
int(* xMutexEnd)(void)
sqlite3_mutex *(* xMutexAlloc)(int)
void(* xMutexFree)(sqlite3_mutex *)
void(* xMutexEnter)(sqlite3_mutex *)
int(* xMutexTry)(sqlite3_mutex *)
void(* xMutexLeave)(sqlite3_mutex *)
int(* xMutexHeld)(sqlite3_mutex *)
int(* xMutexNotheld)(sqlite3_mutex *)
Detailed Description
Definition at line 6227 of file sqlite3.h.
Member Data Documentation
sqlite3_mutex*(* sqlite3_mutex_methods::xMutexAlloc)(int)
Referenced by sqlite3MutexInit().
int(* sqlite3_mutex_methods::xMutexEnd)(void)
void(* sqlite3_mutex_methods::xMutexEnter)(sqlite3_mutex *)
Referenced by sqlite3MutexInit().
void(* sqlite3_mutex_methods::xMutexFree)(sqlite3_mutex *)
int(* sqlite3_mutex_methods::xMutexHeld)(sqlite3_mutex *)
int(* sqlite3_mutex_methods::xMutexInit)(void)
Referenced by sqlite3MutexInit().
void(* sqlite3_mutex_methods::xMutexLeave)(sqlite3_mutex *)
Referenced by sqlite3MutexInit().
int(* sqlite3_mutex_methods::xMutexNotheld)(sqlite3_mutex *)
int(* sqlite3_mutex_methods::xMutexTry)(sqlite3_mutex *)
The documentation for this struct was generated from the following file:
sqlite3.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1