ContextLogger2 Logger Daemon Internals: sqlite3_vfs Struct Reference
sqlite3_vfs Struct Reference
#include <sqlite3.h>
Public Attributes
int iVersion
int szOsFile
int mxPathname
sqlite3_vfs * pNext
const char * zName
void * pAppData
int(* xOpen)(sqlite3_vfs *, const char *zName, sqlite3_file *, int flags, int *pOutFlags)
int(* xDelete)(sqlite3_vfs *, const char *zName, int syncDir)
int(* xAccess)(sqlite3_vfs *, const char *zName, int flags, int *pResOut)
int(* xFullPathname)(sqlite3_vfs *, const char *zName, int nOut, char *zOut)
void *(* xDlOpen)(sqlite3_vfs *, const char *zFilename)
void(* xDlError)(sqlite3_vfs *, int nByte, char *zErrMsg)
void *(* xDlSym)(sqlite3_vfs *, void *, const char *zSymbol)
void(* xDlClose)(sqlite3_vfs *, void *)
int(* xRandomness)(sqlite3_vfs *, int nByte, char *zOut)
int(* xSleep)(sqlite3_vfs *, int microseconds)
int(* xCurrentTime)(sqlite3_vfs *, double *)
int(* xGetLastError)(sqlite3_vfs *, int, char *)
Detailed Description
Definition at line 870 of file sqlite3.h.
Member Data Documentation
int sqlite3_vfs::iVersion
Definition at line 871 of file sqlite3.h.
int sqlite3_vfs::mxPathname
Definition at line 873 of file sqlite3.h.
Referenced by pager_delmaster(), pager_playback(), sqlite3BtreeOpen(), sqlite3PagerOpen(), and unixFullPathname().
void* sqlite3_vfs::pAppData
Definition at line 876 of file sqlite3.h.
Referenced by detectLockingStyle().
sqlite3_vfs* sqlite3_vfs::pNext
Definition at line 874 of file sqlite3.h.
Referenced by sqlite3_vfs_find(), sqlite3_vfs_register(), and vfsUnlink().
int sqlite3_vfs::szOsFile
Definition at line 872 of file sqlite3.h.
Referenced by pager_delmaster(), sqlite3OsOpenMalloc(), and sqlite3PagerOpen().
int(* sqlite3_vfs::xAccess)(sqlite3_vfs *, const char *zName, int flags, int *pResOut)
Referenced by sqlite3OsAccess().
int(* sqlite3_vfs::xCurrentTime)(sqlite3_vfs *, double *)
Referenced by sqlite3OsCurrentTime().
int(* sqlite3_vfs::xDelete)(sqlite3_vfs *, const char *zName, int syncDir)
Referenced by sqlite3OsDelete().
void(* sqlite3_vfs::xDlClose)(sqlite3_vfs *, void *)
Referenced by sqlite3OsDlClose().
void(* sqlite3_vfs::xDlError)(sqlite3_vfs *, int nByte, char *zErrMsg)
Referenced by sqlite3OsDlError().
void*(* sqlite3_vfs::xDlOpen)(sqlite3_vfs *, const char *zFilename)
Referenced by sqlite3OsDlOpen().
void*(* sqlite3_vfs::xDlSym)(sqlite3_vfs *, void *, const char *zSymbol)
Referenced by sqlite3OsDlSym().
int(* sqlite3_vfs::xFullPathname)(sqlite3_vfs *, const char *zName, int nOut, char *zOut)
Referenced by sqlite3OsFullPathname().
int(* sqlite3_vfs::xGetLastError)(sqlite3_vfs *, int, char *)
int(* sqlite3_vfs::xOpen)(sqlite3_vfs *, const char *zName, sqlite3_file *, int flags, int *pOutFlags)
Referenced by sqlite3OsOpen().
int(* sqlite3_vfs::xRandomness)(sqlite3_vfs *, int nByte, char *zOut)
Referenced by sqlite3OsRandomness().
int(* sqlite3_vfs::xSleep)(sqlite3_vfs *, int microseconds)
Referenced by sqlite3OsSleep().
const char* sqlite3_vfs::zName
Definition at line 875 of file sqlite3.h.
Referenced by sqlite3_vfs_find().
The documentation for this struct was generated from the following file:
sqlite3.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1