ContextLogger2 Logger Daemon Internals: CollSeq Struct Reference
CollSeq Struct Reference
#include <sqliteInt.h>
Public Attributes
char * zName
u8 enc
u8 type
void * pUser
int(* xCmp)(void *, int, const void *, int, const void *)
void(* xDel)(void *)
Detailed Description
Definition at line 908 of file sqliteInt.h.
Member Data Documentation
u8 CollSeq::enc
Definition at line 910 of file sqliteInt.h.
Referenced by createCollation(), findCollSeqEntry(), and sqlite3MemCompare().
void* CollSeq::pUser
Definition at line 912 of file sqliteInt.h.
Referenced by createCollation(), and sqlite3MemCompare().
u8 CollSeq::type
Definition at line 911 of file sqliteInt.h.
Referenced by isLikeOrGlob(), and openDatabase().
int(* CollSeq::xCmp)(void *, int, const void *, int, const void *)
Referenced by createCollation(), sqlite3GetCollSeq(), sqlite3LocateCollSeq(), sqlite3MemCompare(), and synthCollSeq().
void(* CollSeq::xDel)(void *)
Referenced by createCollation(), sqlite3_close(), and synthCollSeq().
char* CollSeq::zName
Definition at line 909 of file sqliteInt.h.
Referenced by displayP4(), findCollSeqEntry(), findTerm(), isSortingIndex(), selectAddColumnTypeAndCollation(), sqlite3CheckCollSeq(), sqlite3CreateIndex(), sqlite3Pragma(), and synthCollSeq().
The documentation for this struct was generated from the following file:
sqliteInt.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1