ContextLogger2 Logger Daemon Internals: Walker Struct Reference
Walker Struct Reference
#include <sqliteInt.h>
Public Attributes
int(* xExprCallback)(Walker *, Expr *)
int(* xSelectCallback)(Walker *, Select *)
Parse * pParse
union {
NameContext * pNC
int i
} u
Detailed Description
Definition at line 1980 of file sqliteInt.h.
Member Data Documentation
int Walker::i
Definition at line 1986 of file sqliteInt.h.
Referenced by exprIsConst(), exprNodeIsConstant(), and selectNodeIsConstant().
NameContext* Walker::pNC
Definition at line 1985 of file sqliteInt.h.
Referenced by analyzeAggregate(), analyzeAggregatesInSelect(), resolveExprStep(), resolveSelectStep(), sqlite3ExprAnalyzeAggregates(), sqlite3ResolveExprNames(), and sqlite3ResolveSelectNames().
Parse* Walker::pParse
Definition at line 1983 of file sqliteInt.h.
Referenced by evalConstExpr(), resolveExprStep(), resolveSelectStep(), selectAddSubqueryTypeInfo(), selectExpander(), sqlite3ExprCodeConstants(), sqlite3ResolveExprNames(), sqlite3ResolveSelectNames(), sqlite3SelectAddTypeInfo(), and sqlite3SelectExpand().
union { ... } Walker::u
Referenced by analyzeAggregate(), analyzeAggregatesInSelect(), exprIsConst(), exprNodeIsConstant(), resolveExprStep(), resolveSelectStep(), selectNodeIsConstant(), sqlite3ExprAnalyzeAggregates(), sqlite3ResolveExprNames(), and sqlite3ResolveSelectNames().
int(* Walker::xExprCallback)(Walker *, Expr *)
Referenced by exprIsConst(), sqlite3ExprAnalyzeAggregates(), sqlite3ExprCodeConstants(), sqlite3ResolveExprNames(), sqlite3ResolveSelectNames(), sqlite3SelectAddTypeInfo(), sqlite3SelectExpand(), and sqlite3WalkExpr().
int(* Walker::xSelectCallback)(Walker *, Select *)
Referenced by exprIsConst(), sqlite3ExprAnalyzeAggregates(), sqlite3ExprCodeConstants(), sqlite3ResolveExprNames(), sqlite3ResolveSelectNames(), sqlite3SelectAddTypeInfo(), sqlite3SelectExpand(), and sqlite3WalkSelect().
The documentation for this struct was generated from the following file:
sqliteInt.h
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:04 2011 by Doxygen 1.6.1