ContextLogger2 Logger Daemon Internals: symbian_auto_ptr.hpp File Reference
symbian_auto_ptr.hpp File Reference
Classes
struct e_auto_ptr_ref< Y >
class e_auto_ptr< X >
class e_auto_ptr< HBufC16 >
class e_auto_ptr< HBufC8 >
Functions
void CloseCBaseIndirect (TAny *aPtr)
void CloseHBufC16Indirect (TAny *aPtr)
void CloseHBufC8Indirect (TAny *aPtr)
Function Documentation
void CloseCBaseIndirect (TAny * aPtr)
Definition at line 47 of file symbian_auto_ptr.cpp.
Referenced by e_auto_ptr< X >::e_auto_ptr().
void CloseHBufC16Indirect (TAny * aPtr)
Definition at line 53 of file symbian_auto_ptr.cpp.
Referenced by e_auto_ptr< HBufC16 >::e_auto_ptr().
void CloseHBufC8Indirect (TAny * aPtr)
Definition at line 59 of file symbian_auto_ptr.cpp.
Referenced by e_auto_ptr< HBufC8 >::e_auto_ptr().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1