ContextLogger2 Logger Daemon Internals: table.c File Reference
table.c File Reference
Classes
struct TabResult
Functions
static int sqlite3_get_table_cb (void *pArg, int nCol, char **argv, char **colv)
int sqlite3_get_table (sqlite3 *db, const char *zSql, char ***pazResult, int *pnRow, int *pnColumn, char **pzErrMsg)
void sqlite3_free_table (char **azResult)
Function Documentation
void sqlite3_free_table (char ** azResult)
Definition at line 188 of file table.c.
References sqlite3_free(), and SQLITE_PTR_TO_INT.
Referenced by do_meta_command(), and sqlite3_get_table().
int sqlite3_get_table (sqlite3 * db, const char * zSql, char *** pazResult, int * pnRow, int * pnColumn, char ** pzErrMsg)
Definition at line 121 of file table.c.
References TabResult::azResult, sqlite3::errCode, TabResult::nAlloc, TabResult::nColumn, TabResult::nData, TabResult::nResult, TabResult::nRow, TabResult::rc, sqlite3_exec(), sqlite3_free(), sqlite3_free_table(), sqlite3_get_table_cb(), sqlite3_malloc(), sqlite3_mprintf(), sqlite3_realloc(), SQLITE_ABORT, SQLITE_INT_TO_PTR, SQLITE_NOMEM, SQLITE_OK, and TabResult::zErrMsg.
Referenced by do_meta_command().
static int sqlite3_get_table_cb (void * pArg, int nCol, char ** argv, char ** colv) [static]
Definition at line 47 of file table.c.
References TabResult::azResult, TabResult::nAlloc, TabResult::nColumn, TabResult::nData, TabResult::nRow, TabResult::rc, sqlite3_free(), sqlite3_malloc(), sqlite3_mprintf(), sqlite3_realloc(), SQLITE_ERROR, SQLITE_NOMEM, and TabResult::zErrMsg.
Referenced by sqlite3_get_table().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1