ContextLogger2 Logger Daemon Internals: time_parser_rb.c File Reference
time_parser_rb.c File Reference
Defines
#define Check_Time(t)
Functions
static VALUE rb_parse_interval (VALUE self, VALUE s, VALUE ctx, VALUE now)
static VALUE rb_parse_moment (VALUE self, VALUE s, VALUE ctx, VALUE now)
void Init_time_parser_rb ()
Define Documentation
#define Check_Time (t)
Value:
if (!rb_obj_is_instance_of(t, rb_cTime)) { \
    rb_raise(rb_eTypeError, "%s not a Time", #t); \
  }
Definition at line 7 of file time_parser_rb.c.
Referenced by rb_parse_interval(), and rb_parse_moment().
Function Documentation
void Init_time_parser_rb ()
Definition at line 104 of file time_parser_rb.c.
References rb_parse_interval(), and rb_parse_moment().
static VALUE rb_parse_interval (VALUE self, VALUE s, VALUE ctx, VALUE now) [static]
Definition at line 21 of file time_parser_rb.c.
References Check_Time, error(), and parse_interval().
Referenced by Init_time_parser_rb().
static VALUE rb_parse_moment (VALUE self, VALUE s, VALUE ctx, VALUE now) [static]
Definition at line 62 of file time_parser_rb.c.
References Check_Time, error(), and parse_moment().
Referenced by Init_time_parser_rb().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1