ContextLogger2 Logger Daemon Internals: tokenize.c File Reference
tokenize.c File Reference
Defines
#define charMap(X) sqlite3UpperToLower[(unsigned char)X]
#define IdChar(C) (((c=C)&0x80)!=0 || (c>0x1f && sqlite3IsAsciiIdChar[c-0x20]))
Functions
int sqlite3GetToken (const unsigned char *z, int *tokenType)
int sqlite3RunParser (Parse *pParse, const char *zSql, char **pzErrMsg)
Variables
const char sqlite3IsAsciiIdChar []
Define Documentation
#define charMap (X) sqlite3UpperToLower[(unsigned char)X]
Definition at line 32 of file tokenize.c.
Referenced by keywordCode().
#define IdChar (C) (((c=C)&0x80)!=0 || (c>0x1f && sqlite3IsAsciiIdChar[c-0x20]))
Definition at line 97 of file tokenize.c.
Function Documentation
int sqlite3GetToken (const unsigned char * z, int * tokenType)
Definition at line 123 of file tokenize.c.
References IdChar, keywordCode(), TK_BITAND, TK_BITNOT, TK_BITOR, TK_BLOB, TK_COMMA, TK_CONCAT, TK_DOT, TK_EQ, TK_FLOAT, TK_GE, TK_GT, TK_ID, TK_ILLEGAL, TK_INTEGER, TK_LE, TK_LP, TK_LSHIFT, TK_LT, TK_MINUS, TK_NE, TK_PLUS, TK_REGISTER, TK_REM, TK_RP, TK_RSHIFT, TK_SEMI, TK_SLASH, TK_SPACE, TK_STAR, TK_STRING, and TK_VARIABLE.
Referenced by renameTableFunc(), renameTriggerFunc(), and sqlite3RunParser().
int sqlite3RunParser (Parse * pParse, const char * zSql, char ** pzErrMsg)
Definition at line 384 of file tokenize.c.
References Parse::aAlias, sqlite3::activeVdbeCnt, sqlite3::aLimit, Parse::apVarExpr, Parse::apVtabLock, Parse::aTableLock, Parse::db, db, Token::dyn, IN_DECLARE_VTAB, sqlite3::isInterrupted, sqlite3::mallocFailed, Token::n, Parse::nErr, Parse::nested, Parse::nTableLock, Parse::nVar, Parse::nVarExpr, Parse::nVarExprAlloc, Parse::pNewTable, Parse::pNewTrigger, Table::pNextZombie, Parse::pVdbe, Parse::pZombieTab, Parse::rc, Parse::sLastToken, sqlite3_free(), sqlite3DbFree(), sqlite3DeleteTable(), sqlite3DeleteTrigger(), sqlite3ErrStr(), sqlite3GetToken(), sqlite3Malloc(), sqlite3MPrintf(), sqlite3Parser(), sqlite3ParserAlloc(), sqlite3ParserFree(), sqlite3SetString(), sqlite3StatusSet(), sqlite3VdbeDelete(), SQLITE_DONE, SQLITE_ERROR, SQLITE_INTERRUPT, SQLITE_LIMIT_SQL_LENGTH, SQLITE_NOMEM, SQLITE_OK, SQLITE_STATUS_PARSER_STACK, SQLITE_TOOBIG, TK_ILLEGAL, TK_SEMI, TK_SPACE, sqlite3::u1, Token::z, Parse::zErrMsg, Parse::zSql, and Parse::zTail.
Referenced by sqlite3_declare_vtab(), sqlite3NestedParse(), and sqlite3Prepare().
Variable Documentation
const char sqlite3IsAsciiIdChar[]
Initial value:
 {
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
    0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
}
Definition at line 88 of file tokenize.c.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1