ContextLogger2 Logger Daemon Internals: up_uploader.h File Reference
up_uploader.h File Reference
Defines
#define up_DOMAIN domain_cl2app
#define up_ERR_GENERAL 1
#define ac_global_Uploader ac_get_Uploader(ac_get_global_AppContext())
Typedefs
typedef struct _up_Uploader up_Uploader
Functions
gboolean up_global_init (GError **error)
void up_global_cleanup ()
up_Uploader * up_Uploader_new (ac_AppContext *aAppContext, GError **error)
void up_Uploader_destroy (up_Uploader *object)
gboolean up_Uploader_upload_now (up_Uploader *object, GError **error)
gboolean up_Uploader_reconfigure (up_Uploader *object, const gchar *key, const gchar *value, GError **error)
up_Uploader * ac_get_Uploader (ac_AppContext *self)
Define Documentation
#define ac_global_Uploader ac_get_Uploader(ac_get_global_AppContext())
Definition at line 48 of file up_uploader.h.
Referenced by MainWindow::uploadNow().
#define up_DOMAIN domain_cl2app
Definition at line 11 of file up_uploader.h.
#define up_ERR_GENERAL 1
Definition at line 13 of file up_uploader.h.
Typedef Documentation
typedef struct _up_Uploader up_Uploader
Definition at line 29 of file up_uploader.h.
Function Documentation
up_Uploader* ac_get_Uploader (ac_AppContext * self)
Definition at line 177 of file ac_app_context.cpp.
void up_global_cleanup ()
Definition at line 710 of file up_uploader_epoc.cpp.
Referenced by cl2GlobalCleanup().
gboolean up_global_init (GError ** error)
Definition at line 704 of file up_uploader_epoc.cpp.
Referenced by cl2GlobalInit().
void up_Uploader_destroy (up_Uploader * object)
Definition at line 750 of file up_uploader_epoc.cpp.
Referenced by stop_uploader().
up_Uploader* up_Uploader_new (ac_AppContext * aAppContext, GError ** error)
Definition at line 738 of file up_uploader_epoc.cpp.
References ac_LogDb(), domain_qt, domain_symbian, gx_error_new(), and plat_error_strerror.
Referenced by start_uploader().
gboolean up_Uploader_reconfigure (up_Uploader * object, const gchar * key, const gchar * value, GError ** error)
Definition at line 725 of file up_uploader_epoc.cpp.
Referenced by kr_Controller_reconfigure().
gboolean up_Uploader_upload_now (up_Uploader * object, GError ** error)
Definition at line 719 of file up_uploader_epoc.cpp.
Referenced by f_upload_now(), and MainWindow::uploadNow().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1