ContextLogger2 Logger Daemon Internals: up_uploader_qt.cpp File Reference
up_uploader_qt.cpp File Reference
Classes
struct ScopedPointerGfree
Defines
#define CATCH_FATAL(_act)
#define CHECKBUFOPEN(x) throw_cstr_unless(x, "QBuffer open failed")
Functions
static time_t TimeNow ()
static void DataChanged (bb_Blackboard *bb, enum bb_DataType dt, gpointer data, int len, gpointer arg)
static int SecsToMsecs (int secs)
EXTERN_C gboolean up_global_init (GError **error)
EXTERN_C void up_global_cleanup ()
EXTERN_C gboolean up_Uploader_upload_now (up_Uploader *object, GError **error)
EXTERN_C gboolean up_Uploader_reconfigure (up_Uploader *object, const gchar *key, const gchar *value, GError **error)
EXTERN_C up_Uploader * up_Uploader_new (ac_AppContext *aAppContext, GError **error)
EXTERN_C void up_Uploader_destroy (up_Uploader *object)
Variables
static const char * KBoundary = "-----AaB03xeql7dsxeql7ds"
Define Documentation
#define CATCH_FATAL (_act)
Value:
try {           \
    _act ;          \
  } catch (const std::exception &_ex) {   \
    FatalError(_ex);        \
  }
Definition at line 262 of file up_uploader_qt.cpp.
#define CHECKBUFOPEN (x) throw_cstr_unless(x, "QBuffer open failed")
Referenced by CUploader::CreatePosterAoL().
Function Documentation
static void DataChanged (bb_Blackboard * bb, enum bb_DataType dt, gpointer data, int len, gpointer arg) [static]
Definition at line 50 of file up_uploader_qt.cpp.
References bb_Blackboard_board(), and bb_Board::uploads_allowed.
static int SecsToMsecs (int secs) [static]
Definition at line 354 of file up_uploader_qt.cpp.
Referenced by CUploader::SetPostTimer().
static time_t TimeNow () [static]
Definition at line 42 of file up_uploader_qt.cpp.
References er_FATAL, and er_log_errno.
Referenced by CUploader::CUploader(), and CUploader::postingFinished().
EXTERN_C void up_global_cleanup ()
Definition at line 699 of file up_uploader_qt.cpp.
Referenced by cl2GlobalCleanup().
EXTERN_C gboolean up_global_init (GError ** error)
Definition at line 693 of file up_uploader_qt.cpp.
Referenced by cl2GlobalInit().
EXTERN_C void up_Uploader_destroy (up_Uploader * object)
Definition at line 740 of file up_uploader_qt.cpp.
Referenced by stop_uploader().
EXTERN_C up_Uploader* up_Uploader_new (ac_AppContext * aAppContext, GError ** error)
Definition at line 727 of file up_uploader_qt.cpp.
References domain_qt, and gx_error_new().
Referenced by start_uploader().
EXTERN_C gboolean up_Uploader_reconfigure (up_Uploader * object, const gchar * key, const gchar * value, GError ** error)
Definition at line 714 of file up_uploader_qt.cpp.
Referenced by kr_Controller_reconfigure().
EXTERN_C gboolean up_Uploader_upload_now (up_Uploader * object, GError ** error)
Definition at line 708 of file up_uploader_qt.cpp.
Referenced by f_upload_now(), and MainWindow::uploadNow().
Variable Documentation
const char* KBoundary = "-----AaB03xeql7dsxeql7ds" [static]
Definition at line 140 of file up_uploader_qt.cpp.
Referenced by CFileDataSupplier::Boundary(), and CFileDataSupplier::OpenL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1