ContextLogger2 Logger Daemon Internals: up_uploader_epoc.cpp File Reference
up_uploader_epoc.cpp File Reference
Classes
class CUploader
Defines
#define CTOR_DECL_CUploader
#define CTOR_IMPL_CUploader
Functions
static void DataChanged (bb_Blackboard *bb, enum bb_DataType dt, gpointer data, int len, gpointer arg)
EXTERN_C gboolean up_global_init (GError **error)
EXTERN_C void up_global_cleanup ()
EXTERN_C gboolean up_Uploader_upload_now (up_Uploader *object, GError **error)
EXTERN_C gboolean up_Uploader_reconfigure (up_Uploader *object, const gchar *key, const gchar *value, GError **error)
EXTERN_C up_Uploader * up_Uploader_new (ac_AppContext *aAppContext, GError **error)
EXTERN_C void up_Uploader_destroy (up_Uploader *object)
Variables
CTOR_IMPL_CUploader
Define Documentation
#define CTOR_DECL_CUploader
Value:
public: static CUploader* NewLC(LogDb* aLogDb); \
public: static CUploader* NewL(LogDb* aLogDb); \
private: CUploader(LogDb* aLogDb); \
private: void ConstructL();
Definition at line 48 of file up_uploader_epoc.cpp.
#define CTOR_IMPL_CUploader
Value:
CUploader* CUploader::NewLC(LogDb* aLogDb) \
{ \
  CUploader* obj = new (ELeave) CUploader(aLogDb); \
  CleanupStack::PushL(obj); \
  obj->ConstructL(); \
  return obj; \
} \
 \
CUploader* CUploader::NewL(LogDb* aLogDb) \
{ \
  CUploader* obj = CUploader::NewLC(aLogDb); \
  CleanupStack::Pop(obj); \
  return obj; \
} \
 \
CUploader::CUploader(LogDb* aLogDb) : iLogDb(aLogDb) \
{}
Definition at line 54 of file up_uploader_epoc.cpp.
Function Documentation
static void DataChanged (bb_Blackboard * bb, enum bb_DataType dt, gpointer data, int len, gpointer arg) [static]
Definition at line 170 of file up_uploader_epoc.cpp.
References bb_Blackboard_board(), and bb_Board::uploads_allowed.
Referenced by CUploader::BbRegisterL().
EXTERN_C void up_global_cleanup ()
Definition at line 710 of file up_uploader_epoc.cpp.
EXTERN_C gboolean up_global_init (GError ** error)
Definition at line 704 of file up_uploader_epoc.cpp.
EXTERN_C void up_Uploader_destroy (up_Uploader * object)
Definition at line 750 of file up_uploader_epoc.cpp.
EXTERN_C up_Uploader* up_Uploader_new (ac_AppContext * aAppContext, GError ** error)
Definition at line 738 of file up_uploader_epoc.cpp.
References ac_LogDb(), domain_symbian, gx_error_new(), and plat_error_strerror.
EXTERN_C gboolean up_Uploader_reconfigure (up_Uploader * object, const gchar * key, const gchar * value, GError ** error)
Definition at line 725 of file up_uploader_epoc.cpp.
EXTERN_C gboolean up_Uploader_upload_now (up_Uploader * object, GError ** error)
Definition at line 719 of file up_uploader_epoc.cpp.
Variable Documentation
CTOR_IMPL_CUploader
Definition at line 168 of file up_uploader_epoc.cpp.
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1