ContextLogger2 Logger Daemon Internals: update.c File Reference
update.c File Reference
Functions
static void updateVirtualTable (Parse *pParse, SrcList *pSrc, Table *pTab, ExprList *pChanges, Expr *pRowidExpr, int *aXRef, Expr *pWhere)
void sqlite3ColumnDefault (Vdbe *v, Table *pTab, int i)
void sqlite3Update (Parse *pParse, SrcList *pTabList, ExprList *pChanges, Expr *pWhere, int onError)
Function Documentation
void sqlite3ColumnDefault (Vdbe * v, Table * pTab, int i)
Definition at line 57 of file update.c.
References Table::aCol, Column::affinity, ENC, P4_MEM, Column::pDflt, Table::pSelect, sqlite3ValueFromExpr(), sqlite3VdbeChangeP4(), sqlite3VdbeDb(), VdbeComment, Column::zName, and Table::zName.
Referenced by sqlite3ExprCodeGetColumn(), sqlite3GenerateIndexKey(), and sqlite3Update().
void sqlite3Update (Parse * pParse, SrcList * pTabList, ExprList * pChanges, Expr * pWhere, int onError)
Definition at line 79 of file update.c.
References ExprList::a, SrcList::a, Table::aCol, sqlite3::aDb, Index::aiColumn, COLNAME_NAME, Parse::db, db, sqlite3::flags, SrcList::SrcList_item::iCursor, Table::iPKey, IsVirtual, sqlite3::mallocFailed, Table::nCol, Index::nColumn, Parse::nErr, Parse::nested, ExprList::nExpr, Parse::nMem, SrcList::nSrc, Parse::nTab, OE_Replace, WhereInfo::okOnePass, Index::onError, OP_AddImm, OP_Close, OP_Column, OP_Delete, OP_FifoRead, OP_FifoWrite, OP_Goto, OP_Insert, OP_Integer, OP_MakeRecord, OP_MustBeInt, OP_NotExists, OP_NotNull, OP_Null, OP_OpenPseudo, OP_OpenWrite, OP_ResultRow, OP_RowData, OP_Rowid, OP_SetNumColumns, OP_VRowid, P4_KEYINFO_HANDOFF, ExprList::ExprList_item::pExpr, Table::pIndex, Index::pNext, NameContext::pParse, AuthContext::pParse, Table::pSchema, Table::pSelect, NameContext::pSrcList, sqlite3AuthCheck(), sqlite3AuthContextPop(), sqlite3AuthContextPush(), sqlite3BeginWriteOperation(), sqlite3CodeRowTrigger(), sqlite3ColumnDefault(), sqlite3CompleteInsertion(), sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3ErrorMsg(), sqlite3ExprCacheAffinityChange(), sqlite3ExprCode(), sqlite3ExprCodeAndCache(), sqlite3ExprDelete(), sqlite3ExprListDelete(), sqlite3GenerateConstraintChecks(), sqlite3GenerateRowIndexDelete(), sqlite3GetTempRange(), sqlite3GetTempReg(), sqlite3GetVdbe(), sqlite3IndexKeyinfo(), sqlite3IsReadOnly(), sqlite3IsRowid(), sqlite3MaterializeView(), sqlite3OpenTable(), sqlite3ReleaseTempRange(), sqlite3ReleaseTempReg(), sqlite3ResolveExprNames(), sqlite3SchemaToIndex(), sqlite3SrcListDelete(), sqlite3SrcListLookup(), sqlite3StrICmp(), sqlite3TableAffinityStr(), sqlite3TriggersExist(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeCountChanges(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), sqlite3VdbeMakeLabel(), sqlite3VdbeResolveLabel(), sqlite3VdbeSetColName(), sqlite3VdbeSetNumCols(), sqlite3ViewGetColumnNames(), sqlite3WhereBegin(), sqlite3WhereEnd(), SQLITE_CountRows, SQLITE_DENY, SQLITE_IGNORE, SQLITE_STATIC, SQLITE_UPDATE, TK_UPDATE, Index::tnum, TRIGGER_AFTER, TRIGGER_BEFORE, Parse::trigStack, updateVirtualTable(), WHERE_ONEPASS_DESIRED, Db::zName, Table::zName, ExprList::ExprList_item::zName, and Column::zName.
Referenced by codeTriggerProgram(), and yy_reduce().
static void updateVirtualTable (Parse * pParse, SrcList * pSrc, Table * pTab, ExprList * pChanges, Expr * pRowidExpr, int * aXRef, Expr * pWhere) [static]
Definition at line 604 of file update.c.
References ExprList::a, Table::aCol, Parse::db, db, Table::iPKey, Table::nCol, Parse::nMem, Parse::nTab, OP_Close, OP_Column, OP_Next, OP_OpenEphemeral, OP_Rewind, OP_VUpdate, P4_VTAB, ExprList::ExprList_item::pExpr, Parse::pVdbe, Table::pVtab, sqlite3CreateIdExpr(), sqlite3ExprDup(), sqlite3ExprListAppend(), sqlite3Select(), sqlite3SelectDelete(), sqlite3SelectDestInit(), sqlite3SelectNew(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp3(), sqlite3VdbeAddOp4(), sqlite3VdbeCurrentAddr(), sqlite3VdbeJumpHere(), sqlite3VtabMakeWritable(), SRT_Table, and Column::zName.
Referenced by sqlite3Update().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1