ContextLogger2 Logger Daemon Internals: ut_timer_epoc.cpp File Reference
ut_timer_epoc.cpp File Reference
Classes
struct _ut_Timer
class CUtTimer
Defines
#define make_error(_errCode, _msg)
Functions
ut_Timer * ut_Timer_new (void *userdata, ut_TimerCallback *cb, GError **error)
void ut_Timer_destroy (ut_Timer *self)
gboolean ut_Timer_set_after (ut_Timer *self, int secs, GError **error)
void ut_Timer_cancel (ut_Timer *self)
gboolean ut_Timer_is_active (ut_Timer *self)
Define Documentation
#define make_error (_errCode, _msg)
Value:
gx_error_new(domain_symbian, _errCode, _msg ": %s (%d)",    \
         plat_error_strerror(_errCode), _errCode);
Definition at line 56 of file ut_timer_epoc.cpp.
Function Documentation
void ut_Timer_cancel (ut_Timer * self)
Definition at line 113 of file ut_timer_epoc.cpp.
void ut_Timer_destroy (ut_Timer * self)
Definition at line 90 of file ut_timer_epoc.cpp.
gboolean ut_Timer_is_active (ut_Timer * self)
Definition at line 118 of file ut_timer_epoc.cpp.
ut_Timer* ut_Timer_new (void * userdata, ut_TimerCallback * cb, GError ** error)
Definition at line 70 of file ut_timer_epoc.cpp.
References gx_error_no_memory, make_error, and CUtTimer::NewL().
gboolean ut_Timer_set_after (ut_Timer * self, int secs, GError ** error)
Definition at line 98 of file ut_timer_epoc.cpp.
References SecsToUsecs(), and ut_Timer_cancel().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1