ContextLogger2 Logger Daemon Internals: ut_timer_libev.c File Reference
ut_timer_libev.c File Reference
Classes
struct _ut_Timer
Functions
static void evCallback (EV_P_ ev_timer *w, int revents)
static void setTimer (ut_Timer *self, int wait_secs)
ut_Timer * ut_Timer_new (void *userdata, ut_TimerCallback *cb, GError **error)
void ut_Timer_destroy (ut_Timer *self)
gboolean ut_Timer_set_after (ut_Timer *self, int secs, GError **error)
void ut_Timer_cancel (ut_Timer *self)
gboolean ut_Timer_is_active (ut_Timer *self)
Function Documentation
static void evCallback (EV_P_ ev_timer * w, int revents) [static]
Definition at line 28 of file ut_timer_libev.c.
Referenced by ut_Timer_new().
static void setTimer (ut_Timer * self, int wait_secs) [static]
Definition at line 20 of file ut_timer_libev.c.
Referenced by ut_Timer_set_after().
void ut_Timer_cancel (ut_Timer * self)
Definition at line 63 of file ut_timer_libev.c.
void ut_Timer_destroy (ut_Timer * self)
Definition at line 47 of file ut_timer_libev.c.
References ut_Timer_cancel().
gboolean ut_Timer_is_active (ut_Timer * self)
Definition at line 70 of file ut_timer_libev.c.
ut_Timer* ut_Timer_new (void * userdata, ut_TimerCallback * cb, GError ** error)
Definition at line 34 of file ut_timer_libev.c.
References evCallback(), and gx_error_no_memory.
gboolean ut_Timer_set_after (ut_Timer * self, int secs, GError ** error)
Definition at line 55 of file ut_timer_libev.c.
References setTimer(), and ut_Timer_is_active().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1