ContextLogger2 Logger Daemon Internals: ut_telno_epoc.cpp File Reference
ut_telno_epoc.cpp File Reference
Functions
static CContactItem * FindContactItemByPhoneNoL (const TDesC &phoneNo)
static gchar * GetNameFromContactItemL (const CContactItem &item)
gchar * GetContactNameByPhoneNoL (const TDesC &phoneNo)
gchar * GetContactNameByPhoneNo (const TDesC &phoneNo)
Function Documentation
static CContactItem* FindContactItemByPhoneNoL (const TDesC & phoneNo) [static]
Definition at line 18 of file ut_telno_epoc.cpp.
References ac_get_global_AppContext(), and logg.
Referenced by GetContactNameByPhoneNoL().
gchar* GetContactNameByPhoneNo (const TDesC & phoneNo)
Definition at line 103 of file ut_telno_epoc.cpp.
References GetContactNameByPhoneNoL().
Referenced by CSensor_smsevent::LogEvent().
gchar* GetContactNameByPhoneNoL (const TDesC & phoneNo)
Definition at line 90 of file ut_telno_epoc.cpp.
References FindContactItemByPhoneNoL(), GetNameFromContactItemL(), logg, and logt.
Referenced by GetContactNameByPhoneNo().
static gchar* GetNameFromContactItemL (const CContactItem & item) [static]
Definition at line 50 of file ut_telno_epoc.cpp.
References _LIT(), and logg.
Referenced by GetContactNameByPhoneNoL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1