ContextLogger2 Logger Daemon Internals: ut_compress_zlib_raw.c File Reference
ut_compress_zlib_raw.c File Reference
Defines
#define SET_BINARY_MODE(file)
#define CHUNK (8 * 1024)
Functions
static int def (FILE *source, FILE *dest, int level, unsigned char *inBuf, unsigned char *outBuf)
static GError * zerr (int ret)
static gboolean compress_ft (const char *fs, const char *ft, GError **error)
gboolean compress_file (const char *fn, GError **error)
Define Documentation
#define CHUNK (8 * 1024)
Definition at line 36 of file ut_compress_zlib_raw.c.
Referenced by compress_ft(), and def().
#define SET_BINARY_MODE (file)
Definition at line 32 of file ut_compress_zlib_raw.c.
Function Documentation
gboolean compress_file (const char * fn, GError ** error)
Definition at line 168 of file ut_compress_zlib_raw.c.
References compress_ft(), domain_posix, gx_error_new(), and LOG_UPLOADS_DIR.
Referenced by log_db_take_snapshot().
static gboolean compress_ft (const char * fs, const char * ft, GError ** error) [static]
Definition at line 117 of file ut_compress_zlib_raw.c.
References CHUNK, def(), domain_posix, gx_error_new(), gx_error_no_memory, and zerr().
Referenced by compress_file().
static int def (FILE * source, FILE * dest, int level, unsigned char * inBuf, unsigned char * outBuf) [static]
Definition at line 44 of file ut_compress_zlib_raw.c.
References CHUNK.
Referenced by compress_ft().
static GError* zerr (int ret) [static]
Definition at line 96 of file ut_compress_zlib_raw.c.
References domain_posix, domain_zlib, and gx_error_new().
Referenced by compress_ft().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1