ContextLogger2 Logger Daemon Internals: ut_compress_cryptopp_gzip.cpp File Reference
ut_compress_cryptopp_gzip.cpp File Reference
Functions
static void gzip_file (const char *in, const char *out)
static gboolean compress_ft (const char *fs, const char *ft, GError **error)
gboolean compress_file (const char *fn, GError **error)
Function Documentation
gboolean compress_file (const char * fn, GError ** error)
Definition at line 53 of file ut_compress_cryptopp_gzip.cpp.
References compress_ft(), domain_posix, gx_error_new(), and LOG_UPLOADS_DIR.
static gboolean compress_ft (const char * fs, const char * ft, GError ** error) [static]
Definition at line 41 of file ut_compress_cryptopp_gzip.cpp.
References domain_cryptopp, gx_error_new(), and gzip_file().
Referenced by compress_file().
static void gzip_file (const char * in, const char * out) [static]
Definition at line 35 of file ut_compress_cryptopp_gzip.cpp.
Referenced by compress_ft().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1