ContextLogger2 Logger Daemon Internals: ut_telephony_epoc.cpp File Reference
ut_telephony_epoc.cpp File Reference
Functions
void ClosureFunc_SignalStrength (bb_Blackboard *, enum bb_DataType, gpointer, int, gpointer arg)
void ClosureFunc_NetworkInfo (bb_Blackboard *, enum bb_DataType, gpointer, int, gpointer arg)
void ClosureFunc_NetworkRegistration (bb_Blackboard *, enum bb_DataType, gpointer, int, gpointer arg)
Function Documentation
void ClosureFunc_NetworkInfo (bb_Blackboard * , enum bb_DataType, gpointer , int , gpointer arg)
Definition at line 566 of file ut_telephony_epoc.cpp.
Referenced by CObserverAo_NetworkInfo::BbRegisterL().
void ClosureFunc_NetworkRegistration (bb_Blackboard * , enum bb_DataType, gpointer , int , gpointer arg)
Definition at line 675 of file ut_telephony_epoc.cpp.
Referenced by CObserverAo_NetworkRegistration::BbRegisterL().
void ClosureFunc_SignalStrength (bb_Blackboard * , enum bb_DataType, gpointer , int , gpointer arg)
Definition at line 440 of file ut_telephony_epoc.cpp.
Referenced by CObserverAo_SignalStrength::BbRegisterL().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1