ContextLogger2 Logger Daemon Internals: ut_timer_qt.cpp File Reference
ut_timer_qt.cpp File Reference
Classes
struct _ut_Timer
Functions
ut_Timer * ut_Timer_new (void *userdata, ut_TimerCallback *cb, GError **error)
void ut_Timer_destroy (ut_Timer *self)
gboolean ut_Timer_set_after (ut_Timer *self, int secs, GError **error)
void ut_Timer_cancel (ut_Timer *self)
gboolean ut_Timer_is_active (ut_Timer *self)
Function Documentation
void ut_Timer_cancel (ut_Timer * self)
Definition at line 65 of file ut_timer_qt.cpp.
Referenced by sa_Sensor_mark_stop(), ut_Timer_destroy(), and ut_Timer_set_after().
void ut_Timer_destroy (ut_Timer * self)
Definition at line 46 of file ut_timer_qt.cpp.
Referenced by sa_Sensor_mark_destroy().
gboolean ut_Timer_is_active (ut_Timer * self)
Definition at line 71 of file ut_timer_qt.cpp.
Referenced by sa_Sensor_mark_is_active(), and ut_Timer_set_after().
ut_Timer* ut_Timer_new (void * userdata, ut_TimerCallback * cb, GError ** error)
Definition at line 29 of file ut_timer_qt.cpp.
References gx_error_no_memory.
Referenced by sa_Sensor_mark_new().
gboolean ut_Timer_set_after (ut_Timer * self, int secs, GError ** error)
Definition at line 55 of file ut_timer_qt.cpp.
References ut_Timer_is_active().
Referenced by setTimer().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1