ContextLogger2 Logger Daemon Internals: utils_cl2.c File Reference
utils_cl2.c File Reference
Functions
gboolean mkdir_p (const gchar *pathname, GError **error)
gboolean rm_file (const gchar *pathname, GError **error)
void g_string_vprintf (GString *string, const gchar *format, va_list args)
gboolean is_ascii_ident (const gchar *s)
Function Documentation
void g_string_vprintf (GString * string, const gchar * format, va_list args)
Definition at line 52 of file utils_cl2.c.
gboolean is_ascii_ident (const gchar * s)
Definition at line 63 of file utils_cl2.c.
Referenced by f_is_ascii_ident().
gboolean mkdir_p (const gchar * pathname, GError ** error)
Definition at line 14 of file utils_cl2.c.
References assert_error_unset, gx_error_new(), gx_error_no_memory, and TRAP_OOM_FAIL.
Referenced by create_database(), and CUploader::CUploader().
gboolean rm_file (const gchar * pathname, GError ** error)
Definition at line 38 of file utils_cl2.c.
References assert_error_unset, and gx_error_new().
Referenced by create_database(), CUploader::PosterEvent(), and CUploader::postingFinished().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1