ContextLogger2 Logger Daemon Internals: utils_cl2.h File Reference
utils_cl2.h File Reference
Defines
#define DECREF(x) { g_object_unref(x); x = NULL; }
#define XDECREF(x) { if (x) DECREF(x) }
#define FREE_Z(_x, _f) { if (_x) { _f(_x); (_x) = NULL; } }
#define g_string_append_printf_fix(arg...) g_string_append_printf(arg)
#define g_snprintf_fix(arg...) g_snprintf(arg)
Functions
G_BEGIN_DECLS gboolean mkdir_p (const gchar *pathname, GError **error)
gboolean rm_file (const gchar *pathname, GError **error)
gboolean is_ascii_ident (const gchar *s)
void g_string_vprintf (GString *string, const gchar *format, va_list args)
Define Documentation
#define DECREF (x) { g_object_unref(x); x = NULL; }
Definition at line 17 of file utils_cl2.h.
#define FREE_Z (_x, _f) { if (_x) { _f(_x); (_x) = NULL; } }
Definition at line 24 of file utils_cl2.h.
Referenced by free_config_cache(), and kr_Controller_destroy().
#define g_snprintf_fix (arg...) g_snprintf(arg)
Definition at line 43 of file utils_cl2.h.
Referenced by cl2GlobalInit(), and LogSatelliteInfoL().
#define g_string_append_printf_fix (arg...) g_string_append_printf(arg)
Definition at line 42 of file utils_cl2.h.
Referenced by LogSatelliteInfoL().
#define XDECREF (x) { if (x) DECREF(x) }
Definition at line 18 of file utils_cl2.h.
Function Documentation
void g_string_vprintf (GString * string, const gchar * format, va_list args)
Definition at line 52 of file utils_cl2.c.
gboolean is_ascii_ident (const gchar * s)
Definition at line 63 of file utils_cl2.c.
Referenced by f_is_ascii_ident().
G_BEGIN_DECLS gboolean mkdir_p (const gchar * pathname, GError ** error)
Definition at line 14 of file utils_cl2.c.
References assert_error_unset, gx_error_new(), gx_error_no_memory, and TRAP_OOM_FAIL.
Referenced by create_database(), and CUploader::CUploader().
gboolean rm_file (const gchar * pathname, GError ** error)
Definition at line 38 of file utils_cl2.c.
References assert_error_unset, and gx_error_new().
Referenced by create_database(), CUploader::PosterEvent(), and CUploader::postingFinished().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1