ContextLogger2 Logger Daemon Internals: util.c File Reference
util.c File Reference
Defines
#define UpperToLower sqlite3UpperToLower
Functions
int sqlite3IsNaN (double x)
int sqlite3Strlen (sqlite3 *db, const char *z)
void sqlite3Error (sqlite3 *db, int err_code, const char *zFormat,...)
void sqlite3ErrorMsg (Parse *pParse, const char *zFormat,...)
void sqlite3ErrorClear (Parse *pParse)
void sqlite3Dequote (char *z)
int sqlite3StrICmp (const char *zLeft, const char *zRight)
int sqlite3StrNICmp (const char *zLeft, const char *zRight, int N)
int sqlite3IsNumber (const char *z, int *realnum, u8 enc)
int sqlite3AtoF (const char *z, double *pResult)
static int compare2pow63 (const char *zNum)
int sqlite3Atoi64 (const char *zNum, i64 *pNum)
int sqlite3FitsIn64Bits (const char *zNum, int negFlag)
int sqlite3GetInt32 (const char *zNum, int *pValue)
int sqlite3PutVarint (unsigned char *p, u64 v)
int sqlite3PutVarint32 (unsigned char *p, u32 v)
int sqlite3GetVarint (const unsigned char *p, u64 *v)
int sqlite3GetVarint32 (const unsigned char *p, u32 *v)
int sqlite3VarintLen (u64 v)
u32 sqlite3Get4byte (const u8 *p)
void sqlite3Put4byte (unsigned char *p, u32 v)
static int hexToInt (int h)
void * sqlite3HexToBlob (sqlite3 *db, const char *z, int n)
int sqlite3SafetyCheckOk (sqlite3 *db)
int sqlite3SafetyCheckSickOrOk (sqlite3 *db)
Define Documentation
#define UpperToLower sqlite3UpperToLower
Definition at line 185 of file util.c.
Referenced by sqlite3StrICmp(), and sqlite3StrNICmp().
Function Documentation
static int compare2pow63 (const char * zNum) [static]
Definition at line 337 of file util.c.
Referenced by sqlite3Atoi64(), and sqlite3FitsIn64Bits().
static int hexToInt (int h) [static]
Definition at line 828 of file util.c.
Referenced by sqlite3HexToBlob().
int sqlite3AtoF (const char * z, double * pResult)
Definition at line 252 of file util.c.
References LONGDOUBLE_TYPE, and sqlite3Atoi64().
Referenced by codeReal(), roundFunc(), and sqlite3VdbeRealValue().
int sqlite3Atoi64 (const char * zNum, i64 * pNum)
Definition at line 357 of file util.c.
References compare2pow63().
Referenced by applyNumericAffinity(), codeInteger(), sqlite3AtoF(), and sqlite3VdbeIntValue().
void sqlite3Dequote (char * z)
Definition at line 157 of file util.c.
Referenced by selectColumnsFromExprList(), sqlite3DequoteExpr(), sqlite3NameFromToken(), and sqlite3ValueFromExpr().
void sqlite3Error (sqlite3 * db, int err_code, const char * zFormat, ...)
Definition at line 92 of file util.c.
References sqlite3::errCode, sqlite3::pErr, sqlite3ValueNew(), sqlite3ValueSetStr(), sqlite3VMPrintf(), SQLITE_DYNAMIC, SQLITE_STATIC, and SQLITE_UTF8.
Referenced by bindText(), blobReadWrite(), columnMem(), createCollation(), openDatabase(), sqlite3_blob_open(), sqlite3_close(), sqlite3_declare_vtab(), sqlite3_exec(), sqlite3ApiExit(), sqlite3AutoLoadExtensions(), sqlite3CreateFunc(), sqlite3Prepare(), sqlite3VdbeReset(), sqlite3VtabOverloadFunction(), and vdbeUnbind().
void sqlite3ErrorClear (Parse * pParse)
Definition at line 141 of file util.c.
References Parse::db, Parse::nErr, sqlite3DbFree(), and Parse::zErrMsg.
Referenced by resolveOrderByTermToExprList(), and sqlite3DropTable().
void sqlite3ErrorMsg (Parse * pParse, const char * zFormat, ...)
Definition at line 125 of file util.c.
References Parse::db, db, Parse::nErr, Parse::rc, sqlite3DbFree(), sqlite3VMPrintf(), SQLITE_ERROR, SQLITE_OK, and Parse::zErrMsg.
Referenced by bestVirtualIndex(), checkForMultiColumnSelectError(), invalidateTempStorage(), lookupName(), multiSelect(), resetAccumulator(), resolveAttachExpr(), resolveCompoundOrderBy(), resolveExprStep(), resolveOutOfRangeError(), resolveSelectStep(), selectExpander(), sqlite3_blob_open(), sqlite3AddColumn(), sqlite3AddDefaultValue(), sqlite3AddPrimaryKey(), sqlite3AlterBeginAddColumn(), sqlite3AlterFinishAddColumn(), sqlite3AlterRenameTable(), sqlite3AuthCheck(), sqlite3AuthRead(), sqlite3BeginTrigger(), sqlite3CheckCollSeq(), sqlite3CheckObjectName(), sqlite3CodeRowTrigger(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3CreateView(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTrigger(), sqlite3ExprAssignVarNumber(), sqlite3ExprCodeTarget(), sqlite3ExprListCheckLength(), sqlite3FixSrcList(), sqlite3IndexedByLookup(), sqlite3Insert(), sqlite3IsReadOnly(), sqlite3JoinType(), sqlite3LocateCollSeq(), sqlite3LocateTable(), sqlite3OpenTempDatabase(), sqlite3Pragma(), sqlite3RegisterExpr(), sqlite3Reindex(), sqlite3ResolveOrderGroupBy(), sqlite3Select(), sqlite3StartTable(), sqlite3TwoPartName(), sqlite3Update(), sqlite3ViewGetColumnNames(), sqlite3VtabBeginParse(), sqlite3VtabCallConnect(), sqlite3WhereBegin(), sqliteAuthBadReturnCode(), sqliteProcessJoin(), yy_reduce(), yy_syntax_error(), and yyStackOverflow().
int sqlite3FitsIn64Bits (const char * zNum, int negFlag)
Definition at line 404 of file util.c.
References compare2pow63().
Referenced by codeInteger().
u32 sqlite3Get4byte (const u8 * p)
Definition at line 810 of file util.c.
Referenced by pager_incr_changecounter(), and read32bits().
int sqlite3GetInt32 (const char * zNum, int * pValue)
Definition at line 438 of file util.c.
Referenced by codeInteger(), sqlite3ExprIsInteger(), and sqlite3Pragma().
int sqlite3GetVarint (const unsigned char * p, u64 * v)
Definition at line 552 of file util.c.
Referenced by sqlite3GetVarint32().
int sqlite3GetVarint32 (const unsigned char * p, u32 * v)
Definition at line 714 of file util.c.
References sqlite3GetVarint().
void* sqlite3HexToBlob (sqlite3 * db, const char * z, int n)
Definition at line 847 of file util.c.
References hexToInt(), and sqlite3DbMallocRaw().
Referenced by sqlite3ExprCodeTarget(), and sqlite3ValueFromExpr().
int sqlite3IsNaN (double x)
Definition at line 27 of file util.c.
Referenced by codeReal(), sqlite3_initialize(), sqlite3VdbeExec(), sqlite3VdbeMemSetDouble(), sqlite3VdbeSerialGet(), and sqlite3VXPrintf().
int sqlite3IsNumber (const char * z, int * realnum, u8 enc)
Definition at line 214 of file util.c.
References SQLITE_UTF16BE, and SQLITE_UTF8.
Referenced by applyNumericAffinity(), and parseDateOrTime().
void sqlite3Put4byte (unsigned char * p, u32 v)
Definition at line 813 of file util.c.
int sqlite3PutVarint (unsigned char * p, u64 v)
Definition at line 500 of file util.c.
Referenced by sqlite3PutVarint32().
int sqlite3PutVarint32 (unsigned char * p, u32 v)
Definition at line 533 of file util.c.
References sqlite3PutVarint().
int sqlite3SafetyCheckOk (sqlite3 * db)
Definition at line 936 of file util.c.
References sqlite3::magic, SQLITE_MAGIC_BUSY, and SQLITE_MAGIC_OPEN.
Referenced by sqlite3LockAndPrepare(), sqlite3Prepare16(), and sqlite3VtabUnlock().
int sqlite3SafetyCheckSickOrOk (sqlite3 * db)
Definition at line 944 of file util.c.
References sqlite3::magic, SQLITE_MAGIC_BUSY, SQLITE_MAGIC_OPEN, and SQLITE_MAGIC_SICK.
Referenced by sqlite3_close(), sqlite3_errcode(), sqlite3_errmsg(), sqlite3_errmsg16(), and sqlite3_extended_errcode().
int sqlite3StrICmp (const char * zLeft, const char * zRight)
Definition at line 191 of file util.c.
References UpperToLower.
Referenced by attachFunc(), collationMatch(), columnIndex(), detachFunc(), findTerm(), flagPragma(), getAutoVacuum(), getLockingMode(), getTempStore(), isSortingIndex(), lookupName(), parseDateOrTime(), resolveAsName(), selectColumnsFromExprList(), selectExpander(), sqlite3_blob_open(), sqlite3AddPrimaryKey(), sqlite3CreateForeignKey(), sqlite3CreateIndex(), sqlite3DropTrigger(), sqlite3FindDb(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3FixSrcList(), sqlite3IdListIndex(), sqlite3IndexedByLookup(), sqlite3Insert(), sqlite3IsRowid(), sqlite3Pragma(), sqlite3Update(), and xferCompatibleCollation().
int sqlite3Strlen (sqlite3 * db, const char * z)
Definition at line 57 of file util.c.
References sqlite3::aLimit, and SQLITE_LIMIT_LENGTH.
Referenced by callCollNeeded(), createCollation(), findCollSeqEntry(), sqlite3_overload_function(), sqlite3CreateFunc(), sqlite3FindIndex(), sqlite3FindTable(), sqlite3LocateCollSeq(), and sqlite3UnlinkAndDeleteIndex().
int sqlite3StrNICmp (const char * zLeft, const char * zRight, int N)
Definition at line 198 of file util.c.
References UpperToLower.
Referenced by functionSearch(), getSafetyLevel(), isMatchOfColumn(), keywordCode(), minMaxQuery(), nocaseCollatingFunc(), sqlite3_complete(), sqlite3AlterRenameTable(), sqlite3BeginTrigger(), sqlite3CheckObjectName(), sqlite3CreateIndex(), sqlite3DropTable(), sqlite3ExprCompare(), sqlite3JoinType(), sqlite3Pragma(), strCompare(), and vtabCallConstructor().
int sqlite3VarintLen (u64 v)
Definition at line 797 of file util.c.
Referenced by sqlite3VdbeExec().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1