ContextLogger2 Logger Daemon Internals: vacuum.c File Reference
vacuum.c File Reference
Functions
static int execSql (sqlite3 *db, const char *zSql)
static int execExecSql (sqlite3 *db, const char *zSql)
void sqlite3Vacuum (Parse *pParse)
int sqlite3RunVacuum (char **pzErrMsg, sqlite3 *db)
Function Documentation
static int execExecSql (sqlite3 * db, const char * zSql) [static]
Definition at line 42 of file vacuum.c.
References execSql(), sqlite3_column_text(), sqlite3_finalize(), sqlite3_prepare(), sqlite3_step(), SQLITE_OK, and SQLITE_ROW.
Referenced by sqlite3RunVacuum().
static int execSql (sqlite3 * db, const char * zSql) [static]
Definition at line 26 of file vacuum.c.
References sqlite3_errcode(), sqlite3_finalize(), sqlite3_prepare(), sqlite3_step(), SQLITE_NOMEM, SQLITE_OK, and SQLITE_ROW.
Referenced by execExecSql(), and sqlite3RunVacuum().
int sqlite3RunVacuum (char ** pzErrMsg, sqlite3 * db)
Definition at line 81 of file vacuum.c.
References sqlite3::aDb, sqlite3::autoCommit, execExecSql(), execSql(), sqlite3::flags, sqlite3::mallocFailed, sqlite3::nChange, sqlite3::nDb, sqlite3::nextAutovac, sqlite3::nextPagesize, sqlite3::nTotalChange, Db::pBt, sqlite3_file::pMethods, Db::pSchema, sqlite3BtreeClose(), sqlite3BtreeCommit(), sqlite3BtreeCopyFile(), sqlite3BtreeGetAutoVacuum(), sqlite3BtreeGetMeta(), sqlite3BtreeGetPageSize(), sqlite3BtreeGetReserve(), sqlite3BtreeIsInTrans(), sqlite3BtreePager(), sqlite3BtreeSetAutoVacuum(), sqlite3BtreeSetPageSize(), sqlite3BtreeUpdateMeta(), sqlite3PagerFile(), sqlite3ResetInternalSchema(), sqlite3SetString(), SQLITE_ERROR, SQLITE_IgnoreChecks, SQLITE_NOMEM, SQLITE_OK, SQLITE_WriteSchema, and Db::zName.
Referenced by sqlite3VdbeExec().
void sqlite3Vacuum (Parse * pParse)
Definition at line 70 of file vacuum.c.
References OP_Vacuum, sqlite3GetVdbe(), and sqlite3VdbeAddOp2().
Referenced by yy_reduce().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1