ContextLogger2 Logger Daemon Internals: vdbeapi.c File Reference
vdbeapi.c File Reference
Defines
#define stmtLruRemove(x)
#define stmtLruAdd(x)
#define vdbeReprepare(x) sqlite3Reprepare(x)
Functions
int sqlite3_expired (sqlite3_stmt *pStmt)
int sqlite3_finalize (sqlite3_stmt *pStmt)
int sqlite3_reset (sqlite3_stmt *pStmt)
int sqlite3_clear_bindings (sqlite3_stmt *pStmt)
const void * sqlite3_value_blob (sqlite3_value *pVal)
int sqlite3_value_bytes (sqlite3_value *pVal)
int sqlite3_value_bytes16 (sqlite3_value *pVal)
double sqlite3_value_double (sqlite3_value *pVal)
int sqlite3_value_int (sqlite3_value *pVal)
sqlite_int64 sqlite3_value_int64 (sqlite3_value *pVal)
const unsigned char * sqlite3_value_text (sqlite3_value *pVal)
const void * sqlite3_value_text16 (sqlite3_value *pVal)
const void * sqlite3_value_text16be (sqlite3_value *pVal)
const void * sqlite3_value_text16le (sqlite3_value *pVal)
int sqlite3_value_type (sqlite3_value *pVal)
void sqlite3_result_blob (sqlite3_context *pCtx, const void *z, int n, void(*xDel)(void *))
void sqlite3_result_double (sqlite3_context *pCtx, double rVal)
void sqlite3_result_error (sqlite3_context *pCtx, const char *z, int n)
void sqlite3_result_error16 (sqlite3_context *pCtx, const void *z, int n)
void sqlite3_result_int (sqlite3_context *pCtx, int iVal)
void sqlite3_result_int64 (sqlite3_context *pCtx, i64 iVal)
void sqlite3_result_null (sqlite3_context *pCtx)
void sqlite3_result_text (sqlite3_context *pCtx, const char *z, int n, void(*xDel)(void *))
void sqlite3_result_text16 (sqlite3_context *pCtx, const void *z, int n, void(*xDel)(void *))
void sqlite3_result_text16be (sqlite3_context *pCtx, const void *z, int n, void(*xDel)(void *))
void sqlite3_result_text16le (sqlite3_context *pCtx, const void *z, int n, void(*xDel)(void *))
void sqlite3_result_value (sqlite3_context *pCtx, sqlite3_value *pValue)
void sqlite3_result_zeroblob (sqlite3_context *pCtx, int n)
void sqlite3_result_error_code (sqlite3_context *pCtx, int errCode)
void sqlite3_result_error_toobig (sqlite3_context *pCtx)
void sqlite3_result_error_nomem (sqlite3_context *pCtx)
static int sqlite3Step (Vdbe *p)
int sqlite3_step (sqlite3_stmt *pStmt)
void * sqlite3_user_data (sqlite3_context *p)
sqlite3 * sqlite3_context_db_handle (sqlite3_context *p)
void sqlite3InvalidFunction (sqlite3_context *context, int argc, sqlite3_value **argv)
void * sqlite3_aggregate_context (sqlite3_context *p, int nByte)
void * sqlite3_get_auxdata (sqlite3_context *pCtx, int iArg)
void sqlite3_set_auxdata (sqlite3_context *pCtx, int iArg, void *pAux, void(*xDelete)(void *))
int sqlite3_aggregate_count (sqlite3_context *p)
int sqlite3_column_count (sqlite3_stmt *pStmt)
int sqlite3_data_count (sqlite3_stmt *pStmt)
static Mem * columnMem (sqlite3_stmt *pStmt, int i)
static void columnMallocFailure (sqlite3_stmt *pStmt)
const void * sqlite3_column_blob (sqlite3_stmt *pStmt, int i)
int sqlite3_column_bytes (sqlite3_stmt *pStmt, int i)
int sqlite3_column_bytes16 (sqlite3_stmt *pStmt, int i)
double sqlite3_column_double (sqlite3_stmt *pStmt, int i)
int sqlite3_column_int (sqlite3_stmt *pStmt, int i)
sqlite_int64 sqlite3_column_int64 (sqlite3_stmt *pStmt, int i)
const unsigned char * sqlite3_column_text (sqlite3_stmt *pStmt, int i)
sqlite3_value * sqlite3_column_value (sqlite3_stmt *pStmt, int i)
const void * sqlite3_column_text16 (sqlite3_stmt *pStmt, int i)
int sqlite3_column_type (sqlite3_stmt *pStmt, int i)
static const void * columnName (sqlite3_stmt *pStmt, int N, const void *(*xFunc)(Mem *), int useType)
const char * sqlite3_column_name (sqlite3_stmt *pStmt, int N)
const void * sqlite3_column_name16 (sqlite3_stmt *pStmt, int N)
const char * sqlite3_column_decltype (sqlite3_stmt *pStmt, int N)
const void * sqlite3_column_decltype16 (sqlite3_stmt *pStmt, int N)
static int vdbeUnbind (Vdbe *p, int i)
static int bindText (sqlite3_stmt *pStmt, int i, const void *zData, int nData, void(*xDel)(void *), int encoding)
int sqlite3_bind_blob (sqlite3_stmt *pStmt, int i, const void *zData, int nData, void(*xDel)(void *))
int sqlite3_bind_double (sqlite3_stmt *pStmt, int i, double rValue)
int sqlite3_bind_int (sqlite3_stmt *p, int i, int iValue)
int sqlite3_bind_int64 (sqlite3_stmt *pStmt, int i, sqlite_int64 iValue)
int sqlite3_bind_null (sqlite3_stmt *pStmt, int i)
int sqlite3_bind_text (sqlite3_stmt *pStmt, int i, const char *zData, int nData, void(*xDel)(void *))
int sqlite3_bind_text16 (sqlite3_stmt *pStmt, int i, const void *zData, int nData, void(*xDel)(void *))
int sqlite3_bind_value (sqlite3_stmt *pStmt, int i, const sqlite3_value *pValue)
int sqlite3_bind_zeroblob (sqlite3_stmt *pStmt, int i, int n)
int sqlite3_bind_parameter_count (sqlite3_stmt *pStmt)
static void createVarMap (Vdbe *p)
const char * sqlite3_bind_parameter_name (sqlite3_stmt *pStmt, int i)
int sqlite3_bind_parameter_index (sqlite3_stmt *pStmt, const char *zName)
int sqlite3TransferBindings (sqlite3_stmt *pFromStmt, sqlite3_stmt *pToStmt)
int sqlite3_transfer_bindings (sqlite3_stmt *pFromStmt, sqlite3_stmt *pToStmt)
sqlite3 * sqlite3_db_handle (sqlite3_stmt *pStmt)
sqlite3_stmt * sqlite3_next_stmt (sqlite3 *pDb, sqlite3_stmt *pStmt)
int sqlite3_stmt_status (sqlite3_stmt *pStmt, int op, int resetFlag)
Define Documentation
#define stmtLruAdd (x)
Definition at line 172 of file vdbeapi.c.
Referenced by sqlite3_reset().
#define stmtLruRemove (x)
Definition at line 171 of file vdbeapi.c.
Referenced by sqlite3_finalize(), and sqlite3Step().
#define vdbeReprepare (x) sqlite3Reprepare(x)
Definition at line 173 of file vdbeapi.c.
Referenced by sqlite3_step().
Function Documentation
static int bindText (sqlite3_stmt * pStmt, int i, const void * zData, int nData, void(*)(void *) xDel, int encoding) [static]
Definition at line 1048 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, ENC, sqlite3::mutex, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3Error(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemSetStr(), SQLITE_OK, and vdbeUnbind().
Referenced by sqlite3_bind_blob(), sqlite3_bind_text(), and sqlite3_bind_text16().
static void columnMallocFailure (sqlite3_stmt * pStmt) [static]
Definition at line 782 of file vdbeapi.c.
References Vdbe::db, sqlite3::mutex, Vdbe::rc, sqlite3_mutex_leave, and sqlite3ApiExit().
Referenced by sqlite3_column_blob(), sqlite3_column_bytes(), sqlite3_column_bytes16(), sqlite3_column_double(), sqlite3_column_int(), sqlite3_column_int64(), sqlite3_column_text(), sqlite3_column_text16(), sqlite3_column_type(), and sqlite3_column_value().
static Mem* columnMem (sqlite3_stmt * pStmt, int i) [static]
Definition at line 742 of file vdbeapi.c.
References Vdbe::db, MEM_Null, sqlite3::mutex, Vdbe::pResultSet, sqlite3_data_count(), sqlite3_mutex_enter, sqlite3Error(), SQLITE_NULL, and SQLITE_RANGE.
Referenced by sqlite3_column_blob(), sqlite3_column_bytes(), sqlite3_column_bytes16(), sqlite3_column_double(), sqlite3_column_int(), sqlite3_column_int64(), sqlite3_column_text(), sqlite3_column_text16(), sqlite3_column_type(), and sqlite3_column_value().
static const void* columnName (sqlite3_stmt * pStmt, int N, const void *(*)(Mem *) xFunc, int useType) [static]
Definition at line 885 of file vdbeapi.c.
References Vdbe::aColName, Vdbe::db, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_column_count(), sqlite3_mutex_enter, and sqlite3_mutex_leave.
Referenced by sqlite3_column_decltype(), sqlite3_column_decltype16(), sqlite3_column_name(), and sqlite3_column_name16().
static void createVarMap (Vdbe * p) [static]
Definition at line 1180 of file vdbeapi.c.
References Vdbe::aOp, Vdbe::azVar, Vdbe::db, sqlite3::mutex, Vdbe::nVar, Vdbe::okVar, OP_Variable, VdbeOp::opcode, VdbeOp::p1, VdbeOp::p4, sqlite3_mutex_enter, sqlite3_mutex_leave, and VdbeOp::z.
Referenced by sqlite3_bind_parameter_index(), and sqlite3_bind_parameter_name().
void* sqlite3_aggregate_context (sqlite3_context * p, int nByte)
Definition at line 620 of file vdbeapi.c.
References Mem::db, Mem::flags, MEM_Agg, MEM_Null, sqlite3::mutex, Mem::pDef, sqlite3_context::pFunc, sqlite3_context::pMem, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemGrow(), sqlite3VdbeMemReleaseExternal(), Mem::u, FuncDef::xStep, and Mem::z.
Referenced by avgFinalize(), countFinalize(), countStep(), FUNC(), groupConcatFinalize(), groupConcatStep(), minMaxFinalize(), minmaxStep(), sumFinalize(), sumStep(), and totalFinalize().
int sqlite3_aggregate_count (sqlite3_context * p)
Definition at line 711 of file vdbeapi.c.
References Mem::n, sqlite3_context::pFunc, sqlite3_context::pMem, and FuncDef::xStep.
Referenced by FUNC().
int sqlite3_bind_blob (sqlite3_stmt * pStmt, int i, const void * zData, int nData, void(*)(void *) xDel)
Definition at line 1080 of file vdbeapi.c.
References bindText().
Referenced by block_insert(), DbObjCmd(), FUNC(), segdir_set(), term_insert(), and term_update().
int sqlite3_bind_double (sqlite3_stmt * pStmt, int i, double rValue)
Definition at line 1089 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, sqlite3VdbeMemSetDouble(), SQLITE_OK, and vdbeUnbind().
Referenced by DbObjCmd(), FUNC(), and log_db_log_position().
int sqlite3_bind_int (sqlite3_stmt * p, int i, int iValue)
Definition at line 1099 of file vdbeapi.c.
References sqlite3_bind_int64().
Referenced by DbObjCmd(), FUNC(), leavesReadersInit(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), segdir_max_index(), segdir_set(), segdir_span(), term_insert(), and term_select().
int sqlite3_bind_int64 (sqlite3_stmt * pStmt, int i, sqlite_int64 iValue)
Definition at line 1102 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, sqlite3VdbeMemSetInt64(), SQLITE_OK, and vdbeUnbind().
int sqlite3_bind_null (sqlite3_stmt * pStmt, int i)
Definition at line 1112 of file vdbeapi.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, SQLITE_OK, and vdbeUnbind().
Referenced by DbObjCmd(), FUNC(), and term_insert().
int sqlite3_bind_parameter_count (sqlite3_stmt * pStmt)
Definition at line 1170 of file vdbeapi.c.
References Vdbe::nVar.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_bind_parameter_index (sqlite3_stmt * pStmt, const char * zName)
Definition at line 1218 of file vdbeapi.c.
References Vdbe::azVar, createVarMap(), and Vdbe::nVar.
const char* sqlite3_bind_parameter_name (sqlite3_stmt * pStmt, int i)
Definition at line 1204 of file vdbeapi.c.
References Vdbe::azVar, createVarMap(), and Vdbe::nVar.
Referenced by DbObjCmd(), and FUNC().
int sqlite3_bind_text (sqlite3_stmt * pStmt, int i, const char * zData, int nData, void(*)(void *) xDel)
Definition at line 1121 of file vdbeapi.c.
References bindText(), and SQLITE_UTF8.
Referenced by db_get(), db_set(), DbObjCmd(), do_meta_command(), FUNC(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_keypress(), log_db_log_mark(), log_db_log_position(), log_db_log_profile(), log_db_log_smsevent(), log_text_to_db(), term_insert(), term_select(), and term_select_all().
int sqlite3_bind_text16 (sqlite3_stmt * pStmt, int i, const void * zData, int nData, void(*)(void *) xDel)
Definition at line 1131 of file vdbeapi.c.
References bindText(), and SQLITE_UTF16NATIVE.
int sqlite3_bind_value (sqlite3_stmt * pStmt, int i, const sqlite3_value * pValue)
Definition at line 1141 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, ENC, sqlite3::mutex, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemCopy(), SQLITE_OK, and vdbeUnbind().
Referenced by content_insert(), and content_update().
int sqlite3_bind_zeroblob (sqlite3_stmt * pStmt, int i, int n)
Definition at line 1155 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, sqlite3::mutex, sqlite3_mutex_leave, sqlite3VdbeMemSetZeroBlob(), SQLITE_OK, and vdbeUnbind().
int sqlite3_clear_bindings (sqlite3_stmt * pStmt)
Definition at line 245 of file vdbeapi.c.
References Vdbe::aVar, Mem::flags, MEM_Null, Vdbe::nVar, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeMemRelease(), and SQLITE_OK.
const void* sqlite3_column_blob (sqlite3_stmt * pStmt, int i)
Definition at line 800 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_blob().
Referenced by DbObjCmd(), FUNC(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), optimizeFunc(), push_column(), term_select(), term_select_all(), and termSelect().
int sqlite3_column_bytes (sqlite3_stmt * pStmt, int i)
Definition at line 810 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_bytes().
Referenced by DbObjCmd(), l_sqlite3_column_text_or_blob(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), optimizeFunc(), push_column(), snippetAllOffsets(), snippetText(), term_select(), term_select_all(), and termSelect().
int sqlite3_column_bytes16 (sqlite3_stmt * pStmt, int i)
Definition at line 815 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_bytes16().
int sqlite3_column_count (sqlite3_stmt * pStmt)
Definition at line 720 of file vdbeapi.c.
References Vdbe::nResColumn.
Referenced by columnName(), computeColumnNames(), DbObjCmd(), do_meta_command(), FUNC(), and sqlite3_exec().
const char* sqlite3_column_decltype (sqlite3_stmt * pStmt, int N)
Definition at line 945 of file vdbeapi.c.
References COLNAME_DECLTYPE, columnName(), and sqlite3_value_text().
Referenced by FUNC().
const void* sqlite3_column_decltype16 (sqlite3_stmt * pStmt, int N)
Definition at line 950 of file vdbeapi.c.
References COLNAME_DECLTYPE, columnName(), and sqlite3_value_text16().
double sqlite3_column_double (sqlite3_stmt * pStmt, int i)
Definition at line 820 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_double().
Referenced by DbObjCmd(), FUNC(), and push_column().
int sqlite3_column_int (sqlite3_stmt * pStmt, int i)
Definition at line 825 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_int().
Referenced by FUNC(), push_column(), segdir_count(), and segdir_max_index().
sqlite_int64 sqlite3_column_int64 (sqlite3_stmt * pStmt, int i)
Definition at line 830 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_int64().
Referenced by DbObjCmd(), fulltextRowid(), leavesReadersInit(), optimizeFunc(), segdir_span(), term_select(), and termSelect().
const char* sqlite3_column_name (sqlite3_stmt * pStmt, int N)
Definition at line 920 of file vdbeapi.c.
References COLNAME_NAME, columnName(), and sqlite3_value_text().
Referenced by computeColumnNames(), FUNC(), l_sqlite3_row_mode(), and sqlite3_exec().
const void* sqlite3_column_name16 (sqlite3_stmt * pStmt, int N)
Definition at line 925 of file vdbeapi.c.
References COLNAME_NAME, columnName(), and sqlite3_value_text16().
const unsigned char* sqlite3_column_text (sqlite3_stmt * pStmt, int i)
Definition at line 835 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_text().
Referenced by content_select(), db_get(), DbObjCmd(), dump_callback(), execExecSql(), FUNC(), push_column(), run_table_dump_query(), snippetAllOffsets(), snippetText(), and sqlite3_exec().
const void* sqlite3_column_text16 (sqlite3_stmt * pStmt, int i)
Definition at line 850 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_text16().
int sqlite3_column_type (sqlite3_stmt * pStmt, int i)
Definition at line 856 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), and sqlite3_value_type().
Referenced by content_select(), DbObjCmd(), FUNC(), push_column(), segdir_max_index(), segdir_span(), and sqlite3_exec().
sqlite3_value* sqlite3_column_value (sqlite3_stmt * pStmt, int i)
Definition at line 840 of file vdbeapi.c.
References columnMallocFailure(), columnMem(), Mem::flags, MEM_Ephem, and MEM_Static.
Referenced by fulltextColumn().
sqlite3* sqlite3_context_db_handle (sqlite3_context * p)
Definition at line 589 of file vdbeapi.c.
References Mem::db, sqlite3_context::pFunc, and sqlite3_context::s.
Referenced by attachFunc(), changes(), contextMalloc(), detachFunc(), groupConcatStep(), last_insert_rowid(), likeFunc(), loadExt(), optimizeFunc(), renameTableFunc(), renameTriggerFunc(), replaceFunc(), setDateTimeToCurrent(), strftimeFunc(), substrFunc(), and total_changes().
int sqlite3_data_count (sqlite3_stmt * pStmt)
Definition at line 729 of file vdbeapi.c.
References Vdbe::nResColumn, and Vdbe::pResultSet.
Referenced by columnMem(), FUNC(), and l_sqlite3_row_mode().
sqlite3* sqlite3_db_handle (sqlite3_stmt * pStmt)
Definition at line 1278 of file vdbeapi.c.
int sqlite3_expired (sqlite3_stmt * pStmt)
Definition at line 186 of file vdbeapi.c.
References Vdbe::expired.
int sqlite3_finalize (sqlite3_stmt * pStmt)
Definition at line 201 of file vdbeapi.c.
References Vdbe::db, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeFinalize(), SQLITE_OK, and stmtLruRemove.
Referenced by DbObjCmd(), destroy_sql_statements(), do_meta_command(), dump_callback(), execExecSql(), execSql(), flushStmtCache(), fulltext_vtab_destroy(), fulltextClose(), fulltextFilter(), FUNC(), leavesReaderDestroy(), run_table_dump_query(), sql_step_statement(), sqlite3_blob_close(), sqlite3_blob_open(), sqlite3_declare_vtab(), sqlite3_exec(), and sqlite3Prepare().
void* sqlite3_get_auxdata (sqlite3_context * pCtx, int iArg)
Definition at line 646 of file vdbeapi.c.
References VdbeFunc::apAux, Mem::db, sqlite3::mutex, VdbeFunc::nAux, VdbeFunc::AuxData::pAux, sqlite3_context::pVdbeFunc, sqlite3_context::s, and sqlite3_mutex_held.
Referenced by icuRegexpFunc().
sqlite3_stmt* sqlite3_next_stmt (sqlite3 * pDb, sqlite3_stmt * pStmt)
Definition at line 1288 of file vdbeapi.c.
References sqlite3::mutex, sqlite3::pVdbe, sqlite3_mutex_enter, and sqlite3_mutex_leave.
int sqlite3_reset (sqlite3_stmt * pStmt)
Definition at line 226 of file vdbeapi.c.
References Vdbe::db, sqlite3::errMask, sqlite3::mutex, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeMakeReady(), sqlite3VdbeReset(), SQLITE_OK, and stmtLruAdd.
Referenced by db_get(), db_set(), DbObjCmd(), do_meta_command(), fulltextFilter(), fulltextNext(), FUNC(), leavesReaderReset(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), sql_get_leaf_statement(), sql_get_statement(), and sqlite3_step().
void sqlite3_result_blob (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 314 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetStr().
Referenced by fulltextColumn(), FUNC(), randomBlob(), scalarFunc(), substrFunc(), and tclSqlFunc().
void sqlite3_result_double (sqlite3_context * pCtx, double rVal)
Definition at line 324 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetDouble().
Referenced by absFunc(), avgFinalize(), FUNC(), juliandayFunc(), roundFunc(), sumFinalize(), tclSqlFunc(), and totalFinalize().
void sqlite3_result_error (sqlite3_context * pCtx, const char * z, int n)
Definition at line 328 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), SQLITE_ERROR, SQLITE_TRANSIENT, and SQLITE_UTF8.
Referenced by absFunc(), attachFunc(), detachFunc(), FUNC(), func_callback_wrapper(), icuFunctionError(), icuLikeFunc(), icuLoadCollation(), likeFunc(), loadExt(), optimizeFunc(), scalarFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3InvalidFunction(), sumFinalize(), and tclSqlFunc().
void sqlite3_result_error16 (sqlite3_context * pCtx, const void * z, int n)
Definition at line 334 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), SQLITE_ERROR, SQLITE_TRANSIENT, and SQLITE_UTF16NATIVE.
void sqlite3_result_error_code (sqlite3_context * pCtx, int errCode)
Definition at line 398 of file vdbeapi.c.
References sqlite3_context::isError.
Referenced by attachFunc().
void sqlite3_result_error_nomem (sqlite3_context * pCtx)
Definition at line 411 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mallocFailed, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetNull(), and SQLITE_NOMEM.
Referenced by contextMalloc(), groupConcatFinalize(), replaceFunc(), and strftimeFunc().
void sqlite3_result_error_toobig (sqlite3_context * pCtx)
Definition at line 403 of file vdbeapi.c.
References Mem::db, sqlite3_context::isError, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), SQLITE_STATIC, SQLITE_TOOBIG, and SQLITE_UTF8.
Referenced by contextMalloc(), groupConcatFinalize(), replaceFunc(), strftimeFunc(), and zeroblobFunc().
void sqlite3_result_int (sqlite3_context * pCtx, int iVal)
Definition at line 340 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetInt64().
Referenced by changes(), FUNC(), icuLikeFunc(), icuRegexpFunc(), lengthFunc(), likeFunc(), tclSqlFunc(), and total_changes().
void sqlite3_result_int64 (sqlite3_context * pCtx, i64 iVal)
Definition at line 344 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetInt64().
Referenced by absFunc(), countFinalize(), last_insert_rowid(), randomFunc(), sumFinalize(), and tclSqlFunc().
void sqlite3_result_null (sqlite3_context * pCtx)
Definition at line 348 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetNull().
Referenced by absFunc(), FUNC(), and lengthFunc().
void sqlite3_result_text (sqlite3_context * pCtx, const char * z, int n, void(*)(void *) xDel)
Definition at line 352 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF8.
Referenced by dateFunc(), datetimeFunc(), FUNC(), groupConcatFinalize(), hexFunc(), lowerFunc(), optimizeFunc(), quoteFunc(), renameTableFunc(), renameTriggerFunc(), replaceFunc(), shellstaticFunc(), snippetFunc(), snippetOffsetsFunc(), strftimeFunc(), substrFunc(), tclSqlFunc(), timeFunc(), trimFunc(), typeofFunc(), upperFunc(), and versionFunc().
void sqlite3_result_text16 (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 362 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF16NATIVE.
Referenced by icuCaseFunc16().
void sqlite3_result_text16be (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 371 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF16BE.
void sqlite3_result_text16le (sqlite3_context * pCtx, const void * z, int n, void(*)(void *) xDel)
Definition at line 380 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, sqlite3VdbeMemSetStr(), and SQLITE_UTF16LE.
void sqlite3_result_value (sqlite3_context * pCtx, sqlite3_value * pValue)
Definition at line 390 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemCopy().
Referenced by fulltextColumn(), FUNC(), ifnullFunc(), minMaxFinalize(), minmaxFunc(), nullifFunc(), and quoteFunc().
void sqlite3_result_zeroblob (sqlite3_context * pCtx, int n)
Definition at line 394 of file vdbeapi.c.
References Mem::db, sqlite3::mutex, sqlite3_context::s, sqlite3_mutex_held, and sqlite3VdbeMemSetZeroBlob().
Referenced by zeroblobFunc().
void sqlite3_set_auxdata (sqlite3_context * pCtx, int iArg, void * pAux, void(*)(void *) xDelete)
Definition at line 662 of file vdbeapi.c.
References VdbeFunc::apAux, Mem::db, sqlite3::mutex, VdbeFunc::nAux, sqlite3_context::pFunc, VdbeFunc::pFunc, sqlite3_context::pVdbeFunc, sqlite3_context::s, sqlite3_mutex_held, sqlite3DbRealloc(), and VdbeFunc::AuxData::xDelete.
Referenced by icuRegexpFunc().
int sqlite3_step (sqlite3_stmt * pStmt)
Definition at line 538 of file vdbeapi.c.
References Vdbe::db, db, Vdbe::expired, sqlite3::mallocFailed, sqlite3::mutex, sqlite3::pErr, Vdbe::rc, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_reset(), sqlite3_value_text(), sqlite3ApiExit(), sqlite3DbFree(), sqlite3DbStrDup(), sqlite3Step(), SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_SCHEMA, vdbeReprepare, Vdbe::zErrMsg, and Vdbe::zSql.
Referenced by block_insert(), content_exists(), content_select(), db_get(), db_set(), DbObjCmd(), do_meta_command(), dump_callback(), execExecSql(), execSql(), fulltextNext(), FUNC(), leavesReaderInit(), leavesReadersInit(), leavesReaderStep(), loadAndGetChildrenContaining(), log_db_log_appfocus(), log_db_log_appmessage(), log_db_log_callstatus(), log_db_log_cellid(), log_db_log_httpurl(), log_db_log_inactivity(), log_db_log_indicator(), log_db_log_keypress(), log_db_log_light(), log_db_log_mark(), log_db_log_musicplayer(), log_db_log_musictrack(), log_db_log_position(), log_db_log_profile(), log_db_log_proximity(), log_db_log_smsevent(), log_db_log_tap(), log_text_to_db(), optimizeFunc(), run_table_dump_query(), segdir_count(), segdir_max_index(), segdir_span(), sql_single_step(), sql_step_statement(), sqlite3_blob_open(), sqlite3_exec(), term_select(), and termSelect().
int sqlite3_stmt_status (sqlite3_stmt * pStmt, int op, int resetFlag)
Definition at line 1303 of file vdbeapi.c.
References Vdbe::aCounter.
Referenced by DbObjCmd().
int sqlite3_transfer_bindings (sqlite3_stmt * pFromStmt, sqlite3_stmt * pToStmt)
Definition at line 1267 of file vdbeapi.c.
References sqlite3TransferBindings().
void* sqlite3_user_data (sqlite3_context * p)
Definition at line 580 of file vdbeapi.c.
References sqlite3_context::pFunc, and FuncDef::pUserData.
Referenced by func_callback_wrapper(), icuCaseFunc16(), icuLoadCollation(), likeFunc(), minmaxFunc(), minmaxStep(), scalarFunc(), tclSqlFunc(), and trimFunc().
const void* sqlite3_value_blob (sqlite3_value * pVal)
Definition at line 266 of file vdbeapi.c.
References Mem::flags, MEM_Blob, MEM_Str, sqlite3_value_text(), sqlite3VdbeMemExpandBlob(), and Mem::z.
Referenced by attachFunc(), FUNC(), hexFunc(), optimizeFunc(), quoteFunc(), scalarFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_column_blob(), substrFunc(), and tclSqlFunc().
int sqlite3_value_bytes (sqlite3_value * pVal)
Definition at line 277 of file vdbeapi.c.
References sqlite3ValueBytes(), and SQLITE_UTF8.
Referenced by attachFunc(), FUNC(), groupConcatStep(), hexFunc(), icuLikeFunc(), lengthFunc(), likeFunc(), lowerFunc(), optimizeFunc(), quoteFunc(), replaceFunc(), scalarFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_column_bytes(), substrFunc(), tclSqlFunc(), trimFunc(), and upperFunc().
int sqlite3_value_bytes16 (sqlite3_value * pVal)
Definition at line 280 of file vdbeapi.c.
References sqlite3ValueBytes(), and SQLITE_UTF16NATIVE.
Referenced by icuCaseFunc16(), and sqlite3_column_bytes16().
double sqlite3_value_double (sqlite3_value * pVal)
Definition at line 283 of file vdbeapi.c.
References sqlite3VdbeRealValue().
Referenced by absFunc(), FUNC(), isDate(), roundFunc(), sqlite3_column_double(), sumStep(), and tclSqlFunc().
int sqlite3_value_int (sqlite3_value * pVal)
Definition at line 286 of file vdbeapi.c.
References sqlite3VdbeIntValue().
Referenced by FUNC(), randomBlob(), roundFunc(), sqlite3_column_int(), and substrFunc().
sqlite_int64 sqlite3_value_int64 (sqlite3_value * pVal)
Definition at line 289 of file vdbeapi.c.
References sqlite3VdbeIntValue().
Referenced by absFunc(), fulltextFilter(), fulltextUpdate(), sqlite3_column_int64(), sumStep(), tclSqlFunc(), and zeroblobFunc().
const unsigned char* sqlite3_value_text (sqlite3_value * pVal)
Definition at line 292 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF8.
Referenced by attachFunc(), detachFunc(), fulltextFilter(), FUNC(), groupConcatStep(), icuCaseFunc16(), icuLikeFunc(), icuLoadCollation(), insertTerms(), isDate(), lengthFunc(), likeFunc(), loadExt(), lowerFunc(), quoteFunc(), renameTableFunc(), renameTriggerFunc(), replaceFunc(), scalarFunc(), snippetFunc(), sqlite3_column_decltype(), sqlite3_column_name(), sqlite3_column_text(), sqlite3_errmsg(), sqlite3_step(), sqlite3_value_blob(), sqlite3VdbeExec(), strftimeFunc(), substrFunc(), tclSqlFunc(), trimFunc(), and upperFunc().
const void* sqlite3_value_text16 (sqlite3_value * pVal)
Definition at line 296 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF16NATIVE.
Referenced by icuCaseFunc16(), icuRegexpFunc(), sqlite3_column_decltype16(), sqlite3_column_name16(), sqlite3_column_text16(), and sqlite3_errmsg16().
const void* sqlite3_value_text16be (sqlite3_value * pVal)
Definition at line 299 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF16BE.
const void* sqlite3_value_text16le (sqlite3_value * pVal)
Definition at line 302 of file vdbeapi.c.
References sqlite3ValueText(), and SQLITE_UTF16LE.
int sqlite3_value_type (sqlite3_value * pVal)
Definition at line 306 of file vdbeapi.c.
References Mem::type.
Referenced by absFunc(), attachFunc(), countStep(), fulltextUpdate(), FUNC(), groupConcatStep(), ifnullFunc(), isDate(), lengthFunc(), lowerFunc(), minmaxFunc(), minmaxStep(), optimizeFunc(), quoteFunc(), roundFunc(), snippetFunc(), snippetOffsetsFunc(), sqlite3_column_type(), substrFunc(), tclSqlFunc(), trimFunc(), typeofFunc(), and upperFunc().
void sqlite3InvalidFunction (sqlite3_context * context, int argc, sqlite3_value ** argv)
Definition at line 602 of file vdbeapi.c.
References sqlite3_context::pFunc, sqlite3_free(), sqlite3_result_error(), sqlite3MPrintf(), and FuncDef::zName.
Referenced by sqlite3_overload_function().
static int sqlite3Step (Vdbe * p) [static]
Definition at line 427 of file vdbeapi.c.
References sqlite3::activeVdbeCnt, Vdbe::aOp, sqlite3::sqlite3InitInfo::busy, Vdbe::db, db, sqlite3::errCode, Vdbe::expired, Vdbe::explain, sqlite3::init, sqlite3::isInterrupted, Vdbe::magic, sqlite3::mallocFailed, Vdbe::nOp, OP_Trace, VdbeOp::opcode, VdbeOp::p4, Vdbe::pc, sqlite3::pProfileArg, sqlite3::pVfs, Vdbe::rc, Vdbe::readOnly, sqlite3ApiExit(), sqlite3OsCurrentTime(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3VdbeExec(), sqlite3VdbeList(), SQLITE_ERROR, SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_OK, SQLITE_ROW, SQLITE_SCHEMA, Vdbe::startTime, stmtLruRemove, sqlite3::u1, VDBE_MAGIC_RUN, sqlite3::writeVdbeCnt, sqlite3::xProfile, VdbeOp::z, and Vdbe::zSql.
Referenced by sqlite3_step().
int sqlite3TransferBindings (sqlite3_stmt * pFromStmt, sqlite3_stmt * pToStmt)
Definition at line 1241 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, Vdbe::magic, sqlite3::mutex, Vdbe::nVar, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3VdbeMemMove(), SQLITE_ERROR, SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_OK, VDBE_MAGIC_HALT, and VDBE_MAGIC_RUN.
Referenced by sqlite3_transfer_bindings(), and sqlite3Reprepare().
static int vdbeUnbind (Vdbe * p, int i) [static]
Definition at line 1023 of file vdbeapi.c.
References Vdbe::aVar, Vdbe::db, Mem::flags, Vdbe::magic, MEM_Null, sqlite3::mutex, Vdbe::nVar, Vdbe::pc, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3Error(), sqlite3VdbeMemRelease(), SQLITE_MISUSE, SQLITE_OK, SQLITE_RANGE, and VDBE_MAGIC_RUN.
Referenced by bindText(), sqlite3_bind_double(), sqlite3_bind_int64(), sqlite3_bind_null(), sqlite3_bind_value(), and sqlite3_bind_zeroblob().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1