ContextLogger2 Logger Daemon Internals: vdbeInt.h File Reference
vdbeInt.h File Reference
Classes
struct VdbeCursor
struct Mem
struct VdbeFunc
struct VdbeFunc::AuxData
struct sqlite3_context
struct Set
struct FifoPage
struct Fifo
struct Context
struct Vdbe
Defines
#define keyToInt(X) (X)
#define intToKey(X) (X)
#define CACHE_STALE 0
#define MEM_Null 0x0001
#define MEM_Str 0x0002
#define MEM_Int 0x0004
#define MEM_Real 0x0008
#define MEM_Blob 0x0010
#define MemSetTypeFlag(p, f) ((p)->flags = ((p)->flags&~(MEM_Int|MEM_Real|MEM_Null|MEM_Blob|MEM_Str))|f)
#define MEM_Term 0x0020
#define MEM_Dyn 0x0040
#define MEM_Static 0x0080
#define MEM_Ephem 0x0100
#define MEM_Agg 0x0400
#define MEM_Zero 0x0800
#define VDBE_MAGIC_INIT 0x26bceaa5
#define VDBE_MAGIC_RUN 0xbdf20da3
#define VDBE_MAGIC_HALT 0x519c2973
#define VDBE_MAGIC_DEAD 0xb606c3c8
Typedefs
typedef struct VdbeOp Op
typedef unsigned char Bool
typedef struct VdbeCursor VdbeCursor
typedef struct Set Set
typedef struct FifoPage FifoPage
typedef struct Fifo Fifo
typedef struct Context Context
Functions
void sqlite3VdbeFreeCursor (Vdbe *, VdbeCursor *)
void sqliteVdbePopStack (Vdbe *, int)
int sqlite3VdbeCursorMoveto (VdbeCursor *)
int sqlite3VdbeSerialTypeLen (u32)
u32 sqlite3VdbeSerialType (Mem *, int)
int sqlite3VdbeSerialPut (unsigned char *, int, Mem *, int)
int sqlite3VdbeSerialGet (const unsigned char *, u32, Mem *)
void sqlite3VdbeDeleteAuxData (VdbeFunc *, int)
int sqlite2BtreeKeyCompare (BtCursor *, const void *, int, int, int *)
int sqlite3VdbeIdxKeyCompare (VdbeCursor *, UnpackedRecord *, int *)
int sqlite3VdbeIdxRowid (BtCursor *, i64 *)
int sqlite3MemCompare (const Mem *, const Mem *, const CollSeq *)
int sqlite3VdbeExec (Vdbe *)
int sqlite3VdbeList (Vdbe *)
int sqlite3VdbeHalt (Vdbe *)
int sqlite3VdbeChangeEncoding (Mem *, int)
int sqlite3VdbeMemTooBig (Mem *)
int sqlite3VdbeMemCopy (Mem *, const Mem *)
void sqlite3VdbeMemShallowCopy (Mem *, const Mem *, int)
void sqlite3VdbeMemMove (Mem *, Mem *)
int sqlite3VdbeMemNulTerminate (Mem *)
int sqlite3VdbeMemSetStr (Mem *, const char *, int, u8, void(*)(void *))
void sqlite3VdbeMemSetInt64 (Mem *, i64)
void sqlite3VdbeMemSetDouble (Mem *, double)
void sqlite3VdbeMemSetNull (Mem *)
void sqlite3VdbeMemSetZeroBlob (Mem *, int)
int sqlite3VdbeMemMakeWriteable (Mem *)
int sqlite3VdbeMemStringify (Mem *, int)
i64 sqlite3VdbeIntValue (Mem *)
int sqlite3VdbeMemIntegerify (Mem *)
double sqlite3VdbeRealValue (Mem *)
void sqlite3VdbeIntegerAffinity (Mem *)
int sqlite3VdbeMemRealify (Mem *)
int sqlite3VdbeMemNumerify (Mem *)
int sqlite3VdbeMemFromBtree (BtCursor *, int, int, int, Mem *)
void sqlite3VdbeMemRelease (Mem *p)
void sqlite3VdbeMemReleaseExternal (Mem *p)
int sqlite3VdbeMemFinalize (Mem *, FuncDef *)
const char * sqlite3OpcodeName (int)
int sqlite3VdbeOpcodeHasProperty (int, int)
int sqlite3VdbeMemGrow (Mem *pMem, int n, int preserve)
int sqlite3VdbeMemTranslate (Mem *, u8)
int sqlite3VdbeMemHandleBom (Mem *pMem)
void sqlite3VdbeFifoInit (Fifo *, sqlite3 *)
int sqlite3VdbeFifoPush (Fifo *, i64)
int sqlite3VdbeFifoPop (Fifo *, i64 *)
void sqlite3VdbeFifoClear (Fifo *)
int sqlite3VdbeMemExpandBlob (Mem *)
Define Documentation
#define CACHE_STALE 0
Definition at line 101 of file vdbeInt.h.
Referenced by sqlite3VdbeCursorMoveto(), and sqlite3VdbeExec().
#define intToKey (X) (X)
Definition at line 28 of file vdbeInt.h.
Referenced by sqlite3VdbeExec().
#define keyToInt (X) (X)
Definition at line 27 of file vdbeInt.h.
Referenced by sqlite3VdbeCursorMoveto(), and sqlite3VdbeExec().
#define MEM_Agg 0x0400
Definition at line 163 of file vdbeInt.h.
Referenced by releaseMemArray(), sqlite3_aggregate_context(), sqlite3VdbeExec(), and sqlite3VdbeMemReleaseExternal().
#define MEM_Blob 0x0010
Definition at line 149 of file vdbeInt.h.
Referenced by sqlite3_value_blob(), sqlite3ValueBytes(), sqlite3ValueText(), sqlite3VdbeIntValue(), sqlite3VdbeMemCopy(), sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemSetZeroBlob(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTooBig(), sqlite3VdbeRealValue(), sqlite3VdbeSerialGet(), and sqlite3VdbeSerialType().
#define MEM_Dyn 0x0040
Definition at line 160 of file vdbeInt.h.
Referenced by releaseMemArray(), sqlite3Utf16to8(), sqlite3VdbeList(), sqlite3VdbeMemCopy(), sqlite3VdbeMemFinalize(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemGrow(), sqlite3VdbeMemReleaseExternal(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemShallowCopy(), and sqlite3VdbeMemTranslate().
#define MEM_Ephem 0x0100
Definition at line 162 of file vdbeInt.h.
Referenced by sqlite3_column_value(), sqlite3MemCompare(), sqlite3ValueText(), sqlite3VdbeMemCopy(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemGrow(), sqlite3VdbeMemShallowCopy(), sqlite3VdbeMemTranslate(), and sqlite3VdbeSerialGet().
#define MEM_Int 0x0004
Definition at line 147 of file vdbeInt.h.
Referenced by _storeTypeInfo(), applyAffinity(), applyNumericAffinity(), displayP4(), sqlite3MemCompare(), sqlite3VdbeExec(), sqlite3VdbeIntegerAffinity(), sqlite3VdbeIntValue(), sqlite3VdbeList(), sqlite3VdbeMemIntegerify(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemSetInt64(), sqlite3VdbeMemStringify(), sqlite3VdbeRealValue(), sqlite3VdbeSerialGet(), and sqlite3VdbeSerialType().
#define MEM_Null 0x0001
Definition at line 145 of file vdbeInt.h.
Referenced by _storeTypeInfo(), Cleanup(), columnMem(), displayP4(), releaseMemArray(), sqlite3_aggregate_context(), sqlite3_clear_bindings(), sqlite3MemCompare(), sqlite3ValueNew(), sqlite3ValueText(), sqlite3VdbeExec(), sqlite3VdbeList(), sqlite3VdbeMakeReady(), sqlite3VdbeMemFinalize(), sqlite3VdbeMemGrow(), sqlite3VdbeMemMove(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemSetNull(), sqlite3VdbeSerialGet(), sqlite3VdbeSerialType(), sqlite3VdbeSetNumCols(), and vdbeUnbind().
#define MEM_Real 0x0008
Definition at line 148 of file vdbeInt.h.
Referenced by _storeTypeInfo(), applyAffinity(), applyNumericAffinity(), displayP4(), sqlite3MemCompare(), sqlite3VdbeExec(), sqlite3VdbeIntegerAffinity(), sqlite3VdbeIntValue(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemRealify(), sqlite3VdbeMemSetDouble(), sqlite3VdbeMemStringify(), sqlite3VdbeRealValue(), sqlite3VdbeSerialGet(), and sqlite3VdbeSerialType().
#define MEM_Static 0x0080
Definition at line 161 of file vdbeInt.h.
Referenced by sqlite3_column_value(), sqlite3ValueText(), sqlite3VdbeList(), sqlite3VdbeMemCopy(), sqlite3VdbeMemGrow(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemShallowCopy(), and sqlite3VdbeMemTranslate().
#define MEM_Str 0x0002
Definition at line 146 of file vdbeInt.h.
Referenced by _storeTypeInfo(), applyAffinity(), applyNumericAffinity(), displayP4(), sqlite3_value_blob(), sqlite3MemCompare(), sqlite3Utf16to8(), sqlite3VdbeChangeEncoding(), sqlite3VdbeIntValue(), sqlite3VdbeList(), sqlite3VdbeMemCopy(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTooBig(), sqlite3VdbeMemTranslate(), sqlite3VdbeRealValue(), sqlite3VdbeSerialGet(), and sqlite3VdbeSerialType().
#define MEM_Term 0x0020
Definition at line 159 of file vdbeInt.h.
Referenced by sqlite3Utf16to8(), sqlite3VdbeExec(), sqlite3VdbeList(), sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemHandleBom(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTranslate(), and sqlite3VdbeSetColName().
#define MEM_Zero 0x0800
Definition at line 164 of file vdbeInt.h.
Referenced by sqlite3ValueBytes(), sqlite3VdbeExec(), sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemSetZeroBlob(), sqlite3VdbeMemStringify(), sqlite3VdbeMemTooBig(), sqlite3VdbeSerialPut(), and sqlite3VdbeSerialType().
#define MemSetTypeFlag (p, f) ((p)->flags = ((p)->flags&~(MEM_Int|MEM_Real|MEM_Null|MEM_Blob|MEM_Str))|f)
Definition at line 151 of file vdbeInt.h.
Referenced by applyNumericAffinity(), Cleanup(), setTypeFlag(), and sqlite3VdbeExec().
#define VDBE_MAGIC_DEAD 0xb606c3c8
Definition at line 351 of file vdbeInt.h.
Referenced by sqlite3VdbeDelete().
#define VDBE_MAGIC_HALT 0x519c2973
Definition at line 350 of file vdbeInt.h.
Referenced by sqlite3TransferBindings(), sqlite3VdbeFinalize(), and sqlite3VdbeHalt().
#define VDBE_MAGIC_INIT 0x26bceaa5
Definition at line 348 of file vdbeInt.h.
Referenced by sqlite3VdbeAddOp3(), sqlite3VdbeAddOpList(), sqlite3VdbeChangeP1(), sqlite3VdbeChangeP2(), sqlite3VdbeChangeP3(), sqlite3VdbeChangeP4(), sqlite3VdbeChangeP5(), sqlite3VdbeCreate(), sqlite3VdbeCurrentAddr(), sqlite3VdbeFinalize(), sqlite3VdbeGetOp(), sqlite3VdbeMakeLabel(), sqlite3VdbeMakeReady(), sqlite3VdbeReset(), and sqlite3VdbeResolveLabel().
#define VDBE_MAGIC_RUN 0xbdf20da3
Definition at line 349 of file vdbeInt.h.
Referenced by sqlite3Step(), sqlite3TransferBindings(), sqlite3VdbeExec(), sqlite3VdbeFinalize(), sqlite3VdbeHalt(), sqlite3VdbeList(), sqlite3VdbeMakeReady(), and vdbeUnbind().
Typedef Documentation
typedef unsigned char Bool
Definition at line 41 of file vdbeInt.h.
typedef struct Context Context
Definition at line 260 of file vdbeInt.h.
typedef struct Fifo Fifo
Definition at line 243 of file vdbeInt.h.
typedef struct FifoPage FifoPage
Definition at line 228 of file vdbeInt.h.
typedef struct VdbeOp Op
Definition at line 36 of file vdbeInt.h.
typedef struct Set Set
Definition at line 218 of file vdbeInt.h.
typedef struct VdbeCursor VdbeCursor
Definition at line 96 of file vdbeInt.h.
Function Documentation
int sqlite2BtreeKeyCompare (BtCursor * , const void * , int , int , int *)
int sqlite3MemCompare (const Mem * , const Mem * , const CollSeq *)
Definition at line 664 of file vdbemem.c.
References CollSeq::enc, Mem::enc, Mem::flags, Mem::i, MEM_Ephem, MEM_Int, MEM_Null, MEM_Real, MEM_Str, Mem::n, CollSeq::pUser, Mem::r, sqlite3ValueText(), sqlite3VdbeMemRelease(), sqlite3VdbeMemShallowCopy(), SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, Mem::u, CollSeq::xCmp, and Mem::z.
Referenced by minmaxFunc(), minmaxStep(), nullifFunc(), sqlite3VdbeExec(), and sqlite3VdbeRecordCompare().
const char* sqlite3OpcodeName (int)
Definition at line 4 of file opcodes.c.
Referenced by sqlite3VdbeList().
int sqlite3VdbeChangeEncoding (Mem * , int)
Definition at line 43 of file vdbemem.c.
References Mem::db, Mem::enc, Mem::flags, MEM_Str, sqlite3::mutex, sqlite3_mutex_held, sqlite3VdbeMemTranslate(), SQLITE_ERROR, SQLITE_NOMEM, and SQLITE_OK.
Referenced by applyNumericAffinity(), bindText(), sqlite3_bind_value(), sqlite3Utf16to8(), sqlite3ValueText(), sqlite3VdbeExec(), sqlite3VdbeIntValue(), sqlite3VdbeMemStringify(), and sqlite3VdbeRealValue().
int sqlite3VdbeCursorMoveto (VdbeCursor *)
Definition at line 1855 of file vdbeaux.c.
References CACHE_STALE, VdbeCursor::cacheStatus, VdbeCursor::deferredMoveto, VdbeCursor::isTable, keyToInt, VdbeCursor::lastRowid, VdbeCursor::movetoTarget, VdbeCursor::nullRow, VdbeCursor::pCursor, VdbeCursor::rowidIsValid, sqlite3BtreeCursorHasMoved(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeNext(), and SQLITE_OK.
Referenced by sqlite3VdbeExec().
void sqlite3VdbeDeleteAuxData (VdbeFunc * , int)
Definition at line 1797 of file vdbeaux.c.
References VdbeFunc::apAux, VdbeFunc::nAux, and VdbeFunc::AuxData::xDelete.
Referenced by freeP4(), and sqlite3VdbeExec().
int sqlite3VdbeExec (Vdbe *)
Definition at line 533 of file vdbe.c.
References KeyInfo::aColl, Vdbe::aCounter, sqlite3::activeVdbeCnt, sqlite3::aDb, VdbeOp::ai, sqlite3::aLimit, allocateCursor(), UnpackedRecord::aMem, Vdbe::aMem, Vdbe::aMutex, VdbeCursor::aOffset, Vdbe::aOp, Vdbe::apArg, Vdbe::apCsr, applyAffinity(), applyNumericAffinity(), VdbeCursor::aRow, KeyInfo::aSortOrder, VdbeCursor::atFirst, VdbeCursor::aType, sqlite3::autoCommit, Vdbe::aVar, BTREE_INTKEY, BTREE_LEAFDATA, BTREE_ZERODATA, Vdbe::btreeMask, sqlite3::sqlite3InitInfo::busy, sqlite3::busyHandler, CACHE_STALE, Vdbe::cacheCtr, VdbeCursor::cacheStatus, CHECK_FOR_INTERRUPT, Vdbe::contextStack, Vdbe::contextStackDepth, Vdbe::contextStackTop, Fifo::db, InitData::db, Mem::db, Vdbe::db, db, DB_SchemaLoaded, DbHasProperty, Deephemeralize, VdbeCursor::deferredMoveto, KeyInfo::enc, Mem::enc, ENC, VdbeCursor::ephemPseudoTable, Vdbe::errorAction, ExpandBlob, Vdbe::expired, Vdbe::explain, Schema::file_format, UnpackedRecord::flags, FuncDef::flags, Mem::flags, sqlite3::flags, getVarint32, VdbeOp::i, Mem::i, InitData::iDb, VdbeCursor::iDb, VdbeCursor::iKey, sqlite3::init, intToKey, Vdbe::inVtabMethod, sqlite3_context::isError, VdbeCursor::isIndex, sqlite3::isInterrupted, VdbeCursor::isTable, keyToInt, Context::lastRowid, sqlite3::lastRowid, VdbeCursor::lastRowid, sqlite3::magic, Vdbe::magic, sqlite3::mallocFailed, MASTER_ROOT, MAX_ROWID, MEM_Agg, MEM_Int, MEM_Null, MEM_Real, MEM_Term, MEM_Zero, MemSetTypeFlag, Vdbe::minWriteFileFormat, VdbeCursor::movetoTarget, Mem::n, BusyHandler::nBusy, Vdbe::nCallback, Context::nChange, Vdbe::nChange, Vdbe::nCursor, VdbeCursor::nData, sqlite3::nDb, VdbeCursor::nextRowid, VdbeCursor::nextRowidValid, UnpackedRecord::nField, VdbeCursor::nField, Vdbe::nMem, Vdbe::nOp, sqlite3::nProgressOps, Vdbe::nResColumn, VdbeCursor::nullRow, OE_Abort, OP_Add, OP_AddImm, OP_Affinity, OP_AggFinal, OP_AggStep, OP_And, OP_AutoCommit, OP_BitAnd, OP_BitNot, OP_BitOr, OP_Blob, OP_Clear, OP_Close, OP_CollSeq, OP_Column, OP_Compare, OP_Concat, OP_ContextPop, OP_ContextPush, OP_Copy, OP_CreateIndex, OP_CreateTable, OP_Delete, OP_Destroy, OP_Divide, OP_DropIndex, OP_DropTable, OP_DropTrigger, OP_Eq, OP_Expire, OP_FifoRead, OP_FifoWrite, OP_ForceInt, OP_Found, OP_Function, OP_Ge, OP_Gosub, OP_Goto, OP_Gt, OP_Halt, OP_IdxDelete, OP_IdxGE, OP_IdxInsert, OP_IdxLT, OP_IdxRowid, OP_If, OP_IfNeg, OP_IfNot, OP_IfPos, OP_IfZero, OP_IncrVacuum, OP_Insert, OP_Int64, OP_Integer, OP_IntegrityCk, OP_IsNull, OP_IsUnique, OP_Jump, OP_Last, OP_Le, OP_LoadAnalysis, OP_Lt, OP_MakeRecord, OP_MemMax, OP_Move, OP_MoveGe, OP_MoveGt, OP_MoveLe, OP_MoveLt, OP_Multiply, OP_MustBeInt, OP_Ne, OP_NewRowid, OP_Next, OP_Not, OP_NotExists, OP_NotFound, OP_NotNull, OP_Null, OP_NullRow, OP_OpenEphemeral, OP_OpenPseudo, OP_OpenRead, OP_OpenWrite, OP_Or, OP_Pagecount, OP_ParseSchema, OP_Permutation, OP_Prev, OP_ReadCookie, OP_Real, OP_RealAffinity, OP_Remainder, OP_ResetCount, OP_ResultRow, OP_Return, OP_Rewind, OP_RowData, OP_Rowid, OP_RowKey, OP_SCopy, OP_Sequence, OP_SetCookie, OP_SetNumColumns, OP_ShiftLeft, OP_ShiftRight, OP_Sort, OP_Statement, OP_String, OP_String8, OP_Subtract, OP_TableLock, OP_ToBlob, OP_ToInt, OP_ToNumeric, OP_ToReal, OP_ToText, OP_Trace, OP_Transaction, OP_Vacuum, OP_Variable, OP_VBegin, OP_VColumn, OP_VCreate, OP_VDestroy, OP_VerifyCookie, OP_VFilter, OP_VNext, OP_VOpen, OP_VRename, OP_VRowid, OP_VUpdate, OP_Yield, VdbeOp::opcode, Vdbe::openedStatement, OPFLAG_APPEND, OPFLAG_ISUPDATE, OPFLAG_LASTROWID, OPFLAG_NCHANGE, OPFLG_IN1, OPFLG_IN2, OPFLG_IN3, OPFLG_OUT2_PRERELEASE, OPFLG_OUT3, VdbeOp::p, VdbeOp::p1, VdbeOp::p2, VdbeOp::p3, VdbeOp::p4, P4_COLLSEQ, P4_DYNAMIC, P4_FUNCDEF, P4_INT32, P4_INTARRAY, P4_KEYINFO, P4_MEM, P4_VDBEFUNC, P4_VTAB, VdbeOp::p4type, VdbeOp::p5, VdbeCursor::payloadSize, VdbeCursor::pBt, Db::pBt, Vdbe::pc, VdbeOp::pColl, sqlite3_context::pColl, VdbeCursor::pCursor, VdbeCursor::pData, VdbeFunc::pFunc, VdbeOp::pFunc, sqlite3_context::pFunc, VdbeOp::pI64, UnpackedRecord::pKeyInfo, VdbeCursor::pKeyInfo, VdbeOp::pKeyInfo, sqlite3_context::pMem, VdbeOp::pMem, VdbeCursor::pModule, sqlite3_vtab::pModule, Vdbe::pNext, sqlite3::pProgressArg, VdbeOp::pReal, Vdbe::pResultSet, sqlite3::priorNewRowid, Db::pSchema, VdbeCursor::pseudoTable, sqlite3::pTraceArg, sqlite3::pUpdateArg, putVarint32, sqlite3::pVdbe, VdbeOp::pVdbeFunc, sqlite3_context::pVdbeFunc, sqlite3_vtab_cursor::pVtab, VdbeOp::pVtab, VdbeCursor::pVtabCursor, InitData::pzErrMsg, Mem::r, InitData::rc, Vdbe::rc, REGISTER_TRACE, VdbeCursor::rowidIsValid, sqlite3_context::s, Schema::schema_cookie, SCHEMA_TABLE, VdbeCursor::seqCount, Context::sFifo, Vdbe::sFifo, SMALLEST_INT64, sqlite3_exec(), sqlite3_free(), sqlite3_interrupt(), sqlite3_randomness(), sqlite3_value_text(), sqlite3AnalysisLoad(), sqlite3BeginBenignMalloc(), sqlite3BtreeBeginStmt(), sqlite3BtreeBeginTrans(), sqlite3BtreeClearCursor(), sqlite3BtreeClearTable(), sqlite3BtreeCreateTable(), sqlite3BtreeCursor(), sqlite3BtreeData(), sqlite3BtreeDataFetch(), sqlite3BtreeDataSize(), sqlite3BtreeDelete(), sqlite3BtreeDropTable(), sqlite3BtreeEof(), sqlite3BtreeFactory(), sqlite3BtreeFirst(), sqlite3BtreeFlags(), sqlite3BtreeGetMeta(), sqlite3BtreeIncrVacuum(), sqlite3BtreeInsert(), sqlite3BtreeIntegrityCheck(), sqlite3BtreeIsInStmt(), sqlite3BtreeIsInTrans(), sqlite3BtreeKey(), sqlite3BtreeKeyFetch(), sqlite3BtreeKeySize(), sqlite3BtreeLast(), sqlite3BtreeLockTable(), sqlite3BtreeMovetoUnpacked(), sqlite3BtreeMutexArrayEnter, sqlite3BtreeMutexArrayLeave, sqlite3BtreeNext(), sqlite3BtreePager(), sqlite3BtreePrevious(), sqlite3BtreeUpdateMeta(), sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3DbReallocOrFree(), sqlite3DbStrDup(), sqlite3EndBenignMalloc(), sqlite3ErrStr(), sqlite3ExpirePreparedStatements(), sqlite3Hwtime(), sqlite3InitCallback(), sqlite3IsNaN(), sqlite3Malloc(), sqlite3MemCompare(), sqlite3MPrintf(), sqlite3PagerPagecount(), sqlite3ResetInternalSchema(), sqlite3RollbackAll(), sqlite3RootPageMoved(), sqlite3RunVacuum(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3SetString(), sqlite3UnlinkAndDeleteIndex(), sqlite3UnlinkAndDeleteTable(), sqlite3UnlinkAndDeleteTrigger(), sqlite3VarintLen(), sqlite3VdbeChangeEncoding(), sqlite3VdbeCursorMoveto(), sqlite3VdbeDeleteAuxData(), sqlite3VdbeDeleteUnpackedRecord(), sqlite3VdbeFifoClear(), sqlite3VdbeFifoInit(), sqlite3VdbeFifoPop(), sqlite3VdbeFifoPush(), sqlite3VdbeFreeCursor(), sqlite3VdbeHalt(), sqlite3VdbeIdxKeyCompare(), sqlite3VdbeIdxRowid(), sqlite3VdbeIntegerAffinity(), sqlite3VdbeIntValue(), sqlite3VdbeIOTraceSql, sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemFinalize(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemGrow(), sqlite3VdbeMemIntegerify(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemMove(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemNumerify(), sqlite3VdbeMemRealify(), sqlite3VdbeMemRelease(), sqlite3VdbeMemReleaseExternal(), sqlite3VdbeMemSetNull(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemShallowCopy(), sqlite3VdbeMemTooBig(), sqlite3VdbeRealValue(), sqlite3VdbeRecordUnpack(), sqlite3VdbeSerialGet(), sqlite3VdbeSerialPut(), sqlite3VdbeSerialType(), sqlite3VdbeSerialTypeLen(), sqlite3VdbeSetChanges(), sqlite3VtabBegin(), sqlite3VtabCallCreate(), sqlite3VtabCallDestroy(), sqlite3VtabLock(), sqlite3VtabUnlock(), SQLITE_AFF_MASK, SQLITE_AFF_NUMERIC, SQLITE_AFF_TEXT, SQLITE_BUSY, SQLITE_CORRUPT_BKPT, SQLITE_DEFAULT_TEMP_CACHE_SIZE, SQLITE_DELETE, SQLITE_DONE, SQLITE_EMPTY, SQLITE_ERROR, SQLITE_FULL, SQLITE_FUNC_NEEDCOLL, SQLITE_INSERT, SQLITE_InternChanges, SQLITE_INTERRUPT, SQLITE_IOERR_NOMEM, SQLITE_JUMPIFNULL, SQLITE_LIMIT_LENGTH, SQLITE_LOCKED, SQLITE_MAGIC_BUSY, SQLITE_MAX_LENGTH, SQLITE_MISMATCH, SQLITE_MISUSE, SQLITE_N_BTREE_META, SQLITE_NOMEM, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_DELETEONCLOSE, SQLITE_OPEN_EXCLUSIVE, SQLITE_OPEN_READWRITE, SQLITE_OPEN_TRANSIENT_DB, SQLITE_READONLY, SQLITE_ROW, SQLITE_SCHEMA, SQLITE_SqlTrace, SQLITE_STATIC, SQLITE_STMTSTATUS_SORT, SQLITE_STOREP2, SQLITE_TOOBIG, SQLITE_UPDATE, SQLITE_UTF8, SQLITE_VdbeListing, storeTypeInfo, Stringify, Mem::u, sqlite3::u1, UNPACKED_IGNORE_ROWID, UNPACKED_INCRKEY, UNPACKED_PREFIX_MATCH, UPDATE_MAX_BLOBSIZE, VdbeCursor::useRandomRowid, VDBE_MAGIC_RUN, sqlite3::writeVdbeCnt, sqlite3_module::xClose, sqlite3_module::xColumn, Mem::xDel, sqlite3_module::xEof, sqlite3_module::xFilter, FuncDef::xFunc, sqlite3_module::xNext, sqlite3_module::xOpen, sqlite3::xProgress, sqlite3_module::xRename, sqlite3_module::xRowid, FuncDef::xStep, sqlite3::xTrace, sqlite3_module::xUpdate, sqlite3::xUpdateCallback, Mem::z, VdbeOp::z, sqlite3_vtab::zErrMsg, Vdbe::zErrMsg, Mem::zMalloc, and Db::zName.
Referenced by sqlite3Step().
void sqlite3VdbeFifoClear (Fifo *)
Definition at line 123 of file vdbefifo.c.
References Fifo::db, Fifo::pFirst, FifoPage::pNext, sqlite3DbFree(), and sqlite3VdbeFifoInit().
Referenced by Cleanup(), and sqlite3VdbeExec().
void sqlite3VdbeFifoInit (Fifo * , sqlite3 *)
Definition at line 54 of file vdbefifo.c.
References Fifo::db.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeFifoClear().
int sqlite3VdbeFifoPop (Fifo * , i64 *)
Definition at line 90 of file vdbefifo.c.
References FifoPage::aSlot, Fifo::db, FifoPage::iRead, FifoPage::iWrite, Fifo::nEntry, FifoPage::nSlot, Fifo::pFirst, Fifo::pLast, FifoPage::pNext, sqlite3DbFree(), SQLITE_DONE, and SQLITE_OK.
Referenced by sqlite3VdbeExec().
int sqlite3VdbeFifoPush (Fifo * , i64)
Definition at line 64 of file vdbefifo.c.
References allocateFifoPage(), FifoPage::aSlot, Fifo::db, FIFOSIZE_FIRST, FifoPage::iWrite, Fifo::nEntry, FifoPage::nSlot, Fifo::pFirst, Fifo::pLast, FifoPage::pNext, SQLITE_NOMEM, and SQLITE_OK.
Referenced by sqlite3VdbeExec().
void sqlite3VdbeFreeCursor (Vdbe * , VdbeCursor *)
Definition at line 1107 of file vdbeaux.c.
References Vdbe::db, VdbeCursor::ephemPseudoTable, Vdbe::inVtabMethod, VdbeCursor::pBt, VdbeCursor::pCursor, VdbeCursor::pData, VdbeCursor::pModule, VdbeCursor::pVtabCursor, sqlite3BtreeClose(), sqlite3BtreeCloseCursor(), sqlite3DbFree(), sqlite3SafetyOff, sqlite3SafetyOn, and sqlite3_module::xClose.
Referenced by allocateCursor(), closeAllCursorsExceptActiveVtabs(), and sqlite3VdbeExec().
int sqlite3VdbeHalt (Vdbe *)
Definition at line 1518 of file vdbeaux.c.
References sqlite3::activeVdbeCnt, sqlite3::aDb, Vdbe::aMutex, sqlite3::autoCommit, Vdbe::changeCntOn, checkActiveVdbeCnt, closeAllCursorsExceptActiveVtabs(), Vdbe::db, Vdbe::errorAction, sqlite3::flags, invalidateCursorsOnModifiedBtrees(), Vdbe::magic, sqlite3::mallocFailed, Vdbe::nChange, sqlite3::nDb, OE_Abort, OE_Fail, Vdbe::openedStatement, Db::pBt, Vdbe::pc, Vdbe::rc, Vdbe::readOnly, sqlite3BtreeCommitStmt(), sqlite3BtreeMutexArrayEnter, sqlite3BtreeMutexArrayLeave, sqlite3BtreeRollbackStmt(), sqlite3CommitInternalChanges(), sqlite3DbFree(), sqlite3ResetInternalSchema(), sqlite3RollbackAll(), sqlite3VdbeSetChanges(), SQLITE_BUSY, SQLITE_CONSTRAINT, SQLITE_FULL, SQLITE_InternChanges, SQLITE_INTERRUPT, SQLITE_IOERR, SQLITE_IOERR_BLOCKED, SQLITE_NOMEM, SQLITE_OK, Vdbe::usesStmtJournal, VDBE_MAGIC_HALT, VDBE_MAGIC_RUN, vdbeCommit(), sqlite3::writeVdbeCnt, and Vdbe::zErrMsg.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeReset().
int sqlite3VdbeIdxKeyCompare (VdbeCursor * , UnpackedRecord * , int *)
Definition at line 2421 of file vdbeaux.c.
References Mem::db, UnpackedRecord::flags, Mem::flags, Mem::n, VdbeCursor::pCursor, sqlite3BtreeKeySize(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemRelease(), sqlite3VdbeRecordCompare(), SQLITE_OK, UNPACKED_IGNORE_ROWID, Mem::z, and Mem::zMalloc.
Referenced by sqlite3VdbeExec().
int sqlite3VdbeIdxRowid (BtCursor * , i64 *)
Definition at line 2379 of file vdbeaux.c.
References Mem::db, Mem::flags, getVarint32, Mem::i, Mem::n, sqlite3BtreeKeySize(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemRelease(), sqlite3VdbeSerialGet(), sqlite3VdbeSerialTypeLen(), SQLITE_CORRUPT_BKPT, SQLITE_OK, Mem::u, Mem::z, and Mem::zMalloc.
Referenced by sqlite3VdbeExec().
void sqlite3VdbeIntegerAffinity (Mem *)
Definition at line 384 of file vdbemem.c.
References Mem::db, doubleToInt64(), Mem::flags, Mem::i, MEM_Int, MEM_Real, sqlite3::mutex, Mem::r, sqlite3_mutex_held, and Mem::u.
Referenced by applyAffinity(), and sqlite3VdbeExec().
i64 sqlite3VdbeIntValue (Mem *)
Definition at line 330 of file vdbemem.c.
References Mem::db, doubleToInt64(), Mem::flags, Mem::i, MEM_Blob, MEM_Int, MEM_Real, MEM_Str, sqlite3::mutex, Mem::r, sqlite3_mutex_held, sqlite3Atoi64(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemNulTerminate(), SQLITE_UTF8, Mem::u, and Mem::z.
Referenced by sqlite3_value_int(), sqlite3_value_int64(), sqlite3VdbeExec(), and sqlite3VdbeMemIntegerify().
int sqlite3VdbeList (Vdbe *)
Definition at line 831 of file vdbeaux.c.
References Vdbe::aMem, Vdbe::aOp, Vdbe::db, db, displayP4(), Mem::enc, Vdbe::explain, Mem::flags, Mem::i, sqlite3::isInterrupted, sqlite3::magic, Vdbe::magic, sqlite3::mallocFailed, MEM_Dyn, MEM_Int, MEM_Null, MEM_Static, MEM_Str, MEM_Term, Mem::n, Vdbe::nMem, Vdbe::nOp, Vdbe::nResColumn, OP_Explain, VdbeOp::opcode, VdbeOp::p1, VdbeOp::p2, VdbeOp::p3, VdbeOp::p5, Vdbe::pc, Vdbe::pResultSet, Vdbe::rc, releaseMemArray(), sqlite3_snprintf(), sqlite3ErrStr(), sqlite3OpcodeName(), sqlite3SetString(), sqlite3VdbeMemGrow(), sqlite3VdbeMemSetStr(), SQLITE_BUSY, SQLITE_DONE, SQLITE_ERROR, SQLITE_INTEGER, SQLITE_INTERRUPT, SQLITE_MAGIC_BUSY, SQLITE_MISUSE, SQLITE_NOMEM, SQLITE_NULL, SQLITE_OK, SQLITE_ROW, SQLITE_TEXT, SQLITE_UTF8, Mem::type, Mem::u, sqlite3::u1, VDBE_MAGIC_RUN, Mem::z, and Vdbe::zErrMsg.
Referenced by sqlite3Step().
int sqlite3VdbeMemCopy (Mem * , const Mem *)
Definition at line 532 of file vdbemem.c.
References Mem::flags, MEM_Blob, MEM_Dyn, MEM_Ephem, MEM_Static, MEM_Str, MEMCELLSIZE, sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemReleaseExternal(), and SQLITE_OK.
Referenced by minmaxStep(), sqlite3_bind_value(), and sqlite3_result_value().
int sqlite3VdbeMemExpandBlob (Mem *)
Definition at line 143 of file vdbemem.c.
References Mem::db, Mem::flags, Mem::i, MEM_Blob, MEM_Term, MEM_Zero, sqlite3::mutex, Mem::n, sqlite3_mutex_held, sqlite3VdbeMemGrow(), SQLITE_NOMEM, SQLITE_OK, Mem::u, and Mem::z.
Referenced by sqlite3_value_blob(), and sqlite3VdbeExec().
int sqlite3VdbeMemFinalize (Mem * , FuncDef *)
Definition at line 238 of file vdbemem.c.
References Mem::db, Mem::flags, sqlite3_context::isError, MEM_Dyn, MEM_Null, sqlite3::mutex, Mem::pDef, sqlite3_context::pFunc, sqlite3_context::pMem, sqlite3_context::s, sqlite3_mutex_held, sqlite3DbFree(), SQLITE_ERROR, SQLITE_OK, Mem::u, Mem::xDel, FuncDef::xFinalize, and Mem::zMalloc.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeMemReleaseExternal().
int sqlite3VdbeMemFromBtree (BtCursor * , int , int , int , Mem *)
Definition at line 788 of file vdbemem.c.
References db, Mem::enc, Mem::flags, MEM_Blob, MEM_Dyn, MEM_Ephem, MEM_Term, sqlite3::mutex, Mem::n, sqlite3_mutex_held, sqlite3BtreeCursorDb(), sqlite3BtreeData(), sqlite3BtreeDataFetch(), sqlite3BtreeKey(), sqlite3BtreeKeyFetch(), sqlite3VdbeMemGrow(), sqlite3VdbeMemRelease(), SQLITE_BLOB, SQLITE_OK, Mem::type, Mem::xDel, and Mem::z.
Referenced by sqlite3VdbeExec(), sqlite3VdbeIdxKeyCompare(), and sqlite3VdbeIdxRowid().
int sqlite3VdbeMemGrow (Mem * pMem, int n, int preserve)
Definition at line 77 of file vdbemem.c.
References Mem::db, Mem::flags, MEM_Dyn, MEM_Ephem, MEM_Null, MEM_Static, Mem::n, sqlite3DbFree(), sqlite3DbMallocRaw(), sqlite3DbMallocSize(), sqlite3DbReallocOrFree(), SQLITE_NOMEM, SQLITE_OK, Mem::xDel, Mem::z, and Mem::zMalloc.
Referenced by allocateCursor(), sqlite3_aggregate_context(), sqlite3VdbeExec(), sqlite3VdbeList(), sqlite3VdbeMemExpandBlob(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemNulTerminate(), sqlite3VdbeMemSetStr(), and sqlite3VdbeMemStringify().
int sqlite3VdbeMemHandleBom (Mem * pMem)
Definition at line 338 of file utf.c.
References Mem::enc, Mem::flags, MEM_Term, Mem::n, sqlite3VdbeMemMakeWriteable(), SQLITE_OK, SQLITE_UTF16BE, SQLITE_UTF16LE, and Mem::z.
Referenced by sqlite3VdbeMemSetStr().
int sqlite3VdbeMemIntegerify (Mem *)
Definition at line 401 of file vdbemem.c.
References Mem::db, Mem::i, MEM_Int, sqlite3::mutex, setTypeFlag(), sqlite3_mutex_held, sqlite3VdbeIntValue(), SQLITE_OK, and Mem::u.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeMemNumerify().
int sqlite3VdbeMemMakeWriteable (Mem *)
Definition at line 121 of file vdbemem.c.
References Mem::db, expandBlob, f(), Mem::flags, MEM_Blob, MEM_Str, MEM_Term, sqlite3::mutex, Mem::n, sqlite3_mutex_held, sqlite3VdbeMemGrow(), SQLITE_NOMEM, SQLITE_OK, Mem::z, and Mem::zMalloc.
Referenced by sqlite3ValueText(), sqlite3VdbeExec(), sqlite3VdbeMemCopy(), sqlite3VdbeMemHandleBom(), and sqlite3VdbeMemTranslate().
void sqlite3VdbeMemMove (Mem * , Mem *)
Definition at line 555 of file vdbemem.c.
References Mem::db, Mem::flags, MEM_Null, sqlite3::mutex, sqlite3_mutex_held, sqlite3VdbeMemRelease(), Mem::xDel, and Mem::zMalloc.
Referenced by sqlite3TransferBindings(), and sqlite3VdbeExec().
int sqlite3VdbeMemNulTerminate (Mem *)
Definition at line 170 of file vdbemem.c.
References Mem::db, Mem::flags, MEM_Str, MEM_Term, sqlite3::mutex, Mem::n, sqlite3_mutex_held, sqlite3VdbeMemGrow(), SQLITE_NOMEM, SQLITE_OK, and Mem::z.
Referenced by applyNumericAffinity(), sqlite3ValueText(), sqlite3VdbeExec(), sqlite3VdbeIntValue(), and sqlite3VdbeRealValue().
int sqlite3VdbeMemNumerify (Mem *)
Definition at line 423 of file vdbemem.c.
References Mem::db, doubleToInt64(), Mem::flags, MEM_Blob, MEM_Int, MEM_Null, MEM_Real, MEM_Str, sqlite3::mutex, Mem::r, setTypeFlag(), sqlite3_mutex_held, sqlite3VdbeMemIntegerify(), sqlite3VdbeRealValue(), and SQLITE_OK.
Referenced by sqlite3VdbeExec().
int sqlite3VdbeMemRealify (Mem *)
Definition at line 412 of file vdbemem.c.
References Mem::db, MEM_Real, sqlite3::mutex, Mem::r, setTypeFlag(), sqlite3_mutex_held, sqlite3VdbeRealValue(), and SQLITE_OK.
Referenced by applyNumericAffinity(), and sqlite3VdbeExec().
void sqlite3VdbeMemRelease (Mem * p)
Definition at line 280 of file vdbemem.c.
References Mem::db, sqlite3DbFree(), sqlite3VdbeMemReleaseExternal(), Mem::xDel, Mem::z, and Mem::zMalloc.
Referenced by minMaxFinalize(), releaseMemArray(), sqlite3_clear_bindings(), sqlite3MemCompare(), sqlite3Utf16to8(), sqlite3ValueFree(), sqlite3VdbeDeleteUnpackedRecord(), sqlite3VdbeExec(), sqlite3VdbeIdxKeyCompare(), sqlite3VdbeIdxRowid(), sqlite3VdbeMemFromBtree(), sqlite3VdbeMemMove(), sqlite3VdbeMemReleaseExternal(), sqlite3VdbeMemSetDouble(), sqlite3VdbeMemSetInt64(), sqlite3VdbeMemSetStr(), sqlite3VdbeMemSetZeroBlob(), sqlite3VdbeMemTranslate(), sqlite3VdbeRecordCompare(), and vdbeUnbind().
void sqlite3VdbeMemReleaseExternal (Mem * p)
Definition at line 263 of file vdbemem.c.
References Mem::db, Mem::flags, MEM_Agg, MEM_Dyn, sqlite3::mutex, Mem::pDef, sqlite3_mutex_held, sqlite3VdbeMemFinalize(), sqlite3VdbeMemRelease(), Mem::u, Mem::xDel, and Mem::z.
Referenced by sqlite3_aggregate_context(), sqlite3VdbeExec(), sqlite3VdbeMemCopy(), sqlite3VdbeMemRelease(), and sqlite3VdbeMemShallowCopy().
void sqlite3VdbeMemSetDouble (Mem * , double)
Definition at line 479 of file vdbemem.c.
References Mem::flags, MEM_Real, Mem::r, sqlite3IsNaN(), sqlite3VdbeMemRelease(), sqlite3VdbeMemSetNull(), SQLITE_FLOAT, and Mem::type.
Referenced by sqlite3_bind_double(), and sqlite3_result_double().
void sqlite3VdbeMemSetInt64 (Mem * , i64)
Definition at line 468 of file vdbemem.c.
References Mem::flags, Mem::i, MEM_Int, sqlite3VdbeMemRelease(), SQLITE_INTEGER, Mem::type, and Mem::u.
Referenced by sqlite3_bind_int64(), sqlite3_result_int(), and sqlite3_result_int64().
void sqlite3VdbeMemSetNull (Mem *)
Definition at line 444 of file vdbemem.c.
References MEM_Null, setTypeFlag(), SQLITE_NULL, and Mem::type.
Referenced by sqlite3_result_error_nomem(), sqlite3_result_null(), sqlite3VdbeExec(), sqlite3VdbeMemSetDouble(), and sqlite3VdbeMemSetStr().
int sqlite3VdbeMemSetStr (Mem * , const char * , int , u8 , void(*)(void *))
Definition at line 576 of file vdbemem.c.
References sqlite3::aLimit, Mem::db, Mem::enc, Mem::flags, MEM_Blob, MEM_Dyn, MEM_Static, MEM_Str, MEM_Term, sqlite3::mutex, Mem::n, sqlite3_mutex_held, sqlite3VdbeMemGrow(), sqlite3VdbeMemHandleBom(), sqlite3VdbeMemRelease(), sqlite3VdbeMemSetNull(), SQLITE_BLOB, SQLITE_DYNAMIC, SQLITE_LIMIT_LENGTH, SQLITE_MAX_LENGTH, SQLITE_NOMEM, SQLITE_OK, SQLITE_STATIC, SQLITE_TEXT, SQLITE_TOOBIG, SQLITE_TRANSIENT, SQLITE_UTF8, Mem::type, Mem::xDel, Mem::z, and Mem::zMalloc.
Referenced by bindText(), sqlite3_result_blob(), sqlite3_result_error(), sqlite3_result_error16(), sqlite3_result_error_toobig(), sqlite3_result_text(), sqlite3_result_text16(), sqlite3_result_text16be(), sqlite3_result_text16le(), sqlite3Utf16to8(), sqlite3ValueFromExpr(), sqlite3ValueSetStr(), sqlite3VdbeExec(), sqlite3VdbeList(), and sqlite3VdbeSetColName().
void sqlite3VdbeMemSetZeroBlob (Mem * , int)
Definition at line 453 of file vdbemem.c.
References Mem::enc, Mem::flags, Mem::i, MEM_Blob, MEM_Zero, Mem::n, setTypeFlag(), sqlite3VdbeMemRelease(), SQLITE_BLOB, SQLITE_UTF8, Mem::type, and Mem::u.
Referenced by sqlite3_bind_zeroblob(), and sqlite3_result_zeroblob().
void sqlite3VdbeMemShallowCopy (Mem * , const Mem * , int)
Definition at line 517 of file vdbemem.c.
References Mem::flags, MEM_Dyn, MEM_Ephem, MEM_Static, MEMCELLSIZE, sqlite3VdbeMemReleaseExternal(), Mem::xDel, Mem::z, and Mem::zMalloc.
Referenced by sqlite3MemCompare(), and sqlite3VdbeExec().
int sqlite3VdbeMemStringify (Mem * , int)
Definition at line 197 of file vdbemem.c.
References Mem::db, Mem::enc, Mem::flags, Mem::i, MEM_Blob, MEM_Int, MEM_Real, MEM_Str, MEM_Term, MEM_Zero, sqlite3::mutex, Mem::n, Mem::r, sqlite3_mutex_held, sqlite3_snprintf(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemGrow(), SQLITE_NOMEM, SQLITE_OK, SQLITE_UTF8, Mem::u, and Mem::z.
Referenced by applyAffinity(), and sqlite3ValueText().
int sqlite3VdbeMemTooBig (Mem *)
Definition at line 494 of file vdbemem.c.
References sqlite3::aLimit, Mem::db, Mem::flags, Mem::i, MEM_Blob, MEM_Str, MEM_Zero, Mem::n, SQLITE_LIMIT_LENGTH, and Mem::u.
Referenced by sqlite3VdbeExec().
int sqlite3VdbeMemTranslate (Mem * , u8)
Definition at line 194 of file utf.c.
References Mem::db, Mem::enc, Mem::flags, MEM_Dyn, MEM_Ephem, MEM_Static, MEM_Str, MEM_Term, sqlite3::mutex, Mem::n, READ_UTF16BE, READ_UTF16LE, READ_UTF8, sqlite3_mutex_held, sqlite3DbMallocRaw(), sqlite3VdbeMemMakeWriteable(), sqlite3VdbeMemRelease(), SQLITE_NOMEM, SQLITE_OK, SQLITE_UTF16BE, SQLITE_UTF16LE, SQLITE_UTF8, WRITE_UTF16BE, WRITE_UTF16LE, WRITE_UTF8, Mem::z, and Mem::zMalloc.
Referenced by sqlite3VdbeChangeEncoding().
int sqlite3VdbeOpcodeHasProperty (int , int)
Definition at line 179 of file vdbe.c.
Referenced by resolveP2Values(), and sqlite3VdbeAddOpList().
double sqlite3VdbeRealValue (Mem *)
Definition at line 359 of file vdbemem.c.
References Mem::db, Mem::flags, Mem::i, MEM_Blob, MEM_Int, MEM_Real, MEM_Str, sqlite3::mutex, Mem::r, sqlite3_mutex_held, sqlite3AtoF(), sqlite3VdbeChangeEncoding(), sqlite3VdbeMemNulTerminate(), SQLITE_UTF8, Mem::u, and Mem::z.
Referenced by sqlite3_value_double(), sqlite3VdbeExec(), sqlite3VdbeMemNumerify(), and sqlite3VdbeMemRealify().
int sqlite3VdbeSerialGet (const unsigned char * , u32 , Mem *)
Definition at line 2099 of file vdbeaux.c.
References Mem::flags, Mem::i, MEM_Blob, MEM_Ephem, MEM_Int, MEM_Null, MEM_Real, MEM_Str, Mem::n, Mem::r, sqlite3IsNaN(), swapMixedEndianFloat, Mem::u, Mem::xDel, and Mem::z.
Referenced by sqlite3VdbeExec(), sqlite3VdbeIdxRowid(), sqlite3VdbeRecordCompare(), and sqlite3VdbeRecordUnpack().
int sqlite3VdbeSerialPut (unsigned char * , int , Mem * , int)
u32 sqlite3VdbeSerialType (Mem * , int)
Definition at line 1932 of file vdbeaux.c.
References Mem::db, Mem::flags, Mem::i, sqlite3::mallocFailed, MAX_6BYTE, MEM_Blob, MEM_Int, MEM_Null, MEM_Real, MEM_Str, MEM_Zero, Mem::n, and Mem::u.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeSerialPut().
int sqlite3VdbeSerialTypeLen (u32)
Definition at line 1970 of file vdbeaux.c.
Referenced by sqlite3_blob_open(), sqlite3VdbeExec(), sqlite3VdbeIdxRowid(), sqlite3VdbeRecordCompare(), sqlite3VdbeRecordUnpack(), and sqlite3VdbeSerialPut().
void sqliteVdbePopStack (Vdbe * , int)
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1