ContextLogger2 Logger Daemon Internals: vdbeblob.c File Reference
vdbeblob.c File Reference
Classes
struct Incrblob
Typedefs
typedef struct Incrblob Incrblob
Functions
int sqlite3_blob_open (sqlite3 *db, const char *zDb, const char *zTable, const char *zColumn, sqlite_int64 iRow, int flags, sqlite3_blob **ppBlob)
int sqlite3_blob_close (sqlite3_blob *pBlob)
static int blobReadWrite (sqlite3_blob *pBlob, void *z, int n, int iOffset, int(*xCall)(BtCursor *, u32, u32, void *))
int sqlite3_blob_read (sqlite3_blob *pBlob, void *z, int n, int iOffset)
int sqlite3_blob_write (sqlite3_blob *pBlob, const void *z, int n, int iOffset)
int sqlite3_blob_bytes (sqlite3_blob *pBlob)
Typedef Documentation
typedef struct Incrblob Incrblob
Definition at line 26 of file vdbeblob.c.
Function Documentation
static int blobReadWrite (sqlite3_blob * pBlob, void * z, int n, int iOffset, int(*)(BtCursor *, u32, u32, void *) xCall) [static]
Definition at line 278 of file vdbeblob.c.
References Vdbe::db, Incrblob::db, db, sqlite3::errCode, Incrblob::iOffset, sqlite3::mutex, Incrblob::nByte, Incrblob::pCsr, Incrblob::pStmt, Vdbe::rc, sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3ApiExit(), sqlite3BtreeEnterCursor, sqlite3BtreeLeaveCursor, sqlite3Error(), sqlite3VdbeFinalize(), SQLITE_ABORT, and SQLITE_ERROR.
Referenced by sqlite3_blob_read(), and sqlite3_blob_write().
int sqlite3_blob_bytes (sqlite3_blob * pBlob)
Definition at line 343 of file vdbeblob.c.
References Incrblob::nByte.
Referenced by incrblobInput(), incrblobOutput(), and incrblobSeek().
int sqlite3_blob_close (sqlite3_blob * pBlob)
Definition at line 266 of file vdbeblob.c.
References Incrblob::db, Incrblob::pStmt, sqlite3_finalize(), and sqlite3DbFree().
Referenced by incrblobClose().
int sqlite3_blob_open (sqlite3 * db, const char * zDb, const char * zTable, const char * zColumn, sqlite_int64 iRow, int flags, sqlite3_blob ** ppBlob)
Definition at line 39 of file vdbeblob.c.
References Table::aCol, Index::aiColumn, VdbeCursor::aOffset, Vdbe::apCsr, VdbeCursor::aType, Incrblob::db, Parse::db, Incrblob::flags, Incrblob::iOffset, IsVirtual, sqlite3::mallocFailed, sqlite3::mutex, Incrblob::nByte, Table::nCol, Index::nColumn, OP_Close, OP_Column, OP_Halt, OP_NotExists, OP_OpenRead, OP_OpenWrite, OP_ResultRow, OP_SetNumColumns, OP_Transaction, OP_Variable, OP_VerifyCookie, Incrblob::pCsr, VdbeCursor::pCursor, Table::pIndex, Index::pNext, Table::pSchema, Table::pSelect, Incrblob::pStmt, Schema::schema_cookie, sqlite3_bind_int64(), sqlite3_errmsg(), sqlite3_finalize(), sqlite3_mutex_enter, sqlite3_mutex_leave, sqlite3_snprintf(), sqlite3_step(), sqlite3ApiExit(), sqlite3BtreeCacheOverflow(), sqlite3BtreeEnterAll, sqlite3BtreeEnterCursor, sqlite3BtreeLeaveAll, sqlite3BtreeLeaveCursor, sqlite3DbFree(), sqlite3DbMallocZero(), sqlite3Error(), sqlite3ErrorMsg(), sqlite3LocateTable(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3SchemaToIndex(), sqlite3StrICmp(), sqlite3VdbeAddOpList(), sqlite3VdbeChangeP1(), sqlite3VdbeChangeP2(), sqlite3VdbeChangeP3(), sqlite3VdbeChangeToNoop(), sqlite3VdbeCreate(), sqlite3VdbeMakeReady(), sqlite3VdbeSerialTypeLen(), sqlite3VdbeUsesBtree(), SQLITE_ERROR, SQLITE_MISUSE, SQLITE_OK, SQLITE_ROW, SQLITE_SCHEMA, Table::tnum, Parse::zErrMsg, and Column::zName.
int sqlite3_blob_read (sqlite3_blob * pBlob, void * z, int n, int iOffset)
Definition at line 326 of file vdbeblob.c.
References blobReadWrite(), and sqlite3BtreeData().
Referenced by incrblobInput().
int sqlite3_blob_write (sqlite3_blob * pBlob, const void * z, int n, int iOffset)
Definition at line 333 of file vdbeblob.c.
References blobReadWrite(), and sqlite3BtreePutData().
Referenced by incrblobOutput().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1