ContextLogger2 Logger Daemon Internals: vdbe.h File Reference
vdbe.h File Reference
Classes
struct VdbeOp
struct VdbeOpList
Defines
#define P4_NOTUSED 0
#define P4_DYNAMIC (-1)
#define P4_STATIC (-2)
#define P4_COLLSEQ (-4)
#define P4_FUNCDEF (-5)
#define P4_KEYINFO (-6)
#define P4_VDBEFUNC (-7)
#define P4_MEM (-8)
#define P4_TRANSIENT (-9)
#define P4_VTAB (-10)
#define P4_MPRINTF (-11)
#define P4_REAL (-12)
#define P4_INT64 (-13)
#define P4_INT32 (-14)
#define P4_INTARRAY (-15)
#define P4_KEYINFO_HANDOFF (-16)
#define P4_KEYINFO_STATIC (-17)
#define COLNAME_NAME 0
#define COLNAME_DECLTYPE 1
#define COLNAME_DATABASE 2
#define COLNAME_TABLE 3
#define COLNAME_COLUMN 4
#define COLNAME_N 2
#define ADDR(X) (-1-(X))
#define VdbeComment(X)
#define VdbeNoopComment(X)
Typedefs
typedef struct Vdbe Vdbe
typedef struct VdbeFunc VdbeFunc
typedef struct Mem Mem
typedef struct VdbeOp VdbeOp
typedef struct VdbeOpList VdbeOpList
Functions
Vdbe * sqlite3VdbeCreate (sqlite3 *)
int sqlite3VdbeAddOp0 (Vdbe *, int)
int sqlite3VdbeAddOp1 (Vdbe *, int, int)
int sqlite3VdbeAddOp2 (Vdbe *, int, int, int)
int sqlite3VdbeAddOp3 (Vdbe *, int, int, int, int)
int sqlite3VdbeAddOp4 (Vdbe *, int, int, int, int, const char *zP4, int)
int sqlite3VdbeAddOpList (Vdbe *, int nOp, VdbeOpList const *aOp)
void sqlite3VdbeChangeP1 (Vdbe *, int addr, int P1)
void sqlite3VdbeChangeP2 (Vdbe *, int addr, int P2)
void sqlite3VdbeChangeP3 (Vdbe *, int addr, int P3)
void sqlite3VdbeChangeP5 (Vdbe *, u8 P5)
void sqlite3VdbeJumpHere (Vdbe *, int addr)
void sqlite3VdbeChangeToNoop (Vdbe *, int addr, int N)
void sqlite3VdbeChangeP4 (Vdbe *, int addr, const char *zP4, int N)
void sqlite3VdbeUsesBtree (Vdbe *, int)
VdbeOp * sqlite3VdbeGetOp (Vdbe *, int)
int sqlite3VdbeMakeLabel (Vdbe *)
void sqlite3VdbeDelete (Vdbe *)
void sqlite3VdbeMakeReady (Vdbe *, int, int, int, int)
int sqlite3VdbeFinalize (Vdbe *)
void sqlite3VdbeResolveLabel (Vdbe *, int)
int sqlite3VdbeCurrentAddr (Vdbe *)
void sqlite3VdbeResetStepResult (Vdbe *)
int sqlite3VdbeReset (Vdbe *)
void sqlite3VdbeSetNumCols (Vdbe *, int)
int sqlite3VdbeSetColName (Vdbe *, int, int, const char *, void(*)(void *))
void sqlite3VdbeCountChanges (Vdbe *)
sqlite3 * sqlite3VdbeDb (Vdbe *)
void sqlite3VdbeSetSql (Vdbe *, const char *z, int n)
void sqlite3VdbeSwap (Vdbe *, Vdbe *)
UnpackedRecord * sqlite3VdbeRecordUnpack (KeyInfo *, int, const void *, UnpackedRecord *, int)
void sqlite3VdbeDeleteUnpackedRecord (UnpackedRecord *)
int sqlite3VdbeRecordCompare (int, const void *, UnpackedRecord *)
Define Documentation
#define ADDR (X) (-1-(X))
Definition at line 141 of file vdbe.h.
Referenced by sqlite3DropTriggerPtr(), and sqlite3VdbeAddOpList().
#define COLNAME_COLUMN 4
Definition at line 124 of file vdbe.h.
Referenced by generateColumnTypes().
#define COLNAME_DATABASE 2
Definition at line 122 of file vdbe.h.
Referenced by generateColumnTypes().
#define COLNAME_DECLTYPE 1
Definition at line 121 of file vdbe.h.
Referenced by generateColumnTypes(), sqlite3_column_decltype(), and sqlite3_column_decltype16().
#define COLNAME_N 2
Definition at line 131 of file vdbe.h.
Referenced by sqlite3VdbeDelete(), sqlite3VdbeSetColName(), and sqlite3VdbeSetNumCols().
#define COLNAME_NAME 0
Definition at line 120 of file vdbe.h.
Referenced by generateColumnNames(), returnSingleInt(), sqlite3_column_name(), sqlite3_column_name16(), sqlite3DeleteFrom(), sqlite3Insert(), sqlite3Pragma(), sqlite3Prepare(), and sqlite3Update().
#define COLNAME_TABLE 3
Definition at line 123 of file vdbe.h.
Referenced by generateColumnTypes().
#define P4_COLLSEQ (-4)
Definition at line 93 of file vdbe.h.
Referenced by codeCompare(), displayP4(), sqlite3ExprCodeTarget(), sqlite3VdbeExec(), and updateAccumulator().
#define P4_DYNAMIC (-1)
Definition at line 91 of file vdbe.h.
Referenced by freeP4(), reloadTableSchema(), sqlite3CodeRowTrigger(), sqlite3CreateIndex(), sqlite3EndTable(), sqlite3ExprCodeTarget(), sqlite3FinishTrigger(), sqlite3GenerateConstraintChecks(), sqlite3Pragma(), sqlite3VdbeChangeP4(), sqlite3VdbeExec(), sqlite3VtabFinishParse(), and sqlite3WhereBegin().
#define P4_FUNCDEF (-5)
Definition at line 94 of file vdbe.h.
Referenced by codeAttach(), displayP4(), finalizeAggFunctions(), freeP4(), sqlite3ExprCodeTarget(), sqlite3VdbeExec(), and updateAccumulator().
#define P4_INT32 (-14)
Definition at line 103 of file vdbe.h.
Referenced by displayP4(), sqlite3GenerateConstraintChecks(), sqlite3RefillIndex(), sqlite3VdbeChangeP4(), sqlite3VdbeExec(), and sqlite3WhereBegin().
#define P4_INT64 (-13)
Definition at line 102 of file vdbe.h.
Referenced by codeInteger(), displayP4(), and freeP4().
#define P4_INTARRAY (-15)
Definition at line 104 of file vdbe.h.
Referenced by displayP4(), freeP4(), multiSelectOrderBy(), and sqlite3VdbeExec().
#define P4_KEYINFO (-6)
Definition at line 95 of file vdbe.h.
Referenced by displayP4(), freeP4(), multiSelect(), sqlite3CodeSubselect(), sqlite3Select(), sqlite3VdbeChangeP4(), and sqlite3VdbeExec().
#define P4_KEYINFO_HANDOFF (-16)
Definition at line 113 of file vdbe.h.
Referenced by analyzeOneTable(), freeP4(), multiSelectOrderBy(), resetAccumulator(), sqlite3FindInIndex(), sqlite3OpenTableAndIndices(), sqlite3RefillIndex(), sqlite3Select(), sqlite3Update(), sqlite3VdbeChangeP4(), sqlite3WhereBegin(), and xferOptimization().
#define P4_KEYINFO_STATIC (-17)
Definition at line 114 of file vdbe.h.
Referenced by displayP4(), and multiSelectOrderBy().
#define P4_MEM (-8)
Definition at line 97 of file vdbe.h.
Referenced by displayP4(), freeP4(), sqlite3ColumnDefault(), and sqlite3VdbeExec().
#define P4_MPRINTF (-11)
Definition at line 100 of file vdbe.h.
Referenced by freeP4(), and sqlite3WhereBegin().
#define P4_NOTUSED 0
Definition at line 90 of file vdbe.h.
Referenced by sqlite3VdbeAddOp3(), sqlite3VdbeAddOpList(), and sqlite3VdbeChangeP4().
#define P4_REAL (-12)
Definition at line 101 of file vdbe.h.
Referenced by codeReal(), displayP4(), and freeP4().
#define P4_STATIC (-2)
Definition at line 92 of file vdbe.h.
Referenced by codeTableLocks(), sqlite3CompleteInsertion(), sqlite3DeleteFrom(), sqlite3DropTriggerPtr(), sqlite3ExprCodeTarget(), sqlite3GenerateConstraintChecks(), sqlite3GenerateRowDelete(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3WhereBegin(), and xferOptimization().
#define P4_TRANSIENT (-9)
Definition at line 98 of file vdbe.h.
#define P4_VDBEFUNC (-7)
Definition at line 96 of file vdbe.h.
Referenced by freeP4(), and sqlite3VdbeExec().
#define P4_VTAB (-10)
Definition at line 99 of file vdbe.h.
Referenced by displayP4(), readsTable(), sqlite3AlterRenameTable(), sqlite3DeleteFrom(), sqlite3FinishCoding(), sqlite3Insert(), sqlite3VdbeExec(), sqlite3WhereBegin(), and updateVirtualTable().
#define VdbeComment (X)
Definition at line 202 of file vdbe.h.
Referenced by analyzeOneTable(), codeEqualityTerm(), codeOffset(), codeTriggerProgram(), computeLimitRegisters(), multiSelect(), sqlite3CodeSubselect(), sqlite3ColumnDefault(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeTarget(), sqlite3FindInIndex(), sqlite3Insert(), sqlite3OpenTable(), sqlite3OpenTableAndIndices(), sqlite3Select(), sqlite3WhereBegin(), and xferOptimization().
#define VdbeNoopComment (X)
Definition at line 203 of file vdbe.h.
Referenced by multiSelectOrderBy(), and sqlite3ExprCodeTarget().
Typedef Documentation
typedef struct Mem Mem
Definition at line 36 of file vdbe.h.
typedef struct Vdbe Vdbe
Definition at line 29 of file vdbe.h.
typedef struct VdbeFunc VdbeFunc
Definition at line 35 of file vdbe.h.
typedef struct VdbeOp VdbeOp
Definition at line 73 of file vdbe.h.
typedef struct VdbeOpList VdbeOpList
Definition at line 85 of file vdbe.h.
Function Documentation
int sqlite3VdbeAddOp0 (Vdbe * , int)
Definition at line 168 of file vdbeaux.c.
References sqlite3VdbeAddOp3().
Referenced by multiSelectOrderBy(), pushOntoSorter(), sqlite3DeleteFrom(), sqlite3DropTable(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeTarget(), sqlite3FinishCoding(), sqlite3GetVdbe(), sqlite3StartTable(), and sqlite3Update().
int sqlite3VdbeAddOp1 (Vdbe * , int , int)
Definition at line 171 of file vdbeaux.c.
References sqlite3VdbeAddOp3().
Referenced by analyzeOneTable(), autoIncEnd(), codeAttach(), codeEqualityTerm(), codeOffset(), computeLimitRegisters(), generateOutputSubroutine(), generateSortTail(), loadAnalysis(), multiSelect(), multiSelectOrderBy(), pushOntoSorter(), selectInnerLoop(), sqlite3BeginWriteOperation(), sqlite3CodeSubselect(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3EndTable(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeTarget(), sqlite3FindInIndex(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), and sqlite3WhereEnd().
int sqlite3VdbeAddOp2 (Vdbe * , int , int , int)
Definition at line 174 of file vdbeaux.c.
References sqlite3VdbeAddOp3().
Referenced by analyzeOneTable(), autoIncBegin(), autoIncEnd(), autoIncStep(), codeAllEqualityTerms(), codeApplyAffinity(), codeDistinct(), codeEqualityTerm(), codeInteger(), codeOffset(), codeReal(), codeTriggerProgram(), computeLimitRegisters(), flagPragma(), generateOutputSubroutine(), generateSortTail(), multiSelect(), multiSelectOrderBy(), openStatTable(), pushOntoSorter(), resetAccumulator(), returnSingleInt(), selectInnerLoop(), sqlite3BeginTransaction(), sqlite3ChangeCookie(), sqlite3CodeSubselect(), sqlite3CodeVerifySchema(), sqlite3CommitTransaction(), sqlite3CompleteInsertion(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropTriggerPtr(), sqlite3ExprCode(), sqlite3ExprCodeAndCache(), sqlite3ExprCodeCopy(), sqlite3ExprCodeExprList(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3ExprWritableRegister(), sqlite3FindInIndex(), sqlite3FinishCoding(), sqlite3GenerateConstraintChecks(), sqlite3GenerateIndexKey(), sqlite3GenerateRowDelete(), sqlite3Insert(), sqlite3MinimumFileFormat(), sqlite3OpenMasterTable(), sqlite3OpenTable(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3RollbackTransaction(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), sqlite3Vacuum(), sqlite3VtabFinishParse(), sqlite3WhereBegin(), sqlite3WhereEnd(), updateVirtualTable(), and xferOptimization().
int sqlite3VdbeAddOp3 (Vdbe * , int , int , int , int)
Definition at line 136 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::db, Vdbe::expired, Vdbe::magic, sqlite3::mallocFailed, Vdbe::nOp, Vdbe::nOpAlloc, VdbeOp::opcode, VdbeOp::p, VdbeOp::p1, VdbeOp::p2, VdbeOp::p3, VdbeOp::p4, P4_NOTUSED, VdbeOp::p4type, VdbeOp::p5, resizeOpArray(), and VDBE_MAGIC_INIT.
Referenced by analyzeOneTable(), autoIncBegin(), autoIncEnd(), codeAttach(), codeDistinct(), codeEqualityTerm(), computeLimitRegisters(), destroyRootPage(), generateOutputSubroutine(), generateSortTail(), multiSelect(), multiSelectOrderBy(), openStatTable(), pushOntoSorter(), selectInnerLoop(), sqlite3ChangeCookie(), sqlite3CodeSubselect(), sqlite3CompleteInsertion(), sqlite3DeleteFrom(), sqlite3EndTable(), sqlite3ExprCodeGetColumn(), sqlite3ExprCodeMove(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3GenerateConstraintChecks(), sqlite3GenerateIndexKey(), sqlite3GenerateRowDelete(), sqlite3GenerateRowIndexDelete(), sqlite3Insert(), sqlite3MinimumFileFormat(), sqlite3OpenMasterTable(), sqlite3OpenTable(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), sqlite3VdbeAddOp0(), sqlite3VdbeAddOp1(), sqlite3VdbeAddOp2(), sqlite3VdbeAddOp4(), sqlite3WhereBegin(), updateVirtualTable(), and xferOptimization().
int sqlite3VdbeAddOp4 (Vdbe * , int , int , int , int , const char * zP4, int)
Definition at line 182 of file vdbeaux.c.
References sqlite3VdbeAddOp3(), and sqlite3VdbeChangeP4().
Referenced by analyzeOneTable(), autoIncBegin(), codeCompare(), codeInteger(), codeReal(), codeTableLocks(), finalizeAggFunctions(), generateOutputSubroutine(), generateSortTail(), multiSelectOrderBy(), reloadTableSchema(), resetAccumulator(), selectInnerLoop(), sqlite3AlterRenameTable(), sqlite3CodeRowTrigger(), sqlite3CodeSubselect(), sqlite3CreateIndex(), sqlite3DeleteFrom(), sqlite3DropIndex(), sqlite3DropTable(), sqlite3DropTriggerPtr(), sqlite3EndTable(), sqlite3ExprCodeTarget(), sqlite3FindInIndex(), sqlite3FinishCoding(), sqlite3FinishTrigger(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3OpenTableAndIndices(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3Select(), sqlite3Update(), sqlite3VtabFinishParse(), sqlite3WhereBegin(), updateAccumulator(), updateVirtualTable(), and xferOptimization().
int sqlite3VdbeAddOpList (Vdbe * , int nOp, VdbeOpList const * aOp)
Definition at line 342 of file vdbeaux.c.
References ADDR, Vdbe::aOp, Vdbe::db, Vdbe::magic, sqlite3::mallocFailed, Vdbe::nOp, Vdbe::nOpAlloc, VdbeOpList::opcode, VdbeOp::opcode, OPFLG_JUMP, VdbeOp::p, VdbeOpList::p1, VdbeOp::p1, VdbeOp::p2, VdbeOpList::p2, VdbeOpList::p3, VdbeOp::p3, VdbeOp::p4, P4_NOTUSED, VdbeOp::p4type, VdbeOp::p5, resizeOpArray(), sqlite3VdbeOpcodeHasProperty(), and VDBE_MAGIC_INIT.
Referenced by sqlite3_blob_open(), sqlite3DropTriggerPtr(), and sqlite3Pragma().
void sqlite3VdbeChangeP1 (Vdbe * , int addr, int P1)
Definition at line 388 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::magic, Vdbe::nOp, VdbeOp::p1, and VDBE_MAGIC_INIT.
Referenced by sqlite3_blob_open(), and sqlite3Pragma().
void sqlite3VdbeChangeP2 (Vdbe * , int addr, int P2)
Definition at line 399 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::magic, Vdbe::nOp, VdbeOp::p2, and VDBE_MAGIC_INIT.
Referenced by multiSelect(), sqlite3_blob_open(), sqlite3Pragma(), sqlite3VdbeJumpHere(), and sqlite3WhereBegin().
void sqlite3VdbeChangeP3 (Vdbe * , int addr, int P3)
Definition at line 409 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::magic, Vdbe::nOp, VdbeOp::p3, and VDBE_MAGIC_INIT.
Referenced by sqlite3_blob_open(), and sqlite3Pragma().
void sqlite3VdbeChangeP4 (Vdbe * , int addr, const char * zP4, int N)
Definition at line 524 of file vdbeaux.c.
References KeyInfo::aColl, Vdbe::aOp, KeyInfo::aSortOrder, Vdbe::db, db, freeP4(), VdbeOp::i, Vdbe::magic, sqlite3::mallocFailed, Vdbe::nOp, VdbeOp::p, VdbeOp::p4, P4_DYNAMIC, P4_INT32, P4_KEYINFO, P4_KEYINFO_HANDOFF, P4_NOTUSED, VdbeOp::p4type, VdbeOp::pKeyInfo, sqlite3DbStrNDup(), sqlite3Malloc(), SQLITE_PTR_TO_INT, VDBE_MAGIC_INIT, and VdbeOp::z.
Referenced by codeAttach(), multiSelect(), sqlite3CodeSubselect(), sqlite3ColumnDefault(), sqlite3CompleteInsertion(), sqlite3DeleteFrom(), sqlite3DropTriggerPtr(), sqlite3ExprCodeTarget(), sqlite3FinishCoding(), sqlite3GenerateConstraintChecks(), sqlite3GenerateRowDelete(), sqlite3IndexAffinityStr(), sqlite3Pragma(), sqlite3TableAffinityStr(), sqlite3VdbeAddOp4(), and xferOptimization().
void sqlite3VdbeChangeP5 (Vdbe * , u8 P5)
Definition at line 420 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::magic, Vdbe::nOp, VdbeOp::p5, and VDBE_MAGIC_INIT.
Referenced by analyzeOneTable(), autoIncBegin(), autoIncEnd(), codeAttach(), codeCompare(), generateOutputSubroutine(), generateSortTail(), openStatTable(), selectInnerLoop(), sqlite3CompleteInsertion(), sqlite3EndTable(), sqlite3ExprCodeTarget(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3StartTable(), sqlite3WhereBegin(), sqlite3WhereEnd(), updateAccumulator(), and xferOptimization().
void sqlite3VdbeChangeToNoop (Vdbe * , int addr, int N)
Definition at line 486 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::db, db, freeP4(), OP_Noop, VdbeOp::opcode, VdbeOp::p, VdbeOp::p4, and VdbeOp::p4type.
Referenced by sqlite3_blob_open(), sqlite3CodeSubselect(), and sqlite3Select().
void sqlite3VdbeCountChanges (Vdbe *)
Definition at line 2463 of file vdbeaux.c.
References Vdbe::changeCntOn.
Referenced by sqlite3DeleteFrom(), sqlite3Insert(), and sqlite3Update().
Vdbe* sqlite3VdbeCreate (sqlite3 *)
Definition at line 38 of file vdbeaux.c.
References Vdbe::db, Vdbe::magic, Vdbe::pNext, Vdbe::pPrev, sqlite3::pVdbe, sqlite3DbMallocZero(), and VDBE_MAGIC_INIT.
Referenced by sqlite3_blob_open(), sqlite3GetVdbe(), and sqlite3Pragma().
int sqlite3VdbeCurrentAddr (Vdbe *)
Definition at line 333 of file vdbeaux.c.
References Vdbe::magic, Vdbe::nOp, and VDBE_MAGIC_INIT.
Referenced by analyzeOneTable(), autoIncBegin(), generateOutputSubroutine(), multiSelect(), multiSelectOrderBy(), readsTable(), sqlite3CodeSubselect(), sqlite3DeleteFrom(), sqlite3ExprHardCopy(), sqlite3Insert(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), sqlite3WhereEnd(), and updateVirtualTable().
sqlite3* sqlite3VdbeDb (Vdbe *)
Definition at line 2487 of file vdbeaux.c.
References Vdbe::db.
Referenced by codeReal(), dup8bytes(), openStatTable(), sqlite3ColumnDefault(), sqlite3ExprCodeTarget(), sqlite3IndexAffinityStr(), sqlite3Reprepare(), and sqlite3TableAffinityStr().
void sqlite3VdbeDelete (Vdbe *)
Definition at line 1813 of file vdbeaux.c.
References Vdbe::aColName, Vdbe::aLabel, Vdbe::aMem, Vdbe::aOp, Vdbe::aVar, COLNAME_N, Vdbe::db, freeP4(), Vdbe::magic, Vdbe::nOp, Vdbe::nResColumn, Vdbe::nVar, VdbeOp::p, VdbeOp::p4, VdbeOp::p4type, Vdbe::pNext, Vdbe::pPrev, sqlite3::pVdbe, releaseMemArray(), sqlite3DbFree(), VDBE_MAGIC_DEAD, and Vdbe::zSql.
Referenced by sqlite3RunParser(), and sqlite3VdbeFinalize().
void sqlite3VdbeDeleteUnpackedRecord (UnpackedRecord *)
Definition at line 2258 of file vdbeaux.c.
References UnpackedRecord::aMem, KeyInfo::db, UnpackedRecord::flags, UnpackedRecord::pKeyInfo, sqlite3DbFree(), sqlite3VdbeMemRelease(), UNPACKED_NEED_DESTROY, UNPACKED_NEED_FREE, and Mem::zMalloc.
Referenced by sqlite3BtreeMoveto(), and sqlite3VdbeExec().
int sqlite3VdbeFinalize (Vdbe *)
Definition at line 1779 of file vdbeaux.c.
References Vdbe::db, sqlite3::errMask, Vdbe::magic, sqlite3VdbeDelete(), sqlite3VdbeReset(), SQLITE_MISUSE, SQLITE_OK, VDBE_MAGIC_HALT, VDBE_MAGIC_INIT, and VDBE_MAGIC_RUN.
Referenced by blobReadWrite(), sqlite3_finalize(), and sqlite3Reprepare().
VdbeOp* sqlite3VdbeGetOp (Vdbe * , int)
Definition at line 623 of file vdbeaux.c.
References Vdbe::aOp, Vdbe::db, Vdbe::magic, sqlite3::mallocFailed, and VDBE_MAGIC_INIT.
Referenced by readsTable(), sqlite3ExprHardCopy(), sqlite3FinishCoding(), sqlite3Insert(), and sqlite3WhereEnd().
void sqlite3VdbeJumpHere (Vdbe * , int addr)
Definition at line 432 of file vdbeaux.c.
References Vdbe::nOp, and sqlite3VdbeChangeP2().
Referenced by analyzeOneTable(), autoIncEnd(), codeOffset(), computeLimitRegisters(), generateOutputSubroutine(), multiSelect(), multiSelectOrderBy(), pushOntoSorter(), sqlite3CodeSubselect(), sqlite3DeleteFrom(), sqlite3ExprCodeTarget(), sqlite3FindInIndex(), sqlite3FinishCoding(), sqlite3GenerateConstraintChecks(), sqlite3GenerateRowDelete(), sqlite3Insert(), sqlite3MinimumFileFormat(), sqlite3Pragma(), sqlite3RefillIndex(), sqlite3Select(), sqlite3StartTable(), sqlite3Update(), sqlite3WhereEnd(), updateVirtualTable(), and xferOptimization().
int sqlite3VdbeMakeLabel (Vdbe *)
Definition at line 210 of file vdbeaux.c.
References Vdbe::aLabel, Vdbe::db, Vdbe::magic, Vdbe::nLabel, Vdbe::nLabelAlloc, sqlite3DbReallocOrFree(), and VDBE_MAGIC_INIT.
Referenced by analyzeOneTable(), codeEqualityTerm(), generateOutputSubroutine(), generateSortTail(), multiSelect(), multiSelectOrderBy(), sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3Select(), sqlite3Update(), sqlite3WhereBegin(), and updateAccumulator().
void sqlite3VdbeMakeReady (Vdbe * , int , int , int , int)
Definition at line 1003 of file vdbeaux.c.
References Vdbe::aMem, Vdbe::aOp, Vdbe::apArg, Vdbe::apCsr, Vdbe::aVar, Vdbe::azVar, Vdbe::cacheCtr, Mem::db, Vdbe::db, db, Vdbe::errorAction, Vdbe::explain, Mem::flags, Vdbe::magic, sqlite3::mallocFailed, MEM_Null, Vdbe::minWriteFileFormat, Vdbe::nChange, Vdbe::nCursor, Vdbe::nMem, Vdbe::nOp, Vdbe::nVar, OE_Abort, Vdbe::okVar, Vdbe::openedStatement, Vdbe::pc, Vdbe::rc, resolveP2Values(), sqlite3DbMallocZero(), SQLITE_OK, Vdbe::uniqueCnt, VDBE_MAGIC_INIT, and VDBE_MAGIC_RUN.
Referenced by sqlite3_blob_open(), sqlite3_reset(), and sqlite3FinishCoding().
int sqlite3VdbeRecordCompare (int , const void * , UnpackedRecord *)
Definition at line 2301 of file vdbeaux.c.
References UnpackedRecord::aMem, KeyInfo::aSortOrder, KeyInfo::db, Mem::db, KeyInfo::enc, Mem::enc, UnpackedRecord::flags, Mem::flags, getVarint32, KeyInfo::nField, UnpackedRecord::pKeyInfo, sqlite3MemCompare(), sqlite3VdbeMemRelease(), sqlite3VdbeSerialGet(), sqlite3VdbeSerialTypeLen(), UNPACKED_IGNORE_ROWID, UNPACKED_INCRKEY, UNPACKED_PREFIX_MATCH, and Mem::zMalloc.
Referenced by sqlite3BtreeMovetoUnpacked(), and sqlite3VdbeIdxKeyCompare().
UnpackedRecord* sqlite3VdbeRecordUnpack (KeyInfo * , int , const void * , UnpackedRecord * , int)
Definition at line 2206 of file vdbeaux.c.
References UnpackedRecord::aMem, d(), Mem::db, KeyInfo::db, KeyInfo::enc, Mem::enc, Mem::flags, UnpackedRecord::flags, getVarint32, UnpackedRecord::nField, KeyInfo::nField, UnpackedRecord::pKeyInfo, sqlite3DbMallocRaw(), sqlite3VdbeSerialGet(), sqlite3VdbeSerialTypeLen(), UNPACKED_NEED_DESTROY, UNPACKED_NEED_FREE, and Mem::zMalloc.
Referenced by sqlite3BtreeMoveto(), and sqlite3VdbeExec().
int sqlite3VdbeReset (Vdbe *)
Definition at line 1702 of file vdbeaux.c.
References Vdbe::aOp, Cleanup(), Vdbe::db, sqlite3::errCode, sqlite3::errMask, Vdbe::expired, Vdbe::magic, Vdbe::nOp, VdbeOp::opcode, Vdbe::pc, sqlite3::pErr, Vdbe::rc, sqlite3BeginBenignMalloc(), sqlite3DbFree(), sqlite3EndBenignMalloc(), sqlite3Error(), sqlite3SafetyOff, sqlite3SafetyOn, sqlite3ValueSetStr(), sqlite3VdbeHalt(), SQLITE_OK, SQLITE_TRANSIENT, SQLITE_UTF8, VDBE_MAGIC_INIT, and Vdbe::zErrMsg.
Referenced by sqlite3_reset(), and sqlite3VdbeFinalize().
void sqlite3VdbeResetStepResult (Vdbe *)
Definition at line 1687 of file vdbeaux.c.
References Vdbe::rc, and SQLITE_OK.
Referenced by sqlite3Reprepare().
void sqlite3VdbeResolveLabel (Vdbe * , int)
Definition at line 230 of file vdbeaux.c.
References Vdbe::aLabel, Vdbe::magic, Vdbe::nOp, and VDBE_MAGIC_INIT.
Referenced by analyzeOneTable(), generateOutputSubroutine(), generateSortTail(), multiSelect(), multiSelectOrderBy(), sqlite3CodeRowTrigger(), sqlite3DeleteFrom(), sqlite3ExprCodeTarget(), sqlite3ExprIfFalse(), sqlite3ExprIfTrue(), sqlite3GenerateConstraintChecks(), sqlite3Insert(), sqlite3Select(), sqlite3Update(), sqlite3WhereEnd(), and updateAccumulator().
int sqlite3VdbeSetColName (Vdbe * , int , int , const char * , void(*)(void *))
Definition at line 1214 of file vdbeaux.c.
References Vdbe::aColName, COLNAME_N, Vdbe::db, Mem::flags, sqlite3::mallocFailed, MEM_Term, Vdbe::nResColumn, sqlite3VdbeMemSetStr(), SQLITE_DYNAMIC, SQLITE_NOMEM, and SQLITE_UTF8.
Referenced by generateColumnNames(), generateColumnTypes(), returnSingleInt(), sqlite3DeleteFrom(), sqlite3Insert(), sqlite3Pragma(), sqlite3Prepare(), and sqlite3Update().
void sqlite3VdbeSetNumCols (Vdbe * , int)
Definition at line 1186 of file vdbeaux.c.
References Vdbe::aColName, COLNAME_N, Mem::db, Vdbe::db, db, Mem::flags, MEM_Null, Vdbe::nResColumn, releaseMemArray(), sqlite3DbFree(), and sqlite3DbMallocZero().
Referenced by generateColumnNames(), returnSingleInt(), sqlite3DeleteFrom(), sqlite3Insert(), sqlite3Pragma(), sqlite3Prepare(), and sqlite3Update().
void sqlite3VdbeSetSql (Vdbe * , const char * z, int n)
Definition at line 56 of file vdbeaux.c.
References Vdbe::db, sqlite3DbStrNDup(), and Vdbe::zSql.
Referenced by sqlite3Prepare().
void sqlite3VdbeSwap (Vdbe * , Vdbe *)
Definition at line 72 of file vdbeaux.c.
References Vdbe::nSql, Vdbe::pNext, Vdbe::pPrev, and Vdbe::zSql.
Referenced by sqlite3Reprepare().
void sqlite3VdbeUsesBtree (Vdbe * , int)
Definition at line 731 of file vdbeaux.c.
References sqlite3::aDb, Vdbe::aMutex, Vdbe::btreeMask, Vdbe::db, db, sqlite3::nDb, Db::pBt, and sqlite3BtreeMutexArrayInsert.
Referenced by sqlite3_blob_open(), sqlite3BeginTransaction(), sqlite3FindInIndex(), sqlite3FinishCoding(), sqlite3MinimumFileFormat(), sqlite3Pragma(), and sqlite3StartTable().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1