ContextLogger2 Logger Daemon Internals: vdbefifo.c File Reference
vdbefifo.c File Reference
Defines
#define FIFOSIZE_FIRST (((128-sizeof(FifoPage))/8)+1)
#define FIFOSIZE_MAX (((262144-sizeof(FifoPage))/8)+1)
Functions
static FifoPage * allocateFifoPage (sqlite3 *db, int nEntry)
void sqlite3VdbeFifoInit (Fifo *pFifo, sqlite3 *db)
int sqlite3VdbeFifoPush (Fifo *pFifo, i64 val)
int sqlite3VdbeFifoPop (Fifo *pFifo, i64 *pVal)
void sqlite3VdbeFifoClear (Fifo *pFifo)
Define Documentation
#define FIFOSIZE_FIRST (((128-sizeof(FifoPage))/8)+1)
Definition at line 25 of file vdbefifo.c.
Referenced by sqlite3VdbeFifoPush().
#define FIFOSIZE_MAX (((262144-sizeof(FifoPage))/8)+1)
Definition at line 29 of file vdbefifo.c.
Referenced by allocateFifoPage().
Function Documentation
static FifoPage* allocateFifoPage (sqlite3 * db, int nEntry) [static]
Definition at line 36 of file vdbefifo.c.
References FIFOSIZE_MAX, FifoPage::iRead, FifoPage::iWrite, FifoPage::nSlot, FifoPage::pNext, and sqlite3DbMallocRaw().
Referenced by sqlite3VdbeFifoPush().
void sqlite3VdbeFifoClear (Fifo * pFifo)
Definition at line 123 of file vdbefifo.c.
References Fifo::db, Fifo::pFirst, FifoPage::pNext, sqlite3DbFree(), and sqlite3VdbeFifoInit().
Referenced by Cleanup(), and sqlite3VdbeExec().
void sqlite3VdbeFifoInit (Fifo * pFifo, sqlite3 * db)
Definition at line 54 of file vdbefifo.c.
References Fifo::db.
Referenced by sqlite3VdbeExec(), and sqlite3VdbeFifoClear().
int sqlite3VdbeFifoPop (Fifo * pFifo, i64 * pVal)
Definition at line 90 of file vdbefifo.c.
References FifoPage::aSlot, Fifo::db, FifoPage::iRead, FifoPage::iWrite, Fifo::nEntry, FifoPage::nSlot, Fifo::pFirst, Fifo::pLast, FifoPage::pNext, sqlite3DbFree(), SQLITE_DONE, and SQLITE_OK.
Referenced by sqlite3VdbeExec().
int sqlite3VdbeFifoPush (Fifo * pFifo, i64 val)
Definition at line 64 of file vdbefifo.c.
References allocateFifoPage(), FifoPage::aSlot, Fifo::db, FIFOSIZE_FIRST, FifoPage::iWrite, Fifo::nEntry, FifoPage::nSlot, Fifo::pFirst, Fifo::pLast, FifoPage::pNext, SQLITE_NOMEM, and SQLITE_OK.
Referenced by sqlite3VdbeExec().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1