ContextLogger2 Logger Daemon Internals: walker.c File Reference
walker.c File Reference
Functions
int sqlite3WalkExpr (Walker *pWalker, Expr *pExpr)
int sqlite3WalkExprList (Walker *pWalker, ExprList *p)
int sqlite3WalkSelectExpr (Walker *pWalker, Select *p)
int sqlite3WalkSelectFrom (Walker *pWalker, Select *p)
int sqlite3WalkSelect (Walker *pWalker, Select *p)
Function Documentation
int sqlite3WalkExpr (Walker * pWalker, Expr * pExpr)
Definition at line 41 of file walker.c.
References Expr::pLeft, Expr::pList, Expr::pRight, Expr::pSelect, sqlite3WalkExpr(), sqlite3WalkExprList(), sqlite3WalkSelect(), WRC_Abort, WRC_Continue, and Walker::xExprCallback.
Referenced by exprIsConst(), sqlite3ExprAnalyzeAggregates(), sqlite3ExprCodeConstants(), sqlite3ResolveExprNames(), sqlite3WalkExpr(), sqlite3WalkExprList(), and sqlite3WalkSelectExpr().
int sqlite3WalkExprList (Walker * pWalker, ExprList * p)
Definition at line 60 of file walker.c.
References ExprList::a, ExprList::nExpr, sqlite3WalkExpr(), WRC_Abort, and WRC_Continue.
Referenced by resolveExprStep(), sqlite3WalkExpr(), and sqlite3WalkSelectExpr().
int sqlite3WalkSelect (Walker * pWalker, Select * p)
Definition at line 122 of file walker.c.
References Select::pPrior, sqlite3WalkSelectExpr(), sqlite3WalkSelectFrom(), WRC_Abort, WRC_Continue, and Walker::xSelectCallback.
Referenced by analyzeAggregatesInSelect(), resolveExprStep(), selectExpander(), sqlite3ResolveSelectNames(), sqlite3SelectAddTypeInfo(), sqlite3SelectExpand(), sqlite3WalkExpr(), and sqlite3WalkSelectFrom().
int sqlite3WalkSelectExpr (Walker * pWalker, Select * p)
Definition at line 77 of file walker.c.
References Select::pEList, Select::pGroupBy, Select::pHaving, Select::pLimit, Select::pOffset, Select::pOrderBy, Select::pWhere, sqlite3WalkExpr(), sqlite3WalkExprList(), WRC_Abort, and WRC_Continue.
Referenced by sqlite3WalkSelect().
int sqlite3WalkSelectFrom (Walker * pWalker, Select * p)
Definition at line 95 of file walker.c.
References SrcList::a, SrcList::nSrc, Select::pSrc, sqlite3WalkSelect(), WRC_Abort, and WRC_Continue.
Referenced by sqlite3WalkSelect().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:02 2011 by Doxygen 1.6.1