ContextLogger2 Logger Daemon Internals: window_demo_qt.cpp File Reference
window_demo_qt.cpp File Reference
Defines
#define MY_MAX_ROWS 100
Functions
void guilog (const QString &s)
void guilog (const char *s)
void guilogf (const char *fmt,...)
static void showFreeGerror (GError *error)
Variables
static QStringListModel * gModel = NULL
Define Documentation
#define MY_MAX_ROWS 100
Definition at line 25 of file window_demo_qt.cpp.
Referenced by guilog().
Function Documentation
void guilog (const char * s)
Definition at line 44 of file window_demo_qt.cpp.
References guilog().
void guilog (const QString & s)
Definition at line 31 of file window_demo_qt.cpp.
References gModel, and MY_MAX_ROWS.
Referenced by guilog(), guilogf(), main(), and QtMainE().
void guilogf (const char * fmt, ...)
Definition at line 49 of file window_demo_qt.cpp.
References guilog().
Referenced by CSensor_cellpos::BbChangedL(), CSensor_btprox::BtDiscover(), CSensor_callstatus::ChangedData_CallStatus(), CPosModuleStatAo::ChooseBestPositionerL(), CSensor_music::HandleMediaL(), CSensor_music::HandlePlaybackMessage(), CSensor_profile::HandleProfileActivatedL(), CSensor_indicator::HandleRead(), Sensor_tap::handleReadingChanged(), Sensor_proximity::handleReadingChanged(), Sensor_light::handleReadingChanged(), CSensor_btprox::HandleScanEventL(), CSensor_smsevent::LogEvent(), LogSatelliteInfoL(), main(), CSensor_cellpos::PositionerEventL(), CSensor_cellid::PostNewDataL(), QtMainE(), CSensor_appfocus::RunGL(), CSensor_inactivity::RunL(), and CSensor_httpurl::RunL().
static void showFreeGerror (GError * error) [static]
Definition at line 103 of file window_demo_qt.cpp.
References gx_error_free(), and gx_error_to_string().
Referenced by MainWindow::remokonNow(), and MainWindow::uploadNow().
Variable Documentation
QStringListModel* gModel = NULL [static]
Definition at line 27 of file window_demo_qt.cpp.
Referenced by guilog(), and MainWindow::MainWindow().
ContextLogger2—ContextLogger2 Logger Daemon Internals—Generated on Mon May 2 13:50:03 2011 by Doxygen 1.6.1